### ISSUE TITLE
Error on line 79

### ISSUE THREAD

**Issue by alexross19** [ecederstrand/exchangelib#1]
Hi,
 I am trying to list  cal event from my exchange account  on office365.
I simplified the code to just list  events, but its not working;
----------------------------------------------
from exchangelib import DELEGATE, services
from exchangelib.configuration import Configuration
from exchangelib.account import Account
from exchangelib.ewsdatetime import EWSDateTime, EWSTimeZone
from exchangelib.folders import CalendarItem

year, month, day = 2016, 5, 13
tz = EWSTimeZone.timezone('America/New_York')
calendar_items = []
config = Configuration(username='xxxx\xxxx', password='xxxxx')
account = Account(primary_smtp_address='xxxx@xxxx.xxx', config=config, autodiscover=True, access_type=DELEGATE)

ids = account.calendar.find_items(
    start=tz.localize(EWSDateTime(year, month, day)),
    end=tz.localize(EWSDateTime(year, month, day+1)),
    shape=services.IdOnly,
)
print(ids)
------------------- error ----------------------------

C:\Users\Alex\Desktop>python Python2ExchnageCal_v2.py
Traceback (most recent call last):
  File "Python2ExchnageCal_v2.py", line 1, in <module>
    from exchangelib import DELEGATE, services
  File "C:\Program Files (x86)\Python26\lib\site-packages\exchangelib\__init__.py", line 2, in <module>
    from .account import Account
  File "C:\Program Files (x86)\Python26\lib\site-packages\exchangelib\account.py", line 79
    raise ErrorFolderNotFound('No useable calendar folders') from e
                                                                ^
SyntaxError: invalid syntax

--------------------------------------------------------------------
 Thanks
Alex Ross

**Comment by ecederstrand** [comment]
Hi Alex,

exchangelib is Python3 only. The syntaks error is because "raise Foo from e" is not valid in Python2. I have no personale interest in Python2 but patches are welcome :-)

Erik

**Comment by alexross19** [comment]
Odd... Ok. That makes scene.
 My app requires Python 2.6
:(

Thanks for the fast reply!!
-Alex

**Comment by alexross19** [comment]
The app i am running  has some odd requirement, So it might come to that. :)

I could probably easy install Python 3  in a different dir tree & then call
the full path to Python 3  when i run the script.:)
humm...

Thanks
Alex

**Comment by ecederstrand** [comment]
That sounds like what virtualenv was created for 😀
