### ISSUE TITLE
Setting Categories on Emails

### ISSUE THREAD

**Issue by SteveTapajna** [ecederstrand/exchangelib#101]
New to Python, so hopefully this is something simple, however I can open my inbox using exchangelib, and move emails from the inbox to other folders successfully, however I cannot seem to be able to save changes to properties like:

message.isRead=False 

or

message.categories='Blue Category'

when I run message.save() with just the isRead setting changed, it doesn't seem to do anything, and when I try and change the category if I run in debug mode, and I read the result from the webservice, it complains with "The element 'Categories' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' cannot contain text. List of possible elements expected: 'String' in namespace  'http://schemas.microsoft.com/exchange/services/2006/types'"

Is this a problem with the version of Exchange?

Thanks,

Steve

**Comment by ecederstrand** [comment]
Hi,

`isRead` is spelled wrong. It's called `is_read`.

`categories` must be a list, so you should do this:

```python
message.categories=['Blue Category']
```

**Comment by SteveTapajna** [comment]
thanks, I saw that categories were displayed that way, but I thought I had to pass it as a string, so I quoted that string, I removed the outer quotes and now it works, along with the is_read.  My newness to python caused me to think that it was spelled OK, as it didn't complain when I tried to set that property (when it doesn't exist).  

Thanks and I'll close this issue.

Steve

**Comment by ecederstrand** [comment]
Great. There's code in HEAD to warn about assigning a wrong type to an attribute, so that'll be in the next release.

Regarding the not complaining, that's just how Python works :-) It's actually possible disable random attribute assignment with `__slots__`, but we explicitly need this functionality for extended properties to work.
