### ISSUE TITLE
Missing attendee in mime_content

### ISSUE THREAD

**Issue by lfasci** [ecederstrand/exchangelib#1013]
I tried to retrieve the list of calendar appontments using:

```python
appointments.values_list("mime_content", flat=True))
```

And I discovered that attendees are missed. 
Then I tried to dump the calendar item using the function

```python
for item in accountToMigrate.calendar.all()[:100]:
    dump(item)

def dump(obj):
   for attr in dir(obj):
       if hasattr( obj, attr ):
           print( "%s = %s" % (attr, getattr(obj, attr)))
```

the attendees are present in copy, save and other but not in mime_content.
I don't know if it's an Exchange or code problem I'm using the exchange version is 2010

**Comment by ecederstrand** [comment]
I don't know what led you to expect attendees to be available in the MIME data. It may be, but there are no guarantees.

Just use the [optional_attendees](https://ecederstrand.github.io/exchangelib/exchangelib/items/calendar_item.html#exchangelib.items.calendar_item.MeetingRequest.optional_attendees) and [required_attendees](https://ecederstrand.github.io/exchangelib/exchangelib/items/calendar_item.html#exchangelib.items.calendar_item.CalendarItem.required_attendees) attributes instead.

**Comment by lfasci** [comment]
Ok thank you
