### ISSUE TITLE
mail.detach attachment-> attachment not detached from the object message 

### ISSUE THREAD

**Issue by tinmarbusir** [ecederstrand/exchangelib#1016]
**Describe the bug**
I remove all attachments from a message.
When I send this message as attachment, The attachments of this attachment are still there!!!

**To Reproduce**
```python
def generate_mail_pj(account, mail_with_pjs):
	print("*** copy the mail to drafts")
	id, changekey = mail_with_pjs.copy(account.drafts)
	mail_to_modify = bal.drafts.get(id=id, changekey=changekey)
	
	print("*** delete all pjs")
	for attachment in reversed(mail_to_modify.attachments):
		mail_to_modify.detach(attachment)	
	print_infos("mail_pj", mail_to_modify)
	
	print("*** save")
	mail_saved = mail_to_modify.save()
	print_infos("mail_saved", mail_saved)
	
	print("*** must synchronize with Exchange!!!")
	mail_saved_2 = account.drafts.get(id=mail_saved.id, changekey=mail_saved.changekey)
	print_infos("mail_saved_2", mail_saved_2)
	
	return mail_saved_2

def send_mail(account, mail_pj):
	"""Erik, go to see in your Mailbox^^"""
	message = exchangelib.Message(
		account=account,
		subject="TEST ATTACHMENTS",
		body='Hi',
		to_recipients='erik@cederstrand.dk'
	)
	
	message.attach(exchangelib.ItemAttachment(name=mail_pj.subject, item=mail_pj))
	message.send()


def print_infos(mail_name, mail):
	print(f"{mail.changekey} ({mail_name})")
	print("has_attachments/ nb:", mail.has_attachments, len(mail.attachments))
	print()

if __name__ == "__main__":
	# mail = get_a_mail_with_attachments() # Take a mail from your account
	mail_attachment = generate_mail_pj(account, mail)
	send_mail(account, mail_attachment)
```

**Expected behavior**
I should not have to do 
mail_saved_2 = account.drafts.get(id=mail_saved.id, changekey=mail_saved.changekey)
The message object from exchangelib should not be different from what is in my account!

**Log output**
*** delete all pjs
CQAAABYAAAB71H3grTRASa1wTMEmlUzMAARB7UIA (mail_pj)
has_attachments/ nb: True 0

*** save
CQAAABYAAAB71H3grTRASa1wTMEmlUzMAARB7UIB (mail_saved)
has_attachments/ nb: True 0

*** must synchronize with Exchange!!!
CQAAABYAAAB71H3grTRASa1wTMEmlUzMAARB7UIB (mail_saved_2)
has_attachments/ nb: False 0

**Additional context**
Python 3.6.7
exchangelib==4.6.0

**Comment by ecederstrand** [comment]
The attachments aren't there. As you can see from the output, `len(mail.attachments)` returns 0 in all the print statements.

The confusion lies in the `has_attachments` field. This is a read-only field from the server. The new value is not fetched from the server when you attach/detach attachments. If you want to update the value from the server, you need to run `mail.refresh()` before printing the value of the field.
