### ISSUE TITLE
Incorrect minimum value for merged_free_busy_interval?

### ISSUE THREAD

**Issue by sricks** [ecederstrand/exchangelib#1019]
Current exchangelib version: 4.5.1. Apologies, I wasn't able to find release notes for 4.5.2 or 4.6 so maybe this is already resolved.

We are using the `account.protocol.get_free_busy_info()` method documented here:
https://ecederstrand.github.io/exchangelib/exchangelib/protocol.html#exchangelib.protocol.Protocol.get_free_busy_info

If I set a value that's too high, I get this error from EWS:

> The specified merged free/busy interval is not valid. Specify an interval that is less than the free/busy time window and  between 5 and 1440 minutes.

Which indicates that `5` is a valid value. But if I try setting `merged_free_busy_interval=5`, exchangelib gives me this error:

`ValueError: Value 5 on field 'merged_free_busy_interval' must be greater than 6`

It does work with `merged_free_busy_interval=6`, so it does actually work with intervals that are exactly 6, not greater than 6 like the error describes.

I'm not 100% clear if EWS supports an interval of 5, but Graph does, and I think EWS does too. Graph previously had  [incorrect documentation](https://github.com/microsoftgraph/microsoft-graph-docs/issues/6450) about this feature, maybe EWS also had wrong documentation which led to this limit?

**Comment by ecederstrand** [comment]
Thanks for filing this issue!

https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/mergedfreebusyintervalinminutes says "Six minutes is the minimum interval and one day (1440 minutes) is the maximum interval for this element."

I just tried changing the min value (https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/properties.py#L720) and tested that a value of 5 indeed works.

**Comment by ecederstrand** [comment]
I files https://github.com/MicrosoftDocs/office-developer-exchange-docs/pull/152 to have this fixed in the EWS docs.
