### ISSUE TITLE
Getting latest message body from a thread message - excluding previous replies

### ISSUE THREAD

**Issue by psmitak** [ecederstrand/exchangelib#1024]
Hi,

I am trying to search for some keywords from message body of emails and not in the appended replies. How to avoid searching on the appended replies? I tried searching in unique_body, but unique body also contains previous replies.
Is there any way to get the latest message body? Thanks.

**Comment by ecederstrand** [comment]
I don't think you can create a search that hits only the message and not the quoted text. After all, an email body is just plain text.

**Comment by ecederstrand** [comment]
Your best bet is probably to accept more hits in the initial search than you're interested in, and then do some additional client-side filtering by parsing the message body and determining where your keywords are located.

**Comment by psmitak** [comment]
Ok. Thanks.
