### ISSUE TITLE
folder subscription streaming broken

### ISSUE THREAD

**Issue by nburlett** [ecederstrand/exchangelib#1025]
The change to the `EWSService` base class in commit 803ce8f91b30e6c03ea1fdec74666bd2a7f31856  broke streaming for subscriptions. The folder's `GetStreamingEvents` class has `.streaming == False`

**To Reproduce**

The example code from the documentation shows the issue:

```python
for notification in a.inbox.get_streaming_events(
        subscription_id, connection_timeout=1
):
  ### this will hang waiting for connection_timeout because the underlying connection isn't streaming
  for event in notification.events:
    if isinstance(event, (MovedEvent, NewMailEvent)):
        # Do something
        pass
    elif isinstance(event, (StatusEvent, FreeBusyChangedEvent)):
        # Do something else
        pass
```

A sufficient fix is to set `self.streaming = True` in `exchangelib/services/get_streaming_events.py:GetStreamingEvents.__init__` after the `super` call.

**Comment by nburlett** [comment]
@ecederstrand , any chance of a bugfix 4.6.2 release with this commit?

**Comment by ecederstrand** [comment]
Sure, I just wanted to bring in the remaining improvements from https://github.com/ecederstrand/exchangelib/pull/999

I'll cut a release later today or tomorrow.

**Comment by ecederstrand** [comment]
https://pypi.org/project/exchangelib/4.6.2/
