### ISSUE TITLE
Recieving push notifications doesn't work

### ISSUE THREAD

**Issue by yogeshcodebase** [ecederstrand/exchangelib#1027]
**Describe the bug**
I am creating the Push notifications subscription for **account.calendar**. I got the subscription created. After that when I create/update any event in Outlook calendar, never received the notification request on given callback URL. 
I am following the example given here:
https://github.com/ecederstrand/exchangelib/issues/959

**To Reproduce**

```python
from datetime import datetime, timedelta
from time import sleep
from exchangelib import Account, Configuration, Credentials, CalendarItem

user, password = 'john@example.com', '********'
email = user
c = Configuration(credentials=Credentials(user, password))
a = Account(email, config=c, autodiscover=True, access_type=DELEGATE)
url='https://99f04f27b999.ngrok.io/exchange/webhook'

subscription_id, watermark = a.calendar.subscribe_to_push(callback_url=url)
sleep(60)
start = a.default_timezone.localize(datetime.now())
end = start + timedelta(hours=3)
item = CalendarItem(folder=a.calendar, subject='Hello subscription', start=start, end=end).save()

```

I have also tried:
```python
with a.calendar.push_subscription(callback_url=url) as (subscription_id, watermark):
     print(subscription_id)
     print(watermark)
```
It gives the same result. 

Request XML that has been sent on callback URL while creating subscription:
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap11:Envelope
    xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/">
    <soap11:Header>
        <t:RequestServerVersion
            xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" Version="Exchange2016"
            xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" />
        </soap11:Header>
        <soap11:Body>
            <m:SendNotification
                xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
                <m:ResponseMessages>
                    <m:SendNotificationResponseMessage ResponseClass="Success">
                        <m:ResponseCode>NoError</m:ResponseCode>
                        <m:Notification>
                            <t:SubscriptionId>JgBvczNwMjg2bWIyMjMxLmpwbnAyODYucHJvZC5vdXRsb29rLmNvbRAAAAB/2UPFk+DgT6XykR9ZSc+D6e89C+u+2QgQAAAA/n8DADEZuL8AAAAAAAAAAA==</t:SubscriptionId>
                            <t:PreviousWatermark>AQAAAFIgDU7rQFJNhTMBkTRqb9qVw5cBAAAAAAA=</t:PreviousWatermark>
                            <t:MoreEvents>false</t:MoreEvents>
                            <t:StatusEvent>
                                <t:Watermark>AQAAAFIgDU7rQFJNhTMBkTRqb9rbw5cBAAAAAAE=</t:Watermark>
                            </t:StatusEvent>
                        </m:Notification>
                    </m:SendNotificationResponseMessage>
                </m:ResponseMessages>
            </m:SendNotification>
        </soap11:Body>
    </soap11:Envelope> 
```

Also, one thing to note: When I create a subscription, it sends 3 requests to my server and the request body in those requests is exactly same. 
<img width="1234" alt="Screenshot 2021-12-14 at 4 53 33 PM" src="https://user-images.githubusercontent.com/85509967/145989326-1c420857-f79e-4fa9-8b40-6f5f51db21fa.png">

**Additional context:**
python: 3.7.10
exchangelib: 4.6.0
MS Exchange: 2016

**Comment by ecederstrand** [comment]
So, clearly the subscription is created correctly as the callback URL is called with a payload.

Does your local endpoint return an HTTP 201 response, like suggested in #959?

**Comment by yogeshcodebase** [comment]
Thanks for the response!

Yes, the endpoint returns HTTP 201 response. 
Right. Subscription is created but I never received the change notification request. 
Also, there are 3 subscriptions created every time which is odd.

**Comment by ecederstrand** [comment]
You can't unsubscribe a push subscription, so you probably just have 3 subscriptions registered on the server, some of them from your previous attempts.

I can't tell you why you're not receiving notifications for new events after the initial status event, but according tou https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/notification-subscriptions-mailbox-events-and-ews-in-exchange you have to acknowledge each push notification, so it's still my suspicion that you're either not doing that, or are creating events for something that the subscription does not cover.

**Comment by yogeshcodebase** [comment]
While creating push subscription, the server expects OK response from client. 
I added below response format to my client application and it started working.

```
<?xml version="1.0" encoding="UTF-8"?>
<soap11:Envelope
    xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soap11:Body>
        <m:SendNotificationResult>
            <m:SubscriptionStatus>OK</m:SubscriptionStatus>
        </m:SendNotificationResult>
    </soap11:Body>
</soap11:Envelope>
```

Note: Sending just 201 or 200 response code didn't work for me.

**Comment by ecederstrand** [comment]
Thanks for the update! I'll add this to the docs.

**Comment by ecederstrand** [comment]
Added support for creating the above response and updated documentation in https://github.com/ecederstrand/exchangelib/commit/8f7385d4628b06d53c1c5396eea4a9614cd5e86f

**Comment by yogeshcodebase** [comment]
Thanks!
