### ISSUE TITLE
Can't add attachment to forward or reply item

### ISSUE THREAD

**Issue by Gaabe** [ecederstrand/exchangelib#1028]
**Describe the bug**
When creating a forward or reply item and saving it, the returned object has no attach method.

**To Reproduce**
draft = email.create_forward(**self.kwargs).save(self.account.drafts)
attach = FileAttachment(name=attachment['filename'], content=f.read())
email.attach(attach)
draft.send()

**Expected behavior**
This should work as described in the docs

**Log output**
AttributeError: 'ForwardItem' object has no attribute 'attach'

**Additional context**
Python 3.6.11
exchangelib 4.6.0

**Comment by ecederstrand** [comment]
Thanks for the bug report! I've updated the docs with a working example now.
