### ISSUE TITLE
Possible to filter Roomlists?

### ISSUE THREAD

**Issue by warddebecker** [ecederstrand/exchangelib#103]
Hello,

I was wondering if it is possible to filter which rooms to check in a roomlists, this is what I am currently using:

```python
       for room in svc_account.protocol.get_rooms(item.email_address):
            room_account = Account(
                primary_smtp_address=room.email_address,
                credentials=creds,
                access_type=IMPERSONATION, #IMPERSONATION
                autodiscover = True
            )
            if((room.name.startswith("Room_6")) or (room.name.startswith("Room_5"))):
               #process the rooms....
```
The issue here is that I have a roomlist with 200-ish rooms, and with this method it always goes trough the whole list of rooms, and I filter it afterwards, and it takes 1-2seconds for each room.
So the question is, can I filter it in a way so it only goes through the rooms that I actually need so the script wont take multiple minutes to finish?

Thanks in advance

**Comment by ecederstrand** [comment]
In your example, you aren't actually using `room_account` for anything. Can you explain why you're creating that account for each room?

The `GetRooms` service doesn't allow for filtering server-side (see https://msdn.microsoft.com/en-us/library/office/dd899454(v=exchg.150).aspx), so `get_rooms()` is going to return the 200 rooms regardless.

**Comment by warddebecker** [comment]
I use the `room_account` to get meeting information from the calendar's of the rooms with the impersonation rights.

And do you know any way of making the `get_rooms` go any faster? I don't mind a bit of a delay, but if it has to go trough all those rooms its a bit much.

**Comment by ecederstrand** [comment]
You need to find out where the time is being spent. I assume it's when `room_account` is created, due to the autodiscover lookup, but it would be better to know for sure.

You could start by deferring the `room_account` creation to within the `if` clause, if you're only going to process the filtered rooms. If you *do* need to make autodiscover lookups for 200 rooms, then you'll have to wait for that. There's not much we can do there. But you can disable or cache autodiscover results, as described in https://github.com/ecederstrand/exchangelib#setup-and-connecting That should speed things up.

**Comment by ecederstrand** [comment]
Also, EWS has a `GetUserAvailability` service that we don't support yet, but which you might be able to use for this type of request: https://www.google.dk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwiZp4XsuOrSAhVnJ8AKHWmxD_4QFggjMAE&url=https%3A%2F%2Fmsdn.microsoft.com%2Fen-us%2Flibrary%2Foffice%2Faa564001(v%3Dexchg.150).aspx&usg=AFQjCNFCuU0VthVFtJM3X4aU2mGwRrQueQ&cad=rja

This does not involve autodiscovering the user you want to query.

**Comment by warddebecker** [comment]
I'll test the autodiscover caching probably tomorrow,

And the `GetUserAvailability ` does look interesting, but it support a max of 100 mailboxes in a distributionlist.

**Comment by ecederstrand** [comment]
Yeah, to use `GetUserAvailability` in your case, you would need to query the rooms directly, and batch the requests in chunks of 100.

**Comment by warddebecker** [comment]
Sorry for leaving this open so long, but I've been quite busy.
I placed the account inside the if like you said to make it run a lot faster.
I also tried to use the discovery caching, but this didn't seem to do a lot (might have been doing something wrong).
But for the moment it runs 'ok', would like to make it a bit faster still but its acceptable now.

Thanks for the help

**Comment by ecederstrand** [comment]
No problem. If you set the `auth_type` and `version` explicitly on the `Configuration` object, then you shouldn't be hitting the server at all when creating the `Account` or `Configuration` object. Otherwise it's a bug.
