### ISSUE TITLE
Mail Body is Messed up with HTML

### ISSUE THREAD

**Issue by ConMan05** [ecederstrand/exchangelib#1036]
**Describe the bug**
I was trying to get 341 mails for a particular date [14-01-2022] from a shared mailbox. When I was running for 341 mails on particular date I get messed up HTML in body for 72 mails[example attached below Description]. When I tried running with just that  72 mails seperately , I was getting a proper HTML body.

This issue occured only on this date till I observed.
I tried running 341 mails from the same date thrice but the exchange server itself returns html like this, but when I tried to run for the 72 mails seperately It returns the HTML body in a right manner. 

EXAMPLE :
____________________________________________________________________________________________________________________________________________
htmlhead\r\nmeta http-equiv="Content-Type" content="text/html; charset=utf-8"meta name="Generator" 
content="Microsoft Exchange Server"!-- converted from rtf --style!-- .EmailQuote { margin-left: 1pt; 
padding-left: 4pt; border-left: #800000 2px solid; } --/style/headbodyfont face="Calibri" size="2"span 
style="font-size:11pt;"divHello/divdivnbsp;/divdiv3 I just need to ask you about the quote 
/divdivdelivery is delayed/divdivThanks/divdivnbsp;/divdivfont 
color="red"bWE ARE OPEN. /bfont color="black"b/b/font/font/divdivbConsult our website for the latest 
updates: /ba href="http://abc.com/updates"font color="blue"uhttp://abc.com/updates//u/font/a/divdivfont 
color="#1F497D"nbsp;/font/divdivfont color="#1F497D"Please let me know if there is anything else I can help 
you with.nbsp; Many thanks for choosing us/font/divdiv style="margin-top:5pt;margin-bottom:5pt;"font 
face="Arial" size="3" color="#1F497D"span style="font-size:12pt;"biNEED OPTIONS? /i/b/span/font/divdiv 
style="margin-top:5pt;margin-bottom:5pt;"font face="Arial" color="#1F497D"bWe offer:nbsp;  
Ask our dedicated team. /b/font/divtable width="600" 
style="width:360pt;margin-left:5.4pt;"col width="218" style="width:131.25pt;"col width="381" 
style="width:228.75pt;"tbodytrtda href="http://www.groupmtl.com/"img 
src="image007.png"/a divfont color="#1F497D"nbsp;/font/divdivimg src="image008.png"
/divdivfont color="#444444"nbsp;/font/divdivimg src="image011.jpg"
/div/tdtdtable width="376" style="width:225.85pt;"col width="376" style="width:225.85pt;"
tbodytrtdfont face="Arial" size="3" color="#3D3C3F"span style="font-size:12pt;"
bBlack Berry/b/span/font/td/trtrtdfont face="Arial" size="2" color="#3D3C3F"span 
style="font-size:10pt;"Director/span/font/td/trtrtdfont face="Arial" size="1" color="#3D3C3F"span 
style="font-size:8pt;"/b/span/font/td/trtrtdfont face="Arial" size="2" color="#1F497D"span 
style="font-size:10pt;"bVISIT US ONLINEnbsp;nbsp; /ba href="http://www.google.com/"font color="blue"buwww.google.com/u/b/
font/ab /b/span/font/td/trtrtdfont face="Arial" size="2" color="#9B9B9B"span style="font-size:10pt;"
bphone: /bfont face="Calibri" color="#1F497D"bnbsp;/b/fontb(514) 731-7020 x235/b/span/font/td/trtrtdfont 
face="Arial" size="2" color="#9B9B9B"span style="font-size:10pt;"bmobile: (514)/bfont color="#1F497D"b 
/b/fontb649-6120/b/span/font/td/trtrtdfont face="Arial" size="2" color="#9B9B9B"span style="font-size:10pt;
"bemail:/bfont face="Calibri"nbsp;/fonta href="berry@google.com"font color="blue"uberry@google.com/u/font
/a/span/font/td/trtrtdfont face="Arial" size="2" color="#9B9B9B"span style="font-size:10pt;"nbsp; nbsp; 
/span/font/td/trtrtdfont color="#9B9B9B"/font/td/trtrtd/td/tr/tbody/tabledivfont size="2" 
color="#1F497D"span style="font-size:10pt;"l\' /b/span/font/divdivfont size="1"span style="font-size:8pt;
"bnbsp;nbsp;nbsp;/bfont face="Arial"b n\'/b/font/span/font/divdivfont size="1"span 
style="font-size:8pt;"bnbsp;nbsp;nbsp;/bfont face="Arial"d\' l\'\ d\'\/b/font/span/font/divdivfont
size="1"span style="font-size:8pt;"bnbsp;nbsp;/bfont face="Arial"bd\'/b/font/span/font/divdivfont
size="1"span style="font-size:8pt;"bnbsp;nbsp;/bfont face="Arial"b /b/fontfont face="Arial"brnbsp;nbsp;
/b/font/span/font/divdivfont size="1"span style="font-size:8pt;"bnbsp;nbsp;/bfont face="Arial"b/b/font/
span/font/divdivfont size="1"span style="font-size:8pt;"bnbsp;nbsp;/bfont face="Arial"b /b/font/span/font
/divdivfont color="#1F497D"nbsp;/font/divdivnbsp;/divdivnbsp;/divdivnbsp;/div/span/fonttable 
class="x_-427151271MsoNormalTable" style="width: 700pt; background: red; border-style: solid;"
border="0" width="700pt" cellspacing="0" cellpadding="0"tbodytrtd style="padding: 0.75pt 0.75pt 
0.75pt 0.75pt;"p style="text-align: center;" align="center"span style="font-size: 9.0pt; font-family: 
Arial, sans-serif; color: white;"./span/p/td/tr/tbody/table/body/html
____________________________________________________________________________________________________________________________________________

**To Reproduce**
```python
utc = EWSTimeZone('UTC')
credentials = Credentials(conman@myorg.com, password)
config = Configuration(server='outlook.office365.com', credentials=credentials)
shared_account = Account('sharedmailbox@myorg.com', config=config, autodiscover=False, access_type=DELEGATE, default_timezone=utc)
start = datetime(start_Year,start_Month,start_Date, tzinfo=shared_account.default_timezone)
end = start + timedelta(days=1)
fetch_condition = list(shared_account.inbox.filter(is_read=False,datetime_received__gte=start,datetime_received__lt=end))
for msg in fetch_condition:
            msg.is_read=True
            msg.save(update_fields=['is_read'])
            #Below this I'm using beautifulsoup to parse html and just get text from the html.
```

**Expected behavior**
It should return Proper HTML so that it can be parsed to beautifulSoup and text can be retrived.

**Additional context**
Python Version - 3.8.10
Exchangelib Version - 4.5.1
OS - ubuntu 20.04.2 LTS

**Comment by ecederstrand** [comment]
First of all, it's a bit dangerous to change messages while you're iterating over them. Since `filter()` does paging behind the scenes, items are fetched on-demand as you iterate over `fetch_condition`. It's like modifying a list in Python while iterating over it, which is not a good idea. An alternative would be to collect the item IDs you want to update, and then update them afterwards with `Account.bulk_update()`. If you do want to use `msg.save()`, then do so in combination with `update_fields` to avoid writing back unnecessary field values: `msg.save(update_fields=['is_read'])`.

Regarding the weird HTML, it's difficult to say what's wrong. Your best bet is to enable [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and look at the raw values being returned from the server. You can cut down on the amount of data to look through if you limit the number of fields to fetch with `fetch_condition.only('body')`. If the Exchange server indeed returns broken HTML, there's nothing exchangelib can do  about it.

**Comment by ConMan05** [comment]
Hey @ecederstrand,
I have updated the code.
But I'm getting proper HTML if I run for those 72 mails particularly. but when I try to run them with those 341 mails[Mails for the whole day including 72 mails]. I'm getting broken HTML.
I'll enable debug logging and see what's happening.

**Comment by ConMan05** [comment]
can I use msg.text_body instead of msg.body for all mails ???
will it work for all mails ???

**Comment by ecederstrand** [comment]
The `text_body` field was introduced in Exchange 2013. It's a best-effort attempt by the Exchange server to convert HTML emails to plain text. If it works for your use case, then feel free to use it instead of parsing the HTML body.
