### ISSUE TITLE
AppointmentState mismatch with Microsoft Documentation

### ISSUE THREAD

**Issue by douglassimonsen** [ecederstrand/exchangelib#1040]
**Describe the bug**
In exchangelib's [implementation](https://github.com/ecederstrand/exchangelib/blob/0dd62d7fd881b164bc8edbf7dac4d75bd16eb2d4/docs/exchangelib/fields.html#L571-L580) of AppointmentState, one of the elements is spelled "Cancelled", whereas Microsoft's [documentation](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/appointmentstate) spells it without the 2nd "l".

**Expected behavior**
The expected behavior is to match Microsoft documentation

**Comment by ecederstrand** [comment]
Thanks for the report!
