### ISSUE TITLE
ErrorItemCorrupt causes whole iteration to fail

### ISSUE THREAD

**Issue by mlaricheva** [ecederstrand/exchangelib#1041]
Hi there! I saw this closed issue ( #870 ) which seems very similar to the experience I had while trying to collect all events from a folder (several shared calendars in my case). Some items apparently were broken which raised the ErrorItemCorrupt error and stopped the loop. I fixed it the same way, as in #870, by adding ErrorItemCorrupt to the ERRORS_TO_CATCH_IN_RESPONSE list on my end. I was wondering if you think that's a good idea to add that error there permanently?

**Comment by ecederstrand** [comment]
Thanks for the report! I agree `ErrorItemCorrupt` should be caught and passed to the caller.
