### ISSUE TITLE
How I process the email with it timestamp?

### ISSUE THREAD

**Issue by shaikhsaqib321** [ecederstrand/exchangelib#1044]
I want to process the emails from a specific DateTime timestamp. 
I will be storing the last processed email timestamp in the file or database and when next time I run the job it should do all the emails greater than that timestamp.

Sorry if it sounds confusing.
For example, if the last email processed timestamp is (2022-02-5 02:24:52)

I want to process all the emails that came after this timestamp.
Can anyone please advice or help me with this?

**Comment by ecederstrand** [comment]
You can filter emails by timestamp. You'll just have to decide which timestamp field you want to filter on. Probably `datetime_received` is the most suitable field in your case:

```python
account.calendar.filter(
    datetime_received__gt=datetime.datetime(2022, 1, 31, tzinfo=account.default_timezone),
)
```

**Comment by shaikhsaqib321** [comment]
Awesome Thanks @ecederstrand, that helped!

Clone:
https://stackoverflow.com/questions/70995341/process-email-from-timestamp-great-than-provided-using-exchangelib
