### ISSUE TITLE
Ability to filter on empty categories

### ISSUE THREAD

**Issue by yampelo** [ecederstrand/exchangelib#105]
Hi,

Currently you cannot filter on an empty category. doing

`.all().filter(categories=None)` throws an error, is it possible to add this?

**Comment by ecederstrand** [comment]
`categories` is a list or strings, so a more correct filter expression would be:

```python
.filter(categories=[])
```

But I'm not sure it's actually possible to express this query using the EWS restrictions syntax: https://msdn.microsoft.com/en-us/library/office/aa563791(v=exchg.150).aspx

You may have luck with the `Exists` operator, but it's not supported in exchangelib yet.

**Comment by yampelo** [comment]
The above doesn't work because the value for categories is actually `None` and not an empty list

**Comment by ecederstrand** [comment]
For list types in exchangelib, `[]` and `None` are treated equal for simplification reasons. It's not an EWS distinction. So don't worry too much that `categories` is `None` on your item.

`None` is forbidden as a value in a filter expression since it doesn't have an equivalent in the EWS restrictions syntax.

**Comment by ecederstrand** [comment]
I implemented the `Exists` operator in https://github.com/ecederstrand/exchangelib/commit/4e59e47ed4224f625324e88c627fd8b8698e93e6, which seems to do what you want.

```python
for i in some_folder.filter(categories__exists=True):
    print(i.categories)  # Should print a non-empty list

for i in some_folder.filter(categories__exists=False)
    print(i.categories)  # Should print None
```
