### ISSUE TITLE
Detach attachments with digital signature

### ISSUE THREAD

**Issue by xNykram** [ecederstrand/exchangelib#1061]
**Describe the bug**

Hi,

I want to detach all attachments from email which has digital signature. Unfortunately, instead of a list of attachments, the following code prints only one FileAttachment object which is signature (name='smime.p7m, content_type='multipart/signed''). 

**To Reproduce**

Email with attachments and digital signature.

```
attachments = [attachment for attachment in item.attachments]
for attachment in attachments:
    print(attachment)
```

**Expected behavior**

All attachments should be printed,  then I can detach attachments.

**Additional context**

I cannot remove the signature because the email will be corrupted. 
All attachments are not empty.

If you need more information, please let me know. 

Thanks.

**Comment by ecederstrand** [comment]
It's probable that EWS only delivers one attachment in this case. If you enable debug logging, you can have a look at the actual XML document returned by the API to see if that's the case: https://ecederstrand.github.io/exchangelib/#troubleshooting

It's not clear to me from your description of the email is encrypted or just signed. Anyway, it could be that your attachments are not delivered as EWS Attachment objects but are instead contained in the MIME content of the email. This data is contained in the `Message.mime_content` field.

**Comment by ecederstrand** [comment]
exchangelib doesn't do that for you, but https://docs.python.org/3/library/email.parser.html knows how to parse MIME. There are examples on e.g. StackOverflow on how to extract attachments from MIME content.

**Comment by xNykram** [comment]
Thanks for help. Issue can be closed.
