### ISSUE TITLE
OAuth does not work with non-default authority hosts

### ISSUE THREAD

**Issue by j18ter** [ecederstrand/exchangelib#1063]
Followed instructions for OAuth, but get this error:
`(invalid_request) AADSTS900382: Confidential Client is not supported in Cross Cloud request.`

Online discussions for other software suggest this happens when the authority host is
hard-coded to `https://login.microsoftonline.com`. For some customers of Outlook 365
this must be changed, e.g., to `https://login.microsoftonline.us`.

I tried setting environment variable AZURE_AUTHORITY_HOST, but this didn't help. I see two
places in the exchangelib source code where `https://login.microsoftonline.com` is hard-coded.
Might this be the problem?

**Comment by ecederstrand** [comment]
I don't have any experience with OAuth myself, unfortunately. The easiest way to find out is to just change those two URLs yourself and try whether that allows you to login..

**Comment by j18ter** [comment]
Thanks for the suggestion. Changing these URLs helped with this failure. I got beyond that error, but then something else goes wrong later with a 503 error when trying to get an access token. I have zero experience with OAuth and Office 365 too, and in my case it now involves MFA. I will next try if I can find an alternative library with better documented procedures for the Microsoft 365 Government variant, as I'm not very confident that I can debug this myself. Exchangelib has worked well for me, but now my employer's introduction of MFA has thrown me a curve ball.

**Comment by ecederstrand** [comment]
@j18ter Did you find a solution to this issue?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional information.
