### ISSUE TITLE
Help with OAuth

### ISSUE THREAD

**Issue by id-hkj** [ecederstrand/exchangelib#1065]
This may not be the right place to ask this (sorry!), but I'm having trouble with OAuth authentication. I've written a program to get emails and output data in a spreadsheet, but it uses the authentication with the email and password. I believe from October 1, 2022, this will no longer work (as I think it is basic authentication). This is from the following article:[https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#when-will-this-change-take-place](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#when-will-this-change-take-place)
That leads me onto my problem - I can not figure out how to authenticate in OAuth (using exchangelib) and then how to access the emails (would the later be the same as the way without OAuth?).
I was originally using the o365 module, but that couldn't download attachments (at least from what I had found it couldn't).

I would appreciate it if someone could help.
Thank you in advance.

Edit: I have looked at the documentation, but can not really figure anything out

**Comment by id-hkj** [comment]
In case this helps, with this code:

```
from exchangelib import *
try:
    BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
    cred = OAuth2Credentials(client_id='xxx', client_secret='xxx', tenant_id='xxx')
    config = Configuration(server='outlook.office.com',credentials=cred, auth_type=OAUTH2)
    account = Account(primary_smtp_address='example@outlook.com', credentials=cred, config=config, autodiscover=False, 
 access_type=DELEGATE)

except Exception as e:
    print(str(e))
    print('Unknown failure')
```

I get this error:

```Account None: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\protocol.py", line 196, in get_session
    session = self._session_pool.get(block=False)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 246, in _get_elements      
    yield from self._response_generator(payload=payload)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 208, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 332, in _get_response_xml  
    r = self._get_response(payload=payload, api_version=api_version)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\services\common.py", line 282, in _get_response
    session = self.protocol.get_session()
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\protocol.py", line 200, in get_session
    self.increase_poolsize()
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\protocol.py", line 170, in increase_poolsize
    self._session_pool.put(self.create_session(), block=False)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\protocol.py", line 263, in create_session
    session = self.create_oauth2_session()
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\exchangelib\protocol.py", line 335, in create_oauth2_session
    token = session.fetch_token(token_url=token_url, client_id=self.credentials.client_id,
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '078e63ce-74dd-4a74-8f08-7cd14fb8bfd8'.
Trace ID: 9d617694-b114-4fd2-894c-df625bc15a00
Correlation ID: 1f3cb1d9-5653-4dc8-813e-ecef9481aba6
Timestamp: 2022-03-06 18:13:29Z

(invalid_client) AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '078e63ce-74dd-4a74-8f08-7cd14fb8bfd8'.
Trace ID: 9d617694-b114-4fd2-894c-df625bc15a00
Correlation ID: 1f3cb1d9-5653-4dc8-813e-ecef9481aba6
Timestamp: 2022-03-06 18:13:29Z
Unknown failure```

**Comment by ecederstrand** [comment]
I don't have any experience with OAuth myself, unfortunately. Have you checked the recommendation in the error message? `Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '078e63ce-74dd-4a74-8f08-7cd14fb8bfd8'`

**Comment by id-hkj** [comment]
I've fixed that, and have got a new error:

'''
C:\Users\Avi\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'outlook.office.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Invalid credentials for https://outlook.office.com/EWS/Exchange.asmx
Unknown failure
'''

I have looked at the credentials I gave, but can not find anything wrong

**Comment by jbh-cloud** [comment]
@id-hkj I was getting the same errors as you but realized that I had permissioned my OAuth app to use MS Graph whereas Exchangelib appears to connect directly to the Exchange API.

![image](https://user-images.githubusercontent.com/72975077/161065153-f7bf7b21-4648-4947-af78-81314234a86e.png)

**Comment by ecederstrand** [comment]
@jbh-cloud Thanks for the screenshot! I have just tried registering an app on O365 and granted it the above permissions, and can confirm that I can now log in using OAuth using the app tokens.

**Comment by RossK1** [comment]
For those having a hard time finding this permissions, it doesn't always show up in the commonly used APIs.
So after selecting "Add a permission", select the "APIs my organization uses" tab and type in "office 365 exchange online".
![image](https://user-images.githubusercontent.com/75049118/169883301-a12e853f-4974-4b04-bd94-a370aef75940.png)
After that, select "Application permissions" and you will find the "full_access_as_app" under "Other permissions".
![image](https://user-images.githubusercontent.com/75049118/169883451-5354db2b-3de6-4e70-8d98-951fd2af9631.png)

**Comment by ecederstrand** [comment]
@RossK1 Thanks for these screenshots! Where are they from?

I recently switched the test account used in this project to O365 and added a small guide in the docs: https://ecederstrand.github.io/exchangelib/#oauth-on-office-365 Those screenshots are from the Azure AD admin interface.

**Comment by RossK1** [comment]
@ecederstrand These are from the same Azure AD interface. It's the right-side panel that appears when you click the "+ Add a permission" button. It just took me longer than it should have to find the permission, so figured I'd save others the hunt :)

**Comment by ecederstrand** [comment]
Thanks. I'd be happy to accept a PR against the docs :-)
