### ISSUE TITLE
Is there any a way to get an exception while sending a message to non existent mail address?

### ISSUE THREAD

**Issue by RuthiCohen** [ecederstrand/exchangelib#1070]
Hi, 
Im using python & exchangeLib in order to send a message between users outlook accounts.
The thing is that I get an error mail to my account when sending to an invalid mail but don't get any exception in my script..

is there any a way to get the exception in the code ?

Thanks in advance!

**Comment by ecederstrand** [comment]
That depends on whether that account is in the same or a different organisation. The SMTP protocol does not guarantee this sort of feedback, and the send functionality in EWS does not relay it if the remote server does tell you about unknown email adresses. If you're sending email to external parties, then your only option is to wait for an error email.

For internal accounts, you can use the [resolve_names()](https://ecederstrand.github.io/exchangelib/#non-account-services) method to look up email addresses. The server will tell you which addresses are invalid.

**Comment by RuthiCohen** [comment]
Yes! resolve_names() is exactly what I need.
Thank you!
