### ISSUE TITLE
How to read emails in a shared inbox with a service account 

### ISSUE THREAD

**Issue by misasa07** [ecederstrand/exchangelib#1071]
Hello,

I'm trying to read emails in a shared inbox with a service account. However the following error was triggered.

When making a request as an account that does not have a mailbox, you must specify the mailbox primary SMTP address for any distinguished folders IDs.

I set up the primary SMTP address in Account class as below:
```python
access_type: str = EWS. DELEGATE
credentials = EWS. Credentials(username='serviceaccount@example.com', password ='password') 
Config = EWS. Configuration (
service_endpoint='xxxx',
auth_type='NTLM',
credentials =credentials 
) 
EWS.Account(primary_smtp_address='shared email address', config,=config, access_type=accress_type, autodiscover=False)
```

I can count emails in the inbox and send emails from the account with the service account. 

I can also read emails in the shared inbox using my own email address. 

It is failing in reading emails with the service account only. 

If you could provide some your insights on this issue, that would be really appreciated. 

Thank you.

**Comment by ecederstrand** [comment]
For service accounts, you probably need to switch to the `IMPERSONATION` access type instead of `DELEGATE`

**Comment by misasa07** [comment]
I've tried with IMPERSONATION access type too. However, this error came back:
The SMTP address has no mailbox associated with it.

The service account does not have a mailbox so that's why the shared inbox was assigned as primary SMTP address.

Any idea on this error?

Thank you.

**Comment by Korenaga86** [comment]
I'm having the same issue (or might be making the same mistake). It doesn't seem to be a permissions issue as I am allowed to retrieve the folder structure by calling `account.root.tree()` and in addition I can also retrieve the number of items in a folder, for instance `account.inbox.total_count` gives me the total number of mails in the inbox. 

Sadly when I try to retrieve an email I get the same errors as **misasa07** (with DELEGATE and IMPERSONATION) and I'm at a loss what is happening exactly. Can we assist by sharing the DEBUG logging? 

I read (and see) that this can be enabled by adding the following snippet:
```
import logging
from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
```

**Comment by ecederstrand** [comment]
@misasa07 Did you find a solution to your problem? I'm seeing other places that you may need to connect with DELEGATE access anyway. Has the service user been explicitly granted access to the shared inbox?

**Comment by misasa07** [comment]
Unfortunately there is no change. I have reached out to our IT several
times on this. they did confirmed the service user is granted access to the
shared inbox.
I CAN count emails or send emails with the service account, but read
emails.

**Comment by ecederstrand** [comment]
Ok. I'll close the issue, then. Feel free to reopen if you have any updates to this.
