### ISSUE TITLE
Reading inbox items with client secret 

### ISSUE THREAD

**Issue by TanjilAmin** [ecederstrand/exchangelib#1073]
I am using the following code to access a shared inbox: 

```python
from exchangelib import OAuth2Credentials

credentials = OAuth2Credentials(
  client_id=client_id, client_secret=client_secret, tenant_id=tenant_id
)

from exchangelib import DELEGATE, Account, Credentials, Configuration
 config = Configuration(server='outlook.office365.com', credentials=credentials)

account = Account(primary_smtp_address = 'userid@company.com', 
                  config = config, 
                  autodiscover = False,
                  access_type = DELEGATE
                  )
```

However, I am getting the following error: _Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx_

I have checked the app info many times and keep getting the same error. Any ideas?

**Comment by ecederstrand** [comment]
Please post the full stack trace. That could tell us why it's failing.

Can you connect to other accounts than the shared account?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional information.

**Comment by TanjilAmin** [comment]
I suspect this failure has to do with newly implemented multi-factor authentication.
