### ISSUE TITLE
exchangelib.errors.UnauthorizedError: Invalid credentials

### ISSUE THREAD

**Issue by RuthiCohen** [ecederstrand/exchangelib#1079]
Hi,
I'm using `exchangeLib` in python & when I try to connect my outlook exchange account I get this error
`exchangelib.errors.UnauthorizedError: Invalid credentials for https://{my exchange server}`
the thing is that I could connect 30 min before I got this error.

Any help would be appreciated!
Thank you.

**Comment by ecederstrand** [comment]
Authorization issues are almost impossible to debug on a public list. But if you were able to log in previously and you didn't change any code, then it doesn't seem like an issue with exchangelib.
