### ISSUE TITLE
Endless connection loop in case of wrong password

### ISSUE THREAD

**Issue by sharon8811** [ecederstrand/exchangelib#108]
I Tried to use account with autodiscover if the username and primary smtp address are correct but the password is wrong it will be stuck forever on retries (waited one hour and the process still did not finish).
it seems the discover method in autodiscover is recursive and increasing timeout every retry maybe it will hit stuck overflow but only after a very long time because of the increasing timeout.

**Comment by ramwin** [comment]
set `is_service_account = False` when you create the credentials.

**Comment by ramwin** [comment]
Maybe you are meeting the same problem like [this](https://github.com/ecederstrand/exchangelib/issues/57)

**Comment by ecederstrand** [comment]
@ramwin has the right solution. This will be the default in the next release, and `is_service_account` is deprecated in favour of a dedicated `ServiceAccount` class.

**Comment by sharon8811** [comment]
Thanks works as expected.
but for some reason i trying to connect to a correct account with wrong password and i get nonexistent domain (in AutoDiscoverFailed exception message)

**Comment by ecederstrand** [comment]
Yes, this is an artifact of the autodiscover protocol. There's a sequence of domain names the protocol will send autodiscover requests to, and it continues to the next domain name if anything fails. I think you'll get the same misleading diagnosis if you attempt on with https://testconnectivity.microsoft.com/

**Comment by sharon8811** [comment]
OK, thank you

**Comment by ecederstrand** [comment]
I improved the 'nonexistent domain' error message in https://github.com/ecederstrand/exchangelib/commit/69bf7978b4e23da8b3a4b0c1062868f35a2d19a6
