### ISSUE TITLE
Example for GetFolder service

### ISSUE THREAD

**Issue by iglimanaj** [ecederstrand/exchangelib#1086]
I have tried out many ways for calling the `GetFolder` service, but none of them was successful. Unfortunately, I also couldn't find any easy to use examples in the documentation.

Given is an account (of type `Account`) object and the mailfolder id (of type string) of the folder I am interested in. The use case I want to support is to find the mailfolder name for a given a mailfolder id. I would be happy, if anybody can propose other ways instead of `Get Folder`

**Comment by iglimanaj** [comment]
In the following there is the code (with some dummy values) I have tried so far without success. 

```
from exchangelib import Configuration, Credentials, DELEGATE,  Account\
from exchangelib.folders import DistinguishedFolderId

account_email = "test@email.com"
user_password = "test_password"
server = "https://exchange.email.com"
mailfolder_id = "test_mailfolder_id"


credentials = Credentials(username=account_email, password=user_password)
config = Configuration(server=self.server, credentials=credentials)
account = Account(
               primary_smtp_address=account_email, config=config,
               autodiscover=False, access_type=DELEGATE
             )
folder_obj = DistinguishedFolderId(id=mailfolder_id)
folders_gen = GetFolder(account=account).call(folders=[folder_obj], additional_fields='ChildFolderCount', shape='Default')
folders_list = [f for f in folders_gen]
```

The last line produces the following error:

`exchangelib.errors.ErrorInvalidSchemaVersionForMailboxVersion: Tried versions ('Exchange2016', 'Exchange2019', 'Exchange2015_SP1', 'Exchange2015', 'Exchange2013_SP1', 'Exchange2013', 'Exchange2010_SP2', 'Exchange2010_SP1', 'Exchange2010', 'Exchange2007_SP1', 'Exchange2007') but all were invalid
`

**Comment by ecederstrand** [comment]
To look up a folder by EWS ID, you can use the `SingleFolderQuerySet` class. It's not part of the official API, but it's not going away. `DistinguishedFolderId` is only for distinguished folders, and those should all have shortcuts on the `Account` class. See https://ecederstrand.github.io/exchangelib/exchangelib/account.html

```python
from exchangelib.folders import SingleFolderQuerySet, FolderId

some_folder = SingleFolderQuerySet(account=some_account, folder=FolderId(id=...)).resolve()
```

**Comment by iglimanaj** [comment]
@ecederstrand It works like a charm. Than you!

**Comment by ecederstrand** [comment]
You’re welcome!
