### ISSUE TITLE
Support naive datetime values

### ISSUE THREAD

**Issue by Kami-no** [ecederstrand/exchangelib#109]
Hi,

At work we have rather unusual calendar. In common calendar Mac-users made events without specification of timezone for the whole day and Windows-users made events and outlook forced local timezone (MSK +3).
In Outlook it's all ok out-of-box, but in Thunderbird Lightning-addon it  looks ok if I specify  local timezone (otherwise mac-events ok and win-events has timezone offset +3:00).
But exchangelib act as events without timezone specified has timezone in UTC. When I force local TZ events from mac-users have offset (-3:00).

**Comment by ecederstrand** [comment]
Hmm. That's a bad situation :-)

To fix this, we need to specify somewhere which timezone we should attach to dates that don't have an explicit timezone. This is going to be fragile because in a large installation, users and/or backend servers may be in different timezones. Possibly, this setting should follow the `Account` object - it already has a `locale` setting.

I believe the place we're failing to DTRT is here: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/fields.py#L203

**Comment by Kami-no** [comment]
I think events without timezone are supposed to be always local. At least Outlook and Thunderbird Lightning act this way.

**Comment by ecederstrand** [comment]
That makes sense. I really dislike mixing naive and aware datetimes, but maybe can relax the requirement on read and enforce on write. Would that work for you?

**Comment by Kami-no** [comment]
I think there should be an option to relax the requirement. Default option should be enforcing UTC for unset. If you want to relax it you should understand that you're doing it.

**Comment by ecederstrand** [comment]
Ok. I think this would need to be an option on the `Account` class:

```python
Account(..., naive_datetimes_as_utc=False)
```

If it's a Python process-level setting, you can't set the option per-user or per-configuration, and it can't be a per-`Configuration` setting because a `Configuration` is created dynamically in autodiscover mode.

**Comment by Kami-no** [comment]
It would be nice.

**Comment by Kami-no** [comment]
0 impact...
exchangelib         1.9.4

Nothing changed for calendar/

**Comment by ecederstrand** [comment]
Can you be more specific? What is supposed to happen is that naive datetimes (datetime strings not ending with `Z`) from the server are assumed to be in the `Account.default_timezone` timezone and localized as such.

Are you seeing something different? If so, please post a simple example and the XML relevant response from the server.

**Comment by Kami-no** [comment]
`(venv) dzinin@zinin-nb:~/Projects/python_samples$ python3 exch.py 
Local TZ: Europe/Moscow
Deflt TZ: Europe/Moscow
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
(venv) dzinin@zinin-nb:~/Projects/python_samples$ vi exch.py 
(venv) dzinin@zinin-nb:~/Projects/python_samples$ python3 exch.py 
Local TZ: Europe/Moscow
Deflt TZ: UTC
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 00:00:00+03:00 - 2017-06-24 00:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -
2017-06-23 03:00:00+03:00 - 2017-06-24 03:00:00+03:00: -`

**Comment by Kami-no** [comment]
```
tz = EWSTimeZone.timezone(tz_name)
tz_def = EWSTimeZone.timezone('UTC')
#tz_def = tz
print("Local TZ: %s" % tz)
print("Deflt TZ: %s" % tz_def)
...
a = Account(primary_smtp_address=config.ex_cal, config=cfg, access_type=DELEGATE, autodiscover=False, default_timezone=tz_def)
```

**Comment by Kami-no** [comment]
How to dump xml?

**Comment by Kami-no** [comment]
```
                <t:Start>2017-06-22T21:00:00Z</t:Start>
                <t:End>2017-06-23T21:00:00Z</t:End>
...
                <t:Start>2017-06-23T00:00:00Z</t:Start>
                <t:End>2017-06-24T00:00:00Z</t:End>
```

**Comment by Kami-no** [comment]
Request has nothing about TZ
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header><t:RequestServerVersion Version="Exchange2013_SP1"/></s:Header>
  <s:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties><t:FieldURI FieldURI="item:Subject"/><t:FieldURI FieldURI="calendar:End"/><t:FieldURI FieldURI="calendar:Start"/></t:AdditionalProperties>
      </m:ItemShape><m:CalendarView EndDate="2017-06-23T15:21:03Z" StartDate="2017-06-23T14:21:03Z"/>
      <m:ParentFolderIds><t:FolderId ChangeKey="..." Id="..."/></m:ParentFolderIds>
    </m:FindItem>
  </s:Body>
</s:Envelope>
```

**Comment by ecederstrand** [comment]
The XML you dumped indicates that the returned datetimes are in UTC. `2017-06-23T15:21:03Z` ends with a `Z` which is defined in ISO8601 at a UTC timestamp: https://en.wikipedia.org/wiki/ISO_8601#UTC. I think we are doing things correctly here.

https://github.com/ecederstrand/exchangelib/commit/49d486e7194f4f606ea0711b4635d48515233ad8 handles cases where the server returns a timestamp with no timezone information at all, e.g. `2017-06-23T15:21:03`. In this case we assume the timestamp is a local datetime, and we localize it using `Account.default_timezone` which defaults to `EWSTimeZone.localzone()`.

**Comment by Kami-no** [comment]
Than there are some other hidden features somewhere else. Thunderbird + Lightning + Exchange EWS Provider + right timezone =  exactly this calendar shows for all these events same time...
Same in Outlook.

**Comment by ecederstrand** [comment]
Are you saying the actual datetime values are different in exchangelib and Outlook if you localize them both to UTC, or that the datetimes are equal but exchangelib shows them in UTC and Outlook in MSK?

It the latter is the case, then thi is per design. `exchangelib` is meant to always return UTC. We're more low-level than a MUA, so it's up to exchangelib consumers to localize datetimes according to the preferences of the end user.

**Comment by Kami-no** [comment]
- **Outlook** always shows these events for me in MSK and all starts in 00:00.
- **Thunderbird + Lightning + Exchange EWS Provider** if I don't setup timezone shows these events just _like exchangelib_ - part 00:00 apd part 03:00.
- **Thunderbird + Lightning + Exchange EWS Provider** if I do setup timezone shows these events just _like Outlook_ - all starts at 00:00.

exchangelib for non-localized version shows part 21:00 and part 00:00 and for localized version 00:00 and 03:00.

May be it's a combo for "all day" event + timezone or something else...

**Comment by ecederstrand** [comment]
Ah, OK. It makes sense if this is restricted to all-day events. All-day events are meant to be all-day no matter what timezone you're in, but EWS doesn't special-case this situation and just uses the standard datetime fields, which contain timezone information. When possible, we request datetime values in UTC since timezones in EWS are an absolute mess (see e.g. https://msdn.microsoft.com/en-us/library/office/dn789029(v=exchg.150).aspx).

I'm not sure what to do about this except suggest that you check the `is_all_day` flag on a calendar item and just use the date portion of the `start` and `end` values  for all-day events.

**Comment by Kami-no** [comment]
In current situation (the calendar if for all-day events) the workaround will be to get current date and ask Exchange for events for the day at 5 am.

But in the case when calendar contains not only the whole day events and have such mess with timezones exchangelib will not provide valid information =(

**Comment by ecederstrand** [comment]
Have you tested this? I have calendars with mixed all-day and non-allday events, and the non-allday event start- and end datetimes are returned just fine, just localized to UTC.

The issue here is that, for all-day events, EWS will return the start- and end datetimes at midnight in the timezone we have requested, which I think is the best EWS can do without introducing even more weirdness. We're always requesting datetimes in UTC, which is unfortunate for all-day events if you're treating the datetimes at face value. I think we can live with this, as long as we can work around it with:

```python
for i in account.calendar.all():
    if i.is_all_day:
        print(i.start.date(), i.end.date())
    else:
        print(i.start, i.end)
```

If you prefer, we can add a workaround on the `CalendarItem` class that post-processes `start` and `end` values for allday events when received from the server.

**Comment by Kami-no** [comment]
All these events are "all day" but in the result they have different time start and end.

Results of your first workaround:
```
$ python3 exch.py 
2017-06-25 - 2017-06-26: -
2017-06-25 - 2017-06-26: -
2017-06-25 - 2017-06-26: -
2017-06-25 - 2017-06-26: -
2017-06-25 - 2017-06-26: -
2017-06-26 - 2017-06-27: -
2017-06-26 - 2017-06-27: -
2017-06-26 - 2017-06-27: -
2017-06-26 - 2017-06-27: -
2017-06-26 - 2017-06-27: -
$ python3 exch.py 
2017-06-26 00:00:00+03:00 - 2017-06-26: -
2017-06-26 00:00:00+03:00 - 2017-06-26: -
2017-06-26 00:00:00+03:00 - 2017-06-26: -
2017-06-26 00:00:00+03:00 - 2017-06-26: -
2017-06-26 00:00:00+03:00 - 2017-06-26: -
2017-06-26 03:00:00+03:00 - 2017-06-27: -
2017-06-26 03:00:00+03:00 - 2017-06-27: -
2017-06-26 03:00:00+03:00 - 2017-06-27: -
2017-06-26 03:00:00+03:00 - 2017-06-27: -
2017-06-26 03:00:00+03:00 - 2017-06-27: -
```
Bad idea.

Also initial idea is to get current events. That's why the only way to get current events is to get events for specific time of the current day.

**Comment by ecederstrand** [comment]
Hi @Kami-no. Thanks for not giving up :-)

I just committed a fix so we request EWS results in the timezone of the account instead of always requesting UTC. I added a test that `start` and `end` of all-day items are localised when `default_timezone` is non-UTC.

Can you please confirm whether this fixes your issue?

**Comment by Kami-no** [comment]
```
2017-07-03 00:00:00+03:00 - 2017-07-03: -
2017-07-03 00:00:00+03:00 - 2017-07-03: -
2017-07-03 00:00:00+03:00 - 2017-07-03: -
2017-07-03 00:00:00+03:00 - 2017-07-03: -
2017-07-03 00:00:00+03:00 - 2017-07-03: -
2017-07-03 03:00:00+03:00 - 2017-07-04: -
2017-07-03 03:00:00+03:00 - 2017-07-04: -
2017-07-03 03:00:00+03:00 - 2017-07-04: -
2017-07-03 03:00:00+03:00 - 2017-07-04: -
2017-07-03 03:00:00+03:00 - 2017-07-04: -
```
No luck
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header><t:RequestServerVersion Version="Exchange2013_SP1"/></s:Header>
  <s:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties><t:FieldURI FieldURI="calendar:Start"/><t:FieldURI FieldURI="calendar:IsAllDayEvent"/><t:FieldURI FieldURI="item:Subject"/><t:FieldURI FieldURI="calendar:End"/></t:AdditionalProperties>
      </m:ItemShape><m:CalendarView EndDate="2017-07-03T09:59:59Z" StartDate="2017-07-03T09:00:00Z"/>
      <m:ParentFolderIds><t:FolderId ChangeKey="AgAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADQdPTb" Id="AQMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAAuAAAD8w4nLqQSCUethc4jiFybtgEArbaQwI5dlEyeVn3t19/F2AAAAgENAAAA"/></m:ParentFolderIds>
    </m:FindItem>
  </s:Body>
</s:Envelope>
```

**Comment by ecederstrand** [comment]
That XML looks strange - it should contain a timezone definition. Try git pulling again and running your test?

The intended behaviour is that EWS returns all-day calendar items from midnight to midnight in the requested timezone. I added a test for this in https://github.com/ecederstrand/exchangelib/commit/66fc24dcd6151c4ffafdb3fae013c01df0e0e4fa but maybe it doesn't cover your situation.

**Comment by Kami-no** [comment]
Test is ok
```
$ python3.5 -W ignore setup.py test --test-suite=tests.CalendarTest.test_all_day_datetimes
running test
running egg_info
writing exchangelib.egg-info/PKG-INFO
writing requirements to exchangelib.egg-info/requires.txt
writing top-level names to exchangelib.egg-info/top_level.txt
writing dependency_links to exchangelib.egg-info/dependency_links.txt
reading manifest file 'exchangelib.egg-info/SOURCES.txt'
writing manifest file 'exchangelib.egg-info/SOURCES.txt'
running build_ext
test_all_day_datetimes (tests.CalendarTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 1.029s

OK
```
Uninstalled, installed from git but...
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header><t:RequestServerVersion Version="Exchange2013_SP1"/>
    <t:TimeZoneContext><t:TimeZoneDefinition Id="Russian Standard Time"/></t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties><t:FieldURI FieldURI="calendar:IsAllDayEvent"/><t:FieldURI FieldURI="calendar:Start"/><t:FieldURI FieldURI="calendar:End"/></t:AdditionalProperties>
      </m:ItemShape><m:CalendarView EndDate="2017-07-04T12:59:59+03:00" StartDate="2017-07-04T12:00:00+03:00"/>
      <m:ParentFolderIds><t:FolderId ChangeKey="AgAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADQdPTb" Id="AQMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAAuAAAD8w4nLqQSCUethc4jiFybtgEArbaQwI5dlEyeVn3t19/F2AAAAgENAAAA"/></m:ParentFolderIds>
    </m:FindItem>
  </s:Body>
</s:Envelope>
```
```
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header><t:RequestServerVersion Version="Exchange2013_SP1"/>
    <t:TimeZoneContext><t:TimeZoneDefinition Id="Russian Standard Time"/></t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties><t:FieldURI FieldURI="calendar:IsAllDayEvent"/><t:FieldURI FieldURI="calendar:Start"/><t:FieldURI FieldURI="calendar:End"/></t:AdditionalProperties>
      </m:ItemShape><m:CalendarView EndDate="2017-07-04T12:59:59+03:00" StartDate="2017-07-04T12:00:00+03:00"/>
      <m:ParentFolderIds><t:FolderId ChangeKey="AgAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADQdPTb" Id="AQMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAAuAAAD8w4nLqQSCUethc4jiFybtgEArbaQwI5dlEyeVn3t19/F2AAAAgENAAAA"/></m:ParentFolderIds>
    </m:FindItem>
  </s:Body>
</s:Envelope>' Response data:
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header><h:ServerVersionInfo
    MajorVersion="15"
    MinorVersion="0"
    MajorBuildNumber="1263"
    MinorBuildNumber="5"
    Version="V2_23"
    xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:FindItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:RootFolder TotalItemsInView="10" IncludesLastItemInRange="true">
            <t:Items>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAFRAAgI1MJvnSnAAEYAAAAA8w4nLqQSCUethc4jiFybtgcArbaQwI5dlEyeVn3t19/F2AAAAAABDQAArbaQwI5dlEyeVn3t19/F2AAA0HO4TQAAEA==" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADQdOjt"/>
                <t:Start>2017-07-04T00:00:00+03:00</t:Start>
                <t:End>2017-07-05T00:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAFRAAgI1MJvnSnAAEYAAAAA8w4nLqQSCUethc4jiFybtgcArbaQwI5dlEyeVn3t19/F2AAAAAABDQAAL6a1Gk/9dUC1lpw4gpeKiQAA+N3uSAAAEA==" ChangeKey="DwAAABQAAAAgEz0aH648ToCrnWSeVJroAALhJQ=="/>
                <t:Start>2017-07-04T00:00:00+03:00</t:Start>
                <t:End>2017-07-05T00:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAFRAAgI1MJvnSnAAEYAAAAA8w4nLqQSCUethc4jiFybtgcArbaQwI5dlEyeVn3t19/F2AAAAAABDQAAvEbOBnRmqkG5S+xhNFbnJwAAAADdHgAAEA==" ChangeKey="DwAAABQAAADT8c8pRoPnSZmIyHgiYSluAAZEfw=="/>
                <t:Start>2017-07-04T00:00:00+03:00</t:Start>
                <t:End>2017-07-05T00:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAFRAAgI1MJvnSnAAEYAAAAA8w4nLqQSCUethc4jiFybtgcArbaQwI5dlEyeVn3t19/F2AAAAAABDQAArbaQwI5dlEyeVn3t19/F2AAAHYP3vwAAEA==" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAAAdhCD0"/>
                <t:Start>2017-07-04T00:00:00+03:00</t:Start>
                <t:End>2017-07-05T00:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOAFRAAgI1MJvnSnAAEYAAAAA8w4nLqQSCUethc4jiFybtgcArbaQwI5dlEyeVn3t19/F2AAAAAABDQAANnObY88cR0+Bw4VMHvlfpgAAAACq7gAAEA==" ChangeKey="DwAAABQAAABB+TAqu+NLRrD4j0rdu0JkAAd0MQ=="/>
                <t:Start>2017-07-04T00:00:00+03:00</t:Start>
                <t:End>2017-07-05T00:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOABGAAAAAADzDicupBIJR62FziOIXJu2BwCttpDAjl2UTJ5Wfe3X38XYAAAAAAENAACttpDAjl2UTJ5Wfe3X38XYAADaGSmlAAA=" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADaGmgU"/>
                <t:Start>2017-07-04T03:00:00+03:00</t:Start>
                <t:End>2017-07-05T03:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOABGAAAAAADzDicupBIJR62FziOIXJu2BwCttpDAjl2UTJ5Wfe3X38XYAAAAAAENAACttpDAjl2UTJ5Wfe3X38XYAADaGSnJAAA=" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADaGmg4"/>
                <t:Start>2017-07-04T03:00:00+03:00</t:Start>
                <t:End>2017-07-05T03:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOABGAAAAAADzDicupBIJR62FziOIXJu2BwCttpDAjl2UTJ5Wfe3X38XYAAAAAAENAACttpDAjl2UTJ5Wfe3X38XYAADaGSm0AAA=" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADaGmgj"/>
                <t:Start>2017-07-04T03:00:00+03:00</t:Start>
                <t:End>2017-07-05T03:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOABGAAAAAADzDicupBIJR62FziOIXJu2BwCttpDAjl2UTJ5Wfe3X38XYAAAAAAENAACttpDAjl2UTJ5Wfe3X38XYAADaGSoQAAA=" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADaGmh/"/>
                <t:Start>2017-07-04T03:00:00+03:00</t:Start>
                <t:End>2017-07-05T03:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
              <t:CalendarItem><t:ItemId Id="AAMkAGNlNTAxNjM3LWU3OTAtNGY5YS1iZWMyLTczZjEwOTcxNjBiOABGAAAAAADzDicupBIJR62FziOIXJu2BwCttpDAjl2UTJ5Wfe3X38XYAAAAAAENAACttpDAjl2UTJ5Wfe3X38XYAADaGSnvAAA=" ChangeKey="DwAAABYAAACttpDAjl2UTJ5Wfe3X38XYAADaGmhe"/>
                <t:Start>2017-07-04T03:00:00+03:00</t:Start>
                <t:End>2017-07-05T03:00:00+03:00</t:End>
                <t:IsAllDayEvent>true</t:IsAllDayEvent>
              </t:CalendarItem>
            </t:Items>
          </m:RootFolder>
        </m:FindItemResponseMessage>
      </m:ResponseMessages>
    </m:FindItemResponse>
  </s:Body>
</s:Envelope>
```

**Comment by ecederstrand** [comment]
Ok, so *some* of you all-day events were returned with the time `T03:00:00+03:00` and the rest with `T00:00:00+03:00`. I'm not sure if this is something we can solve internally in exchangelib.

**Comment by Kami-no** [comment]
Some of the events has tz UTC and some had Moscow. All experiments gave the same result as we had at the start.

There is a hardcore way to find a method to solve it - I'll dump traffic from Thunderbird plugin that can parse the calendar and show it right.

**Comment by ecederstrand** [comment]
Ok, what could be happening is that we're not respecting the `StartTimeZone` and `EndTimeZone` elements when we receive items. We only set these when we create and update items. But it is a bit strange that all timestamps are returned with Moscow offset but not consistently at midnight. The timezone should be irrelevant.
