### ISSUE TITLE
Delta token max length

### ISSUE THREAD

**Issue by iglimanaj** [ecederstrand/exchangelib#1092]
I have experienced delta tokens (coming from sync_iems) that can be up to 100k characters long, which I find quite exceptional. Do you have experience with such long tokens? Is this normal?

The issue is not directly related to the exchangelib package, but I hope to get an answer from the experts of this community :smile:

**Comment by ecederstrand** [comment]
Personally, I don't have any experience or knowledge whether this is notmal or not. You may get better answers in a forum specific to Microsoft Exchange.

**Comment by ecederstrand** [comment]
Closing. Feel free to update here if you get more insight into this.
