### ISSUE TITLE
Using App registration and certificate based authentication

### ISSUE THREAD

**Issue by fabge** [ecederstrand/exchangelib#1093]
I am trying to use a certificate based authentication for an Azure App registration.

The app registration has already been granted sufficient permissions:
![grafik](https://user-images.githubusercontent.com/21140791/174823923-c9dc5dd9-e9b5-4856-a488-04492ba8ba66.png)

I am now trying to use certificates instead of client ID & client secret:
![grafik](https://user-images.githubusercontent.com/21140791/174824112-d59be737-3eb7-410d-ae6f-df1e0fc9e4c1.png)

Is this possible? I haven't found anything in the documentation?

Thanks in advance!

**Comment by ecederstrand** [comment]
I haven't tried CBA myself, but maybe this is what you're looking for? https://ecederstrand.github.io/exchangelib/#certificate-based-authentication-cba
