### ISSUE TITLE
Unread Filter Not Working?

### ISSUE THREAD

**Issue by milind** [ecederstrand/exchangelib#1095]
Hey! So I've started to use this library recently but when trying to get some filtering for all of the unread emails from today, I get some unexpected behaviors that I can't quite explain (I expect that the error is entirely on my end, which is why I haven't placed this under a bug report, but I've been staring at the problem for a while and can't seem to figure out what is happening on the backend). I am trying to follow @ecederstrand's suggestion in this [StackOverflow answer](https://stackoverflow.com/questions/62650722/python-exchangelib-how-to-get-todays-unread-mail-list) but all emails appear to have the unread status, even though they all appear as read messages when I open up the email account in Outlook itself. The following is the filter query I'm using (returns all emails when `is_read=False` and returns no emails when `is_read=True`).
```python
filtered_emails = folder.filter(
    is_read=False, datetime_received__gte=midnight
)
```
I'm happy to answer any questions or try anything different if you have any suggestions! Thank you!

**Comment by ecederstrand** [comment]
I cannot reproduce this. Here's the inbox of my test account:
![image](https://user-images.githubusercontent.com/559151/178926169-3a61aad2-813d-4ac3-aa59-59621d9b01f9.png)

Here's my test code:
```python
a = Account(...)
print("Read:")
for i in a.inbox.filter(is_read=True).only("subject"):
    print(i.subject)

print("Unread:")
for i in a.inbox.filter(is_read=False).only("subject"):
    print(i.subject)
```

which correctly prints:
```
Read:
This email has been read
Unread:
This email is still unread
```

**Comment by ecederstrand** [comment]
Did you manage to figure this out?

**Comment by milind** [comment]
Apologies for not getting back to this sooner - I've been passively trying to debug the problem and still haven't quite figured out what could be causing it. When trying to use my script with a few other emails on the same exchange server, including my own personal email, the filter as read parameter seems to work perfectly, but I still can't isolate what it is about this one particular email account that seems to evade the filter. Will try out a few other solutions over the next few days as well.

**Comment by ecederstrand** [comment]
So EWS is showing one thing, and Outlook another. Maybe you can access the account with OWA or a different client, and check the read status there? That would give a hint about who's right. I'd put my money on EWS, though, because all instances where I've experienced this turned out to be Outlook using a stale cache.

**Comment by milind** [comment]
Just as an update to this, it seems as though it's just one folder that is experiencing this problem and I'm able to set the read status through the exchangelib package, so my solution will likely be to mark everything as read and manage the read status from my script itself, which should cover about 90% of my use case - the last 10% of being able to decipher when someone reads an email through a client likely will not be too big a loss. Thanks so much for your help!
