### ISSUE TITLE
Read Follow up and skip 'Mark Complete'/ MeetingRequest / MeetingCancellation /MeetingResponse mails

### ISSUE THREAD

**Issue by Pratibha-Singh** [ecederstrand/exchangelib#1096]
I want to read only inbox with 'Follow-up' mails and store in a folder also want to skip mails having 'Mark Complete'/ MeetingRequest / MeetingCancellation /MeetingResponse. 
Here is my code:
I have used extended property for Flag having- follow-up and Mark complete emails. 

Here I am getting error: 
`AttributeError: 'flag' is not a valid attribute. See MeetingRequest.FIELDS for valid field names**`

```python
class Flag(ExtendedProperty):
    property_tag =   #0x0e08 
    property_type = 'Integer'

Message.register('flag', Flag)
mooved = 0
for m in account.inbox.all()[:100]:
    if isinstance(m, MeetingResponse):
        print("its a Meeting response")
        continue
        if isinstance(m, MeetingRequest):
            continue
            if isinstance(m, MeetingCancellation):
                print("its a Meeting Request")
                continue
    else:
        m.flag = 2  # for mark complete flag
        print(m.flag)
        m.move(toBox)
        mooved = mooved+1
```

I just want to read all inbox mails and also check if  mail is flagged as 'Mark complete' then skip if 'follow-up' then parse that email, if meeting request/Response/cancellation then skip.
I have checked https://ecederstrand.github.io/exchangelib/ and https://github.com/ecederstrand/exchangelib/issues/85 but could not use in my scenario.

**Comment by ecederstrand** [comment]
I took the liberty of properly highlighting your code, which reveals that the error is due to an error in your if/else loop. You're not actually ignoring `MeetingRequest` items, which is also what the error message states.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues with this after fixing your code.
