### ISSUE TITLE
Create/update/delete/empty and navigate folders

### ISSUE THREAD

**Issue by major** [ecederstrand/exchangelib#110]
Would it be possible to add a method that creates a new folder? I've dug around in the existing code and I haven't found a method for that yet.

**Comment by ecederstrand** [comment]
This isn't implemented yet, but would be a great addition. I think the existing API from items could work:

```python
my_folder = Folder(name'My Folder', parent=my_account.inbox)
my_folder.save()
another_folder = Folder(name'Another Folder', parent=my_folder)
another_folder.save()
```

The service is described here: https://msdn.microsoft.com/en-us/library/office/aa563574(v=exchg.150).aspx

EWS also has `UpdateFolder` and `DeleteFolder` to support `.save()` and `.delete()` on existing folders. The `Folder` class would benefit from a clear parent/children relationship as part of the API.

**Comment by Afterburned6387** [comment]
I'd be very interested in this feature as well. I'm not all that far along, but I'm looking at the service offering link above to see if its in my wheelhouse to put together a contribution.

**Comment by beeekey** [comment]
this would also be very interesting for me ...

**Comment by FusionFC** [comment]
There is also an ability to "empty" a folder documented here: [https://msdn.microsoft.com/en-us/library/office/gg274404(v=exchg.80).aspx](url)

This would be a nice addition to the Folder class as well.

**Comment by ecederstrand** [comment]
An API for navigating folders could be modelled around [pathlib](https://docs.python.org/3/library/pathlib.html) with missing components (e.g. `walk()`) lending from [os](https://docs.python.org/3/library/os.html)

**Comment by ecederstrand** [comment]
Now only missing the `.empty()` method to close this issue.

**Comment by mrlewis-urw** [comment]
Can you please add an example of how to move an item to "todos" folder, under "inbox"
Only example you have in documentation is accessing predefined/default folders.

I can't get this new implementation to work... basically having to resort to moving items to the trash, junk, or sent folders because I can't find or address the custom folder I made.

**Comment by ecederstrand** [comment]
```python
item.move(some_folder / 'sub_folder' / 'even_deeper' / 'leaf')
```

**Comment by mrlewis-urw** [comment]
Fantastic! Thank you!  that worked great!
I didn't realize that was syntax for the function.  My script is working perfectly now.
