### ISSUE TITLE
DNS timeout for multiple nameservers using Autodiscovery

### ISSUE THREAD

**Issue by adisidis** [ecederstrand/exchangelib#1102]
**Describe the bug**
Using the autodiscover option with multiple nameservers will Timeout if the first nameserver does not respond within the timeframe. Resolving using the next nameservers will not occur, as the `lifetime` is reached.
The Autodiscover is setting the same timeout for the dns Resolver and for the `lifetime` (which is the total timeout regardless of the nameservers). 
method: **_is_valid_hostname**

**To Reproduce**
```
from exchangelib.autodiscover.discovery import AutoDiscovery
ad = Autodiscovery(None)
ad.resolver.nameservers.insert(0, '1.2.3.1') # '1.2.3.1' should be some unreachable host
ad._is_valid_hostname('github.com')
```

**Expected behavior**
Resolving should continue using other nameservers if available and if time allows.

**Log output**
dns.exception.Timeout: The DNS operation timed out after 10.001440048217773 seconds

**Additional context**
Python 3.8.10
exchangelib 4.7.3

**Comment by ecederstrand** [comment]
This is really something that the `dnspython` package should take care of. Anyway, I cannot reproduce this:

```python
>>> import dns.resolver
>>> r = dns.resolver.Resolver()
>>> r.nameservers
['192.168.86.1']
>>> r.resolve("google.com").__dict__
{'qname': <DNS name google.com.>, 'rdtype': <RdataType.A: 1>, 'rdclass': <RdataClass.IN: 1>, 'response': <DNS message, ID 44838>, 'nameserver': '192.168.86.1', 'port': 53, 'chaining_result': <dns.message.ChainingResult object at 0x10587f850>, 'canonical_name': <DNS name google.com.>, 'rrset': <DNS google.com. IN A RRset: [<142.250.179.206>]>, 'expiration': 1659530352.610888}
>>> r.nameservers.insert(0, "1.2.3.4")
>>> r.nameservers
['1.2.3.4', '192.168.86.1']
>>> r.resolve("google.com").__dict__
{'qname': <DNS name google.com.>, 'rdtype': <RdataType.A: 1>, 'rdclass': <RdataClass.IN: 1>, 'response': <DNS message, ID 36127>, 'nameserver': '192.168.86.1', 'port': 53, 'chaining_result': <dns.message.ChainingResult object at 0x10587f430>, 'canonical_name': <DNS name google.com.>, 'rrset': <DNS google.com. IN A RRset: [<142.250.179.206>]>, 'expiration': 1659530256.9398699}
```

Does this also happen with an up-to-date version of `dnspython` (currently 2.2.1)?

**Comment by adisidis** [comment]
@ecederstrand using the dns.resolver directly is OK, but the current implementation is:
```
    @threaded_cached_property
    def resolver(self):
        import pdb; pdb.set_trace()
        resolver = dns.resolver.Resolver(**self.DNS_RESOLVER_KWARGS)
        for k, v in self.DNS_RESOLVER_ATTRS.items():
            setattr(resolver, k, v)
        return resolver
```

The setattr(resolver, k, v) is setting the timeout for the nameserver incorrectly (by default this is 2.0, see dns.resolver.reset())

So if you attempt to reproduce as I mentioned (make sure you use the Autodiscovery class) you should reproduce this easily.

**Comment by ecederstrand** [comment]
Ah, that makes sense! I can reproduce if I set `r.timeout = 10` in the above example.

It wasn't clear to me until now what the difference between timeout and lifetime is. The referenced commit makes it possible to configure both, and sets the default timeout well below the lifetime.
