### ISSUE TITLE
search message by "item_id"

### ISSUE THREAD

**Issue by frederickchai** [ecederstrand/exchangelib#111]
Hi,
Its there a way to search messages by item_id ?? 
I know you can search using this sentense: _account.inbox.filter(subject='foo')_  (search by subject) but if I have the message _item_id_ how I can get the message object ???

I try using **account.inbox.get(item_id="AAMkADYxNDQwMGJkLTk....")** but its returning this message: 
_ErrorInvalidValueForProperty: The specified value is invalid for property. (FieldURI='item:ItemId')
_

**Comment by ecederstrand** [comment]
EWS does not support getting items by `ItemId` alone. You also need to specify the `Changekey`.

We should probably support `get()` and `filter()` with item IDs, but for now you can use `account.fetch(some_ids)`, where `some_ids` is a list or generator of either `ItemId` objects or '('item_id', 'changekey')` tuples, or a `QuerySet` object.

**Comment by frederickchai** [comment]
thanks a lot !!!

**Comment by ecederstrand** [comment]
I added `get(item_id=..., changekey=...)` support in https://github.com/ecederstrand/exchangelib/commit/b1a30d52f6893336bbd078e6a47f22e183ce0088
