### ISSUE TITLE
EWSDateTime.fromisoformat() throws exception when timezone is in the date string

### ISSUE THREAD

**Issue by p3l** [ecederstrand/exchangelib#1114]
**Describe the bug**
EWSDateTime behaves different from datetime when I read string output with a timezone offset from isoformat() in that it throws an exception.

**To Reproduce**
Here is a short script that reproduces the issue

> from datetime import datetime
> from exchangelib import EWSDateTime, EWSTimeZone
> 
> d = EWSDateTime.now(tz = EWSTimeZone.localzone())
> 
> dstr = d.isoformat()
> print(f'Output: {dstr}')
> 
> rdstr = datetime.fromisoformat(dstr)
> print(f'Input: {rdstr}')
> 
> rdstr = EWSDateTime.fromisoformat(dstr)
> print(f'Input: {rdstr}')

This is the output from the script:
> $ python test.py
> Output: 2022-08-29T01:07:10.440493+02:00
> Input: 2022-08-29 01:07:10.440493+02:00
> Traceback (most recent call last):
>   File "/home/petlun/code/lab/test.py", line 12, in <module>
>     rdstr = EWSDateTime.fromisoformat(dstr)
>   File "/home/petlun/code/lab/venv/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 93, in __new__
>     raise InvalidTypeError("tzinfo", tzinfo, EWSTimeZone)
> exchangelib.errors.InvalidTypeError: 'tzinfo' datetime.timezone(datetime.timedelta(seconds=7200)) must be of type <class > 'exchangelib.ewsdatetime.EWSTimeZone'

**Expected behavior**
I would expect that EWSDateTime.fromisoformat() would behave the same way as datetime.fromisoformat() in the above example.

**Additional context**
> $ python --version
> Python 3.9.7
> $ python -m pip list -l | grep exchangelib
> exchangelib           4.7.6

**Comment by p3l** [comment]
Sorry, just after I posted that I noticed .fromisoformat() is not listed in the documentation. I just typed it out of datetime habit.

If anyone runs into the same issue I guess the proper way to do it is to replace .fromisoformat() with .from_string():
> rdstr = EWSDateTime.from_string(dstr).astimezone(tz = EWSTimeZone.localzone())
> print(f'Input: {rdstr}')

**Comment by ecederstrand** [comment]
Thanks for the bug report! The referenced commit should fix this.
