### ISSUE TITLE
AADSTS900144 error when using OAUTH2 authentication

### ISSUE THREAD

**Issue by finganinja** [ecederstrand/exchangelib#1115]
**Describe the bug**
When creating an account object with OAUTH2 auth_type, error AADSTS900144 is returned.
If I add the `client_id` to the request body manually, by modifying `requests_oauthlib/oauth2_session.py` (!!) it correctly retrieves the token, which makes it appear that the calling function from exchangelib is either not setup correctly, or, more likely not being used correctly by me, though I have followed the [doco](https://ecederstrand.github.io/exchangelib/#oauth-on-office-365) as closely as possible.
```python
credentials = OAuth2Credentials(client_id=OAUTH_CLIENT_ID, client_secret=OAUTH_SECRET, tenant_id=OAUTH_TENANT_ID)
configuration = Configuration(credentials=credentials, server="outlook.office365.com", auth_type=OAUTH2)
account = Account('USER_EMAIL', config=configuration)
```

**To Reproduce**
use OAUTH2 credentials to create an Account object

**Expected behavior**
correct token retrieval

**Log output**
```  <..snipped stack trace..>
File "/home/ad/.local/lib/python3.9/site-packages/exchangelib/protocol.py", line 292, in create_session
    session = self.create_oauth2_session()

File "/home/ad/.local/lib/python3.9/site-packages/exchangelib/protocol.py", line 345, in create_oauth2_session
    token = session.fetch_token(

File "/usr/lib/python3/dist-packages/requests_oauthlib/oauth2_session.py", line 247, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)

File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)

File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)

File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)

File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'.
```

**Additional context**
python 3.9.2, exchangelib 4.7.6

**Comment by finganinja** [comment]
I have created a workaround which appears to correct the error above, by forcing the `client_id` into the body of the request (injected lines 342, 343 of `protocol.py` in exchangelib):

```python
client = BackendApplicationClient(client_id=self.credentials.client_id)

# this doesn't do anything about injecting client_id into the body
client.prepare_request_body(include_client_id=True)

# this is the magic sauce that gets around the AADSTS900144 error
token_params['body'] = f"client_id={self.credentials.client_id}"
```
   
  I still have an issue with "Invalid credentials", but this may be as obvious as is implied.

**Comment by finganinja** [comment]
further refined by replacing the above with
```python
include_cliet_id=True
```
in `session.fetch_token()`

**Comment by ecederstrand** [comment]
That's weird. I have the exact same code working without issues for the exchangelib test suite. Which version of `requests_oauthlib` and `oauthlib` do you have installed?

In the last comment, are you saying the only change needed to fix your situation is this?:

```diff
--- a/exchangelib/protocol.py
+++ b/exchangelib/protocol.py
@@ -314,7 +314,7 @@ class BaseProtocol:
 
     def create_oauth2_session(self):
         session_params = {"token": self.credentials.access_token}  # Token may be None
-        token_params = {}
+        token_params = {"include_client_id": True}
 
         if isinstance(self.credentials, OAuth2AuthorizationCodeCredentials):
             token_params["code"] = self.credentials.authorization_code  # Auth code may be None
```

**Comment by finganinja** [comment]
Hi @ecederstrand, thanks for the response.

The current library versions in use are 
```
exchangelib = 4.7.6
requests_oauthlib = 1.0.0
requests_oauthlib = 3.1.0
```

No, to be clear, I modified `protocol.py` in `exchangelib` to add `include_client_id=True` as a parameter to the `token = session.fetch_token()` call.

This fixed the initial AADSTS900144 error for me. The overarching problem was that the server side wanted the `client_id` included in the body of the request.

**Comment by ecederstrand** [comment]
Thanks for the clarification. I think the above patch reaches the same goal, since `token_params` is passed as kwargs to `fetch_token()`.

**Comment by ecederstrand** [comment]
`requests-oauthlib` is at version 1.3.1 now, so it might be fixed there already. Just FYI.

**Comment by finganinja** [comment]
Yes, both methods above work.

Though, I would lean towards the parameter passing, since it leverages a mechanism that already exists.

I will also update my `requests-oauthlib`, and see whether that fixes it on my end.

Thanks again.

**Comment by finganinja** [comment]
OK, it appears merely updating `requests-oauthlib` has fixed the underlying issue, without need for the code changes above.

Not sure why my python library files are so out of date (relatively fresh system build), but hopefully this helps anyone else that comes across the problem.

**Comment by ecederstrand** [comment]
Thanks for the extra test! I've committed the fix regardless, instead of trying to find out exactly when this was fixed and tightening the requirements for requests-oauthlib.
