### ISSUE TITLE
Delegate access type with OAuth authentication scope and grant issues

### ISSUE THREAD

**Issue by shiv81** [ecederstrand/exchangelib#1119]
**Describe the bug**
Trying to use OAUTH authentication using DELEGATE access type. According to logs, the wrong scope is being requested in the token request. Also when I test in Postman, I am only able to get it to work when using Password Credentials type, not Client Credentials type.

**To Reproduce**
```python
emailAccount = 'test@test.com'
client_id = '...'
secret_id = '...'
tenant_id = '...'

oauthcredentials = OAuth2Credentials(
    client_id=client_id,
    client_secret=secret_id,
    tenant_id=tenant_id,
    identity=Identity(primary_smtp_address=emailAccount),
)

config =  Configuration(
    credentials=oauthcredentials,
    auth_type=OAUTH2,
    server='outlook.office365.com',
)

account = Account(
    emailAccount,
    config=config,
    autodiscover=False,
    access_type=DELEGATE,
)
```

**Expected behavior**
The debugging logs in Exchangelib state the following:
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'client_credentials', 'scope': 'https://outlook.office365.com/.default'}

However according to the Microsoft EWS Oauth page, https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth , the scope should be https://outlook.office365.com/EWS.AccessAsUser.All when using DELEGATE auth.

If the access type was set to App only/Impersonate, then the https://outlook.office365.com/.default scope would be correct.

When I try in Postman by creating a new request -> Authorization tab -> Type -> Oauth 2.0 -> then click the "Get New Access Token" button -> choose grant type "Client Credentials" -> fill in access token url  https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/token -> fill in client id and secret and scope as https://outlook.office365.com/EWS.AccessAsUser.All -> I get the error: The provided value for scope https://outlook.office365.com/EWS.AccessAsUser.All is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).

When I try using the Password Credentials grant type instead and include the account email and password, it succeeds and returns a token. The requests-oauthlib package mentions this as a oauthlib.oauth2.LegacyApplicationClient.

**Log output**
Added above

**Additional context**
I apologize for not adding Postman screenshots but could not due to being blocked on a work computer. I guess I just want to confirm if someone has been able to use DELEGATE access type using OAUTH2. I am unable to get the IMPERSONATE/App access due to company restrictions. I think it would work if the correct scope was used and support was added to use the password grant. If I missed this in the documentation, please forgive me. As it is now, I am able to get a token using the other scope but end up getting a 403 error since the scope is incorrect for the EWS.AccessAsUser.All permission which I verified is granted in the Azure AD portal.

**Comment by ecederstrand** [comment]
Thanks for the detailed report! This looks like a bug, and should be fixable. I'll have a look within the next week, but feel free to dive in and attempt a fix yourself if you have the time.

**Comment by ecederstrand** [comment]
@shiv81 Can you test out https://github.com/ecederstrand/exchangelib/pull/1121? I'm unable to test myself due to my current test account setup. To test, you should use the new credentials class:

```python
from exchangelib import OAuth2LegacyCredentials

creds = OAuth2LegacyCredentials(
    client_id=client_id,
    client_secret=client_secret,
    tenant_id=tenant_id,
    username=username,
    password=password,
)
```

**Comment by shiv81** [comment]
I actually ended up modifying the existing OAuth2Credentials class to include username and password so the init looks like this:
       `super().__init__()
        self.client_id = client_id
        self.client_secret = client_secret
        self.tenant_id = tenant_id
        self.identity = identity
        self.access_token = access_token
        self.username = username
        self.password = password`

Then I modified the scope in the credentials file to  https://outlook.office365.com/EWS.AccessAsUser.All.

Finally, in the protocol file, I changed it so it is using the LegacyApplicationClient instead of the Backend ApplicationClient and passed in the added username and password parameters into the fetch_token method. 

I was able to get this to work yesterday since I was on a tight deadline with Microsoft's final basic auth deadline finally coming up on Oct 1. Will also reach back out sometime this week about confirming #1121 if that works due to the busy week. Really appreciate your quick turnaround - thanks

**Comment by ecederstrand** [comment]
Cool, thanks for describing your changes! That's exactly what the PR attempts to do. Let me know when you've given it a try. Then I can merge and cut a new release.

**Comment by shiv81** [comment]
I can confirm that the PR fixes the issue when using the new OAuth2LegacyCredentials class. Thanks so much!

**Comment by ecederstrand** [comment]
Delegate OAuth access is now documented at https://ecederstrand.github.io/exchangelib/#delegate-oauth-on-office-365
