### ISSUE TITLE
Authentication with different users

### ISSUE THREAD

**Issue by am-technix** [ecederstrand/exchangelib#112]
I tried successfully to use exchangelib. 

All is running correctly, I can add calendar entries, search, etc...

But it is only possible to use the first test-user I used for my first tests.

When II try with a second test-user, changing those 2 lines in my prototype script :

`credentials = Credentials(username='INDIV\xxxxx', password='yyyy')
account = Account(primary_smtp_address='zzzz@domain.com', credentials=credentials,
                  autodiscover=True, access_type=DELEGATE)`

I have an error :
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

I tried EWS tests on a Microsoft site https://testconnectivity.microsoft.com, with te same parameters of the 2 accounts and the tests are OK.

Is there something stored that can explained why only 1 user is running correctly ?

Thank you very much

**Comment by ecederstrand** [comment]
https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover.py caches the credentials along with the email domain. Maybe we're making assumptions there that we shouldn't be making?

**Comment by ecederstrand** [comment]
I think `exchangelib.autodiscover.AutodiscoverCache.__getitem__` is the culprit. We're reusing the cached credentials even though we claim not to.

**Comment by am-technix** [comment]
Thank you

**Comment by ecederstrand** [comment]
Did the workaround work? If so, I'd like to keep the issue open until the issue is fixed

**Comment by am-technix** [comment]
No, I had already tested that solution, but it was not the problem. 
I have also tried on a new VM and there is a problem on user2 and not user1... Those 2 users are on the same domain, same server, and I am sure of the mail/login/password, tried with OWA and with the Microsoft test server.
We use a shared server on OVH.
My code has only 2 lines for the test. 
Very very strange but I am trying to trace line by line...

**Comment by am-technix** [comment]
I found a workaround !

When I use :
`credentials = Credentials(username='INDIV\tef-537f7af5382444cf', password='xxxxx')`
for the credentials, it is working only for one user (I check the username many time, in the OWA, "change password").

but if I use directly the **primary_smtp_address** in place of username type **domain\username**, it is **always** working.

So, no more problem !

Thanks for your library, this is a big work and at high quality ! 
And thank's to have taken time to help me.

**Comment by ecederstrand** [comment]
No problem. Glad you got it working!
