### ISSUE TITLE
OAuth2 authentication by passing "access_token" in credentials?

### ISSUE THREAD

**Issue by milano-slesarik** [ecederstrand/exchangelib#1122]
Hello, 

I'm trying to use "access_token" that I obtain using `allauth` to authenticate `exchangelib` so I can fetch private and public contacts. Tried many configurations but still getting errors. Not sure if it's a bug or if I'm doing something wrong: 

`exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office.com/EWS/Exchange.asmx`
or 
`exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx`

```python
client_id = "-"  # Application (client) ID
client_secret = "-"  # is Value, and Secret ID is ---
tenant_id = "-"  # Directory (tenant) ID
access_token = "-"
credentials = OAuth2AuthorizationCodeCredentials(
    client_id=client_id,
    client_secret=client_secret,
    tenant_id=tenant_id,
    identity=Identity(primary_smtp_address="<EMAIL>"),
    access_token=OAuth2Token(
        {
            "access_token": access_token,
        }
    ),
)
config = Configuration(server="outlook.office.com", credentials=credentials)
account = Account(
    primary_smtp_address=self.primary_smtp_address,
    config=config,
    autodiscover=False,
    access_type=DELEGATE,
)
```

AZURE APP:

![image](https://user-images.githubusercontent.com/7869582/193820484-b95cedc6-fdc3-4cfa-85e6-17955641dbc7.png)

Do anybody knows what to do? Thanks

**Comment by ecederstrand** [comment]
This package uses the EWS API, not Graph. See https://ecederstrand.github.io/exchangelib/#oauth-on-office-365 on setting permissions for EWS.

**Comment by ecederstrand** [comment]
Closing, but feel free to reopen if you have additional questions related to this.

**Comment by futilestudio** [comment]
@ecederstrand Is the **full_access_as_app** necessary if the only thing I want is to read public contacts from Exchange Online accounts - of any user who gives me permissions using OAuth2.

There are also more granular ones like **Contacts.Read**

Thanks

**Comment by milano-slesarik** [comment]
@ecederstrand  Is the **full_access_as_app** necessary if the only thing I want is to read public contacts from Exchange Online accounts - of any user who gives me permissions using OAuth2.

There are also more granular ones like **Contacts.Read**

Thanks

**Comment by ecederstrand** [comment]
- I have no idea. Try it out and let us know 🙂
