### ISSUE TITLE
Failed to get auth type from service

### ISSUE THREAD

**Issue by piyush-agarwalla-02** [ecederstrand/exchangelib#1125]
The code was working fine since last one month to connect to outlook mail box and download emails. Suddenly from today it is throwing error 'TransportError: Failed to get auth type from service'. This error is thrown when I execute account.inbox

Please suggest what could be the reason

**Comment by ecederstrand** [comment]
The reason for the error is that the HTTP authentication errors don't contain enough information for us to guess the authentication method of the server you are contacting. If you [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) you can see the HTTP headers returned by the server and post them here for further debugging.

That said, if this is an account on Office365, then I believe they recently disabled Basic authentication. Instead, you need to switch to OAuth authentication. See https://ecederstrand.github.io/exchangelib/#oauth-on-office-365

**Comment by ecederstrand** [comment]
@piyush-agarwalla-02 Did you find the time to collect the debugging information?

**Comment by piyush-agarwalla-02** [comment]
Hi, I checked the mailbox **is an on prem Exchange server.** I have tried capturing the debug logs as suggested. Please find the debug logs attached. I am using basic authentication (using username and password) to connect to mail box.

[Error_log1.txt](https://github.com/ecederstrand/exchangelib/files/9872387/Error_log1.txt)
[Error_log2.txt](https://github.com/ecederstrand/exchangelib/files/9872388/Error_log2.txt)

**Comment by ecederstrand** [comment]
Looking at the logs in the first file, it's reporting an HTTP 404 on https://webmail-****.com/EWS/Exchange.asmx. This means that there's no EWS service hosted at `webmail-****.com`. You'll need to ask your Exchange admins which hostname to use to connect to EWS.

**Comment by ecederstrand** [comment]
Closing, as I don't think this is an issue with exchangelib.
