### ISSUE TITLE
How do I subscribe to multiple accounts

### ISSUE THREAD

**Issue by danhuazhou** [ecederstrand/exchangelib#1128]
Hi,I have a credentials have been given impersonation, and I'd like to subscribe to multiple account calendar.
If there are too many accounts, my method is not elegant.I read the documents but couldn't find any clues
Is there a way to subscribe to all accounts or subscribe to all the accounts in a group? Can you give me some advice? Thank you very much

my example:
```python
from exchangelib import DELEGATE, IMPERSONATION, Account
from exchangelib import Credentials


def create_subscription(address):
    credentials = Credentials(username='MYWINDOMAIN\\myuser',
                              password='topsecret')
    account = Account(
        primary_smtp_address=address, credentials=credentials,
        autodiscover=True, access_type=IMPERSONATION
    )
    subscription_id, watermark = account.calendar.subscribe_to_push(
        callback_url='https://my_app.example.com/callback_url'
    )
    return subscription_id


mail_list = ['myusername@example.com', 'test1@example.com',
             'test2@example.com']
for addr in mail_list:
    create_subscription(addr)

```

**Comment by ecederstrand** [comment]
What is not elegant about it? How would you like it to look instead?

**Comment by danhuazhou** [comment]
I need to subscribe to thousands of accounts.Will too many subscriptions affect the performance of EWS?

**Comment by ecederstrand** [comment]
That depends on the server hosting the EWS service. Are you concerned with how long time it takes to create thousands of subscriptions, or whether the server can handle sending notifications for thousands of active subscriptions?

Anyway, I suggest you just try it out and see if it works for you. The EWS service backing the above `subscribe_to_push()` call is https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/subscribe-operation. I don't think it handles multiple accounts in a single request, so you probably have to subscribe to each account individually.

**Comment by danhuazhou** [comment]
If have a folder that contains all the calendar, I wish I had just subscribed to this folder.Perhaps that is unlikely,in the document example subscriptions are based on specific accounts.Maybe I have to subscribe to each account individually.
Thank you very much for your reply

**Comment by ecederstrand** [comment]
I'm closing the issue as it doesn't seem like there's anything to fix. Feel free to reopen if you have additional questions on this topic.
