### ISSUE TITLE
Python 2.7, exchangelib 2.2.0 is not listing inbox or any folder gives error.

### ISSUE THREAD

**Issue by bbelgaonkar-conga** [ecederstrand/exchangelib#1133]
**Describe the bug**
Python 2.7, exchangelib 2.2.0 is not listing inbox or any folder gives the error as NoneType object has no attribute major.
But it is working when I run in debug mode Account and expand for Result. Attached screenshots

**To Reproduce**
```python
client_id = 'b28ebf7f-bea0-425c-ba6e-5308e4e5f5a436'
client_secret = 'Bpv8Q~H-O~saM_me1xc3RiaiAaYKswp7N0V6KasHrt'
tenant_id = '3a41ae53-fb35-4431-be7b-a0b3e1aee3c056'
user = 'clmtestautomationuser1234@conga.com'
    
credentials = OAuth2Credentials(client_id=client_id, client_secret=client_secret,tenant_id=tenant_id)
config = Configuration(credentials=credentials, auth_type=OAUTH2,server="outlook.office365.com")
account = Account(primary_smtp_address=user,config=config)
account.inbox
```

**Expected behavior**
It should list the items present in the inbox without evaluating and expanding the result of Account

**Log output**
If applicable, add relevant output from [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) .

**Additional context**
Python2.7, exchangelib 2.2.0

**Comment by bbelgaonkar-conga** [comment]
![screenshot2](https://user-images.githubusercontent.com/63365133/196621844-17bba95c-a421-4d16-bcaa-0bf6678b3845.png)
![screenshot2](https://user-images.githubusercontent.com/63365133/196622114-09daaad3-aad3-497f-93e9-6be9a5f3c87a.png)
![screenshot3](https://user-images.githubusercontent.com/63365133/196622146-4949e3c5-a3b4-4ad7-90b6-d9af3aa82fa5.png)

**Comment by ecederstrand** [comment]
Hi @bbelgaonkar-conga First of all, if the credentials you posted are valid, you should remove them immediately and invalidate the credentials on the Exchange server.

Second, we'll need the stack trace leading to the AttributeError. It would also help if you can capture the last XML response before the error. See https://ecederstrand.github.io/exchangelib/#troubleshooting

Finally, you should really update to Python 3 and the latest version of exchangelib. The Python 2 versions of exchangelib are no longer supported and will not receive updates.

**Comment by bbelgaonkar-conga** [comment]
@ecederstrand Credential are not valid

**Comment by ecederstrand** [comment]
@bbelgaonkar-conga Did you manage to collect the needed debug information?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have time to revisit this.
