### ISSUE TITLE
CachingProtocol: comparrsion with None fails

### ISSUE THREAD

**Issue by 5263** [ecederstrand/exchangelib#1134]
I discovered a problem when acessing Office365 with IMPERSONATION in Version 4.8.0
https://github.com/ecederstrand/exchangelib/blob/6d4930a2053346f2468da0bea8d357165961d79a/exchangelib/protocol.py#L391
The comparrsion ```__eq__``` fails with in AtributeError in getattr.

As a workaround I was able to treat an AttributeError like the KeyError in 
https://github.com/ecederstrand/exchangelib/blob/6d4930a2053346f2468da0bea8d357165961d79a/exchangelib/protocol.py#L392

**Comment by ecederstrand** [comment]
Thanks for the report! Can you post the stack trace here, please?

**Comment by 5263** [comment]
I'm sorry i got problems to reproduce the problem (on a different machine). I remember that the key was "primary_smtp_address". It happened when tried to login with DELEGATE and IMPERSONATE (in the same interpreter).
I think this might be rare edge case and will close the issue.

**Comment by ecederstrand** [comment]
Alright. Reading the code, I can't figure out how that line would throw an AttributeError. If you happen to trigger this again, please reopen and post the stack trace here.
