### ISSUE TITLE
EWS deprecation and Migration to Graph API

### ISSUE THREAD

**Issue by nico525** [ecederstrand/exchangelib#1135]
Hi,
As I understood, slowly but surely Microsoft is going to deprecate and no longer invest into EWS especially when using exchange online. Please find the article [here](https://techcommunity.microsoft.com/t5/exchange-team-blog/upcoming-api-deprecations-in-exchange-web-services-for-exchange/ba-p/2813925). Is there work being done to migrate this awesome project to the ms graph API?

i see that you support the OAuth authentication already, but all communication to exchange are done through EWS and not the GraphAPI, correct?

**Comment by ecederstrand** [comment]
This project uses EWS and will continue to do so. There are other projects based on the Graph API out there that you can use if you want to use that API instead.
