### ISSUE TITLE
Using modern authentication with certificate thumbprint?

### ISSUE THREAD

**Issue by champlin2** [ecederstrand/exchangelib#1137]
Now that basic authentication is being turned off for tenants by Microsoft is there a way to use a locally installed certificate thumbprint (preferably in the LocalMachine\Personal cert store) for authentication (along with AppId and Organization/tenantId) like when using the Connect-ExchangeOnline PS cmdlet?  Or do we have to store the client secret in our script and use that to create an OAuth credential?

**Comment by ecederstrand** [comment]
There's no support in exchangelib for accessing a certificate thumbprint.

I have no idea how these local thumbprints work, and I don't have access to a Windows environment where I can test it out. I assume there are other packages or code snippets around that can handle the access to the thumbprint and get you to a point where you have a client secret that EWS OAuth needs, without having to store the secret in your script.

**Comment by ecederstrand** [comment]
Closing, as I don't think support for this functionality is something that should be included in exchangelib. Feel free to comment here if you have differing opinions.
