### ISSUE TITLE
Items not being deleted from folders

### ISSUE THREAD

**Issue by champlin2** [ecederstrand/exchangelib#1138]
For our automated tests we have a need to remove all items and folders (well those that are not system folders if there is a way to tell) from a mailfile before the next test runs.  I wrote a little script using exchangelib -- first we get the number of messages that are currently in the mail file (there is probably a much better way to do this but this was quick and dirty):

    total_docs = 0
    for folder in account.msg_folder_root.walk():
        total_docs += folder.total_count
        if after and folder.total_count > 0:
            print(f'{datetime.now().strftime("%Y-%m-%d %H:%M:%S")} {folder.total_count} items in {[folder.name](http://folder.name/)}')
    return total_docs

The 'after' flag defaults to False but after we call the next snippet to delete all the messages we get the count again and if there are items in any of the folders we report it.  To delete all the items we again loop over all the folders trying to delete each item and then we empty Recoverable Items and Trash:

    for folder in account.msg_folder_root.walk():
        for item in folder.all():
            try:
                item.delete()
            except ErrorCannotDeleteObject:
                print(f'Cannot delete item {[item.id](http://item.id/)} in {account.primary_smtp_address}')
               
        account.recoverable_items_deletions.empty()
        account.trash.empty()

However, after this completes and we call our function to get the number of messages it returns the same number as before the delete with the messages spread across the folders they were originally in.  Am I doing something wrong where it is not deleting the items like I think it should be?

Also, is there a way after deleting the items we can determine if a folder is a system folder or not and if not delete it?

**Comment by ecederstrand** [comment]
One thing to note is that the `total_count` value doesn't automatically update itself after deleting items in the folder. You have to do `some_folder.refresh()` to get the new count values.

If this doesn't help, then it would be useful to see the list of folders that still contain items. It's possible the they are e.g. archive folders that cannot be emptied.

Finally, the test suite in this project also needs to do what you're doing, except also deleting all folders that may have been created during tests. The code for doing this starts at https://github.com/ecederstrand/exchangelib/blob/8efeb6dda2b4305af59255ebc9d4aec306ea3cc2/tests/common.py#L160

**Comment by champlin2** [comment]
Thanks - changing to use wipe() and refresh() seems to have fixed the issue.  I did need to catch ErrorItemNotFound though as it seems that when it tried to delete items in the Contacts folder that it failed with "couldn't get properties".
