### ISSUE TITLE
Missing END:VCALENDAR for some expanded calendar events

### ISSUE THREAD

**Issue by laur89** [ecederstrand/exchangelib#115]
Quite sure it's bad data coming from the API, but wanted to confirm with you guys just in case.
Some events' `mime_content` (which is the .ical file) is missing the `END:VCALENDAR` line in the end, meaning additional logic is required to handle those cases. py3 example:

    import base64
    import arrow
    from tzlocal import get_localzone
    from exchangelib import DELEGATE, Account, Credentials, EWSDateTime

    def fetch_calendars():

        def sanitize(p):
            end = 'END:VCALENDAR\n'
            s = base64.b64decode(p).decode().replace('\r\n', '\n')
            if not s.endswith(end):
                s += end

            return s

        now = arrow.now()
        upper_limit = now.replace(days=+3)
        tz = get_localzone()

        items = ACCOUNT.calendar.view(
            start=tz.localize(EWSDateTime(now.year, now.month, now.day)),
            end=tz.localize(EWSDateTime(upper_limit.year, upper_limit.month, upper_limit.day)),
        )

        return [sanitize(elem.mime_content) for elem in items]

exchangelib doesn't process that data in any way, and it's simply bad data from the api?

**Comment by ecederstrand** [comment]
Which version of exchangelib is this?

You could enable DEBUG logging and have a look at the raw data coming over the wire. That would tell you where the problem is.

At least in version 1.9.1, we don't process `mime_content` in any way, except base64 decoding the string.

**Comment by laur89** [comment]
Ah sorry, ver is `1.8.1` (installed via `pip3` on debian testing)

**Comment by ecederstrand** [comment]
BTW, you should really use `EWSTimeZone` objects instead of `tzlocal` objects. This hides all the crazy timezone details that Microsoft decided was necessary.

**Comment by ecederstrand** [comment]
Try installing 1.9.1. I rewrite just about every line in the lib between those versions :-)

**Comment by laur89** [comment]
Noted, will give it a try.

Re. `EWSTimeZone` - would've used it, but didn't see a way to get an instance for local timezone. Wouldn't like to read `/etc/timezone` for that.

**Comment by ecederstrand** [comment]
Ah, I see what you mean. I added `EWSTimeZone.localzone()` in https://github.com/ecederstrand/exchangelib/commit/ba4d77dec75980b40236a271ae9df6aba1efb64b

**Comment by laur89** [comment]
Tried out 1.9.2, `EWSTimeZone.localzone()` works just fine.
Still seeing those missing `VCALENDAR` end lines. Guess it's just bad data from MS and have to live with it.

Thanks for your help.
