### ISSUE TITLE
Will OAuth2LegacyCredentials still work in 2023?

### ISSUE THREAD

**Issue by ms-coding** [ecederstrand/exchangelib#1152]
Hi, i just wanted to ask, if the OAuth2LegacyCredentials-Login will still work in 2023?
Microsoft is dropping the possibility to use Legacy-Login after 2022-12-31.

I don't know if the naming is just a coincidence and behind the scenes the OAuth2LegacyCredentials-Login does not depend on a real legacy-login (or purely on OAuth2, also in the name ;-) ), or if there is a problem rising in using it from then on.

I hope you understand my request, if not, just ask and i try to make it clearer.

Also many thanks for developing this awesome library, it gets a lot of work done for me :-)

**Comment by ecederstrand** [comment]
I have no idea, really. Since it's 2023 now, just give it a try :-)

`OAuth2LegacyCredentials` does send the username and password for authentication, so assuming this is what Microsoft is shutting down, then it will no longer work as an authentication method against Office365.

**Comment by ms-coding** [comment]
Up until now it works like a charm, no login-problems at all :-).
