### ISSUE TITLE
How do I restart the get_streaming_events connection without missing any emails?

### ISSUE THREAD

**Issue by malekhnovich** [ecederstrand/exchangelib#1153]
Looking for a way to better handle the timeout of `get_streaming_events`

**Describe the solution you'd like**
Either an extended timeout beyond the max 30 minutes or better handling/documentation on how to handle downtime between concurrent connections.
or can i just wrap it all in a `while` loop? but would that gurantee that nothing gets dropped. Probably not right?

```
while True:
        with STREAMING SUBSCRIPTION(connection_timeout=30) as sub:
                  get events ....
```

**Additional context**
Is the correct approach to sync items between connections or is there a better way to handle it. My concern is running into the issue where one connection expires before the other connection starts and emails get lost.

Thanks for all the help in advance and loving this library 

Max

**Comment by malekhnovich** [comment]
or can i just wrap it all in a `while` loop? but would that gurantee that nothing gets dropped. Probably not right?

```
while True:
        \t # WITH STREAMING SUBSCRIPTION(connection_timeout=30) as sub:
        \t # get events ....
```

**Comment by ecederstrand** [comment]
Streaming subscriptions are only meant to receive events that happen right now. You cannot stop a subscription, wait a but, and catch up on events that happened while you were not listening. If you want to do that, use pull subscriptions instead. They support watermarks that let you specify where you left off when requesting the next list of events.

**Comment by malekhnovich** [comment]
oh i see

```

def _filter_events(notifications, event_cls, item_id):
    events = []
    watermark = None
    for notification in notifications:
        logging.info(f"length of notification events: {len(notification.events)}")
        for e in notification.events:
            watermark = e.watermark
            if not isinstance(e, event_cls):
                continue
            if item_id is None:
                events.append(e)
                continue
            if e.event_type == event_cls.ITEM:
                if isinstance(e, MovedEvent) and e.old_item_id.id == item_id:
                    events.append(e)
                elif e.item_id.id == item_id:
                    events.append(e)
    return events, watermark


def pull_subs():
    existing_watermark = None
    previous_subscription_id = None
    # while True:
    while True:
        with account.inbox.pull_subscription(watermark=existing_watermark,timeout=500000000,event_types=["NewMailEvent"]) as (
            subscription_id,
            watermark,
        ):
            logging.info(f"Opening subscription...")
            import time
            logging.info(f"sleeping for 10")
            time.sleep(1000)
            
            notifications = list(inbox.get_events(subscription_id, watermark))
            events, _ = _filter_events(notifications, NewMailEvent, None)
            # created_events, watermark = _filter_events(notifications, CreatedEvent, None)
            if len(events)>0:
                [write_msg_event_to_eml_file(event) for event in events]
            logging.info(f"events: {events}")
            existing_watermark = watermark
        previous_subscription_id = subscription_id
```

**Comment by ecederstrand** [comment]
Yeah, that seems about right. There's some sort of timing issue with events in EWS, so I'm not very surprised you had to add the sleep. We do something similar in the test suite: https://github.com/ecederstrand/exchangelib/blob/05b7fde45d0a680269a5109c149e749af63f509b/tests/test_items/test_sync.py#L231

**Comment by malekhnovich** [comment]
awesome thanks for all the help Erik!
