### ISSUE TITLE
Upload calendar ICS file

### ISSUE THREAD

**Issue by rodrigues8** [ecederstrand/exchangelib#1154]
Good Morning!

I'm working on calendars with exchangelib, I would like to know if it's possible to upload a .ICS file, I've tried some ways but I couldn't.

Basically I'm creating a migration system for email calendars that use the CALDAV calendar, I thought that after generating the ICS I would be able to upload it to the exchange via EWS.

I know that in OWA there is an option to import a calendar via ics, I just don't know if the EWS has support for this function.

I would like to finish by thanking you for your great work, I've been using exchangelib for a while and it always helps me with internal projects.

**Comment by ecederstrand** [comment]
There's no built-in support for this, but there are Python libraries that can read .ics files. You could use that to translate to a `CalendarItem`.
