### ISSUE TITLE
Trying To Read Full conversation.

### ISSUE THREAD

**Issue by pchilate** [ecederstrand/exchangelib#1158]
**Issue**

I want to read the full conversation of an email.
I am able to establish the connection with the account using **exchangelib**

```python
credentials = Credentials(
            username = EMAIL,
            password = PASSWORD)

config = Configuration(service_endpoint=SERVICE_ENDPOINT, credentials=credentials)

a = Account(
                primary_smtp_address = EMAIL, 
                credentials=Credentials(EMAIL, PASSWORD), 
                autodiscover=False, 
                access_type=DELEGATE, config = config)
```

here I have one agent folder, inside that folder that particular email is there
this is the folder structure

```python
folder_ = a.root / 'Top of Information Store' / folder / agent
```
now I already have the conversation_id for the email that I want to read.

```python
convrsn_id = ConversationId(conversation_id)
```

here I am filtering the email using conversation_id on that particular folder, fetching only the required fields
and at last, I am printing the content of the email (**full conversation of that thread**)

```python
for email in folder_.filter(conversation_id=convrsn_id).only('subject','text_body','body','datetime_received','conversation_id')[:1]:
    email_subject = email.subject
    msg_uid = email.conversation_id.id
    email_date = email.datetime_received
    email_date = str(email_date)
    email_date = datetime.strptime(email_date, "%Y-%m-%d %H:%M:%S%z")
    email_content = email.text_body
    print("--------email content-----------")
    print(email_content)
```

but in the terminal after printing, I am not getting the latest msg of that thread if that msg is from my side (**reply msg**) but if the latest msg is from the sender (**customer**) I am getting full conversation on the terminal including that lastest msg.

**what is the issue??, why i am not getting the correct output??**

**Comment by ecederstrand** [comment]
Is the reply from you also located in `folder_`? Usually, sent emails are stored in the `a.sent` folder.

**Comment by ecederstrand** [comment]
@pchilate Did you solve this issue? Maybe you can get Outlook to show you in which folder the missing email is located?

**Comment by pchilate** [comment]
yes, somehow I am able to read the content, I use "item. body" to read that full thread.
is there anything so I can read full conversations between to people like msg by msg?

**Comment by ecederstrand** [comment]
When the email is sent from outside the organization, like your Gmail account, then the special Exchange conversation fields may not be set. In that case, you may have to look into email headers to link together the emails in the conversation. See `Item.headers`.

**Comment by nitin302** [comment]
Hello @pchilate could you share your working code for this? I am testing something similar.
