### ISSUE TITLE
add header to a created msg

### ISSUE THREAD

**Issue by frederickchai** [ecederstrand/exchangelib#116]
Hi,
I create a MessageHeader object (and added a name a value), after that I add it to the header list: _item.headers.append(custom_header)_ and **send_and_save** it, the problem is that when I retrieve this message its doesn't have the custom header that I added. How I can add this header to a message and send it to a folder in my account ??

**Comment by ecederstrand** [comment]
From what I've read, InternetMessageHeaders is read-only field in EWS, so we ignore it when saving. It may be possible to write headers somehow, I just haven't found a solution.

**Comment by ecederstrand** [comment]
For future reference, here's an article discussing message headers in EWS: https://msdn.microsoft.com/en-us/library/office/hh545614(v=exchg.140).aspx
