### ISSUE TITLE
Public Folders from Exchange Online are not accessible any more via Exchangelib

### ISSUE THREAD

**Issue by natenjo** [ecederstrand/exchangelib#1160]
### **Describe the bug**
Since beginning of 2023 we are unable to access Public Folders in Exchange Online.  Folders are not listed/loaded.
We first thought it was a issue as we didn't switch to oauth2 yet as other methods are depreciated  ([see Microsoft documentation](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#when-will-this-change-take-place))., but even after switching, the result stayed the same.

This is also neither a permission issue, as it is possible to access the public folders via Outlook.

In the discussion section to this project there seem to be at least tree people reporting the same technical issue: ( https://github.com/ecederstrand/exchangelib/discussions/1157 )

### **To Reproduce**

```
credentials = OAuth2Credentials(
 client_id='***', 
 client_secret='***', 
 tenant_id='***',
 identity=Identity(primary_smtp_address='***')
)

config = Configuration(
  server='outlook.office365.com',
  credentials=credentials,
)

my_account = Account(
  primary_smtp_address='***', 
  config=config,
  autodiscover=False, 
  access_type=DELEGATE
)

my_account.root.refresh()
my_account.public_folders_root.refresh()
print(my_account.public_folders_root.tree())
```

Result:
```
root@ubuntu:~# python3 test.py
IPM_SUBTREE
```

### **Expected behavior**
That the public folders are accessable when using exchgelib, as is was the case untill at lease end of 2022

### **Log output**
When doing the [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) . There are a lot of details, which I can't post publically.  **In the dubug xml file the folders are visible.  I _assume_ that Microsoft has changed something on the Exchange Online side slightly, resulting in Exchangelib to not interpret the result correctly**

### **Additional context**
Python version 3.10.6 
Exchangelib version 4.9.0
OS: Linux Ubuntu 22.04 LTS

**Comment by natenjo** [comment]
It is working again! 
I assume Microsoft fixed/changed something on their side, as we did not do any code changes,

**Comment by ecederstrand** [comment]
@skathepuri You'll need to provide more details if you want anybody to help you. Please file a new issue.

**Comment by skathepuri** [comment]
I am getting the following exception when I am trying to access the folders on the EWS:
raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)\nexchangelib.errors.ErrorAccessDenied: Not allowed to access Non IPM folder.

**Comment by ecederstrand** [comment]
That's what was reported in #1290
