### ISSUE TITLE
Shared RootOfHierarchy._subfolders_lock causes deadlocks

### ISSUE THREAD

**Issue by bn-crandom** [ecederstrand/exchangelib#1161]
**Describe the bug**
`RootOfHierarchy._subfolders_lock` is declared as a static variable, and despite being _used_ as an instance variable via `self._subfolders_lock`, it remains thus.  Our application uses one greenlet per mailbox being processed, and we're seeing frequent deadlocks where the process appears to hang completely.  I added a signal handler that dumps all greenet stacks and was able to capture the output below, and it indicates that most of the greenlets are deadlocked on trying to acquire `_subfolders_lock`.  

Given that each hierarchy root in each mailbox has an independent set of folders, I can't see a reason why they should need a share a lock . From the code, it looks like the sharing of the lock may have been unintentional.

**To Reproduce**
With most M365 tenants, we're seeing multiple deadlocks an hour.  With some, jobs manage to complete just fine.  It's unclear why the behavior is inconsistent.  Given that the deadlocks appear to be timing-based, it's probably just bad luck.

**Expected behavior**
Multiple greenlets should be able to process multiple mailboxes concurrently without blocking on non-shared resources.

**Log output**
[trace_sanitized.txt](https://github.com/ecederstrand/exchangelib/files/10414107/trace_sanitized.txt)

**Additional context**

Python: 3.7.8
exchangelib: 4.8.0

**Comment by bn-crandom** [comment]
@ecederstrand, this is our workaround to force non-shared locks.  It seems to be working:
```
    def create_account(self, mailbox):
        account = Account(primary_smtp_address=mailbox, config=self.ews_config, access_type=self.access_type)

        # Force each hierarchy root to use its own lock rather than a shared lock to prevent deadlocks [BCAS-286]
        account.root._subfolders_lock = Lock()

        # The account may not have personal archives or public folders, and requesting the root of either will result
        # in an EWS request, so only initialize the locks of these if the job is configured to use them
        if self.config.personal_archives:
            try:
                account.archive_root._subfolders_lock = Lock()
            except:
                pass

        if self.config.public_folders:
            try:
                account.public_folders_root._subfolders_lock = Lock()
            except:
                pass

        return account
        ```

**Comment by ecederstrand** [comment]
Thanks for the report! I agree this is an error. I'll see if I can come up with a fix shortly.
