### ISSUE TITLE
message_id__in filter stopped working on certain exchange accounts?

### ISSUE THREAD

**Issue by rajaramsrn** [ecederstrand/exchangelib#1164]
**Describe the bug**
This query filter message_id__in just stopped working against an exchange inbox:

filtered_items = service_account.inbox.filter(message_id__in=["DM***redacted***39@D******21.NA***9.PROD.OUTLOOK.COM",]).only("subject", "body", "datetime_received", "sender", "attachments", "headers")

filtered_items.count()
0

Just for contrast, the following works fine. But I was using the above pattern due to list I use in code and it used to work just fine until today!

filtered_items = service_account.inbox.filter(message_id__icontains="DM***redacted***39@D******21.NA***9.PROD.OUTLOOK.COM").only("subject", "body", "datetime_received", "sender", "attachments", "headers")

filtered_items.count()
1

**To Reproduce**
Just run the above message_id__icontains filter query on exchange email account using a list of message_id in a list.

**Expected behavior**
The query should simply be successful per its expectation

**Log output**
None

**Additional context**
exchangelib==4.9.0

**Comment by ecederstrand** [comment]
This looks like an account located on Office365. I assume this broke without you updating the exchangelib version. In that case, there's not much you can do if their indexing and search functionality no longer supports this type of search.

**Comment by ecederstrand** [comment]
@rajaramsrn Dod you find a solution to your problem?

**Comment by rajaramsrn** [comment]
> 

@ecederstrand Thanks. Sorry could not get back earlier. No I did not find a solution. It happened couple more times. in the last month. It fixes by itself again and pulls emails using the 'message_id__in'. 

I can only suspect some glitch at the Office365.  I am thinking I might have to use the 'icontains' as fallback.

**Comment by ecederstrand** [comment]
Ok. Closing since I don't think there's anything exchangelib can do to fix the issue. Feelr free to reopen if you disagree.
