### ISSUE TITLE
ReadingAttachments

### ISSUE THREAD

**Issue by pchilate** [ecederstrand/exchangelib#1165]
Hii @ecederstrand,

I am trying to read full conversations of specific emails with their attachments.but when there new message comes into thread with or  without any attachments, i am not getting the previous attachments in the thread

is there any way get previous attachments as well.

**Comment by ecederstrand** [comment]
Can you please post the code you are using to perform your task?

**Comment by pchilate** [comment]
convrsn_id = ConversationId(conversation_id)

credentials = Credentials(
                    username = login,
                    password = password)
                    
config = Configuration(service_endpoint=service_endpoint, credentials=credentials)

a = Account(
    primary_smtp_address = login, 
    credentials=Credentials(login, password), 
    autodiscover=False, 
    access_type=DELEGATE, config = config)

print("-------------Connection Established successfully----------------")


for email in folder_.filter(conversation_id=convrsn_id).only('subject','text_body','unique_body','body','datetime_received','author','to_recipients','cc_recipients','bcc_recipients','attachments')[:1]:
                        if email.attachments:
                            if os.listdir('/home/ubuntu/workspace/eclassifier-backend-phase2/backend/media/attachments/'):
                                for f in os.listdir('/home/ubuntu/workspace/eclassifier-backend-phase2/backend/media/attachments/'):
                                    print(f)
                                    os.remove('/home/ubuntu/workspace/eclassifier-backend-phase2/backend/media/attachments/'+f)
                            counter = 0
                            for attachment in an email.attachments:
                                counter += 1
                                if isinstance(attachment, FileAttachment):
                                    local_path = f'/home/ubuntu/workspace/eclassifier-backend-phase2/backend/media/attachments/{attachment.name}'
                                    with open(local_path, 'wb') as f:
                                        f.write(attachment.content)
                                    print('Saved attachment to', local_path)
                                    sub_preview['attachment_path_'+str(counter)] = local_path
                                elif isinstance(attachment, ItemAttachment):
                                    if isinstance(attachment.item, Message):
                                        print(attachment.item.subject, attachment.item.body)



Hii @ecederstrand,

above code, I am using for reading the full thread with attachments, 

1. when the thread starts (new email comes in folder_) with an attachment, and if I run this, I am able to read the message with its attachments.
2. when I reply to this email with a new attachment and run this again to read both the messages with their attachments (for the first email and the attachment that I have sent in reply), but in the output, I get only the latest attachment i.e I have sent in reply, not the previous one which came from sender first time.

**Comment by ecederstrand** [comment]
I think this is just an error in your script? Each time your for-loop handles a new email, you are deleting all attachments in your download folder and storing only the attachment contained in that email.
