### ISSUE TITLE
GetUserOofSettings not implemented?

### ISSUE THREAD

**Issue by nohir0** [ecederstrand/exchangelib#117]
is it possible to use the current exchangelib module to use the GetUserOofSettings operation?
https://msdn.microsoft.com/en-us/library/office/aa563465(v=exchg.150).aspx

I was not able to find a class/method for it...
Thanks in advance for your support!

**Comment by ecederstrand** [comment]
This service is not yet supported, unfortunately.

**Comment by nohir0** [comment]
Ok, thanks for the quick reply. I'll stick to the node ews module until then... unfortunately ;)

**Comment by ecederstrand** [comment]
In case anyone stumbles upon thi issue, getting and setting OOF messages was just implemented. See https://github.com/ecederstrand/exchangelib#out-of-facility
