### ISSUE TITLE
How to send email with auth_type=NOAUTH 

### ISSUE THREAD

**Issue by mbarre** [ecederstrand/exchangelib#118]
Hi,

I try to send email with auth_type=NOAUTH but I have this error :
```
    config = Configuration(service_endpoint=smtp_server, auth_type=NOAUTH, credentials=credentials)
NameError: global name 'NOAUTH' is not defined
```
It seems that NOAUTH is not accessible in the package description in _ _init__.py
```
from .transport import BASIC, DIGEST, NTLM
```
NOAUTH is missing.
 

Thanks in advance.

**Comment by ecederstrand** [comment]
It's not there because an Exchange server with no authentication is normally a really bad idea. But you can import it with `from exchangelib.transport import NOAUTH`
