### ISSUE TITLE
Pypi package contains additional files and fails to import

### ISSUE THREAD

**Issue by PHvL** [ecederstrand/exchangelib#1181]
**Describe the bug**
The pypi package of 5.0.0 cannot be imported. There seems to be a stray folder in /site-packages/exchangelib/autodiscover/discovery in addition to the file /exchangelib/autodiscover/discovery.py with removed code from 4.9.0.

**To Reproduce**
```python
import exchangelib
```

**Expected behavior**
This
```
ls /home/philipp/.local/lib/python3.9/site-packages/exchangelib/autodiscover/discovery/
base.py  __init__.py  pox.py  __pycache__  soap.py
```
should probably not be in the wheel (the source package seems to be fine).

**Log output**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philipp/.local/lib/python3.9/site-packages/exchangelib/__init__.py", line 1, in <module>
    from .account import Account, Identity
  File "/home/philipp/.local/lib/python3.9/site-packages/exchangelib/account.py", line 6, in <module>
    from .autodiscover import Autodiscovery
  File "/home/philipp/.local/lib/python3.9/site-packages/exchangelib/autodiscover/__init__.py", line 2, in <module>
    from .discovery import Autodiscovery, discover
ImportError: cannot import name 'Autodiscovery' from 'exchangelib.autodiscover.discovery' (/home/philipp/.local/lib/python3.9/site-packages/exchangelib/autodiscover/discovery/__init__.py)
```

**Additional context**
Python 3.9.2 (default, Feb 28 2021, 17:03:44) on Ubuntu 20.04

**Comment by oliverbeagley-pgg** [comment]
Same issue as above, manually deleting the folder allows the package to be importable so given it is not in the source tree I'm guessing thats the problem

**Comment by ecederstrand** [comment]
Thanks for the report! I'll fix this and release a new version tonight.
