### ISSUE TITLE
Access shared calendar

### ISSUE THREAD

**Issue by nico202** [ecederstrand/exchangelib#1184]
Hi, I know this has been answered elsewhere, but none of the option I'm trying seems to work.

I have a shared calendar I have access to via outlook web, as shown in the picture.
![image](https://user-images.githubusercontent.com/8214542/230353676-d40f2908-1d63-492f-a8d6-d42bc73763dc.png)

I can "view" the item as a `Message` in exchangelib with "(account.root / 'Common Views').all()".  How can I access to the calendar itself and add events to it?

I tried creating a delegate account with the sharer's email address

```
credentials = Credentials(username, password)
account = Account(username, credentials=credentials, autodiscover=True)
other = Account("other@company.xxx", credentials=credentials, autodiscover=True)

other.root.all()  ## fails with exchangelib.errors.ErrorAccessDenied.  
other.calendar ## fails with exchangelib.errors.ErrorFolderNotFound: No usable default <class 'exchangelib.folders.known_folders.Calendar'> folders

```

Also, various tests with ```SingleFolderQuerySet(account=claudio, folder=DistinguishedFolderId(``` leads to exchangelib.errors.ErrorInvalidSchemaVersionForMailboxVersion: Tried versions ('Exchange2016', 'Exchange2019', 'Exchange2015_SP1', 'Exchange2015', 'Exchange2013_SP1', 'Exchange2013', 'Exchange2010_SP2', 'Exchange2010_SP1', 'Exchange2010', 'Exchange2007_SP1', 'Exchange2007') but all were invalid

Do you have any hint?

Thanks, Nicolò

**Comment by nico202** [comment]
I finally found the "SharedFolderId" info on the outlook web client request log, used it in a single folder query set like this:
```
folder = SingleFolderQuerySet(
    account=account,
    folder=FolderId(id="XXX",
                    changekey="YYY"),
).resolve()
```

and it worked, but still I'd like to know what was the correct way to achieve it, thanks!

**Comment by ecederstrand** [comment]
Hi @nico202 I believe these menu items are special "NavLink" or "WunderBar" entries in the "Common Views" folder. According to [this answer on StackOverflow](https://stackoverflow.com/a/23773834/219640) you can extract the folder ID of the shared calendar using extended properties.

**Comment by ecederstrand** [comment]
@nico202 Did you manage to find a solution to your problem?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you find the time to get back to this issue.

**Comment by vjsingh** [comment]
@nico202 Any update here? We are experiencing a similar issue

**Comment by ecederstrand** [comment]
I think the recommendation is still to explore the WunderBar items as described in https://github.com/ecederstrand/exchangelib/issues/1184#issuecomment-1503354151

Feel free to post your solution here if you get something to work.

**Comment by claell** [comment]
Problem is that the NavLink / WunderBar items don't seem to contain the calendar folder id? At least that are my current results. I can get the NavLink item for "shared calendars" or "other calendars". But what to do with that item? I would think that this item contains information about several calendars shared with me. But I can't get further. I can extract some email address from the NavLink item, but that seemed to be a dead end as well, so far.

So as of now, I didn't find a way to do this without manually inspecting the request logs as @nico202 seemed to have done (not tested on my side, yet).
