### ISSUE TITLE
throws No compatible auth type was reported by server when using 5.0.2 version

### ISSUE THREAD

**Issue by Theepan15** [ecederstrand/exchangelib#1187]
We have been using this package for a quite a while now. I recently upgraded to 5.0.2. One of our email account throws this error.

Exception:  No compatible auth type was reported by server

However, it works with 4.9.0 version.  Here is the sample code.

**Comment by ecederstrand** [comment]
It's very helpful to provide the full stack trace instead of just the error message.

Anyway, it's not really possible to debug this without credentials to the server. Your best option is to [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and comparing the output between version 4.9.0 and 5.0.2.

The exception is thrown here: https://github.com/ecederstrand/exchangelib/blob/8f6ced514384d612aa9d14250dff4bade443a34b/exchangelib/transport.py#L160 so the two log lines emitted in that function may give you a hint about the issue.

**Comment by Theepan15** [comment]
Thank you for the quick response. I will generate the full stack trace and compare.

**Comment by Theepan15** [comment]
I tried the debug option. I noticed the following difference. Sorry I can not paste full debug messages due to sensitive info. 

lets say our company is ABC.ca

4.9.0
DEBUG:urllib3.connectionpool:https://webmail.ABC.ca:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0

Auth Type: NTLM

5.0.2
DEBUG:urllib3.connectionpool:https://ABC.ca:443 "POST /autodiscover/autodiscover.svc HTTP/1.1" 404 0

5.0.2 is trying to access a wrong URL. that is why there is no response for this.  Any help really appreciate. Thank you

**Comment by ecederstrand** [comment]
In the debug messages you posted, 5.0.2 is trying to autodiscover, while 4.9.0 already did that. 5.0.2 just hasn't found the right server yet.

Is that the last debug message before you get the stack trace in 5.0.2? I'd still like to see the full stack trace.

**Comment by Theepan15** [comment]
I replaced our company email with ABC.ca. Sorry about that, 

Email@ABC.ca
DEBUG:exchangelib.autodiscover.discovery:Waiting for autodiscover_cache lock
DEBUG:exchangelib.autodiscover.discovery:autodiscover_cache lock acquired
DEBUG:exchangelib.autodiscover.discovery:Cache miss for key ('ABC.ca', Credentials('domain\\username', '********'))
INFO:exchangelib.autodiscover.discovery:Step 1: Trying autodiscover on 'https://ABC.ca/autodiscover/autodiscover.svc' with email 'Email@ABC.ca'
DEBUG:exchangelib.autodiscover.discovery:Attempting to get a valid response from https://ABC.ca/autodiscover/autodiscover.svc
DEBUG:exchangelib.autodiscover.discovery:Checking if ABC.ca can be looked up in DNS
DEBUG:exchangelib.services.common:Calling service GetUserSettings
DEBUG:exchangelib.services.common:Trying API version Exchange2016
DEBUG:exchangelib.protocol:Server ABC.ca: Increasing session pool size from 0 to 1
DEBUG:exchangelib.transport:Trying to get response from https://ABC.ca/autodiscover/autodiscover.svc
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ABC.ca:443
Exception:  No compatible auth type was reported by server
DEBUG:urllib3.connectionpool:https://ABC.ca:443 "POST /autodiscover/autodiscover.svc HTTP/1.1" 404 0
DEBUG:exchangelib.transport:Request headers: {'User-Agent': 'exchangelib/5.0.2 (python-requests/2.28.2)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox': 'DUMMY@example.com', 'Content-Length': '899'}
DEBUG:exchangelib.transport:Response headers: {'Server': 'Microsoft-IIS/8.0', 'X-Powered-By': 'ASP.NET', 'Date': 'Wed, 26 Apr 2023 21:35:49 GMT', 'Content-Length': '0', 'Set-Cookie': 'NSC_JOty04dytcuob2m4o0zbpxmil2ewmjdyayvlbe=ffffffffaf11c24845525d5ff6694f58455e445a4a42384660;Version=1;Max-Age=3600;path=/;secure;httponly', 'Strict-Transport-Security': 'max-age=157680000'}
DEBUG:exchangelib.protocol:Server ABC.ca: Closing sessions

Process finished with exit code 0

**Comment by ecederstrand** [comment]
Thanks. I still really need the full stack trace. Please run your code without any try/except clauses and return the full output, so we can see full path the program chose to hit that exception.

**Comment by ecederstrand** [comment]
Hi @Theepan15 Can you give the referenced commit a try? I think it should fix your issue.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues with this.

**Comment by Theepan15** [comment]
Sorry , I was away from the office a couple of days. 
Thank you for fixing the issue. it works now. Are you going to update this fix in future version? Thanks

**Comment by ecederstrand** [comment]
Version 5.0.3 is out now.
