### ISSUE TITLE
message.body and message.text_body both None

### ISSUE THREAD

**Issue by Kclemen** [ecederstrand/exchangelib#1188]
**Describe the bug**
When the mail in outlook gives the message "no preview available" the message.text and message.body both result in None. Even though the mail does contain text input.

**To Reproduce**
Some mails in outlook give the status "no preview available", while others just show the preview (small text). When the preview is shown, also the message.body and message.text_body both work just fine.

**Expected behavior**
message.body and message.text_body should always show the content of the mail.

**Comment by ecederstrand** [comment]
Most probably, EWS does not return any data in these fields. You can check by [enabling debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and checking the XML document in the response from EWS.

I this is true, then you may still be able to access the text of the message via the `mime_content` field.

**Comment by Kclemen** [comment]
Thank you for your fast response.
I've copied the mime_content below:

`<t:MimeContent CharacterSet="UTF-8">UmVjZWl2ZWQ6IGZyb20gQU04UDE5M0                                                                                                             1CMTAxMC5FVVJQMTkzLlBST0QuT1VUTE9PSy5DT00gKDI2MDM6MTBhNjoyMGI6MWUxOjoxMCkNCiBieS                                                                                                             BQQVhQMTkzTUIxNjY0LkVVUlAxOTMuUFJPRC5PVVRMT09LLkNPTSB3aXRoIEhUVFBTOyBGcmksIDE0IE                                                                                                             FwciAyMDIzDQogMTM6MDA6MTkgKzAwMDANClJlY2VpdmVkOiBmcm9tIE1XNFBSMDNDQTAwMjUubmFtcH                                                                                                             JkMDMucHJvZC5vdXRsb29rLmNvbSAoMjYwMzoxMGI2OjMwMzo4Zjo6MzApDQogYnkgQU04UDE5M01CMT                                                                                                             AxMC5FVVJQMTkzLlBST0QuT1VUTE9PSy5DT00gKDI2MDM6MTBhNjoyMGI6MWUxOjoxMCkgd2l0aA0KIE                                                                                                             1pY3Jvc29mdCBTTVRQIFNlcnZlciAodmVyc2lvbj1UTFMxXzIsDQogY2lwaGVyPVRMU19FQ0RIRV9SU0                                                                                                             FfV0lUSF9BRVNfMjU2X0dDTV9TSEEzODQpIGlkIDE1LjIwLjYyOTguMzA7IEZyaSwgMTQgQXByDQogMj                                                                                                             AyMyAxMzowMDoxOCArMDAwMA0KUmVjZWl2ZWQ6IGZyb20gQ08xTkFNMTFGVDA3OC5lb3AtbmFtMTEucH                                                                                                             JvZC5wcm90ZWN0aW9uLm91dGxvb2suY29tDQogKDI2MDM6MTBiNjozMDM6OGY6Y2FmZTo6Y2IpIGJ5IE                                                                                                             1XNFBSMDNDQTAwMjUub3V0bG9vay5vZmZpY2UzNjUuY29tDQogKDI2MDM6MTBiNjozMDM6OGY6OjMwKS                                                                                                             B3aXRoIE1pY3Jvc29mdCBTTVRQIFNlcnZlciAodmVyc2lvbj1UTFMxXzIsDQogY2lwaGVyPVRMU19FQ0                                                                                                             RIRV9SU0FfV0lUSF9BRVNfMjU2X0dDTV9TSEEzODQpIGlkIDE1LjIwLjYyOTguMzYgdmlhIEZyb250ZW                                                                                                             5kDQogVHJhbnNwb3J0OyBGcmksIDE0IEFwciAyMDIzIDEzOjAwOjE3ICswMDAwDQpSZWNlaXZlZDogZn                                                                                                             JvbSBhMjctMjQ5LnNtdHAtb3V0LnVzLXdlc3QtMi5hbWF6b25zZXMuY29tICg1NC4yNDAuMjcuMjQ5KS                                                                                                             BieQ0KIENPMU5BTTExRlQwNzgubWFpbC5wcm90ZWN0aW9uLm91dGxvb2suY29tICgxMC4xMy4xNzUuMT                                                                                                             c3KSB3aXRoIE1pY3Jvc29mdCBTTVRQDQogU2VydmVyICh2ZXJzaW9uPVRMUzFfMiwgY2lwaGVyPVRMU1                                                                                                             9FQ0RIRV9SU0FfV0lUSF9BRVNfMjU2X0dDTV9TSEEzODQpIGlkDQogMTUuMjAuNjI5OC4zMyB2aWEgRn                                                                                                             JvbnRlbmQgVHJhbnNwb3J0OyBGcmksIDE0IEFwciAyMDIzIDEzOjAwOjE3ICswMDAwDQpGcm9tOiBUcm                                                                                                             FkaW5nVmlldyA8bm9yZXBseUB0cmFkaW5ndmlldy5jb20+DQpUbzogImt1cnQuY2xlbWVucy4xQG91dG                                                                                                             xvb2suY29tIiA8a3VydC5jbGVtZW5zLjFAb3V0bG9vay5jb20+DQpTdWJqZWN0OiBBbGVydDogMWggLS                                                                                                             AyNSAxLjcgUk1BIDEgMSAxIDQNClRocmVhZC1Ub3BpYzogQWxlcnQ6IDFoIC0gMjUgMS43IFJNQSAxID                                                                                                             EgMSA0DQpUaHJlYWQtSW5kZXg6IEFRSFpidEVRWmR1VCszOXNKVUt5Y0VjRENEOXZlQT09DQpEYXRlOi                                                                                                             BGcmksIDE0IEFwciAyMDIzIDE0OjAwOjE3ICswMTAwDQpNZXNzYWdlLUlEOg0KCTwwMTAxMDE4NzdmZG                                                                                                             EyZDJiLWQ0MzAxZmIyLWNkZTYtNDE4ZS05NzY3LTNlY2RkOGJlY2M1Mi0wMDAwMDBAdXMtd2VzdC0yLm                                                                                                             FtYXpvbnNlcy5jb20+DQpDb250ZW50LUxhbmd1YWdlOiBlbi1VUw0KWC1NUy1FeGNoYW5nZS1Pcmdhbm                                                                                                             l6YXRpb24tQXV0aEFzOiBBbm9ueW1vdXMNClgtTVMtRXhjaGFuZ2UtT3JnYW5pemF0aW9uLUF1dGhTb3                                                                                                             VyY2U6DQoJQ08xTkFNMTFGVDA3OC5lb3AtbmFtMTEucHJvZC5wcm90ZWN0aW9uLm91dGxvb2suY29tDQ                                                                                                             pYLU1TLUhhcy1BdHRhY2g6DQpYLU1TLUV4Y2hhbmdlLU9yZ2FuaXphdGlvbi1OZXR3b3JrLU1lc3NhZ2                                                                                                             UtSWQ6DQoJODhiN2IzZjEtMTQxMC00YjljLTc0MzAtMDhkYjNjZTgzMjc3DQpYLU1TLUV4Y2hhbmdlLU                                                                                                             9yZ2FuaXphdGlvbi1TQ0w6IC0xDQpYLU1TLVRORUYtQ29ycmVsYXRvcjoNClgtTVMtRXhjaGFuZ2UtT3                                                                                                             JnYW5pemF0aW9uLVJlY29yZFJldmlld0NmbVR5cGU6IDANCnJlY2VpdmVkLXNwZjogUGFzcyAocHJvdG                                                                                                             VjdGlvbi5vdXRsb29rLmNvbTogZG9tYWluIG9mDQogd2VzdC1zbXRwLnRyYWRpbmd2aWV3LmNvbSBkZX                                                                                                             NpZ25hdGVzIDU0LjI0MC4yNy4yNDkgYXMgcGVybWl0dGVkIHNlbmRlcikNCiByZWNlaXZlcj1wcm90ZW                                                                                                             N0aW9uLm91dGxvb2suY29tOyBjbGllbnQtaXA9NTQuMjQwLjI3LjI0OTsNCiBoZWxvPWEyNy0yNDkuc2                                                                                                             10cC1vdXQudXMtd2VzdC0yLmFtYXpvbnNlcy5jb207IHByPUMNCngtbXMtcHVibGljdHJhZmZpY3R5cG                                                                                                             U6IEVtYWlsDQpYLU1pY3Jvc29mdC1BbnRpc3BhbS1NYWlsYm94LURlbGl2ZXJ5Og0KCWFid2w6MDt3bD                                                                                                             oxO3Bjd2w6MTtrbDowO2R3bDowO2RrbDowO3J3bDowO3VjZjowO2ptcjowO2V4OjA7YXV0aDoxO2Rlc3                                                                                                             Q6STtPRlI6VHJ1c3RlZFNlbmRlckxpc3Q7RU5HOig1MDYyMDAwMzA1KSg5MDAwMDExNykoOTAwMTIwMj                                                                                                             ApKDkxMDIwMDIwKSg5MTA0MDA5NSkoOTA1MDAyMCkoOTA2NTAyNCkoOTEwMDMzOCkoNDgxMDAxMCkoND                                                                                                             kxMDAzMykoODgyMDA5NSkoOTU3NTAwMikoMTAxOTUwMDIpKDk0MzkwMDYpKDkzMTAwMTEpKDkyMjAwMz                                                                                                             EpOw0KWC1NZXNzYWdlLUluZm86DQoJcVplbGhJaVluUGt4ODRDTkg2QWVRczJyMW1mYng0NzVSaUk1Sz                                                                                                             ArWGIyZnZybnRCZlRKMTBOMnpOSXZjdnRmN1ZnWG1vL3JJaURUaVg5UzRxYUhaQi94N3ZHWWkrMjBqSH                                                                                                             ZSQnY1a1MyN083RkhERXdZOUU5cVlkdVNXS2ROcnZrVXFwQm1OWjdRbldLMkJVakhyVUlBPT0NClgtTW                                                                                                             Vzc2FnZS1EZWxpdmVyeTogVmoweExqRTdkWE05TUR0c1BUQTdZVDB3TzBROU1UdEhSRDB4TzFORFREMH                                                                                                             RNUT09DQpYLU1pY3Jvc29mdC1BbnRpc3BhbS1NZXNzYWdlLUluZm86DQoJPT91cy1hc2NpaT9RP25kNn                                                                                                             JCbEhmeVlRU1R4R2h6T0w2M2tYeWFDbWJPd3c0cVZvZE9pS2NQTEJpLytFblNST3VydVlMa0VGcD89DQ                                                                                                             ogPT91cy1hc2NpaT9RP1FWSkd3bDhvRTZIS3ZlUVlwSmlhQStCM2VtZFphZlViWFNtVW1HRCtuU3ZKM0                                                                                                             thUmdxSldBSWFvOHpDND89DQogPT91cy1hc2NpaT9RPzRoUDVRa2FBSGhGN3Z4MkZZNGI1TFVxZU9IbU                                                                                                             lPMTZ2VmpBNUZqcWJ3V2c0T2pqUmJ3Q2lIWkFnSnJGLz89DQogPT91cy1hc2NpaT9RPy9EMnk4bGxqWD                                                                                                             E2NE9FeVlKL3l0MGNJaW9wVkhKRlBMYjl3ZzhtZUEwY3lqVXltcmlETHdmUUh1WmlFQj89DQogPT91cy                                                                                                             1hc2NpaT9RP2RWWFZ4dGlOdTRGNnRKdndNZFZRdkNzQWpQcVUrMHR6SU9hMXR6R1V1MjB4SVNpeDVHM3                                                                                                             hGUDRKYmhnVT89DQogPT91cy1hc2NpaT9RP0svd0MrSEUzb2kxM1hSRWs2YlpTZ04reWw1YmpWRjVSMn                                                                                                             BpTXpKcy9Rdm15ZzBxZWthalJ2R2VTU1Zvaz89DQogPT91cy1hc2NpaT9RP0Q2OFJobFZGeEYrejQ4N1                                                                                                             NEL1d2T0hZMkFpbFhMa0Fod09aVEgxZmpYSVZuVkNTUWJJN3NTRG5zY0w1ZD89DQogPT91cy1hc2NpaT                                                                                                             9RP0ZyaVA4OU42US9XNURZb0ZLb1Z5L000ZFBOMXA1Qi9RbGxmTnErZG1RbHhBYTFFNE1DdU9sQ0R3eD                                                                                                             B6MT89DQogPT91cy1hc2NpaT9RP3VjSHJNVUVOQ1ZQOGc4WDRhQmZzTnFMZnFZbXFjL0I3U0REMzBhSn                                                                                                             l5T3JLcUJWUmFZUmowSVJwN1g5dD89DQogPT91cy1hc2NpaT9RP0VaYlZGeHYxYjkyS1NFeG5NSFcvUF                                                                                                             RsRThVNU81bzBLS28xOTRPSjVtM3JERXp2NUtxSXVuNDliMWdyYj89DQogPT91cy1hc2NpaT9RPy9rQz                                                                                                             IvUVRqUlFaSnh6THBlYXByYVdTajkxaGhjOXRabk1UTTRSYXFvbDIrdyt0TFhLaW1vdmFFNGkvaj89DQ                                                                                                             ogPT91cy1hc2NpaT9RP2NJbWlqZlNxK1VaTnNRWTFiRGtYRkE1NFgrU20veEtzUE4yMExZQXJ5a1owUX                                                                                                             pQTGdhY1JTTmNLeEFKMT89DQogPT91cy1hc2NpaT9RP2oyRWhYR2gyaWExVnQ1M0xPQXNLQkdVT1Q4dT                                                                                                             hCZ3hLNWpObDVpYkM4TU9pZlM2Mkx4cVBEMkRCYjNNdT89DQogPT91cy1hc2NpaT9RPzY3dkk2eG5CVm                                                                                                             h0R3NXRXprMmNXNDJhUERwK1M1TkFrSDhFRTFCYmhxSVJaODRmVnNWLzU2T2tvWkFkZz89DQogPT91cy                                                                                                             1hc2NpaT9RP0hlM3o4SW4yeWZzMEg3SGw2bk5sbUMxdURMa2lOb1dPQ2pLSmF4Yis3aVNmNlM2SFlOcF                                                                                                             FkYUdFYzJrVD89DQogPT91cy1hc2NpaT9RP0VWbWQ0RmFrd2E0aksyTlpEVjFJTHpzWjFDWTJ3dTYvd3                                                                                                             pPdFczUWk3cmdjOG5GSjBmZ3M5ekNUanpGYT89DQogPT91cy1hc2NpaT9RPzk1dU9yNjhTTzBmcUdDb0                                                                                                             03ZWprYTU1dTIraDhXTi9GT0c2TGZTdzd0WFpBZElpeDdQdVgzTmR4VjgrdD89DQogPT91cy1hc2NpaT                                                                                                             9RP3ZKU1I4Q3VVV0FWNVNJOGNUSVI2YklQckY2SnY2OTZRd1p2bFZwM3d1UmphOHZGMU52ZndDSGthbz                                                                                                             NNRT89DQogPT91cy1hc2NpaT9RP0doTlo5SzNSc0VZcFZyZUFONWJRajI0Qzd6Skx5Mzd4UFY5Qk5sVV                                                                                                             FoNXdFN3llZUFaWjFqczR4UW5YZD89DQogPT91cy1hc2NpaT9RP0pPZlVQV0MzaGw3alJScjhqdjh5Y0                                                                                                             JYbml1YVlxK1VNTjhaUUx6RHpKRjQ2dldUTWhXQ3ZBcDdVTG9SQj89DQogPT91cy1hc2NpaT9RP2wvaT                                                                                                             dhSkhrdENhdFRGUnk1a0lyRHdOeVFLd0xucFJJZFh6UVdtb1llejc4MDVxeitKQ2Z5QmNNdlBkMD89DQ                                                                                                             ogPT91cy1hc2NpaT9RPzFXcUptcnhrcmhOTi8reXRXQ0ZZV3hmVllWZ09rYVkybmhFbU9Wc0MxWDRZQ2                                                                                                             1yZUkvUGo3Tyt4VGxnOT89DQogPT91cy1hc2NpaT9RP3lobzZPaUJXNVUwbzZEZFNRMGJ2c2VCOTJuU0                                                                                                             JlcTgxRHZWd2R3cVlta1NuWFlKUFhPeEtzb0tXRElXaT89DQogPT91cy1hc2NpaT9RP3I4aS8vcEo5WV                                                                                                             plSXVXb0xMNmZ1UlNzcmg4VTdueFV0M2h2dm1NeG5sR2NRRDI1NE4wWUlreUo5UkJQTD89DQogPT91cy                                                                                                             1hc2NpaT9RP0Q1dURzR2hvb05TLzZ0cEtsUXd2dCtUV00xN0xMaXorPz0NCkNvbnRlbnQtVHlwZTogdG                                                                                                             V4dC9wbGFpbjsgY2hhcnNldD0idXMtYXNjaWkiDQpDb250ZW50LUlEOiA8NDhGNzhGNDBFMzhBNjg0QU                                                                                                             E0N0M5REEyQjk0Q0VDOTJARVVSUDE5My5QUk9ELk9VVExPT0suQ09NPg0KTUlNRS1WZXJzaW9uOiAxLj                                                                                                             ANCg0K</t:MimeContent>
`

**Comment by ecederstrand** [comment]
Ah, I meant `message.mime_content`, not the `MimeContent` element in the XML document.

Outlook probably also uses that to display the message text.

**Comment by Kclemen** [comment]
For the moment I can not further test it anymore because I do not have an email anymore with the issue.
For some reason when I use body instead of text_body the email got overwritten to an empty one.

**Comment by ecederstrand** [comment]
Ok. Closing, but feel free to reopen if you encounter this issue again.
