### ISSUE TITLE
Any Way To Fetch Categories of email from ModifiedEvent object in get_streaming_events

### ISSUE THREAD

**Issue by sonivi** [ecederstrand/exchangelib#1189]
Is there anyway to get categories from ModifiedEvent object obtained from get_streaming_events

```
credentials = Credentials(username=myuser", password=mypwd)
config = Configuration(credentials=credentials, service_endpoint=email_service_endpoint)
a = Account(primary_smtp_address=email, config=config, autodiscover=False, access_type=DELEGATE)
subscription_id = a.inbox.subscribe_to_streaming()
for notification in a.inbox.get_streaming_events(subscription_id, connection_timeout=STREAMING_TIMEOUT):
    events = notification.events
    # Is there any way to get email details from this events[0]. wanted to fetch email.categories without calling a.root.get(id=events[0].item_id.id)
```

**Comment by ecederstrand** [comment]
The API does not send this information. See https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/getstreamingevents-operation and https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/modifiedevent

**Comment by ecederstrand** [comment]
The suggested approach to efficiently get categories for a specific item given the item ID is to call `a.root.all().only("categories").get(id= item_id.id)`
