### ISSUE TITLE
Access to GAL

### ISSUE THREAD

**Issue by sbjhs** [ecederstrand/exchangelib#1190]
**Describe the bug**
OWA shows a directory with all other contacts belonging to the same organization. 

**Expected behavior**
A functionality to access this directory. 

**Additional context**
The GAL Contacts folder which is accessible through known folders and through the folder structure only includes contacts copied by the individual user from the GAL. 

It should be possible using the FindPeople function (https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/findpeople-operation): "Setting the DistinguishedFolderId to "directory" will search the GAL as the primary source of personas.". 

It is unclear to me how I can use the FindPeople function in exchangelib to query the GAL.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional questions.
