### ISSUE TITLE
Public folders support extracting access rights

### ISSUE THREAD

**Issue by iglimanaj** [ecederstrand/exchangelib#1194]
Hi community, 

Is it possible to retrieve the access rights structures that are associated with public folders in Outlook?

**Comment by ecederstrand** [comment]
A Folder object has the `permission_set` and `effective_rights` fields. Is that what you're looking for?

**Comment by iglimanaj** [comment]
@ecederstrand thanks for the quick reply. Yeah, from the first sight, that's what  I was looking for. I am closing this issue.
