### ISSUE TITLE
second call onwards to account.inbox getting stuck 

### ISSUE THREAD

**Issue by SPratapSingh** [ecederstrand/exchangelib#1198]
First call to account.inbox call is successfull and I am able to fetch all details whatever required. Any subsequent call from same server instance is getting stuck forever. This was not a problem before. My project has been running fine since 2 years. 

Below code I am using to get account:

```python
server = 'outlook.jpmchase.net'
cred = Credentials(username=username, password=password)
config = Configuration(server=server, credentials=cred, auth_type="NTLM", retry_policy=FaultTolerance(max_wait=300))
account = Account(primary_smtp_address=self._email_id, autodiscover=False,
                  config=config, access_type=DELEGATE)
account.protocol.TIMEOUT = 300
```

Please suggest

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues with this.
