### ISSUE TITLE
Task items don't populate the "Owner" field

### ISSUE THREAD

**Issue by Afterburned6387** [ecederstrand/exchangelib#120]
I am attempting to build some task automation, but I need the "Owner" attribute of Tasks to be correctly populated. EWS indicates it is a "read-only" attribute:

(https://msdn.microsoft.com/en-us/library/office/aa564312(v=exchg.150).aspx)

I would have assumed that it would auto-populate based on the account that created it, but that isn't working. I think it might have to do with the lack of support for the 'IsFromMe' field:

(https://msdn.microsoft.com/en-us/library/office/aa565618(v=exchg.150).aspx)

It would be easy enough to add the 'IsFromMe' field to the 'Task' Item as a BooleanField, but I just can't confirm if that would work. Anyone else have any ideas on how to get "Owner" working?

Thanks,

**Comment by ecederstrand** [comment]
I'm unsure you mean by "I just can't confirm if that would work".

Did you try to add an `IsFromMe` field to `Task`, and it didn't affect the "Owner" field when you save and refresh a task? Or are you having problems adding the field to exchangelib?

**Comment by Afterburned6387** [comment]
No, I was hoping someone (maybe you) would know more about the Owner field, and what affected it. Because it doesn't seem to be all that well documented on MSDN.

I'll create a branch and give it a test today to see if the "IsFromMe" field is the missing piece, and submit a merge request if so.

**Comment by ecederstrand** [comment]
I took a stab at this, but `IsFromMe` doesn't help the least. The `Owner` field simply isn't populated when I create a Task for myself.

There are some hints at https://github.com/jamesiarmes/php-ews/issues/308 Your best bet is probably to impersonate the user and create the task that way.

**Comment by ecederstrand** [comment]
Closing since I think this is just how EWS works. Feel free to reopen if you disagree or come up with a solution :-)
