### ISSUE TITLE
Inconsistency in retreiving / creating subfolders

### ISSUE THREAD

**Issue by BBArikL** [ecederstrand/exchangelib#1206]
**Describe the bug**
While searching for a folder in a automated script, the program looks for a sub-folder and if it can't find it, it will create it to move messages into it. However I just encountered an interesting problem: The folder could not be found (with `parent_folder / target_folder_name` syntax) but when it came to creating it (with `Folder(parent=parent_folder, name=target_folder_name)`), the server responded that it already existed! Upon investigation, the lookup had a character which was lower-case but upper-case on the server, making a difference between these two responses. If it can help pin down a specific case here it is:
* The folder is in a shared account of Microsoft 365
* The folder is many sub-folders deep (Account --> 'Information Store' --> 'Sub-folder 1' --> 'Sub-folder 2')

**To Reproduce**

1. Create an folder with any name (Lets say 'Family A')
2. Do a lookup on the folder name but this time with a little change in character casing (`Family a`) (with `/` syntax)
3. Catch ErrorFolderNotFound
4. Create a folder with the current parent folder and the target folder name (Any change in character casing will trigger this bug)
5. Get ErrorFolderExists

Sample code:
```python
from exchangelib import OAuth2LegacyCredentials, Configuration, Account, DELEGATE, Folder
from exchangelib.errors import ErrorFolderNotFound

exchange_client_id = ''
exchange_client_secret = ''
exchange_tenant_id = ''
exchange_username = ''
exchange_password = ''
exchange_server = ''
address = ''

content_folder_name = ''
sub_folder1_name = ""
target_folder_name = ""

credentials = OAuth2LegacyCredentials(
    client_id=exchange_client_id,
    client_secret=exchange_client_secret,
    tenant_id=exchange_tenant_id,
    username=exchange_username,
    password=exchange_password,
)
config = Configuration(server=exchange_server, credentials=credentials)
account = Account(
    primary_smtp_address=address
    if address is not None
    else exchange_username,
    config=config,
    autodiscover=False,
    access_type=DELEGATE,
)

content_folder = account.root / content_folder_name

sub_folder1 = content_folder / sub_folder1_name

try:
    target_folder = sub_folder1 / target_folder_name
except ErrorFolderNotFound:
    target_folder = Folder(parent=sub_folder1, name=target_folder_name)

    # Next line will trigger the exception:
    # exchangelib.errors.ErrorFolderNotFound: No subfolder with name <target_folder_name>

    # During handling of the above exception, another exception occurred:

    # exchangelib.errors.ErrorFolderExists: A folder with the specified name already exists.,
    # Could not create folder <target_folder_name>

    target_folder.save()


```

**Expected behavior**
I was expecting the folder lookup to match the one used in the server but it seem that MS servers treat folders as case-insensitive while the lookup is case-sensitive, provoking this error.

**Additional context**
Python: 3.11.4
exchangelib: 5.0.3

Thank you for this great library and have a great day!

**Comment by ecederstrand** [comment]
Thanks for the report! I agree this is a bug.

Case-insensitive folder name handling isn't covered by the test suite. I'll write some tests and fix anything that comes up.
