### ISSUE TITLE
Add ability to create, modify, and delete distribution lists in Exchange Online.

### ISSUE THREAD

**Issue by isaiahh1013** [ecederstrand/exchangelib#1207]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
If this is concerns missing functionality from EWS, please provide links to this feature in MSDN.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional questions related to this.
