### ISSUE TITLE
 The license is invalid for this mailbox

### ISSUE THREAD

**Issue by trekker25** [ecederstrand/exchangelib#1209]
Since about a month I have been accessing a mailbox that is on Exhange Online using OAuth2:

credentials = OAuth2Credentials(client_id=AZURE_CLIENT_ID, client_secret=AZURE_CLIENT_CREDENTIAL, tenant_id=AZURE_TENANT_ID , identity=Identity(primary_smtp_address=MAILBOX_3CX))

Has been working perfectly, but suddenly last night we get this message back:

exchangelib.errors.ErrorInvalidLicense: The license is invalid for this mailbox., Mailbox 'c0593cae-2dea-4178-aecf-63d6b17809e7' doesn't have a valid license.

The Mailbox doesn't have a Business Premium license, but last month it still worked.  Is this some kind of a grace period in which you can use the mailbox using Exchange Online?

In the meantime, i will contact my hoster, if a single Exchange Online license can be provided without a very expensive Business Premium license.

**Comment by ecederstrand** [comment]
exchangelib is just a client for EWS. It doesn't handle any licensing. You'll have to work out this issue with Microsoft support.
