### ISSUE TITLE
Glob uses rsplit

### ISSUE THREAD

**Issue by LevitatingOrange** [ecederstrand/exchangelib#1212]
Hello, 

I have trouble getting `Folder.glob` to work for deeper nested glob patterns. The issue seems to stem from using `rsplit` inside
the `_glob` function of `Folder`:
 
https://github.com/ecederstrand/exchangelib/blob/2115c62138f517335f4c9a9b54ab3397076940b1/exchangelib/folders/base.py#L151

If we for example have the pattern `root/inbox/todos`, then `glob` won't return any folder entry even if the path exists. `rsplit('/', 1) will split on the first `/` it encounters *from the right*  but then stop, e.g.

```python
"root/inbox/todos".rsplit('/', 1) # will return ["root/inbox", "todos"]
```

Afterwards `glob` matches each child of the folder with the first part of the returned array, e.g.
```python
fnmatch('root', 'root/inbox') # will return false
```
 I think it should be `split` not `rsplit`. `split` splits starting from the left and would correctly only use `root` as the argument to `fnmatch`. 

Did I miss something here? If my assumptions are correct I am happy to submit a small pull request to remedy this issue.

**Comment by ecederstrand** [comment]
Which globbing patterns did you try? And which results did you expect for those patterns?

**Comment by LevitatingOrange** [comment]
In an EWS store where the folder at path 'Top Of Information Store/Other/TODO' exists, 
the glob 'Top Of Information Store/Other/TODO' returns an empty iterator, instead of one whose only returned element is the folder 'TODO'
