### ISSUE TITLE
GCCH support

### ISSUE THREAD

**Issue by UnhappyHermes** [ecederstrand/exchangelib#1213]
Have you seen any success with attempts to connect to accounts in gcch? When I attempt to connect, it always responds that the client is not supported in cross cloud requests.

**Comment by ecederstrand** [comment]
What is GCCH?

**Comment by ecederstrand** [comment]
I haven't heard any reports of failure nor success with that environment. I assume authentication is further restricted than standard OAuth on O365, so you would probably need to contact Microsoft support to find out how to authenticate against GCCH.

**Comment by ecederstrand** [comment]
Closing, but please update us here if you have any success accessing a GCCH environment.
