### ISSUE TITLE
Question: ImportError: cannot import name 'Credentials' from partially initialized module 'exchangelib'

### ISSUE THREAD

**Issue by scheung38** [ecederstrand/exchangelib#1214]
Trying to connect to my outlook email account

> pip install exchangelib

email.py

```
from exchangelib import Credentials, Account

credentials = Credentials(EMAIL, PASSWORD)
account = Account(EMAIL, credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)

```

Then:

> python sample.py

File "$HOME/email.py", line 1, in <module>
    from exchangelib import Credentials, Account
ImportError: cannot import name 'Credentials' from partially initialized module 'exchangelib' (most likely due to a circular import) ($HOME/.venv/lib/python3.11/site-packages/exchangelib/__init__.py

python 3.11.4

What did I do wrong anyone, thank you.

EDIT:

Fixed now, changed file name to anything but email.py

**Comment by ecederstrand** [comment]
Yeah, that's a common Python gotcha. Don't Name your scrips the same as built-in modules: https://docs.python.org/3/library/email.html
