### ISSUE TITLE
Discrepancy between timestamps viewed on Microsoft Web Mail vs the timestamps on the emails downloaded using exchangelib.

### ISSUE THREAD

**Issue by ahiremath123** [ecederstrand/exchangelib#1215]
Problem Description : When I log into my shared mailbox using my ASIAPAC credentials , I can view the timestamps on my email which is consistent with what other members of the mailbox can see, these users are in domains other than ASIAPAC.
But when I download these emails into my database, I clearly see that there is an additional 4 hours added to the timestamp of the email.

Could you kindly suggest a method where I can download these emails , keeping the original timestamps intact. I don't want these timestamps to change according to my local time zone.

I have tried setting the "default_timezone" parameter in the Exchange server user accounts class parameter to 'None' and even to the time zone where the particular mailbox is located using EWStimezone(key=<required timezone>), still it shows the timestamps with an offset of 4 hours.

Is there a way to actively ignore the time zone information and get the timestamps as it if from the shared mailbox.

**Comment by ecederstrand** [comment]
Possibly related to #541. Do you see this warning when downloading emails?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you get time to revisit this.
