### ISSUE TITLE
create_reply_all has me in the list of recipients

### ISSUE THREAD

**Issue by claell** [ecederstrand/exchangelib#1218]
**Describe the bug**
This seems to be wanted as of https://github.com/ecederstrand/exchangelib/issues/522#issuecomment-446094726. However, in Outlook, for example, reply all won't have me as recipient (unless I was the only recipient, I think). This behavior also leads to a small side bug: If I am in the recipients of the email, I am added twice as recipient for the reply all.

**To Reproduce**
Can be delivered if needed.

**Expected behavior**
Don't add me to the list of recipients 

**Log output**
None

**Additional context**
Both up to date, can give more details if needed.

**Comment by claell** [comment]
https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/items/message.py#L145 <- This seems to be the problematic part. Also, can it happen that this logic will lead to having no recipients at all?

**Comment by ecederstrand** [comment]
I can't recall why that code was added. Since a `Message` item has both `sender` and `author` fields, it could be that it was added in case those two fields are different. We could add a check that they are at least different. And also add `sender` or `author` when `to_recipients` is empty?

**Comment by claell** [comment]
Seems like it was added after https://github.com/ecederstrand/exchangelib/issues/522#issuecomment-446094726 in https://github.com/ecederstrand/exchangelib/commit/bb5927285e61d60fd64e6f8d8e05b5f1a29c95fb. In the comment, you say:

> I agree that reply_all() should default to sending to both self.to_recipients and self.author.

Not sure, why, though.

The code doesn't use `sender` as of now, so not sure, can this be a reason for it, then?

**Comment by ecederstrand** [comment]
When you have a message in your inbox, then `sender` and/or `author` will contain the person who sent the email. When you reply to all, wouldn't you expect that person to be in `to_recipients`? Or maybe I'm misunderstanding something?

**Comment by claell** [comment]
Ah, possibly, I misunderstood the meaning of `self.author`. I thought that field always referred to me, not the message author. Now, it makes sense to me. Still, somehow, the behavior is broken. Maybe, it's because I am (of course) on the recipients of the email. So then, when I send the reply, I am added back to it, which is unwanted.

I had a test email sent from me to my account. When I used reply_all, it had me listed twice for the recipients.

Also, on another email, I was added to the recipients of reply_all (there only once; I guess because I wasn't sender of the original email).

**Comment by ecederstrand** [comment]
Ah, so you want `self.account.primary_smtp_address` removed from `to_recipients`, and probably also `author` if that argument is passed to `reply_all()`. That makes sense.

**Comment by claell** [comment]
I guess. I think, I did some wrong interpretations what caused the problems, based on my short tests with this lib.

**Comment by claell** [comment]
Looks that I tested with two edge cases, before, and I interpreted things not in a correct way.

The first test was with an email sent from me to me. There, the reply_all adds me twice to recipients. Expected behavior: Only add me once (but don't remove me completely, because I was the only sender of the email).

The second test was a reply to an email sent from a mailing list on behalf of me. There, I also was added as recipient for reply_all; probably because the email was sent on behalf of me. Not sure what the expected behavior would be in such cases. In the current case, I didn't want me as recipient of my reply, but there might be other cases where that is wanted?

A new test with a more normal scenario: I was in the recipients of the email (CC). In the reply_all email, I am also in CC of that email. This is unwanted.

I hope, this more detailed description helps a bit with improving the current situation.

**Comment by claell** [comment]
Thank you very much for the quick fix!

**Comment by claell** [comment]
> and probably also `author` if that argument is passed to `reply_all()`. That makes sense.

That part, which I now finally understand, is still not implemented from what I see. For me, it is not really relevant right now. Just wanted to add a note, so it's not forgotten.

**Comment by claell** [comment]
I recently discovered a problem with the fix: The order of the recipients is not the same as in Outlook. I need to check again, what exactly is happening in which case.
