### ISSUE TITLE
Localization for replies

### ISSUE THREAD

**Issue by claell** [ecederstrand/exchangelib#1219]
**Is your feature request related to a problem? Please describe.**
When creating a reply, the relevant fields are not localized:

![grafik](https://github.com/ecederstrand/exchangelib/assets/6171135/7474ccf8-691c-4f84-b1cb-14f815e734e6)

**Describe the solution you'd like**
Not sure whether there is an easy way to have them localized and behave like they would in normal Outlook.

**Describe alternatives you've considered**
I didn't find a straightforward workaround to this, but maybe, there is one.

**Additional context**
None

**Comment by ecederstrand** [comment]
Weird. We don't specify any localization, I don't think the [CreateItem](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/createitem-operation) service supports localization, and we don't hardcode any of those values.

**Comment by claell** [comment]
Just to be sure, the wanted behavior is that the fields are in German, not English. Are you saying this should work, or that this isn't possible?

**Comment by ecederstrand** [comment]
I'm saying that it surprises me that your email client doesn't show these fields in the localization you chose in that client. We don't make any attempt in exchangelib to specify the localization of emails, AFAIK, so I'm curious what's different in the emails sent by exchangelib compared to the other emails in your inbox.

**Comment by claell** [comment]
Ah, okay. I am using Outlook 365, so pretty standard client. Its language is German.

But are that really fields are dynamic, so they can be localized? To me, they just seem hardcoded in the message HTML body, no?

**Comment by ecederstrand** [comment]
Thy comparing two emails, one where the fields are localized, and one where they aren't. That will hopefully tell you what the difference is. You may have to dive into `mime_content` to find the difference.

**Comment by claell** [comment]
After finding out, how to view the source in Outlook (and through exchangelib):

One from exchangelib:
```
<o:p></o:p></span></p><div class=MsoNormal align=center style='text-align:center'><span style='mso-fareast-font-family:"Times New Roman"'><hr size=2 width="98%" align=center></span></div><div id=divRplyFwdMsg><p class=MsoNormal><b><span lang=EN-US style='mso-fareast-font-family:"Times New Roman";color:black;mso-ansi-language:EN-US'>From:</span></b><span lang=EN-US style='mso-fareast-font-family:"Times New Roman";color:black;mso-ansi-language:EN-US'> Ellsel, Claudius Matts<br><b>Sent:</b> Freitag, 25. August 2023 19:09:07<br><b>To:</b> Ellsel, Claudius Matts<br><b>Subject:</b> Test</span><span lang=EN-US style='mso-fareast-font-family:"Times New Roman";mso-ansi-language:EN-US'> <o:p></o:p></span></p><div><p class=MsoNormal>
```

And one from Outlook:
```
<div style="border:none;border-top:solid #E1E1E1 1.0pt;padding:3.0pt 0cm 0cm 0cm">
<p class="MsoNormal"><a name="_MailOriginal"><b><span style="mso-fareast-font-family:&quot;Times New Roman&quot;">Von:</span></b></a><span style="mso-bookmark:_MailOriginal"><span style="mso-fareast-font-family:&quot;Times New Roman&quot;"> Ellsel, Claudius Matts &lt;mail@adress.com&gt;
<br>
<b>Gesendet:</b> Freitag, 25. August 2023 18:36<br>
<b>An:</b> Ellsel, Claudius Matts
```

Sorry in advance for the bad formatting etc. To me, it looks like the values are hardcoded in HTML? Or can this change dynamically?

**Comment by ecederstrand** [comment]
Yeah, that's Outlook applying its own formatting in HTML. exchangelib just sends a `ReplyAllToItem` item to the server and lets Exchange handle any formatting of the reply item.

You can do the same in exchangelib by creating an `HTMLBody` object that formats the reply the same way Outlook does it.

**Comment by claell** [comment]
So the HTML is generated on Client side, not from the Exchange server or exchangelib?

**Comment by ecederstrand** [comment]
exchangelib doesn't do any automatic HTML formatting. That's out of scope of the library.

**Comment by claell** [comment]
Okay. But I'd guess the HTML is then built by the Exchange server from the `ReplyToAllItem`? At least I never heard of a recipient client localizing HTML on the fly when viewing an email.

If that assessment is correct, maybe it's possible to tell the Exchange server how it should format the reply HTML?

**Comment by ecederstrand** [comment]
I don't think it is. But if you want better control of the reply message, you can just create a full `Message` item where you specify the HTML body and other fields exactly the way you want it. `ReplyToAllItem` is just a helper to create simple replies.

**Comment by claell** [comment]
Problem is that this manual approach will be error-prone and time-consuming.

Right now, it seems that it is not even clear where exactly these fields are added (Exchange mail server side or viewing email client side)?

If it's Exchange server side, maybe one can send additional information to it to tell it how one expects the server generated reply message to be localized.

**Comment by ecederstrand** [comment]
> Problem is that this manual approach will be error-prone and time-consuming.

That's exactly why we don't attempt to do it in this library. We're not Outlook, or a full-fledged email client, and don't want to be.

`If it's Exchange server side, maybe one can send additional information to it to tell it how one expects the server generated reply message to be localized.`

I haven't seen anything in the EWS docs on MSDN mentioning this possibility.

**Comment by claell** [comment]
I haven't looked much into this and are not experienced with it, though. Maybe that item (https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/replyalltoitem) doesn't support it, as you suggest. And possibly, Outlook doesn't use that item for their reply all feature, but also builds a full `Message` item for that.

**Comment by claell** [comment]
For now, I understand that this is out of scope for this library and that either one would need to implement the functionality manually or find a way how to do this with EWS, so this library can add support for it.

I'll close this, then. Thank you very much for your support!
