### ISSUE TITLE
Extract date and time mail sent

### ISSUE THREAD

**Issue by 16msp** [ecederstrand/exchangelib#122]
Is it possible to extract date and time a mail has has been sent by the sender ? If yes how ...

**Comment by ecederstrand** [comment]
A `Message` has the `datetime_sent` attribute, but I think it's only populated if the email was sent *from* the account, not if it was received from an external sender. Your next best option is the `datetime_received` attribute, which is hopefully not too far off from the time the email was sent.

You could also sift through the `headers` dict and see if any of those contain what you want, but EWS is quite bad at handling Internet message headers (see #116).

**Comment by 16msp** [comment]
Thnkssss
