### ISSUE TITLE
Replies don't always retain the conversation_id

### ISSUE THREAD

**Issue by claell** [ecederstrand/exchangelib#1223]
**Describe the bug**
This seems to be a known problem (#703 #642). However, I see that for the `create_reply` and `create_reply_all` functions, sometimes, the `conversation_id` is retained, and sometimes it is not. I guess this is due to some automatic detection by EWS.

**To Reproduce**
None

**Expected behavior**
Outlook does set this reliably for the affected cases, if I create the reply (draft) there.

I was wondering, what causes this behavior, and whether there are ways to make this work.

**Log output**
None

**Additional context**
None

**Comment by claell** [comment]
After experimenting a little, I saw that sometimes, the `subject` is a little different from the `conversation_topic`. For example, in a mailing list, the subject contains "[list-name]" as prefix, whereas conversation_topic doesn't contain that prefix. In the past, I set the reply subject based on the original subject. That then causes apparently also makes the reply conversation topic to contain the mailing list prefix. In such cases, the reply (draft) is not seen as part of the conversation and has a different `conversation_id`.

Example:

Original message:
subject: `[list-name] some subject`
conversation_topic: `some subject`

Reply (draft) based on the original subject <- this message has a different conversation_id after creating it:
subject: `RE: [list-name] some subject`
conversation_topic: `[list-name] some subject`

Reply (draft) created without the mailing list prefix <- this message has the original conversation_id after creating it:
subject: `RE: some subject`
conversation_topic: `some subject`

I also found https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-work-with-conversations-by-using-ews-in-exchange

> Exchange applies the same ConversationTopic value to replies to the first message and then updates the ConversationIndex value to represent the message's position relative to the original message. If the subject of the email thread changes, Exchange applies a new ConversationTopic value and new ConversationIndex values to the new conversation.

Not sure whether that is connected.

For now, I'll use the conversation topic as base for the reply subject. Hopefully, that will work reliably.

**Comment by ecederstrand** [comment]
Thanks for the details investigation! `conversation_id` and `conversation_topic` fields are read-only and their value are determined by the Exchange server, as you've also found out.

I'm not sure there's anything more we can do in exchangelib in this area.

**Comment by claell** [comment]
That's alright. I was mainly looking for ways how to be able to achieve what I want (having Outlook/Exchange treat messages as conversations when I want them to).

Apparently, I found a way (or a cause why it hasn't been the case before for some messages).

Then, I am happy to close this issue again for now.
