### ISSUE TITLE
Filter "sender" for getting messages from inbox doesn't work correctly

### ISSUE THREAD

**Issue by Maksim75ru** [ecederstrand/exchangelib#1224]
I use version 4.9.0 and found a bug:
Firstly, I connected to the target mailbox and get account. Then I tried to get messages from the target sender.
I set filter, but I didn't get any messages. Then I started to found out a solution. Worked only one filter, it's `sender_icontains=` and when I delete a last letter from sender_email...It's really strange. 
I used different filters like `sender__in=`, `sender__contains=`, `sender=`, but it didn't work.

I update version to 5.1.0 and I didn't get messages. I used all filters that I mentioned before, but no one worked. I also try them with deleting a last letter from sedner_email, but it didn't work.

Can you fix it?

![photo_2023-09-07 21 50 22](https://github.com/ecederstrand/exchangelib/assets/60866480/e8a529bc-e5c8-49fc-8cf0-fcbdc6fc8646)
![photo_2023-09-07 21 50 25](https://github.com/ecederstrand/exchangelib/assets/60866480/b6eb1090-6ec7-458f-b71d-de272e7de651)

**Comment by ecederstrand** [comment]
If you enable [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) you can see the exact XML request document exchangelib sends. Can you capture the `FindItem` request sent in 4.9.0 and in 5.1.0 and check what the difference is in your case?

**Comment by Maksim75ru** [comment]
v 4.9.0

![4 9 0 sender__in](https://github.com/ecederstrand/exchangelib/assets/60866480/6151cf70-2022-421d-8111-1d1abcc82aca)

![4 9 0 sender__icontains](https://github.com/ecederstrand/exchangelib/assets/60866480/a6976872-5d74-4410-a234-1e3ad203047e)

**Comment by Maksim75ru** [comment]
v 5.1.0

![5 1 0 sender__icontains](https://github.com/ecederstrand/exchangelib/assets/60866480/b468ff42-275f-4860-9dee-5aeb3a3574f4)

![5 1 0 sender__in](https://github.com/ecederstrand/exchangelib/assets/60866480/f796c065-38b2-469e-b390-f87f3e6dc4e9)

**Comment by Maksim75ru** [comment]
Today I could't catch any messages. I used v 4.9.0 and 5.1.0 and different filters like `sender__in`, `sender__icontains`, `sender__contains`, and just `sender`. And also I delete the last letter in the email (It worked before, when I created this topic), but today it didn't work((

**Comment by ecederstrand** [comment]
Ok. It's really difficut from the screenshots to see what the difference is between the two. But filtering on sender email has historically been flaky in Exchange, so it's possible that this is a server issue rather than an issue in exchangelib.
