### ISSUE TITLE
Problem with Credentials: AttributeError: 'NoneType' object has no attribute 'count'

### ISSUE THREAD

**Issue by Katesib** [ecederstrand/exchangelib#1226]
Hello! 
My code works on the local machine (Windows), but doesn't work on the VM (Linux). 

I use exchangelib=5.1.0

credentials = Credentials(username=DOMEN_MAIL, password=MAIL_PASSWORD)
account = Account(
        primary_smtp_address=ADDRESS_FROM,
        credentials=credentials,
        autodiscover=True,
    )

DOMEN_MAIL like "domain\\username"
ADDRESS_FROM like "username@domain.ru"

Error on the VM:
![image](https://github.com/ecederstrand/exchangelib/assets/31221083/8b35a4ad-a66b-4a18-945e-69acad5c3fc3)
But username doesn't contain '@'...

Could there be a problem with the operating system?  
What am I doing wrong? Thanks a lot!

**Comment by ecederstrand** [comment]
You’re somehow passing `None` as `username` attribute to the `Credentials` class. You need to check what your `DOMEN_MAIL` actually contains when you get the exception.
