### ISSUE TITLE
No Body element in SOAP response

### ISSUE THREAD

**Issue by hamzaalmali** [ecederstrand/exchangelib#1229]
Hello, I have integrated the library into my django application, but when I say bring the first 10 mails, it brings the mails, but immediately afterwards it gives the error No Body element in SOAP response, or when I send the mail, it sends the mail, but immediately afterwards No Body element in SOAP response, can you help me overcome this problem?

The exchange server I use has disabled access to e-mail via the browser, access is only possible through the Outlook application.

**Comment by ecederstrand** [comment]
Please post the stack trace you get. Additionaly, please record the last XML request and XML response that contains the error message. See https://ecederstrand.github.io/exchangelib/#troubleshooting on how to capture the XML. Thanks!
