### ISSUE TITLE
In-Place Archive Mails Search

### ISSUE THREAD

**Issue by kashyapwwwgmailcom** [ecederstrand/exchangelib#1230]
I am not able to search mails in In-Place Archive. 

So far, I have successfully listing mails in Inbox and Archive, but not in Office365 Exchange In-Place Account.

Please help me hot to go inside In-Place Archive using exchangelib

**Comment by ecederstrand** [comment]
What did you try so far? The archive folders should be available via `Accountarchive_msg_folder_root`. See https://stackoverflow.com/a/36978106/219640

**Comment by kashyapwwwgmailcom** [comment]
To get mail folders list in Inbox I have used the follwoing code
a = Account(username, credentials=credentials, autodiscover=True, config=config, access_type=IMPERSONATION)
folder = a.inbox.parent
all_folders = folder.glob('**/*')

**Comment by ecederstrand** [comment]
That example code doesn't really make sense. `testfolder` is undefined, so it doesn't look like you're searching within `a.archive_msg_folder_root` at all.

**Comment by kashyapwwwgmailcom** [comment]
To get mail folders list in Inbox I have used the following code:

a = Account(
    username, credentials=credentials, autodiscover=True, config=config, access_type=IMPERSONATION
)
folder = a.inbox.parent
all_folders = folder.glob('**/*')
**for testfolder in all_folders:**
for item in testfolder.all().only('sender').order_by("-datetime_received")[:100]:
    print(item.sender)

But if I do the following to get mail in In-Place Archive, nothing is returned:

folder = a.archive_msg_folder_root.children
all_folders = folder.glob('**/*')
**for testfolder in all_folders:**
for item in testfolder.all().only('sender').order_by("-datetime_received")[:100]:
    print(item.sender)

**Comment by ecederstrand** [comment]
Just try:

```python
for item in a.archive_msg_folder_root.walk().all().only('sender').order_by("-datetime_received")[:100]:
    print(item.sender)
```

If that doesn't work, then Office365 is getting the emails it displys in its In-Place Archive from somewhere else. I don't know where that would be.

**Comment by ecederstrand** [comment]
Hi @kashyapwwwgmailcom Do you ever find a solution to your issue?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you get back to this.

**Comment by rwludwig** [comment]
Hi Erik, love the library and thank you for making your work openly available.

I'm having problems accessing the In-Place Archive on some accounts and thought to comment here. I can open a new issue if you think it more appropriate.

I'm trying to access several "Online Archive" enabled O365 accounts. The archive shows up in Outlook as "In-Place Archive" but may be different, I'm not exactly sure. We're programmatically moving large numbers of emails into the main folder of each account, and have an archiving policy that marks them for archiving after 24 hours. We're unable to reach the mail in the archive from Graph API, so we've used win32com + MAPI before and are now exploring EWS via exchangelib for manipulating messages within the archives.

We've followed the instructions in the documentation to set up an azure app with impersonation rights, and I'm able to connect to the account and access the folders from the root, but don't see or can't access any folders in the archive root. Oddly, when I check the number of children the archive root has, it shows 6, but walking or iterating over children yields no folders.

Here is my code for connecting to the account with app credentials:
`from exchangelib import OAuth2Credentials, Account, Configuration
from exchangelib.version import Version, EXCHANGE_O365
credentials = OAuth2Credentials(
    client_id=<client_id>,
    client_secret=<client_secret>,
    tenant_id=<tenant_id>,
)
config = Configuration(
    credentials=credentials,
    auth_type="OAuth 2.0",
    version = Version(build=EXCHANGE_O365),
)
account = Account(<account@domain>, config=config, autodiscover=True)`

I'm able to successfully refresh the root and archive_msg_folder_root. 

child_folder_count is 62 for account.root, and 6 for account.archive_msg_folder_root.

print(account.root.tree()) shows everything expected, but print(account.archive_msg_folder_root.tree()) shows just "Top of Information Store". In Outlook there is an inbox with large numbers of nested subfolders within the "In-Place Archive". 

Any help or a direction to investigate is much appreciated. Please let me know if you need logs or more information.

- Wes
