### ISSUE TITLE
How to get changeKey from mail(Message) - it says Message has no attribute changeKey

### ISSUE THREAD

**Issue by SumitSoni-00** [ecederstrand/exchangelib#1232]
Hi,
I know we can get message from id and changeKey

`account.inbox.get(id=email.id, changekey=email.changeKey)`

**But issue is I am getting error (Message object has no attribute changeKey).
But I am able to get id(email.id) .
My question is how to get changeKey from mail(Message)?**

Additional I only require attachments list in message .Though we can get from`email.attachments` but there is any additional parameter is there in `get()` method from which it is possible to get only attachements list in message(similarly like `.only()` method)

**Comment by ecederstrand** [comment]
The attribute name is `change_key`, not `ChangeKey`.
