### ISSUE TITLE
exchangelib.errors.ErrorFolderNotFound: No subfolder with name 'XXX' on 5.1.0 version

### ISSUE THREAD

**Issue by multikoop** [ecederstrand/exchangelib#1233]
**Describe the bug**
A working "Cronjob" using exchangelib suddenly stopped working properly.  The EWS connect still worked, but while processing
`to_folder = account.inbox / 'autoreplies'`
an exception is thrown:

```
 File "/usr/lib/python3.10/site-packages/exchangelib/folders/base.py", line 783, in {}truediv{} 
    raise ErrorFolderNotFound(f"No subfolder with name {other!r}")
exchangelib.errors.ErrorFolderNotFound: No subfolder with name 'autoreplies'
```

**To Reproduce**
```
credentials = Credentials(EWS_USER, EWS_PWD)
config = Configuration(server = EWS_SERVER, credentials = credentials)
account = Account(primary_smtp_address = SMTP_NAME, config = config, autodiscover = False, access_type = DELEGATE)
 
#Line 32
to_folder = account.inbox / 'autoreplies'
q= (Q(subject__contains='Automatic reply')
        | Q(subject__contains='Autoreply')
       )
 
for email in account.inbox.filter(q).order_by('-datetime_received'):
    email.move(to_folder)
```

**Expected behavior**
Identified emails by the specified filter criteria should be moved to the given folder (autoreplies).

**Log output**
```
File "/home/xyz/main.py", line 32
    to_folder = account.inbox / 'autoreplies'
File "/usr/lib/python3.10/site-packages/exchangelib/folders/base.py", line 783, in {}truediv{} 
    raise ErrorFolderNotFound(f"No subfolder with name {other!r}")
exchangelib.errors.ErrorFolderNotFound: No subfolder with name 'autoreplies'
```

**Additional context**

- Python: 3.10
- exchangelib: 5.1.0

My current workaround is to use an older version (4.7.6). Maybe newer version works too. At the moment I cannot say with which version the break occured.  The above code defintely produces the error with 5.1.0.  (It might have worked also with 5.0.3, but i am not sure atm)

**Comment by ecederstrand** [comment]
This is strange. That functionality is covered by the test suite.

The easiest way to debug this is to check the XML request and response responsible for this lookup, in both the working and non-working exchanging versions to find the difference. See https://ecederstrand.github.io/exchangelib/#troubleshooting on capturing the XML.

**Comment by ecederstrand** [comment]
Closing, but feel free to reopen if you get back to debugging this issue.
