### ISSUE TITLE
Implement SubscribeToAllFolders attribute to subscription requests

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#1243]
Pull, Push and Streaming subscription requests support a `SubscribeToAllFolders` attribute. See
https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/pullsubscriptionrequest, https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/pushsubscriptionrequest, https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/streamingsubscriptionrequest

exchangelib should support that flag. Possibly as the default if the subscription is created from `Account.root`.

### Discussed in https://github.com/ecederstrand/exchangelib/discussions/1242

<div type='discussions-op-text'>

<sup>Originally posted by **CubePirate** October 30, 2023</sup>
I can't seem to figure out how to create a stream subscription for all folders, does the library support it?
I know EWS does support it, via "`<StreamingSubscriptionRequest SubscribeToAllFolders="">`"
See https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/streamingsubscriptionrequest
</div>

**Comment by CubePirate** [comment]
Wow! That was fast. Thanks Erik!

**Comment by ecederstrand** [comment]
You're welcome! You can now call the subscription methods directly on the Account object, e.g. `some_account.subscribe_to_pull()`. That should create a subscription on all folders.
