### ISSUE TITLE
Email Attachment

### ISSUE THREAD

**Issue by lcdyen** [ecederstrand/exchangelib#125]
How do I attach an excel spreadsheet (from another folder) onto a message item?

**Comment by ecederstrand** [comment]
File attachments are just bytes - exchangelib doesn't care about which type of file you're attaching:

```python
with open('/path/to/my_spreadsheet.xlsx') as f:
    binary_file_content = f.read()
my_file = FileAttachment(name='my_spreadsheet.xlsx', content=binary_file_content)
my_item.attach(my_file)
```

See also https://github.com/ecederstrand/exchangelib#attachments

**Comment by lcdyen** [comment]
I tried attaching excel spreadsheet as binary file content; however, all recipients told me that the attached spreadsheet was unreadable (issue with content problem).

**Comment by ecederstrand** [comment]
You may need to set the `content_type` attribute manually. See http://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document for official values for `.xls` and `.xlsx`.

If that doesn't work, try attaching an Excel sheet to an email via Outlook and use exchangelib to look at the full attributes that Outlook creates the attachment with. That will probably give you an idea why your recipients are unhappy.

**Comment by lcdyen** [comment]
I tried all content_type from the link you provided; none worked (the file at recipient side is only at 200B, as compare to the original 19KB)

How do I use exchangelib to look at the full attribute?
Also, have you ever sent an excel attachment successfully? (i.e. opens correctly at the recipient side)

(I'm still relatively new to Python and thanks for your help!)

**Comment by ecederstrand** [comment]
200B is definitely wrong. Maybe you're not fully reading the file content, or maybe your Excel file is mangled?

I just wrote this little example that works for me (exhcangelib==1.9.2 against Office365). I can open the Excel sheet via the web client just fine:

```python
c = Credentials(username, password)
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)

with open('sheet.xlsx', 'rb') as f:
    content = f.read()  # Read the binary file contents
att = FileAttachment(name='sheet.xlsx', content=content)
m = Message(account=a, folder=a.inbox, subject='Excel attachment')
m.attach(att)
m.save()

m.refresh()  # Get updated item from server
for a in m.attachments:
    print(a)  # Just print the attachment to see all the attributes
# m.delete()
```

**Comment by lcdyen** [comment]
Thanks!!
It works now :)

**Comment by ecederstrand** [comment]
Great!

**Comment by MartinThoma** [comment]
See also: https://stackoverflow.com/a/45438104/562769
