### ISSUE TITLE
Adding The "X-Auto-Response-Suppress" Header Ignored when sending emails

### ISSUE THREAD

**Issue by AradCarmi** [ecederstrand/exchangelib#1258]
**Describe the bug**
I'm trying to ignore replies when sending emails using the "X-Auto-Response-Suppress" header to my Message but when reading the incoming email (the .eml file), the headers have been omitted. Sending other headers seems to be working well.

**To Reproduce**
Send a message adding the "X-Auto-Response-Suppress" header.

**Expected behavior**
The header should be added to the request.

**Additional context**
exchange-lib version: 4.9.0
python version: 3.10.13

**Comment by ecederstrand** [comment]
How are you sending the message? 

In my testing I have not been able to create messages with headers via EWS. Therefore, this field is treated as read-only in exchangelib: https://github.com/ecederstrand/exchangelib/blob/b6e4b1c07c5dedf1fa419ec9769e2447f7200333/exchangelib/items/item.py#L83

If you have reason to believe that this field is indeed writeable, then please note it here.

**Comment by AradCarmi** [comment]
Sorry for the mistake, I meant to the `send_and_save` function within the `Message` class.
I was able to add to my `Message` object a header as a kwargs (It parses as `ExtendedPropertyField` not sure the meaning of this) and when adding the specific `X-Auto-Response-Suppress` header it fails to add it (I can't see the header in the .eml file).
Is there a better solution for adding a header to the request instead of adding it to the `Message` as a property?
I'm looking for a solution to ignore the auto replies from the 'OOF' mailboxes.
Thanks in advance.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you get back to this.
