### ISSUE TITLE
Moving Emails to another Folder

### ISSUE THREAD

**Issue by GitHub2022** [ecederstrand/exchangelib#126]
Hi, i couldn't find any suitable method to move an email from folder A to Folder B. Is there any way to do it?

**Comment by ecederstrand** [comment]
All items have a `move()` method:

```python
my_item.move(to_folder)
```

If you want to move a large amount of items at once, `Account` has a `bulk_move()` method that takes an iterable of items:

```python
my_account.bulk_move(items, to_folder)
```

**Comment by GitHub2022** [comment]
Thank you. Is there any documentation around where i can find such things? The general documentation doesnt have all the options available. I was checking here: https://pypi.python.org/pypi/exchangelib

**Comment by ecederstrand** [comment]
The documentation for these were missing, so your ticket prompted me to improve the docs :-) https://github.com/ecederstrand/exchangelib/commit/e1994988e9e0261141899c5ecab64d0405eb9312

The README is getting unwieldy. I would like to switch to GitHub pages, but time is short.

**Comment by GitHub2022** [comment]
Yeah, as always, time goes by. Good work, thank you so much for your effort!
