### ISSUE TITLE
filter(...).only('headers') returns always None

### ISSUE THREAD

**Issue by sharon8811** [ecederstrand/exchangelib#127]
if i query for only headers it returns None

**Comment by ecederstrand** [comment]
Does this also happen if you remove the `.only()`? It could be that your messages simply don't have any headers.

**Comment by sharon8811** [comment]
no - i checked there is headers for the message if i get the same Message without only i get the headers back.
btw it doesn't work with values and values_list either

**Comment by ecederstrand** [comment]
That's strange. Which version of python and exchangelib is this? I did a quick test on v. 1.9.3 on Python3 and I can't reproduce:

```python
for i in a.inbox.filter(headers__exists=True):
    print(i.item_id, len(i.headers))
    i2 = a.inbox.all().only('headers').get(item_id=i.item_id, changekey=i.changekey)
    print(i2.item_id, len(i2.headers))
    print()
```
This prints (ID's truncated):
```bash
YSAAA= 56
YSAAA= 56

ifAAA= 57
ifAAA= 57

WkAAA= 27
WkAAA= 27

q4AAA= 26
q4AAA= 26
[...]
```

**Comment by sharon8811** [comment]
i use python 2.7 and exchangelib 1.9.3 but i don't think the example you gave is exactly the same as mine:
in your example you iterate over a.inbox.filter(headers__exists=True) which fetch all emails fields and caches them and then you do seconds query a.inbox.all().only('headers').get(item_id=i.item_id, changekey=i.changekey) which probably takes the fields from the cached data from the first fetch.
in my case this is the only query i run:
a.inbox.filter(headers__exists=True).only('headers')

**Comment by ecederstrand** [comment]
Ooh, you're right! It's not due to caching, but we're incorrectly issuing a `FindItem` call in this case, and `FindItem` can't handle the `InternetMessageHeaders` field. This example show the problem:

```python
for i in a.inbox.filter(headers__exists=True).only('headers'):
    print(i.item_id, i.headers)
```

This prints

```bash
YSAAA= None
ifAAA= None
WkAAA= None
[...]
```

**Comment by sharon8811** [comment]
thanks with this change it works,
but on the same matter if i do only() query on extended property i am getting:
ErrorInvalidRequest: The request is invalid. 

this is my extended property and my code:
`
class MyTestField(ExtendedProperty):
    property_id = '00020329-0000-0000-c000-000000000046'
    property_name = 'MyTestField'
    property_type = 'String'

Message.register('my_test_field', MyTestField)

a.inbox.all().only('my_test_field')
`
and i get the exception after a while

**Comment by ecederstrand** [comment]
That one happens because you should assign your ID to `property_set_id`, not `property_id`
