### ISSUE TITLE
attached mail as ItemAttachment

### ISSUE THREAD

**Issue by Gewitsch** [ecederstrand/exchangelib#1275]
**Describe the bug**
![Python_manually_attached_mail](https://github.com/ecederstrand/exchangelib/assets/161429660/eec9a111-5059-47a3-a54e-2cc598c81661)
![Python_exchangelib_attached_mail](https://github.com/ecederstrand/exchangelib/assets/161429660/8e0511a9-105d-4a59-8a60-1a5c6fd7f9cf)
First of all I am new to this posting. So please forgive me for mistakes I made with this report.
The attached email looks like when I attempt to send a message again, but I thought it would like when I normally open an email.

**To Reproduce**
```python
anzuhaengende_nachricht.mime_content = None
antwort.attach(ItemAttachment(item=anzuhaengende_nachricht, name=anzuhaengende_nachricht.subject))
antwort.send_and_save()
```

I am german so my code is in german language. 
"anzuhaengende_nachricht" = message for attaching
"antwort" = message I wanna send

**Expected behavior**
I expected the message that I attach via exchangelib to look the same as the one I attached manually with outlook 365.

**Log output**
If applicable, add relevant output from [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) .

**Additional context**
Python version 3.11 and exchangelib version 5.1.0.

I tried googling this issue yesterday for several hours, but it is hard to describe in words.

**Comment by ecederstrand** [comment]
I think the best option to find out what the difference between sending an item attachment from exchange and from Outlook is to create two identical emails , one from each system, and then use exchangelib to inspect all attriburtes on the two items to find out what the difference is.

**Comment by ecederstrand** [comment]
I was thinking of something along these lines:

```python
item_from_exchangelib = inbox.get(subject="Hello from exchangelib")
item_from_outlook = inbox.get(subject="Hello from outlook")

for f in Message.FIELDS:
    exchangelib_val = getattr(item_from_exchangelib, f.name)
    outlook_val = getattr(item_from_outlook, f.name)
    if exchangelib_val != outlook_val:
        print(f"Diff on field {f.name}. exchangelib: {exchangelib_val!r} Outlook: {outlook_val!r}")
```

**Comment by Gewitsch** [comment]
[analyse.txt](https://github.com/ecederstrand/exchangelib/files/14420457/analyse.txt)

I got this textfile with the print content.
To the previous tests I reduced the mail to just the attached mail, your suggested subject, "test" as the body and the attached mail itself is very "plain" in its structure.

Hopefully this helps with finding a solution.

**Comment by ecederstrand** [comment]
The text file only reports `mime_content` as being different, and that field is auto-generated. That doesn't get us any further, unfortunately.

**Comment by Gewitsch** [comment]
Sorry my mistake. I did not format it in any way. 
A little usage of notepad++ later and I got hopefully the same content just being displayed in a better way.

Now the document follows 
Diff on field field.name
exchangelib:
exchangelib value
Outlook:
outlook value

[analyse.txt](https://github.com/ecederstrand/exchangelib/files/14431407/analyse.txt)

some values are ... very long.

**Comment by Gewitsch** [comment]
Yes I do attach the same message.

The attached mail has the subject = "Test", body = "Test" and no attachments itself. Very plain and simple. 

What can I further do to help solving this issue?

**Comment by ecederstrand** [comment]
I don't have any obvious ideas.

I don't really consider this a bug, since it's not a goal of exchangelib to have feature parity with Outlook, but please do post your solution here if you find one.

**Comment by ecederstrand** [comment]
Closing, but it would still be great if you post any solution here so others can benefit :-)
