### ISSUE TITLE
Linting error: `account.inbox.filter(...)`

### ISSUE THREAD

**Issue by DeflateAwning** [ecederstrand/exchangelib#1276]
**Describe the bug**
The following code gives a linting error:

```python
from exchangelib import Credentials, Account

# from README for completeness
credentials = Credentials("john@example.com", "topsecret")
account = Account("john@example.com", credentials=credentials, autodiscover=True)

# part with linting problem:
email_message = account.inbox.filter(subject__contains='the', sender__contains='example.com').order_by('-datetime_received')[0]
```

This code runs fine, but the `.filter` part of `account.inbox.filter(...)` gets the following linting error in Pyright:

```
Cannot access member "filter" for type "threaded_cached_property"
  Member "filter" is unknown
```

**Additional context**
Python 3.9, exchangelib 5.1.0

**Comment by ecederstrand** [comment]
I think this is just Pyright not being able to properly understand the code properly. I don't see anything wrong.

**Comment by DeflateAwning** [comment]
Just opened an issue at Pyright: https://github.com/microsoft/pyright/issues/7378

**Comment by hmc-cs-mdrissi** [comment]
https://github.com/pydanny/cached-property/issues/172 is probably real issue. threaded_cached_property doesn't play well with static analysis tools in general.

The easiest trick,

```python
if TYPE_CHECKING:
  my_prop = property
else:
  my_prop = threaded_cached_property
```

**Comment by ecederstrand** [comment]
Most of exchangelib was written way before type annotations became a Python feature. Adding full annotations is a huge effort that I will not undertake myself, at least.

**Comment by DeflateAwning** [comment]
I wasn't suggesting that we need full annotations; I do however thing that it makes sense to add hints on parts that are being labelled as errors

**Comment by ecederstrand** [comment]
In this case, it looks like the real issue lies in the cached-property package. I think the issue should be solved there.

There are other places where static type checkers have a hard time reasoning about exchangelib code. I haven't seen any cases where there were actual errors, and refactoring turned out to be a lot of work for very little gain.

I'm closing this issue because exchangelib doesn't use Pyright. I'm not generally opposed to doing so, but please work on adding support in a PR instead.

**Comment by DeflateAwning** [comment]
@ecederstrand, would you be willing to help me write an issue for this in the `cached-property` package? Or at least point me to the part where that issue needs to be created?

**Comment by hmc-cs-mdrissi** [comment]
The issue already exists. https://github.com/pydanny/cached-property/issues/172 is the correct issue. Fixing that will fix the problem here.
