### ISSUE TITLE
Managinge Safe Senders

### ISSUE THREAD

**Issue by williamsjj** [ecederstrand/exchangelib#128]
Is there an API for managing Safe Senders via EWS?

**Comment by ecederstrand** [comment]
I have no idea what Safe Senders are. Do you have a link?

**Comment by ecederstrand** [comment]
After a bit of googling, it looks like this is only accessible via Exchange management commands: https://technet.microsoft.com/en-us/library/aa995952(EXCHG.80).aspx

**Comment by ecederstrand** [comment]
Closing due to submitter timeout. Feel free to re-open if you think this is is indeed possible with EWS.
