### ISSUE TITLE
Typo in Exchange 2019 version

### ISSUE THREAD

**Issue by fjcuadrado** [ecederstrand/exchangelib#1287]
Hi.

**Describe the bug**

I don’t know if what I see it is a typo, but it seems so. 

In the Exchange versions (see the following permalink to the code line) the API Version field of the Exchange 2019 is set to Exchange2016. Is that right? Because it seems that is a typo and the value should be Exhange2019. 

https://github.com/ecederstrand/exchangelib/blob/d2fbf1dd90dafc130fde8d2276741663f2d3e221/exchangelib/version.py#L130

Thank you.

**Comment by ecederstrand** [comment]
This is not an error.
