### ISSUE TITLE
Conversation ID of the Message Item

### ISSUE THREAD

**Issue by vincentlam** [ecederstrand/exchangelib#129]
Is it possible to get the conversation id of the emails?

**Comment by ecederstrand** [comment]
It's not a supported field yet but would not be difficult to add.

**Comment by ninSmith** [comment]
Big +1 for this feature, I would also be interested

Thanks

**Comment by ecederstrand** [comment]
I just committed read-only support for Conversation ID, exposed as attribute `conversation_id`. Please reopen if write support is needed.

**Comment by tariksetia** [comment]
I have <class 'exchangelib.items.Message'> object stored in say mail.
However mail.conversation_id returns noneType.
Does every email have a conversation id?
