### ISSUE TITLE
Validation rule error when manage inbox rules

### ISSUE THREAD

**Issue by buituan11** [ecederstrand/exchangelib#1292]
**Describe the bug**
I want to manage rules of multiple accouts. But when i create rules in each accout, it show error "A validation error occurred while executing the rule operation"

**To Reproduce**
declare a rule 
`rule = Rule(
    display_name="Messs",
    priority=1,
    is_enabled=True,
    is_not_supported=False,
    is_in_error=True,
    conditions=Conditions(
        contains_sender_strings=[
            "sender_example",
        ],
    ),
    exceptions=Exceptions(),
    actions=Actions(
        delete=True
        # redirect_to_recipients=mailbox,
        # mark_as_read=True
    ),
)`
account create rule 
`rule_id = account.create_rule(rule)`
Error: 
`exchangelib.errors.ErrorInboxRulesValidationError: A validation error occurred while executing the rule operation.`

![image](https://github.com/ecederstrand/exchangelib/assets/36917020/d2ed7df3-6347-41fe-a04a-7fbf3bceb8ad)

**Expected behavior**
Create rules successfully

**Comment by ecederstrand** [comment]
There is an error in your rule so the server rejects the rule. If you [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting), then the returned XML from the server will usually give you more information about what exactly is wrong.

**Comment by ecederstrand** [comment]
I improved error messages for validation errors in inbox rules in https://github.com/ecederstrand/exchangelib/commit/cc45183289d125669c65890b794bc7dc51debb30

**Comment by buituan11** [comment]
Thanks for reply. I fixed this error
