### ISSUE TITLE
Create calendar appointment in another account as access data, the appointment is created in the access account.

### ISSUE THREAD

**Issue by LKleemann** [ecederstrand/exchangelib#1298]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, describe how other clients like Outlook or OWA behave.
If I want to create an appointment in another account using the "CalendarItem" function, the appointment is created in the calendar of the access account. I have already made several attempts to do this, unfortunately without success.

**Uses Function**
```python
newCalenderItem = CalendarItem(
            account=self.mailAccount_TestUser,
            folder=SingleFolderQuerySet(account=self.mailAccount_TestUser, folder=DistinguishedFolderId(id=Calendar.DISTINGUISHED_FOLDER_ID, mailbox=self.mailbox_TestUser)).resolve(),
            start=datetime.strptime(startDatetime, '%Y-%m-%dT%H:%M:%S').astimezone(tz=tz),
            end=datetime.strptime(endDateTime, '%Y-%m-%dT%H:%M:%S').astimezone(tz=tz),
            subject=subject,
            legacy_free_busy_status=LegacyFreeBusyStatus,
            is_all_day=True,
        )
        print("newCalenderItem", newCalenderItem)
        id = newCalenderItem.save()
```
**The connection to the server is established as follows**
```python
        self.credentials = Credentials(
            username='System@[domain].de', password='[password]')
        
        self.config = Configuration(server="[domain].de",
            credentials=self.credentials, auth_type="basic", retry_policy=FaultTolerance(max_wait=3600),
        )
        self.mailAccount_TestUser = Account(
            primary_smtp_address='Test.User@[domain].de', config=self.config,
            autodiscover=False, access_type=DELEGATE
        )
        self.mailbox_TestUser = Mailbox(email_address='Test.User@[domain].de')
```

**Different tests**
Due to several already open tickets in Github, I have already carried out the following tests.

`folder=SingleFolderQuerySet(account=self.mailAccount_TestUser, folder=DistinguishedFolderId(id=Calendar.DISTINGUISHED_FOLDER_ID, mailbox=self.mailbox_TestUser)).resolve(),`

`folder=self.mailAccount_TestUser.calendar,`

No matter what I enter in the folder, the appointment is always created in the system user calendar. 

Thank you very much for your support.

**Comment by ecederstrand** [comment]
Can you please test whether this commit fixes this? https://github.com/ecederstrand/exchangelib/commit/f65079f372a35d09a3d4b3e929ecc53bd60b6fc1

**Comment by ecederstrand** [comment]
Actually, I believe https://github.com/ecederstrand/exchangelib/commit/d9035d03960797f9277381845e4ec98f837798ea may fix this for you.

**Comment by LKleemann** [comment]
Thank you very much for your quick response.

The problem has been solved with your update.

Have a nice day.
