### ISSUE TITLE
How to get items from specific calendar

### ISSUE THREAD

**Issue by meilon** [ecederstrand/exchangelib#13]
I just found this library and first of: thanks! I was just about to start with DavMail just to get calendar items to ical (publishing calendar is turned off), with this the memory footprint is a lot smaller!

I already managed to get items from the default calendar, but how do I search for elements in a specific caleder, preferably by name? I'm still new to python and I don't know how account.folders works.

**Comment by ecederstrand** [comment]
Interesting. I haven't tried that. I always just use the default calendar (`account.calendar`).

This should work, but I haven't tried:

```
from exchangelib.folders import Calendar

for calendar in account.folders[Calendar]:
    calendar.find_items(start=start, end=end, ...)
```

**Comment by meilon** [comment]
Sadly it doesn't work, I get `NameError: name 'Calendar' is not defined`.

**Comment by meilon** [comment]
I just updated to the current version via pip, but sadly after adhering to the new stuff in the changelog the above code doesn't work anymore. `account.folders[Calendar]` is empty for me, why is that?

I had to change the code to

    from exchangelib.folders import Root
    
    specificFolder = [item for item in account.folders[Root] if item.name == 'My Folder Name']

to find my calendar folder again.

**Comment by ecederstrand** [comment]
That's definitely a regression. I'll see if I can find out what happened.

**Comment by ecederstrand** [comment]
This should work again. Sorry for the breakage.
