### ISSUE TITLE
ImportError: cannot import name 'Calendar'

### ISSUE THREAD

**Issue by busla** [ecederstrand/exchangelib#130]
* Python 3.5.2
* exchangelib 1.9.3

`ImportError: cannot import name 'Calendar'`

I´m getting this error using the demo code in the docs. I also don´t see this class anywhere in the source code.

**Comment by ecederstrand** [comment]
Hi @busla The docs are wrong. `Calendar` is located in `exchangelib.folders` so you need to do `from exchangelib.folders import Calendar`. I'll get it fixed.

**Comment by ecederstrand** [comment]
Fixed by https://github.com/ecederstrand/exchangelib/commit/347a61f4bc1472ac5297f8e25eb6875d62eb525e
