### ISSUE TITLE
Call to https://servername/EWS/Exchange.asmx fails

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#131]
Hi, 

I stumbled over your project and I love it. Before I tried to hack around the old Office365 API to work with my Office365 Calendar which was kinda ugly.

Now I want to include the Calendar of my work Exchange Account as well (which is not hosted on Office365 and therefore not availlable over the Office365 API)

Your library works just fine with my Office365 Account (even adding attachments - I never figured that out using the Office365 API)

Now when I try to connect to the mail server at work I get an `exchangelib.errors.TransportError: Unknown failure`

After some research I found that for some reason the client should ignore certificate warnings?
The Status Code is 500.

Hope that helps
Best regards

**Comment by ecederstrand** [comment]
Can you post the full stactrace, please?

Are you saying that `validate_ssl` fixed the problem for you?

**Comment by fruitloop** [comment]
The `validate_ssl` thing worked on my phone. I couldn't find a flag for your tool though.

Here is the full Stacktrace:
```
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/roland/PycharmProjects/time-tracking/time_tracking/cli.py
getting calendar events using exchangelib

Adress: **************
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Password: ***********
Calendar: Kalender
User: **********\\**********
EWS https://mail.my.company.com/EWS/Exchange.asmx, account None: Exception in _get_elements: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 72, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 138, in _get_response_xml
    allow_redirects=False)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/util.py", line 462, in post_ratelimited
    raise TransportError('Unknown failure\n' + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 0
Timeout: 120
Session: 21546
Thread: 140735112982528
Auth type: <requests.auth.HTTPBasicAuth object at 0x10b0c0f60>
URL: https://mail.my.company.com/EWS/Exchange.asmx
Verify: True
Allow redirects: False
Response time: 0.13436543400166556
Status code: 500
Request headers: {'User-Agent': 'python-requests/2.14.1', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '462', 'Authorization': 'Basic ***some***secret***hash***'}
Response headers: {'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Content-Type': 'text/html', 'Content-Length': '1979  '}
Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>*****\\\\*****</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>'
Response data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML dir=ltr><HEAD><TITLE>The page cannot be displayed</TITLE>
<STYLE id=L_defaultr_1>A:link {
	FONT: 8pt/11pt verdana; COLOR: #ff0000
}
A:visited {
	FONT: 8pt/11pt verdana; COLOR: #4e4e4e
}
</STYLE>

<META content=NOINDEX name=ROBOTS>
<META http-equiv=Content-Type content="text-html; charset=UTF-8">

<META content="MSHTML 5.50.4522.1800" name=GENERATOR></HEAD>
<BODY bgColor=#ffffff>
<TABLE cellSpacing=5 cellPadding=3 width=410>
  <TBODY>
  <TR>
    <TD id=L_defaultr_0 valign=middle align=left width=360>
      <H1 id=L_defaultr_2 style="FONT: 13pt/15pt verdana; COLOR: #000000"><ID id=L_defaultr_3><!--Problem-->The page cannot be displayed
</ID></H1></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_4
      style="FONT: 8pt/11pt verdana; COLOR: #000000"><ID id=L_defaultr_5><B>Explanation: </B>There is a problem with the page you are trying to reach and it cannot be displayed.</ID></FONT></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_6 
      style="FONT: 8pt/11pt verdana; COLOR: #000000">
      <HR color=#c0c0c0 noShade>

      <P id=L_defaultr_7><B>Try the following:</B></P>
      <UL>
        <LI id=L_defaultr_8><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_defaultr_9><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_defaultr_10><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.

      </UL>
      <HR color=#c0c0c0 noShade>

      <P id=L_defaultr_11>Technical Information (for support personnel)</P>
      <UL>
        <LI id=L_defaultr_12>Error Code: 500 Internal Server Error. The parameter is incorrect. (87)

        </UL></FONT></TD></TR></TBODY></TABLE></BODY></HTML>




Failed to create cached protocol with key ('https://mail.my.company.com/EWS/Exchange.asmx', Credentials('******\\\\******', '********'), True): Unknown failure
Retry: 0
Waited: 0
Timeout: 120
Session: 21546
Thread: 140735112982528
Auth type: <requests.auth.HTTPBasicAuth object at 0x10b0c0f60>
URL: https://mail.my.company.com/EWS/Exchange.asmx
Verify: True
Allow redirects: False
Response time: 0.13436543400166556
Status code: 500
Request headers: {'User-Agent': 'python-requests/2.14.1', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '462', 'Authorization': 'Basic ***the***same***secret***hash?***'}
Response headers: {'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Content-Type': 'text/html', 'Content-Length': '1979  '}
Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>*****\\\\*****</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>'
Response data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML dir=ltr><HEAD><TITLE>The page cannot be displayed</TITLE>
<STYLE id=L_defaultr_1>A:link {
	FONT: 8pt/11pt verdana; COLOR: #ff0000
}
A:visited {
	FONT: 8pt/11pt verdana; COLOR: #4e4e4e
}
</STYLE>

<META content=NOINDEX name=ROBOTS>
<META http-equiv=Content-Type content="text-html; charset=UTF-8">

<META content="MSHTML 5.50.4522.1800" name=GENERATOR></HEAD>
<BODY bgColor=#ffffff>
<TABLE cellSpacing=5 cellPadding=3 width=410>
  <TBODY>
  <TR>
    <TD id=L_defaultr_0 valign=middle align=left width=360>
      <H1 id=L_defaultr_2 style="FONT: 13pt/15pt verdana; COLOR: #000000"><ID id=L_defaultr_3><!--Problem-->The page cannot be displayed
</ID></H1></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_4
      style="FONT: 8pt/11pt verdana; COLOR: #000000"><ID id=L_defaultr_5><B>Explanation: </B>There is a problem with the page you are trying to reach and it cannot be displayed.</ID></FONT></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_6 
      style="FONT: 8pt/11pt verdana; COLOR: #000000">
      <HR color=#c0c0c0 noShade>

      <P id=L_defaultr_7><B>Try the following:</B></P>
      <UL>
        <LI id=L_defaultr_8><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_defaultr_9><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_defaultr_10><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.

      </UL>
      <HR color=#c0c0c0 noShade>

      <P id=L_defaultr_11>Technical Information (for support personnel)</P>
      <UL>
        <LI id=L_defaultr_12>Error Code: 500 Internal Server Error. The parameter is incorrect. (87)

        </UL></FONT></TD></TR></TBODY></TABLE></BODY></HTML>



Traceback (most recent call last):
  File "/Users/roland/PycharmProjects/time-tracking/time_tracking/cli.py", line 130, in <module>
    if __name__ == '__main__': main()
  File "/Users/roland/PycharmProjects/time-tracking/time_tracking/cli.py", line 111, in main
    rewe_config = Configuration(server='mail.my.company.com', credentials=rewe_cred)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/configuration.py", line 48, in __init__
    version=version
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 173, in __call__
    raise e
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 168, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 222, in __init__
    self.version = Version.guess(self)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/version.py", line 194, in guess
    return cls._guess_version_from_service(protocol=protocol, hint=api_version)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/version.py", line 224, in _guess_version_from_service
    ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username])
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 981, in call
    return_full_contact_data=return_full_contact_data,
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 72, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 138, in _get_response_xml
    allow_redirects=False)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/util.py", line 462, in post_ratelimited
    raise TransportError('Unknown failure\n' + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 0
Timeout: 120
Session: 21546
Thread: 140735112982528
Auth type: <requests.auth.HTTPBasicAuth object at 0x10b0c0f60>
URL: https://mail.my.company.com/EWS/Exchange.asmx
Verify: True
Allow redirects: False
Response time: 0.13436543400166556
Status code: 500
Request headers: {'User-Agent': 'python-requests/2.14.1', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '462', 'Authorization': 'Basic ***one***more***time***the***same***hash***='}
Response headers: {'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Content-Type': 'text/html', 'Content-Length': '1979  '}
Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007" /></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>*****\\\\*****</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>'
Response data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML dir=ltr><HEAD><TITLE>The page cannot be displayed</TITLE>
<STYLE id=L_defaultr_1>A:link {
	FONT: 8pt/11pt verdana; COLOR: #ff0000
}
A:visited {
	FONT: 8pt/11pt verdana; COLOR: #4e4e4e
}
</STYLE>

<META content=NOINDEX name=ROBOTS>
<META http-equiv=Content-Type content="text-html; charset=UTF-8">

<META content="MSHTML 5.50.4522.1800" name=GENERATOR></HEAD>
<BODY bgColor=#ffffff>
<TABLE cellSpacing=5 cellPadding=3 width=410>
  <TBODY>
  <TR>
    <TD id=L_defaultr_0 valign=middle align=left width=360>
      <H1 id=L_defaultr_2 style="FONT: 13pt/15pt verdana; COLOR: #000000"><ID id=L_defaultr_3><!--Problem-->The page cannot be displayed
</ID></H1></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_4
      style="FONT: 8pt/11pt verdana; COLOR: #000000"><ID id=L_defaultr_5><B>Explanation: </B>There is a problem with the page you are trying to reach and it cannot be displayed.</ID></FONT></TD></TR>
  <TR>
    <TD width=400 colSpan=2><FONT id=L_defaultr_6 
      style="FONT: 8pt/11pt verdana; COLOR: #000000">
      <HR color=#c0c0c0 noShade>

      <P id=L_defaultr_7><B>Try the following:</B></P>
      <UL>
        <LI id=L_defaultr_8><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
<LI id=L_defaultr_9><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
<LI id=L_defaultr_10><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.

      </UL>
      <HR color=#c0c0c0 noShade>

      <P id=L_defaultr_11>Technical Information (for support personnel)</P>
      <UL>
        <LI id=L_defaultr_12>Error Code: 500 Internal Server Error. The parameter is incorrect. (87)

        </UL></FONT></TD></TR></TBODY></TABLE></BODY></HTML>




Process finished with exit code 1
```

I Call:
```
Credentials(...)
Configuration(...)
Account(...)
```
that's probably why the stacktrace keeps repeating.

**Comment by ecederstrand** [comment]
`Account` has a `verify_ssl` option that you can ser to `false`, but it would be better to set up your root certificates to accept your company's certificate. This is out of scope for exchangelib.

**Comment by fruitloop** [comment]
Thanks I'll try that tonight

**Comment by fruitloop** [comment]
Unfortunately this did exactly nothing. At least now I know that it was no certificate error. :(

**Comment by ecederstrand** [comment]
I've seen this reported before but never managed to get to the root of the problem.

exchangelib tries to guess the Exchange version of the remote server automatically. What apparently happens is that the remote server denies all our attempts at this with an HTTP 500 error.

You could try disable the version guessing by hardcoding the server version and EWS endpoint as described in https://github.com/ecederstrand/exchangelib#setup-and-connecting But of course, it would be better to find out why the remote server is misbehaving.

**Comment by ecederstrand** [comment]
@fruitloop Did you ever get to the bottom of this?

**Comment by fruitloop** [comment]
Unfortunately not yet.

The Exchange Server I'm trying to connect is the company mail server. I have yet to discover what version of Exchange is running on that thing.

My private Office365 Calendars work just fine.

**Comment by fruitloop** [comment]
I finally managed to find the exact version of the exchange server.
I'll try to connect tonight.

**Comment by fruitloop** [comment]
Crazy things happen!

Now that I finally found the Version number of the server I went and started tests with all defaults (autodiscovery, ...) and now everything works just fine.

Probably my shitty internet connection caused timeouts the first time I tried.

**Comment by ecederstrand** [comment]
Dang! I had hoped for a good explanation to the weirdness, but I'm glad you got it working :-)

**Comment by fruitloop** [comment]
The mysterious error seems to be back.

I get a bunch of timeouts. I guess I tried connecting too often.
I'll give it a few days to cool down and try hardcoding all the autodiscovery variables
hope that works.

**Comment by ecederstrand** [comment]
I googled "Error Code: 500 Internal Server Error. The parameter is incorrect. (87)" which is contained in the failing response you posted above.

It seems it may be caused by a misconfiguration in ISA: https://social.technet.microsoft.com/Forums/ie/en-US/ae744eef-e736-4e58-80a7-ba8aac2ec84a/error-500-internal-server-error-the-parameter-is-incorrect-87?forum=ForefrontedgePub

Could this be an issue on your company network?

**Comment by fruitloop** [comment]
thats a probability.

at the moment i'm getting 401s with timeouts doubling the seconds

**Comment by ecederstrand** [comment]
401s are an indication of rate-limiting by the server, assuming your credentials *are* in fact correct. If you're good friends with the Exchange admin, you could convince him or her to remove the rate-limiting policies on the account you're testing with.

**Comment by fruitloop** [comment]
My credentials are correct, I use the same on my phone for email/calendar.

The strange thing is that it worked once for a few days and now everything I get is this `401` that just keeps counting the cool down up until I manually stop it.

Unfortunately I have no clue who is the Exchange Admin I'm just a Software Developer there.

What I don't understand is why it worked once.

**Comment by ecederstrand** [comment]
I have hit this issue before and I'm pretty sure this is EWS ratelimiting  in. That or some EWS "suspicious behaviour" filter setting off alarms due to the way we use EWS. I don't think you'll get to the root of this without some cooperstion from the Exchange admins.

**Comment by fruitloop** [comment]
When I have more time in a few weeks I'm going to try running my script from my server with a completely different IP. That way we could rule out that I'm already blacklisted on the server.

Which would be strange, since I can send/receive mails using outlook and that exact account.

If this won't solve the problem I'll have to try to contact one of the admins of the Exchange Server.

**Comment by fruitloop** [comment]
Unfortunately I did not. It still throws errors (different ones though I think).
I will try to analyze and post them tomorrow.

**Comment by fruitloop** [comment]
Incremental Updates:
I don't have my code on my machine at work, but I ran the commands directly in python3.6:

```
cred = ServiceAccount(...)
version = Version(...)
config = Config(version=version, credentials=cred, ...)
account = Account(config=config, autodiscover=False, ...)
```

There is no error on `ServiceAccount`, `Version` and `Config`. `Account` however takes forever. (still running)
It doesn't crash though? Maybe there is no timeout on the python shell?

**Comment by ecederstrand** [comment]
Try using `Credentials` class instead of `ServiceAccount`. The latter will patiently keep on trying if it gets a HTTP 401 response, which is probably why it's taking forever. You can able `DEBUG` logging to see exactly what's going on.

**Comment by fruitloop** [comment]
Now it throws all kinds of errors (mostly SSL due to internal server names)
I'll keep trying tomorrow evening from home.

How do I enable DEBUG in the python shell?

**Comment by ecederstrand** [comment]
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

should work

**Comment by ecederstrand** [comment]
You can disable SSL verification with `Account(..., verify_ssl=False)`

**Comment by fruitloop** [comment]
The SSL error seems to come before Account. Somewhere on autodiscover.
It dissappears if I specify Server and Version manually.

**Comment by ecederstrand** [comment]
That's strange. `verify_ssl` is supposed to be propagated to the autodiscover code. Please post the stack trace if this is holding you up.

**Comment by fruitloop** [comment]
sorry for not answering. I won't be able to continue testing this until end of september.
When I tried the commands on the python shell it crashed before I came to declare the account variable.

In the script though it works just fine.

**Comment by fruitloop** [comment]
Last Update:

the company is updating their Exchange Server from 2010 to 2016.
Unfortunately I can't test if this solves that problem since I no longer
work there.

**Comment by ecederstrand** [comment]
Ok, thanks for the update.

**Comment by danmanning** [comment]
@ecederstrand I have exactly the same issue that has been posted above:

### Code
```
        from exchangelib.util import PrettyXmlHandler
        logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

        from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
        BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

        from exchangelib import Account, Credentials, Message, Mailbox, DELEGATE, Configuration, Version, Build
        exCredentials = Credentials(username=ExchangeUsername, password=ExchangePassword)
        exVersion = Version(build=Build(int(exVer[0]),int(exVer[1]),int(exVer[2]),int(exVer[3])))
        exConfig = Configuration(server=ExchangeUrl, credentials=exCredentials, version=exVersion)
        exAccount = Account(primary_smtp_address=ExchangeEmailAddress, credentials=exCredentials, config=exConfig, autodiscover=False, access_type=DELEGATE)
```

### Error
>   File "d:\test.py", line 146, in <module>
>     CheckExpiry()
>   File "d:\test.py", line 103, in CheckExpiry
>     SendEmails(emailsToSend)
>   File "d:\test.py", line 142, in SendEmails
>     raise e
>   File "d:\test.py", line 120, in SendEmails
>     exConfig = Configuration(server=ExchangeUrl, credentials=exCredentials, version=exVersion)
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\configuration.py", line 46, in __init__
>     version=version
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\protocol.py", line 172, in __call__
>     protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\protocol.py", line 204, in __init__
>     name=self.credentials.username)
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\transport.py", line 133, in get_service_authtype
>     timeout=BaseProtocol.TIMEOUT)
>   File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 555, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 508, in send
> 
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mail.company.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004A3A940>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

I'm a Python noob  so fully appreciate if it could be an issue in my code

**Comment by ecederstrand** [comment]
This looks like a DNS problem on your side. See e.g. https://stackoverflow.com/questions/7334199/getaddrinfo-failed-what-does-that-mean

**Comment by yzcheung** [comment]
I have met with the same problem. All the methods provided above can't help. Hope anyone solved this issue can share with me.

**Comment by ecederstrand** [comment]
@yzcheung This is a really old isse. Please open a new issue instead and describe your issue there.

**Comment by Chrescht** [comment]
> verify
I get TypeError: __init__() got an unexpected keyword argument 'verify_ssl'.

**Comment by ecederstrand** [comment]
The `verify_ssl` option is deprecated in version 1.10.0: https://github.com/ecederstrand/exchangelib/blob/master/CHANGELOG.md#1100

**Comment by hemanthyernagula** [comment]
Any Update for this? I'm getting invalid credientials for server_endpoint/EWS/Exchange.asmx, I dont know why is it automatically adding "EWS/Exchange.asmx" to the provided endpoint.

**Comment by ecederstrand** [comment]
@hemanthyernagula This is a really old isse. Please open a new issue instead and describe your problem there.
