### ISSUE TITLE
Support Custom Authentication Domains for Global and Governmental Environments (gcc-high, dod, etc)

### ISSUE THREAD

**Issue by barryyosi-panw** [ecederstrand/exchangelib#1317]
It seems that the library hardcodes `.com` domain for the required endpoints such as

https://github.com/ecederstrand/exchangelib/blob/5fa602e49c01a1953942c6228d75f45ffc3020f6/exchangelib/credentials.py#L142

https://github.com/ecederstrand/exchangelib/blob/5fa602e49c01a1953942c6228d75f45ffc3020f6/exchangelib/credentials.py#L147

https://github.com/ecederstrand/exchangelib/blob/5fa602e49c01a1953942c6228d75f45ffc3020f6/exchangelib/credentials.py#L314

Making it impossible to interface `.us`, `.de` & `.cn`  domains.

Is there any possible solution? Or perhaps it might be enhanced?

**Comment by ecederstrand** [comment]
These are just helper classes. If you need to use different domains in the places you pointed to, just subclass and change what you want. Eg.:

```python
class MyGermanO365(O365InteractiveCredentials):
    AUTHORITY = "https://login.microsoftonline.de/organizations" 

credentials = MyGermanO365(...)
```
