### ISSUE TITLE
Implement passing an Account object to GetUserAvailability in order to fix the "Returning naive datetime"-warning for timezone-unaware server responses.

### ISSUE THREAD

**Issue by Archern4r** [ecederstrand/exchangelib#1319]
Hi there,

as mentioned in https://github.com/ecederstrand/exchangelib/issues/643 a warning about naive datetimes is printed to the console whenever the Exchange-server returns naive datetime-strings in its XML-response while using `GetUserAvailability`, or more generally, using `Account.protocol.get_free_busy_info`. The warning stems from https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/fields.py#L690 in `DateTimeField`, which tries to make the datetimes timezone-aware with the provided `Account` object in case naive datetimes are returned by the server. This warning cannot be circumvented if the server returns naive datetimes as it happens while parsing the XML to python objects, so before one can interact with it conveniently.

The solution I would propose to this is allowing to set the `Account` object in https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/services/get_user_availability.py#L27, which is currently hard-set to `None`; this would result in `DateTimeField` attaching the `default_timezone` of the passed `Account` object to naive datetimes. 
Changing that so that an `Account` object can be passed to `GetUserAvailability` (or also just passing a default timezone which is then attached to an `Account` object and passed to `FreeBusyView.from_xml`) should solve the logging problems without affecting anything else about `DateTimeField`. Since `Account.protocol.get_free_busy_info` (https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/protocol.py#L496C9-L496C17) is a method of the `Account` object itself, perhaps it is possible to use the `default_timezone` provided there instead of requiring it to be passed as a variable to `get_free_busy_info`; I am not sure if that attribute can be accessed from `Account.protocol` though since I lack the experience in Python for that. 

The alternative provided in the issue cited above works but suppresses all warnings for the `exchangelib` while doing so and also does not solve the problem. The change I proposed is a tiny one indeed and should not affect anything but `GetUserAvailability` while solving the logging problem and making `DateTimeField.from_xml` work as intended.

Is there a certain reason for the `Account` being hardcoded to `None` that I just missed? In case I misunderstood or forgot about something, please let me know; as stated above, I'm not that experienced yet myself.

**Comment by ecederstrand** [comment]
The `GetUserAvailability` service can be called on any mailbox, and the returned naive datetimes would be local to the timezone of that mailbox, which is not guaranteed to be the same as the `Account` you just happen to be calling `Account.protocol.get_free_busy_info()` from.

**Comment by Archern4r** [comment]
Perhaps a solution making it possible to pass a default `EWSTimeZone` to `get_free_busy_info` in case the server returns naive datetimes instead of inferring the default timezone from the `Account` that's calling would be better then? The default value for that could remain `None` so that people who provide a default timezone should know what they are doing and either correct timezones for datetimes or only group users with the same timezones in their `get_free_busy_info`-queries. Currently if naive datetimes are returned, you need to correct the timezones for every `CalendarEvent` object afterwards too and you either need to suppress the warning or have your console spammed. I feel in many use-cases (mostly the ones with mostly the same timezones for all mailboxes) this proposed change would be an improvement over current functionality and it would also be a pretty small.

Are you generally opposed to the idea of changing that hardcoded `account=None` in https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/services/get_user_availability.py#L27?

Should I provide a code example for convenience or is that not necessary?

**Comment by ecederstrand** [comment]
I see that we're already picking out the timezone of the `start` argument to `Protocol.get_free_busy_info()` and passing that to the `GetUserAvailability` service. Looking at https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/getuseravailability-operation#getuseravailability-operation-soap-headers, it's documented that the `TimeZoneContext` SOAP header applies to all datetime values in the response. So We could override `GetUserAvailability._timezone` to set this timezone, and then make sure the code that parses the naive datetimes in the response also gets access to this timezone object.
