### ISSUE TITLE
Not enough scope error 

### ISSUE THREAD

**Issue by usnarr** [ecederstrand/exchangelib#1321]
Python 3.12  Exchangelib 5.4.1

I am trying to access the items in the mailbox but I keep getting 403 code with this message: 'x-ms-diagnostics': '2000008;reason="The token contains not enough scope to make this call.". In azure I have permissions:
email, mail.read, mail.readWrite ,mailboxsettins.read ,offline_access , SMTP.send , user.readm IMAP.AccessAsUser.all
IS this an scope parameter issue?

```python
client_id = client_id
client_secret = client_secret
tenant_id = tenant_id
authority = f'https://login.microsoftonline.com/{tenant_id}'
scope =  ["https://outlook.office365.com/.default"]    

# Create a confidential client application
app = msal.ConfidentialClientApplication(
    client_id,
    authority=authority,
    client_credential=client_secret,
)

# Acquire a token
result = app.acquire_token_for_client(scopes=scope)

if 'access_token' in result:
    access_token = result['access_token']
    print(f'Access token: {access_token}')
else:
    print(f'Error: {result.get("error")}')
    print(f'Description: {result.get("error_description")}')
    print(f'Correlation ID: {result.get("correlation_id")}')
token = OAuth2Token({
    'access_token': access_token,
    'token_type': 'Bearer',
    'expires_in': result['expires_in'],
    'scope': scope,
})
# Setup OAuth2 credentials
credentials = OAuth2Credentials(
    client_id=client_id,
    client_secret=client_secret,
    tenant_id=tenant_id,
    access_token=token
    
)

# Setup configuration
config = Configuration(
        credentials=credentials,
        server = 'outlook.office.com',
        auth_type=OAUTH2,
    version=Version(build=EXCHANGE_O365))

# Setup account
account = Account(
    primary_smtp_address= mymail,
    config=config,
    autodiscover=False,
    access_type=IMPERSONATION
)
print(f"ACCOUNT    {account}")
if account:
     print("connecteddddd")
for item in account.inbox.all():
        print("got item ", item.sender)
```

**Comment by ecederstrand** [comment]
The permissions needed are documented in https://ecederstrand.github.io/exchangelib/#delegate-oauth-on-office-365. The one you need is `EWS.AccessAsUser.All`. It's possible that you can get it to work with less, but I haven't tested other combinations.

**Comment by usnarr** [comment]
Here are the current permissions, unfortunately I keep on getting 403  'x-ms-diagnostics': '2000008;reason="The token contains not enough scope to make this call.";error_category="invalid_grant"' , I tried grating full_access_as_app  but it does not work either.

![image](https://github.com/ecederstrand/exchangelib/assets/115319980/29d316bb-cb05-4cb7-a1e5-334e717436c0)

**Comment by ecederstrand** [comment]
Try following the guide at https://ecederstrand.github.io/exchangelib/#delegate-oauth-on-office-365 meticulously. It has been tested to work.

**Comment by usnarr** [comment]
Thank you that was helpful!
