### ISSUE TITLE
BASIC in exchangelib

### ISSUE THREAD

**Issue by rshunim** [ecederstrand/exchangelib#1333]
BASIC authentication is no longer supported.
Can you tell me when it will be removed from the library?

Thanks
Roei

https://support.microsoft.com/en-us/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d 

![image](https://github.com/user-attachments/assets/e3839993-c3e2-4f54-848e-27fc8f030a8c)

**Comment by ecederstrand** [comment]
That notice only applies to Microsoft-hosted Exchange services. There are still lots of on-prem Exchange servers running that offer, or can be configured to offer, BASIC auth.

**Comment by ecederstrand** [comment]
Closing since some users still need support for Basic auth.
