### ISSUE TITLE
Missing license declaration for `winzone.py`

### ISSUE THREAD

**Issue by stefan6419846** [ecederstrand/exchangelib#1336]
**Describe the bug**

https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/winzone.py embeds data sourced from an unknown version of https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml Depending on the version, they are subject to either Unicode-DFS-2016 or Unicode-3.0, which both require to at least include the copyright and permission notice with the distribution. As far as it concerns the wheels, this is not the case at the moment, but might affect source distributions as well.

**Expected behavior**

*exchangelib* documents which version of the `windowsZones.xml` is being included and whether changes have been done. Additionally, the copyright and permission notice are shipped within *exchangelib* accordingly.

**Additional context**

Disclaimer: IANAL.

**Comment by ecederstrand** [comment]
The version of CLDR is specified here: [CLDR_WINZONE_TYPE_VERSION = "2021a"](https://github.com/ecederstrand/exchangelib/blob/b4ce1873cc04f17f7e9203ed4840f51a480d44ce/exchangelib/winzone.py#L12)

https://github.com/unicode-org/cldr/blob/main/common/supplemental/windowsZones.xml only claims copyright until 2013, but in any event it links to http://www.unicode.org/copyright.html which again links to this license for Data Files: https://www.unicode.org/license.txt

I don't see anything in that license that requires exchangelib to make any adjustments. I also don't think that Unicode can claim copyright over Windows timezone names, which is the only thing exchangelib is reproducing in our winzone.py.

**Comment by stefan6419846** [comment]
The repository has a license and points to a license files, thus apparently someone considered it copyrightable. IANAL, but at least in Germany, such collections might receive protection due to database rights and require licenses accordingly to declare usage policies.

**Comment by ecederstrand** [comment]
I'm not sure I come to the same conclusion, but I don't mind if you create a PR that adds a link to https://www.unicode.org/license.txt to the top of winzone.py.
