### ISSUE TITLE
HTML Email Styles Not Applied When Sending to Gmail Using Exchange 2016

### ISSUE THREAD

**Issue by shmuel44** [ecederstrand/exchangelib#1341]
**Describe the bug**
I am experiencing an issue when sending HTML emails to Gmail using Exchange 2016 (Build 15.1). The styles defined in the HTML body are not being applied in the received email. However, when I use Exchange 2019 (Build 15.2), the styles are correctly applied in Gmail.

**To Reproduce**
1 . Use the following script to send an email with HTML content using Exchange 2016 (Build 15.1):
```python
from exchangelib import Credentials, Account, Configuration, Version, Message, HTMLBody
from exchangelib.version import EXCHANGE_2016, EXCHANGE_2019

SERVER = ".com"
USERNAME = ""
PASSWORD = ""
EMAIL_ACCOUNT = "@"
TO= "@gmail.com"

def send_test_email():

      credentials = Credentials(USERNAME, PASSWORD)
      config = Configuration(server=SERVER, credentials=credentials, auth_type="NTLM", version=Version(EXCHANGE_2016))
      account = Account(EMAIL_ACCOUNT, config=config, autodiscover=False, access_type="delegate")

      message = Message(
          account=account,
          subject="Test Email",
          body=HTMLBody("""
              <h1 style="color: blue; font-family: Arial, sans-serif;">This is a test email</h1>
              <p style="color: green; font-family: Verdana, sans-serif;">With an HTML body.</p>
          """),
          to_recipients=[TO],
      )

message.send_and_save()
```
2. Send the email to a Gmail account.

3. Observe that the styles are not applied in the received email.

**Expected behavior**
The HTML styles should be applied in the received email when using Exchange 2016, just as when using Exchange 2019.

**Log output**
```sh
  <h:ServerVersionInfo
    xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="1" MajorBuildNumber="2176" MinorBuildNumber="9" Version="V2017_07_11"/>
  </s:Header>
```

**Additional context**
exchangelib version: 5.4.3
Exchange Server version: 2016 (Build 15.1)
Python version: 3.10

**Comment by ecederstrand** [comment]
exchangelib doesn't do things differently in this case depending on the version of the remote Exchange server. I assume that the two Exchange servers send the email with slightly different formatting. The easiest test would be to send two identical emails to Gmail using the two different Exchange versions and in GMail inspecting the differences between the two emails.

Also, I would expect that the same happens if you send the email with Outlook instead of exchangelib. Is that the case?

**Comment by shmuel44** [comment]
Hi @ecederstrand,
When I send an email through Outlook, the HTML is sent with styling.

When I send an email via a different library, I notice the following headers when it reaches Gmail:

Via the library:
```
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
```
Via Outlook:
```
Content-Type: application/ms-tnef; name="winmail.dat"
Content-Transfer-Encoding: binary
```

**Comment by shmuel44** [comment]
Here is the email row that I received when I sent the email via Exchange 2019. (👍):

```
Subject: Test Email SK 2019
Thread-Topic: Test Email SK 2019
Thread-Index: dummy
Date: Thu, 7 Nov 2024 16:38:37 +0000
Message-ID: dummy
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: 
X-MS-TNEF-Correlator: 
x-originating-ip: dummy
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
</head>
<body>
<h1 style=3D"color: blue; font-family: Arial, sans-serif;">This is a test e=
mail</h1>
<p style=3D"color: green; font-family: Verdana, sans-serif;">With an HTML b=
ody.</p>
</body>
</html>
```

Here is the email row that I received when I sent the email via Exchange 2016. (👎 ):
```
Subject: Test Email SK 2016
Thread-Topic: Test Email SK 2016
Thread-Index: dummy
Date: Thu, 7 Nov 2024 16:37:55 +0000
Message-ID: dummy
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: 
X-MS-TNEF-Correlator: dummy
x-originating-ip: dummy
MIME-Version: 1.0

--dummy
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

This is a test email

With an HTML body.

--dummy ID_
Content-Disposition: attachment; filename="winmail.dat"
Content-Transfer-Encoding: base64
Content-Type: application/ms-tnef; name="winmail.dat"


--dummy--
```

**Comment by shmuel44** [comment]
Thank you for your help! 👑
