### ISSUE TITLE
Getting KeyError: 'folders' when trying to read subfolders of inbox

### ISSUE THREAD

**Issue by psmitak** [ecederstrand/exchangelib#1343]
I am getting KeyError: 'folders' error when I am trying to access subfolders of Inbox of a shared online mailbox. The same code is working for rest of the mailboxes. There is no issue with permissions as well. 

Below is the error:

`Traceback (most recent call last):
  File "C:\virtualenvs\ctenv\lib\site-packages\cached_property.py", line 70, in __get__
    return obj_dict[name]
KeyError: 'folders'`

I am using 4.7.4 version of ExchangeLib.

Could you please point out the cause of this issue?

Thanks,
Smita

**Comment by ecederstrand** [comment]
Thanks for the report. The `KeyError` is a consequence of the use of cached properties in exchangelib. The full stack trace for the exception contains more than what you posted, and the rest of the stack trace contains the actual cause of your exception.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you get the time to post the full stack trace.
