### ISSUE TITLE
EWS Calendar ID, Contact Id and Task Id of item

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#135]
Is it possible to get Calendar ID, Contact Id and Task Id of item?

**Comment by ecederstrand** [comment]
I'm not sure I understand your question. `Item` objects fertched from EWS have `item_id` and `changekey` attributes, if that's what you meant. If not, please point to sone EWS docs describing these fields.

**Comment by ecederstrand** [comment]
@shireen91 Please close this issue if my answer solved your issue, or explain in mere detail what you wanted instead.
