### ISSUE TITLE
Moving Category of the item

### ISSUE THREAD

**Issue by kkckc24** [ecederstrand/exchangelib#136]
Hello This is David.

# I logined the Exchange Server and took the items as below:
all_items=account.inbox.all()
# then wanted to move the folder as below:
target_folder=account.inbox.get_folder_by_name("TCN")
recentone = all_items[0]

# then I wanted to move the folder to "TCN"
recentone.folder=target_folder;
recentone.save()

However, it's not working and I cannot find the solution at the moment.
Is there any other way to move the folder of the item?

Thank you in advance.
David

**Comment by ecederstrand** [comment]
You can't move items to new folders like that :-) You need to use the `move()` method. See https://github.com/ecederstrand/exchangelib#creating-updating-deleting-sending-and-moving

**Comment by kkckc24** [comment]
move() method is working well 👍 
recentone.move(to_folder=target_folder) 

Thank you very much esederstrand,
