### ISSUE TITLE
Support for Exchange Named Properties

### ISSUE THREAD

**Issue by SidharthPati** [ecederstrand/exchangelib#137]
Is there support to fetch the Exchange Named Properties?
If yes, then can you please tell me how?

**Comment by ecederstrand** [comment]
Hi @SidharthPati By "named properties", I assume you mean extended properties? If not please describe or post a link describing what you would like.

Extended properties are supported. There's a short description here: https://github.com/ecederstrand/exchangelib#extended-properties

The magic values Microsoft uses for common extended properties is something you'll have to look up elsewhere.

**Comment by SidharthPati** [comment]
Hey @ecederstrand , 

_# If folder items have extended properties, you need to register them before you can access them. Create
# a subclass of ExtendedProperty and set your custom property_id:
class LunchMenu(ExtendedProperty):
    property_set_id = '12345678-1234-1234-1234-123456781234'
    property_name = 'Catering from the cafeteria'
    property_type = 'String'_

In the above snippet, we are registering the id, name and type here. But is there a way in which we can fetch id, name and type of any given mail present in the Exchange Server.

Given any mail, I want to fetch these properties.

**Comment by ecederstrand** [comment]
I'm not sure EWS is able to hand out all extended properties on a given item without naming them explicitly.

You could try to add debug logging and call `some_folder.find_items(Q(), shape='AllProperties')` to see what EWS is able to return whan you ask it to return everything.

**Comment by shireen91** [comment]
Is it possible to get message class of email by default?

**Comment by shireen91** [comment]
I tried following snippet.. I am getting exception

class LunchMenu(ExtendedProperty):
    property_id = '12345678-1234-1234-1234-123456781234'
    property_name = 'Catering from the cafeteria'
    property_type = 'String'

credentials = ServiceAccount(username=service_name, password=pwd)
    config = Configuration(credentials=credentials,
                           server=server_name,
                           verify_ssl=False,
                           auth_type=NTLM)
    account = Account(primary_smtp_address=mailboxname, config=config, access_type=IMPERSONATION)
    folders = account.folders

  Message.register('lunch_menu',LunchMenu)
  for folder in folders.values():
        for item in folder:
                 for message in item.all().order_by('-datetime_received')[:100]:
                print message.last_modified_time







    for message in item.all().order_by('-datetime_received')[:100]:
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\queryset.py", line 161, in __iter__
    for val in result_formatter(self._query()):
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\account.py", line 406, in fetch
    for i in GetItem(account=self).call(items=ids, additional_fields=only_fields):
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\services.py", line 450, in _pool_requests
    elems = r.get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.

**Comment by SidharthPati** [comment]
hi @ecederstrand , any update on this?

**Comment by ecederstrand** [comment]
Sorry for not getting back to you before. In your extended property, `property_id` should be spelled `property_set_id`. See https://github.com/ecederstrand/exchangelib/blob/master/README.rst#extended-properties

I got this example to work locally:

```python
from exchangelib import Account, Credentials, ExtendedProperty, Message

email = 'john@example.com'
password = 'secret'
a = Account(email, credentials=Credentials(email, password), autodiscover=True)

class LunchMenu(ExtendedProperty):
    property_set_id = '12345678-1234-1234-1234-123456781234'
    property_name = 'Catering from the cafeteria'
    property_type = 'String'

Message.register('lunch_menu', LunchMenu)
for folders in a.folders.values():
    for folder in folders:
        for item in folder.all().order_by('-datetime_received')[:100]:
            print(item.last_modified_time)
```

**Comment by michael-doubez** [comment]
Hello,

For Named Properties (created from User Defiend Fields in outlook), I got it working by using `distinguished_property_set_id` instead:

```Python
class LunchMenu(ExtendedProperty):
    distinguished_property_set_id = 'PublicStrings'
    property_name = 'Catering from the cafeteria'
    property_type = 'String'
```

Got it from there : https://blogs.technet.microsoft.com/exchange/2009/04/06/named-properties-x-headers-and-you/

**Comment by ecederstrand** [comment]
Thanks for the example, @michael-doubez I'm not very familiar with extended properties myself, so it's good to get more examples of working code!

**Comment by SidharthPati** [comment]
The example given by @michael-doubez is spot on. It worked for me and @shireen91 . Thanks a lot @michael-doubez and @ecederstrand
