### ISSUE TITLE
Shared Calendars

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#138]
Hi, 

now that I've got our Exchange Server at work to communicate with my script I was wondering how I can access calendars from other contacts.

In Outlook 2016 I would do something like 'open calendar from address book' to see calendars that have been shared with me.

Is there a way to realise that with your library?

Best regards
Roland

**Comment by ecederstrand** [comment]
I'm not sure you can find out which calendars you have access to, but you can open calendars of other accounts just by creating a new `Account` with your own credentials.

**Comment by fruitloop** [comment]
I do know what calendars I have access to from Outlook.

So I would just initialize an account object with my credentials but another SMTP_address?

________________________________

**Comment by ecederstrand** [comment]
Yes, that's how it works. You'll have to test if you have access via delegation or impersonation, but it's a simple setting on the `Account` object.

**Comment by kamalpy** [comment]
@ecederstrand is there any way to do that without the delegate permission? I tried to access the calendar of employees in my organization but I can access only when they grant me delegate access explicitly otherwise the calendar folder doesn't exist for particular user.

**Comment by ecederstrand** [comment]
There's a service called `GetUserAvailability` which may provide what you want: https://msdn.microsoft.com/en-us/library/office/aa564001(v=exchg.150).aspx

I don't think you'll be able to get access to the calendar of other accounts unless you have been granted access somehow.

**Comment by kamalpy** [comment]
Thanks, it worked.

**Comment by iDevo** [comment]
@kamalpy I'm exactly looking for the same function too, so I'm able to check the availability of other employees. Is it possible to share your code? 
Thanks you in advance!

**Comment by ecederstrand** [comment]
@iDevo From what I understand, this is a permissions issue on the Exchange server. If your connecting credentials don't have access to the account you're trying to query, there's nothing exchangelib can do.

The `GetUserAvailability` service is not implemented yet, but there's a workaround in https://github.com/ecederstrand/exchangelib/issues/256

**Comment by kamalpy** [comment]
Hi @iDevo, sorry just saw this.
I won't be able to share the code due to company policy(the reason I wasn't able to send pull request in first place),  but let me see if I can help.

**Comment by ecederstrand** [comment]
@kamalpy So your company policy allows you to use open source code, but not contribute back? That's a really nasty company policy :-)
