### ISSUE TITLE
how to create a new mailbox from a new user in Active directory?

### ISSUE THREAD

**Issue by bonhomie** [ecederstrand/exchangelib#142]
Is there a way to create a new mailbox similar to the powershell command 
New-Mailbox -UserPrincipalName $upn -Alias $alias -Name $name -SamAccountName $name -FirstName $fn -LastName $ln -Password (ConvertTo-SecureString $pww -AsPlainText -Force)

??

**Comment by djreynolds922** [comment]
I don't believe that would be in scope for this project. This project is focused on logging into the mailboxes with Python and manipulating the contents, not managing an Exchange Deployment.

**Comment by ecederstrand** [comment]
Hi @bonhomie 

At least for the time being, this library will only support functions that are exposed via EWS. It's not meant to be a frontend for the Exchange PowerShell commands.
