### ISSUE TITLE
Exporting Items

### ISSUE THREAD

**Issue by djreynolds922** [ecederstrand/exchangelib#143]
Hey, I'm sure I'm doing something wrong as I'm just a novice developer trying to make sense of stuff. I'm trying to write a script to download all attachments from an E-mail and then also download the E-mail itself to include. When I utilize the export function like this:

`account.export([item])`

I get a massive string which doesn't appear to be usable to me to save in a file format. From reading through the EWS Documentation, it appears I need to also get the MIME content? I really have no clue here. Is there a way to download a Message object from your library in a format that can be saved as a file?

**Comment by djreynolds922** [comment]
Discovered what .mimecontent actually is, which is exposed by the message object in this library. Wrote that to a .eml file and it's exactly what I need.

For anyone else who might have this issue, here's a code snippet:

`for item in inbox.all():
    with open(os.path.join(local_path), "wb") as f:
        f.write(item.mime_content)`

**Comment by ecederstrand** [comment]
Hi @djreynolds922 Yes, `mimecontent` is a good candidate for what you want to do. `Account.export()` is a complementary method to `Account.upload()` and are meant for archiving and data migration purposes.

**Comment by marioschaefer** [comment]
Hi, im trying to achieve something similar and think it suits best into this Thread, so i didnt open a new one.
We want to use your API for archiving the whole mailbox.
@ecederstrand 
I used to do that with the "AllItems"-folder, but learned that its created by outlook and if you dont use Outlok you dont have this folder.
I Have two questions, **first**: is there a similar folder to the "allitems"-folder, or can i get all items(and if possible: only the emails) of the whole mailbox?
If i do: 
```python
inboxfolder = account.inbox
messages = list(inboxfolder.all().order_by('datetime_received'))
```
I get only 16 mails, which is the actual foldercontent of my "Inbox"-Folder.

**second**: 
Can i only download the "mime_content"(i dont need all the other fields) of a message, to reduce the traffic between the server and our script?
Or are these fields generated by the API on the client?
```python
inboxfolder = account.inbox
messages = list(inboxfolder.all().only('mime_conent').order_by('datetime_received'))
```
-> throws an exception:
```python
Property is not valid for this operation. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="item:MimeContent" />)
```

**Comment by ecederstrand** [comment]
1) I don't think there's a method to get all items in a mailbox, unfortunately, and I don't know of any meta-folders that contain what you want. The [FindItem](https://msdn.microsoft.com/en-us/library/office/aa566107(v=exchg.150).aspx) operation we use to discover items require a list of folders.

2) This is a bug in the latest release. It's fixed on the master branch.

**Comment by marioschaefer** [comment]
@ecederstrand 
thanks for your quick reply.
Is there some kind of filter to get only mail-items, no calendar or notes or etc?

**Comment by ecederstrand** [comment]
You could probably add a filter on a message-only field, e.g. `.filter(sender__exists=True)`, but you could also just do this in your own code:

```python
from exchangelib import Message

for item in account.some_folder.all():
    if not isinstance(item, Message):
        continue
    # Do something with the message
```

**Comment by marioschaefer** [comment]
first will filter on the server and i will only get the items with an existing sender.
second solution means i will download all the items, and after that i will check if it's a message.
correct?

**Comment by ecederstrand** [comment]
Yes, that's correct. You might have messages without a sender, if they are drafts, so be careful with the first solution. The latter requires more bandwidth but is safer.

**Comment by marioschaefer** [comment]
understood.
Thanks! much appreciated!

**Comment by AnkushGupta02** [comment]
@ecederstrand  I am working on the similar lines but instead of saving all emails i just need a single email which matches the condition. Here is what i am doing.

```
for item in account.inbox.filter(is_read=False).order_by('-datetime_received')[:0]:
      if item.subject.startswith('XYZ') and item.sender.email_address.lower() in sender:
           save_email(item)

def save_email(message):
    msgs = [m.mime_content for m in message]
    msg_qa_file_path = "path"
    msg_full_file_path = os.path.join(msg_qa_file_path,  message.subject+'.eml')
    with open(msg_full_file_path, 'w') as f:
        f.write(str(msgs))
```
Below is the error i am getting 
**msgs = [m.mime_content for m in message]
TypeError: 'Message' object is not iterable**

Can someone suggest how to save a single email based on keyword matching? Thanks in advance.

**Comment by ecederstrand** [comment]
The error is thrown because you are treating `message` as if it is a list of messages, but the way you are calling `save_email()`, `message` is a single email message.

So, either call `save_email()` with a list of messages, or change `save_email()` to threat `message` as a single message: ``msgs = message.mime_content`

**Comment by AnkushGupta02** [comment]
@ecederstrand Thanks for your prompt response. Much appreciated. It worked. A quick question do we have any provision in exchangelib current version to save the email in .msg format ?

**Comment by ecederstrand** [comment]
No, there is no such functionality. The reason is that, to my knowledge, there is no actual .msg file format specification. It's just text with whatever your email client happens to be able to parse.
