### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by kkckc24** [ecederstrand/exchangelib#147]
Hello. This is David. 

The simple login is not working on the specific computer which got all windows-updated.
The code was working fine but not working from today after I got windows updated.

Would you please give me any advice for the following code?
I re-installed anaconda and exchangelib but I cannot fix it.

Thank you in advance.

My login code is as belows:

`from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version

``# User Information`
myuserid = 'kckang'
mypassword = 'test
mydomain = 'ttt'
myaccount = 'kckang@ttt.co.kr'

creds = Credentials(username='{}\{}'.format(mydomain, myuserid), password=mypassword)
account = Account(primary_smtp_address=myaccount, credentials=creds, autodiscover=True, access_type=DELEGATE)`

The errors are as below

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\Users\kckang\Anaconda3\lib\shelve.py in __getitem__(self, key)
    110         try:
--> 111             value = self.cache[key]
    112         except KeyError:

KeyError: 'ht.co.kr'

During handling of the above exception, another exception occurred:

EOFError                                  Traceback (most recent call last)
<ipython-input-1-8cbf07c42d6c> in <module>()
      8 
      9 creds = Credentials(username='{}\{}'.format(mydomain, myuserid), password=mypassword)
---> 10 account = Account(primary_smtp_address=myaccount, credentials=creds, autodiscover=True, access_type=DELEGATE)

C:\Users\kckang\Anaconda3\lib\site-packages\exchangelib\account.py in __init__(self, primary_smtp_address, fullname, access_type, autodiscover, credentials, config, verify_ssl, locale)
     52                 raise AttributeError('config is ignored when autodiscover is active')
     53             self.primary_smtp_address, self.protocol = discover(email=self.primary_smtp_address,
---> 54                                                                 credentials=credentials, verify_ssl=verify_ssl)
     55         else:
     56             if not config:

C:\Users\kckang\Anaconda3\lib\site-packages\exchangelib\autodiscover.py in discover(email, credentials, verify_ssl)
    169     if autodiscover_key in _autodiscover_cache:
    170         # Python dict() is thread safe, so accessing _autodiscover_cache without a lock should be OK
--> 171         protocol = _autodiscover_cache[autodiscover_key]
    172         assert isinstance(protocol, AutodiscoverProtocol)
    173         log.debug('Cache hit for domain %s credentials %s: %s', domain, credentials, protocol.server)

C:\Users\kckang\Anaconda3\lib\site-packages\exchangelib\autodiscover.py in __getitem__(self, key)
    100         domain, credentials, verify_ssl = key
    101         with shelve_open(self._storage_file) as db:
--> 102             endpoint, auth_type = db[str(domain)]  # It's OK to fail with KeyError here
    103         protocol = AutodiscoverProtocol(service_endpoint=endpoint, credentials=credentials, auth_type=auth_type,
    104                                         verify_ssl=verify_ssl)

C:\Users\kckang\Anaconda3\lib\shelve.py in __getitem__(self, key)
    112         except KeyError:
    113             f = BytesIO(self.dict[key.encode(self.keyencoding)])
--> 114             value = Unpickler(f).load()
    115             if self.writeback:
    116                 self.cache[key] = value

EOFError: Ran out of input
``

**Comment by ecederstrand** [comment]
It seems your on-disk autodiscover cache database got corrupted somehow. Until we can recover from this error automatically, you should be able to fix this with:

```python
from exchangelib.autodiscover import AUTODISCOVER_PERSISTENT_STORAGE
import os
os.unlink(AUTODISCOVER_PERSISTENT_STORAGE)
```

**Comment by kkckc24** [comment]
Thank you ecederstrand,

I went to 'C:\Users\kckang\AppData\Local\Temp' folder and deleted related files and it is working well at the moment

Thank you very much !!

**Comment by ecederstrand** [comment]
Reopening make sure we fix the code to survive corrupted cache files throwing `EOFError` :-)

**Comment by kkckc24** [comment]
FYI, when I first run the code I got the response as follows:

Thank you very much :)

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-6e343e49cbc1> in <module>()
      1 from exchangelib.autodiscover import AUTODISCOVER_PERSISTENT_STORAGE
      2 import os
----> 3 os.unlink(AUTODISCOVER_PERSISTENT_STORAGE)

FileNotFoundError: [WinError 2] Cannot found the file 'C:\\Users\\kckang\\AppData\\Local\\Temp\\exchangelib.cache'

**Comment by ecederstrand** [comment]
Yeah, you should just run the code *once*. After that, the file is deleted and will be created again automatically. If you had the above code at the top of your script, you can delete it again now.

**Comment by RoelantStegmann** [comment]
I have the same problem, and the solution does not work (says it cannot find the file). I used

from exchangelib.autodiscover import AUTODISCOVER_PERSISTENT_STORAGE
import glob
import os 

for f in glob.glob(os.path.dirname(AUTODISCOVER_PERSISTENT_STORAGE) + '\exchangelib*'):
    print(f)
    os.unlink(f)
