### ISSUE TITLE
Create/update/delete folders (Again)

### ISSUE THREAD

**Issue by kkckc24** [ecederstrand/exchangelib#148]
Hello, This is David

I have been looking for the way to create folder and found the https://github.com/ecederstrand/exchangelib/issues/110

However, it seems like not working at this moment. 

Would you please insight me to how to create folder at this moment?

Thank you in advance.
David

**Comment by ecederstrand** [comment]
The posted code in #110 is just an example of how it *could* work :-) Folder CRUD is still not implemented.

For now, if you want to create folders, you'll have to do it with Outlook or some other EWS client.

**Comment by kkckc24** [comment]
Hello ecederstrand,

I got the error as follows and it was working well until last week.

  File "<ipython-input-7-82af1a398182>", line 1
    my_folder = Folder(name'My Folder', parent=my_account.inbox)
                                     ^
SyntaxError: invalid syntax

Did i missing anything ?

**Comment by ecederstrand** [comment]
That's strange. The code you posted is missing a `=` after `Foler(name` but even when yo put that in, you should get `AttributeError: 'parent' are invalid kwargs for this class` because parent-child relationships are not yet implemented.

**Comment by kkckc24** [comment]
I got the same message from two laptop.
My environment is anaconda 4.3.1 (64-bit) on python 3.6.0. 

anythow, I understood that it's not the scope of the project 
and always appreciated for this project 

Thank you 

my_folder = Folder(name'My Folder', parent=my_account.inbox)
my_folder.save()
another_folder = Folder(name'Another Folder', parent=my_folder)
another_folder.save()

  File "<ipython-input-7-82af1a398182>", line 1
    my_folder = Folder(name'My Folder', parent=my_account.inbox)
                                     ^
SyntaxError: invalid syntax

**Comment by ecederstrand** [comment]
You're getting a `SyntaxError` because the last line should be `my_folder = Folder(name='My Folder', parent=my_account.inbox)` (your code is missing the `=` sign).

Deleting and creating folders *is* in scope of this project. It's just that nobody has had the time to implement it yet :-)
