### ISSUE TITLE
sending attachment on EWS 2007

### ISSUE THREAD

**Issue by robjuffermans** [ecederstrand/exchangelib#150]
I'm trying to send an attachment through Exchange EWS 2007 and get this error. Any clue?

```python
File "scan.py", line 268, in send_mail
    fa = ex.FileAttachment(name=attachment_name, content=attachment_content)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/items.py", line 515, in send_and_save
    send_meeting_invitations=send_meeting_invitations
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/items.py", line 168, in _create
    send_meeting_invitations=send_meeting_invitations)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/account.py", line 245, in bulk_create
    send_meeting_invitations=send_meeting_invitations,
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/account.py", line 239, in <genexpr>
    i if isinstance(i, Exception)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/services.py", line 452, in _pool_requests
    for elem in elems:
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/services.py", line 264, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/services.py", line 237, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "/home/rob/.venvs/exchange/lib/python3.6/site-packages/exchangelib-1.9.3-py3.6.egg/exchangelib/services.py", line 254, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="item:Attachments" />)
```

**Comment by ecederstrand** [comment]
Can you post example code exhibiting this behavior? We shouldn't end up in this code path when adding attachments.

EWS is vague on whether attachments are actually supported on Exchange 2007, but at least you reported success in fetching attachments in #100.

**Comment by robjuffermans** [comment]
m = ex.Message(account=self.account,                                     
                folder=self.account.sent,                                        
                subject=subject,                                                 
                body=body,                                                       
                to_recipients=to_recipients                                      
        )                                                                        
                                                                                 
            for attachment_name in attachments:                                  
                path = os.path.join(self.attachmentsdir, str(mail['doc_documentatie_id']), attachment_name)
                if os.path.isfile(path):                                         
                    with open(path, 'rb') as f:                                  
                        attachment_content = f.read()                            
                        fa = ex.FileAttachment(name=attachment_name, content=attachment_content)
                        m.attach(fa)                                             
        m.send_and_save()

**Comment by ecederstrand** [comment]
Thanks. I don't think the test suite covers adding an attachment and then sending. I'll have to test this locally before I can give you a more informed answer.

**Comment by ecederstrand** [comment]
Hmm. I got this simplified code to work against my test server, which is Exchange 2013:

```python
from exchangelib import Message, FileAttachment, Credentials, Account

a = Account(email, credentials=Credentials('john@example.com', 'secret'), autodiscover=True)

m = Message(
   folder=a.sent,
   subject='My Subject',
   body='My Body',
   to_recipients=['erik@cederstrand.dk'],
)

fa = FileAttachment(name='My File', content=b'My Binary Content')
m.attach(fa)
m.send_and_save()
```

So it's not a general problem with exchangelib. Can you post the request XML that triggered the error? Just enable debug logging as described in https://github.com/ecederstrand/exchangelib#troubleshooting

It's possible that Exchange 2007, or at least your version of it, just doesn't support this operation.

**Comment by robjuffermans** [comment]
Hi, I know it is possible to send Attachments through EWS, because I'm already doing that by creating the XML messages myself. But I prefer using your library :)

Here's the composed XML message:

Request headers: {'User-Agent': 'python-requests/2.13.0', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '1963'}
Response headers: {'Cache-Control': 'private, max-age=0', 'Content-Length': '1025', 'Content-Type': 'text/xml; charset=utf-8', 'Server': 'Microsoft-IIS/7.0', 'X-AspNet-Version': '2.0.50727', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 22 Jun 2017 21:05:46 GMT'}
Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2007_SP1" /></s:Header><s:Body><m:CreateItem MessageDisposition="SendAndSaveCopy" SendMeetingInvitations="SendToNone"><m:SavedItemFolderId><t:FolderId ChangeKey="AQAAABYAAACbhmPzad87QZSvNTXEkAQvAD//KSIp" Id="AAMkADJlNDNhNDU0LTIzZDItNDYyNC1iOGY0LTMwNzA5NDg2MDcwYQAuAAAAAAAx6zQWGLR0SataD6JYGKk2AQCbhmPzad87QZSvNTXEkAQvAD//KSAMAAA=" /></m:SavedItemFolderId><m:Items><t:Message><t:Subject>test 2</t:Subject><t:Sensitivity>Normal</t:Sensitivity><t:Body BodyType="HTML">this is &lt;b&gt;bold&lt;/b&gt;</t:Body><t:Attachments><t:FileAttachment><t:Name>kassa.ini</t:Name><t:ContentType>application/octet-stream</t:ContentType><t:Content>W0dlbmVyYWxdDQpzaG9wbm89OTkNCg0KDQpkYXRhc2hvcD1jOlxkcmVhbVxkYXRhc2hvcCAyLjAuYWNjZGINCmRhdGFISz1jOlxkcmVhbVxkYXRhSEsubWRiDQoNCnJlbSB2b29ycmFhZCB3YWFyc2NodXdpbmcNCnZvb3JyYWFkd2FhcnNjaHV3aW5nPS0xDQoNCnJlbSBwaW5uZW4NCkhlZWZ0UE9JUD0wDQpYVElMTkVYVD0tMQ0KDQpyZW0gbW9uc3RlciBrYXNzYQ0KSXNtb25zdGVyPTANCg0KcmVtIGF1dG9pbnZvZXIga25vcA0KYXV0b2ludm9lcj0tMQ0KDQpyZW0gdG91Y2hzY3JlZW4NCnRvdWNoc2NyZWVuPTANCg0KDQpbcGluXQ0KZGVmYXVsdHBpbj0wNQ0KcGluMDU9UkVOVDAxDQpwaW4wMz1HU00wMQ0KDQpbZXJyb3JdDQo=</t:Content></t:FileAttachment></t:Attachments><t:Importance>Normal</t:Importance><t:ReminderIsSet>0</t:ReminderIsSet><t:ReminderMinutesBeforeStart>0</t:ReminderMinutesBeforeStart><t:ToRecipients><t:Mailbox><t:EmailAddress>rob@maxmath.nl</t:EmailAddress><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:ToRecipients><t:IsReadReceiptRequested>0</t:IsReadReceiptRequested><t:IsDeliveryReceiptRequested>0</t:IsDeliveryReceiptRequested><t:IsRead>0</t:IsRead><t:IsResponseRequested>0</t:IsResponseRequested></t:Message></m:Items></m:CreateItem></s:Body></s:Envelope>'
Response data: <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Header><t:ServerVersionInfo MajorVersion="8" MinorVersion="1" MajorBuildNumber="436" MinorBuildNumber="0" Version="Exchange2007_SP1" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" /></soap:Header><soap:Body><m:CreateItemResponse xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><m:ResponseMessages><m:CreateItemResponseMessage ResponseClass="Error"><m:MessageText>Set action is invalid for property.</m:MessageText><m:ResponseCode>ErrorInvalidPropertySet</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:FieldURI FieldURI="item:Attachments" /></m:MessageXml><m:Items /></m:CreateItemResponseMessage></m:ResponseMessages></m:CreateItemResponse></soap:Body></soap:Envelope>

**Comment by ecederstrand** [comment]
Thanks. Can you post the working Xml message also?

**Comment by robjuffermans** [comment]
haha no problem :)

First I create the item:

`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">

  <soap:Body>
    <CreateItem MessageDisposition="SaveOnly"
    xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">

      <SavedItemFolderId>
        <t:DistinguishedFolderId Id="drafts" />
      </SavedItemFolderId>
      <Items>
        <t:Message>
          <t:ItemClass>IPM.Note</t:ItemClass>
          <t:Subject>test 2</t:Subject>
          <t:Body BodyType="HTML">this is
          &lt;b&gt;bold&lt;/b&gt;</t:Body>
          <t:ToRecipients>
            <t:Mailbox>
              <t:EmailAddress>rob@maxmath.nl</t:EmailAddress>
            </t:Mailbox>
          </t:ToRecipients>
          <t:IsRead>false</t:IsRead>
        </t:Message>
      </Items>
    </CreateItem>
  </soap:Body>
</soap:Envelope>`

Then create the attachment:

`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">

  <soap:Body>
    <CreateAttachment xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">

      <ParentItemId Id="AAAOAGNzQHZhbmlsaWEuY29tAEYAAAAAAHRhVZsSAiJFnyN5WyQs/b8HAD/Q39VVqnNFh8BPExtDGtYAAACWIN8AAJuGY/Np3ztBlK81NcSQBC8BYeDsoSIAAA==" />
      <Attachments>
        <t:FileAttachment>
          <t:Name>kassa.ini</t:Name>
          <t:Content>
          W0dlbmVyYWxdDQpzaG9wbm89OTkNCg0KDQpkYXRhc2hvcD1jOlxkcmVhbVxkYXRhc2hvcCAyLjAuYWNjZGINCmRhdGFISz1jOlxkcmVhbVxkYXRhSEsubWRiDQoNCnJlbSB2b29ycmFhZCB3YWFyc2NodXdpbmcNCnZvb3JyYWFkd2FhcnNjaHV3aW5nPS0xDQoNCnJlbSBwaW5uZW4NCkhlZWZ0UE9JUD0wDQpYVElMTkVYVD0tMQ0KDQpyZW0gbW9uc3RlciBrYXNzYQ0KSXNtb25zdGVyPTANCg0KcmVtIGF1dG9pbnZvZXIga25vcA0KYXV0b2ludm9lcj0tMQ0KDQpyZW0gdG91Y2hzY3JlZW4NCnRvdWNoc2NyZWVuPTANCg0KDQpbcGluXQ0KZGVmYXVsdHBpbj0wNQ0KcGluMDU9UkVOVDAxDQpwaW4wMz1HU00wMQ0KDQpbZXJyb3JdDQo=</t:Content>
        </t:FileAttachment>
      </Attachments>
    </CreateAttachment>
  </soap:Body>
</soap:Envelope>`

and then send the item:

`<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">

  <soap:Body>
    <SendItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"
    SaveItemToFolder="true">
      <ItemIds>
        <t:ItemId Id="AAAOAGNzQHZhbmlsaWEuY29tAEYAAAAAAHRhVZsSAiJFnyN5WyQs/b8HAD/Q39VVqnNFh8BPExtDGtYAAACWIN8AAJuGY/Np3ztBlK81NcSQBC8BYeDsoSIAAA=="
        ChangeKey="CQAAABYAAACbhmPzad87QZSvNTXEkAQvAWHhLcdQ" />
      </ItemIds>
    </SendItem>
  </soap:Body>
</soap:Envelope>`

hope this helps!

**Comment by ecederstrand** [comment]
Thanks for the examples! It seems we need a special case for Exchange 2007 in this code path. I'll see what I can do in the next couple of days.

**Comment by robjuffermans** [comment]
Excellent!

Something different: maybe it's an idea to put the supported Python versions on your mainpage

**Comment by ecederstrand** [comment]
Thanks, I've added a version badge to the README now :-)

I haven't had time to fix this yet. What needs to happen is to change the `send_and_save()` path for Exchange2007 to first create the item, then create the attachment, and finally send the item, as you described.

**Comment by bjellesma-mastermans** [comment]
Hi, I'm just reopening to say that it looks as if this issue also affects Exchange 2010. The same fix of saving and sending seem to work.

**Comment by ecederstrand** [comment]
@bjellesma-mastermans Which specific version of Exchange is this? `print(account.protocol.version)` will tell you.

**Comment by bjellesma-mastermans** [comment]
@ecederstrand Build=14.1.438.0, API=Exchange2010_SP1, Fullname=Microsoft Exchange Server 2010 SP1

**Comment by ecederstrand** [comment]
I just committed a fix to include all versions of Exchange 2010 in the workaround.
