### ISSUE TITLE
API can't handle PostItem?

### ISSUE THREAD

**Issue by marioschaefer** [ecederstrand/exchangelib#151]
when i'm crawling through a mailbox:
```python
            allitemfolder = account.root.get_folder_by_name('AllItems')
            for message in allitemfolder.filter(datetime_received__range=(tz.localize(exchangelib.EWSDateTime(2017, 5, 1)), tz.localize(exchangelib.EWSDateTime(year, month, day+1)))).order_by('datetime_received'):
....
                    with open(filepath, 'wb') as f:
                        f.writelines(message.mime_content)
....
```
 i'm always getting this error when item number 7 is getting processed:
```'{http://schemas.microsoft.com/exchange/services/2006/types}PostItem'```
I'm not sure how to track this down.

I've also to admit that i don't know what this item is or what it exactly does, and i also dont need it.
I'm purely interested in Emails, so for me it would also be okay if you supply a workaround to "ignore" this type of messages if implementing the processing of it in the API is too timecostly.

**Comment by ecederstrand** [comment]
We don't support [PostItem](https://msdn.microsoft.com/en-us/library/office/bb891851(v=exchg.150).aspx), and we apparently crash when we encounter one. We need to at least create a stub class so we can read these items.

I've never seen these items before. How do you create them in e.g. Outlook?

**Comment by ecederstrand** [comment]
https://msdn.microsoft.com/en-us/library/office/aa562989(v=exchg.150).aspx contains a list of all the item types we can encounter.

**Comment by marioschaefer** [comment]
I don't know to be honest.
My mailbox can be imported just fine.
This mailbox is from a colleague of mine, but he's non-technical so he cant tell me which item this is or how he created it.

Is there a quickfix how i can prevent this crash and just continue with the next item?

**Comment by marioschaefer** [comment]
okay, seems like i got it working with adding the required class in items.py:
``` python
class PostItem(Message):
    # Supported attrs: https://msdn.microsoft.com/en-us/library/office/bb891851(v=exchg.150).aspx
    # TODO: Untested and unfinished. Only the bare minimum supported to allow reading a folder that contains meeting
    # cancellations.
    ELEMENT_NAME = 'PostItem'
    FIELDS = Message.FIELDS + [
        TextField('message_id', field_uri='message:InternetMessageId', is_read_only=True, is_read_only_after_send=True),
    ]


ITEM_CLASSES = (CalendarItem, Contact, Message, Task, MeetingRequest, MeetingResponse, MeetingCancellation, PostItem)
```

**Comment by ecederstrand** [comment]
Yes, that's almost correct :-) It should inherit fields from the `Item` class instead, since `Message` has fields that `PostItem` does not support.

**Comment by marioschaefer** [comment]
Thank you!
