### ISSUE TITLE
calendar.find_Items() help

### ISSUE THREAD

**Issue by leefrankeFNC** [ecederstrand/exchangelib#153]
For this code:
`for calendar in account.folders[Calendar]:
    items= calendar.find_items(subject__startswith='Global')
    for item in items:
        print(item.start, item.end, item.subject, item.body, item.location)`

I'm getting this error:
find_items() got an unexpected keyword argument 'subject__startswith'

I've also tried just 'subject'.

I'm new to python so I might be missing an import. I can send emails without a problem so I know that I am making a connection to the server.

My import looks like this:
`from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q,  ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version

from exchangelib.folders import Calendar`

thanks!

**Comment by ecederstrand** [comment]
You should use the `calendar.filter()` method instead. `find_items()` is an internal method.
