### ISSUE TITLE
Expose request `proxy` kwd into the API to support both SOCKS & HTTP proxies

### ISSUE THREAD

**Issue by ankostis** [ecederstrand/exchangelib#156]
According to #123, http-proxy support is based on underlying `requests` module,
so it can be configured either with the `HTTP_PROXY/HTTPS_PROXY` vars or with the `proxies` kwd in all requests methods.

As of April 2016 requests/requests#2953 [got merged](https://stackoverflow.com/a/36954255/548792) in `requests-2.10.1` and now SOCKS proxies are also supported.  I believe that the proper way now to specify both proxies is to use [the `proxies={}` method](http://docs.python-requests.org/en/master/user/advanced/#socks), which supportes elaborate mappings, like that:

    proxies={
        'http': 'socks5://user:pass@host:port',
        'http://10.20.1.128': 'socks5h://user:pass@host:port'  # 'socks5h' for local dns-resolving.
    }
    requests.get('http://go.to', proxies=proxies)

With the current API of *exchangelib* this is impossible. 

1. Would it make sense to add a new kwd `proxies` immediately after the `verify` kwd?
2. Would it be better to support a generic `requests_kwds` dictionary instead?
   [edit:] For instance, [`cert` kwd](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) might also bee used that way.

**Comment by ankostis** [comment]
Could I provide a PR for THIS release for option 2 above?

**Comment by ecederstrand** [comment]
Thanks for the report!

I'm happy to accept better proxy support. Can you explore whether adding this via a custom `HTTPAdapter` class is possible? We use it here: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/protocol.py#L119 and the few other places we use `requests` methods directly could be changed to use an `HTTPAdapter` class.

You could then plugin in your custom adapter class and have it used instead. I'm thinking something along the lines of:

```python
>>> from exchangelib.protocol import Protocol
>>> from requests.adapters import HTTPAdapter
>>> Protocol.HTTP_ADAPTER_CLASS
<class 'requests.adapters.HTTPAdapter'>
>>> class MyAdapter(HTTPAdapter):
...     pass  # Make the necessary customization here
...
>>> Protocol.HTTP_ADAPTER_CLASS = MyAdapter
>>> # Start using exchangelib here
```

I'm sort of hoping custom TLS versions (see #155) and disabling SSL verification can be folded into a plugin model like this.

**Comment by ankostis** [comment]
`HTTPAdapter` seems like the proper approach, but my limited knowledge of `requests` does not allow me to say eanything more.
Thanks.

**Comment by ecederstrand** [comment]
This should be possible now. You can supply your own HTTPAdapter class that we'll use everywhere:

```python
from exchangelib.protocol import BaseProtocol
BaseProcotol.HTTP_ADAPTER_CLS = MyAdapterClass
```

To add proxy support, have a look at the `get_connection()` class here: http://docs.python-requests.org/en/master/_modules/requests/adapters/

**Comment by Ads5740** [comment]
Can anyone put up an example of how to set a proxy adapter up please?

**Comment by ecederstrand** [comment]
Something like this should get you going:

```python
class MyProxyAdapter(BaseAdapter):
    def send(self, *args, **kwargs):
        kwargs['proxies'] = {
          'http': 'http://10.10.1.10:3128',
          'https': 'http://10.10.1.10:1080',
        }
        return super().send(*args, **kwargs)

```

See also the requests docs on proxies: http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by Ads5740** [comment]
Thanks,
I placed the code above with diff proxies of course in the protocol.py:
```python
class MyProxyAdapter(requests.adapters.HTTPAdapter):
    def send(self, *args, **kwargs):
        kwargs['proxies'] = {
          'http': 'http://10.10.1.10:3128',
          'https': 'http://10.10.1.10:1080',
        }
        return super().send(*args, **kwargs)
```
but get:

```  
File "C:\Python27\lib\site-packages\exchangelib\account.py", line 83, in __init__
    self.root = Root.get_distinguished(account=self)
  File "C:\Python27\lib\site-packages\exchangelib\folders.py", line 537, in get_
distinguished
    folders = list(cls.get_folders(account=account, ids=[cls(account=account, na
me=cls.DISTINGUISHED_FOLDER_ID)]))
  File "C:\Python27\lib\site-packages\exchangelib\folders.py", line 528, in get_
folders
    shape=IdOnly
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 876, in cal
l
    shape=shape,
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 76, in _get
_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 140, in _ge
t_response_xml
    allow_redirects=False)
  File "C:\Python27\lib\site-packages\exchangelib\util.py", line 444, in post_ra
telimited
    r = session.post(url=url, headers=headers, data=data, allow_redirects=False,
 timeout=protocol.TIMEOUT)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\exchangelib\protocol.py", line 296, in sen
d
    return super().send(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

I must be missing something obvious.

If I set my environment variables, it works without any proxy issues but would rather it more dynamic and build the authentication when I supply the mailbox credentials, my code calling exchangelib has:

```python
# Build credentials
parser = argparse.ArgumentParser(description=description)
parser.add_argument("-u", "-U", action="store", type=str, dest="id", help="User ID")
parser.add_argument("-p", "-P", action="store", type=str, dest="password", help="Password")
parser.add_argument("-d", "-D", action="store", type=str, dest="domain", help="Domain")
parser.add_argument("-e", "-E", action="store", type=str, dest="email", help="Email")
args = parser.parse_args()   
id = args.id
domain = args.domain.upper()
password = args.password    
username = domain+'\\'+id
email = args.email.lower()

from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter, MyProxyAdapter
from requests.adapters import HTTPAdapter

BaseProtocol.HTTP_ADAPTER_CLS = MyProxyAdapter

# Connect to exchange mailbox
    
credentials = Credentials(username=username, password=password)
version = Version(build=Build(8, 3, 83, 6))
config = Configuration(server='<server>', credentials=credentials, version=version, auth_type=NTLM)
account = Account(primary_smtp_address=email, config=config, autodiscover=False, access_type=DELEGATE)
```

So would like to pass the captured creds to the proxy

**Comment by ecederstrand** [comment]
Oh, you're on Python2.7. I updated my example code now.

**Comment by Ads5740** [comment]
<Sigh> yes 2.7 long story....
Good news is it works perfectly, thanks again.

Using both and it works:
```Python
# Build credentials
parser = argparse.ArgumentParser(description=description)
parser.add_argument("-u", "-U", action="store", type=str, dest="id", help="User ID")
parser.add_argument("-p", "-P", action="store", type=str, dest="password", help="Password")
parser.add_argument("-d", "-D", action="store", type=str, dest="domain", help="Domain")
parser.add_argument("-e", "-E", action="store", type=str, dest="email", help="Email")
args = parser.parse_args()   
id = args.id
domain = args.domain.upper()
password = args.password    
username = domain+'\\'+id
email = args.email.lower()

from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
from requests.adapters import HTTPAdapter

class MyProxyAdapter(requests.adapters.HTTPAdapter):
    def send(self, *args, **kwargs):
        http_proxy = 'http://'+id+':'+password+'@PROXY:PORT'
        https_proxy = 'https://'+id+':'+password+'@PROXY:PORT'
        kwargs['proxies'] = {
          'http': http_proxy,
          'https': https_proxy,
        }
        return super(MyProxyAdapter, self).send(*args, **kwargs)

BaseProtocol.HTTP_ADAPTER_CLS = MyProxyAdapter
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

# Connect to exchange mailbox
    
credentials = Credentials(username=username, password=password)
version = Version(build=Build(8, 3, 83, 6))
config = Configuration(server='mail.service.group', credentials=credentials, version=version, auth_type=NTLM)
account = Account(primary_smtp_address=email, config=config, autodiscover=False, access_type=DELEGATE)
```

Looks ugly for now, tidy up later, but it works

**Comment by Kenith** [comment]
Hello @Ads5740,

We have used the proxy, but error with: nodename nor servname provided, or not known.
Would you please take time to give me a hand?

```
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
from requests.adapters import HTTPAdapter
import requests
from exchangelib import DELEGATE, Account, Credentials, NTLM
from exchangelib.configuration import Configuration

class MyProxyAdapter(requests.adapters.HTTPAdapter):
    def send(self, *args, **kwargs):
        http_proxy = 'http://127.0.0.1:3128'
        kwargs['proxies'] = {
            'http': http_proxy,
            'https': http_proxy,
        }
        return super(MyProxyAdapter, self).send(*args, **kwargs)

BaseProtocol.HTTP_ADAPTER_CLS = MyProxyAdapter
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

config = Configuration(server='https://mailsg.***.***.com/EWS/Exchange.asmx',
                       credentials=Credentials(username='GLOBAL\***', password='***'),
                       auth_type=NTLM)

account = Account(primary_smtp_address='***.***@***.com',
                  config=config,
                  access_type=DELEGATE)
```

Error:
Traceback (most recent call last):
  File "/Users/ken/PycharmProjects/Debug/Debug.py", line 182, in <module>
    auth_type=NTLM)
  File "/Library/Python/2.7/site-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/Library/Python/2.7/site-packages/exchangelib/protocol.py", line 172, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/exchangelib/protocol.py", line 222, in __init__
    self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
  File "/Library/Python/2.7/site-packages/exchangelib/transport.py", line 115, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1079d1910>: Failed to establish a new connection: **[Errno 8] nodename nor servname provided, or not known',**))

Thank you,
Ken

**Comment by ecederstrand** [comment]
In your `Configuration`, the `server` argument should be a hostname, not a URL. If you want to provide the exact URL, use the `service_endpoint` argument.

**Comment by Kenith** [comment]
@ecederstrand Great, really appreciate for your hot & quick help.
Now the issue fixed!!
Nice day to you.

Thank you Again.

**Comment by RastogiDeeksha** [comment]
Hi @ecederstrand,
If we set the proxy variables in the environment(windows server) only then we are able to send the email using Adapter Class.
Is there any way to send Emails, without setting the environment variables?

Thanks,
Deeksha

**Comment by ecederstrand** [comment]
Which environment variables are you setting? Please post an example of your custom `HTTPAdapter` class and how you're configuring it in exchangelib.

**Comment by RastogiDeeksha** [comment]
We are setting HTTPS_PROXY and HTTP_PROXY in environment variables(Windows env).

SampleCode -

import requests
from exchangelib import Credentials, Account, DELEGATE, Configuration, Mailbox, Message, FileAttachment, HTMLBody, ExtendedProperty
from exchangelib.protocol import BaseProtocol
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication

class ProxyAdapter(requests.adapters.HTTPAdapter):
    def send(self, *args, **kwargs):
        kwargs["proxies"] = ProxyAdapter.proxies
        return super(ProxyAdapter, self).send(*args, **kwargs)

proxy = {"http":"http://user:pass@proxy_doman:port", "https":"http://username:password@proxy_domain:port"}
ProxyAdapter.proxies = proxy
BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter
credentials = Credentials(username=username, password=password)
primary_smtp_address = username
server = "Outlook.Office365.com"
config = Configuration(server=server, credentials=credentials)
account = Account(primary_smtp_address=primary_smtp_address,credentials=credentials,autodiscover=False,config=config, access_type=DELEGATE)
send_email = Message(account=account,subject="test subject", body="test body", to_recipients=email_to)
send_email.send_and_save()

**Comment by ecederstrand** [comment]
That seems right. Are you sure that your code is indeed hitting the `ProxyAdapter.send()` method? You could insert a breakpoint to be sure.

**Comment by RastogiDeeksha** [comment]
Hi @ecederstrand ,
Yes that class method is hitting, we just need a confirmation like to declare environment variable(http_proxy and https_proxy) is mandatory if we are using exchangelib library in the windows environment?

**Comment by ecederstrand** [comment]
I would assume that the environment variables are redundant, but since we're just relying on `requests` for for proxy support, this is really a question for requests, not exchangelib.
