### ISSUE TITLE
Looks like EWSDataTime is not working?

### ISSUE THREAD

**Issue by Jaycolas** [ecederstrand/exchangelib#157]
TodaysEmail = MyOwnFolder.all(start__gt = EWSDateTime(2017,6,24))

Looks like EWSDataTime is not working?

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/restriction.py", line 195, in clean
    raise ValueError('Value "%s" for filter on field path "%s" is unsupported' % (self.value, self.field_path))
ValueError: Value "2017-06-24 00:00:00" for filter on field path "start" is unsupported

**Comment by ecederstrand** [comment]
You need to make your datetime value timezone-aware: `tz = EWSTimeZone.localzone(); tz.localize(EWSDateTime(2017, 6, 24))`.

Please leave the issue open. I'd like to add better error reporting in this case.

**Comment by ecederstrand** [comment]
Fixed in 014b78b3ea8c5091009d434864a9f03c80b58768
