### ISSUE TITLE
Add Message.From maybe?

### ISSUE THREAD

**Issue by trivita** [ecederstrand/exchangelib#159]
```python
MailboxListField('send_from', field_uri='message:From', is_read_only_after_send=True, is_searchable=False),
```

added this to items.py myself.
helped me get senders information

**Comment by ecederstrand** [comment]
The `message:From` field is already available as `Item.author` :-)

It can't be named `from`, unfortunately, because `from` is also a Python keyword.

**Comment by trivita** [comment]
thanks, i'm such an idiot,

**Comment by ecederstrand** [comment]
Can you give an example? What I meant was that the EWS FieldURI `message:From` is wired up as the `author` attribute on our `Message` class. See https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/items.py#L476
