### ISSUE TITLE
How to correlate with MFC Mapi for PR_ENTRYID([Tag:] 0xfff, 0n4095)

### ISSUE THREAD

**Issue by SidharthPati** [ecederstrand/exchangelib#161]
For a specific mail, I am getting the value of PR_ENTRYID from ExchangeLib (message_id) as : AAAAAJXv2ELfyfpHrdn/Vdi/WDYHABw3W1WVDPZHvff3PMvZMf0AAAAWtcAAABw3W1WVDPZHvff3PMvZMf0AABZPjGQAAA==

But for the same mail, I am getting the value of PR_ENTRYID from MFCMapi as:
0000000095EFD842DFC9FA47ADD9FF55D8BF583607001C375B55950CF647BDF7F73CCBD931FD00000016B5C000001C375B55950CF647BDF7F73CCBD931FD0000164F8C640000

How do I correlate these values?

**Comment by ecederstrand** [comment]
The first value is just base64-encoded:

```python
>>> import base64
>>> base64.b64decode('AAAAAJXv2ELfyfpHrdn/Vdi/WDYHABw3W1WVDPZHvff3PMvZMf0AAAAWtcAAABw3W1WVDPZHvff3PMvZMf0AABZPjGQAAA==')
b'\x00\x00\x00\x00\x95\xef\xd8B\xdf\xc9\xfaG\xad\xd9\xffU\xd8\xbfX6\x07\x00\x1c7[U\x95\x0c\xf6G\xbd\xf7\xf7<\xcb\xd91\xfd\x00\x00\x00\x16\xb5\xc0\x00\x00\x1c7[U\x95\x0c\xf6G\xbd\xf7\xf7<\xcb\xd91\xfd\x00\x00\x16O\x8cd\x00\x00'
```

If you're using extended properties to get the value in exchangelib, we should be decoding the value already (see https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/extended_properties.py#L129) but either you didn't set `property_type=''Binary'`, or there's a bug somewhere.

**Comment by ecederstrand** [comment]
By the way, if you get this working, please post your extended property definition here. I'd like to collect useful extended properties in a contrib or examples section in the repo.

**Comment by SidharthPati** [comment]
Hi @ecederstrand , I tried decoding the value but it keeps returning unicode data.
```
import base64
print base64.b64decode('AAAAAJXv2ELfyfpHrdn/Vdi/WDYHABw3W1WVDPZHvff3PMvZMf0AAAAWtcAAABw3W1WVDPZHvff3PMvZMf0AABZPjGQAAA==')
```

```
OUTPUT:
  ���B���G���UؿX6 7[U��G���<��1�   ��  7[U��G���<��1�  O�d
```

I also tried to decode the value using online Base64 decoder which too returned unicode data:
![image](https://user-images.githubusercontent.com/22004791/27723726-0ff8852c-5d8c-11e7-85fb-ecef5ca49082.png)

Am I missing something here?

**Comment by ecederstrand** [comment]
Apparently, Outlook does some cool formatting of the binary value. You can do the same in Python (convert to bin to hex and then format without the leading `0x`, and finally upper-case):

```python
>>> import base64
>>> decoded_val = base64.b64decode('AAAAAJXv2ELfyfpHrdn/Vdi/WDYHABw3W1WVDPZHvff3PMvZMf0AAAAWtcAAABw3W1WVDPZHvff3PMvZMf0AABZPjGQAAA==')
>>> ''.join('{:02x}'.format(n) for n in decoded_val).upper()
'0000000095EFD842DFC9FA47ADD9FF55D8BF583607001C375B55950CF647BDF7F73CCBD931FD00000016B5C000001C375B55950CF647BDF7F73CCBD931FD0000164F8C640000'
```

**Comment by ecederstrand** [comment]
This should be solved in #146

**Comment by SidharthPati** [comment]
Sorry @ecederstrand for the delayed response, thanks a lot for your help. As mentioned in #146 , even I got it working by making a small change in the above snippet:

```
import base64
decoded_val = base64.b64decode('AAAAAJXv2ELfyfpHrdn/Vdi/WDYHABw3W1WVDPZHvff3PMvZMf0AAAAWtcAAABw3W1WVDPZHvff3PMvZMf0AABZPjGQAAA==')
print (''.join([ "%02X" % ord(x) for x in decoded_val]).strip())
```

```
OUTPUT:
0000000095EFD842DFC9FA47ADD9FF55D8BF583607001C375B55950CF647BDF7F73CCBD931FD00000016B5C000001C375B55950CF647BDF7F73CCBD931FD0000164F8C640000
```

**Comment by SidharthPati** [comment]
@ecederstrand , as you had asked me to post an extended property definition, I used the below definition to fetch the Message Size of a mail:

```
class MessageSize(extended_properties.ExtendedProperty):
    property_tag = 0x0E08  
    property_type = 'Integer'

Message.register('MessageSize', MessageSize)

Message.deregister('MessageSize')
```
This returns the Message Size in bytes.

**Comment by ecederstrand** [comment]
Thanks, @SidharthPati !
