### ISSUE TITLE
Get list of all shared contacts

### ISSUE THREAD

**Issue by dgikiller** [ecederstrand/exchangelib#162]
Hi,

I am working with an Exchange Server and I need to create a script that will retrieve the list of a specific subset of contacts.

The problem is the fact that I am not able to get the list of all contacts from my smtp address.

There is a way to know what is the smtp address associated with the list of all shared contacts or a way to retrieve the list using my smtp server address? 
Thank you very much in advance for your reply. 

Kindest Regards,
Francesco.

**Comment by ecederstrand** [comment]
Hi @dgikiller 

exchangelib currently only supports access to the private contacts folder, not shared contacts. This is tracked in #93 but I'm not actively working on it.

**Comment by dgikiller** [comment]
Hi @ecederstrand,

First of all thank you for your reply.
So there is not even dedicated SMTP address that tracks all the contacts in the Exchange server, am I right?

**Comment by ecederstrand** [comment]
Yes, I think that's correct. AFAIK, the `Account.contacts` folder only contains the contacts that were created by the user. To access the global address book, which is what most business users refer to as the address book, we'll need to solve #93.

**Comment by ahusking** [comment]
Did anyone test this/get this working?

I've tried, but get an error saying Q() is undefined.
@ecederstrand I'm happy to try and assist with some testing if you like.

Cheers,

**Comment by ahusking** [comment]
account = Account(‘user@example.com’, credentials=credentials, autodiscover=True)

folder = account.root / 'AllContacts'
for persona in folder.find_people(
            Q(),
                additional_fields={FieldPath(field=f) for f in Persona.supported_fields() if not f.is_complex},
                ):
        print(persona)

That gives me "No Subfolder named AllContacts"



If I change allcontacts to allitems, I get NameError: name 'Q' is not defined

Essentially all I'm trying to do is enumerate the GAL

**Comment by ecederstrand** [comment]
`No Subfolder named AllContacts` is because there's no subfolder under the root folder with that name. You can see the full folder structure with `print(account.root.tree())`.

`NameError: name 'Q' is not defined` is because you're missing an import statement for Q (`from exchangelib import Q`). But just use `folder.people()` instead, as described in https://github.com/ecederstrand/exchangelib#searching-contacts

**Comment by ahusking** [comment]
I had a look at the account.root.tree(), and didn't see anything that was obvious as to where the GAL would be stored.

When I search the only contacts folder using your suggestion in the link, I get 

`The request failed schema validation. Could not find schema information for the element 'http://schemas.microsoft.com/exchange/services/2006/messages:FindPeople`

**Comment by ecederstrand** [comment]
In my test account, the GAL contact folder is located at:
```
root
├── Top of Information Store
│   ├── Contacts
│   │   ├── GAL Contacts
```

**Comment by ahusking** [comment]
What version of exchange are you testing on?

**Comment by ecederstrand** [comment]
This is `Build=15.0.1395.0, API=Exchange2013_SP1, Fullname=Microsoft Exchange Server 2013 SP1` but  the folder structure of your mailbox will also depend on server-side configuration.

**Comment by antonylu** [comment]
I found the GAL from the root tree.
```
folder = a.root / '資訊存放區頂端' / '連絡人' / 'GAL Contacts'
for p in folder.people():
    print(p)
for p in folder.people().only('display_name').filter(display_name='antony').order_by('display_name'):
    print(p)
```
str(folder) is as below:

```
GALContacts(Root(<exchangelib.account.Account object at 0x0000015A9E081CF8>, '[self]', 'root', 7, 0, 27, None, 'AAMkAGRjAAAAATk4LWE5N2YtNDUzOC1hN2FjLWJhYWNkY2U1ZTEzYgAuAAAAAAAAAAAAgBTAS6nemKSAAAAAAQClR/R9R/gLR63Czh/XXXXAAAAAAEBAAA=', 'AQAAABYAAAClR/R9R/gLR63Czh/XY9HXAAHfBq9/'), 'GAL Contacts', 0, None, 0, 'IPF.Contact.GalContacts', 'AQMkAGRAAAAAYTk4LWE5N2YtNDAAAAAhN2FjLWJhYQBjZGNlNWUxM2IALgAAAyvork2AFMBLqd6YpINZq5ABAKVH9H1H+AtHrcLAAAAA0dcAAAIBIQAAAA==', 'AwAAABQAAAAuTrqAAAAARrnsR5/AAAAAAAAEMQ==')
```
However, there is no output from above code.
len(folder.people()) is 0
Any suggestion?

**Comment by thefedoration** [comment]
I'm getting that same. looks like the feature to display people was added [here](https://github.com/ecederstrand/exchangelib/commit/02ad4df5e0ecc3be9e703da190610e362c7d21f6), and should have also included the ability to filter.

What I'm seeing is that `folder.people()` properly finds the contacts in the folder, but the QuerySet is not properly searchable.
<img width="921" alt="Screen Shot 2021-05-17 at 9 39 55 AM" src="https://user-images.githubusercontent.com/6766645/118525915-8d126300-b6f4-11eb-8e6e-616859c32eaf.png">

**Comment by thefedoration** [comment]
Okay I couldn't get it to work with `folder.people()`, seems something is off with the filter functionality for this QuerySet.

However, I was able to achieve what I needed by using the `EmailAddress` indexed property. This will return a list of `Contact` objects.
```
from exchangelib.indexed_properties import EmailAddress
list(folder.filter(email_addresses__contains=EmailAddress(email='someemail')))
```

If looks like you can do something similar (ditching the `.people()`) to filter by `display_name` as well
```
list(folder.filter(display_name__contains='somename').values_list('email_addresses', 'display_name'))
```

**Comment by ecederstrand** [comment]
It's possible that EWS simply doesn't support filtering in combination with the `FindPeople` service.

Can you enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) and see if we are at least generating a sane request?

**Comment by thefedoration** [comment]
yeah sure thing. you're looking for `[exchangelib.util.xml] DEBUG Request XML` right?

Query 1
`contacts = folder.people().filter(display_name__icontains=phrase)`

Request 1
`[exchangelib.util.xml] DEBUG Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016"/><t:TimeZoneContext><t:TimeZoneDefinition Id="Eastern Standard Time"/></t:TimeZoneContext></s:Header><s:Body><m:FindPeople Traversal="Shallow"><m:PersonaShape><t:BaseShape>IdOnly</t:BaseShape></m:PersonaShape><m:IndexedPageItemView MaxEntriesReturned="100" Offset="0" BasePoint="Beginning"/><m:Restriction><t:Contains ContainmentMode="Substring" ContainmentComparison="IgnoreCase"><t:FieldURI FieldURI="contacts:DisplayName"/><t:Constant Value="fed"/></t:Contains></m:Restriction><m:ParentFolderId><t:FolderId Id="AAMkADQxNmI2YzFkLTc3Y2ItNGFmYi04MTJhLWJkNWMzZTJkZmY5NQAuAAAAAACFH2M6nFsFQKbSElAZAQCKAQAy4OVJu6q4SayNCQNasWwxAAAAAC6qAAA=" ChangeKey="BwAAABYAAAAy4OVJu6q4SayNCQNasWwxAAAAAAL1"/></m:ParentFolderId></m:FindPeople></s:Body></s:Envelope>'`

Query 2
```
query = Q(
    Q(email_addresses__icontains=EmailAddress(email=phrase)) | 
    Q(display_name__icontains=phrase)
)
contacts = list(folder.filter(query))
```

Request 2
`[exchangelib.util.xml] DEBUG Request XML: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016"/><t:TimeZoneContext><t:TimeZoneDefinition Id="Eastern Standard Time"/></t:TimeZoneContext></s:Header><s:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>IdOnly</t:BaseShape></m:ItemShape><m:IndexedPageItemView MaxEntriesReturned="100" Offset="0" BasePoint="Beginning"/><m:Restriction><t:Or><t:Contains ContainmentMode="Substring" ContainmentComparison="IgnoreCase"><t:FieldURI FieldURI="contacts:DisplayName"/><t:Constant Value="fed"/></t:Contains><t:Contains ContainmentMode="Substring" ContainmentComparison="IgnoreCase"><t:IndexedFieldURI FieldURI="contacts:EmailAddress" FieldIndex="EmailAddress1"/><t:Constant Value="fed"/></t:Contains></t:Or></m:Restriction><m:ParentFolderIds><t:FolderId Id="AAMkADQxNmI2YzFkLTc3Y2ItNGFmYi04MTJhLWJkNWMzZTJkZmY5NQAuAAAAAACFH2M6nFsFQKbSElAZAQCKAQAy4OVJu6q4SayNCQNasWwxAAAAAC6qAAA=" ChangeKey="BwAAABYAAAAy4OVJu6q4SayNCQNasWwxAAAAAAL1"/></m:ParentFolderIds></m:FindItem></s:Body></s:Envelope>'`

**Comment by ecederstrand** [comment]
I took the liberty of reformatting your post. I don't see anything wrong with the `FindPeople` request. It seems that combining `FindPeople` with a filter simply does not work, or does not work on your specific server.

**Comment by thefedoration** [comment]
Got it - for what it's worth I'm connecting to the `outlook.office365.com` exchange server. I'll be running some tests in other versions of the server over the coming weeks, will comment here if I find something else on other flavors.

For now, using `Query 2` above is getting me exactly what I need.

**Comment by TanjilAmin** [comment]
> Okay I couldn't get it to work with `folder.people()`, seems something is off with the filter functionality for this QuerySet.
> 
> However, I was able to achieve what I needed by using the `EmailAddress` indexed property. This will return a list of `Contact` objects.
> 
> ```
> from exchangelib.indexed_properties import EmailAddress
> list(folder.filter(email_addresses__contains=EmailAddress(email='someemail')))
> ```
> 
> If looks like you can do something similar (ditching the `.people()`) to filter by `display_name` as well
> 
> ```
> list(folder.filter(display_name__contains='somename').values_list('email_addresses', 'display_name'))
> ```

This approach has worked me. However how can I see the list of fields available for .values_list() ? I would like to extract the contact details specific individuals.

**Comment by ecederstrand** [comment]
Assuming you're only interested in `Contact` items, the supported fields on that item type are available via `Contact.FIELDS`.
