### ISSUE TITLE
EffectiveRights - adding this field to folders

### ISSUE THREAD

**Issue by synic** [ecederstrand/exchangelib#163]
I'd like to be able to get the EffectiveRights field of a folder.

Looking at the code, I couldn't see a way to get this already built in.  I want to add it, but since I don't really know the library or how you like to do things, I want to run it past you first.

This is what I have so far:

```python
class EffectiveRightsField(FieldURIField):
    RIGHTS = ('CreateAssociated', 'CreateContents', 'CreateHierarchy',
              'Delete', 'Modify', 'Read', 'ViewPrivateItems')

    def from_xml(self, elem, account):
        field_elem = elem.find(self.response_tag())
        effective_rights = []

        for right in self.RIGHTS:
            value = get_xml_attr(
                field_elem, '{%s}%s' % (TNS, right))
            if value == 'true':
                effective_rights.append(right)

        return effective_rights
```

In this way you could do something like `'Modify' in account.calendar.effective_rights`.  However, this is NOT how it works in the C# version, instead, it's a bitflag.  

Which would you prefer?   Or another way all together?  Or is it already built in somehow and I just missed it?

Thanks!

**Comment by ecederstrand** [comment]
For reference, here's the documentation for that field: https://msdn.microsoft.com/en-us/library/office/bb891883(v=exchg.150).aspx

We already have an `EnumField` for values that are stored in EWS as integers, see e.g. https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/recurrence.py#L108 `EnumListField` is the same, just for lists of integers.

The best solution is probably to subclass `EnumListField` to make it read and write the `true`/`false` formatted XML but present it to the user as a list of the `RIGHTS` elements that were `true`.

**Comment by ecederstrand** [comment]
Another possibility is to create an `EffectiveRights` object that subclasses `EWSElement` and defines the 7 fields in `FIELDS`, and a then create a custom field that subclasses `EWSElementField` and in the `clean()` method lets the user either set an `EffectiveRights` instance or a list of simple strings.
