### ISSUE TITLE
Is it possible to obtain a folder by it's ID?

### ISSUE THREAD

**Issue by synic** [ecederstrand/exchangelib#164]
Title says it all, can I get an instance of a folder given it's `folder_id` ?

**Comment by ecederstrand** [comment]
To answer the immediate question, then yes, this code doesn't crash:

```python
from exchangelib.folders import Folder
Folder(folder_id='foo')
```

But to do anything useful with it, you would need to add an account and a changekey:

```python
Folder(acount=a, folder_id='foo', changekey='bar')
```
