### ISSUE TITLE
ewsdatetime raises ValueError for "GMT+0"

### ISSUE THREAD

**Issue by c2d** [ecederstrand/exchangelib#165]
Account creation fails with

```
exchangelib/ewsdatetime.py", line 158, in from_pytz raise ValueError('No Windows timezone name found for timezone "%s"' % tz.zone)
ValueError: No Windows timezone name found for timezone "GMT+0"
```
Is there a way around this?

**Comment by ecederstrand** [comment]
The direct reason for this is that there is no translation between `GMT+0` and the corresponding Windows timezone name in https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/winzone.py

When we create an `Account` object, we attempt to find the local timezone if the `default_timezone` argument is unset. This is done via `EWSTimeZone.localzone()` which asks the OS. In your case, your OS thinks it's in the timezone `GMT+0`.

A solution would be to simply set the timezone explicitly:
```python
tz = EWSTimeZone.timezone('GMT')  # We do support this timezone name
a = Account(..., default_timezone=tz)
```

**Comment by c2d** [comment]
Thank you very much. This works fine. :)
