### ISSUE TITLE
iCalUid - how to obtain it?

### ISSUE THREAD

**Issue by synic** [ecederstrand/exchangelib#166]
Sorry about all of these.  This one seems a bit more complicated.

How does one obtain an iCalUid (https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.appointment.icaluid(v=exchg.80).aspx) for a `CalendarItem`?

**Comment by ecederstrand** [comment]
I have no idea. Supposedly you can get the value by defining an extended property, but you'll have to go digging in the technical documents from Microsoft for the magic incantations. https://msdn.microsoft.com/en-us/library/cc433490(v=exchg.80).aspx and https://msdn.microsoft.com/en-us/library/cc425490(v=exchg.80).aspx could be places to start.

**Comment by ecederstrand** [comment]
Actually, https://stackoverflow.com/questions/30904968/how-to-search-for-an-exchange-appointment-for-an-icaluid-using-java-ews-api suggests this property is the same as the one mentioned in https://github.com/ecederstrand/exchangelib/issues/78#issuecomment-278823350

**Comment by synic** [comment]
Thank you

**Comment by synic** [comment]
Hrmm, apparently GlobalObjectId is not the same as iCalUid.  It is in the case of non-recurring meetings, but each instance of a recurring meeting will have the same iCalUid, but different GlobalObjectIds.

Going to re-open in case someone knows.  In the document linked in issue #78, there is a CalendarUid:

```python
2.400 PidNameCalendarUid
Canonical name: PidNameCalendarUid
Description: Specifies the unique identifier of an appointment or meeting.
Property set: PS_PUBLIC_STRINGS {00020329-0000-0000-C000-000000000046}
Property name: urn:schemas:calendar:uid
Data type: PtypString, 0x001F
Area: Common
Defining reference: [MS-XWDCAL] section 2.2.2.33
Alternate names: urn:schemas:calendar:uid
```

Though this does not work:

```python
class iCalUid(ExtendedProperty):
    property_id = '00020329-0000-0000-C000-000000000046'
    property_name = 'urn:schemas:calendar:uid'
    property_type = 'String'
```

**Comment by synic** [comment]
I will also note that `iCalUid` is supposed to be a first class property, but I'm not totally sure how they relate to extended properties.

**Comment by ecederstrand** [comment]
`property_name` should probably be `PidNameCalendarUid ` instead of `urn:schemas:calendar:uid` in the above.

**Comment by synic** [comment]
Good news!  I found it, had to use a proxy and watch packets from the C# code.

```
        TextField('ical_uid', field_uri='calendar:UID', is_required=False, is_searchable=False),
```

I'll make a PR for both this field and `IsCancelled` if that's ok?

**Comment by synic** [comment]
Actually, maybe it would be better if we could register first-class properties too?  There are lots of fields that maybe not everyone needs/wants, but it would be nice if those that do can easily obtain them, just like you can do with the extended properties.

**Comment by ecederstrand** [comment]
Thanks for your hard work!

Until now, I've pulled in the first class properties as needed and after understanding how they work and what they actually do. Some fields seem to be overlapping in functionality, and I'd prefer one way of doing things.

But exchangelib has evolved since, and there's support for restricting the returned fields, marking fields as only supported in some Exchange versions etc. So may now is the time to pull in the kitchen sink?

The test suite is pretty good at weeding out errors in the field definitions. So that would be a first test when adding new fields.

I've added `uid` and `iscancelled` fields locally and will be committing as soon as the test suite completes here.

**Comment by synic** [comment]
I brought it up because I have a whole slew of fields that we use currently (about 38 first-class fields) for analytics on calendar events (is_online, is_deleted_item, is_reminder_set, meeting_workspace_url, original_start, original_end, online_meeting_url, appointment_type, conference_type, edit_url, read_url to name a few).

I started with the ones we absolutely require to get the system to function, but we'll eventually need all the fields.  I'm fairly sure we don't even use all the fields that are available.  At this point, I think we may end up having to fork exchangelib to make it work for us.

**Comment by ecederstrand** [comment]
I'm not against adding all the CalendarItem fields mentioned in https://msdn.microsoft.com/en-us/library/office/aa564765(v=exchg.150).aspx so if you can come up with a patch that passes the test suite, please just send a PR.

You're welcome to fork exchangelib, of course, but I'm not sure we're even in disagreement at this point :-)

**Comment by synic** [comment]
Nope, haha, we aren't.  I will make a PR when I get a moment.

Thanks again!

**Comment by jfoclpf** [comment]
> Nope, haha, we aren't. I will make a PR when I get a moment.
> 
> Thanks again!

Can you tell me how did you get `ICalUid`?

**Comment by ecederstrand** [comment]
It should be available as the `CalendarItem.uid` field.
