### ISSUE TITLE
Query: Are the messages in a folder retrieved in a sequential order based on time?

### ISSUE THREAD

**Issue by SidharthPati** [ecederstrand/exchangelib#168]
Hi @ecederstrand , I have a couple of questions.

1) Do we fetch the messages in a folder based on received time? Is it always sequential (as we see in outlook - latest mail first approach)?
2) I see that the folders are retrieved randomly. Is there a way to retrieve these folders in a sequential order (say alphabetically)?

**Comment by ecederstrand** [comment]
1: Message order in a `.filter()` or `.all()` call is undefined unless you add an `.order_by('some_field')` to the filter. The default Outlook order (first 110 emails in reverse received order) would be something like 'account.inbox.all().order_by('-datetime_received')[:100])'

2: The FindFolder does not allow specifying any sorting (see https://msdn.microsoft.com/en-us/library/office/aa564962(v=exchg.150).aspx) but you could easily do the sorting client-side based on whatever folder attribute you want.

**Comment by SidharthPati** [comment]
Thanks @ecederstrand
