### ISSUE TITLE
support extended properties on folders

### ISSUE THREAD

**Issue by LarsNordin** [ecederstrand/exchangelib#171]
Currently no way to register extended properties for message folder objects. 

The goal is to be able to get the storage usage of each folder in Exchange.
See https://stackoverflow.com/questions/44568723/using-python-exchangelib-how-to-get-total-size-of-messages-in-mail-folder

Folder size seems to be exposed, see this forum thread:
https://social.technet.microsoft.com/Forums/office/en-US/31f9a157-4d19-44bf-ad58-62577915b624/mailbox-size-and-folder-sizes?forum=exchangesvrdevelopment

**Comment by ecederstrand** [comment]
This should mimic the way we register extended property fields on the `Item` model.

**Comment by ecederstrand** [comment]
Will be working on this as time permits. We should be able to do the following:

```python
class FolderSize(ExtendedProperty):
    property_tag = 0x0e08
    property_type='Integer'

Folder.register('size', FolderSize)
account = Account(...)
print(account.inbox.size)
```

We can reuse most of `Item.register()`. We just need to know where in the XML to insert the extended property.

**Comment by uwe-schwarz** [comment]
If anyone comes across this here, if you're folders are too large and you get negative numbers for size. Just use 'Long' instead of 'Integer'.
