### ISSUE TITLE
Message with Multiple to_addresses

### ISSUE THREAD

**Issue by samh194** [ecederstrand/exchangelib#173]
Hi @ecederstrand 

I am trying to generate an email with multiple addresses as below:

`m = Message(
                account=account,
                subject=Subject,
                body=default_body,
                to_recipients=[Mailbox(email_address=Recipients)]
            )`

Recipients is a list of recipients e.g. ['test@test.com', 'email@email.com']

Is there any way to generate an email message to multiple recipients this way?

**Comment by ecederstrand** [comment]
Just assign the list of recipients to the `to_recipients` attribute:

```python
m = Message( account=account, subject=Subject, body=default_body, to_recipients=['test@test.com', 'email@email.com'])
```

`to_recipients` will take either a list of `Mailbox` items or just plain email address strings.

**Comment by cyjaysun** [comment]
thanks.
m = Message(account=account, to_recipients=['test@test.com', 'email@email.com'], ...)
It's work.
