### ISSUE TITLE
Notification subscriptions in EWS

### ISSUE THREAD

**Issue by sebastiantoro** [ecederstrand/exchangelib#175]
Is it possible to subscribe to [EWS Notifications ](https://msdn.microsoft.com/en-us/library/office/dn458791(v=exchg.150).aspx) and receive and process those notifications using python's `exchangelib`? (what `php-ews` does for PHP)

**Comment by ecederstrand** [comment]
This is not implemented yet.

Closing as it's a duplicate of https://github.com/ecederstrand/exchangelib/issues/145

**Comment by python-requests-html** [comment]
> This is not implemented yet.
> 
> Closing as it's a duplicate of [#145](https://github.com/ecederstrand/exchangelib/issues/145)





https://kristoffboulevard5.github.io/checkjs493/
