### ISSUE TITLE
Getting contacts directly from GAL

### ISSUE THREAD

**Issue by akaduri75** [ecederstrand/exchangelib#176]
I’m using exchangelib and it works great for me. Very happy with it.
I’ll appreciate if one of the experts here can assist with clarifying the following issues:
1.	The exchangelib client works good (i.e. returns contacts list) only after I manually update my contacts from the GAL (using outlook).
Is it a must or can exchangelib client bring the contact from GAL directly without the need to update the contacts list first?
	For example, the following application (http://www.nirsoft.net/utils/outlook_address_book_view.html)  shows the GAL’s content even if my contacts list is empty.
2.	Something that I may not understand pretty well:
If I update my contacts list (using outlook), so as far as I understand they are copied locally. So why do I still need to provide credentials to connect to the exchange server?
Is it just for authentication, or maybe the contacts are not locally stored as I assume, but just copied from GAL and still reside on the exchange server?
3.	I need a unique ID for every contact. In the SW I’ve mentioned earlier, it shows “Entry ID”. On the other hand in exchnagelib’s client I found that I can get “item_id”.
Is “item_id” unique? Is this thing comes from exchange or exchangelib’s client generates it?

Thank you

**Comment by ecederstrand** [comment]
1. The GAL is not implemented yet. It's an open issue (#93)

2. Your GAL contacts are copied to a folder attached to your account on the Exchange server. exchangelib has no local cache of information (except some autodiscover info) and does not attempt to locate an Outlook installation on the local machine.

3. `item_id` is an Exchange-generated UUID and exchangelib just exposes it as the `item_id` attribute.

**Comment by akaduri75** [comment]
In regard of 1+2, is there a way in exchangelib to update the exchange server with GAL (rather than directly query the GAL), or its actually the same GAL support mentioned in answer #1?

**Comment by ecederstrand** [comment]
What I've seen described is that Outlook can scrape the entire GAL and put it in the contacts folder connected to your own account.

For exchangelib to do the same, we would also need access to the GAL. Which is #93 :-)
