### ISSUE TITLE
exchangelib.errors.ErrorRecurrenceHasNoOccurrence

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#177]
Hi,

I'm trying to get a range of events from one specific calendar using:
`account.calendar.get_folder_by_name('IG Plan').filter(start__range=(today,future)).order_by('start')`

There are events in that range in that calendar but all I get is:
```
Traceback (most recent call last):
  File "t-minus.py", line 51, in <module>
    if __name__ == '__main__': main(sys.argv)
  File "t-minus.py", line 41, in main
    for c in cal:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 161, in __iter__
    for val in result_formatter(self._query()):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/queryset.py", line 228, in _as_items
    for i in iterable:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/account.py", line 421, in fetch
    for i in GetItem(account=self).call(items=ids, additional_fields=only_fields):
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 452, in _pool_requests
    for elem in elems:
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 264, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 237, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 254, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorRecurrenceHasNoOccurrence: Recurrence has no occurrences in the specified range., There are no occurrences in the current recurrence.
```
None of the events are recurring. They are however events that go over several days.

Am I doing something wrong?

**Comment by ecederstrand** [comment]
Well, that's not very helpful behaviour by EWS - decide to select an item for the search result, and then refuse to return it.

I have no idea what is going on. Can you narrow down the problem by identifying the exact item? Maybe that will give you a hint of what's going on. Possibly enable debug logging to see what the full request and response contains.

**Comment by fruitloop** [comment]
Now it works. This was probably due to a shitty internet connection over mobile data.

**Comment by ecederstrand** [comment]
Hmm. Sounds unlikely, but you're welcome to reopen if you can reproduce :-)

**Comment by jacobmischka** [comment]
I actually just ran into this too, I'll try to narrow down what's going on and post back here soon. In the meantime I think this might as well be reopened.

**Comment by jacobmischka** [comment]
Hm it almost looks like a server/configuration problem, the error is just being spit out by Exchange.

```xml
<m:GetItemResponseMessage ResponseClass="Error">
	<m:MessageText>Recurrence has no occurrences in the specified range.</m:MessageText>
	<m:ResponseCode>ErrorRecurrenceHasNoOccurrence</m:ResponseCode>
	<m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
	<m:MessageXml>
		<t:Value Name="EffectiveStartDate">8/16/2017 12:00:00 AM</t:Value>
		<t:Value Name="EffectiveEndDate">10/18/2017 12:00:00 AM</t:Value>
	</m:MessageXml>
	<m:Items/>
</m:GetItemResponseMessage>
```

Is there a way that I can just ignore this error so that I can still read the rest of the events? It looks like if I do a standard --

```python
for event in account.calendar.all():
		try:
			print(event)
		except Exception as e:
			print(e, file=sys.stderr)
```

-- it fails in the generator, so none of the events that occur after the error get printed.

**Comment by fruitloop** [comment]
I see you are having the error on a "multi day event" as well.

Mine crashed there as well.

**Comment by jacobmischka** [comment]
Ah, looks like just a wrapper generator that eats the exception works:

```python
def wrapper(gen):
	while True:
		try:
			yield next(gen)
		except StopIteration:
			raise
		except Exception as e:
			print()

def main():
	logging.basicConfig(level=logging.DEBUG)
	account = get_account()
	for event in wrapper(account.calendar.all().__iter__()):
		try:
			print(event)
		except Exception as e:
			print(e, file=sys.stderr)
```

So maybe this isn't a problem after all. Maybe it might be nice to not break by default if one of the items in a response set happens to raise an error, but I'm not sure if that's really possible.

Thanks!

**Comment by ecederstrand** [comment]
Adding `ErrorRecurrenceHasNoOccurrence` to the `exchangelib.services.EWSService.ERRORS_TO_CATCH_IN_RESPONSE` tuple should work in the sense that you'll get an exception object in the return values instead of the whole generator crashing when it encounters this element.

If it works, I'll gladly add this exception to the list.

**Comment by jacobmischka** [comment]
Thank you!

**Comment by ecederstrand** [comment]
I assume this only happens if you do some sort of filtering on the start and/or end date of the calendar items? If so, I think this is just EWS tripping over its own toes, fetching items that don't match the filter and then complaining that the item doesn't match.

If you want to have only recurring calendar items returned in the query, you can filter on `is_recurring=True`. `type='RecurringMaster'` would probably also work.

`You can then `account.calendar.view()` to get the expanded calendar items for a certain date range.

**Comment by tinyweasel** [comment]
I'm not filtering at all actually, this code is part of an automated job that runs every ten minutes and gets any changed items from the calendar and writes them to a database. Every item in the calendar was initially synced to the database as well. We save the RecurringMasters and the Recurrences for the sake of troubleshooting.

**Comment by tinyweasel** [comment]
MaxChangesReturned is set to 100, that's the only range of any kind set on it. This Microsoft page says the events could be corrupt, any input on that?

https://social.msdn.microsoft.com/Forums/office/en-US/929412ea-07c7-4060-a181-7a1e217b0f40/e2007sp1ewsmac-calendarfolderfindappointments-recurrence-has-no-occurrences-in-the?forum=exchangesvrdevelopment

**Comment by ecederstrand** [comment]
I have no idea if that could be the issue, but we are sending a fairly innocent request, so an internal problem in Exchange seems likely.
