### ISSUE TITLE
Cannot Import Name 'Delegate'

### ISSUE THREAD

**Issue by abekan** [ecederstrand/exchangelib#179]
Hi,
The first line of my code includes Import Delegate but I get the following error:
ImportError: cannot import name 'Delegate'
I checked the exchangelib folder and didn't see Delegate.py in there--is this no longer part of the library? 
I'm having the same issue with IMPERSONATION and NTLM
I'm very new to Python, so i would really appreciate any guidance.
Many thanks.

**Comment by ecederstrand** [comment]
Python is case-sensitive, so you need to write your imports exactly as stated in the examples:

```python
from exchangelib import DELEGATE
```

There is no `delegate.py` because `DELEGATE` is a shortcut in `__init__.py` to its original location in `credentials.py`
