### ISSUE TITLE
send emails

### ISSUE THREAD

**Issue by jim-bo** [ecederstrand/exchangelib#18]
Is there a way to send emails via exchange using this library?

**Comment by ecederstrand** [comment]
I didn't know myself, but [this is actually possible with EWS](https://msdn.microsoft.com/en-us/library/office/dn600292(v=exchg.150).aspx) using either the `SendItem` service with existing draft items, or with the `CreateItem` service. We don't support the former service yet (but it would be easy to add). We do support the latter, but only in save-mode, not in send-and-save mode. Until the mode is configurable, you'll need to got to `exchange lib.folders.Folder.create_xml()` and change `MessageDisposition='SaveOnly'` to `MessageDisposition='SendAndSaveCopy'`. Then you can do something like:

```python
email = Message(
    subject='Hi',
    body='Dear mom', 
    to_recipients=[Mailbox(email_address='mom@example.com')]
)
sent_folder = my_account.folders[Messages][<choose one of the folders here as your destination>]
sent_folder.add_items([email])
```

**Comment by ecederstrand** [comment]
Since version 1.7.0, sending emails is supported, with less code than the above:

```python
from exchangelib import Account, Credentials
from exchangelib.folders import Message, Mailbox

email = 'john@example.com'
password = 'topsecret'

a = Account(email, credentials=Credentials(email, password), autodiscover=True)
m = Message(
    folder=a.sent, 
    subject='Daily motivation', 
    body='All bodies are beautiful', 
    to_recipients=[Mailbox(email_address='erik@cederstrand.dk')])
m.send()  # Or m.send_and_save() if you want a copy in the 'Sent' folder

```

**Comment by rm17tink** [comment]
Hello Sir,
How can I attach an excel file from a dir

**Comment by rm17tink** [comment]
How can i send an email with an excel attachment

**Comment by ecederstrand** [comment]
There's an example of file attachments at https://github.com/ecederstrand/exchangelib/blob/master/README.rst#attachments

Excel files are just binary data as far as EWS is concerned, so there's nothing special you need to do there.

**Comment by rm17tink** [comment]
Yeah I didn't understand that for statement i just need directory source file but it won't send

⁣Sent from BlueMail ​

**Comment by ecederstrand** [comment]
Please post your failing code and the except you get.

**Comment by rm17tink** [comment]
Really appreciate all your help. I think the issue I have is with the .pdf attachment. I am getting a content error, i am not sure its from the FileAttachment in exchangelib . Does it accept PDFs as content?

Error message = `TypeError: Field '_content' value '<PyPDF2.pdf.PdfFileReader object at 0x0000000011E320F0>' must be of type <class 'bytes'>`

```
```
from exchangelib import Account, Credentials, Message, Mailbox, FileAttachment
import PyPDF2

dir_path = ('C:/Users/Istcrmt/Documents/Python/PythonforAnaconda3.5/')
excel_name = 'test.xlsx'
cover_letter_name = 'test.pdf'
#attach an excel file:
    
with open(dir_path + excel_name, 'rb') as f, \
open(dir_path + cover_letter_name, 'rb') as g:
    # Read the binary file contents
    excel_content = f.read()  
    cl_content = PyPDF2.PdfFileReader(g)
excel_att = FileAttachment(name='test.xlsx', content=excel_content) 
cl_att = FileAttachment(name='test.pdf', content=cl_content) 

# loop through the email list 
for i in email_list.itertuples():
# if you want a copy in the 'Sent' folder
    m = Message(
        account=a 
        ,folder=a.sent
        ,subject=(i.AGENCY_NAME + ' I made an email script.')
        ,body=body_of_email 
        ,to_recipients=[Mailbox(email_address=i.NEW_MAIL)])
    
#attach files
    m.attach(excel_att)
    m.attach(cl_att)
        
    m.send_and_save()

```

**Comment by ecederstrand** [comment]
You shouldn't convert `g` to a `PyPDF2` object. Just read the bytes from the file directly, like you did for the Excel file.

`FileAttachment` doesn't care about the file type. It just wants a `bytes` object. If the receiving end is having trouble opening the file, you may have to set the `content_type` attribute explicitly. We try to guess the mimetype of the file from the `name` attribute, but that may fail.

**Comment by rm17tink** [comment]
Yes i mirrored the process as the excel but always end up with a corrupt pdf file that way. 

⁣Sent from BlueMail ​

**Comment by MartinThoma** [comment]
People who come here might be interested in this:

```
from exchangelib import ServiceAccount, Configuration, Account, DELEGATE
from exchangelib import Message, Mailbox, FileAttachment

from config import cfg  # load your credentials


def send_email(account, subject, body, recipients, attachments=None):
    """
    Send an email.

    Parameters
    ----------
    account : Account object
    subject : str
    body : str
    recipients : list of str
        Each str is and email adress
    attachments : list of tuples or None
        (filename, binary contents)

    Examples
    --------
    >>> send_email(account, 'Subject line', 'Hello!', ['info@example.com'])
    """
    to_recipients = []
    for recipient in recipients:
        to_recipients.append(Mailbox(email_address=recipient))
    # Create message
    m = Message(account=account,
                folder=account.sent,
                subject=subject,
                body=body,
                to_recipients=to_recipients)

    # attach files
    for attachment_name, attachment_content in attachments or []:
        file = FileAttachment(name=attachment_name, content=attachment_content)
        m.attach(file)
    m.send_and_save()


credentials = ServiceAccount(username=cfg['user'],
                             password=cfg['password'])

config = Configuration(server=cfg['server'], credentials=credentials)
account = Account(primary_smtp_address=cfg['smtp_address'], config=config,
                  autodiscover=False, access_type=DELEGATE)

# Read attachment
attachments = []
with open('filestorage/numbers-test-document.pdf', 'rb') as f:
    content = f.read()
attachments.append(('whatever.pdf', content))

# Send email
send_email(account, 'Test 14:35', 'works', ['themoosemind@gmail.com'],
           attachments=attachments)

```

**Comment by srikkar** [comment]
Hi,
using exchangelib, Im able to send emails with attachments.
But, replying with attachments features seems unavailable.

Please help on this.
