### ISSUE TITLE
Project management suggestions

### ISSUE THREAD

**Issue by ankostis** [ecederstrand/exchangelib#181]
Thank you again for this lib.

Regarding the management of this project, I would like to make 2 suggestions:
- Would it be possible to use tagged-releases and/or milestones to track fixed bugs?
For instance, I'm trying to see if #160 is included in latest PyPi release.
- Usually the documentation-link (https://pypi.python.org/pypi/exchangelib) of a project is included at the top of the GitHub-repo (just click the `Edit` button to the top of the landing-page and set it).
  Even better, you may include all info links using [RST's field-lists](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#field-lists) beneath  `README.rst`'s header-line like this (but need maintenance afterwards):
```
####################################
Exchange Web Services client library
####################################
:release:       1.9.4
:date:          2017-06-22
:home:          https://github.com/ecederstrand/exchangelib/
:pypi-repo:     https://pypi.python.org/pypi/exchangelib/
```

**Comment by ecederstrand** [comment]
Thanks for the suggestions! Yes, I think it's time to be more explicit about releases. I'm just back from vacation but will pick this up soon.

Regarding documentation, I think the README has already grown too big and I'd prefer to clean it up and move it to e.g. GitHub pages.

**Comment by ankostis** [comment]
Regarding the last point, i use import rst directives to slice readme into doc sections. Thanksgiving to this trick, i avoid redundancy but still the full docs exist in GitHub.

**Comment by ecederstrand** [comment]
Cool! Do you have an example of that somewhere?

**Comment by ankostis** [comment]
Chevk JRCSTU/co2mpas

**Comment by MartinThoma** [comment]
[`git tag`](https://git-scm.com/book/en/v2/Git-Basics-Tagging) is actually really easy to use:

* Create new tag for last commit: `git tag -a v1.4 -m "my version 1.4"`
* List all tags: `git tag`
* Tag old commit: `git tag -a v1.2 9fceb02 -m "Message here"`
* Compare commits by tag: `git diff tag1 tag2`
