### ISSUE TITLE
can i use it to connect outlook owa?

### ISSUE THREAD

**Issue by daniel-bluesea** [ecederstrand/exchangelib#182]
my company has a web gui for our outlook: webmail2.go2uti.com.

is this lib can connect to it?

**Comment by kamalpy** [comment]
You can directly connect to your exchange server with exchangelib .

**Comment by ecederstrand** [comment]
You cannot connect to OWA directly using exchangelib, but most servers that expose OWA also expose access to EWS, which is the webservice exchangelib connects to.

**Comment by daniel-bluesea** [comment]
i managed to connect with credentials and account calls:

account = Account(primary_smtp_address='john@example.com', credentials=credentials,
                  autodiscover=True, access_type=DELEGATE)

still struggling with to find other APIs that are similar to those of python IMAP lib that are more familiar to me (email uid, search, filter and similar)

**Comment by ecederstrand** [comment]
If you have questions regarding how to use exchangelib, please look through the README and create an issue here if anything is unclear :-)
