### ISSUE TITLE
Carbon Copy/ BCC

### ISSUE THREAD

**Issue by rm17tink** [ecederstrand/exchangelib#183]
Do I have the ability to carbon Copy someone or do I have to loop through a list of emails independently? Thanks 

m = Message(
    account=a 
    ,folder=a.sent
    ,subject=('Hello, is it me you're waiting for?')
    ,body = body_of_email 
    ,to_recipients=[Mailbox(email_address=X@XX.com)])

**Comment by ecederstrand** [comment]
Yes. There are the `cc_recipients` and `bcc_recipients` attributes for that. They behave the same as `to_recipients`.

It's not documented, but you can pass either a list of `Mailbox` instance or a list of plain email address strings.

**Comment by rm17tink** [comment]
Thanks very much. 

Any understanding of this warning..only happened today for the first time "INFO:exchangelib.version:API version "Exchange2007" worked but server reports version "Exchange2016". Using "Exchange2016""

**Comment by ecederstrand** [comment]
It's not a warning, just an info :-) When we make the initial connection, EWS expects a version string in the SOAP header, but we don't know the server version yet. So exchangelib does some guessing. The message just means we tried with "Exchange2007" but the server was actually "Exchange2016". This message is harmless.

**Comment by rm17tink** [comment]
Thanks. Can I also pass through a stored contact group(several) in outlook as the cc_recipients? I couldn't find the documentation on that? I tried to pass a string with ; in between as a group of people but it didn't work. I would be best passing an actual contact group.

**Comment by ecederstrand** [comment]
The `CcRecipients` element (https://msdn.microsoft.com/en-us/library/office/aa581076(v=exchg.150).aspx) expects a list of `Mailbox` elements (https://msdn.microsoft.com/en-us/library/office/aa565036(v=exchg.150).aspx) so it seems it is indeed possible to create an `Mailbox` object in exchangelib for the distribution list and add that to the `cc_recipients` list (you may need to set the `mailbox_type` explicitly, see https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/properties.py#L222).

**Comment by rm17tink** [comment]
Probably my own ineptitude but I cant pass a set of emails in a single cc_recipients and the multy doesnt work either 
# 
email_list = 'x@yes.com ; y@yes.co'
m = Message(
    account=a 
    ,folder=a.sent
    ,subject=('test')
    ,body = body_of_email 
    ,to_recipients =[Mailbox(email_address=email1)]
    ,cc_recipients =[Mailbox(email_address=email2)]
    ,cc_recipients =[Mailbox(email_address=email3)]
#ideally 
 ,cc_recipients =[Mailbox(email_address=email_list)]
    )

**Comment by ecederstrand** [comment]
A `Mailbox` item can only hold one email address. If you provide just the email adresses, thy must be a `list` of strings. So, do one of the following:

```python
cc_recipients =[Mailbox(email_address='x@yes.com'), Mailbox(email_address='y@yes.co')]
# or:
cc_recipients =['x@yes.com', 'y@yes.co']
```

**Comment by rm17tink** [comment]
Thanks. Both of these produce invalid syntax 
```
m = Message(
    account=a 
    ,folder=a.sent
    ,subject=('Test')
    ,body = body_of_email 
    #,to_recipients = [Mailbox(email_address=email)]
    ,to_recipients = [email]
```
                          ERRORS
```
    #CC Recipients
    cc_recipients = [email, SMTP]
        # or:
    #cc_recipients =[Mailbox(email_address=email), Mailbox(email_address=SMTP)]    
```     
    
    
    )

**Comment by ecederstrand** [comment]
What is the syntax error? It seems you're missing a comma between some of the arguments:

```python
m = Message(
    account=a,
    folder=a.sent,
    subject='Test',
    body=body_of_email,
    to_recipients=[email],
    cc_recipients=[email, SMTP],
    #cc_recipients=[Mailbox(email_address=email), Mailbox(email_address=SMTP)],
)
```

**Comment by ecederstrand** [comment]
Please reopen if you're still stuck :-)
