### ISSUE TITLE
How do I find WINDOMAIN?

### ISSUE THREAD

**Issue by MartinThoma** [ecederstrand/exchangelib#184]
I am currently struggling with the first part of the example:

```
# Username in WINDOMAIN\username format. Office365 wants usernames in PrimarySMTPAddress
# ('myusername@example.com') format. UPN format is also supported.
credentials = Credentials(username='MYWINDOMAIN\\myusername', password='topsecret')
```

Where do I find the `WINDOMAIN`?

**Comment by ecederstrand** [comment]
This is something your organization will have to supply. `WINDOMAIN` is the Windows domain name that your Windows username is connected to. This is needed if the Exchange server uses the ActiveDirectory server for authentication, AFAIK. You could try using your email address instead. This is sometimes accepted by the Exchange server.

f you have access to OWA, then the credentials for OWA will usually work with exchangelib.

**Comment by MartinThoma** [comment]
What are usual WINDOMAIN names? Are there any restrictions on what characters can be in there? Just to give me a clue what I am looking for, e.g. what of the following could be a WINDOMAIN?

* google
* google.com
* GOOGLE
* GOOGLE 123
* GOOGLE-123
* http://google.com

**Comment by ecederstrand** [comment]
Here's a link to a blog post with commands you can use to find your [Windows Domain](https://en.wikipedia.org/wiki/Windows_domain) name: https://www.windows-commandline.com/find-domain-name-command-line/

Also make sure to try your email address as the username. That may work for you.

**Comment by MartinThoma** [comment]
Thank you!
