### ISSUE TITLE
Viewing shared calendar via sharing_metadata.xml

### ISSUE THREAD

**Issue by jacobmischka** [ecederstrand/exchangelib#188]
Is it currently possible to view a calendar that was shared via a `sharing_metadata.xml` attachment using this library?

I read through the source of this package but I couldn't seem to find any function where I can find the folder using the `EntryId`, `FolderId`, and/or `MailboxId` that the file specifies. I'm in the process of trying to dig through ews documentation for what I'm supposed to do with these values, but if you could point me in the right direction I would greatly appreciate it.

Example `sharing_metadata.xml` file for reference ([via blog post](https://willcode4foodblog.wordpress.com/2012/04/13/understanding-sharing-invitation-requests-ews-managed-api-1-2-part-1/)):

```xml
<?xml version="1.0"?>
<SharingMessage xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/sharing/2008">
  <DataType>calendar</DataType>
  <Initiator>
    <Name>SharedByUserDisplayName</Name>
    <SmtpAddress>SharedByUser@contoso.com</SmtpAddress>
<EntryId>00000000DCA740C8C042101AB4B908002B2FE18201000656D2D4B65697A657220507
5626C6963205363686F6F6C732F6F753D6D696E6973747261746976652047726F757020284654
9424F48463233535092F636E3D52656369704757436F6E6E00</EntryId>
  </Initiator>
  <Invitation>
    <Providers>
      <Provider Type="ms-exchange-internal" TargetRecipients="sharedToUser@contoso.com">
        <FolderId xmlns="http://schemas.microsoft.com/exchange/sharing/2008">
00000000EA272C6387A99442B4B371A18905E4DB01007F8000</FolderId>
        <MailboxId xmlns="http://schemas.microsoft.com/exchange/sharing/2008">
00000000EA272C6387A993A547A9A1B0F249B6491B00000000000038A1BB1005E5101AA1BB08002B
2A56C20000454D534D44422E444C4C00000000000000001B55FA20AA6611CD9BC800AA002FC45A0C
000000445443454D585075626C6963205363686F6F6C732F6F753D4578636867652041646D6520
</MailboxId>
      </Provider>
    </Providers>
  </Invitation>
</SharingMessage>
```

I'm pretty unfamiliar with exchange, so apologies if I'm missing something simple.

Thanks your help and all your work on this library!

**Comment by jacobmischka** [comment]
Ah, looks like the extended properties support that this library has should be enough to get this to work. Thanks!

**Comment by ecederstrand** [comment]
I'm glad you seem to have found a solution. I've never encountered `sharing_metadata.xml` files before.

The `FolderId`, `EntryId` etc. values look like base64 encoded values. You should be able to get those via extended properties on items you already know how to access via exchangelib, but I'm not sure how you'd look up mailboxes and folders via those values using exchangelib.

If you do get this to work, it would be great if you post a small howto here so others can benefit. I can also add a description to the README. If you prefer explicit support via some helper methods in exchangelib, you're welcome to create a PR.

**Comment by jacobmischka** [comment]
I plan on it! I read through the spec and it looks like you just need to reply with a bunch of magic extended props. I think I'll need to submit a patch for extended properties to support "Property Long ID" values, and then once I get something working I'll try writing a helper function that automates everything. I'll try to have something in the next few days.

Thanks for your help!

**Comment by nkrumm** [comment]
@jacobmischka fantastic work figuring this out. did you ever come around to making this work using exchangelib?

**Comment by kbrowder** [comment]
@jacobmishka I have the same question, any hints?

**Comment by jacobmischka** [comment]
Ah sorry, no, I didn't get around to it. I ended up getting the calendar shared with me the standard way instead, which happened by accident but made the application much easier.

Sorry for getting your hopes up!
