### ISSUE TITLE
AWS WorkMail?

### ISSUE THREAD

**Issue by Erve1879** [ecederstrand/exchangelib#19]
I'm trying to get AWS WorkMail to play ball with this library, but I keep getting either a 403 Forbidden, or 500 INTERNAL SERVER ERROR. 

I've tried using the two setup methods shown in the readme, as well as almost every combination of server/username/auth type I can think of. The trouble is I can't find any WorkMail specific docs anywhere, other than to say that it is a fully EWS-compatible service.

Probably far OT, but I'd be very grateful for any tips/suggestions/knowledge you might be able to impart!

**Comment by ecederstrand** [comment]
Hmm, I never heard of AWS WorkMail before, and the error messages from AWS are less than helpful, if that's all you get. You could try setting up DEBUG logging and uncommenting [these two lines](https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/util.py#L289-L290) to see the full HTTP exchange. Maybe that will give you an indication of what is happening.

Maybe AWS only support a subset of the EWS services, and we're using one of the non-supported ones?

**Comment by Erve1879** [comment]
Thanks @ecederstrand - the exception is actually coming from here: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/transport.py#L213

So it's related to auto discover it seems. However, WorkMail does support auto-discover (assuming mail clients etc use the same process)

**Comment by ecederstrand** [comment]
Ok, that's part of the code that tries to guess which authentication type the Autodiscover endpoint requires (Basic, NTLM, Digest, or None). The code path starts here: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover.py#L303

We're sending what is supposed to be a well-formed autodiscover request and looking at the HTTP headers for hints on what auth type to use, but maybe AWS actually does send that in the headers but we're just too picky about the status code being 401?

**Comment by Erve1879** [comment]
Just edited my last message with the headers - doesn't look like WorkMail is giving anything useful in the headers at all.

**Comment by Erve1879** [comment]
I'm also trying this setup, which results in exactly the same headers and 403 response:

````
config = Configuration('george@opendna.ai', 'mypassword'
                           server='ews.mail.us-east-1.awsapps.com',
                           auth_type=NTLM)
    credentials = Credentials(username='george@opendna.ai',
                              password='pwk-ezS-RPK-yL6')
    account = Account(primary_smtp_address='george@opendna.ai',
                      config=config, access_type=DELEGATE)
````

**Comment by ecederstrand** [comment]
Have you tried other auth_type values? Maybe they don't support NTLM. Otherwise, the best I can think of is to log the traffic a functioning client is sending and compare that with what exchange lib is sending.

BTW, you might want to change your password now, assuming you forgot to blank out the one in `Credentials(...)` above...

**Comment by Erve1879** [comment]
Thanks @ecederstrand - a lesson in quick fire commenting code snippets! 

Have tried different auth methods, but will keep plugging away and see what gives. Have tried monitoring traffic, but SSL makes it hard...

**Comment by ecederstrand** [comment]
:-) Yeah, you probably need to set up a MITM SSL proxy, e.g. https://mitmproxy.org

**Comment by ecederstrand** [comment]
@Erve1879 Did you get anywhere? If you're not actively working on this, I'd like to either close this issue or park is as an enhancement request.

**Comment by Erve1879** [comment]
@ecederstrand - sadly not, no. Unfortunately I'm not going to be able to devote any time to debugging this, so I'll close on the assumption that not many WorkMail users have a the need for this!

**Comment by hamannju** [comment]
I know this is old, but it is literally what comes up then you google how to connect to AWS Workmail using exchangelib. 
So the way to get this to work is to not use autodiscover at all and instead configure the service endpoint manually via a Configuration object.
The endpoint url can be found by using the Microsoft Tool for testing autodiscover. My working configuration is:

config = Configuration(
        credentials=credentials, 
        service_endpoint='https://ews.mail.eu-west-1.awsapps.com/EWS/Exchange.asmx',
        auth_type='basic'
)

**Comment by ecederstrand** [comment]
Thanks for the example!

If you set up autodiscover on your email domain (even a fake one, the autodiscover protocol is pretty simple), you *should* be able to redirect clients to the EWS endpoint of AWS Workmail.

**Comment by thomas-schulze-entwicklerschmiede** [comment]
You saved my Christmas - thanks for Your great library!
