### ISSUE TITLE
Complete or Delete Tasks

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#192]
Hi,

I have managed to create Tasks.
However I can not delete or complete them.

`task.delete()` tells me it can't delete non recurring tasks?
and `task.is_complete = True` followed by `task.save()` does nothing.

What am I doing wrong?

**Comment by ecederstrand** [comment]
Just to assist debugging, can you please post a complete example producing the error? Thanks

**Comment by fruitloop** [comment]
Okay, the problem still exists, but this is no longer urgent.

I was creating tasks and if they were still here I would have deleted them and created new ones.
Now I'm just changing the existing ones or creating new ones if there are none.

Probably the better way anyways ;)



For the debugging part:
The `task.is_complete = True` followed by `task.save()` does not output anything at all. However it doesn't work either.

The `task.delete()` gives me this output:
```
Traceback (most recent call last):
  File "/Users/roland/PycharmProjects/time-tracking/time_tracking/cli.py", line 542, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/roland/PycharmProjects/time-tracking/time_tracking/cli.py", line 269, in main
    t.delete()
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 261, in delete
    affected_task_occurrences=affected_task_occurrences, suppress_read_receipts=suppress_read_receipts)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/items.py", line 274, in _delete
    raise res[0]
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 237, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/services.py", line 254, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorCannotDeleteTaskOccurrence: Deleting a task occurrence is not permitted on non-recurring tasks, on the last occurrence of a recurring task or on a regenerating task.```

**Comment by ecederstrand** [comment]
I just had a closer look at this.

To delete tasks, I think you'll have luck if you set the `affected_task_occurrences` flag:

```python
from exchangelib.items import ALL_OCCURRENCIES
task.delete(affected_task_occurrences=ALL_OCCURRENCIES)
```

Regarding `task.is_complete`, this is a read-only field in EWS (and in exchangelib). If you want to mark a task completed, you must set `task.status = Task.COMPLETED` in combination with `task.percent_complete = Decimal(100)`.

**Comment by fruitloop** [comment]
Thanks for analyzing. I'll try that tonight.

So much to do just to complete/delete a Task. 
That begs for a nice wrapper ;)

**Comment by ecederstrand** [comment]
For the delete part, you have to tell EWS if you want to delete all or only one occurrence. But I guess we could be smart and check if the item is actually a recurring item and set the appropriate `affected_task_occurrences` value accordingly.

`save()` will bump `percent_complete` to 100 for you if `status` is COMPLETED, but it'll also print a warning because your fields are inconsistent (a complete task must be 100% complete). But maybe you were looking for a `complete()` method that sets the status and percentage and saves in one go?

**Comment by fruitloop** [comment]
Exactly, the `affected_task_occurrence` "should" be optional and only required if the item is actually recurring.

A `complete()` that actually completes (100% done and `status` to `completed`) would be great since it would reduce lines of code and I also think it makes more sense when reading the code.

**Comment by ecederstrand** [comment]
Ok. Let's leave the issue open until I or someone else gets around to implementing these two things.

**Comment by fruitloop** [comment]
Wow, that was fast
