### ISSUE TITLE
Passing in a date for the filter

### ISSUE THREAD

**Issue by rm17tink** [ecederstrand/exchangelib#193]
ag_list = []
for message in a.sent.all().filter(start__gte=EWSDateTime(2017, 8, 7)):
        ag_list.append(message.all)

I get this error, even when i create a date variable with datetime

ValueError: Value "2017-08-07 00:00:00" for filter on field path "start" is unsupported

**Comment by ecederstrand** [comment]
This is a misleading error message, fixed in https://github.com/ecederstrand/exchangelib/commit/014b78b3ea8c5091009d434864a9f03c80b58768

You need to make your `EWSDateTime` object timezone-aware. Naive datetimes will not work.

**Comment by rm17tink** [comment]
Thanks.  How would I pull not only the subject but the date of the emails?

**Comment by ecederstrand** [comment]
This depends on which date you mean. You're searching the Sent folder, which usually only contains `Message` items. But you're filtering on the `start` field, which is only present on `CalendarItem` objects. So it's questionable what the filter will return.

To see the available fields on the `Message` class, do this:

```python
form exchangelib import Message
Message.supported_fields()
```

**Comment by rm17tink** [comment]
You have better support and help than a conglomerate institution. I thank you always for your responses.

Also I couldnt locate the timezone call. I used microsofts desgination but none worked. I am under EST which never could be found under EWS.

Thanks

**Comment by ecederstrand** [comment]
Thanks for the kind words! Regarding timezones, do this to get a localized datetime:

```python
tz = EWSTimeZone.timezone('Europe/Copenhagen')
localized_datetime = tz.localize(EWSDateTime(2017, 8, 7, 6, 5, 4))
```

This is also how `pytz` recommends creating localized dates.

Regarding your second question, have a look at the `values()` or `values_list()` methods of querysets: https://github.com/ecederstrand/exchangelib#searching

This will return only the values you specify in the arguments.

**Comment by ecederstrand** [comment]
Closing. Please reopen if this didn't answer your questions.
