### ISSUE TITLE
ErrorMimeContentConversionFailed while account.fetch

### ISSUE THREAD

**Issue by marioschaefer** [ecederstrand/exchangelib#194]
Hi,

this is more like a question, than a bug report.
I'm trying to get messages from the exchangeserver(for archiving purposes) with a messagelist and account.fetch:
```python
try:
    for foldermsg in account.fetch(ids=foldermsglist, only_fields=['mime_content']):
        try:
            #archive the message
        except:
            #log exception
except:
    #log this exception
    #ErrorMimeContentConversionFailed 
```

Now, sometimes im hitting the ErrorMimeContentConversionFailed-Exception.
But i dont know which message this is(because the Exception doesnt tell me), so i cant exclude it from the messagelist and try again.
Can i modify the Exception to also return the message-id(and change-id) or something like that to identify the exact message which is causing this Exception? 
And if, how?

Or do you have any other idea?

Thanks
Mario

**Comment by ecederstrand** [comment]
Try adding `ErrorRecurrenceHasNoOccurrence` to the `exchangelib.services.EWSService.ERRORS_TO_CATCH_IN_RESPONSE` tuple. This looks related to #177.

**Comment by marioschaefer** [comment]
Hi,
thanks for the advice.
This is working perfectly, i can now catch the Error and just continue with the next message.

perfect!

**Comment by ecederstrand** [comment]
Reopening as a reminder to add `ErrorMimeContentConversionFailed` to the list.
