### ISSUE TITLE
Implement 2-factor authentication

### ISSUE THREAD

**Issue by shie-erlich** [ecederstrand/exchangelib#196]
hi folks and thanks for working on this project!
my code successfully logs in and pulls down the data i need (using access_type=DELEGATE), as long as i'm logged in to my company network (either the real network or over VPN). 
however, when not on corpnet i get an "incorrect password" error.

questions:
1. anyone knows why is this happening? should i do something different?
2. could this be 2-factor auth at play? if so, any clue as to how to handle that?
3. when i remove the access_type option, i get an error saying that my account doesn't have permissions to impersonate that user (which is myself), and this happens on or off the corpnet. any clue?

thank you!

**Comment by ecederstrand** [comment]
Does this work with other clients, e.g. an Outlook client on your phone?

Re. 2: We don't implement any "exotic" auth methods yet (OAuth, Kerberos, 2-factor, ...), just Basic, Digest and NTLM. Adding to the list would be a fantastic contribution :-)

Re. 3: This is expected. AFAIK you normally don't have impersonation access to your own account.

**Comment by ecederstrand** [comment]
Also, "password incorrect" can also just mean that your login was rejected for any number of reasons (firewalling, different auth requirements, throttling policies, etc).

**Comment by shie-erlich** [comment]
thanks Erik and sorry for the late reply (i'm on vacation).

to answer your questions/comments:

- it does work on my phone using outlook, and meanwhile i learned that my
company indeed uses 2fac
- re: 2 ... understood. i didn't even know 2fac was an actual auth method,
thought about it as a pre-auth step. do you have links to documentation on
what needs to be implemented?
- re 3: this is all very complicated i guess :)

**Comment by ecederstrand** [comment]
No problem :-) I actually have no idea how 2-factor auth is implemented on Exchange, I've just seen it implemented at various companies.

You're welcome to research a solution - unfortunately I have limited time and no way of testing.

**Comment by ecederstrand** [comment]
I took the liberty of changing the subject and marking this as an enhancement.

**Comment by cranbar** [comment]
Supporting 2-factor authentication is probably only possible via OAuth.

**Comment by ecederstrand** [comment]
Oauth is now supported. I'm closing this issue as there's nothing concrete to work on.
