### ISSUE TITLE
EXCHANGE 2010 for item in account.inbox.all() exchangelib.errors.ErrorInvalidPropertyRequest:

### ISSUE THREAD

**Issue by hsxf** [ecederstrand/exchangelib#199]
print account2.inbox.total_count

    for item in account2.inbox.all():
        print 'aa'
File "/usr/local/lib/python2.7/dist-packages/exchangelib/services.py", line 254, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorInvalidPropertyRequest: 属性对此对象类型无效。 (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="calendar:End" />)

**Comment by ecederstrand** [comment]
Apparently, your server does not like that we're requesting the `calendar:End`field. I don't know why this happens to you because Exchange 2010 is supposed to allow calendar items in your inbox, but you can work around it for now by requesting the exact fields you want:

```python
from exchangelib import Message
# List all fields on the Message class
print(Message.FIELDS)
# Select some of these fields
for item in my_account.inbox.all().only('subject', 'body', ...):
    print(item)
```

**Comment by hsxf** [comment]
Thank you very much, but I want the entire mail MIME data, how can i do it? In addition, filter function can specify the number of it? For example, I only want 10 numbers in a certain time range of mail

**Comment by hsxf** [comment]
Thank you, MIME problem solved, but the filter function of the problem has not been resolved

**Comment by ecederstrand** [comment]
It seems not all versions of Exchange 2010 support meeting requests with a `start` field. Can you print your exact version number?

```python
print(my_account.protocol.version)
```

**Comment by ecederstrand** [comment]
BTW, to return only a limited amount of items, just slice your QuerySet like this: `account2.inbox.all()[:10]`

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have time to post your Exchange version :-)

**Comment by junngit** [comment]
Configuration set version=Version(build=Build(14, 2))
