### ISSUE TITLE
find_items: 'NoneType' object has no attribute 'q'

### ISSUE THREAD

**Issue by sleonov** [ecederstrand/exchangelib#20]
I am at version 1.6.2

This code started throwing exception:
---
ids = account.inbox.find_items()
---

Exception otput (read_mailbox is my function calling find_items()
---
ERROR:sbudevops.exchange:read_mailbox: Caught exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/sbudevops/exchange.py", line 108, in read_mailbox
    ids = account.inbox.find_items()
  File "/usr/lib/python3.4/site-packages/exchangelib/folders.py", line 787, in find_items
    restriction.q,
AttributeError: 'NoneType' object has no attribute 'q'
---

Thanks!

**Comment by ecederstrand** [comment]
Thanks for the report!

**Comment by sleonov** [comment]
Will pip3 have it soon?
Thanks!

On Mon, Sep 19, 2016 at 12:30 PM, Erik Cederstrand <notifications@github.com

**Comment by ecederstrand** [comment]
I have some large changes pending that will go into the next release. I'll probably have a new version ready on PyPI next week.

**Comment by sleonov** [comment]
Thank you.

**Comment by ecederstrand** [comment]
Version 1.7.0 is in PyPI now. There are a lot of backwards-incompatible changes. Check README.rst and CHANGELOG.rst!

**Comment by sleonov** [comment]
Thank you. I will give it a shot.
