### ISSUE TITLE
how to fetch email by id

### ISSUE THREAD

**Issue by sae13** [ecederstrand/exchangelib#200]
sorry i am noob 
how i can have access emails by id?
like fecth secound email ro whatever

**Comment by salmansamie** [comment]
Dude, it's all about parsing the response contents however you want. This is a completely different thing. Use something like Beautiful soup(bs4) and lxml frameworks.

On Aug 14, 2017 8:46 AM, Saeb <notifications@github.com> wrote:

sorry i am noob
how i can have access emails by id?
like fecth secound email ro whatever

**Comment by sae13** [comment]
Sorry I am beginner.
How I can fetch email by is? With what command?all example I saw is acc.inbox.all()
But I wanna get emails one by one.

**Comment by salmansamie** [comment]
I think this one has answers to your question:
http://it1me.seriousdigitalmedia.com/it-answers?id=43491673&ttl=Read+emails+and+download+attachment+using+python+centos

**Comment by sae13** [comment]
Yep. Tnx

۱۳۹۶-۰۵-۲۳ ۱۳:۰۰ +۰۴:۳۰ گرینویچ, smr_samie <notifications@github.com>:
> I think this one has answers to your question:
> http://it1me.seriousdigitalmedia.com/it-answers?id=43491673&ttl=Read+emails+and+download+attachment+using+python+centos
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ecederstrand/exchangelib/issues/200#issuecomment-322129843


-- 
به امید ایرانی آبادتر آزادتر و پیشرفته تر از امروز
بدرود

**Comment by ecederstrand** [comment]
I'm not sure I understand the initial question, but you can get an email by `ItemId` (https://msdn.microsoft.com/en-us/library/office/aa580234(v=exchg.150).aspx) with:

```python
account.inbox.get(item_id=..., changekey=...)
```

If you want to get the first item in your inbox, you need to specify how to order the items, and then you can simply use indexing:

```python
account.inbox.all().order_by('-datetime_received')[0]
```

**Comment by sae13** [comment]
how i get items from specefic sender ? i tried 
```>>> item = account.inbox.filter(from="pay@nicico.com")
  File "<stdin>", line 1
    item = account.inbox.filter(from="pay@nicico.com")
                                   ^
SyntaxError: invalid syntax
```

**Comment by ecederstrand** [comment]
That's because `from` is a Python keyword. We had to translate the `From` EWS field to `author` in exchangelib. So do this instead:

```python
item = account.inbox.filter(author="pay@nicico.com")
```

**Comment by sae13** [comment]
​tnx​

**Comment by sae13** [comment]
`item = account.inbox.filter(author="pay@nicico.com")`
sorry for amateur questions, but how I can tell it find both read and unread messages?

**Comment by ecederstrand** [comment]
The example filter above will give you both. There's also a `sender` field you can try to filter on.

**Comment by sae13** [comment]
tnx , but above filter doesn't show read items, pls try that

**Comment by ecederstrand** [comment]
Can you please verify this by getting all items in your inbox, and checking that you in fact have messages by this author which are read?

```python
for item in account.inbox.all():
    if item.author and item.author.email_address.lower() != 'pay@nicico.com':
        continue
    print(item.author.email_address, item.is_read)
```

**Comment by sae13** [comment]
tnx 👍
