### ISSUE TITLE
[Documentation] Times of emails

### ISSUE THREAD

**Issue by MartinThoma** [ecederstrand/exchangelib#201]
E-Mails seem to have four time fields:

* 'datetime_created',
* 'datetime_sent',
* 'datetime_received',
* 'last_modified_time'

Are there any guarantees about the content of those fields? What can the sender manipulate?

Lets have a normal scenario: I use Thunderbird. I make a draft on `2017-02-20 22:15` and send it on `2017-02-21 09:30` (my mail servers time - but my local clock is by one minute, so `2017-02-21 09:29`). It arrives on the recipients mail server at `2017-02-21 09:31` and he marks the email as read at `2017-02-21 11:45`.

Questions:

* Is "datetime_created" now `2017-02-20 22:15` or `2017-02-21 09:30` or `2017-02-21 09:29` (on usual mail clients)?
* Is "last_modified_time" now `2017-02-21 09:31` or `2017-02-21 11:45`?
* Is "datetime_sent" the time on senders machine or the time on the senders mail server?

**Comment by ecederstrand** [comment]
I'm not sure this is in scope for exchangelib, but let's leave that for a moment. We're all about making Exchange easier to use and understand, so maybe we should expand that to documentation also...

I can't make any guarantees about what it's possible to modify within the Exchange data store, but all these fields are read-only in exchangelib. The testing I have done indicates that these fields are not modifiable via EWS.

**Comment by ecederstrand** [comment]
Hi @MartinThoma,

Do you have any suggestions to how we could improve documentation in this area?

**Comment by MartinThoma** [comment]
@ecederstrand I didn't read it as arrogant / rude. I like the fact that you take your time to answer :-)

I would add a section after "Attachments" and before "Troubleshooting" with "associated timestamps". That would basically be a summary of this issue. If you think that could be a good idea, I could make a pull request (probably this weekend)

**Comment by ecederstrand** [comment]
I'm fine with this. Type away :-)
