### ISSUE TITLE
Support *all* item fields

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#203]
I think it's time to support the kitchen sink. Previous policy was to only add fields that were understood and commonly used, but we have added many new fields since, and now the list of non-implemented fields is somewhat arbitrary and cause for confusion.

For each `Item` subclass, we should go through the MSDN documentation and add fields to the `FIELDS` lists with the correct field type and settings. If in doubt, fields should be marked read-only.

**Comment by ecederstrand** [comment]
After the latest commits, only the following fields are unimplemented:

```
class Item:
    ResponseObjects
    WebClientReadFormQueryString
    WebClientEditFormQueryString

class CalendarItem:
    ConflictingMeetings
    AdjacentMeetings
    AppointmentState

class Message:
    ReminderMessageData

class Task(Item):
    Recurrence

class Contact(Item):
    CompleteName
    Photo
    UserSMIMECertificate
    MSExchangeCertificate
    ManagerMailbox
    DirectReports
```

These are either non-trivial to implement or throw server errors on my current test server.

**Comment by bobusfindus** [comment]
Hi Eric... I have downloaded the latest source from GitHub, but am still having trouble accessing a shared mailbox using ExchangeLib. I have configured the credentials as follows:
config = Configuration(server='my.mailserver.net', credentials=Credentials(
    'WINDOMAIN\\lan_user', config.LAN_PASS), auth_type=NTLM,  service_endpoint='https://EWS-Server.asmx',)
sam_account = Account(
    primary_smtp_address='other@shared-mailbox.com', config=config, access_type=DELEGATE)

However when I do a folder tree walk, exchangelib will only return folders in my mailbox, not the other shared mailbox I'm trying to access. 

I read that the bug had been fixed on Github, but it still seems to be happening to me - have you got any ideas what's wrong? I'm pulling my hair out here!

Cheers, Bob

**Comment by ecederstrand** [comment]
There are multiple ways to do this. The easiest way is probably to fetch the full item first, make changes and then call save():

```python
full_item = account.inbox.get(item_id=item.id)
full_item.subject = 'New subject'
full_item.save()
```

**Comment by flipdazed** [comment]
is `Contact.DirectReports` related to the OWA contact card Properties that sends a request to `{server}/owa/ev.owa?oeh=1&ns=RecipWell&ev=GetRecipProps`?

**Comment by ecederstrand** [comment]
I don’t know how OWA works, unfortunately, so I can’t nasser your question.

**Comment by ecederstrand** [comment]
https://github.com/ecederstrand/exchangelib/pull/812, https://github.com/ecederstrand/exchangelib/pull/813 and https://github.com/ecederstrand/exchangelib/pull/814 added more fields on Contact, and all remaining fields on CalendarItem and Message.
