### ISSUE TITLE
How do I limit the number of messages received

### ISSUE THREAD

**Issue by hsxf** [ecederstrand/exchangelib#208]
First of all, thank you for your enthusiasm to answer some of the questions I mentioned
I now have a question
How do I limit the number of messages received? I use this code

```python
for item in items_for_Find.only('subject','mime_content','last_modified_time')\
    .order_by('-last_modified_time')[:1]:
```

but i find the client first to get all the mail and then limit

I want the server to only return a certain amount of mail data

**Comment by ecederstrand** [comment]
Slicing like you do in your example is perfectly fine. Internally, we only fetch the data necessary to fulfil the slice, so `my_account.inbox.all()[:5]` is still efficient even if you have 5.000 mails in your inbox. See also the slicing examples in https://github.com/ecederstrand/exchangelib#searching

**Comment by hsxf** [comment]
My inbox has 3 emails, and I only intend to download an email when testing
In my test, I put the log print level for the debug level, I use the following code to test
for item in items_for_Find.only('subject','mime_content','last_modified_time')\
    .order_by('-last_modified_time')[:1]:
From the printed log out, the client first makes three requests each time to get a message ID, and then the fourth request is to get the data of the three messages, the server returns the data of the three messages, which is not what I expect the result of


Here a total of four network requests, if I have 1000 e-mail, it will be a lot of network requests, so too consume network performance

**Comment by hsxf** [comment]
The network request process is as follows：
1...<m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="1" Offset="0" />...
2...<m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="1" Offset="1" />...
3...<m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="1" Offset="2" />...
4...<m:ItemIds><t:ItemId ChangeKey="..." Id="..." /><t:ItemId ChangeKey="..." Id="..." /><t:ItemId ChangeKey="..." Id="..." /></m:ItemIds></m:GetItem></s:Body></s:Envelope>...

**Comment by ecederstrand** [comment]
Thanks for the examples! I agree we should be smarter than that.

**Comment by hsxf** [comment]
Thank you, look forward to the updated version

**Comment by ecederstrand** [comment]
I just released v. 1.9.5 and cannot reproduce with this version. Can you please try to reproduce?

**Comment by ecederstrand** [comment]
Please feel free to reopen if you can reproduce this
