### ISSUE TITLE
Partial sync - implement SyncFolderItems method

### ISSUE THREAD

**Issue by utapyngo** [ecederstrand/exchangelib#209]
I need to synchronize a mailbox. There is an article describing how to do it using EWS:

https://msdn.microsoft.com/en-us/library/office/dn440953(v=exchg.150).aspx

Essentially, to perform a partial sync, one needs to store and provide `cSyncState` value.
However, the only mention of SyncState in `exchangelib` sources is

    class ErrorInvalidSyncStateData(ResponseMessageError): pass

Am I missing something?

**Comment by ecederstrand** [comment]
Yeah, `SyncState` is not implemented yet.

You can, however, quite cheaply implement sync functionality by doing something like:

```python
cached_ids = get_ids_from_local_cache(some_emailadress)
fresh_ids = some_account.all().values_list('item_id', 'changekey')
deleted_ids, changed_ids, new_ids = compare_items(cached_ids, fresh_ids)
# Update local cache from these lists
```

The network traffic may be higher, but the code will be easier to reason about, and you won't lose any updates by accident.

**Comment by utapyngo** [comment]
AttributeError: 'Account' object has no attribute 'all'

Did you mean syncing each folder separately?

**Comment by ecederstrand** [comment]
Sorry, I meant to write `some_account.inbox.all()` in the example, not `some_account.all()` (updated now). And yes, the approach will only work per-folder, so maybe it doesn't fit your needs.

You would feed the `changed_ids` and `new_ids` lists to `some_account.fetch(ids=list_of_ids)` to bulk get full item contents by ID.

**Comment by utapyngo** [comment]
What is the simplest way of getting all mail messages?
I tried this:

        ids = []
        for folder in account.root.get_folders():
            if not isinstance(folder, Messages):
                continue
            ids.extend(folder.all().values_list('item_id', 'changekey'))

But this sometimes returns ids of `CalendarItem`s and is slow when there are many folders.

**Comment by ecederstrand** [comment]
I'm not sure if there are any easy ways to do this via EWS, but I haven't been through the full documentation. The `FindItem` service only works per-folder. You could probably use `account.export()`, but I'm not sure it's faster.

**Comment by ecederstrand** [comment]
SyncFolderItems support was completed with a set of commits ending in https://github.com/ecederstrand/exchangelib/commit/a729eac1acf66265bfa1392fbb6ad4cb380cca24
