### ISSUE TITLE
Excessive InsecureRequestWarning(s)

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#215]
Hello,

i'm attempting to write a script to check a mailbox for new messages and send out a meeting/appointment based on data in message body. Because this is an internal corporate environment, I am using verify_ssl=False. This still generates a plethora of warnings:

**C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)**

I have exported the certificated needed for the connetction, but I cannot find an exchangelib method to use it.

I am currently using the requests module to suppress the warnings, but I would rather be able to supply the certificate to keep our network security department happy.

Any chance of getting this added?

I am using Python 2.7.11 on Windows 7.
My exchangelib version is 1.9.4
My Exchange version is: Build=15.1.845.36, API=Exchange2016, Fullname=Microsoft Exchange Server 2016

Thanks,

rjwiii

**Comment by ecederstrand** [comment]
Generally, trusted certificates should be handled outside exchangelib, and even outside Python. exchangelib uses `requests`, which again uses OpenSSL (I believe), so you should add the new certificate to the system-wide certificate store so OpenSSL can use it.

However, it's possible to customize the transport adapter class that exchangelib uses, so customize e.g. certificate validation. See the bottom of the 'setup' section: https://github.com/ecederstrand/exchangelib#setup-and-connecting and the corresponding documentation in http://docs.python-requests.org/en/master/api/#requests.adapters.BaseAdapter

Another possibility is to use the `REQUESTS_CA_BUNDLE` environment variable. See http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification You may also be able to handle this with the `certifi` package, see the section on CA certificates: http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

**Comment by rjwiii** [comment]
Thank you. I will try the options you mentioned.

**Comment by ecederstrand** [comment]
Hi @rjwiii Did you figure this out? If so, I'd like to add your solution to the documentation.

**Comment by rjwiii** [comment]
@ecederstrand - I have not tried yet. I am currently ignoring all InsecureRequestWarnings. Testing other things that have development priority. I will try to work on this more if my work makes in into production.

**Comment by ecederstrand** [comment]
Closing this. I have tested `REQUESTS_CA_BUNDLE` to work as a way to supply a custom certificate. If that is infeasible, `requests` will use the `certifi` package (if installed) which has more advanced certificate functionality.

Finally, if you want to continue disabling SSL verification, then you can suppress the warning like this:

```python
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
