### ISSUE TITLE
Rehash of issue #54 items: Calendar items do not get "sent" to attendees.

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#216]
Hello again,

I am attempting to create a calendar item and send it out to the attendees. Below is my code:

**vcn_appt = exchangelib.CalendarItem(folder=vcn_acct.calendar)
vcn_appt.subject = vcn_item.subject
vcn_appt.start = local_tz.localize(exchangelib.EWSDateTime(loc_start.year, loc_start.month, loc_start.day, loc_start.hour, loc_start.minute))
vcn_appt.end = local_tz.localize(exchangelib.EWSDateTime(loc_end.year, loc_end.month, loc_end.day, loc_end.hour, loc_end.minute))
vcn_appt.required_attendees = [exchangelib.Attendee(mailbox=exchangelib.Mailbox(email_address='attendee1@example.com), response_type='Accept')]
vcn_appt.required_attendees.append(exchangelib.Attendee(mailbox=exchangelib.Mailbox(email_address='attendee2@example.com'), response_type='Accept'))
vcn_appt.save()**

All attendees are connected to the same exchange server. Wen I .save() the item, it dutifully appears in the calendar of the sender, but does NOT appear in any of the attendees calendars or mailboxes. Upon inspection, I do see the intended attendees in the calendar item in Outlook, but no calendar item appears or is sent to the attendees.

Calendar items do not have a .send() method.

Any ideas?

I am using Python 2.7.11 on Windows 7.
My exchangelib version is 1.9.4
My Exchange version is: Build=15.1.845.36, API=Exchange2016, Fullname=Microsoft Exchange Server 2016

Thank you,

rjwiii

**Comment by ecederstrand** [comment]
You can't send a calendar item - that's only for Message items. You can:

1. Create a `CalendarItem`, save it, and attach it to a message that you send out.
2. `save()` the calendar item using the `send_meeting_invitations`argument (possible values are in `exchangelib.items.SEND_MEETING_INVITATIONS_CHOICES`). A meeting invitation will be sent to the attendees.

Please note that support for handling meeting invitations is very limited. See #89

**Comment by rjwiii** [comment]
Brilliant! I couldn't find any examples of that anywhere. Exactly what I was looking for.

I must say you are a very responsive and help developer. Your module is simply fantastic!

My only complaint is lack of documentation and good examples.

Thank you for your help!

rjwiii

**Comment by ecederstrand** [comment]
Thanks!

I'm sometimes struggling to keep up with issues and new features, so if you have time to improve the README or other documentation, I'll gladly pull in the changes.

**Comment by ecederstrand** [comment]
Docs for meeting invitation options to `.save()` added in https://github.com/ecederstrand/exchangelib/commit/2c57e100be99bf4c597b9720548c88750bf9a805
