### ISSUE TITLE
Add Python 2 backwards compatibility

### ISSUE THREAD

**Issue by wolfhechel** [ecederstrand/exchangelib#22]
I have a backport of this project supporting Python 2.7, would this be interesting to merge back?

The backporting involved:
- Updating dnspython3 to dnspython (latest supports both 2 and 3)
- Using future package for raise with and metaclass compatibility
- Using unicode type where applicable

If this is of interest I will open a PR, you can review the fork at https://github.com/TheFarm/exchangelib

**Comment by ecederstrand** [comment]
Hey, that's really cool! I'm bogged down with work this week but will review and merge as soon as I can.

**Comment by ecederstrand** [comment]
I reviewed your fork and added a few comments there. Apart form that, it looks good! If you create a pull request, I'll see if I can get your code into HEAD (haven't tried being on the receiving end of a PR before).

**Comment by wolfhechel** [comment]
I checked your comments and I'll fix those asap.

Before merging however I would like to setup tox to be able to run both Python 2 and Python 3 tests automatic.

Unfortunately I don't have a clean Exchange server I can run the tests against so at least 50% of the tests hasn't been run.

**Comment by ecederstrand** [comment]
+1 to tox. The landscape and travis files should also know about Python 2. Don't worry about the remaining tests, I have a test server and will handle any fallout.

**Comment by jayanth1991** [comment]
I'm very interested in this PR. Any update on the merge with upstream is much appreciated!

**Comment by wolfhechel** [comment]
Sorry I missed this your comment from before. The most recent codebase on my fork also implements querying on extended fields, requesting extended fields from find_items and adds support to cancel booked meetings, this code is not however covered by tests due to not having a test server to use.

The code is hosted in a separate branch but it does contain some additional Python 2 fixes regarding unicode compatibility that will need to be merged back. I'll look into fixing that this weekend and I'll drop a note here when it's done.

**Comment by jayanth1991** [comment]
Thanks @wolfhechel

**Comment by wolfhechel** [comment]
Alright so I pushed my unicode fixes back to the python2_backport branch, can you please test this @ecederstrand on your test server?

**Comment by ecederstrand** [comment]
Cool! No test failures with python3. If you create a PR, I'll review and merge as soon as I can.

**Comment by ecederstrand** [comment]
BTW, testing with python2.7 crashed on dependency installation because `setup.py` still has `Programming Language :: Python :: 3 :: Only`. This should be more specific. At least `2.7`, `3.4`, `3.5` should work.

**Comment by vikramarsid** [comment]
@ecederstrand Are you still considering to support python2_backport ? It is really good to have this support.

**Comment by ecederstrand** [comment]
Yes. I just need a PR for review that includes Python2 testing so we don't break support down the line.

I have no personal interest in Python2 but don't mind adding support.

**Comment by wolfhechel** [comment]
Sorry I've been away from this code, the problem with doing open source development during your regular work day as a consultant is that you rarely find the time to return to your code once you're done with the given task.

Does your CI have tox support that could be used to run the tests simultaneously?

**Comment by ecederstrand** [comment]
Ah, yes, I often find myself in the situation that fixing the problem at hand takes far less time than contributing a proper patch that includes clean code, a motivation, tests etc. I'm grateful that you're taking the time anyway so we can all benefit.

I signed up at travis-ci.org to have the tests done there. Travis reads https://github.com/ecederstrand/exchangelib/blob/master/.travis.yml so Python 2.7 needs to be added there. Locally, I run `python3 setup.py test`. I haven't used `tox` before, but it would be great if it's possible to set up local testing of all supported Python versions in a single command.

**Comment by ecederstrand** [comment]
@vikramarsid @wolfhechel I fixed the remaining issues in #46 and will merge as soon as the automatic checks have run.

**Comment by ecederstrand** [comment]
I fixed some fallout from the backport and released version 1.7.4 on PyPI. Thanks for your hard work @wolfhechel and @vikramarsid !

Some tests are failing for unrelated reasons. Apparently the test suite is fragile when tests are run in parallel on Travis-CI.
