### ISSUE TITLE
Forward messages

### ISSUE THREAD

**Issue by new2python** [ecederstrand/exchangelib#220]
Would it be possible to add forwarding functionality? I reviewed the source code but didn't seem to find what I was looking for. Basically looking to forward messages sitting in the inbox, or any other folder.

By the way, this is an awesome distribution, it has allowed me to move away from POP3 and IMAP, both of which my IT group refuse to support.

**Comment by ecederstrand** [comment]
I guess that would be possible, yes. Forwarding is basically just re-sending the message to different recipients and prepending the subject with `Fwd:`, so an `item.forward()` method would look something like:

```python
def forward(self, to_recipients, cc_recipients=None, bcc_recipients=None):
    self.item_id = None
    self.changekey = None
    self. to_recipients = to_recipients
    self. cc_recipients = cc_recipients
    self. bcc_recipients = bcc_recipients
    self.subject = 'Fwd: ' + self.subject
    self.send()
```

You could try this and see how it works. If it's ok, I'll add it as a helper method on the `Message` class.

**Comment by new2python** [comment]
Hi ecederstrand,
Appreciate your prompt response, I tested out your suggestion but ran into an error, copied further below. I'm still new to Python so you'll have to forgive my weak troubleshooting skills, but it appears that the state of the folder variable changes as it's passed from the send() method to the _create() method and then on to bulk_create() method. However, there is an assertion test in the send() method that checks that the folder value == None.

Traceback (most recent call last):
  File "L:\POS_Reporting\exchange_library_script\email_parser.py", line 56, in <
module>
    message.forward(to_recipients='ccholon@tng.com')
  File "C:\Users\svc_aadevbot2\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\exchangelib\items.py", line 534, in forward
    self.send()
  File "C:\Users\svc_aadevbot2\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\exchangelib\items.py", line 507, in send
    res = self._create(message_disposition=SEND_ONLY, send_meeting_invitations=s
end_meeting_invitations)
  File "C:\Users\svc_aadevbot2\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\exchangelib\items.py", line 176, in _create
    send_meeting_invitations=send_meeting_invitations)
  File "C:\Users\svc_aadevbot2\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\exchangelib\account.py", line 238, in bulk_create
    raise AttributeError("Folder must be None in send-ony mode")
AttributeError: Folder must be None in send-ony mode

**Comment by ecederstrand** [comment]
Ah, yes. The example I pasted was incomplete. I have updated it to something that works in a simple test.

**Comment by ecederstrand** [comment]
On a similar note, `Message` could have a `reply(reply_body, send_to_all=False, subject_prefix='Re:', keep_original_body=False, top_post=False)` method.

**Comment by ecederstrand** [comment]
@new2python Does the updated `forward()` method work for you?

I'm a bit hesitant to add this as a helper method since it's quite easy to implement yourself and users may easily have other things they want to do before forwarding the message, in which case the method is useless.

The same goes for a `reply()` method. I'm not sure we can make it flexible enough to be genuinely useful.

**Comment by new2python** [comment]
Hi Erik,

I agree, after taking a bit more time to study your library I realized that
it's actually more efficient to use or edit elements from an existing email
and encapsulate within a function for easier readability.

Appreciate you taking the time review.

Regards,
Curtis

**Comment by ecederstrand** [comment]
No problem. Closing until further notice.
