### ISSUE TITLE
Allow single query on multiple folders

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#224]
A use case would be filtering on the inbox and all subfolders of the inbox in one single query. Depends on #223 

One way of doing this is creating a new `FolderCollection` class which holds a resolved or unresolved list of folders (e.g. a concrete `some_folder.children` list or a `some_folder.walk()` generator) and implements the `get()`, `all()`, `filter()` and `exclude()` methods (extract these in a `SearchableMixIn` class?). `some_folder.all()` would just create a `FolderCollection` containing `some_folder` as the only member, and call `filter()` on that.

For this to work, `QuerySet` must first support multiple folders.

**Comment by fruitloop** [comment]
correct me if I'm wrong. At the moment it is not possible to filter over mails in subfolders?
I rather have to walk over them myself? With that I run into the problem, that when testing
I exceed the maximum number of API requests and get an error.

**Comment by ecederstrand** [comment]
Correct. You can't do something like:

```python
account.inbox.filter(is_read=False, include_subfolders=True)
```

You have to do:

```python
for subfolder in account.inbox.children:
    subfolder.filter(is_read=False)
```

**Comment by ecederstrand** [comment]
Fixed in https://github.com/ecederstrand/exchangelib/commit/848b968ae563b0751419689e3012c780051f01c0

You can now do:

```python
account.inbox.walk().filter(is_read=False)  # Folder and children
account.inbox.children.filter(is_read=False)  # Children only
account.inbox.glob('*').filter(is_read=False)  # A set of folders defined by a globbing pattern
```

And have results retrieved in a single (paged) request.
