### ISSUE TITLE
Deprecate verify_ssl arguments

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#225]
Disabling SSL verification is strongly discouraged and should not be this easy :-) Also, there are a huge number of connection customizations the user may want to do. `requests` suggests custom `HTTPAdapter` classes to handle this customization, and we support registering custom classes.

Let's remove the `verify_ssl` options in favour of:

```python
from requests.adapters import HTTPAdapter
from exchangelib.protocol import BaseProtocol

class NoVerifyHTTPAdapter(HTTPAdapter):
    def init_poolmanager(self, *args, **kwargs):
        kwargs['verify'] = False
        super(NoVerifyHTTPAdapter, self).init_poolmanager(*args, **kwargs)

BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
```

We can even provide `NoVerifyHTTPAdapter` for convenience.

Remember to keep `verify_ssl: False` support in the test suite.

**Comment by alpal** [comment]
Hi, just wondering if there is a way to check the version of the exchangelib library at runtime after import? I couldn't find one. The reason being I would like to be able to check if the version in use supports the above verify_ssl option or not, as we've got some divergent installs that have different versions of the pip library installed.

**Comment by ecederstrand** [comment]
No, but there should be. Please open a new issue to have `exchangelib.__version__` implemented.

In the meantime, I think your best option is a try/catch where you attempt to use the `verify_ssl` argument.
