### ISSUE TITLE
ErrorSchemaValidation - Exchange 2010

### ISSUE THREAD

**Issue by sdeshpande** [ecederstrand/exchangelib#227]
Hi Guys,

Can someone tell me how I can fix the below error I am getting while trying to connect to Exchange 2010

exchangelib.errors.ErrorSchemaValidation: The request failed schema validation.

Regards,
Saurabh

**Comment by ecederstrand** [comment]
Please capture the request and response XML that triggers this, and post it here. See https://github.com/ecederstrand/exchangelib#troubleshooting on how to get the XML.

**Comment by sdeshpande** [comment]
Sending you the xml file in PM

**Comment by sdeshpande** [comment]
`DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://owany.domainname.com/EWS/Exchange.asmx', Credentials('domainname\\username', '********'), True)'
DEBUG:exchangelib.transport:Getting service auth type for https://owany.domainname.com/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Requesting b'
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope
	xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
	xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
	xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
	<s:Header>
		<t:RequestServerVersion Version="Exchange2016" />
	</s:Header>
	<s:Body>
		<m:ResolveNames ReturnFullContactData="false">
			<m:UnresolvedEntry>domainname\\username</m:UnresolvedEntry>
		</m:ResolveNames>
	</s:Body>
</s:Envelope>' from https://owany.domainname.com/EWS/Exchange.asmx
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): owany.domainname.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'Content-Type': 'text/xml; charset=utf-8', 'Connection': 'keep-alive', 'Accept': '*/*', 'Accept-Encoding': 'compress, gzip', 'Content-Length': '461', 'User-Agent': 'python-requests/2.9.1'}
DEBUG:exchangelib.transport:Response headers: {'Server': 'Microsoft-IIS/7.5', 'WWW-Authenticate': 'Basic realm="owany.domainname.com", Negotiate, NTLM', 'Date': 'Fri, 01 Sep 2017 13:32:43 GMT', 'Set-Cookie':
'exchangecookie=a193bfe49a4e4ac0b8fce4cac10407b5; expires=Sat, 01-Sep-2018 13:32:44 GMT; path=/; HttpOnly', 'Content-Length': '0', 'X-Powered-By': 'ASP.NET'}
DEBUG:exchangelib.transport:realm: owany.domainname.com
DEBUG:exchangelib.transport:Auth type is NTLM
DEBUG:exchangelib.protocol:Server owany.domainname.com: Created session 26979
DEBUG:exchangelib.protocol:Server owany.domainname.com: Created session 8500
DEBUG:exchangelib.protocol:Server owany.domainname.com: Created session 18888
DEBUG:exchangelib.protocol:Server owany.domainname.com: Created session 21900
DEBUG:exchangelib.transport:Getting docs auth type for https://owany.domainname.com/EWS/types.xsd
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): owany.domainname.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:exchangelib.transport:Request headers: {'Accept': '*/*', 'Content-Type': 'text/xml; charset=utf-8', 'Connection': 'keep-alive', 'Accept-Encoding': 'compress, gzip', 'User-Agent': 'python-requests/2.9.1'}
DEBUG:exchangelib.transport:Response headers: {'Date': 'Fri, 01 Sep 2017 13:32:43 GMT', 'Server': 'Microsoft-IIS/7.5', 'Content-Length': '0', 'WWW-Authenticate': 'Basic realm="owany.domainname.com", Negotiate, NTLM', 'X-Powered-By': 'ASP.NET'}
DEBUG:exchangelib.transport:realm: owany.domainname.com
DEBUG:exchangelib.version:Asking server for version info
DEBUG:exchangelib.version:Getting https://owany.domainname.com/EWS/types.xsd with auth type HttpNtlmAuth
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): owany.domainname.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /EWS/types.xsd HTTP/1.1" 401 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /EWS/types.xsd HTTP/1.1" 200 24146
DEBUG:exchangelib.version:Request headers: {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'Keep-Alive', 'Authorization': 'NTLM TlRMTVNTUAADAAAAGAAYAGkAAAD2APYAgQAAAAgACABYAAAACQAJAGAAAAAAAAAAaQAAABAAEAB3AQAANoKJ4gYBsR0AAAAPjbVs6tFil0nIv5UH18HN9UxJQlJFTUFYcmVzaWxvYW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeTo0qDSDoOa2Ve88CWfW2AEBAAAAAAAA7HfeyiYj0wGAqbeuCimEbQAAAAACABAARQBDAEkAQwBMAE8AVQBEAAEAFgBRAFQAUwAtAEgAVABDAEEAUwAwADUABAAYAGUAYwBpAGMAbABvAHUAZAAuAGMAbwBtAAMAMABRAFQAUwAtAEgAVABDAEEAUwAwADUALgBlAGMAaQBjAGwAbwB1AGQALgBjAG8AbQAFABgAZQBjAGkAYwBsAG8AdQBkAC4AYwBvAG0ABwAIAOx33somI9MBBgAEAAIAAAAKABAAONE/5oSHcM2S2XbapG11gQAAAAAAAAAAL25+deYEn2SY5Y/YYPtHoQ==', 'User-Agent': 'python-requests/2.9.1'}
DEBUG:exchangelib.version:Response code: 200
DEBUG:exchangelib.version:Response headers: {'Vary': 'Accept-Encoding', 'Content-Type': 'text/xml', 'Server': 'Microsoft-IIS/7.5', 'Last-Modified': 'Wed, 06 Feb 2013 03:00:32 GMT', 'ETag': '"086b20164ce1:0"', 'Content-Encoding': 'gzip', 'Persistent-Auth': 'true', 'Date': 'Fri, 01 Sep 2017 13:32:44 GMT', 'Accept-Ranges': 'bytes', 'Content-Length': '24146', 'X-Powered-By': 'ASP.NET'}
DEBUG:exchangelib.version:Shortname according to https://owany.domainname.com/EWS/types.xsd: Exchange2010_SP2
DEBUG:exchangelib.protocol:Server owany.domainname.com: Waiting for session
DEBUG:exchangelib.protocol:Server owany.domainname.com: Got session 21900
DEBUG:exchangelib.util:Session 21900 thread 140278708918016: retry 0 timeout 120 POST'ing to https://owany.domainname.com/EWS/Exchange.asmx after 10s wait
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): owany.domainname.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:requests.packages.urllib3.connectionpool:"POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:requests.packages.urllib3.connectionpool:"POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 21900
Thread: 140278708918016
Auth type: 
<requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f952ab43da0>
URL: https://owany.domainname.com/EWS/Exchange.asmx
Verify: True
Allow redirects: False
Response time: 0.34256219799863175
Status code: 200
Request headers: {'Cookie': 'exchangecookie=c236671c149a44a58d9cefc966d50194; expires=Sat, 01-Sep-2018 13:32:44 GMT; path=/; HttpOnly', 'Content-Type': 'text/xml; charset=utf-8', 'Connection': 'Keep-Alive', 'Authorization': 'NTLM TlRMTVNTUAADAAAAGAAYAGkAAAD2APYAgQAAAAgACABYAAAACQAJAGAAAAAAAAAAaQAAABAAEAB3AQAANoKJ4gYBsR0AAAAPWZIf+v6Z0DK+sw9cXW9jCkxJQlJFTUFYcmVzaWxvYW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJqDLtrxUn0JlBhdI3W/LwEBAAAAAAAAVeTzyiYj0wEIdDILxQU4yQAAAAACABAARQBDAEkAQwBMAE8AVQBEAAEAFgBRAFQAUwAtAEgAVABDAEEAUwAwADUABAAYAGUAYwBpAGMAbABvAHUAZAAuAGMAbwBtAAMAMABRAFQAUwAtAEgAVABDAEEAUwAwADUALgBlAGMAaQBjAGwAbwB1AGQALgBjAG8AbQAFABgAZQBjAGkAYwBsAG8AdQBkAC4AYwBvAG0ABwAIAFXk88omI9MBBgAEAAIAAAAKABAAONE/5oSHcM2S2XbapG11gQAAAAAAAAAA7xLKjbrCrHVSL/750h6XCg==', 'Accept': '*/*', 'Accept-Encoding': 'compress, gzip', 'Content-Length': '465', 'User-Agent': 'python-requests/2.9.1'}
Response headers: {'Vary': 'Accept-Encoding', 'Content-Type': 'text/xml; charset=utf-8', 'X-AspNet-Version': '2.0.50727', 'Server': 'Microsoft-IIS/7.5', 'Transfer-Encoding': 'chunked', 'Persistent-Auth': 'true', 'Cache-Control': 'private', 'Date': 'Fri, 01 Sep 2017 13:32:44 GMT', 'Content-Encoding': 'gzip', 'X-Powered-By': 'ASP.NET'}
Request data: b'
	<?xml version="1.0" encoding="utf-8"?>
	<s:Envelope
		xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
		xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
		xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
		<s:Header>
			<t:RequestServerVersion Version="Exchange2010_SP2" />
		</s:Header>
		<s:Body>
			<m:ResolveNames ReturnFullContactData="false">
				<m:UnresolvedEntry>domainname\\username</m:UnresolvedEntry>
			</m:ResolveNames>
		</s:Body>
	</s:Envelope>'
Response data: 
	<?xml version="1.0" encoding="utf-8"?>
	<s:Envelope
		xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
		<s:Header>
			<h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="319"
MinorBuildNumber="2" Version="Exchange2010_SP2"
				xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
				xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
			</s:Header>
			<s:Body
				xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				<m:ResolveNamesResponse
					xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
					xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
					<m:ResponseMessages>
						<m:ResolveNamesResponseMessage ResponseClass="Error">
							<m:MessageText>No results were found.</m:MessageText>
							<m:ResponseCode>ErrorNameResolutionNoResults</m:ResponseCode>
							<m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
						</m:ResolveNamesResponseMessage>
					</m:ResponseMessages>
				</m:ResolveNamesResponse>
			</s:Body>
		</s:Envelope>

DEBUG:exchangelib.util:Session 21900 thread 140278708918016: Useful response from https://owany.domainname.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server owany.domainname.com: Releasing session 21900
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account None
DEBUG:exchangelib.services:Adding missing build number for account None
Before Account
DEBUG:exchangelib.folders:Root (root) created for username@domainname.com
DEBUG:exchangelib.services:Getting folder Root (root)
DEBUG:exchangelib.protocol:Server owany.domainname.com: Waiting for session
DEBUG:exchangelib.protocol:Server owany.domainname.com: Got session 21900
DEBUG:exchangelib.util:Session 21900 thread 140278708918016: retry 0 timeout 120 POST'ing to https://owany.domainname.com/EWS/Exchange.asmx after 10s wait
DEBUG:requests.packages.urllib3.connectionpool:"POST /EWS/Exchange.asmx HTTP/1.1" 500 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 21900
Thread: 140278708918016
Auth type: 
		<requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f952ab43da0>
URL: https://owany.domainname.com/EWS/Exchange.asmx
Verify: True
Allow redirects: False
Response time: 0.02001582400407642
Status code: 500
Request headers: {'Cookie': 'exchangecookie=c236671c149a44a58d9cefc966d50194', 'Content-Type': 'text/xml; charset=utf-8', 'Connection': 'Keep-Alive', 'Accept': '*/*', 'Accept-Encoding': 'compress, gzip', 'Content-Length': '1187', 'User-Agent': 'python-requests/2.9.1'}
Response headers: {'Content-Type': 'text/xml; charset=utf-8', 'X-AspNet-Version': '2.0.50727', 'Server': 'Microsoft-IIS/7.5', 'Transfer-Encoding': 'chunked', 'Cache-Control': 'private', 'Date': 'Fri, 01 Sep 2017 13:32:44 GMT', 'Content-Encoding': 'gzip', 'X-Powered-By': 'ASP.NET'}
Request data: b'
			<?xml version="1.0" encoding="utf-8"?>
			<s:Envelope
				xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
				xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
				xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
				<s:Header>
					<t:RequestServerVersion Version="Exchange2010_SP2" />
					<t:TimeZoneContext>
						<t:TimeZoneDefinition Id="Eastern Standard Time" />
					</t:TimeZoneContext>
				</s:Header>
				<s:Body>
					<m:GetFolder>
						<m:FolderShape>
							<t:BaseShape>IdOnly</t:BaseShape>
							<t:AdditionalProperties>
								<t:FieldURI FieldURI="folder:FolderClass" />
								<t:FieldURI FieldURI="folder:DisplayName" />
								<t:FieldURI FieldURI="folder:TotalCount" />
								<t:FieldURI FieldURI="folder:ChildFolderCount" />
								<t:FieldURI FieldURI="folder:UnreadCount" />
								<t:FieldURI FieldURI="folder:EffectiveRights" />
							</t:AdditionalProperties>
						</m:FolderShape>
						<m:FolderIds>
							<t:DistinguishedFolderId Id="root">
								<t:Mailbox>
									<t:EmailAddress>username@domainname.com</t:EmailAddress>
									<t:MailboxType>Mailbox</t:MailboxType>
								</t:Mailbox>
								<t:Mailbox>
									<t:EmailAddress>username@domainname.com</t:EmailAddress>
									<t:MailboxType>Mailbox</t:MailboxType>
								</t:Mailbox>
							</t:DistinguishedFolderId>
						</m:FolderIds>
					</m:GetFolder>
				</s:Body>
			</s:Envelope>'
Response data: 
			<?xml version="1.0" encoding="utf-8"?>
			<s:Envelope
				xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
				<s:Body>
					<s:Fault>
						<faultcode
							xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorSchemaValidation
						</faultcode>
						<faultstring xml:lang="en-US">The request failed schema validation: The element 'DistinguishedFolderId' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'Mailbox' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.</faultstring>
						<detail>
							<e:ResponseCode
								xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorSchemaValidation
							</e:ResponseCode>
							<e:Message
								xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The request failed schema validation.
							</e:Message>
							<t:MessageXml
								xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
								<t:LineNumber>1</t:LineNumber>
								<t:LinePosition>987</t:LinePosition>
								<t:Violation>The element 'DistinguishedFolderId' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has invalid child element 'Mailbox' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'.</t:Violation>
							</t:MessageXml>
						</detail>
					</s:Fault>
				</s:Body>
			</s:Envelope>

DEBUG:exchangelib.util:Got status code 500 but trying to parse content anyway
DEBUG:exchangelib.util:Session 21900 thread 140278708918016: Useful response from https://owany.domainname.com/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server owany.domainname.com: Releasing session 21900
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account username@domainname.com
WARNING:exchangelib.services:EWS https://owany.domainname.com/EWS/Exchange.asmx, account username@domainname.com: Exception in _get_elements: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 73, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 147, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 180, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 203, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorSchemaValidation: The request failed schema validation.

Traceback (most recent call last):
  File "exchange.py", line 19, in 
			<module>
    access_type=DELEGATE)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/account.py", line 83, in __init__
    self.root = Root.get_distinguished(account=self)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/folders.py", line 410, in get_distinguished
    shape=shape
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 875, in call
    shape=shape,
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 73, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 147, in _get_response_xml
    res = self._get_soap_payload(soap_response=soap_response_payload)
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 180, in _get_soap_payload
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 203, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorSchemaValidation: The request failed schema validation.
DEBUG:exchangelib.protocol:Server owany.domainname.com: Closing sessions`

**Comment by ecederstrand** [comment]
Hmm. Somehow, the `DistinguishedFolderId` element got *two* `Mailbox` child elements, which is invalid. I have no idea how that is possible, but clearly we have a bug somewhere.

**Comment by sdeshpande** [comment]
Thank you. Let me know if I can be of any assistance.

**Comment by MatthewClarkMay** [comment]
Also having same issues on my end. Trying to debug the problem but not very familiar with this library yet.

**Comment by ecederstrand** [comment]
Downgrading to 1.9.5 should fix this for now, until the bug is fixed.

**Comment by sdeshpande** [comment]
Got it. I will try this and report back.

**Comment by sdeshpande** [comment]
Downgrading to 1.9.5 actually worked. Thank you very much.

**Comment by chhitesh** [comment]
I faced similar issue while extracting emails. I am wondering if this issue still exist in the current version.

**Comment by ecederstrand** [comment]
The problem reported in this issue has been fixed. If you have problems with the current version of exchangelib, please open a new issue and add details there.
