### ISSUE TITLE
Autodiscover redirects to same host may be treated as uniuqe

### ISSUE THREAD

**Issue by SamCB** [ecederstrand/exchangelib#228]
The method [`autodiscover.py:_get_auth_type_or_raise()`](https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover.py#L261) doesn't properly handle urls which redirect to the same host (mainly ones that redirect to their own `www`), but also have a valid `canonical_hostname`.

```python
# ...
        canonical_hostname = _get_canonical_name(redirect_hostname)
        if canonical_hostname:
            log.debug('Canonical hostname is %s', canonical_hostname)
            redirect_hostname = canonical_hostname
        # Try the process on the new host, without 'www'. This is beyond the autodiscover protocol and an attempt to
        # work around seriously misconfigured Exchange servers. It's probably better to just show the Exchange
        # admins the report from https://testconnectivity.microsoft.com
        if redirect_hostname.startswith('www.'):
            redirect_hostname = redirect_hostname[4:]
        if redirect_hostname == hostname:
            log.debug('We were redirected to the same host')
            raise_from(AutoDiscoverFailed('We were redirected to the same host'), e)
# ...
```

If a `canonical_hostname` exists, then `redirect_hostname` is no-longer the original, even if they point to the same thing. From what I can tell, all this needs is the check for `redirect_hostname` equality to be stuck in front of the `canonical_hostname`, but I'm not too sure about autodiscover, so there may be more to this.

**Comment by SamCB** [comment]
I have a potential fix to demonstrate this in my repository fork: https://github.com/SamCB/exchangelib/tree/change_redirect_order

**Comment by ecederstrand** [comment]
Thanks for your analysis!

I'm having trouble following your reasoning. Can you post a simple example of the redirect sequence you're having issues with, and how you would like it to be instead? Some hostnames or URLs, where they were collected from, and what the end result is before and after the proposed change, would be great, to document this change.

I've spent endless hours debugging and working around autodiscover bugs and misconfigurations, so I'd prefer a solid case before changing anything here. It's sometimes a tradeoff between following the spec and supporting broken servers, and it's almost impossible to test everything.

**Comment by SamCB** [comment]
No problem. I understand that Autodiscover is a fickle beast. If what we have is an outlier or something wrong with our clients outside the scope of this library we can figure out some workaround ourselves.

Several of our clients have a setup like this (the ones with problems are all using office365 with their own domain names):

1. We have:
    ```python
    hostname="example.com"
    ```
2. The server is setup to immediately redirect to `"www.example.com"`. So
    ```python
    redirect_hostname="www.example.com"
    ```
3. The hostname also has a CNAME:
    ```python
    canonical_hostname="xyz.example.org"
    ```
4. Which now means:
    ```python
    redirect_hostname="xyz.example.org"
    ```
5. Which means, that:
    ```python
    "example.com" != "xyz.example.org"
    # i.e.
    hostname != redirect_hostname
    ```
    so this is considered a proper redirect, and raises a `RedirectError` instead of being a redirect to the same host, (from what we can tell we think this is what it should be) and raising an `AutoDiscoverFailed`.

When we tested the changes we made in [my fork](https://github.com/ecederstrand/exchangelib/compare/master...SamCB:change_redirect_order) the `_get_auth_type_or_raise()` method threw an `AutoDiscoverFailed` which meant the autodiscover process attempted the next valid address, instead of running down the rabbit hole (which for one of our clients meant trying to find the Autodiscover endpoints among several `wix.com` and aws domains) before failing completely.

If this is a legitimate cause for change I don't expect my fork to be the solution, more of a demonstration of it working in one case. I'd assume there are other services that expect CNAMEs to be part of the whole redirect cycle, so we'd still need to follow them. I assume that it might be required to try both methods. We firstly try the original method, if we get to the end and it's an error, we roll back and make sure there aren't any internal redirects along the way, and raise up if that's the case. I'm not sure however, if that is feasible with the current solution.

**Comment by ecederstrand** [comment]
I think there's some leeway in the spec regarding this. From https://msdn.microsoft.com/en-us/library/hh352638(v=exchg.140).aspx:

```
    If the redirection URL is valid, the client tries the URL and then does one of the following:
        If the attempt succeeds, the client proceeds to step 5.
        If the attempt fails, the client proceeds to step 4.
    If the redirection URL is not valid, the client proceeds to step 4.
```

where step 4 is getting the canonical name from DNS. There is no mention of how to decide if a redirection URL is valid.

Looking at the current code, we risk looking up the canonical name from `www.example.com` which is always going to be a bad idea. So something needs to be changed. But if I read your code correctly, it always fails if the redirect hostname starts wih 'www', which I think is incorrect. In this case, we should look up the canonical name on the original hostname before failing.

Maybe we can change the code to:
   1. look at the redirect URL
   2. check if the URL looks good (currently meaning 'hostname does not begin with www', but we could expand that)
   3a: If the URL is good, continue with that
   3b. If not, look up canonical name

**Comment by SamCB** [comment]
Hmmm. If that's the spec then the method I proposed is definitely out. I guess the real problem is that the canonical name could be the right thing (regardless of whether or not the redirect is just `www.`) but it could also be a red herring because we're accidentally looking at something set up to be a webserver.

I think what might actually be needed is to follow the CNAME process down as we do. If we find out that it's a dead end, we need to make sure that an `AutoDiscoverFailed` gets thrown so we catch it in [`_try_autodiscover()`](https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover.py#L233). From there we'll try the `autodiscover.example.com/...` endpoint. From what I can tell it doesn't appear to do that.

**Comment by ecederstrand** [comment]
Hi @SamCB Just to let you know it'll be some days before I can go deeper into this ($work calling), but in general I'm willing to go pretty far so support broken setups. And you may be correct that this is simply a bug in exchangelib.

The link I posted previously looks a little dated. There's a more recent description of Autodiscover here: https://msdn.microsoft.com/en-us/library/office/jj900169(v=exchg.150).aspx

**Comment by SamCB** [comment]
That's fine. I'd try exploring a bit and making a proper PR on this, but I'm a bit tied up as well. My hack has got it working for the accounts that we've been having problems on, so I'm going to stick to that for the short term until I can dedicate some proper time to the problem.

I guess I'll also have to find some time some day to go through and actually understand the Autodiscover process. Thanks for those links.

**Comment by ecederstrand** [comment]
Hi @SamCB Can you post the particular domain you're having issues with, and the domain you expected to have it resolved to? That would make debugging a bit easier. An email is fine if you're unhappy with posting it publicly.

**Comment by ecederstrand** [comment]
Hi @SamCB I'm currently debugging the autodiscover code for other reasons. Would it be possible for you to post or email me the troublesome domain? That way I can try to fix autodiscover for your domain also.

**Comment by ecederstrand** [comment]
A completely rewritten autodiscover implementation was added in https://github.com/ecederstrand/exchangelib/commit/d0a7c1dfed7937f1dad89a01c4b983009ddcdd4a.

I'm closing this issue as obsolete. Feel free to reopen a new issue if you have autodiscover problems with the new implementation.
