### ISSUE TITLE
Creating a room

### ISSUE THREAD

**Issue by poskadesign** [ecederstrand/exchangelib#229]
Hi, first a congratulations for this magnificent project is in order!

This is not an issue per se but could anyone point out to me how to create a room (and a room list) by using the exchangelib? Are rooms a "folder" like calendar and contacts?

Thank you in advance for any help.

**Comment by ecederstrand** [comment]
I'm not sure this is possible via EWS. A Room is basically a special account, and Exchange accounts cannot be created via EWS. You need to to this via PowerShell instead, if you want to do this programmatically.

**Comment by poskadesign** [comment]
Thanks for the quick reply. Do you think it is possible to automate this process without a PowerShell (running on Linux)?

**Comment by ecederstrand** [comment]
Since Exchange is Windows-only software, you would have to create a custom endpoint on the Exchange server which exposes the functionality you need to the Linux machine. See e.g. https://stackoverflow.com/questions/19666200/how-can-i-create-an-exchange-mailbox-in-exchange-2010-from-python-perl

**Comment by poskadesign** [comment]
Thanks a lot!
