### ISSUE TITLE
Meeting invites & RTF bodies

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#231]
Here's the kicker: You can't use HTML in the bodies of meetings & appointments. Only plain text & RTF are allowed. Through VBA, I am able to dump the RTF, but it comes back byte encoded and unreadable.

I know there is an HTML helper. Is there also an RTF helper? Any support for RTF in Exchangelib?

Thanks,

rjwiii

**Comment by ecederstrand** [comment]
By "HTML helper", do you mean the `text_body` field? That one is a field generated server-side by Exchange, not something implemented locally in exchangelib.

It's not entirely clear to me what you're asking for. Do you want something that can strip RTF markup from `CalendarItem.body`?

Also, how did you conclude that you can't use HTML in the body of meetings? We have the `HTMLBody` class to tell EWS that `Item.body` should be interpreted as HTML. Does that not work for you?

**Comment by rjwiii** [comment]
When I started this project, I was using VBA. Since I want this project not to rely on having the Office Object Model installed, I switch to using exchangelib instead. When I was working in VBA, I could only return bodies in RTF or text for appointments/meetings. To set the appointment/meeting body with any sort of formatting, I had to use the Word Editor  methods & properties.

Here are a couple of links that discuss this:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/469a17dc-4f73-4243-b182-75e2677d8f54/html-in-outlook-meeting-body?forum=vsto

http://www.outlookcode.com/threads.aspx?forumid=4&messageid=31257

Micro$oft doesn't make things easy ... :(

Thanks,

rjwiii

**Comment by ecederstrand** [comment]
Ok, so you have existing calendar items with RTF-formatted `body` values that you need to work with? In that case, you should go looking for a Python RTF parser/emitter. Otherwise, just continue your project with an HTML body.

I just did a quick test in Office365 where I created a calendar item with some markup in the body field. This gets stored as HTML in `item.body` and is displayed correctly again by Office365, so I assume HTML is the default for newer versions of Exchange.

**Comment by rjwiii** [comment]
Can you post your code?

I will give it a try,

Thanks

rjwiii

**Comment by ecederstrand** [comment]
I created a calendar item via Office365, and added some text in bold and italics in the body using the online text editor. Then I used exchangelib to fetch the `body` field via EWS:

```python
>>> item = a.calendar.get(subject='HTML test item')
>>> print(item.body)
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css" style="display:none;"><!-- P {margin-top:0;margin-bottom:0;} --></style>
</head>
<body dir="ltr">
<div id="divtagdefaultwrapper" style="font-size:12pt;color:#000000;font-family:Calibri,Helvetica,sans-serif;" dir="ltr">
<p><b>sefsdsdf<i>sdfsdsdf</i>sdfsdsdf</b>sdfsfsdf'</p>
</div>
</body>
</html>
```

**Comment by rjwiii** [comment]
I'm going the other way ... I'm attempting to format the body via python & exchangelib ... is that possible?

**Comment by rjwiii** [comment]
I just tested exchangelib.HTMLbody ... and it WORKED! Didn't think it would ...

Thanks,

rjwiii

**Comment by ecederstrand** [comment]
No problem. For the sake of anyone else stumbling over this issue, here's how to use `HTMLBody` to tell EWS it should interpret the body as HTML instead of just text that happens to look like HTML:

```python
form exchangelib import CalendarItem, HTMLBody

item = CalendarItem(...)
item.body = HTMLBody('''\
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css" style="display:none;"><!-- P {margin-top:0;margin-bottom:0;} --></style>
</head>
<body dir="ltr">
<div id="divtagdefaultwrapper" style="font-size:12pt;color:#000000;font-family:Calibri,Helvetica,sans-serif;" dir="ltr">
<p><b>sefsdsdf<i>sdfsdsdf</i>sdfsdsdf</b>sdfsfsdf'</p>
</div>
</body>
</html>''')
item.save()
```
