### ISSUE TITLE
Querying Issue: Limitation on number of items queried and appended to a list

### ISSUE THREAD

**Issue by manonfire86** [ecederstrand/exchangelib#240]
Hi,

When I attempt to perform a basic loop to pull the items from the following query into a list, the query times out between items 100-200. The inbox contains approximately 300k emails and I would like to be able to pull all of this data and eventually convert it to a dataframe. Can you please elaborate on the limitations of the query system? Thank you.

```python
author_items = inbox.all().values('author')
inboxlength = len(author_items)
authors = []
for i in range(inboxlength):
    authors.append(author_items[i].values())
```

**Comment by ecederstrand** [comment]
You're missing that `author_items` is a QuerySet, not a `list`. So when you do `author_items[n]`, it will fetch at least `n` items, and that's done `inboxlength` times. That's going to hurt when you have 300.000 items in the folder :-)

To do what you're doing, you should do something like this instead:

```python
inbox_length = inbox.total_count  # Will get you the number without counting each item
# values_list(..., flat=True) returns only the requested value in a generator
# .iterator() disables internal caching of the QuerySet, to save some memory
authors = list(inbox.all().values_list('author', flat=True).iterator())
```

**Comment by manonfire86** [comment]
Thank you! :)
