### ISSUE TITLE
Creating a calendar item with location set to a room

### ISSUE THREAD

**Issue by steponas-darius** [ecederstrand/exchangelib#245]
Hi,

Firstly, thanks for the magnificent library. After using it for a couple of months, I ran into a problem while trying to create a calendar item and setting the event location to a room. I tried this:

```
CalendarItem(
    start=pytz.timezone('Europe/Vilnius').localize(EWSDateTime(2017, 9, 14, 12, 0)),
    end=pytz.timezone('Europe/Vilnius').localize(EWSDateTime(2017, 9, 14, 13, 0)),
    subject='My cool meeting',
    account=account,
    folder=account.calendar,
    required_attendees=[
        Attendee(mailbox=Mailbox(email_address='myroom@me.onmicrosoft.com'),
                 response_type='Accept')
    ]
).save()
```

but this leaves the `location` field empty. So how do you correctly set the event location to a room.

Any help would be greatly appreciated.

**Comment by ecederstrand** [comment]
The `location` field is a simple string in EWS. This is separate from the `required_attendees` and there is no connection between the two.

**Comment by ecederstrand** [comment]
Closing. Please reopen if you still have issues with this :-)
