### ISSUE TITLE
Need verify_ssl, fix not working

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#247]
UPDATE: I've been trying some of your suggestions from issue #215 and so far nothing has worked. The certifi package isn't working on Windows. Could you possibly expose the "requests" package verify= parameter so I can to a verify="path to cert file"?

I followed your work-around and it's not working. Traceback is below:

No handlers could be found for logger "exchangelib.protocol"
Traceback (most recent call last):
  File "C:/Users/M82129/Git/Vendor_Circuit_Notification/vcnmain.py", line 294, in <module>
    ex_config = exchangelib.Configuration(server="xxxxx.xxxxx.com", credentials=my_creds)
  File "C:\Python27\lib\site-packages\exchangelib\configuration.py", line 46, in __init__
    version=version
  File "C:\Python27\lib\site-packages\exchangelib\protocol.py", line 177, in __call__
    raise e
exchangelib.errors.ErrorNameResolutionNoResults: No results were found.

Here is what I have for the work-around in code:

exchangelib.protocol.BaseProtocol.HTTP_ADAPTER_CLS = exchangelib.protocol.NoVerifyHTTPAdapter

If I can't fix this, I will have to downgrade.

Thanks,

rjwiii

**Comment by ecederstrand** [comment]
Ah, that's one is a different issue, fixed in https://github.com/ecederstrand/exchangelib/commit/a171c6ff3b0a1350fa76a1632565bed8b02c2f8f

**Comment by ecederstrand** [comment]
I'm not going to expose the verify adapter again because subclassing `HTTPAdapter` is a more general and flexible solution. The `NoVerifyHTTPAdapter` solution works (I'm using it myself) but you just hit a different bug.

**Comment by ecederstrand** [comment]
Should be fixed in version 1.10.2

**Comment by rjwiii** [comment]
That fixed it! Thanks.

rjwiii
