### ISSUE TITLE
Storing ItemAttachments to disk 

### ISSUE THREAD

**Issue by ninSmith** [ecederstrand/exchangelib#248]
Is it possible to convert an ItemAttachments to a FileAttachments ?  

People send email (.msg) as attachment and I would like to store them. However ItemAttachments don't have a ```content``` attribute while FileAttachments do.

Thx

**Comment by ecederstrand** [comment]
And `ItemAttachment` has an `item` attribute which returns a normal `Item` instance (in the case of an attached email, this would be a `Message` instance). You need to decide how to store this instance as text, assuming you want to write to disk. Probably, the `Message.mime_content` field is what you're looking for to achieve this.

**Comment by ninSmith** [comment]
It is exactly what I need !

For information, ```Message.mime_content``` gives a nice ```.eml``` :)

Thanks very much !
