### ISSUE TITLE
get_folder_by_name() deprecated

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#249]
In my script, once I am done processing an incoming e-mail, I set **is_read = True** and move it to a root folder I created in Outlook called "Processed":

`email.move(to_folder=acct.root.get_folder_by_name("Processed"))`

According to the warning: 

C:\Python27\lib\site-packages\exchangelib\folders.py:156: UserWarning: The get_folder_by_name() method is deprecated. Use "[f for f in self.walk() if f.name == name]" or "some_folder / 'Sub Folder'" instead, to find folders by name.
  warnings.warn('The get_folder_by_name() method is deprecated. Use "[f for f in self.walk() if f.name == name]" '

How would I get to a root folder I created?

Thanks!

rjwiii

**Comment by ecederstrand** [comment]
This is documented in the CHANGELOG, and there are instructions on new-style folder navigation in the README: https://github.com/ecederstrand/exchangelib#folders

However, Travis is complaining that the forward slash navigation doesn't work on Python2.7 (see https://travis-ci.org/ecederstrand/exchangelib/jobs/275360428) so right now please keep using `get_folder_by_name()` until his is fixed.

**Comment by ecederstrand** [comment]
Python 2.7 issue fixed in https://github.com/ecederstrand/exchangelib/commit/028ed696489f096d764921d93fa3a06551d68624
