### ISSUE TITLE
Extended properties

### ISSUE THREAD

**Issue by amille44420** [ecederstrand/exchangelib#25]
Hi, I read as much as possible from the source code to see how are handled extended properties. But I didn't see any explicit way to add extended properties to an item model to retrieve our own extended properties from EWS and operate with those.

For now, with the latest changes, this is the way I'm doing it

``` python
class CustomProperty(ExtendedProperty):
    property_guid = 'my-guid'
    property_name = 'name'
    property_type = 'String'

additional_properties = {
    'custom_property': (CustomProperty, CustomProperty),
}

CalendarItem.ITEM_FIELDS.update(additional_properties)

CalendarItem.ORDERED_FIELDS += tuple(additional_properties.keys())
```

Is there a way I missed ? If there's not, I believe it would be a great feature to have a better and more explicit way for it. Because, for example, for now to use the latest version, I've to be very careful with the exchangelib updates to keep my extended properties available.

**Comment by ecederstrand** [comment]
Thanks for the heads up! I'm not very familiar with extended properties and how developers use them. I've only had the need for an `extern_id` attribute in `CalendarItem` objects, which is implemented as an extended property (see `exchangelib.folders.ExternId`) but it's not easily extendable.

If you can come up with an easier and more intuitive way of handling custom extended properties, I'm happy to review a pull request.

**Comment by amille44420** [comment]
Ok, I'll try to give it a try on my spare time

**Comment by ecederstrand** [comment]
I think inheriting `ExtendedProperty` as you did is a reasonable approach. Maybe what is missing is just a class method on `Item` to register the custom property? Something like:

```
class CustomProperty(ExtendedProperty):
    property_guid = 'my-guid'
    property_name = 'name'
    property_type = 'String'

CalendarItem.register('custom_property', CustomProperty)
```

where `register()` would handle the details in your example above. Afterwards, the 'custom_property' attribute would be available like any other attribute.

**Comment by amille44420** [comment]
I thought of this solution too but is it good to make extended property global ? Maybe for now this the easiest solution to apply. 

I mean, by doing it that way, the extended properties will be shared for all `CalendarItem`.  We may want to have some extended properties on one folder and different extended properties on another, both being calendar folders. We could meet the same issue if we want to use different extended properties depending of the account.

However there's currently a huge use of static/class methods. So my way of thinking bring huge changes. I studied how [ews-java-api](https://github.com/OfficeDev/ews-java-apil) does. They inform a `PropertySet` to define which properties we wanna retrieve.  I believe it to be a good solution because it's way more explicit to see what we're requesting and that way the developers are free to put anything they want into this set. Though it leads to a lot of changes too.

**Comment by ecederstrand** [comment]
Retrieving properties explicitly is easy with this exchangelib. Just do:

`my_calendar.filter(...).only('start', 'end', 'my_custom_property')`

If extended properties are primarily used per-folder, then `register()` should be a method on a `Folder` instance. And you are right, that does not work well with the current code. I'll have a look in the next few days how this can be done cleanly.

**Comment by ecederstrand** [comment]
Revisting this, I now have a hard time seeing how the `register()` on a folder could work. As far as I understand, an extended property is something you register globally on the server, but the value is something that is attached to individual items. Thus, extended properties is not something that you can automatically attach to items in a folder. A folder may contain a mix of items, some of which have a certain extended property, ans some that don't. If you move an item from one folder to another, the new folder knows nothing about extended properties on the moved item.

I think the only sane approach here is to place the `register()` on the `Item` class. After calling `register()`, all new items would get the custom attribute, but right now I can't see any severe downsides to that. Calling `deregister()` would possibly remove access to that attribute on existing item instances, though.
