### ISSUE TITLE
send mail with embedded images in html

### ISSUE THREAD

**Issue by mthlvt** [ecederstrand/exchangelib#250]
Is it possible to send a message with embedded images (not links)?
Could you give an example please?

Thanks

**Comment by ecederstrand** [comment]
Embedding images and other MIME content in email messages is not specific to exchangelib. https://docs.python.org/3.6/library/email.contentmanager.html should get you going in the right direction.

**Comment by mthlvt** [comment]
Thanks @ecederstrand, I got it working :thumbsup:

If anyone is interested here are some gists to save a couple minutes:

Load the image file and create the attachment:
```
import os
logoname = 'logo.png'
fp = open(logoname, 'rb')                                                    
logoimg = FileAttachment(name=logoname, content=fp.read())
fp.close()
````
refer to the image in the HTML body:
` <img src="cid:logo.png">`

attach the image to a message item
```
m.attach(logoimg)
```

**Comment by ecederstrand** [comment]
Cool, thanks for the example!

**Comment by Eric-Hua** [comment]
if you have some problem,try belowlogo_filename = 'aaa.jpeg'
``` python
    with open(logo_filename, 'rb') as f:
        my_logo = FileAttachment(name=logo_filename, content=f.read())
    my_logo.is_inline = True
    my_logo.content_type = "GIF/Image"
    my_logo.content_id = logo_filename
    m.attach(my_logo)
```

**Comment by guptasakshi01** [comment]
<img src="cid:logo.png">
Adding image source to html body is not displaying image in email. Its giving X sign.
@mthlvt  Can you please help on this ??

**Comment by mthlvt** [comment]
@guptasakshi01 please post more code to check your issue.
In the mail, do you see the file as an attachment or nothing attached?

**Comment by douglaspsadm** [comment]
It's work fine for outlook, but gmail don't show the image. can you please help me?

`
nome1 = 'teste.png'
with open(nome1, 'rb') as fp:
    logoimg2 = ex.FileAttachment(name=nome1, content=fp.read(), is_inline=True)

body=ex.HTMLBody( f'<img src="cid:{nome1 }" >'

m.attach(logoimg2)
`

**Comment by guptasakshi01** [comment]
@mthlvt  

using exchanglib library of python

logo = "icon.png"
with open(logo, 'rb') as fp:
     logoimg2 = ex.FileAttachment(name=logo, content=fp.read(), is_inline=True)

body = HTMLBody('''<html>
<body>
<img src="cid:logo.png">
</body>''')

m = Message(account=account,subject="testing",body=body,to_recipients=[Mailbox(email_address='********')])
m.send()

**Comment by guptasakshi01** [comment]
@mthlvt 
using exchanglib library of python

logo = "icon.png"
with open(logo, 'rb') as fp:
logoimg2 = FileAttachment(name=logo, content=fp.read(), is_inline=True)

body = HTMLBody('`<html><body><img src="cid:logo"></html></body>`')

m = Message(account=account,subject="testing",body=body,to_recipients=[Mailbox(email_address='********')])
m.send()

**Comment by douglaspsadm** [comment]
@guptasakshi01
Replace  cid:logo for cid:icon.png.

Canal be this way:
body = HTMLBody('`<html><body><img src="cid:icon.png"></html></body>`')

Or this way

body = HTMLBody(f'<html><body><img src="cid:{logo}"></html></body>')

Anyeay, Cid is the nane of the file.

**Comment by guptasakshi01** [comment]
###### Its not working 
In place of icon.png i am giving path of image file
`body = HTMLBody('<html><body><img src="cid:icon.png"></html></body>')`
###### Its giving error:-
`body = HTMLBody(f'<html><body><img src="cid:{logo}"></html></body>')`
  File "<stdin>", line 1
    body = HTMLBody(f'<html><body><img src="cid:{logo}"></html></body>')
                                                                      ^
SyntaxError: invalid syntax

**Comment by ecederstrand** [comment]
@guptasakshi01 

Your Python version does not support [f strings](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498). Do this instead:

```python
body = HTMLBody('<html><body><img src="cid:{}"></html></body>'.format(logo))
```

**Comment by douglaspsadm** [comment]
@guptasakshi01 
On first case, don't give the Path, Just the filename. Cid:img.png

**Comment by ecederstrand** [comment]
@douglaspsadm I would suggest creating an email in Gmail where the inline image actually works, then send it to an Exchange-hosted email account. If the email also works in Outlook, then use exchangelib to check what the HTML body looks like. That will tell you which email format Gmail accepts.

**Comment by guptasakshi01** [comment]
@douglaspsadm  from which path it picks file ??

**Comment by douglaspsadm** [comment]
@guptasakshi01
i'll try explain on your code :( my english is bad.
`
#logo = path file for your img.

logo = "c:\\users...\\icon.png"
with open(logo, 'rb') as fp:
logoimg2 = FileAttachment(name=logo, content=fp.read(), is_inline=True)

#now the img nedd be attach on email, and call the cid with the file name.

body = HTMLBody('`<html><body><img src="cid:icon.png"></html></body>`')

m = Message(account=account,subject="testing",body=body,to_recipients=[Mailbox(email_address='********')])

m.attach(logoimg2 )

m.send()
`

if don't show again i can try help :) just call

**Comment by guptasakshi01** [comment]
@douglaspsadm while doing it this way its attaching image file to email instead of embedding it :( :(

**Comment by douglaspsadm** [comment]
@guptasakshi01 well, i think you have my problem too hahaha
if you send this email for a outlook account the img will embed inline, if you send for gmail or yahoo mail the img dont show inline. 
I'm trying solve this have like 10 days =\
Look this page:
https://sendgrid.com/blog/embedding-images-emails-facts/

**Comment by guptasakshi01** [comment]
@douglaspsadm  did you try using base64 encoding ??

**Comment by douglaspsadm** [comment]
@guptasakshi01 i try, it not work, you can try, maybe i do something wrong :(

`
import base64

data_uri = open('/path/to/image/image.png', 'rb').read().encode('base64').replace('\n', '')

img_tag = '<img src="data:image/png;base64,{0}" width="400" height="275">'.format(data_uri)

# or this way

mage = open('/path/to/image/image.png', 'rb')
image_read = image.read()
image_64_encode = base64.encodestring(image_read)
image_64_decode = base64.decodestring(image_64_encode)

img_tag = '<img src="data:amer/jpg;base64,{0}" width="400" height="275">'.format(image_64_decode)

`

**Comment by guptasakshi01** [comment]
I have tried and it worked for me using base64 encoding,
But I am not able to see image in Web App but image is like "X" in Desktop Application.

**Comment by douglaspsadm** [comment]
@guptasakshi01 for me using base64 just show a "X" in all places.
what code you used?

**Comment by guptasakshi01** [comment]
Try this
```
body= HTMLBody('''<html>
<img src="data:image/png;base64,encodinghere">
<p>
Hi test, <br />
<br />Testing Body<br />
</p>
<img src="data:image/png;base64,encodinghere">
</body>
</html>
''')
```

You can try generating base64 encoding using https://www.motobit.com/util/base64-decoder-encoder.asp

please tell me how it worked in outlook client
For me its not working

**Comment by douglaspsadm** [comment]
@guptasakshi01  don't work on outlook and gmail. Just show the 'X'

**Comment by arturio333** [comment]
What was the solution?

**Comment by abdulrahman004** [comment]
I had the same problem trying to embed images sending to gmail. Then I tried what @ecederstrand  suggested on a different thread. Sent an email from gmail with an embedded image to an exchange account and inspected the body. 

Apparently gmail uses this tag 
<img data-imagetype="AttachmentByCid" src="cid:id">

Using the above tag with the `FileAttachment` with the content-id parameter set to `id` worked in getting inline images for gmail
