### ISSUE TITLE
Filtering by itemId or changekey

### ISSUE THREAD

**Issue by cmannfolk** [ecederstrand/exchangelib#251]
I would like to modify and delete calendar items based on their itemId or changeKey, which are more likely to be unique than the subject of an event. Is there an easy way to implement the filtering search for these portions of a calendarItem?

Thanks!

**Comment by ecederstrand** [comment]
If you know the `item_id` and `changekey` values, you can use `Account.fetch()` to bulk fetch multiple items at a time. It takes a list of `(item_id, changekey)` tuples and returns a generator.

It you always only fetch one item, `account.inbox.get(item_id=..., changekey=...)` is shorter and more intuitive.
