### ISSUE TITLE
moving emails into custom folder at inbox

### ISSUE THREAD

**Issue by super4bike** [ecederstrand/exchangelib#252]
hi,
i like to move some emails from the inbox into a subfolder of this inbox, named test-abc.
The script below is able to move into standard folder "trash", but how works it into a non standard folder like my "test-abc" folder?
And how can i check if the folder "test-abc" exists?

> from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount,\
>     EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
>     Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
>     HTMLBody, Build, Version
> 
> 
> credentials=Credentials(username=username, password=password)
> version = Version(build=Build(15 ,0 ,12 ,34))
> config = Configuration(server=server,credentials=credentials, version=version, auth_type=NTLM)
> 
> account = Account(primary_smtp_address=smtp_adress, config=config,
>                   autodiscover=False, access_type=DELEGATE)
> # clear cache and refresh to the folder root
> account.root.refresh()
> unread = account.inbox.filter()   # returns all mails
> > # finding all folders in the email inbox
> for i in account.inbox.get_folders():
># output of all standard and my created folders
>     print(i)
> for item in unread:
> # move all to trash
>     item.move(account.trash)
Thank you for supporting
super4bike

**Comment by ecederstrand** [comment]
I'm glad you asked! I just made this a lot easier two days ago in v1.10.2.

```python
from exchangelib.errors import ErrorFolderNotFound

try:
    abc_folder = account.inbox / 'test-abc'
    item.move(to_folder=abc_folder)
except ErrorFolderNotFound:
    print('Uh-oh. Subfolder not found!')
```

Further documentation at https://github.com/ecederstrand/exchangelib#folders

**Comment by ecederstrand** [comment]
If you have a large amount of items to move, you can speed up the process with `Account.bulk_move()`

**Comment by super4bike** [comment]
what about this code line:   abc_folder = account.inbox / 'test-abc'                  

 ... making a string like :    abc_folder = "account.inbox.test-abc"   ??
my code for python 3.6 console ...
```
            try:
                  abc_folder = "account.inbox.test-abc"
                  item.move(to_folder=abc_folder)
            except ErrorFolderNotFound:
                  print("Uh-oh. Subfolder not found!")

```
... get failed in console with **AssertionsError at line item.move(to_folder=abc_folder)**
... means the subfolder doesn't exist, but in inbox it is one??

... can not see my problem, thanks for your input ...

**Comment by ecederstrand** [comment]
The code `abc_folder = account.inbox / 'test-abc'` is correct, so please don't change it :-)

We're using `__truediv__` to support this syntax, which mimics the syntax of folder navigation that `pathlib` uses. Internally, it returns any folder in `account.inbox.children` with the name `test-abc` and throws `ErrorFolderNotFound` if there is no match.

**Comment by ecederstrand** [comment]
You can try `print(account.inbox.tree())` or `print(account.root.tree())` to have a look at your entire folder structure.

**Comment by super4bike** [comment]
.... hhmmm what about me?

always the script above, extendet with:

>            # item.move(account.trash) --> works fine if uncommented
>            try:
>                 abc_folder = account.inbox / 'test-abc'
>                  item.move(to_folder=abc_folder)
>           except ErrorFolderNotFound:
>                print("Uh-oh. Subfolder not found!")
getting the Error:
Traceback (most recent call last):  File "EP-exchange-Email-Move_36.py", line 88, in <module>
    abc_folder = account.inbox / 'test-abc' TypeError: unsupported operand type(s) for /: 'Inbox' and 'str'


... and what i make wrong with your other sugesstions ...
>print(account.inbox.tree()) #  --> AttributeError: 'Inbox' object has no attribute 'tree'
>print(account.root.tree()) # --> AttributeError: 'Root' object has no attribute 'tree'

for me this works fine; print output "Messages (test-abc):
>for i in account.inbox.get_folders():
>   print(i)                          # --> works fine, get all subfolders from inbox

**Comment by ecederstrand** [comment]
You probably don't have v1.10.2 installed

**Comment by super4bike** [comment]
... of corse, you are right! it was not v1.10.2 !!!

**all it works now**: the trees are so beautyfull, and the moving in my folder so great!

i am sorry for the unnecessary looping at the end here

THANK YOU!

**Comment by ecederstrand** [comment]
A perfect response to start the weekend :-) Thanks! Glad you like the new improvements.
