### ISSUE TITLE
Can not move or copy a calendar occurrence.

### ISSUE THREAD

**Issue by ccs1910** [ecederstrand/exchangelib#254]
Hello!

i tried to move a calendar event which is an occurence meeting to Deleted Items folder, but failed and got this error message : :
exchangelib.errors.ErrorCalendarCannotMoveorCopyOccurrence : Can not move or copy a calendar occurrence.

kindly help.

thanks,
Christian CS

**Comment by ecederstrand** [comment]
That's correct behaviour. You can't copy or move an occurrence, only delete and change.
