### ISSUE TITLE
Implement GetUserAvailability service

### ISSUE THREAD

**Issue by KoenR3** [ecederstrand/exchangelib#256]
Hello

I was wondering if there is any way to call the GetUserAvailability from within the library, or at least pass the request through the library.  I have to be able to query a Rooms availability but without IMPERSONATION access, I currently can't and granting an account IMPERSONATION access is not what I want to do for security reasons.

**Comment by ecederstrand** [comment]
[GetUserAvailability](https://msdn.microsoft.com/en-us/library/office/aa564001(v=exchg.150).aspx) is not supported yet, but it would be a great addition, and probably not very difficult to implement.

An implementation would start in `exchangelib/services.py`, and is usually wired up to `Account` or `Protocol` with helper methods, depending on the type of service.

**Comment by driesken** [comment]
Is there any other way besides getting all calendar items at this moment and determining the status from that? Would indeed be a nice enhancement!

**Comment by ecederstrand** [comment]
Sorry, no. Your best option right now is to do:

```python
a = Account('target_mailbox@example.com', credentials=my_credentials)
is_available = bool(a.calendar.view(start=start_dt, end=end_dt, max_items=1).count())
```

but that still requires access to the calendar of the target account.

**Comment by AlJohri** [comment]
@ecederstrand I unfortunately found this library only after writing my own implementation: https://gist.github.com/AlJohri/a5b70a96ae4998fc24569a43016a3071

I don't have time to integrate it right now but just leaving this here in case it's helpful. I haven't worked with XML too much so the construction of the request is just string manipulation right now. have to look how you handle that stuff in this library

**Comment by ecederstrand** [comment]
The `GetUserAvailability` service *must* have a [TimeZone](https://msdn.microsoft.com/en-us/library/office/aa565658(v=exchg.150).aspx) element which is absolutely horrible to implement.

For some reason, we can't just pass the timezone ID and be done with it. Also, the element can only contain one DST and one STD transition, so it's dependent on the timeframe and we have to figure out the transition values seem fitting for this *exact* availability request.

We have to either get the full timezone info from the server using the `GetServerTimeZones` and parse the result, or get the (hopefully matching) information from `pytz` using some [internal pytz attributes](https://stackoverflow.com/questions/18131839/std-offset-for-pytz-timezones), use some heuristics to choose the most fitting transition, and then build the `TimeZone` element from that.
