### ISSUE TITLE
Access Public Folders

### ISSUE THREAD

**Issue by Brian-z** [ecederstrand/exchangelib#258]
I haven't yet found a way to navigate from my User account to an associated public folder. 

The Public Folders, is associated with my mailbox. I do not manage the exchange server (or public folders), it is corporately managed. 

When I connect to my account, I only see the standard folders associated with my user profile, not the shared folders which have also been shared with my mailbox.

is there anyway I can access this shared folder? 

My current source code (very straightforward).

```python
credentials = Credentials(username='myusername', password='mypassword!')

my_account = Account(primary_smtp_address='myemail', credentials=credentials,
					 autodiscover=True, access_type=DELEGATE)

folders = my_account.folders
target_folder = ['Public Folders - my email, 'All Public Folders', 'NBCUniversal', 'NBCU', 'NEWS',
				 'Transcripts']

for folder in my_account.root.walk():
	print(folder)
 



```

**Comment by ecederstrand** [comment]
I actually have no idea how to find folders that have been shared with an account via EWS. If you find out, please post it here so I can add it to the docs, or at least document what need to be implemented for this to work in exchangelib.

**Comment by ecederstrand** [comment]
Of course, if you already know the primary SMTP address of the mailbox holding the shared folder, there are instructions in https://github.com/ecederstrand/exchangelib#setup-and-connecting

**Comment by Brian-z** [comment]
Thanks for the advice, I am working on setting up a meeting with my companies EWS team. I will report back here if I find anything out. My worry is that they are securing it from their side, making this  a fool's errand.

**Comment by ecederstrand** [comment]
Hi @Brian-z Did you get anywhere with this?

**Comment by Brian-z** [comment]
@ecederstrand unfortunately not, I decided to contact my outlook team and have them create a shared mailbox which can be communicated with via EWS. According to them, public folders are an older implementation that companies should be moving away from if possible, and isn't accessible through EWS.

**Comment by ecederstrand** [comment]
Ok, thanks for the update! Closing this for now.
