### ISSUE TITLE
TLS CA certificate

### ISSUE THREAD

**Issue by askemottelson** [ecederstrand/exchangelib#264]
I get an OSError (on a docker instance), stating it couldn't find the necessary certificate:

For now I could only get pass this by using the `NoVerifyHTTPAdapt`, which is not really a viable solution. Any thoughts?

```
    config = Configuration(server=c["host"], credentials=credentials)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/configuration.py", line 46, in __init__
    version=version
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 172, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/protocol.py", line 204, in __init__
    name=self.credentials.username)
  File "/usr/local/lib/python3.6/site-packages/exchangelib/transport.py", line 133, in get_service_authtype
    timeout=BaseProtocol.TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 407, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 226, in cert_verify
    "invalid path: {0}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /usr/local/lib/python3.6/site-packages/certifi/cacert.pem
```

**Comment by ecederstrand** [comment]
Somehow, `requests` cannot find the certificate bundle it's looking for. It looks like you may have hit https://github.com/requests/requests/issues/4171

**Comment by askemottelson** [comment]
Hmm, yeah, that sounds related, I'm however not using Anaconda, but Python 3.6.1
The weird this is that `/usr/local/lib/python3.6/site-packages/certifi/cacert.pem` _does_ exist locally

**Comment by ecederstrand** [comment]
That's strange. I had a look and it's clearly `os.path.exists(path_to_cacert)` that fails. This in turn just does an `os.stat(path)` so for some reason the user you're running the script as in the Docker can't access that path. You should not be able to do `os.stat('/usr/local/lib/python3.6/site-packages/certifi/cacert.pem')` in a Python interpreter as that user, either.

Maybe a permissions problem?

**Comment by askemottelson** [comment]
Here's the strange part: both `os.path.exists` and `os.stat` works fine:
```
>>> import os
>>> os.stat('/usr/local/lib/python3.6/site-packages/certifi/cacert.pem')
os.stat_result(st_mode=33188, st_ino=9959, st_dev=125, st_nlink=1, st_uid=0, st_gid=50, st_size=296399, st_atime=1507662319, st_mtime=1507660553, st_ctime=1507660560)
```

**Comment by ecederstrand** [comment]
Wow, that's head-scratching. `exchangelib` isn't setting the certificate store anywhere, so you should get the same error if you do a simple `import requests; requests.get('https://google.com')` (I was going to suggest to request `https://diku.dk` but the result is hilarious :-))

**Comment by askemottelson** [comment]
Yeah, I'm scratching my head too.

```
>>> import requests; requests.get('https://google.com')
<Response [200]>
```

Haha, and excellent that diku.dk doesn't support https 👍

**Comment by ecederstrand** [comment]
I think it's time to add a breakpoint in `/usr/local/lib/python3.6/site-packages/requests/adapters.py` line 226. I have no idea what's going on at this point.

**Comment by askemottelson** [comment]
Okay, sorry @ecederstrand, I figured out the problem - my bad. Had unknowingly a test environment in my docker instance, that emulated a fake filesystem.
