### ISSUE TITLE
MIME content conversion failed.

### ISSUE THREAD

**Issue by jorgekl** [ecederstrand/exchangelib#266]
Exchangelib is throwing the follow exception as soon as I reach a specific email while iterating through the FilteredMail results:
 `exchangelib.errors.ErrorMimeContentConversionFailed: MIME content conversion failed.`

The emal has another email object attached, but I guess it might have some difference since have lots of mails with attached mail objects working fine.  The email opens normally in Outlook.   Any ideas on what could be the cause?   More detail on the exception below.

Thanks in advance!!

```python
 File "C:\MyScript.py", line 146, in main
   for MailItem in FilteredMail:
 File "c:\Python27\lib\site-packages\exchangelib\queryset.py", line 232, in __iter__
   for val in result_formatter(self._query()):
 File "c:\Python27\lib\site-packages\exchangelib\account.py", line 381, in fetch
   for i in GetItem(account=self).call(items=ids, folder=validation_folder, additional_fields=only_fields):
 File "c:\Python27\lib\site-packages\exchangelib\services.py", line 423, in _pool_requests
   for elem in elems:
 File "c:\Python27\lib\site-packages\exchangelib\services.py", line 236, in _get_elements_in_response
   container = self._get_element_container(message=msg, name=self.element_container_name)
 File "c:\Python27\lib\site-packages\exchangelib\services.py", line 207, in _get_element_container
   return self._raise_errors(code=response_code, text=msg_text, xml=msg_xml)
 File "c:\Python27\lib\site-packages\exchangelib\services.py", line 224, in _raise_errors
   raise vars(errors)[code](text)
exchangelib.errors.ErrorMimeContentConversionFailed: MIME content conversion failed.
```

**Comment by ecederstrand** [comment]
This is an error message from the server. I'm not sure what could cause it, but it's possible that the value of the `mime_content` field is somehow corrupt. You could test this by not fetching that field: `for MailItem in FilteredMail.only(list_of_fieldnames_you_need)`.

If this is the case, you could try to convince the server to re-generate the `mime_content` field. If you're able to edit the body of the email, that may trigger it. The `mime_content` is supposedly writable through EWS, but exchangelib doesn't support it yet (see https://github.com/ecederstrand/exchangelib/blob/3609fa23e403821bdc5f80cd896a9df1d73f0275/exchangelib/items.py#L90).

**Comment by ecederstrand** [comment]
@jorgekl Did you ever get to the bottom of this?

**Comment by ecederstrand** [comment]
Closing due to timeout. Feel free to re-open if you have more information :-)
