### ISSUE TITLE
how to get calendar of room resource

### ISSUE THREAD

**Issue by mohmagdy** [ecederstrand/exchangelib#269]
hello , i am doing app that require to get calendar of a room resource 
since its defined as resource mailbox , i cannot access its exchange account directly 
according to https://blogs.msdn.microsoft.com/exchangedev/2009/06/15/exchange-impersonation-vs-delegate-access/

> delegate access is resource mailbox management. Resources, such as conference rooms, can be managed by one or more people. Resources are represented by mailboxes, but not in the traditional sense. Resource mailboxes do not have owners; therefore, they can only be accessed by mail-enabled users to whom delegate access is granted.

how could i achieve that with exchangelib ?

**Comment by ecederstrand** [comment]
Normally, for this type og task, the account associated with your login credentials will be granted impersonation acces to the target account by the Exchange admin. When you create an `Account` with the primary SMTP address of the room resource, you can specify either DELEGATE or IMPERSONATION, depending on the access type you have been granted.

**Comment by mohmagdy** [comment]
do you mean that : 

- we shall create two accounts , one for room and other for user 

- MS Exchange admin to grant user account access to room resource account as DELEGATE or IMPERSONATION ?

**Comment by ecederstrand** [comment]
Yes, your example code it how it's supposed to work, although you should set the access type as `Account(..., access_type=IMPERSONATION)` if that's what `me@example.com` was granted.

We may not always be able to find the default calendar folder. In that case, you can `print(roomAcc.root.tree())` to see the available folders.

**Comment by ecederstrand** [comment]
If you don't see any calendar folders in the output of last command, your service account may simply have insufficient privileges to the room account.

**Comment by mohmagdy** [comment]
thanks its fixed
the root cause was as you mentioned , the user don't has sufficient privileges to the room account , i asked the email server admin to

**Comment by mohmagdy** [comment]
thanks its fixed
root cause was as you mentioned , user didn't has sufficient privileges to the room account.
