### ISSUE TITLE
Implement ReplyToItem and ReplyAllToItem for CreateItem service

### ISSUE THREAD

**Issue by Kami-no** [ecederstrand/exchangelib#270]
Hi, I need to reply a message so that it could be part of a thread in mail clients. Is there a way to do it? Found nothing about it in the manual.

**Comment by ecederstrand** [comment]
There's no `Item.reply()` helpr or anything like that, but I believe Exchange will sort the reply correctly if you preserve the `conversation_id` field on the reply message.

There's some inspiration in https://github.com/ecederstrand/exchangelib/issues/220

**Comment by Kami-no** [comment]
The problem is that `conversation_id = none` like index and toptic... I haven't found any vars with values that specific for a thread...

**Comment by ecederstrand** [comment]
Have you tried to use e.g. Outlook to create a reply that is correctly threaded? Then you could compare attributes of the two messages and see what the common value is.

Outside of the Microsoft bubble, many mail clients rely on email headers (the `Item.headers` field) to do the threading, specifically the `Message-ID`, `References`, and `In-Reply-To`header values.

**Comment by Kami-no** [comment]
I suppose there is a way in EWS API - https://msdn.microsoft.com/en-us/library/office/dd633704(v=exchg.80).aspx

**Comment by ecederstrand** [comment]
Oh, neat! I didn't know about that method.
