### ISSUE TITLE
Filter by item type

### ISSUE THREAD

**Issue by utapyngo** [ecederstrand/exchangelib#272]
I am trying to get all message ids from a folder and occasionally receive ids of `CalendarItem`s.
Is there a way to filter only `Message` ids?

**Comment by ecederstrand** [comment]
You could try to filter on the `item_class` field. I haven't tried it, but it's a good bet. Otherwise, you could filter on any other field that only exists on `Message` items, e.g. `account.inbox.filter(sender__exists=True)`. Finally, you could just do the filtering client-side (`if not isinstance(item, Message): continue`)

**Comment by utapyngo** [comment]
I can't do filtering client-side because it would imply loading excess `CalendarItem`s to the client which I want to avoid.

Filtering on `item_class` does not work server-side. I get `ValueError: Unknown fieldname 'item_class' on class 'Messages'`

**Comment by ecederstrand** [comment]
`item_class` was added in https://github.com/ecederstrand/exchangelib/commit/dc15de57c1612e1cefb8f409840d7f9b4a91e41b and is only available in v1.10.4.

Unless you have huge amounts of calendar items in your folders, I doubt that you'll notice any performance issues in your app if you resort to client-side filtering. Especially if you use the `.iterator()` specifier.

**Comment by utapyngo** [comment]
I do have huge amounts of calendar items in the "Calendar Version Store" folder (which is of type `Messages` for some reason).

How to use `item_class`?

`filter(item_class=Message)`:

    ValueError: Value "<class 'exchangelib.items.Message'>" for filter on field path "item_class" is unsupported

`filter(item_class='Message')` returns nothing.

**Comment by ecederstrand** [comment]
I have no idea what's special about `item_class=None` items, sorry.

AFAIK, "Calendar Version Store" is an internal Exchange system folder, so you could just skip that, unless you have special needs that requires you to traverse. It's not a folder that's visible to normal users.

**Comment by ecederstrand** [comment]
If you want items with both empty and `IPM.Note` values, you could do something like this (I'm not sure exactly how the empty values would match): `my_folder.filter(Q(item_class='IPM.Note') | Q(item_class__exists=False))`

or simply `my_folder.exclude(item_class='IPM.Appointment')`.

**Comment by ecederstrand** [comment]
Closing. Please feel free to reopen if you disagree :-)
