### ISSUE TITLE
Implement GetUserOofSettings and SetUserOofSettings

### ISSUE THREAD

**Issue by sucrefine** [ecederstrand/exchangelib#278]
i cannt find any function to set auto-reply for exchange ,please help me,thanks

**Comment by ecederstrand** [comment]
This isn't supported at the moment. You could, however, write a script that monitors your inbox and sends a reply to all the emails you want. Just remember to respect mailing list headers and ignore incoming auto-replies.

**Comment by sucrefine** [comment]
i am going to write a service that allows users who need it to set up auto-reply,is there any reasonable solutions

**Comment by ecederstrand** [comment]
There are no solutions that work out of the box, so you would need to implement the [SetUserOofSettings](https://msdn.microsoft.com/en-us/library/office/aa580294(v=exchg.150).aspx) and [GetUserOofSettings](https://msdn.microsoft.com/en-us/library/office/aa563465(v=exchg.150).aspx) services. The fundamentals for the implementation are already available in exchangelib.

**Comment by sucrefine** [comment]
Hi ecederstrand
i found exchangelib seemed to have plans to add the auto response function, and if it was implemented,please let me know thank you

**Comment by ecederstrand** [comment]
Hi @sucrefine I have no concrete plans to implement this in the near future, but GitHub will send you a notification if there are updates to this ticket. Contributions are welcome, of course.

**Comment by ecederstrand** [comment]
This is now done. See the README for documentation
