### ISSUE TITLE
O365 - ErrorExceededConnectionCount 

### ISSUE THREAD

**Issue by chunderstruck** [ecederstrand/exchangelib#279]
Hi, 
I've been using this exchangelib library for the past 3 months to monitor a mailbox but over the past few days the script stopped running because it was running into an issue with concurrent connections.  The exchange environment is in O365, anyone aware of if there is a way to explicitly terminate the connection?  The mailbox was moved which should have reset the connection.   

exchangelib.errors.ErrorExceededConnectionCount: You have exceeded the available concurrent connections for your account.  Try again once your other requests have completed.

This issue only occurs when using impersonation, i'm not sure if this is an exchange issue or a library issue.  The code has been running consistently for months.

`account = Account(primary_smtp_address=smtp_address,
                       credentials=Credentials(username=username, password=password),
                       autodiscover=True,
                       access_type=access_type)`

**Comment by ecederstrand** [comment]
`ErrorExceededConnectionCount` means that you have exceeded a policy limit that has been set on the account you connect with. You could try lowering `BaseProtocol.SESSION_POOLSIZE` from the default of 4, or lower your level of concurrency if you're running exchangelib in multiple processes.

If you're running e.g. a sync service or anything else that requires a large number of connections, you could talk to the Exchange admins about changing or removing the policy.

**Comment by chunderstruck** [comment]
How do you lower the Poolsize?  I was running into this issue even when the script wasn't running.

**Comment by ecederstrand** [comment]
Just do this before running anything that uses exchangelib:

```python
form exchangelib.protocol import BaseProtocol
BaseProtocol.SESSION_POOLSIZE = 1
```
