### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by jayanth1991** [ecederstrand/exchangelib#28]
First of all, this is an amazing library. Very thankful to all the authors.

So I have a Exchange 2013_SP1 server setup and I am testing failure cases. If I add a configuration with incorrect credentials. It goes in a loop and never returns (at least after 10mins). How do I restrict the number of retries before giving up, especially for the case for incorrect credentials.

**Comment by ecederstrand** [comment]
Thanks for the kind words!

This was answered in more depth in #16. In short, it's not possible to distinguish between a temporarily malfunctioning EWS service and incorrect credentials. If you do need immediate failures, version 1.7.0 introduced the `is_service_account=False` attribute to the `Credentials` model which should work in your case.

**Comment by jayanth1991** [comment]
Fantastic!

That does the trick. Thanks a lot.

**Comment by MartinThoma** [comment]
`is_service_account` seems to no longer exist in `Credentials`. How can I prevent the endless loop now?

**Comment by ecederstrand** [comment]
`is_service_account` is deprecated in favour of two credentials classes, `Credentials` and `ServiceAccount`. The former enables fail early, the latter enables backoff and retry.
