### ISSUE TITLE
Hanging at configuration Step.

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#280]
Hi,

I am not able to move forward as it is returning nothing at configuration step. 
I see following output and it is still running. can you please help me.

```bash
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```
CODE:

```python
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message,Task, Contact,  \
    Mailbox, Attendee, Q,  ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version
from exchangelib.items import MeetingRequest

from exchangelib import extended_properties

credentials = ServiceAccount(username="demouser2@domain365.com", password="abc!12")
config = Configuration(credentials=credentials,
                               server= "outlook.office365.com",
                               verify_ssl=False,
                               auth_type=NTLM)


account = Account(
    primary_smtp_address="AutoMB1@domain365.onmicrosoft.com", 
    config=config, access_type=IMPERSONATION)
folders = account.folders
```

**Comment by ecederstrand** [comment]
`ServiceAccount` hides any errors in the connection. Try using `credentials = Credentials(...)` instead, to see the error immediately.

**Comment by shireen91** [comment]
I am following error after using credentials 

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2016.2.3\helpers\pydev\pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Test/readprop.py", line 14, in <module>
    auth_type=NTLM)
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\configuration.py", line 48, in __init__
    version=version
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\protocol.py", line 168, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\protocol.py", line 219, in __init__
    self.docs_auth_type = get_docs_authtype(verify=self.verify_ssl, docs_url=self.types_url)
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\transport.py", line 109, in get_docs_authtype
    r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, verify=verify)
  File "C:\Python27\lib\site-packages\requests-2.13.0-py2.7.egg\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests-2.13.0-py2.7.egg\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.13.0-py2.7.egg\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests-2.13.0-py2.7.egg\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000041B3208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by ecederstrand** [comment]
The hostname we're trying to access is unknown by your DNS server. You'll need to enable debug logging to see exactly which URL we're failing on.

But it looks like you're trying to connect to Office365. autodiscover should work for your email. You could try removing your custom configuration and having autodiscover do the work for you.

**Comment by shireen91** [comment]
I removed configuration and using autodicover = TRue. i have enabled debug logging. can you please help me with this error?

(10/31/2017 12:33:18 312 MainThread) DEBUG [exchangelib.autodiscover:_get_autodiscover_response@360] - Response headers: {'Content-Length': '1606', 'X-CalculatedBETarget': 'bn6pr1101mb2356.namprd11.prod.outlook.com', 'Set-Cookie': 'X-BackEndCookie2=demouser2@commvault365.com=u56Lnp2ejJqByM/Oms/JmcfSzM3Hz9LLxs/M0p6cns/SyMzLxsjMmZuezJ7NgZyQkpKJnoqTi8zJytGckJKBzc/OyNLOztLMz6vOycXMzMXOx4GRnpKPjZvOztGPjZCb0ZCKi5OQkJTRnJCSgc8=; expires=Thu, 30-Nov-2017 16:33:18 GMT; path=/Autodiscover; secure; HttpOnly, X-BackEndCookie=demouser2@commvault365.com=u56Lnp2ejJqByM/Oms/JmcfSzM3Hz9LLxs/M0p6cns/SyMzLxsjMmZuezJ7NgZyQkpKJnoqTi8zJytGckJKBzc/OyNLOztLMz6vOycXMzMXOx4GRnpKPjZvOztGPjZCb0ZCKi5OQkJTRnJCSgc8=; expires=Thu, 30-Nov-2017 16:33:18 GMT; path=/Autodiscover; secure; HttpOnly', 'Content-Encoding': 'gzip', 'request-id': '8685909f-fc26-4c87-8eed-10796a1388bf', 'X-AspNet-Version': '4.0.30319', 'Vary': 'Accept-Encoding', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/10.0', 'X-BEServer': 'BN6PR1101MB2356', 'X-DiagInfo': 'BN6PR1101MB2356', 'X-FEServer': 'DM5PR20CA0027', 'Cache-Control': 'private', 'Date': 'Tue, 31 Oct 2017 16:33:17 GMT', 'Content-Type': 'text/xml; charset=utf-8'}
(10/31/2017 12:33:18 328 MainThread) DEBUG [exchangelib.autodiscover:_parse_response@421] - Primary SMTP: AutoMB1@commvault365.onmicrosoft.com, EWS endpoint: https://outlook.office365.com/EWS/Exchange.asmx
(10/31/2017 12:33:18 328 MainThread) DEBUG [exchangelib.autodiscover:_autodiscover_quick@315] - Autodiscover success: AutoMB1@commvault365.onmicrosoft.com may connect to https://outlook.office365.com/EWS/Exchange.asmx as primary email AutoMB1@commvault365.onmicrosoft.com
(10/31/2017 12:33:18 328 MainThread) DEBUG [exchangelib.protocol:__call__@157] - Waiting for _protocol_cache_lock
(10/31/2017 12:33:18 328 MainThread) DEBUG [exchangelib.protocol:__call__@166] - Protocol __call__ cache miss. Adding key '('https://outlook.office365.com/EWS/Exchange.asmx', Credentials('demouser2@commvault365.com', u'********'), False)'
(10/31/2017 12:33:18 407 MainThread) DEBUG [exchangelib.protocol:create_session@124] - Server outlook.office365.com: Created session 4992
(10/31/2017 12:33:18 407 MainThread) DEBUG [exchangelib.protocol:create_session@124] - Server outlook.office365.com: Created session 23419
(10/31/2017 12:33:18 407 MainThread) DEBUG [exchangelib.protocol:create_session@124] - Server outlook.office365.com: Created session 14315
(10/31/2017 12:33:18 407 MainThread) DEBUG [exchangelib.protocol:create_session@124] - Server outlook.office365.com: Created session 191
(10/31/2017 12:33:18 828 MainThread) DEBUG [exchangelib.protocol:get_session@81] - Server outlook.office365.com: Waiting for session
(10/31/2017 12:33:18 828 MainThread) DEBUG [exchangelib.protocol:get_session@83] - Server outlook.office365.com: Got session 191
(10/31/2017 12:33:19 078 MainThread) DEBUG [exchangelib.protocol:release_session@91] - Server outlook.office365.com: Releasing session 191
(10/31/2017 12:33:19 095 MainThread) ERROR [__main__:<module>@73] - Error: [20]

**Comment by shireen91** [comment]
(10/31/2017 13:19:22 299 MainThread) DEBUG [exchangelib.version:_get_shortname_from_docs@206] - Response headers: {'Content-Length': '57104', 'X-CalculatedBETarget': 'BN6PR1101MB2356.namprd11.prod.outlook.com', 'Content-Encoding': 'gzip', 'X-BEServer': 'BN6PR1101MB2356', 'request-id': 'c9bea3af-928b-4252-a768-8328b4595b3f', 'Accept-Ranges': 'bytes', 'X-CalculatedFETarget': 'BN6PR03CU003.internal.outlook.com', 'Vary': 'Accept-Encoding', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/8.5', 'Last-Modified': 'Sun, 15 Oct 2017 11:01:06 GMT', 'X-DiagInfo': 'BN6PR1101MB2356', 'ETag': '"0456e6a445d31:0"', 'X-FEServer': 'BN6PR03CA0063, BN6PR11CA0006', 'Date': 'Tue, 31 Oct 2017 17:19:22 GMT', 'Content-Type': 'text/xml', 'X-BackEndHttpStatus': '200, 200', 'X-FEProxyInfo': 'BN6PR03CA0063.NAMPRD03.PROD.OUTLOOK.COM'}
(10/31/2017 13:19:22 427 MainThread) DEBUG [exchangelib.version:guess@189] - Shortname according to https://outlook.office365.com/EWS/types.xsd: None
(10/31/2017 13:19:22 944 MainThread) DEBUG [exchangelib.services:_get_response_xml@140] - Trying API version Exchange2007 for account None
(10/31/2017 13:19:22 944 MainThread) DEBUG [exchangelib.services:_get_response_xml@158] - Adding missing build number for account None
(10/31/2017 13:19:22 944 MainThread) WARNING [exchangelib.services:_get_elements@109] - EWS https://outlook.office365.com/EWS/Exchange.asmx, account None: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\services.py", line 72, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\services.py", line 159, in _get_response_xml
    new_version = Version.from_response(requested_api_version=api_version, response=r.text)
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\version.py", line 246, in from_response
    api_version_from_server = info.get('Version') or build.api_version()
  File "C:\Python27\lib\site-packages\exchangelib-1.9.3-py2.7.egg\exchangelib\version.py", line 102, in api_version
    return self.API_VERSION_MAP[self.major_version][self.minor_version]
KeyError: 20

**Comment by ecederstrand** [comment]
Ah, that's a bug that was fixed in https://github.com/ecederstrand/exchangelib/commit/1c7d3e9c223e8f3bea8aad70558624a7ef01238c. Just upgrade exchangelib to the latest version.

**Comment by shireen91** [comment]
Thanks after upgrading it worked.
