### ISSUE TITLE
Unable (?) to register and/or search on custom ExtendedProperty for Message

### ISSUE THREAD

**Issue by Benco1** [ecederstrand/exchangelib#282]
Trying 

```
class OnHold(ExtendedProperty):
    property_set_id = '12345678-1234-1234-1234-123456781234'
    property_name = 'Item is currently being processed'
    property_type = 'bool'

Message.register('on_hold', OnHold)
```

I am trying to verify it is successful by doing something like ...

```
item = account.inbox.all().order_by('-datetime_received')[0]
# print item.__dict__.keys()
message_id = item.message_id
item.on_hold = True
item.save()

item2 = account.inbox.get(message_id=message_id)
print item2.on_hold
```

But usually get some sort of exception saying `on_hold` isn't recognized. Tried variations of this. Can you offer an example of how to apply an `ExtendedProperty` to an e-mail and method for confirming that it works @ecederstrand

**Comment by ecederstrand** [comment]
There's some documentation of extended properties, including a working example, at https://github.com/ecederstrand/exchangelib#extended-properties

From your example code, I can see that `property_type='bool'` is not a valid value. Try `property_type='Boolean'` instead. But you'll need to post the exact error message or stack trace to get more specific help :-)

**Comment by Benco1** [comment]
@ecederstrand wow, sorry. just wanted to get back to say this was my dumb mistake on the `property_type`. fixed it and works fine. thanks and sorry to waste your time with this.

**Comment by ecederstrand** [comment]
Hey, no worries. We should at least have printed a useful error message, so I’ll look into why that didn’t happen.

**Comment by ecederstrand** [comment]
Just committed a fix so you will now get this error if you attempt the above:

```python
ValueError: 'property_type' value 'bool' must be one of ['ApplicationTime', 'Binary', 
'BinaryArray', 'Boolean', 'CLSID', 'CLSIDArray', 'Currency', 'CurrencyArray', 'Double',
 'DoubleArray', 'Float', 'FloatArray', 'Integer', 'IntegerArray', 'Long', 'LongArray', 'Short', 
'ShortArray', 'String', 'StringArray']
```
