### ISSUE TITLE
exchangelib too slow for unpacking emails

### ISSUE THREAD

**Issue by kthouz** [ecederstrand/exchangelib#283]
I am trying to extract 1000 emails but it is taking more than `5 min` on `MacBook Pro, Processor 2.9GHz intel i5, RAM 16GB`. Here is a sample code
```
account = Account(...)
myMails = {}
counter = 0
raw_mails = account.inbox.all()
for item in raw_mails[:1000]:
    myMails[counter] = item
    counter += 1
```
Is this a common issue?

**Comment by ecederstrand** [comment]
This should depend almost entirely on the size of emails in your inbox, your internet connection speed and the Exchange server, and much less on your local hardware.

You'll have to do some profiling find out where time is spent. But beware that the above query will get all attributes on all messages, even attachments. Depending on what you want to do with the 1000 emails, you may be able to optimize your query.

**Comment by kthouz** [comment]
I used `only()` to filter few attributes that I wanted. Thanks for the hint
