### ISSUE TITLE
SSL Certificate Issue

### ISSUE THREAD

**Issue by mayers81** [ecederstrand/exchangelib#284]
Hi this is my code

```
`from datetime import timedelta
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version

from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

credentials = Credentials(username='domain\\user', password='password')
version = Version(build=Build(15, 0, 12, 34))
config = Configuration(server='mail.servers', credentials=credentials, version=version, auth_type=NTLM)
account = Account(primary_smtp_address='user@domain', config=config,
                  autodiscover=False, access_type=DELEGATE)

print(account.inbox.total_count)
print(account.inbox.child_folder_count)
print(account.inbox.unread_count)`
```

The script works but I'll restore this output

(env_mail) c:\lab\python\env_mail>Scripts\python.exe connect.py
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\lab\python\env_mail\lib\site-packages\urllib3\connectionpool.py:858: Insecure
RequestWarning: Unverified HTTPS request is being made. Adding certificate verif
ication is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advan
ced-usage.html#ssl-warnings
  InsecureRequestWarning)
11953
0
36

If I take the instructions

```
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
```
It gives me a mistake

'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)')

I thank you in advance

**Comment by ecederstrand** [comment]
To silence warnings in Python, see https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

But it would be better to find out why you cannot verify the certificate. See https://stackoverflow.com/questions/46691545/sslerror-on-exchangelib-cant-connect-on-the-server for some suggestions on debugging and solutions.

**Comment by mayers81** [comment]
Ok but my certificate ssl is valid because it returns error? if I connect to a browser I will not restrain any errors

**Comment by ecederstrand** [comment]
The SSL certificate on the server is probably fine, but `requests` doesn't have access to the same root CAs as your browser.

Does `import requests; requests.get('https://url_to_your_exchange_server.com')` fail? If so, follow the suggestions in the SO question I linked to.

**Comment by mayers81** [comment]
The same mistake

Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERT
IFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

Is there no way to pass them RootCA and Certificate?

Thanks

**Comment by ecederstrand** [comment]
Yes, there are ways to pass the root CA. See my comment on https://stackoverflow.com/questions/46691545/sslerror-on-exchangelib-cant-connect-on-the-server#comment80634556_46691545
