### ISSUE TITLE
How to delete Calendar item?

### ISSUE THREAD

**Issue by cr1010** [ecederstrand/exchangelib#288]
Hi, how do i delete a calendar item based on having the item_id. I have tried filtering but get an error "'item_id' is not a valid field when filtering on Calendar". The code i attempted in my Django DeleteView is:
    def post(self, *args, **kwargs):
        exchange_id = self.request.GET['eid']
        item = account.calendar.filter(
        item_id=exchange_id,
        )
        for ex in item:
            item.delete(send_meeting_cancellations=SEND_ONLY_TO_ALL)
        return self.delete(*args, **kwargs)

**Comment by cr1010** [comment]
I solved this. The issue was I wasnt including the changekey. Thanks for the brilliant library!
Here is my code that worked:
    def post(self, *args, **kwargs):
        exchange_id = self.request.GET['eid']
        exchange_changekey = self.request.GET['eck']
        item = CalendarItem(folder=account.calendar, item_id=exchange_id, changekey=exchange_changekey)
        item.delete(send_meeting_cancellations=SEND_ONLY_TO_ALL)
        return self.delete(*args, **kwargs)

**Comment by ecederstrand** [comment]
Thanks for the kind words!

You can't call `filter()` with `item_id` and `changekey` arguments, but you can actually do that with `get()`:
```python
account.calendar.get(item_id=exchange_id, changekey=exchange_changekey).delete()
```
