### ISSUE TITLE
Question: Search for users located in a given office 

### ISSUE THREAD

**Issue by iDevo** [ecederstrand/exchangelib#289]
Hi there! 
First of all thank you very much for this libary - great work! 

I'd like to start a kind of reverse search for users located in a specific office respectively where the user attribute office contains a given string. 

Example: 
Search string: "123"
User: Name: "John Doe", Office: "R**123**"

It's the same functionality using Outlook and the advanced find function of the Outlook address book.
I've tried multiple request but unfortunately couldn't get it to work.
Thanks in advance!

**Comment by ecederstrand** [comment]
I think this would require the `FindPeople` service which is unimplemented and tracked in #93

**Comment by iDevo** [comment]
Yes, sorry I didn't see this post. This one can be closed, but an implementation is not available yet, right?

**Comment by ecederstrand** [comment]
Nope, no implementation yet. Sorry :-)
