### ISSUE TITLE
Folders with meeting requests causes KeyError exceptions.

### ISSUE THREAD

**Issue by alxbse** [ecederstrand/exchangelib#29]
Trying to use the library to fetch unread items from a mailbox. Ran into an issue where if the folder contains meeting requests a KeyError exception occurs.

Simple test:

``` python
items = account.inbox.filter(is_read=False)
for item in items:
    print('subject: {}, read: {}'.format(item.subject, item.is_read))
```

Example error message:

``` python
<exchangelib.queryset.QuerySet object at 0x7f134dfec7f0>
Traceback (most recent call last):
  File "ews.py", line 30, in <module>
    for item in items:
  File "/home/alex/src/django-dashing-test/venv/lib/python3.5/site-packages/exchangelib/queryset.py", line 125, in __iter__
    self._cache = list(self._query())
  File "/home/alex/src/django-dashing-test/venv/lib/python3.5/site-packages/exchangelib/queryset.py", line 97, in _query
    items = self.folder.fetch(ids=ids, only_fields=additional_fields)
  File "/home/alex/src/django-dashing-test/venv/lib/python3.5/site-packages/exchangelib/folders.py", line 1585, in fetch
    return self.account.fetch(folder=self, *args, **kwargs)
  File "/home/alex/src/django-dashing-test/venv/lib/python3.5/site-packages/exchangelib/account.py", line 312, in fetch
    items
  File "/home/alex/src/django-dashing-test/venv/lib/python3.5/site-packages/exchangelib/account.py", line 311, in <lambda>
    lambda i: validation_folder.item_model_from_tag(i.tag).from_xml(elem=i, account=self, folder=folder),
  File "/home/alex/src/django-dashing-test/venv/lib/python3.5/site-packages/exchangelib/folders.py", line 1419, in item_model_from_tag
    return cls.ITEM_MODEL_MAP[tag]
KeyError: '{http://schemas.microsoft.com/exchange/services/2006/types}MeetingRequest'
```

As far as I understood it from the source no MeetingRequest class has not been implemented yet. Is there a reason why it's missing or have I missed something?

I hacked together a bare minimum version of the various meeting requests types and got it working. I could implement more of the meeting types and create a pull request, just wanted to verify if I'm on the right track?

Example implementation:

``` python
class MeetingRequest(ItemMixIn):
    # Supported attrs: https://msdn.microsoft.com/en-us/library/office/aa565229(v=exchg.150).aspx
    ELEMENT_NAME = 'MeetingRequest'
    FIELDURI_PREFIX = 'meetingrequest' # educated guess
    ITEM_FIELDS = {
        'from': ('From', Mailbox),
        'is_read': ('IsRead', bool),
        'start': ('Start', EWSDateTime),
        'end': ('End', EWSDateTime),
    }
    ORDERED_FIELDS = (
        'subject', 'from', 'is_read', 'start', 'end'
    )
    REQUIRED_FIELDS = {'subject'}
    READONLY_FIELDS = {'from'}

    __slots__ = tuple(ITEM_FIELDS) + tuple(Item.ITEM_FIELDS)

    def __init__(self, **kwargs):
        for k in self.ITEM_FIELDS:
            field_type = self.ITEM_FIELDS[k][1]
            default = False if (k in self.required_fields() and field_type == bool) else None
            v = kwargs.pop(k, default)
            setattr(self, k, v)
        super().__init__(**kwargs)
```

**Comment by kraulin** [comment]
This is my first time using github, I'm unsure of the protocol... but I'm
looking for documentation / assistance in using this code base.

I'm trying to access a folder inside my account called 'undeliverable' and
get a list of the emails inside and see if they have attachments.

I've successfully retrieved a list of all the folders in my account and
'Undeliverable' is listed in the response.

I did an:
for i in account.folders:
...     print(i)

Now that code shows <class 'exchangelib.folders.Root'>.  that's where all
the folders I've created live.
How do I get inside the array that Root contains to then do something akin
to:
account.Root['Undeliverable].find_items() and get all the data associated
with that email, attachments and everything?

Thanks,
Bryan James

>

**Comment by alxbse** [comment]
@kraulin, by posting your problem as a comment in an unrelated issue you've essentialy hijacked the issue and that is looked down upon on GitHub.

I would suggest that you create a new issue with the same body as your comment and a suitable title such as "Need example on how to get folder".

**Comment by ecederstrand** [comment]
@alxbse You are right. The `Meeting*` item types are not supported yet, and your approach to add them is also correct.

Testing the new item type(s) should be easy. Add a new `MeetingRequestTest` modeled after eg. `ContactsTest` in `tests/__init__.py`

**Comment by ecederstrand** [comment]
@kraulin , as @alxbse said, please open a separate issue next time. There's a green "New issue" button on the main issues page.

`account.folders` is a Python `dict` where the key is the folder class and the value is a list of folders of that type. To list all folders, do something like this:

```
for folder_cls, folders in account.folders.items():
    print(folder_cls)
    for f in folders:
        print('    ', f)
```

The only docs we have ATM is the README.

**Comment by ecederstrand** [comment]
@alxbse I'd be happy to review a PR if you do implement this.

**Comment by alxbse** [comment]
@ecederstrand I'm having a hard time using the BaseItemTest for implementing a test case. The problem seem to be that it's not possible to create a MeetingRequest using CreateItem. 

As far as I can understand it the MeetingRequest, MeetingResponse and MeetingCancellation type of message are created as results of creating other types. MeetingRequest messages seems to be created based on a previous CalendarItem created that has attendees.

If I use folder.bulk_create to create a MessageRequests similiar to the previous example the resulting item will be a Message. I've checked the resulting XML and the outgoing requests is for type MeetingRequest but the response is for Message. Thus all tests fail related to wrong type, just like they should.

As I'm sure you've ready many times this documents describes creating Message types: https://msdn.microsoft.com/en-us/library/office/aa566468(v=exchg.150).aspx

This one describes "creating" meeting requests: https://msdn.microsoft.com/en-us/library/office/aa566464(v=exchg.150).aspx
All the examples listed there are only related to replying to meeting requests though.

I'm thinking of trying to see it it's possible to send meeting requests to oneself somehow but those are usually never sent to organizer.

Do you have any suggestions? Maybe some suitable subset of tests from BaseItemTest?

**Comment by ecederstrand** [comment]
Honestly, I don't have much experience with meeting requests. If it's not feasible to write a test that generates setting requests, -responses or -cancellations, then we'll have to live with a smaller subset of tests, possibly only local tests that don't touch the server.

Another possibility would be to let the test suite require two test accounts for the meeting request tests. Running these tests should be skipped if there is only one account configured in the test setup file.

I'm fine with either solution for now.

**Comment by ecederstrand** [comment]
@alxbse Did you get any further? I'd like to at least fix the KeyErrors since they are a show-stopper for reading inboxes with meeting requests. If your code does that, I'd like to pull it in, even though tests are lacking.
