### ISSUE TITLE
Reccurrence Master Event and Modified Occurrences Original Start Time are one hour off.

### ISSUE THREAD

**Issue by tarikbenmerar** [ecederstrand/exchangelib#291]
I am testing recurring events with an outlook 365 calendar that has non UTC timezone. From my current tests on another UTC calendar the original start time for both the master recurrent event and the modified occurence is the same, but with the non UTC timezone I find a one hour difference as in the data below (See in bold).

CalendarItem(mime_content=b'BEGIN:VCALENDAR\r\nMETHOD:PUBLISH\r\nPRODID:Microsoft Exchange Server 2010\r\nVERSION:2.0\r\nBEGIN:VTIMEZONE\r\nTZID:Pacific Standard Time\r\nBEGIN:STANDARD\r\nDTSTART:16010101T020000\r\nTZOFFSETFROM:-0700\r\nTZOFFSETTO:-0800\r\nRRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11\r\nEND:STANDARD\r\nBEGIN:DAYLIGHT\r\nDTSTART:16010101T020000\r\nTZOFFSETFROM:-0800\r\nTZOFFSETTO:-0700\r\nRRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3\r\nEND:DAYLIGHT\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nORGANIZER;CN=testTesting:MAILTO:test@outlook.com\r\nDESCRIPTION;LANGUAGE=en-US:\\n\r\nRRULE:FREQ=WEEKLY;UNTIL=20180408T203000Z;INTERVAL=1;BYDAY=SU,TU,TH;WKST=SU\r\nUID:040000008200E00074C5B7101A82E008000000006BBF708F334DD301000000000000000\r\n 010000000EB47B669CD391747A9C8C285F08C5ECE\r\nSUMMARY;LANGUAGE=en-US:Testing Random Day Recurring \r\nDTSTART;TZID=Pacific Standard Time:20171022T133000\r\nDTEND;TZID=Pacific Standard Time:20171022T143000\r\nCLASS:PUBLIC\r\nPRIORITY:5\r\nDTSTAMP:20171109T173058Z\r\nTRANSP:OPAQUE\r\nSTATUS:CONFIRMED\r\nSEQUENCE:0\r\nLOCATION;LANGUAGE=en-US:\r\nX-MICROSOFT-CDO-APPT-SEQUENCE:0\r\nX-MICROSOFT-CDO-OWNERAPPTID:2115683435\r\nX-MICROSOFT-CDO-BUSYSTATUS:BUSY\r\nX-MICROSOFT-CDO-INTENDEDSTATUS:BUSY\r\nX-MICROSOFT-CDO-ALLDAYEVENT:FALSE\r\nX-MICROSOFT-CDO-IMPORTANCE:1\r\nX-MICROSOFT-CDO-INSTTYPE:1\r\nX-MICROSOFT-DONOTFORWARDMEETING:FALSE\r\nX-MICROSOFT-DISALLOW-COUNTER:FALSE\r\nBEGIN:VALARM\r\nDESCRIPTION:REMINDER\r\nTRIGGER;RELATED=START:-PT15M\r\nACTION:DISPLAY\r\nEND:VALARM\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:040000008200E00074C5B7101A82E008000000006BBF708F334DD301000000000000000\r\n 010000000EB47B669CD391747A9C8C285F08C5ECE\r\nRECURRENCE-ID;TZID=Pacific Standard Time:20171107T133000\r\nSUMMARY:Testing Random Day Recurring \r\nDTSTART;TZID=Pacific Standard Time:20171107T150000\r\nDTEND;TZID=Pacific Standard Time:20171107T160000\r\nCLASS:PUBLIC\r\nPRIORITY:5\r\nDTSTAMP:20171108T220535Z\r\nTRANSP:OPAQUE\r\nSTATUS:CONFIRMED\r\nSEQUENCE:0\r\nLOCATION:\r\nX-MICROSOFT-CDO-APPT-SEQUENCE:0\r\nX-MICROSOFT-CDO-OWNERAPPTID:2115683435\r\nX-MICROSOFT-CDO-BUSYSTATUS:BUSY\r\nX-MICROSOFT-CDO-INTENDEDSTATUS:BUSY\r\nX-MICROSOFT-CDO-ALLDAYEVENT:FALSE\r\nX-MICROSOFT-CDO-IMPORTANCE:1\r\nX-MICROSOFT-CDO-INSTTYPE:3\r\nX-MICROSOFT-DONOTFORWARDMEETING:FALSE\r\nX-MICROSOFT-DISALLOW-COUNTER:FALSE\r\nEND:VEVENT\r\nBEGIN:VEVENT\r\nUID:040000008200E00074C5B7101A82E008000000006BBF708F334DD301000000000000000\r\n 010000000EB47B669CD391747A9C8C285F08C5ECE\r\nRECURRENCE-ID;TZID=Pacific Standard Time:20171109T133000\r\nSUMMARY:Testing Random Day Recurring \r\nDTSTART;TZID=Pacific Standard Time:20171109T150000\r\nDTEND;TZID=Pacific Standard Time:20171109T160000\r\nCLASS:PUBLIC\r\nPRIORITY:5\r\nDTSTAMP:20171109T173057Z\r\nTRANSP:OPAQUE\r\nSTATUS:CONFIRMED\r\nSEQUENCE:0\r\nLOCATION:\r\nX-MICROSOFT-CDO-APPT-SEQUENCE:0\r\nX-MICROSOFT-CDO-OWNERAPPTID:2115683435\r\nX-MICROSOFT-CDO-BUSYSTATUS:BUSY\r\nX-MICROSOFT-CDO-INTENDEDSTATUS:BUSY\r\nX-MICROSOFT-CDO-ALLDAYEVENT:FALSE\r\nX-MICROSOFT-CDO-IMPORTANCE:1\r\nX-MICROSOFT-CDO-INSTTYPE:3\r\nX-MICROSOFT-DONOTFORWARDMEETING:FALSE\r\nX-MICROSOFT-DISALLOW-COUNTER:FALSE\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n', item_id='AQMkADAwATM0MDAAMS0wNjM2LWNlM2MtMDACLTAwCgBGAAADCV5KKG3aH0Ggdj34skeWFwcASfmShA5AOECoxa7764i3vAAAAjwbAAAASfmShA5AOECoxa7764i3vAAAAkAIAAAA', changekey='DwAAABYAAABJ+ZKEDkA4QKjFrvvriLe8AAAIkpfQ', item_class='IPM.Appointment', subject='Testing Random Day Recurring ', sensitivity='Normal', text_body='\r\n', body='<html>\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\r\n<style type="text/css" style="display:none;"></style>\r\n</head>\r\n<body dir="ltr">\r\n<div id="divtagdefaultwrapper" style="font-size:12pt;color:#000000;font-family:Calibri,Helvetica,sans-serif;" dir="ltr">\r\n<p><br>\r\n</p>\r\n</div>\r\n</body>\r\n</html>\r\n', attachments=[], datetime_received=EWSDateTime(2017, 10, 25, 1, 49, 56, tzinfo=<UTC>), size=11620, importance='Normal', is_submitted=False, is_draft=False, is_from_me=False, is_resend=False, is_unmodified=False, datetime_sent=EWSDateTime(2017, 10, 25, 1, 49, 56, tzinfo=<UTC>), datetime_created=EWSDateTime(2017, 10, 25, 1, 49, 56, tzinfo=<UTC>), reminder_due_by=EWSDateTime(2017, 11, 7, 23, 0, tzinfo=<UTC>), reminder_is_set=True, reminder_minutes_before_start=15, has_attachments=False, culture='en-US', effective_rights=EffectiveRights(create_associated=False, create_contents=False, create_hierarchy=False, delete=True, modify=True, read=True, view_private_items=True), last_modified_name='Testing', last_modified_time=EWSDateTime(2017, 11, 9, 17, 30, 58, tzinfo=<UTC>), is_associated=False, conversation_id=ConversationId(id='AQQkADAwATM0MDAAMS0wNjM2LWNlM2MtMDACLTAwCgAQAAX3VnA8Yx5Cm1diyQBsrEU=', changekey=None), uid='040000008200E00074C5B7101A82E008000000006BBF708F334DD301000000000000000010000000EB47B669CD391747A9C8C285F08C5ECE', start=EWSDateTime(2017, 10, 22, 20, 30, tzinfo=<UTC>), end=EWSDateTime(2017, 10, 22, 21, 30, tzinfo=<UTC>), is_all_day=False, legacy_free_busy_status='Busy', is_meeting=False, is_cancelled=False, is_recurring=False, meeting_request_was_sent=False, is_response_requested=True, type='RecurringMaster', my_response_type='Organizer', organizer=Mailbox(name='Testing', email_address='test@outlook.com', mailbox_type='Mailbox', item_id=None), conflicting_meeting_count=1, adjacent_meeting_count=0, duration='PT1H', appointment_sequence_number=0, recurrence=Recurrence(pattern=WeeklyPattern(interval=1, weekdays=[7, 2, 4], first_day_of_week=7), boundary=EndDatePattern(start=EWSDate(2017, 10, 22), end=EWSDate(2018, 4, 8))), first_occurrence=FirstOccurrence(item_id='AQMkADAwATM0MDAAMS0wNjM2LWNlM2MtMDACLTAwCgFRAAgIANUY39aaQABGAAACCV5KKG3aH0Ggdj34skeWFwcASfmShA5AOECoxa7764i3vAAAAjwbAAAASfmShA5AOECoxa7764i3vAAAAkAIAAAAEA==', changekey='DwAAABYAAABJ+ZKEDkA4QKjFrvvriLe8AAAIkpfQ', start=EWSDateTime(2017, 10, 22, 20, 30, tzinfo=<UTC>), end=EWSDateTime(2017, 10, 22, 21, 30, tzinfo=<UTC>), **original_start=EWSDateTime(2017, 10, 22, 20, 30, tzinfo=<UTC>))**, last_occurrence=LastOccurrence(item_id='AQMkADAwATM0MDAAMS0wNjM2LWNlM2MtMDACLTAwCgFRAAgIANWc46wAQABGAAACCV5KKG3aH0Ggdj34skeWFwcASfmShA5AOECoxa7764i3vAAAAjwbAAAASfmShA5AOECoxa7764i3vAAAAkAIAAAAEA==', changekey='DwAAABYAAABJ+ZKEDkA4QKjFrvvriLe8AAAIkpfQ', start=EWSDateTime(2018, 4, 8, 20, 30, tzinfo=<UTC>), end=EWSDateTime(2018, 4, 8, 21, 30, tzinfo=<UTC>), original_start=EWSDateTime(2018, 4, 8, 20, 30, tzinfo=<UTC>)), modified_occurrences=[Occurrence(item_id='AQMkADAwATM0MDAAMS0wNjM2LWNlM2MtMDACLTAwCgFRAAgIANUlcn02QABGAAACCV5KKG3aH0Ggdj34skeWFwcASfmShA5AOECoxa7764i3vAAAAjwbAAAASfmShA5AOECoxa7764i3vAAAAkAIAAAAEA==', changekey='DwAAABYAAABJ+ZKEDkA4QKjFrvvriLe8AAAIkpfQ', start=EWSDateTime(2017, 11, 7, 23, 0, tzinfo=<UTC>), end=EWSDateTime(2017, 11, 8, 0, 0, tzinfo=<UTC>), **original_start=EWSDateTime(2017, 11, 7, 21, 30, tzinfo=<UTC>)**), Occurrence(item_id='AQMkADAwATM0MDAAMS0wNjM2LWNlM2MtMDACLTAwCgFRAAgIANUnBNIJwABGAAACCV5KKG3aH0Ggdj34skeWFwcASfmShA5AOECoxa7764i3vAAAAjwbAAAASfmShA5AOECoxa7764i3vAAAAkAIAAAAEA==', changekey='DwAAABYAAABJ+ZKEDkA4QKjFrvvriLe8AAAIkpfQ', start=EWSDateTime(2017, 11, 9, 23, 0, tzinfo=<UTC>), end=EWSDateTime(2017, 11, 10, 0, 0, tzinfo=<UTC>), **original_start=EWSDateTime(2017, 11, 9, 21, 30, tzinfo=<UTC>))**], _start_timezone=<DstTzInfo 'America/Dawson' LMT-1 day, 14:42:00 STD>, _end_timezone=<DstTzInfo 'America/Dawson' LMT-1 day, 14:42:00 STD>, allow_new_time_proposal=True, is_online_meeting=False)

**Comment by ecederstrand** [comment]
The output is extremely hard to read. Can you maybe format it and cut away the unneeded info? For example, the `<UTC>` timezone names disappeared because you posted it as plain text.

I haven't looked up the Dawson timezone, but you're probably crossing the DST border. If 2017-10-22 is before DST and 2017-11-9 is after, then EWS could get confused.

Are the actual start and end times of the occurrences correct?

**Comment by tarikbenmerar** [comment]
@ecederstrand I think I understand the issue. It is sun saving issue. The sun saving ended on November 5th that's why the hours are different from the master event one. I also verified the data recieved in the SOAP message, it is the same value. Sorry for the inconvenience.

**Comment by ecederstrand** [comment]
No problem. Closing this issue, feel free to reopen if you disagree.
