### ISSUE TITLE
Endless loop on getting calendaritem

### ISSUE THREAD

**Issue by driesken** [ecederstrand/exchangelib#294]
Hi,

I'm getting some weird behavior for a specific user mailbox. The script works fine for all other users except this one. When I try to get the calendaritems, there is an endless loop of the following output:

```
DEBUG:exchangelib.util:Session 4508 thread 139762650560320: Useful response from https://xxxxxxx/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server mail.xxxxxxx.be: Releasing session 4508
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account  xxxxxxx@xxxxxxx.be
DEBUG:exchangelib.services:FindFolder: Got page with next offset 1 (last_page False)
DEBUG:exchangelib.services:EWS https://mail.xxxxxxx.be/EWS/Exchange.asmx, account  xxxxxxx@xxxxxxx.be, service FindFolder: Getting items at offset 1
DEBUG:exchangelib.protocol:Server mail.xxxxxxx.be: Waiting for session
DEBUG:exchangelib.protocol:Server mail.xxxxxxx.be: Got session 4508
DEBUG:exchangelib.util:Session 4508 thread 139762650560320: retry 0 timeout 120 POST'ing to https://xxxxxxx/EWS/Exchange.asmx after 10s wait
/usr/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://mail.xxxxxxx.be:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 4508
Thread: 139762650560320
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x288ddd0>
URL: https://mail.xxxxxxx.be/EWS/Exchange.asmx
HTTP adapter: <exchangelib.protocol.NoVerifyHTTPAdapter object at 0x288df50>
Allow redirects: False
Response time: 0.0166780948639
Status code: 200
Request headers: {'Content-Length': '1218', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.4', 'Connection': 'Keep-Alive', 'Cookie': 'X-BackEndCookie=S-1-5-21-3222743990-3588243504-3938062828-46253=rJqNiZqNgb2zzsnSz8fRnpbRlpGLmo2RnpPRioWYmpGL0Z2agc7GzMjGxsjGy8iBzc/OyNLOztLOyqvPx8XPxsXMyg==; exchangecookie=5dcf5f1b0d524c3b9cee777c4fe3c5ce', 'Content-Type': u'text/xml; charset=utf-8'}
Response headers: {'X-CalculatedBETarget': 'xxxxx.be', 'Set-Cookie': 'X-BackEndCookie=S-1-5-21-3222743990-3588243504-3938062828-46253=rJqNiZqNgb2zzsnSz8fRnpbRlpGLmo2RnpPRioWYmpGL0Z2agc7GzMjGxsjGy8iBzc/OyNLOztLOyqvPx8XPxsXMyg==; expires=Wed, 15-Nov-2017 08:09:35 GMT; path=/EWS; secure; HttpOnly', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'request-id': '73300449-982c-48d5-a79a-e3a9f58bc731', 'X-AspNet-Version': '4.0.30319', 'Vary': 'Accept-Encoding', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/10.0', 'X-FEServer': 'VMAILBOXSVR2P', 'Cache-Control': 'private', 'Date': 'Wed, 15 Nov 2017 07:59:34 GMT', 'Content-Type': 'text/xml; charset=utf-8'}
Request data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /><t:TimeZoneContext><t:TimeZoneDefinition Id="Romance Standard Time" /></t:TimeZoneContext></s:Header><s:Body><m:FindFolder Traversal="Deep"><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:ChildFolderCount" /><t:FieldURI FieldURI="folder:EffectiveRights" /><t:FieldURI FieldURI="folder:FolderClass" /><t:FieldURI FieldURI="folder:DisplayName" /><t:FieldURI FieldURI="folder:ParentFolderId" /><t:FieldURI FieldURI="folder:TotalCount" /><t:FieldURI FieldURI="folder:UnreadCount" /></t:AdditionalProperties></m:FolderShape><m:IndexedPageFolderView BasePoint="Beginning" MaxEntriesReturned="100" Offset="1" /><m:ParentFolderIds><t:DistinguishedFolderId Id="root"><t:Mailbox><t:EmailAddress>xxxx@xxx.be</t:EmailAddress><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:ParentFolderIds></m:FindFolder></s:Body></s:Envelope>
Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="339" MinorBuildNumber="0" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:FindFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:FindFolderResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:RootFolder IndexedPagingOffset="1" TotalItemsInView="751" IncludesLastItemInRange="false"><t:Folders/></m:RootFolder></m:FindFolderResponseMessage></m:ResponseMessages></m:FindFolderResponse></s:Body></s:Envelope>
```

And a snippet which reproduces the issue:
```python
tz = EWSTimeZone.timezone('Europe/Brussels')
all_items = account.calendar.all()
start_dt = tz.localize(EWSDateTime.now())
end_dt = start_dt + timedelta(minutes=5)
legacy_free_busy_statusses = Set([])
for item in account.calendar.view(start=start_dt, end=end_dt, max_items=3):
    print(item)
```

**Comment by ecederstrand** [comment]
According to the response, the account has 751 folders. So either this is in fact an endless loop, and we have a bug in the paging of results from the `FindFolder` service request, or you're just impatient and we haven't finished the 8 requests needed to get 751 folders in pages of 100 :-)

If you use the XML pretty-printer (see https://github.com/ecederstrand/exchangelib#troubleshooting), it should be quite obvious if we are progressing or requesting the same page over and over. Here's a snippet from your output:

```xml
                <m:FindFolderResponseMessage ResponseClass="Success">
                    <m:ResponseCode>NoError</m:ResponseCode>
                    <m:RootFolder IndexedPagingOffset="1" TotalItemsInView="751" IncludesLastItemInRange="false">
                        <t:Folders/>
                    </m:RootFolder>
                </m:FindFolderResponseMessage>
```

The `IndexedPagingOffset` should increase for each request.

**Comment by driesken** [comment]
Thanks for the fast response. I've waited for a few minutes, but it seems to continue looping?

Looks like it is indeed stuck at the same page:
DEBUG:exchangelib.services:FindFolder: Got page with next offset 1 (last_page False)

**Comment by ecederstrand** [comment]
In that case, I'm pretty sure there's a bug. It will probably be a couple of days before I have time to look at this. The code that handles this is https://github.com/ecederstrand/exchangelib/blob/cd891106ed50eaaf72c6e5307802c95c95bbd048/exchangelib/services.py#L309

You're welcome if you want to take a stab at this yourself until then.

**Comment by ecederstrand** [comment]
Actually, I think this is a broken response from the Exchange server:

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="339" MinorBuildNumber="0"
                             Version="Exchange2010_SP2"
                             xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
                             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <m:FindFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
                              xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:FindFolderResponseMessage ResponseClass="Success">
                    <m:ResponseCode>NoError</m:ResponseCode>
                    <m:RootFolder IndexedPagingOffset="1" TotalItemsInView="751" IncludesLastItemInRange="false">
                        <t:Folders/>
                    </m:RootFolder>
                </m:FindFolderResponseMessage>
            </m:ResponseMessages>
        </m:FindFolderResponse>
    </s:Body>
</s:Envelope>
```

It's claiming to have not be the last page (`IncludesLastItemInRange` is false), but there are no folders in the response, so our page offset is never progressing.

We should be better at catching this situation by adding an assert somewhere. I see we already have an exception in https://github.com/ecederstrand/exchangelib/blob/cd891106ed50eaaf72c6e5307802c95c95bbd048/exchangelib/services.py#L856 because Exchange 2010 doesn't support paging in this context. Maybe that should be changed to include Exchange 2010 SP2 which is what you're connecting to?

**Comment by driesken** [comment]
It is indeed Exchange 2010 SP2 I'm trying to connect to. I've modified the line in /usr/lib/python2.7/site-packages/exchangelib-1.10.4-py2.7.egg/exchangelib/services.py as you suggested but unfortunately it doesn't seem to have any effect.

```
if self.account.version.build >= EXCHANGE_2010_SP2:
            indexedpageviewitem = create_element('m:IndexedPageFolderView', MaxEntriesReturned=text_type(page_size),
                                                 Offset=text_type(offset), BasePoint='Beginning')
```

**Comment by ecederstrand** [comment]
Oh, I'm sorry if I was unclear. The problem may be that your Exchange version doesn't support the `IndexedPageFolderView` element, so try disabling that. A simple way to do this:

```python
if False:
            indexedpageviewitem = ...
```

**Comment by driesken** [comment]
I've modified services.py but I'm still getting the (assert) Offset error.

>     def get_payload(self, additional_fields, shape, depth, page_size, offset=0):
        findfolder = create_element('m:%s' % self.SERVICE_NAME, Traversal=depth)
        foldershape = create_element('m:FolderShape')
        add_xml_child(foldershape, 't:BaseShape', shape)
        if additional_fields:
            additional_properties = create_element('t:AdditionalProperties')
            expanded_fields = chain(*(f.expand(version=self.account.version) for f in additional_fields))
            set_xml_value(additional_properties, sorted(expanded_fields, key=lambda f: f.path), self.account.version)
            foldershape.append(additional_properties)
        findfolder.append(foldershape)
        #if self.account.version.build == EXCHANGE_2010_SP2:
        if False:
            indexedpageviewitem = create_element('m:IndexedPageFolderView', MaxEntriesReturned=text_type(page_size),
                                                 Offset=text_type(offset), BasePoint='Beginning')
            findfolder.append(indexedpageviewitem)
        else:
            assert offset == 0, 'Offset is %s' % offset
        parentfolderids = create_element('m:ParentFolderIds')
        set_xml_value(parentfolderids, self.folders, version=self.account.version)
        findfolder.append(parentfolderids)
        return findfolder

DEBUG:

> DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account xxxxxxx@xxxxxxx.be
DEBUG:exchangelib.services:Not last page in range, but Exchange didn't send a page offset. Assuming first page
DEBUG:exchangelib.services:FindFolder: Got page with next offset 1 (last_page False)
DEBUG:exchangelib.folders:Folder class <class 'exchangelib.folders.Folder'> matches container class None (Freebusy Data)
DEBUG:exchangelib.services:EWS https://mail.xxxxxxx.be/EWS/Exchange.asmx, account xxxxxxx@xxxxxxx.be, service FindFolder: Getting items at offset 1


Am I doing something wrong?

**Comment by ecederstrand** [comment]
The response from your server is basically broken. We're requesting folders 1-100 of the `FindFolder` result. The server responds with an empty list and a header saying this is a list of folders starting at item 1, there are 751 in all, and there are more to fetch. That doesn't make any sense at all.

You could try to revert your local patches, and instead change the `page_size=100` to `page_size=1000` here: https://github.com/ecederstrand/exchangelib/blob/cd891106ed50eaaf72c6e5307802c95c95bbd048/exchangelib/folders.py#L492

Maybe the server behaves better if we try to get everything in one go.

**Comment by driesken** [comment]
Ah, I understand. I've reverted my changes (so services.py is stock again) and modified the page_size variable in folders.py. Unfortunately, the loop is there again.

> DEBUG:exchangelib.util:Session 29492 thread 140326023874368: Useful response from https://mail.xxxxxxx.be/EWS/Exchange.asmx
DEBUG:exchangelib.protocol:Server mail.xxxxxxx.be: Releasing session 29492
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account xxxxxxx@xxxxxxx.be
DEBUG:exchangelib.services:FindFolder: Got page with next offset 1 (last_page False)
DEBUG:exchangelib.services:EWS https://mail.xxxxxxx.be/EWS/Exchange.asmx, account xxxxxxx@xxxxxxx.be, service FindFolder: Getting items at offset 1
DEBUG:exchangelib.protocol:Server mail.xxxxxxx.be: Waiting for session
DEBUG:exchangelib.protocol:Server mail.xxxxxxx.be: Got session 29492
DEBUG:exchangelib.util:Session 29492 thread 140326023874368: retry 0 timeout 120 POST'ing to https://mail.xxxxxxx.be/EWS/Exchange.asmx after 10s wait
/usr/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
DEBUG:urllib3.connectionpool:https://mail.xxxxxxx.be:443 "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 29492
Thread: 140326023874368
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x3de2110>
URL: https://mail.xxxxxxx.be/EWS/Exchange.asmx
HTTP adapter: <exchangelib.protocol.NoVerifyHTTPAdapter object at 0x3d74f90>
Allow redirects: False
Response time: 0.018275976181
Status code: 200
Request headers: {'Content-Length': '1219', 'Accept-Encoding': u'compress, gzip', 'Accept': '*/*', 'User-Agent': 'python-requests/2.18.4', 'Connection': 'Keep-Alive', 'Cookie': 'X-BackEndCookie=S-1-5-21-3222743990-3588243504-3938062828-46253=rJqNiZqNgb2zzsnSz8fRnpbRlpGLmo2RnpPRioWYmpGL0Z2agc7GzMjGxsjGy8iBzc/OyNLOztLOyavOy8XKx8XLzw==; exchangecookie=6890bf64d58146888e98003578043c52', 'Content-Type': u'text/xml; charset=utf-8'}
Response headers: {'X-CalculatedBETarget': 'xxxxx.be', 'Set-Cookie': 'X-BackEndCookie=S-1-5-21-3222743990-3588243504-3938062828-46253=rJqNiZqNgb2zzsnSz8fRnpbRlpGLmo2RnpPRioWYmpGL0Z2agc7GzMjGxsjGy8iBzc/OyNLOztLOyavOy8XKx8XLzw==; expires=Thu, 16-Nov-2017 14:58:40 GMT; path=/EWS; secure; HttpOnly', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'request-id': 'e09e8c67-db69-4266-bd82-1b25d9525427', 'X-AspNet-Version': '4.0.30319', 'Vary': 'Accept-Encoding', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/10.0', 'X-FEServer': 'VMAILBOXSVR2P', 'Cache-Control': 'private', 'Date': 'Thu, 16 Nov 2017 14:48:39 GMT', 'Content-Type': 'text/xml; charset=utf-8'}
Request data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2" /><t:TimeZoneContext><t:TimeZoneDefinition Id="Romance Standard Time" /></t:TimeZoneContext></s:Header><s:Body><m:FindFolder Traversal="Deep"><m:FolderShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="folder:ChildFolderCount" /><t:FieldURI FieldURI="folder:EffectiveRights" /><t:FieldURI FieldURI="folder:FolderClass" /><t:FieldURI FieldURI="folder:DisplayName" /><t:FieldURI FieldURI="folder:ParentFolderId" /><t:FieldURI FieldURI="folder:TotalCount" /><t:FieldURI FieldURI="folder:UnreadCount" /></t:AdditionalProperties></m:FolderShape><m:IndexedPageFolderView BasePoint="Beginning" MaxEntriesReturned="1000" Offset="1" /><m:ParentFolderIds><t:DistinguishedFolderId Id="root"><t:Mailbox><t:EmailAddress>xxxxxxx@xxxxxxx.be</t:EmailAddress><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:ParentFolderIds></m:FindFolder></s:Body></s:Envelope>
Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="339" MinorBuildNumber="0" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:FindFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:FindFolderResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:RootFolder IndexedPagingOffset="1" TotalItemsInView="415" IncludesLastItemInRange="false"><t:Folders/></m:RootFolder></m:FindFolderResponseMessage></m:ResponseMessages></m:FindFolderResponse></s:Body></s:Envelope>

**Comment by driesken** [comment]
We've migrated the mailbox to our new environment (V2016_10_10) and now it is working perfect.

**Comment by ecederstrand** [comment]
Ok. Good to know. This seems to confirm it was a bug in your specific Exchange version.
