### ISSUE TITLE
Get item by item_id only without changekey

### ISSUE THREAD

**Issue by finkandreas** [ecederstrand/exchangelib#295]
Hi,
I need the feature to get an item by item_id only without a changekey. Basically what I try to achieve is a one-way sync, where the changekey could have been changed by somebody using the OWA frontend. Nevertheless I want to update already existing items, i.e. preferably I want to fetch the item with the current changekey.
What I did is to update the ItemId class in properties.py and set `is_required=False`, and use `account.fetch([("unique_item_id", None)])` and everything works.
Would you consider to apply this change so I wouldn't have my own version of exchangelib, or what is the reason that you set is_required=True?

**Comment by ecederstrand** [comment]
Of, I didn't know that you can fetch an item without the changekey. We should definitely remove that restriction.

**Comment by ecederstrand** [comment]
Fixed in https://github.com/ecederstrand/exchangelib/commit/a4dbbab63d62994bcb4e32441e3ad99e6b4b7539
