### ISSUE TITLE
Access to shared calendar events

### ISSUE THREAD

**Issue by alexs555** [ecederstrand/exchangelib#296]
Hello!
I'd like to ask if there are an opportunity to access events from other calendars, that I add to my outlook calendar(other people, meetings rooms, etc). I explored source code, but found nothing( 
![share-outlook-folders](https://user-images.githubusercontent.com/3940001/32984394-dfb0f094-ccb6-11e7-9899-0017bc01ad5e.gif)

**Comment by ecederstrand** [comment]
Yes, that's possible. If you want to connect to there accounts than your own, see https://github.com/ecederstrand/exchangelib#setup-and-connecting

**Comment by alexs555** [comment]
Thanks for reply, but I think that it not an option. I don't own all those accounts (take a look at picture), I just want to see their public events being logged in in my account

**Comment by ecederstrand** [comment]
Have you tried? You don’t need to own these accounts, you just need to have sufficient premissions to access them.

**Comment by alexs555** [comment]
Oh, I tried and connection seems to be succedded!

```
root
└── Freebusy Data
```
I feel that this

**Comment by ecederstrand** [comment]
Just have a look at the contents of that folder:

```python
for item in (account.root / 'Freebusy Data').all():
    print(item.__class__, item.subject)
```

**Comment by ecederstrand** [comment]
Hi @alexs555 Did you find the data you were looking for? If so, feel free to close this issue.
