### ISSUE TITLE
How to filter items based on list of itemIds

### ISSUE THREAD

**Issue by rsrini83** [ecederstrand/exchangelib#297]
Hi,

Is there anyway to filter items by itemid ? 

--Srinu

**Comment by ecederstrand** [comment]
Yes, there is. If you also have the change keys, use [fetch()](https://github.com/ecederstrand/exchangelib#bulk-operations). Otherwise, see https://github.com/ecederstrand/exchangelib/issues/295

**Comment by rsrini83** [comment]
Yes, i realized after i post and i referred issue #295, was able to download. 
Thanks for quick reply.
