### ISSUE TITLE
Sender's Information

### ISSUE THREAD

**Issue by DeepakLabh** [ecederstrand/exchangelib#298]
Hi all,

I was wondering if there are any methods to get sender's information (specifically country) via EWS or any other services.

As there is option from Microsoft Outlook account where you can view everyone's infos.

Thanks.

**Comment by ecederstrand** [comment]
I think that would require an implementation of https://github.com/ecederstrand/exchangelib/issues/93

It would only work for in-house users, of course.

**Comment by ecederstrand** [comment]
Closing as duplicate of #93
