### ISSUE TITLE
BadHanshake  error after upgrading to latest ExchangelIb Package

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#299]
Hi,

After upgrading from exchangelib 1.9.3 to latest verison I see following error? Is there any immediate workaround as we are blocked with this issue?
[HTTPSConnectionPool(host='exch2013cas-1.testexch.commvault.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))]

**Comment by ecederstrand** [comment]
You can disable SSL for now, as described in https://github.com/ecederstrand/exchangelib#setup-and-connecting. But ideally you should find a way to validate the certificate of the server. This is outside the scope of exchangelib, but there are some suggestions in https://github.com/ecederstrand/exchangelib/issues/215

**Comment by shireen91** [comment]
I built my own certificate authority
and installed wild card certificate issued by my own certificate authority + root certificate of  certificate authority
After ECP/OWA started working very well (without certificate error)

But still library gives same error. I never got the error with exchangelib 1.9.3 version.
After upgrading to latest version. I see this error. DId you change anything in latest version?

**Comment by ecederstrand** [comment]
There is no special handling of SSL certificates in exchangelib. We just use the `requests` package. So `requests` would probably also fail if you just do `requests.get('https://your.example.com/EWS/Exchange.asmx')`.

You may get the error now because pip decided to also install a newer version of `requests` or `certifi`.
