### ISSUE TITLE
Support all distinguished folders as properties on Account

### ISSUE THREAD

**Issue by DmytroLapshyn** [ecederstrand/exchangelib#301]
Hi,

I once had to make a small addition to this excellent library to enable it to recognize search folders. I am by no means a professional Python developer so I thought I would just share a code snippet rather than making a full-fledged pull request:

```
class SearchFolders(Folder):
    DISTINGUISHED_FOLDER_ID = 'searchfolders'
    supported_item_models = ITEM_CLASSES

    LOCALIZED_NAMES = {
        'en_US': (u'Search Folders',),
        # TODO: Add more localizations
    }
```

```
searchfolders = account.root.get_default_folder(SearchFolders)
for folder in searchfolders.find_folders(shape="AllProperties"):
        print(folder.name)
```

Hopefully someone will find this useful.

**Comment by ecederstrand** [comment]
Thanks! According to https://msdn.microsoft.com/en-us/library/office/aa580808(v=exchg.150).aspx we're missing support for a whole range of these. I think it makes sense to support them all as properties on the `Account` class, like we do for e.g. `Account.inbox`.

**Comment by DmytroLapshyn** [comment]
> I think it makes sense to support them all as properties on the Account class, like we do for e.g. Account.inbox.

Absolutely, that would be the best way to support them.
