### ISSUE TITLE
Creating a calendar item with location set to a room

### ISSUE THREAD

**Issue by romainrichard** [ecederstrand/exchangelib#303]
Somewhat similar to #245, I'm having an issue with the `location` field.

I have a room named "My Room" that has the following email address: myroom@example.com.
I want to create a calendar item that will be set in that room, so I tried setting the `location` field to the room's name or email address, but the event that gets created only has the string as location instead of actually being linked to the room.
Meaning that when I look at the event, I see that the location is "My Room" or "myroom@example.com", literally. So the room doesn't actually get booked.

In #245 you said:
> So just use any string value that identifies the room.

Do you have an example as to what I should be using to make my use case work?

**Comment by ecederstrand** [comment]
The `location` field is just a string value on the Exchange server. It's purely informational and cannot contain a reference to a room account. To book a room and have it show up in the calendar or that room, you must add myroom@example.com to the `required_attendees` list.

**Comment by romainrichard** [comment]
I created an event through the Exchange web UI and added the room in question to the event.
When getting the event through `exchangelib`, I see the following extra properties (compared to creating the event through `exchangelib`):
```
X-MICROSOFT-LOCATIONDISPLAYNAME:My Room
X-MICROSOFT-LOCATIONSOURCE:Resource
X-MICROSOFT-LOCATIONURI:myroom@example.com
```

Am I correct to assume that I can't set those fields with `exchangelib`?

**Comment by ecederstrand** [comment]
Was this on the `mime_content` attribute? EWS does support writing to this field, but exchangelib doesn't (yet). Do you have a need for these values that cannot be solved by using `required_attendees`?

**Comment by romainrichard** [comment]
Correct it is in the `mime_content` attribute.
I wouldn't say I have a need for this because the room does get booked which is the goal, but it would have been nicer if I could also set the location as one would do through the web UI.
Since this is not available yet I'll close this issue.

Thanks for being so responsive, really appreciate it.
