### ISSUE TITLE
Usage of is_online_meeting

### ISSUE THREAD

**Issue by R3alAli** [ecederstrand/exchangelib#307]
Hello,

Great library, thanks! I am trying to add an online meeting to the calendar invite that is created. I am unsure where to declare is_online_meeting = True . I saw you had added that additional Calendar Item a couple days ago.

Any guidance is much appreciated. Below is a snippet of what I am doing:

```python
calendaritem = CalendarItem(
        start = time,
        end = time + timedelta(minutes = 30),
        subject='SUBJECT',
        body='BODY',
        location = 'LOCATION',
        account = user_account,
        folder = user_account.calendar,
        required_attendees = [
        	Attendee(mailbox=Mailbox(email_address = 'EMAIL'), response_type='Accept'), 
        	Attendee(mailbox=Mailbox(email_address = 'EMAIL2'))
        ],
   )
calendaritem.save()
calendaritem.save(is_online_meeting = True) #Is it correct here?
calendaritem.save(send_meeting_invitations=SEND_ONLY_TO_ALL)
```

**Comment by ecederstrand** [comment]
`is_online_meeting` goes in the constructor like the other attributes. Or you can set `calendaritem.is_online_meeting = True` before `calendaritem.save()`

**Comment by R3alAli** [comment]
Thanks for the quick reply. OK so I did try your first suggestion, looks like this:

calendaritem = CalendarItem(
    start = time,
    end = time + timedelta(minutes = 30),
    subject='SUBJECT',
    body='BODY',
    location = 'LOCATION',
    account = user_account,
    folder = user_account.calendar,
    required_attendees = [
    	Attendee(mailbox=Mailbox(email_address = 'EMAIL'), response_type='Accept'), 
    	Attendee(mailbox=Mailbox(email_address = 'EMAIL2'))
    	],
    is_online_meeting = True
)
calendaritem.save()
calendaritem.save(send_meeting_invitations=SEND_ONLY_TO_ALL)

I get the following error:

exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: <ns0:FieldURI xmlns:ns0="http://schemas.microsoft.com/exchange/services/2006/types" FieldURI="calendar:IsOnlineMeeting" />)

**Comment by ecederstrand** [comment]
Do you get the error on the first or second call to `save()`? Also, [this](https://stackoverflow.com/questions/31542914/meeting-request-properties-not-settable-in-ews-soap-calls) suggests the property is read-only, but says it's read-writable by the organizer. So I'm not really sure who's right.

**Comment by R3alAli** [comment]
The 2nd call. Interesting link.

**Comment by ecederstrand** [comment]
Ok. The second call is redundant. Just remove it (or the first one if you need the merting invitation setting). The 2nd call results in an update, so `is_online_meeting’ probably only supports inserats, not updates, on your Exchange version.

**Comment by R3alAli** [comment]
No dice, it is now happening on the only `save()` call. Same error as before.

**Comment by ecederstrand** [comment]
Well, that makes no sense at all. You deleted the 2nd statement, and now the first one fails?

**Comment by R3alAli** [comment]
I misread the log, my apologies. It fails on the first call to `save()` in the first scenario. And fails on the only call to `save()` in the 2nd scenario.

**Comment by ecederstrand** [comment]
I don't have access to an account with impersonation access to another account ATM, so I can't test this. Using `DELEGATE` access, I have no issues with `is_online_meeting`.

**Comment by ecederstrand** [comment]
Re-visiting https://msdn.microsoft.com/en-us/library/office/aa565195(v=exchg.150).aspx:

> The IsOnlineMeeting property is read-writable for the organizer's calendar item. It is read-only for meeting requests and for attendees' calendar items.

You may have been updating one of the items for which this property is read-only. However, even when I create a test item with myself as organizer, I still can't write the property. So I'm just parking it read-only in all cases in this library.
