### ISSUE TITLE
Getting the ical feed for a calendar

### ISSUE THREAD

**Issue by romainrichard** [ecederstrand/exchangelib#308]
I've been able to get calendar events by using `events = account.calendar.view(start, end)`, then I can do something like this to get the raw ical feed for each event:
```
for event in events:
    print(event.mime_content)
```

I was wondering if there was a way to get the full ical feed for the calendar instead of having bits of it in each event, something like `account.calendar.mime_content`.
The reason I'm asking is because the product I'm working on currently relies on getting the full ical feed so it'd be easier to integrate with `exchangelib` if it did support that.
If not I'm sure we can find a way around it, maybe something like:
```
ical_feed = "".join(account.calendar.view(start, end).values_list("mime_content", flat=True))
```

**Comment by ecederstrand** [comment]
I think your own suggestion is a nice one-liner that (hopefully) does what you want. I've looked aruond a bit and don't see any specific EWS services to export ical feeds specifically.

We *could* add an `account.calendar.ical` helper, but then you would still want to specify the start and end dates, so there's not much extra value in having a helper.

**Comment by romainrichard** [comment]
Gotcha, thanks for checking!
