### ISSUE TITLE
Debug logging not working due to encoding issues

### ISSUE THREAD

**Issue by adrinavarro** [ecederstrand/exchangelib#309]
Hi!

I'm running a script that inserts contacts in batches to EWS. While debugging unusual behaviour (such as entire batches altogether apparently not being inserted) I have noticed that there are debug log items missing from the output. However, there's the following trace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3207: ordinal not in range(128)
Logged from file util.py, line 465
```

This seems to come from [util.py:465](https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/util.py#L465), where a post request is logged (for a bulk_create, etc).

I'm running Python 2.7. There's a chance this might not happen in Python 3 due to improved unicode support, however, changing the version is sadly not a possibility for me.

I'm strongly inclined to believe this is caused by UTF-8 characters in either xml_request or xml_response, as I'm manipulating items with accents in them.

A possible solution would be to encode or sanitize those fields in a way that makes them compatible with Python's logging module.

I will keep investigating on my end and propose any tested solutions I come up with, however, any comments are appreciated, as I have yet to figure out why this logging call fails while all other operations are successfully logged.

**Comment by ecederstrand** [comment]
Hmm, the XML request (`data`) is supposed to be a `bytes` object at this point, and so is `r.content`. All other values in `log_vals` are either non-strings or contain only ASCII characters. Python shouldn't need to decode anything. Are you sure that the error comes from util.py:465?

**Comment by adrinavarro** [comment]
It's what the log says, and my project has no file named "util.py". See:

```
cat /var/log/runner.log | grep "Logged from file util.py, line 465" | wc -l
544
```

**Comment by ecederstrand** [comment]
Thanks for checking :-) Unless something really wierd is going on, there must be a unicode object somewhere in the log values after all. You could try to `print(repr(log_msg)); print(repr(log_vals))` in line 464 and run your code again. That should make it apparent.

**Comment by adrinavarro** [comment]
Thanks!

So I think I got the culprit. The xml_response (for contacts insertion) has phone numbers formatted as follows: "<t:PhoneNumbers><t:Entry Key="HomePhone">(123)\xc2\xa1234-1234</t:Entry>"

The logging utility (as per Python's source code) attempts to convert that to ascii, and it can't output that character, thus the error.

**Comment by ecederstrand** [comment]
Ah, there we have it. `log_msg` should be a `str`, not a `unicode` string. Try making `log_msg` an `str` explicitly with the `b` prefix:

```python
log_msg = b'''\
...
'''
```

What happens is that string formatting tries to implicitly convert the arguments to unicode:

```python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> u'%s' % 'æøå'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
>>> 
>>> 
>>> b'%s' % 'æøå'
'\xc3\xa6\xc3\xb8\xc3\xa5'
>>>
```

I don't know why this happens because by default, strings in Python2 are supposed to be bytes, not unicode.

**Comment by ecederstrand** [comment]
Feel free to re-open if the referenced commit does not fix your problem :-)

**Comment by adrinavarro** [comment]
Hi! Thank you A LOT for taking the time to ponder on my very own issue :-)

The commit did not fix this issue… I kept investigating and did a short snippet to reproduce it in Python 2.7:

```from __future__ import unicode_literals

import logging

logging.basicConfig()

log = logging.getLogger()
log.setLevel(logging.DEBUG)

payload = b'<t:PhoneNumbers><t:Entry Key="HomePhone">(123)\xc2\xa1234-1234</t:Entry>'

log_msg_normal = 'Test: %(test)s'
log_msg_new = 'Test: %(test)r'

log_vals = dict(test=str(payload))

print(repr(log_msg_new))
print(repr(log_msg_normal))
print(repr(log_vals))

log.debug(log_msg_new, log_vals)
log.debug(log_msg_normal, log_vals)```

I think the solution would be to use `%(xml_request)r` and `%(xml_response)r` in the `log_msg` template. %(…)r instead of %(…)s calls `repr` when formatting, and would remain efficient as `repr` would not be called unless debug is enabled.

**Comment by ecederstrand** [comment]
[I'm sorry, Dave, I'm afraid I can't do that](https://www.youtube.com/watch?v=7qnd-hdmgfk) :-) It would mess up debug messages by adding quotes to the output:

```python
DEBUG:root:Test: '<t:PhoneNumbers><t:Entry Key="HomePhone">(123)\xc2\xa1234-1234</t:Entry>'
```

The strange thing is that when I apply the fix from the commit to your reproducer (converting `log_msg_*` to `str` explicitly to circumvent `unicode_literals`) then it fixes the issue:

```python
from __future__ import unicode_literals

import logging

logging.basicConfig()

log = logging.getLogger()
log.setLevel(logging.DEBUG)

payload = b'<t:PhoneNumbers><t:Entry Key="HomePhone">(123)\xc2\xa1234-1234</t:Entry>'

log_msg_normal = str('Test: %(test)s')
log_msg_new = str('Test: %(test)r')

log_vals = dict(test=str(payload))

print(repr(log_msg_new))
print(repr(log_msg_normal))
print(repr(log_vals))

log.debug(log_msg_new, log_vals)
log.debug(log_msg_normal, log_vals)
```

So either there's something else going on, or you accidentally ran last the test with a version of exchangelib without the patch.

**Comment by adrinavarro** [comment]
Actually, you're absolutely right. I apologize. Turns out the issue is twofold… ahhh, I wish this was Python 3 :)

Somewhere else in my app, the logger is initialised with a custom log format. This format is according to Python's documentation: https://docs.python.org/2/library/logging.html

Somehow, with the default log format it works just fine, but with the custom one it doesn't work.

```
from __future__ import unicode_literals

import logging

logging.basicConfig(format='%(asctime)s - %(threadName)s - %(levelname)s - %(name)s - %(message)s')
# logging.basicConfig()

log = logging.getLogger()
log.setLevel(logging.DEBUG)

payload = b'<t:PhoneNumbers><t:Entry Key="HomePhone">(123)\xc2\xa1234-1234</t:Entry>'

log_msg_normal = str('Test: %(test)s')

log_vals = dict(test=str(payload))

print(repr(log_msg_normal))
print(repr(log_vals))

log.debug(log_msg_normal, log_vals)
```

I think the fix on my end will be to change `%(message)s` to `%(message)r`. I can do with the quotes! And I think it will be more helpful for me, as non-ascii chars are not converted but instead output as unicode with the backslash.

**Comment by ecederstrand** [comment]
Yes, lots of things are so much better in Python3 :-)

It makes sense that you're having the problem with a custom format. However, the `unicode_literals` at the top is playing tricks with your custom format, too, so you could just force that to a `str`:

```python
from __future__ import unicode_literals

import logging

logging.basicConfig(format=str('%(asctime)s - %(threadName)s - %(levelname)s - %(name)s - %(message)s'))
# logging.basicConfig()
...
```

That makes the problem go away, at least on my machine.

**Comment by adrinavarro** [comment]
Wow, good point. Actually, my config is loaded from a dict extracted from a
JSON file and passed directly to logger.config.dictConfig, so I don't think
there's an easy way to force str there… I think changing the format from %s
to %r might be the path of least resistance.

**Comment by ecederstrand** [comment]
Yeah, you could prepare the dict before pasning it to dictConfig().

Anyway, thanks for your thorough report. It’s issues like these that make exchangelib better :-)
