### ISSUE TITLE
Read timed out, question

### ISSUE THREAD

**Issue by change94** [ecederstrand/exchangelib#311]
Hey, i made a script that uses your great library. Its running once every minute and is collecting some data from the exchange... So far everything works just fine. But after every ~40 minutes i get a "read timeout" from the exchange. After the timeout it works fine till the next 40 minutes passed. Do i have to close the socket or something to prevent this?

Error message : HTTPSConnectionPool(host='#.#.#.#', port=####): Read timed out. (read timeout=120)

**Comment by ecederstrand** [comment]
If you're polling every minute, then connections should stay open. But it's possible that the remote server is closing connections after a timeout on their side.

Long-running scripts is what the `ServiceAccount` class was created for. See https://github.com/ecederstrand/exchangelib#setup-and-connecting. You could try using that class instead, if you're not doing so already. This will paper over minor glitches in the connection.

**Comment by change94** [comment]
ServiceAccount fixed it thanks!
