### ISSUE TITLE
XML debug log message fail to convert

### ISSUE THREAD

**Issue by earlchew** [ecederstrand/exchangelib#312]
I'm not sure that https://github.com/ecederstrand/exchangelib/issues/309 is really resolved:

```
    # In Python 2, we want this to be a 'str' object so logging doesn't break (all formatting arguments are 'str').
    # We activated 'unicode_literals' at the top of this file, so it would be a 'unicode' object unless we convert
    # to 'str' explicitly. This is a no-op for Python 3.
    log_msg = str('''\
```

```
Traceback (most recent call last):
  File "/home/earlchew/Local/pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/home/earlchew/Local/pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/home/earlchew/Local/pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()^M
  File "/home/earlchew/Local/pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16258: ordinal not in range(128)
```

This article speaks to the issue at length in particular with respect to HTML content: https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

> HTTP
>
> Web pages can be encoded in just about any encoding. The Content-type header should contain a charset field to hint at the encoding. The content can then be decoded manually against this value. Alternatively, Python-Requests returns Unicodes in response.text.

**Comment by ecederstrand** [comment]
`UnicodeDecodeError` happens because Python2 wants to convert a `unicode` object to a `str`. The patch changed logging on Python2 so both the log message and log arguments are `str`.

So either your test didn't happen on an exchangelib containing the patch, or we still have unicode arguments somewhere that are converted implicitly.

It's my understanding that logging in Python2 should be done with `str` objects, not `unicode`. Your PR goes against that.

I'm not fond of decoding the full HTTP response on every request, when it's only used in a debug log message that probably won't be used 99% of the time. Let's find out why you're still getting the `UnicodeDecodeError` and provide a fix for that.

**Comment by earlchew** [comment]
@ecederstrand Triple quoted strings are of type `str`:
```
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> type(
... '''
... TEST
... ''')
<type 'str'>
```

So `str(''' ... ''')` is tautological, but harmless.

> I'm not fond of decoding the full HTTP response on every request ...

Yes, that's a good point, and an oversight on my part. I misread the `finally` as an `except` when hacking. Let me try to rectify that.

**Comment by earlchew** [comment]
https://stackoverflow.com/questions/18034272/python-str-vs-unicode-types
> Note: In Python 3, unicode was renamed to str and there is a new bytes type for a plain sequence of bytes.

Checking:

```
Python 3.6.1 (default, Dec 2015, 13:05:11)
[GCC 4.8.2] on linux
   type(''' ... ''')
=> <class 'str'>   
```

**Comment by ecederstrand** [comment]
I'm aware that triple-quoted strings are of type `str` in Python2, but `utils.py` imports `unicode_literals` at the top, which chages this:

```python
$ python2.7
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import unicode_literals
>>> type('''xxx''')
<type 'unicode'>
```

**Comment by ecederstrand** [comment]
Actually, I think what's happening is the other strings in the format arguments being unicode, which forces the entire log message to become unicode. Here's an example:

```python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import unicode_literals
>>> b'foo %(bar)s %(baz)s' % {'bar': u'æøå', 'baz': b'xyz'}
u'foo \xe6\xf8\xe5 xyz'
```

**Comment by ecederstrand** [comment]
The only candidate I can find for requiring explicit conversion to `str` in `log_vals` is `r.url`. The rest are `bool`, `int`, `timedelta`, `dict` or classes that don't have custom `__str__` methods. `data` and `r.content` should already be `str` at this point.

Can you try replacing `r.url` with `str(r.url)` in https://github.com/ecederstrand/exchangelib/blob/9ef6d58b44c33bf5cf5164a5b96cf118ec57cdc1/exchangelib/util.py#L464 and see if that fixes your issue?

**Comment by earlchew** [comment]
I reverted all my changes to `util.py` and poked around some more for the issue I am seeing.

I confirmed that the problem relates to `%(xml_response)s`. Removing the line marked `###` causes the error message to go away.

```
    log_msg = str('''\
Retry: %(retry)s
Waited: %(wait)s
Timeout: %(timeout)s
Session: %(session_id)s
Thread: %(thread_id)s
Auth type: %(auth)s
URL: %(url)s
HTTP adapter: %(adapter)s
Allow redirects: %(allow_redirects)s
Response time: %(response_time)s
Status code: %(status_code)s
Request headers: %(request_headers)s
Response headers: %(response_headers)s
Request data: %(xml_request)s
Response data: %(xml_response)s   ####
''')
```

Using the information in the error message, I dumped the content of `r.content`:

```
  File "/home/earlchew/Local/pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5115: ordinal not in range(128)
```

That position in `r.content` contains the following octets:

```
0000000   t   ;   L   e   t 342 200 231   s     
         74  3b  4c  65  74  e2  80  99  73  20 
```

That particular sequence `e2 80 99` corresponds to an apostrophe: `Let’s`

My understanding of the problem is this:
* The encoding of `r.content` is determined by the choice of `charset` in the headers. In this case it is `utf-8`.
* Although `log_msg` is created as `str` using 241b0fee, the `msg % self.args` operation seems to want to convert the `r.content` to unicode.
* Without guidance, the conversion uses the ascii code which fails on the utf-8 encoded characters in the text.

Digging into `logging.py` I added:

```
        if self.args:
            print '@@@', type(msg)
            msg = msg % self.args
```

Perplexingly, this shows:

```
@@@ <type 'str'>
Traceback (most recent call last):
...
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5115: ordinal not in range(128)
```

I tried boiling this down to a test case:

```
# -*- coding: utf-8 -*-

t = 'Let’s'
f = '%s'
x = f % t
```

But this works as advertised, so there's something else going on.

I can confirm that I do not see the error message when I use the changes I proposed.

**Comment by ecederstrand** [comment]
Did you try replacing `r.url` with `str(r.url)` as I suggested?

**Comment by earlchew** [comment]
> I think it wants to do this because one of the values in `self.args` (i.e. `r.url`) is unicode

Yes. I've confirmed that your hunch is correct. This approach also fixes the problem.

I've revised the commit to reflect this.
