### ISSUE TITLE
AutoDiscoverFailed

### ISSUE THREAD

**Issue by cr1010** [ecederstrand/exchangelib#316]
Hi, I have recently started receiving an autodiscover error after upgrading to latest version. The error is:
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

My code is:
credentials = Credentials(username="my@email.onmicrosoft.com", password="mypassword")
account = Account(
    primary_smtp_address="my@email.onmicrosoft.com", autodiscover=True, credentials=credentials,
    access_type=DELEGATE)
folders = account.folders

Can you please advise how I can resolve this?

**Comment by ecederstrand** [comment]
The first thing to do is test that autodiscover actually works for your account. You can do this at https://testconnectivity.microsoft.com

If that works, you'll need to enable debug logging in exchangelib and compare the autodiscover steps in the debug output with the steps performed in the report you get from https://testconnectivity.microsoft.com, to see where we're failing.

**Comment by ecederstrand** [comment]
Hi @cr1010 Did you manage to find a solution?

**Comment by ecederstrand** [comment]
Closing due to timeout. Feel free to re-open if you have more details about this issue.
