### ISSUE TITLE
Exchangelib stuck when reading contacts

### ISSUE THREAD

**Issue by adrinavarro** [ecederstrand/exchangelib#318]
I'm extracting contacts from an EWS account (Office 365 hosted):

```
exchangelib.protocol.BaseProtocol.SESSION_POOLSIZE = 1
…
account = exchangelib.Account(…)
query = account.contacts.all()
contacts = list(item for item in query.iterator() if isinstance(item, exchangelib.items.Contact))
```

The account in question has ~267 contacts. This usually works well, but it sometimes gets stuck forever in `Waiting for GetItem._get_elements result n of n` ([services.py:453](https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/services.py#L453)), as if `r.get()` never returned.

Here's part of the log (removing the full request headers / responses, I can provide the entire log via email): https://gist.github.com/adrinavarro/82672f4c6c7612ba4e187aef977400a0

I've seen this happen as well before "SESSION_POOLSIZE" was adjusted (this is because we hit Office365 for several accounts at once and at some point it felt a bit like a DDos).

**Comment by ecederstrand** [comment]
If you turn on debug logging, you may get a clue why it's stuck. My guess its that you're still being hit by rate-limiting policies on the Exchange server. If that is the case, the log will contain repeated HTTP timeouts or HTTP 401 responses. This assumes you're using the `ServiceAccount` class, of course.

**Comment by adrinavarro** [comment]
Debug logging is on (see gist). I'm using impersonation to log in.

I've noticed that my code does first initialize the connection (with Account), watch for exceptions (thus checking the password), then close the connection by invoking ```account.protocol.close(); exchangelib.protocol.close_connections()```. And again, it calls the same routine to initialize the connection/object when it's going to read contacts.

Surprisingly, it fails if I don't connect twice (?!). I'm now working on isolating the issue to see how it can be reproduced.

**Comment by ecederstrand** [comment]
Hi @adrinavarro Did you find a solution to this?

**Comment by ecederstrand** [comment]
Looking at the log again, `FindItem` is returning 200-something items. These are then passed on to `GetItem` and chunked into 3 requests, but `GetItem` never returns the requests that are queued up. It's likely that the server has stalled or rate-limited your account, in which case you'll just have to wait until the server decides to deliver the data you're waiting for.

**Comment by adrinavarro** [comment]
Apologies for not replying or following up earlier. We've been dealing with several issues and this one sort of fell through. Sorry again.

We believe we have identified the root cause for this. Our program does forking (actually, uses multiprocessing.Process in Python), and sometimes exchangelib is initialised (and thus, credentials are checked, issuing a request) in the main process — and then contents are queried within the children process.

In most use cases this would work just fine, but because exchangelib uses a ThreadPool, it cannot be shared between these two processes so the requests never return.

**Comment by ecederstrand** [comment]
Ah. That makes sense. While exchangelib should be thread-safe, you cannot share objects between processes. You need to create the `Account` or `Configuration` objects within each process.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if this requires changes to exchangelib :-)
