### ISSUE TITLE
multiple excludes not working

### ISSUE THREAD

**Issue by petr-tik** [ecederstrand/exchangelib#323]
Hey Erik, 
First of all, thanks for open-sourcing this library - it's a huge help. I wanted to clarify how to combine multiple QuerySets in one exclude statement, because currently the domains I want to exclude show up in results. 

I have read the documentation and the source for exchangelib and Django's QuerySet when I was writing the code below. 

Using Python3
Exchange protocol version
```
print(outlook.account.protocol)
EWS url: https://outlook.office365.com/EWS/Exchange.asmx
Product name: Microsoft Exchange Server 2016
EWS API version: Exchange2016
Build number: 15.20.345.17
EWS auth: basic
XSD auth: basic
```

My code

```
domains_to_exclude = ["linkedin.com", 'calendar-notification@google.com', "atlassian.com", "bitbucket.org"]
query = Q(sender__icontains=domains_to_exclude[0])
for domain in domains_to_exclude[1:]:
    query |= Q(sender__icontains=domain)
print(query)
qs = self.account.inbox.filter(~query).values("datetime_sent", "datetime_received", "sender")
for email in qs.iterator():
    emails.add((email.sender.name, email.sender.email_address, email.datetime_sent))
```

I want to make a SQL statement like:
WHERE sender NOT (LIKE '%linkedin.com%' OR LIKE '%atlassian.com%') and it doesn't seem to filter them out.

Let me know, if you need any additional information

Thanks

**Comment by ecederstrand** [comment]
You can check whether the boolean logic of the queryset is what you expected: `print(qs.q.expr())`.

If we built the expression as expected, maybe EWS just doesn't support icontains on sender emails. EWS has some quirks in complex filter expressions. I would suggest [enabling debug logging](https://github.com/ecederstrand/exchangelib#troubleshooting) and checking the actual XML restriction expression that goes over the wire.

**Comment by ecederstrand** [comment]
I have played around a bit with filtering on sender, and my conclusion is that this is either broken in EWS, or only works for some sender types. In my tests, I can filter senders that have `mailbox_type='OneOff'`, but not senders that have `mailbox_type='Mailbox'`.

Would that explain the issue you're seeing? Someone suggests using extended properties in this situation. You may have luck with that: https://social.msdn.microsoft.com/Forums/exchange/en-US/958c0b70-b8c5-4a34-8346-cb473c7c8455/ews-search-by-sender-name-not-email?forum=exchangesvrdevelopment

**Comment by ecederstrand** [comment]
I tested with the `subject` field instead using the following snippet, and it works as expected:

```python
q = Q(subject__icontains='foo') | Q(sender__icontains='bar')
for i in a.inbox.filter(~q).only('subject'):
    print(i.subject)
```

Closing, as I I assume this is only a problem with the `sender` field, where EWS has a quirk that exchangelib can't really fix. Feel free to re-open if you feel otherwise :-)
