### ISSUE TITLE
restore archived emails

### ISSUE THREAD

**Issue by EhsanMirzaei** [ecederstrand/exchangelib#325]
Hey @ecederstrand 
Thanks for the lib. 
I'm trying to pull some information from the one of the folders in a mailbox, and  I use the following method. The archived emails in the mailbox are not include the full Body of the actual email . Is there anyway to restore the archived emails or the full body of the achieved emails?

cheers

**Archive= account.inbox.get_folder_by_name('somefolder')**

**Comment by ecederstrand** [comment]
I'm not sure what you mean by "archived emails". EWS has export and upload methods for mailbox archiving purposes, that are exposed as `Account.export()` and `Account.upload()`.

If you meant "archive" as moving a message from one folder to another using OWA, Outlook or exchangelib, then the body should be accessible just like messages in any other folder. You can use the method you posted, but it's deprecated in newer versions, and replaced by better folder navigation (see https://github.com/ecederstrand/exchangelib#folders).

**Comment by EhsanMirzaei** [comment]
Thanks for your reply @ecederstrand  , but I think I didn't make it clear enough. 

So our EWS policy for some folders is to archive the emails after one week but what I need is to have the unarchived version.  when I used the following method, all the emails which are older that one week are archived  and the body of the emails are missing but I want to know how could I request for the unarchived version of the emails.

**Archive= account.inbox.get_folder_by_name('somefolder')**
In outlook you can double click on the archived email and It will pop up with the full version.

**Comment by ecederstrand** [comment]
Ah, now I understand.

I'm not sure how Exchange stores these emails, but you could have a look in one of the pre-defined archive folders defined from here and on: https://github.com/ecederstrand/exchangelib/blob/2731a460246b74d498228fb8da6f56584963211c/exchangelib/account.py#L115

Also, in newer versions of exchangelib you can use `print(account.root.tree())` to get an overview of the folders hierarchy of a given account.

**Comment by kfjelsted** [comment]
When I attempt to do 
print(account.root.tree())after discovery phase completes, 
I get an "unknown name." Then I capitalized account as in 
print(Account.root.tree())

receive back: 
attributeError: type objec 

and I get t 'Account' has no attribute 'root'

**Comment by ecederstrand** [comment]
Upper-case `Account` will not work. Your script creates an `Account` instance somehow, you need to call `root.tree()` on that:

```python
account = Account(
    'john@example.com',
    credentials=Credentials(username='MYWINDOMAIN\\myusername', password='topsecret'),
    autodiscover=True
)
print(account.root.tree())
```

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if there are unanswered questions.
