### ISSUE TITLE
Struck in accessing calendar events

### ISSUE THREAD

**Issue by suddenraj** [ecederstrand/exchangelib#326]
Error : No handlers could be found for logger "exchangelib.fields"

```python
now = datetime.datetime.now()
end = datetime.date.today() + datetime.timedelta(30)
start = EWSDateTime(now.year, now.month, now.day)
end  = EWSDateTime(end.year, end.month, end.day)
# find all calendars and their next 1 month entries
tz = EWSTimeZone.timezone('Europe/Vienna')
items = account.calendar.view(start=tz.localize(start), end=tz.localize(end))
for item in items:
    print("start")
```

**Comment by ecederstrand** [comment]
Your example code should just work.

It doesn't look like the error comes (only) from the code you posted. Normally, this error comes if you create a logger but don't add a handler before using it, or don't call `logging.basicConfig()` before attempting to log a message.

Can you post your full example, or at least a stack trace?

**Comment by suddenraj** [comment]
Please find the below code and find the the method "event_List", 
I don't get any stack trace , but instead of my print values the exception is coming...

output::
'("Let's go for meeting", EWSDateTime(2017, 4, 15, 19, 0, tzinfo=<UTC>))
("Let's go for meeting", EWSDateTime(2017, 4, 15, 19, 0, tzinfo=<UTC>))
('FW: Cowen/Softek Demonstation', EWSDateTime(2017, 9, 21, 18, 0, tzinfo=<UTC>))
('Annual Review 2017', EWSDateTime(2017, 9, 7, 9, 30, tzinfo=<UTC>))
('Prism Integration into BlueMatrix Client Manager', EWSDateTime(2017, 8, 23, 14, 0, tzinfo=<UTC>))
('Weekly Project Status Review', EWSDateTime(2017, 8, 7, 13, 0, tzinfo=<UTC>))
('Prism Bulk Call Troubleshoot', EWSDateTime(2017, 8, 3, 17, 0, tzinfo=<UTC>))
('Prism Trader App - Upcoming Release discussion', EWSDateTime(2017, 8, 2, 12, 30, tzinfo=<UTC>))
('Prism/CIA Integration Follow-Up', EWSDateTime(2017, 8, 3, 13, 0, tzinfo=<UTC>))
('"Live" Troubleshoot for Prism/CIA Integration ', EWSDateTime(2017, 7, 31, 18, 30, tzinfo=<UTC>))
('Production Bugs reporting', EWSDateTime(2017, 7, 24, 6, 30, tzinfo=<UTC>))
('Interview / Java / Ganeshkumar.S / Telephonic / 9715921400', EWSDateTime(2017, 6, 15, 9, 0, tzinfo=<UTC>))
('Interview / Java / Abdul Kader.T.S.N / Telephonic / 9894714253', EWSDateTime(2017, 6, 15, 9, 30, tzinfo=<UTC>))
**No handlers could be found for logger "exchangelib.fields"**
('DATAZOIC : Tower Leads Meeting', EWSDateTime(2017, 8, 29, 9, 30, tzinfo=<UTC>))
'


`# EWS 
import sys, os, csv, json, re, optparse, random, time, shutil, time
import datetime, logging, urllib, email, quopri, traceback
import requests, base64
from bs4 import BeautifulSoup
from tzlocal import get_localzone
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem,Contact, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version, errors
from exchangelib.indexed_properties import IndexedElement, EmailAddress, PhysicalAddress, PhoneNumber, \
    SingleFieldIndexedElement, MultiFieldIndexedElement    
from exchangelib.properties import Attendee, Mailbox, RoomList, MessageHeader, Room, ItemId, Member, EWSElement    
from exchangelib.fields import BooleanField, IntegerField, DecimalField, TextField, EmailField, URIField, ChoiceField, \
    BodyField, DateTimeField, Base64Field, PhoneNumberField, EmailAddressField, TimeZoneField, \
    PhysicalAddressField, ExtendedPropertyField, MailboxField, AttendeesField, AttachmentField, CharListField, \
    MailboxListField, Choice, FieldPath, EWSElementField, CultureField, DateField, EnumField, EnumListField, IdField, \
    CharField, TextListField
from exchangelib.winzone import MS_TIMEZONE_TO_PYTZ_MAP    
#from ws.mydb import gdb
from email.utils import parseaddr
from email.parser import FeedParser
from dateutil import parser
from pprint import pprint
tz = EWSTimeZone.localzone()
#from ws.sutils import *

def restore_windows_1252_characters(s):
    """Replace C1 control characters in the Unicode string s by the
    characters at the corresponding code points in Windows-1252,
    where possible.

    """
    import re
    def to_windows_1252(match):
        try:
            return bytes([ord(match.group(0))]).decode('windows-1252')
        except UnicodeDecodeError:
            # No character at the corresponding code point: remove it.
            return ''
    return re.sub(r'[\u0080-\u0099]', to_windows_1252, s)


class EWS (object):

    def __init__(self):
        self.debug = False
        # if set to true, retries will be exponentially delayed.
        self.enable_fault_tolerance = True
        
        # account details of primary email addresses
        self.targets = {}

        # target url to upload parsed mail to
        self.mailurl = "http://127.0.0.1:5000/mail"

    # version=15.0.12.34
    def connect(self, primary_email, server=None, version=None):
        if primary_email in self.targets and self.targets[primary_email] is not None:
            return self.targets[primary_email]
        try:
            if server:
                if version is not None:
                    #print ('using pre-defined version (no auto discover)')
                    aver = version.split('.')
                    if len(aver)<4:
                        #print ("error: version must be of format v.v.v.v")
                        return False
                    version = Version(build=Build(aver[0], aver[1], aver[2], aver[3]))
                    config = Configuration(server=server, credentials=self.credentials, version=version, auth_type=NTLM)
                else:
                    config = Configuration(server=server, credentials=self.credentials, has_ssl=True)
                account = Account(primary_smtp_address=primary_email, config=config, autodiscover=False, 
                                access_type=IMPERSONATION, credentials=self.credentials)
            else:
                # use this if the server supports auto discover for the end points
                #print ('using auto discovery...')
                account = Account(primary_smtp_address=primary_email, credentials=self.credentials, 
                            autodiscover=True, access_type=IMPERSONATION)
            self.targets[primary_email] = account
        except errors.ErrorImpersonateUserDenied as ie:
            print  (errors.ErrorImpersonateUserDenied)
            print ("impersonation of user "+primary_email+" denied")
            return None
        except:
            raise
        # self.ews_url        = account.protocol.service_endpoint
        # self.ews_auth_type  = account.protocol.auth_type
        # self.primary_smtp_address = account.primary_smtp_address
        return account

    def login(self, username, password):
        # for windows exchange server username should be WinDomain\\username 
        # for office 365 username should be primary email address
        # self.credentials = Credentials(username=username, password=password, verify_ssl=False)
        
        #service account provides a fault tollerant facility which backs-off exponentially
        # thereby not overloading the server in case of load (sleep time doubles after every 
        # disconnects)
        if not self.enable_fault_tolerance:
            self.credentials = Credentials(username=username, password=password)
        else:
            self.credentials = ServiceAccount(username=username, password=password)

    # format exchangelib MailBox to named elements
    def mailboxes(self, mb):
        if mb is None: return []    # empty array of MailBoxes
        if not isinstance(mb, list):
            return {'name': mb.name, 'email': mb.email_address.lower(), 'mailbox_type': mb.mailbox_type, 'item_id': mb.item_id}
        addr = [{'name': m.name, 'email': m.email_address.lower(), 'mailbox_type': m.mailbox_type, 'item_id': m.item_id} for m in mb]
        return addr

    def asciize(self, s):
        return (''.join( [chr(c) for c in s if c<=0x80] )).encode('utf8')

    def special_chars(self, s):
        if False:
            print ("++++++++++++++++++")
            print (s)
            print ("##################")
        x = []
        skip = 0
        for i in range(0, len(s)-3):
            if skip>0:
                skip -= 1
                continue
            if s[i] == 0xe2 and s[i+1]==0x80 and (s[i+2]==0x99 or s[i+2]==0x98):
                x.append("'")
                skip = 2
            elif s[i] == 0xe2 and s[i+1]==0x80: # and (s[i+2]==0x99 or s[i+2]==0x98):
                x.append("-")
                skip = 2
            elif s[i] == 0xf0 and s[i+1] == 0x9f: #\x98\x8a
                x.append("-")
                skip = 3
            else:
                x.append(chr(s[i]))
        x.append(chr(s[len(s)-2]))
        x.append(chr(s[len(s)-1]))
        return (''.join(x)).encode('utf8')
    def get_account_folders(self, email_address, server):
        print("get_account_folders")
        account = self.connect(email_address, server=server)
        print("Inbox count :"+str(account.inbox.total_count))
        print("Contacts :"+str(account.contacts.total_count))
        print(account.root.tree)
        print("------------------------------------------")
        for c in account.contacts.all():
            print(c)
            print("------------------------------------------")    
        return

        if not account: return "No folder"
        try:
            #print("Account ::"+str(account.root.get_folders()))
            return account.root.get_folders()
        except Exception as e:
            traceback.print_exc()
            # give it a retry with the new credentials (next time)
            self.targets[email_address] = None
        return 

    def mails(self, email_address, server=None):
        print("Mails")
        start = datetime.datetime.utcnow().isoformat()
        print (email_address, start)
        sys.stdout.flush()
        #self.contact_list(email_address, server=server)
        print("***************************************")
        self.update_Contact(email_address, server=server)
         

    def calendar(self, email_address, server=None):
        #MS_TIMEZONE_TO_PYTZ_MAP['Customized Time Zone'] = 'Europe/Vienna'
        account = self.connect(email_address, server=server)
        if not account: return
        
        now = datetime.datetime.now()
        end = datetime.date.today() + datetime.timedelta(30)
        start = EWSDateTime(now.year, now.month, now.day)
        end   = EWSDateTime(end.year, end.month, end.day)
        # find all calendars and their next 1 month entries
        tz=EWSTimeZone.timezone('Europe/Vienna')
        #EWSTimeZone.timezone('Europe/Vienna')
        items = account.calendar.view(start=tz.localize(start),end=tz.localize(end),)
        print(items)
        #for item in items:
        #    print("start")
            #print(item.start)
            #yield {'start': i.start.astimezone(tz), 'summary': i.subject}
            #print(item.end, item.subject, item.body, item.location)
            #print('    ', item.subject, item.start)
        '''
        for f in account.get_folders():
            if type(f).__name__ == 'Calendar':
                print ("Calendar: ", f.name)
                #items = account.calendar.filter(start__range=(tz.localize(start), tz.localize(end)))
                #items = account.calendar.view(start__range=(tz.localize(start), tz.localize(end))) 
                #items = f.filter(start__range=(tz.localize(start), tz.localize(end)))
                #items = f.find_items(Q())
                #items = f.filter( start__range=(tz.localize(EWSDateTime(2016, 1, 1)), tz.localize(EWSDateTime(2018, 1, 1))) )
                # items = f.filter( start__gte=tz.localize(EWSDateTime(2016, 1, 1)) )
                # for item in items:
                #     print ('    ', item.subject)
                #     #print ('    ', item.mime_content)
                # print ("End.")'''

                


    def contact_list(self, email_address, server):
        #print("adsd")
        account = self.connect(email_address, server=server)
        i = 0
        data = []
        for c in account.contacts.all():
            cont = {}
            #print(c)
            cont["name"] =  c.display_name
            cont["given_name"] =  c.given_name
            cont["middle_name"] =  c.middle_name
            cont["nickname"] =  c.nickname
            cont["company_name"] =  c.company_name
            cont["item_id"] = c.item_id
            cont["changekey"] = c.changekey
            #cont["last_modified_time"] = c.last_modified_time
            #cont["datetime_created"] = c.datetime_created
            #cont["email_addresses"] =  em.EmailAddress.email
            #cont["phone_numbers"] =  c.phone_numbers
            cont["job_title"] =  c.job_title
            data.append(cont)
            '''#print(type(c.email_addresses))
            #ema = iter(c.email_addresses)
            #print(json.dumps(c.email_address))
            for em in c.email_addresses:
                print(em.get_field_by_fieldname("email"))
                print("------------------------------------------")
                #v = next(em)
                print(em.get_field_by_fieldname("email")) '''
        json_data = json.dumps(data)
        print(json_data)
        return

    def add_Contact(self, email_address, param, server):
        account = self.connect(email_address, server=server)
        item = Contact(folder=account.contacts)
        
        item.display_name = param["givenName"]
        item.company_name = param["companyname"]
        i = param["emailAddresses"]
        item.email_addresses = [EmailAddress(email='%s' % i, label="EmailAddress1")]
        ret = item.save()
        data = {}
        data["item_id"] = ret.item_id
        data["changekey"] = ret.changekey
        json_data = json.dumps(data)
        print(json_data)
        return

    def update_Contact(self, email_address, param, server):
        account = self.connect(email_address, server=server)
        item_id = param["item_id"]
        changekey = param["change_key"]
        item_idss =[(item_id,changekey)]
        co = account.fetch(item_idss)
        i = "ramya"
        item = next(co)
        #print(item.email_addresses)
        item.email_addresses = [EmailAddress(email='%s@datazoic.com' % i, label="EmailAddress1")]
        item.display_name = "ramya"
        item.given_name = i
        item.job_title = "software developer"
        ret = item.save()
        data = {}
        data["item_id"] = ret.item_id
        data["changekey"] = ret.changekey
        json_data = json.dumps(data)
        print(json_data)
        return
    
    def dump(self,obj):
      for attr in dir(obj):
        print("obj.%s = %s" % (attr, getattr(obj, attr)))

    def event_List(self, email_address, param, server):
        account = self.connect(email_address, server=server)
        i = 0
        items = account.calendar.filter(start__range=(
            tz.localize(EWSDateTime(2017, 1, 1)),
            tz.localize(EWSDateTime(2017, 10, 1))
        ))

        for item in items:
            print(item.subject,item.start)
            #print(item.start, item.end, item.subject, item.body, item.location)
        return

    def add_event(self, email_address, param, server):
        return
        
    def update_event(self, email_address, param, server):
        return

    def delete_event(self, email_address, param, server):
        return


    
    
if __name__ == "__main__":
    optp = optparse.OptionParser()
    optp.add_option('-v', '--verbose', dest='verbose',      help='Increase verbosity (specify multiple times for more)',  action='count', default=0)
    optp.add_option('-u', '--username',  dest='username',   help='user name (for Exchange domain\\user) (for office 365 email address)', default='****@****.com')
    optp.add_option('-p', '--password',  dest='password',   help='Password for the account', default='********')
    optp.add_option('-t', '--target',   dest='target',   help='Target email address', default='saranraj@*****.com')
    optp.add_option('-s', '--server',   dest='server',   help='SMTP server name', default='outlook.office365.com')
    optp.add_option('-f', '--folder',   dest='folder',   help='Process file in folder', default='')
    optp.add_option('-d', '--download', dest='download', help="Download mails to folder", default=None)
    optp.add_option('-r', '--replies', dest='replies', help="Update replies", default=False, action='store_true')
    (opts, args) = optp.parse_args()
    #if opts.verbose: logging.basicConfig(level=logging.DEBUG)

    ews = EWS()
    if opts.verbose>0: ews.debug = True
    arguments = sys.argv[1:]
    #print(arguments)
    count = len(arguments)
    if count < 1:
        print("method name")
    elif count < 2:
        print("argument missing")    
    else:
        ews.login(opts.username, opts.password)
        if(arguments[0] == "list_contact"):
            #print("list contact")
            ews.contact_list(opts.target,server=opts.server)
        elif(arguments[0] == "add_contact"):
            #print("add contact")
            #print(type(arguments[1]))
            json_data = json.loads(arguments[1])
            #print(json_data["givenName"])
            ews.add_Contact(opts.target,json_data,server=opts.server)
        elif(arguments[0] == "update_contact"):    
            #print("update contact")
            json_data = json.loads(arguments[1])
            ews.update_Contact(opts.target,json_data,server=opts.server)
        elif(arguments[0] == "list_event"):
            #print("list event")
            #ews.calendar(opts.target, server=opts.server)
            ews.event_List(opts.target,arguments[1],server=opts.server)
        elif(arguments[0] == "add_event"):
            #print("add_event")
            ews.add_event(opts.target,arguments[1],server=opts.server)
        elif(arguments[0] == "update_event"):    
            #print("update event")
            ews.update_event(opts.target,arguments[1],server=opts.server)
        elif(arguments[0] == "delete_event"):    
            #print("update event")
            ews.update_event(opts.target,arguments[1],server=opts.server)

    
`

**Comment by suddenraj** [comment]
I think the issue is coming for a particular **calendar item**

**Comment by suddenraj** [comment]
Any update on this ?
I got one error message on my console. 
"No handlers could be found for logger "exchangelib.fields""

I can not handle this issue, not coming in the exception handling also .

**Comment by ecederstrand** [comment]
Try adding `logging.basicConfig(level=logging.INFO)` at the top of your script.

**Comment by suddenraj** [comment]
Thanks very much

**Comment by ecederstrand** [comment]
Did it work? If so, please close this ticket :-)
