### ISSUE TITLE
Get size of a mailbox

### ISSUE THREAD

**Issue by SidharthPati** [ecederstrand/exchangelib#329]
Hi,

Is there support for us to get the size of a mailbox?

**Comment by ecederstrand** [comment]
I'm not sure if you can get the entire size of a mailbox out of EWS, but you can get the size of a specific folder by using extended properties. See the last part of https://github.com/ecederstrand/exchangelib#extended-properties

**Comment by SidharthPati** [comment]
Ok thank you. I was actually looking for size of mailbox. I'll probably have to take help of powershell for this.

**Comment by ecederstrand** [comment]
Googling suggests that getting full Mailbox size is only possible with PowerShell: https://social.msdn.microsoft.com/Forums/exchange/en-US/b4a10ba2-8ae7-40e7-9408-f198a5b9ce10/ews-to-get-size-of-all-mailboxes-on-given-mailbox-server-role

You could get an approximation by iterating over all folders and getting the size of each folder, but whether that works for you depends on your use case:

```python
class FolderSize(ExtendedProperty):
    property_tag = 0x0e08
    property_type = 'Integer'

Folder.register('size', FolderSize)
total_size = sum([f.size for f in account.root.walk()])
