### ISSUE TITLE
Manual S/MIME encrypted mails

### ISSUE THREAD

**Issue by BreakfastSerial** [ecederstrand/exchangelib#331]
I'm trying to send manually encrypted S/MIME mails.

I can manually S/MIME encrypt data with OpenSSL as I can't seem to find an option for exchangelib to encrypt with S/MIME.

From what I've understood, the easiest way would be to add the appropriate mail headers and encrypt the message body manually for the recipient.

So I believe the headers I have to add are:

```
    MIME-Version: 1.0
    Content-Type: application/pkcs7-mime; name="smime.p7m"; smime-type=enveloped-data
    Content-Transfer-Encoding: base64
    Content-Disposition: attachment; filename="smime.p7m"
    Content-Description: S/MIME Encrypted Message
```

The actual mail body would the just be the S/MIME encrypted (base64 encoded) message including optional attachments (e.g. images).

How can I add these _custom_ mail headers with exchangelib in Python?

**Comment by ecederstrand** [comment]
I haven't used MIME email headers with EWS before, but according to https://msdn.microsoft.com/en-us/library/office/hh545614(v=exchg.140).aspx you need to create the full MIME content manually, encode it, and set that as the `my_message.mime_content` value.

Note that `mime_content` is read-only in exchangelib currently: https://github.com/ecederstrand/exchangelib/blob/cc6e532e99af171530f0b782162c215be38b2dd6/exchangelib/items.py#L132 You would need to set `Message.FIELDS[0].is_read_only = False` first and hope it works :-)

Please post the solution here if you get it to work, so I can document it in the README!

**Comment by ecederstrand** [comment]
Just for clarification, these headers aren't really *custom* in the traditional sense of custom (`X-Foo`) headers. For that, you should use extended properties. See https://msdn.microsoft.com/en-us/library/office/dn596091(v=exchg.150).aspx

**Comment by BreakfastSerial** [comment]
I've just tried to send an S/MIME encrypted mail as described.

First I've prepared the mail with OpenSSL with the recipients public key, for example like this:

```
$ openssl smime -encrypt -in message.txt -from from@mail.local -to to@mail.local -subject "Encrypted message" -des3 to.public.pem
```

Then I've set up Python to send the actual mail and as suggested I've enabled writing the `mime_content`, set it to the output of the above OpenSSL command and sent the message.

In summary:

```
>>> mc=b"""
... To: to@mail.local
... From: from@mail.local
... Subject: Encrypted message
... MIME-Version: 1.0
... Content-Disposition: attachment; filename="smime.p7m"
... Content-Type: application/x-pkcs7-mime; smime-type=enveloped-data; name="smime.p7m"
... Content-Transfer-Encoding: base64
...
... MIICEQYJKoZIhvcNAQcD
... <SNIPPED BASE64 TEXTBLOCK>
... QMHBAjPkCMtE/dx4YAITufA
... A52/1A8=
... """
>>> m = Message(account=account, mime_content=mc, to_recipients=['to@mail.local']))
>>> m.send()
```

The message sends just fine, but it's not interpreted as an S/MIME encrypted mail, Outlook rather just displays the complete `mime_content` in the message body. I'll retry the same with Thunderbird, as it allows me to inspect the actual raw mail.

**Comment by BreakfastSerial** [comment]
This is quite interesting. In the last attempt I've sent a mail from to my own mail account managed by the Exchange server I'm sending the mail with.

I've just replayed the scenario, but the recipient is on an external mail provider. OpenSSL the message first, use the `mime_content` in exchangelib and sent the message.

The received message in Thunderbird uses all the correct mail headers and the actual message body is the base64 block as created by OpenSSL. I just can't decrypt it at the moment but I assume that is a different problem.

I'm just not quite sure yet why the local recipient is handled differently. I'll continue the tests and report back once I know something new.

**Comment by ecederstrand** [comment]
Cool, thanks for the update!

**Comment by BreakfastSerial** [comment]
Ok, so I can successfully decrypt the received message manually by simply copy/pasting the complete raw message and using OpenSSL:

    openssl smime -decrypt -in encrypted.message.raw -recip to.public.pem -inkey to.private.pem

I don't understand yet why Thunderbird is unable to decrypt it and why the raw message is different for Outlook. But it looks promising... I'll keep you updated.

**Comment by ecederstrand** [comment]
Just an idea: Can you send yourself an encrypted message using a known-good client? You would then be able to inspect both the working and non-working messages and hopefully find out what the difference is.

**Comment by ecederstrand** [comment]
Just FYI, I made the `mime_content` writeable for new and draft items in 9c29817fe8fb0e8e46b8a95b9383aeee939b58dd and 794c263acf56fa21197a7af9913e7a9baf72b366

**Comment by BreakfastSerial** [comment]
That's exactly what I'm currently comparing, but it seems the exchange server handles mail for accounts of the exchange server differently than mails for external accounts. But I'm not sure yet!
Thanks for the update!

**Comment by ecederstrand** [comment]
Hi @BreakfastSerial Did you get this to work? Feel free to reply here if there's anything we can do to help.

**Comment by mthlvt** [comment]
if you managed to get this working, sharing the code would be nice. 👍

**Comment by BreakfastSerial** [comment]
I'm sorry for the very late reply. Unfortunately I haven't looked into the issue anymore and can't report back with a working solution.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you think changes to exchangelib could be made to support this functionality.
