### ISSUE TITLE
Favorites VS Shortcuts

### ISSUE THREAD

**Issue by thomasjiangcy** [ecederstrand/exchangelib#333]
I've seen several issues related to Public Folders and haven't been able to find how to retrieve them accurately.

What I've done so far was to add the Public Folders to the mailbox Favorites manually via the OWA. However, when I login via `exchangelib` and run `print(account.root.tree())`, the Favorites folder is empty but instead, all the folders I added to Favorites appear under another folder called `Shortcuts` and each of them have an absolute path of `\root\Shortcuts\<folder-name>`. When I try accessing them, the message count is 0, though there are clearly files under them.

However, I've also noticed through observing the APIs called by the OWA that it calls an endpoint `/service.svc?action=GetFavorites&ID=-2&AC=1` to retrieve all the folders under `Favorites`, this returns a list of objects with the actual `FolderId` and `ChangeKey` of the folders. I'm guessing that this has something to do with symlinks between the folders?

In any case, it's a little confusing and I'll be happy to learn how I might be able to access the public folders directly from Favorites to view the messages.

**Comment by ecederstrand** [comment]
I haven't played around with shortcuts / favorites in Outlook, unfortunately. My current test server only has one account, so it's a bit difficult to test :-) So this is just to say that shortcuts have received little to no testing in exchangelib.

I may be able to test this on another Exchange server, but you're welcome to dig further nito this issue in the meantime. If you want to know what exchangelib is doing internally, you can [enable debug logging](https://github.com/ecederstrand/exchangelib#troubleshooting) and follow the exact XML that goes over the wire.

**Comment by thomasjiangcy** [comment]
I see! Thanks for the info, I guess I will close this for now :)
