### ISSUE TITLE
AssertionError - Exchangelib (authentication)

### ISSUE THREAD

**Issue by ccs1910** [ecederstrand/exchangelib#334]
I executed this code : 

```python
o_credentials = Credentials(username=in_username, password=in_password)
o_account = Account(primary_smtp_address=in_smtp_address, credentials=o_credentials, autodiscover=True, access_type=DELEGATE, verify_ssl=False)
```

i use exchangelib 1.9.4 and i got below traceback : 
```python
Traceback (most recent call last):
  File ".\auth.py", line 54, in <module>
    o_account = Account(primary_smtp_address=in_smtp_address, credentials=o_credentials, autodiscover=True, access_type=DELEGATE, verify_ssl=False)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\account.py", line 67, in __init__
    credentials=credentials, verify_ssl=verify_ssl)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\autodiscover.py", line 186, in discover
    protocol=protocol)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\autodiscover.py", line 321, in _autodiscover_quick
    ews_url, primary_smtp_address = _parse_response(r.text)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\autodiscover.py", line 431, in _parse_response
    assert ews_url and primary_smtp_address
AssertionError
```

previously it's working fine. but now, it shows error like above.
could you please help ?
or a hint would be great.

thanks, Christian CS

**Comment by ecederstrand** [comment]
This means the autodiscover response didn't contain the URL primary SMTP address we expected. You'll have to enable debug logging and extract the XML of the autodiscover response to find out what's going on.

**Comment by ccs1910** [comment]
i think it's correct, so now i tried to force the EWS url. but still it doesn't work and get another error: 
Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:719)'),))

here's the code ; 
o_credentials = Credentials(username=in_username, password=in_password)
config = Configuration(service_endpoint='http://mail.xxx.net/EWS/Exchange.asmx', credentials=o_credentials)
o_account = Account(primary_smtp_address=in_smtp_address, config=config, autodiscover=False, access_type=DELEGATE, verify_ssl=False)

kindly help

**Comment by ecederstrand** [comment]
exchangelib is supposed to survive not having access to `/EWS/types.xsd`. We just have less possibilities to guess the server version. Lots of changes has gone into this part of the code since 1.9.4. This should not be an issue with recent versions of exchangelib, so you can try upgrading.

But let's fix the original issue first. Can you capture the autodiscover response XML and post it here?

**Comment by ccs1910** [comment]
hello, i think for now it works.
i upgrade the exchangelib but i still can't use the autodiscover and i force the service_endpoint.

config = Configuration(service_endpoint= config['service_endpoint'], credentials=o_credentials)
o_account = Account(primary_smtp_address=in_smtp_address, config=config, autodiscover=False, access_type=DELEGATE)

**Comment by ecederstrand** [comment]
I would really like to help, but it's not possible without the debug output I have asked for.

**Comment by ccs1910** [comment]
ok... so if i am using autodiscover, my script : 

o_credentials = Credentials(username=in_username, password=in_password)
o_account = Account(primary_smtp_address=in_smtp_address, credentials=o_credentials, autodiscover=True, access_type=DELEGATE)

and result : 
outlook : auth : starts
DEBUG:exchangelib.autodiscover:Attempting autodiscover on email alor.crpmiidjktopp17@pmi.com
DEBUG:exchangelib.autodiscover:Waiting for _autodiscover_cache_lock
DEBUG:exchangelib.autodiscover:_autodiscover_cache_lock acquired
DEBUG:exchangelib.autodiscover:Cache miss for domain pmi.com credentials pmi\s-outmeet
DEBUG:exchangelib.autodiscover:Cache contents: {}
DEBUG:exchangelib.autodiscover:Trying autodiscover on https://pmi.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for https://pmi.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): pmi.com
ERROR:urllib3.connection:Certificate did not match expected hostname: pmi.com. Certificate: {'serialNumber': 'E49F49C476A6EB748FBD6BBBCD2C6AA6', 'version': 3, 'crlDistributionPoints': ('http://crl.usertrust.com/TrustedSecureCertificateAuthority5.crl',), 'notBefore': 'Dec  1 00:00:00 2017 GMT', 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'DE'),), (('localityName', 'Wilmington'),), (('organizationName', 'Corporation Service Company'),), (('commonName', 'Trusted Secure Certificate Authority 5'),)), 'OCSP': ('http://ocsp.usertrust.com',), 'caIssuers': ('http://crt.usertrust.com/TrustedSecureCertificateAuthority5.crt',), 'subjectAltName': (('DNS', 'secure.pmi.com'), ('DNS', 'www.secure.pmi.com')), 'subject': ((('countryName', 'CH'),), (('postalCode', '2000'),), (('stateOrProvinceName', 'Neuchatel'),), (('localityName', 'Neuchatel'),), (('streetAddress', 'Quai Jeanrenaud 3'),), (('organizationName', 'Philip Morris International Management SA'),), (('organizationalUnitName', 'GTS'),), (('organizationalUnitName', 'Enterprise SSL'),), (('commonName', 'secure.pmi.com'),)), 'notAfter': 'Nov 30 23:59:59 2020 GMT'}
DEBUG:exchangelib.autodiscover:Trying autodiscover on https://autodiscover.pmi.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for https://autodiscover.pmi.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): autodiscover.pmi.com
DEBUG:exchangelib.autodiscover:Trying autodiscover on http://autodiscover.pmi.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for http://autodiscover.pmi.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): autodiscover.pmi.com
DEBUG:urllib3.connectionpool:http://autodiscover.pmi.com:80 "HEAD /Autodiscover/Autodiscover.xml HTTP/1.1" 302 0
DEBUG:exchangelib.transport:Autodiscover HTTP redirect to https://autodiscover.pmi.com/Autodiscover/Autodiscover.xml
DEBUG:urllib3.connectionpool:http://autodiscover.pmi.com:80 "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 302 0
DEBUG:exchangelib.transport:Request headers: {'Accept': '*/*', 'Accept-Encoding': 'compress, gzip', 'Content-Type': 'text/xml; charset=utf-8', 'Connection': 'keep-alive',
'User-Agent': 'python-requests/2.18.4', 'Content-Length': '361'}
DEBUG:exchangelib.transport:Response headers: {'Connection': 'Keep-Alive', 'Location': 'https://autodiscover.pmi.com/Autodiscover/Autodiscover.xml', 'Server': 'BigIP', 'Content-Length': '0'}
DEBUG:exchangelib.autodiscover:Attempting to get canonical name for autodiscover.pmi.com
DEBUG:exchangelib.autodiscover:Attempting to get SRV record on autodiscover.pmi.com
DEBUG:exchangelib.autodiscover:Attempting to get SRV record on _autodiscover._tcp.pmi.com
DEBUG:exchangelib.autodiscover:Releasing_autodiscover_cache_lock
test 22222222222222222
auth : target account & autodiscover : Error :  All steps in the autodiscover protocol failed
Traceback (most recent call last):
  File ".\auth.py", line 64, in <module>
    o_account = Account(primary_smtp_address=in_smtp_address, credentials=o_credentials, autodiscover=True, access_type=DELEGATE)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\account.py", line 74, in __init__
    credentials=credentials)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\autodiscover.py", line 214, in discover
    email=email)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\exchangelib\autodiscover.py", line 262, in _try_autodiscover
    raise_from(AutoDiscoverFailed('All steps in the autodiscover protocol failed'), None)
  File "C:\Users\csantoso\AppData\Local\Programs\Python\Python35\lib\site-packages\future\utils\__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed
outlook : auth : ends
Traceback (most recent call last):
  File ".\auth.py", line 84, in <module>
    send_mail(o_account, "ini lagi ngetes ALOORRR", HTMLBody('<p>Dear '+meet_subj+' (Meeting Organizer),</p>'+\
NameError: name 'o_account' is not defined


i am not sure what happened, but if i am not using the autodiscover, it's working.

**Comment by ecederstrand** [comment]
This looks like a certificate issue with pmi.com. Your output says: `Certificate did not match expected hostname: pmi.com` and then `exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed`.

So somehow your Python installation is not able to validate the certificate of pmi.com. exchangelib then continues with the autodiscover process until all other options are exhausted, and fails.

If you think you should be able to autodiscover pmi.com email addresses, then first get an autodiscover test report on https://testconnectivity.microsoft.com. If that works, then match the report against the steps exchangelib is taking and find you where we're doing things differently. You may want to install exchangelib from the master branch on GitHub - I just committed better debug output for the autodiscover process.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you still think this is an issue with exchangelib.
