### ISSUE TITLE
Feature Request - Attachments in Attachment

### ISSUE THREAD

**Issue by Ads5740** [ecederstrand/exchangelib#335]
Is there any road map or possibility of being able to extract an attachment from an attachment.
For instance if an email has another email attached to it and a pdf is contained within that second email?

Currently if I use the ItemAttahchment method it fails:

```python
attachments = item.attachments
if attachments:
    for attach in attachments:
        if isinstance(attach, ItemAttachment):
            sub_attachments = attach.attachments
            if sub_attachments:
                for sub_attachment in sub_attachments:
                    if isinstance(sub_attachment, ItemAttachment):
                        print sub_attachment
```

``` 
    sub_attachments = attach.attachments
AttributeError: 'ItemAttachment' object has no attribute 'attachments'
```
Only option I can think of so far is is saving the attachment in a tmp folder and parsing it as a new item.

Are there any other ways?

**Comment by ecederstrand** [comment]
`ItemAttachment` has an `item` attribute which points to the actual item that is attached. So to access attachments of attachments, you would do this:

```python
for attachment in item.attachments:
    if not isinstance(attachment, ItemAttachment):
        continue
    for sub_attachment in attachment.item.attachments:
        print(sub_attachment)
```

**Comment by Ads5740** [comment]
Cancel, I think I figured it out.
For other:
```Python
attachments = item.attachments
                if attachments:
                    for attach in attachments:    
                        if isinstance(attach, ItemAttachment):
                             if isinstance(attach.item, Message): 
                                    sub_attachments = attach.item.attachments
                                          if sub_attachments:
                                               for sub_attachment in sub_attachments:    
                                                     if isinstance(sub_attachment, FileAttachment):
                                                            file_path = os.path.join(temp_folder, sub_attachment.name)
                                                                with open(file_path, 'wb') as f:
                                                                     f.write(sub_attachment.content)
```

**Comment by Ads5740** [comment]
long winded but it works, thanks for the support though

**Comment by Ads5740** [comment]
would this:
```
if not isinstance(sub_attachment, FileAttachment):
```
not be:
```
if isinstance(sub_attachment, FileAttachment):
```

if the file is a pdf

**Comment by ecederstrand** [comment]
I took the liberty of cleaning up your example code a bit. If the attachment is a PDF, then the attachment is a `FileAttachment` instance. So the example code loops through all sub-attachments, skips the ones that are not file attachments, and saves the rest to disk.

**Comment by Ads5740** [comment]
So as a quick follow up, how would you save an email attached to an email?
The FileAttachment works great but for an email I keep getting:
```
    f.write(attach)
TypeError: argument 1 must be convertible to a buffer, not ItemAttachment
```

**Comment by ecederstrand** [comment]
That depends on how you want to serialize the email. An Exchange item is a complex structure that you can't just convert to a stream of bytes, like you can with the contents of a file.

I've seen people just store the MIME content (`f.write(attach.item.mime_content)`) but it depends on what you want to use the file for afterwards.

**Comment by Ads5740** [comment]
So I'd like store a whole email that comes in to a mailbox attached to an email, to then be able to uploaded to something like [Viper](https://github.com/viper-framework/viper) for further analysis.

Or even better, not write the file to disk but upload the attached email to an API directly

**Comment by ecederstrand** [comment]
If the API requires binary data, then you have to serialize the `Message` class somehow. The `Message` class is a standard Python class with various instance attributes defined in the Message.FIELDS structure. Some of the attributes are bools, integers and strings, some are instances of other Python classes.

The `mime_content` field may be a good approximation, `repr(item)` is another possibility, but you can also assemble a `bytes()` object in Python by selecting the exact fields you want to have included in the data you upload via the API.

**Comment by Ads5740** [comment]
Thanks for the response.
The mime_content sort of works, seems to put it in base 64 so may just need to put a base64 decoder on the Viper end

**Comment by ecederstrand** [comment]
Which version of `exchangelib` is this? Recent versions will base64 decode the `mime_content` field for you.

**Comment by Ads5740** [comment]
it's 1.10.3

**Comment by ecederstrand** [comment]
Hmm. That's strange. I just installed 1.10.3 and get the `mime_content` field base64-encoded in the raw XML response but transparently decoded when I print the field.

Closing, as the original question seems answered. Feel free to re-open if you have further issues.
