### ISSUE TITLE
Sender address selection when sending from a shared mailbox

### ISSUE THREAD

**Issue by mthlvt** [ecederstrand/exchangelib#336]
Hi there 😃

I'm logging into a shared mailbox (`shared@domain.com`) with account (`user@domain.com`).

How to I send e-mails appearing from `shared@domain.com` (current code below results in mails sent from `user@domain.com`)?

```python
credentials = ServiceAccount(username='domain\\user', password='topsecret')

account = Account(primary_smtp_address='shared@domain.com', credentials=credentials,config=config,autodiscover=False, access_type=DELEGATE)

m = Message(
    account=account,
    subject='subject text',
    body=html_body,
    to_recipients=['another.user@domain.com'])
m.send(False)
```
Thanks!  
ps: changing delegate by impersonation didn't work (can't login)

**Comment by ecederstrand** [comment]
It's unclear to me if this is even possible using EWS. This seems to indicate that it's not: https://stackoverflow.com/questions/8921916/ews-managed-api-how-to-set-from-of-email

But it's a pretty easy test. There are two relevant fields on the `Message` class: `author` and `sender`. But `sender` is read-only, according to my tests. Try setting `author` as `shared@domain.com`, send, and see if it works.

**Comment by mthlvt** [comment]
I had tried sender without success but **author** does work.
Thanks for your help!
