### ISSUE TITLE
Add custom headers to avoid throttling issue?

### ISSUE THREAD

**Issue by alexdelin** [ecederstrand/exchangelib#338]
Running into this issue: https://support.microsoft.com/en-us/help/2990048/ews-throttling-occurs-after-a-migration-of-office-365-dedicated-itar-t?wa=wsignin1.0
which results in intermittent `ErrorNoRespondingCASInDestinationSite` errors getting thrown by exchange. 

Is there a straight forward way to add custom headers to the requests as shown on that page to avoid the issue?

**Comment by ecederstrand** [comment]
Do you know if `X-AnchorMailbox` is always safe to specify, or should it be used only as a workaround for the above issue?

If it's always safe, I can add it to this library. If not, then I think your best option for now is to create a custom HTTP Adapter class that injects this header. See the bottom of the https://github.com/ecederstrand/exchangelib#setup-and-connecting section on how to do that. There's a `BaseAdapter. add_headers()` method for this exact use case.

One caveat of this approach is that you would need to somehow change the `X-AnchorMailbox` value every time you want to connect to a new Account.

**Comment by ecederstrand** [comment]
Hmm, looks like the header is always good practice: https://blogs.msdn.microsoft.com/webdav_101/2015/05/11/best-practices-ews-authentication-and-access-issues/. We should always add it when using impersonation, then.

**Comment by alexdelin** [comment]
Yes, I'll do some testing with a custom HTTP Adapter to check if it resolves the issue. 

Also, out of curiosity, would there by any other way to catch and handle the `ErrorNoRespondingCASInDestinationSite` errors. My initial thought was to create some kind of backoff mechanism like the one you have here: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/util.py#L406-L427

**Comment by ecederstrand** [comment]
`ErrorNoRespondingCASInDestinationSite` is a per-account exception, as far as I understand, so letting it affect the backoff in `post_ratelimited()` would affect all requests to EWS, not just the Account that is throwing the error.

I maintain a calendar sync service that handles this outside of exchangelib. It catches account-specific errors like e.g. `ErrorMailboxStoreUnavailable` and `ErrorCannotDeleteObject`, and quarantines accounts based on that. You could use the same approach.

**Comment by RossK1** [comment]
@ecederstrand , was `X-AnchorMailbox` ever added as a standard header to include? I am getting `exchangelib.errors.ErrorTooManyObjectsOpened: Too many concurrent connections opened., Cannot open mailbox.` errors and it looks like setting this header for each account I am connecting to may resolve the issue. Thanks!

**Comment by ecederstrand** [comment]
Yes, the header is set now: https://github.com/ecederstrand/exchangelib/blob/ee2565c33301e9964db345440029aeeecf931337/exchangelib/services/common.py#L759

`ErrorTooManyObjectsOpened` usually happens when you, or other clients, have too many connections open to the same mailbox. Try scaling back concurrency in your script if you're opening connections in parallel.

**Comment by RossK1** [comment]
Thanks for clarifying :) I'll check with our EWS admins and see what's up.
