### ISSUE TITLE
get *all* mails to filter

### ISSUE THREAD

**Issue by fruitloop** [ecederstrand/exchangelib#339]
Hi, is there a way to get **all** mails and filter them?

I use rules to move emails based on addresses. They get a category and get moved to a subfolder.
What I would need is a query to get **all** mails and filter by category.

also, is it possible to filter for the flags described in #324?

**Comment by ecederstrand** [comment]
You mean all emails of multiple subfolders in a single query? That's not possible currently, but it's tracked in #224. EWS does support it.

Not all fields are filterable via EWS, but if EWS does support filtering on these custom flags, then just use the normal filter syntax after you register the extended property: `account.inbox.filter(flag=2)`

**Comment by fruitloop** [comment]
thanks, I'll find out what of the flags can be filtered, update this issue and close it tonight.
