### ISSUE TITLE
CalendarItem

### ISSUE THREAD

**Issue by freenetwork** [ecederstrand/exchangelib#340]
item = CalendarItem(
        start = tz.localize(EWSDateTime(start.year, start.month, start.day, start.hour, start.minute)),
        end = tz.localize(EWSDateTime(end.year, end.month, end.day, end.hour, end.minute)),
        subject = conference.name,
        body = conference.description,
        location ='devnull',
        categories = ['ВКС'],
        required_attendees = required_attendees,
        optional_attendees = optional_attendees,
        reminder_is_set = True
    )

How to change organizer name?

**Comment by ecederstrand** [comment]
```python
item.organizer =  'anne@example.com'
```

**Comment by freenetwork** [comment]
i must have right to organizer account?

**Comment by ecederstrand** [comment]
I don't know. Just try :-)

**Comment by freenetwork** [comment]
i thx. For change organizer calendar item need right to account organizer.
