### ISSUE TITLE
Why copy location and time to body notification on CalendarItem

### ISSUE THREAD

**Issue by freenetwork** [ecederstrand/exchangelib#341]
![image](https://user-images.githubusercontent.com/3347236/36249731-2f93ee52-126e-11e8-82b9-99976b917595.png)

Location copy to When, and time copy to Where and add line "*~*~*~*~*~*~*~*~*~*"

item = CalendarItem(
        start = tz.localize(EWSDateTime(start.year, start.month, start.day, start.hour, start.minute)),
        end = tz.localize(EWSDateTime(end.year, end.month, end.day, end.hour, end.minute)),
        subject = conference.name,
        body = body,
        location = location,
        categories = ['ВКС'],
        required_attendees = required_attendees,
        optional_attendees = optional_attendees,
        reminder_is_set = True
    )
    res = account.calendar.bulk_create(items=[item], send_meeting_invitations= SEND_TO_ALL_AND_SAVE_COPY)
    print (res)

**Comment by ecederstrand** [comment]
What did you expect to happen?

We just create the items in the Exchange store. We have no control over how it's displayed in Outlook.

**Comment by m2mbr** [comment]
@ecederstrand I think the result should be just the content of the body field

**Comment by ecederstrand** [comment]
exchangelib doesn't add any tilde-formatted lines or enhancements to the body field, so I assume this is something that either your client or your server is adding for you. You can check by fetching the original body contents again:

```python
item.referesh()
print(item.body)
```

If the tilde line is there, then you server is modifying the message somehow. If not, then your client is the one adding it.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you still think this is an error in exchangelib.

**Comment by ouyangde** [comment]
> e

when query calendar items from sender's account, they are not modified, but when from receiver's, we can see extra lines are added. It seems that the exchange server is modifying the message. But if I use Outlook to do the same thing, then neither items are modified.
So there must be some thing differences between exchangelib and Outlook.

**Comment by ouyangde** [comment]
> exchangelib doesn't add any tilde-formatted lines or enhancements to the body field, so I assume this is something that either your client or your server is adding for you. You can check by fetching the original body contents again:
> 
> ```python
> item.refresh()
> print(item.body)
> ```
> 
> If the tilde line is there, then you server is modifying the message somehow. If not, then your client is the one adding it.


when query calendar items from sender's account, they are not modified, but when from receiver's, we can see extra lines are added. It seems that the exchange server is modifying the message. But if I use Outlook to do the same thing, then neither items are modified.
So there must be some thing differences between exchangelib and Outlook.
