### ISSUE TITLE
Is there any method/API to list all the users in Exchange mailbox?

### ISSUE THREAD

**Issue by iniyanp** [ecederstrand/exchangelib#344]
Hi,

I am trying to find an API/method to list down all the users in mailbox. so that I can control the calendar events for them using exchangelib.

Thanks,
Iniyan P

**Comment by ecederstrand** [comment]
When you say "all users in mailbox", do you mean "all accounts on the server"? If so, then I don't think EWS provides this information. If not, then please explain in more detail what you mean by "users in mailbox".

**Comment by iniyanp** [comment]
Hi @ecederstrand . Yes. All accounts on the server. So If EWS doesn't provide this information, one option would be to use Microsoft Graph API ? Thanks,

**Comment by ecederstrand** [comment]
I don't know if the Graph API provides this information. If not, I think you'll have to use th PowerShell management commands.

**Comment by lihsingc** [comment]
Hi,

I wonder if exchangelib supports [GetSearchableMailboxes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.exchangeservice.getsearchablemailboxes?redirectedfrom=MSDN&view=exchange-ews-api), if that is the case then it might be possible by searching for an empty string.

**Comment by jackwhit3** [comment]
Hi,

I wonder if exchangelib supports [GetSearchableMailboxes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.exchangeservice.getsearchablemailboxes?redirectedfrom=MSDN&view=exchange-ews-api). If so, it might be possible to achieve by specifying an empty searchFilter.
