### ISSUE TITLE
Request Server Version

### ISSUE THREAD

**Issue by ccs1910** [ecederstrand/exchangelib#347]
Hello, 

In exchangelib, do we have a way to "Request Server Version"?  

ewsSoapHeader = {
't:RequestServerVersion': { attributes: { Version: process.env.EWS_SERVER_VERSION || "Exchange2013" }}
} 

thanks,
Christian CS

**Comment by ecederstrand** [comment]
exchangelib tries to automatically detect the server version, and will use the returned value in further requests. If you know what you're doing, you can set the version explicitly as explained in https://github.com/ecederstrand/exchangelib#setup-and-connecting

**Comment by ccs1910** [comment]
thanks!
we are using this version = Version(build=Build(15, 0)) for exchange 2013

**Comment by ecederstrand** [comment]
Looks good. There's a translation from build number to version name in https://github.com/ecederstrand/exchangelib/blob/4c213ae707dee1f7fbb1a89a0e7742eb8c443671/exchangelib/version.py#L49
