### ISSUE TITLE
Can you mark a message as read?

### ISSUE THREAD

**Issue by shellycao** [ecederstrand/exchangelib#35]
Is it possible to change the ```is_read``` field of a message and save the modified Message object?

**Comment by ecederstrand** [comment]
Yes, that should be possible. Just change the field and call save() on the message.

**Comment by shellycao** [comment]
Ah, okay! There was something else wrong with my code the first time I tried .save() so I assumed it didn't work. Thanks for clarifying.

**Comment by shellycao** [comment]
Every time I try to call save(), move() or move_to_trash() (even when I don't modify any fields) I always get this error: ```ErrorIncorrectUpdatePropertyCount: An object within a change description must contain one and only one property to modify```

I've looped through my entire inbox to see if it was a one time thing, but the error is thrown for each e-mail. Others online have also gotten this error, but they weren't using exchangelib. Their solutions didn't apply to my situation - they had to update fields one at a time (as opposed to trying to update multiple things at once).

If you had any suggestions, that'd be great! If this error isn't related to exchangelib, sorry!

**Comment by ecederstrand** [comment]
Can you turn on debug logging for exchangelib and post the `UpdateItem` request XML? Debug logging spews out a lot of data, but you'll find it right above the line that prints the response XML containing the `ErrorIncorrectUpdatePropertyCount` string.

Also, the code that triggers this would be great, so we can add it to the test suite.

Take care to anonymise any sensitive data :-)

**Comment by shellycao** [comment]
How do you turn on debug logging? I tried adding ```import logging``` and ```logging.getLogger('exchangelib').setLevel(10)```, but I got the same error message as before.

Here's my code, it's pretty basic:

    from exchangelib import DELEGATE, Account, Credentials, Configuration, NTLM
    creds = Credentials(
        username = 'abc',
        password = 'abc')
    config = Configuration(
        server = 'abc.com',
        credentials = creds,
        auth_type = NTLM)
    account = Account(
        primary_smtp_address = 'abc@abc.com',
        config = config,
        access_type = DELEGATE)
    for message in account.inbox.all():
        #message.is_read = True
        message.save()

**Comment by ecederstrand** [comment]
Thanks for the test case! You can turn on logging by adding this at the top of your script:

```
import logging
loglevel = logging.DEBUG
logging.basicConfig(level=loglevel)
logging.getLogger('exchangelib').setLevel(loglevel)
```

**Comment by ecederstrand** [comment]
Can you try the latest commit, https://github.com/ecederstrand/exchangelib/commit/7e814bd36c5d89178532b32085ed814cbcff1e8c ? I just fixed some errors with `save()` on existing items. If you still get errors, I'll need the request  XML that triggers the `ErrorIncorrectUpdatePropertyCount`.

**Comment by shellycao** [comment]
The latest commit works! Thanks so much. Did you still want the XML?

**Comment by ecederstrand** [comment]
Great! In that case, I don't need the XML. Just open a new issue containing the relevant XML if you get new exceptions.
