### ISSUE TITLE
HTMLBody

### ISSUE THREAD

**Issue by cr1010** [ecederstrand/exchangelib#350]
Hi, Im not sure if there is an issue with HTMLBody or I am just not using it correctly in my Django project. I have imported HTMLBody from exchangelib and are using the following code in my CalendarItem:

```
item = CalendarItem(
                folder=account.calendar,
                body = HTMLBody('<html><body><strong>Client Name: </strong>%s</body></html>') % client_name,
```

This is rendering as follows in the calendar invite:

> <html><body><strong>Client Name: </strong>JOE BLOGGS</body></html>

The rest of the functionality works amazingly!, just have this issue with rendering HTML content in the body.

Do you have any suggestions on how I can get the HTML recognised?

**Comment by ecederstrand** [comment]
It's possible that the `%` operator returns a `str` operator. Have you tried first formatting the string and then creating an `HTMLBody` instance?

**Comment by cr1010** [comment]
Perfect! Thanks for your guidance.

I created a variable:
`body = '<html><body><strong>Client Name: </strong>%s</body></html>' % client_name`

then used the variable in CalendarItem:
```
                item = CalendarItem(
                folder=account.calendar,
                body = HTMLBody(body),

```
