### ISSUE TITLE
Custom Header and override Message-ID

### ISSUE THREAD

**Issue by jscurtu** [ecederstrand/exchangelib#358]
Is there a way to add a custom header key/value? 
e.g: 

X-Custom-Me: Some Value 

And add a override/custom Message-ID ?

Thanks

**Comment by ecederstrand** [comment]
Yes. You have to use extended properties for that. See https://msdn.microsoft.com/en-us/library/office/dn596091(v=exchg.150).aspx

**Comment by jscurtu** [comment]
@ecederstrand thanks for the reply.. 

Dont know if I am doing something wrong, but its not working.. 

`from exchangelib import ExtendedProperty


class AddTransactionId(ExtendedProperty):
    distinguished_property_set_id = 'InternetHeaders'
    property_name = 'X-Transaction-Id'
    property_type = 'String'


Message.register('ta_id', AddTransactionId)


def send_test():

    m = Message(
        account=account,
        folder=account.sent,
        subject='Daily motivation',
        body='All bodies are beautiful',
        ta_id='<550e8400-e29b-11d4-a716-446655440000.0001@test.test>',
        to_recipients=[Mailbox(email_address='sales@myadlerglobal.com')]
    )

    print(m.ta_id)
    m.send_and_save()`

Also tried overriding the Message-ID by adding message_id='TEST12328379837' to the Message attributes but dont work.. 

Any idea? 

Thx

**Comment by ecederstrand** [comment]
What is not working? Does the receiver not see the header, or are you getting exceptions in the script you posted?

**Comment by jscurtu** [comment]
Sorry, just see it actually works.. I now see the custom header.
But overriding the Message-ID does not work.

**Comment by jscurtu** [comment]
When I write it dont work, then I mean its not overriding.. I do not have any exceptions

**Comment by ecederstrand** [comment]
You can't change the `message_id` value, AFAIK. We've marked it as read-only, at least, and I think we have a test to check that it is in fact not writable: https://github.com/ecederstrand/exchangelib/blob/a0a84115c4949963e120b47fa15d931b2bf2a960/exchangelib/items.py#L579

**Comment by jscurtu** [comment]
i override the read-only and tested it, it works.. 
#359 

Thanks alot for your help!
