### ISSUE TITLE
How do I search for all calendar events on a day?

### ISSUE THREAD

**Issue by huo-jiaquan** [ecederstrand/exchangelib#364]
Hi, ecederstrand

I tried to search for all calendar events on a day with
`calendar.filter(start__range=(start, end))`
It only returned the non-recurring events. How do I search for all the events including both recurring and non-recurring ones?

Many thanks
Jiaquan

**Comment by ecederstrand** [comment]
To get recurring events unfolded, you need to use the `.view()` method instead. See https://github.com/ecederstrand/exchangelib#searching
