### ISSUE TITLE
Error when using QuerySet

### ISSUE THREAD

**Issue by c2d** [ecederstrand/exchangelib#365]
When using a combination of filters on a calendar I get (without any obvious reason to why) an error like this 
`  raise ValueError("Unknown fieldname '%s' on class '%s'" % (fieldname, cls.__name__))
ValueError: Unknown fieldname 'start' on class 'Outbox'
`
for about 50% of the requests.
The filter looks like this:

`account.calendar.filter(start__range=(tz.localize(EWSDateTime(2018, 3, 17)), tz.localize(EWSDateTime(2018, 3, 22)))).filter(subject='Topic').filter(categories='MyCategory')`

Has anyone an idea what is going wrong here?

**Comment by ecederstrand** [comment]
Which version of exchangelib is this? Does this also fail with the latest version (currently 1.10.7)?

It may be that the calendar folder is being mistakenly parsed as an Outbox folder when we parse the XML in the response from the server, but I have a hard time seeing how that is possible. See https://github.com/ecederstrand/exchangelib/blob/8041519d5b1ac2486cfa3e5035b3e79675ac7004/exchangelib/folders.py#L1074

**Comment by c2d** [comment]
@ecederstrand  This indeed does not fail in the latest version, but in 1.10.5 (I am also completely lost as to why though). Thank you.
