### ISSUE TITLE
ErrorInternalServerError WebClient FormQueryString

### ISSUE THREAD

**Issue by frennkie** [ecederstrand/exchangelib#372]
https://github.com/ecederstrand/exchangelib/blob/600192942bbfb7763083179352593b37182d436c/exchangelib/items.py#L176

Could this be because they should be `item` instead of `calendar` ?!
* item:WebClientEditFormQueryString
* item:WebClientReadFormQueryString

https://msdn.microsoft.com/en-us/library/hh354700(v=exchg.150).aspx

**Comment by ecederstrand** [comment]
Thanks!
