### ISSUE TITLE
Add a simple way to check version at runtime, e.g. __version__

### ISSUE THREAD

**Issue by alpal** [ecederstrand/exchangelib#376]
See thread in #225 - https://github.com/ecederstrand/exchangelib/issues/225#issuecomment-355553234 - I think it's possible there are times when it might be nice to be able to simply check the version of the library at run time.

**Comment by ecederstrand** [comment]
Long overdue. Thanks!

**Comment by alpal** [comment]
Thank you! Sorry it took me a while to actually raise it :)
