### ISSUE TITLE
How to deleted Occurrence from CalendarItem?

### ISSUE THREAD

**Issue by freenetwork** [ecederstrand/exchangelib#383]
```python
items = account.calendar.all()
for item in items:
    print (item.deleted_occurrences)
    if item.deleted_occurrences is None:
        start = tz.localize(EWSDateTime(2018, 4, 8, 5, 0))
        item.deleted_occurrences = [DeletedOccurrence(start=start.date())]
    else:
        start = tz.localize(EWSDateTime(2018, 4, 8, 5, 0))
        item.deleted_occurrences.append(DeletedOccurrence(start=start.date()))
    print (item.deleted_occurrences)
    item.save(send_meeting_invitations = SEND_ONLY_TO_ALL)
```

It is return printing:
```
None
[DeletedOccurrence(start=EWSDate(2018, 4, 8))]
```

Вut Occurrence not deleted.

**Comment by ecederstrand** [comment]
`deleted_occurrences` is a read-only field, so changing it and calling `save()` does not have any effect:

```python
>>> from exchangelib import CalendarItem
>>> CalendarItem.get_field_by_fieldname('deleted_occurrences').is_read_only
True
```

`account.calendar.all()` returns the master calendar items, where you can only change certain attributes that concern all occurrences of a recurring item. To delete a specific occurrence, you need to use `account.calendar.view()` to fetch the individual occurrences. You can then call `item.delete()` to delete the occurrences you want.

**Comment by freenetwork** [comment]
It is work!

**Comment by freenetwork** [comment]
How to change occurrence? )

**Comment by ecederstrand** [comment]
Using the same procedure: get hold of the occurrence using `view()`, change the (non-read-only) fields you want, and call `item.save()`.

**Comment by ecederstrand** [comment]
Actually, there's a bug where calling just `item.save()` on an occurrence will fail. You need to call `item.save(update_fields=['start', 'end', 'subject', ...])`. I'll commit a fix shortly.
