### ISSUE TITLE
Custom Root CA

### ISSUE THREAD

**Issue by frennkie** [ecederstrand/exchangelib#388]
The exchange servers I'm connecting to have TLS certificates that are issue by an internal CA. I found the snippet that turns off the TLS certificate verification. This is OK for development and testing but not for production. 

What would be the recommended (and then may be also documented) way to add a custom root certificate chain? I have made the following and it's working, but it's not really "flexible".

```python
class CustomRootCAHTTPAdapter(requests.adapters.HTTPAdapter):
    # An HTTP adapter that uses a custom root CA certificate at a hard coded location
    def cert_verify(self, conn, url, verify, cert):
        super(CustomRootVerifyHTTPAdapter, self).cert_verify(conn=conn, url=url, verify="root_ca.crt", cert=cert)
```

**Comment by ecederstrand** [comment]
Python, or the Python community, has no easy or standard way to do thins, AFAIK. But there are various ways to get what you want:

1. `requests` will use the `certifi` package if it's installed. You could convince that do pick up your custom certificates (but beware of https://github.com/certifi/python-certifi/issues/22).
2. `requests` has various ways to define custom certificates. See http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
3. The most general solution is the custom `HTTPAdapter` class, as you have implemented, and that I see as the one exchangelib should recommend and document.

**Comment by ecederstrand** [comment]
I'm curious why you think your example is not sufficiently flexible. If you have lots of contexts where you need each to have their own custom certificate, you could just do something like:

```python
from urllib.parse import urlparse
class CustomRootCAHTTPAdapter(requests.adapters.HTTPAdapter):
    # An HTTP adapter that uses a custom root CA certificate at a hard coded location
    def cert_verify(self, conn, url, verify, cert):
        cert_file = {
            'example.com': '/path/to/example.com.crt',
            'mail.internal': '/path/to/mail.internal.crt',
            ...
        }[urlparse(url).hostname]
        super(CustomRootVerifyHTTPAdapter, self).cert_verify(conn=conn, url=url, verify=cert_file, cert=cert)```

**Comment by frennkie** [comment]
My concern was more "How you the dev dynamically set the ca_bundle file?" or even "How you a enduser set a custom root CA?". So I was kind of thinking along the lines of `account = Account(...., verify="ca_bundle.pem")` or maybe `BaseProtocol.HTTP_ADAPTER_CLS = CustomRootCAHTTPAdapter(file="ca_bundle.pem")`... but both your example and my code can easily be adapted to that.. so I think this can be closed...

**Comment by ecederstrand** [comment]
This project previously had an `Account(...., verify_ssl=False)` option. After a while, someone also wanted `Account(...., verify="ca_bundle.pem")`. Then someone only wanted it for the internal server and not Office365, and they were using a hybrid version so you didn't know which server you were hitting before the autodiscover lookup was made. After a few months, someone else wanted `Account(...., proxy_server='example.com')`, except actually different proxy servers for HTTP and HTTPS...

So, I'm closing this, because we're looking into a rabbit hole. I don't think we can get much more flexible and user-friendly than the current offering :-)
