### ISSUE TITLE
Not able to send e-mail since 1.7.1

### ISSUE THREAD

**Issue by vladanmilosevic73** [ecederstrand/exchangelib#39]
Hi,
I have been successfully copy-pasting code from your examples which send e-mails. I do not require a lot - I just want to send an e-mail. (I will work on reading it later). My Python knowledge is modest - basic stuff and Lego programming (programming using blocks someone else made :)).
My tests were working fine until I have tried up replicate this on a host which was newly built and using 1.7.2 version when I started getting this exception:

    m.send()  # Or m.send_and_save() if you want a copy in the 'Sent' folder
    File "C:\Program Files\Python35\lib\site-packages\exchangelib-1.7.1-py3.5.egg\exchangelib\folders.py", line 1201, in send
    raise ValueError('Item must have an account')
    ValueError: Item must have an account

My code:

`
    from exchangelib.folders import Message, Mailbox
    from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, \
        EWSDateTime, EWSTimeZone, Configuration, NTLM, Q
    from exchangelib.folders import Calendar
    import locale
    
    email = 'a@b.com'
    
    locale.setlocale(locale.LC_ALL, '')
    credentials_in = Credentials(username='DOMAIN\\username', password='secret')
    config = Configuration(
    server='email.com',
    credentials=credentials_in,
    auth_type=NTLM
    )
    a = Account(primary_smtp_address=email, config=config,
                  access_type=DELEGATE)
    m = Message(
         folder=a.sent, 
         subject='Daily motivation', 
         body='All bodies are beautiful', 
         to_recipients=[Mailbox(email_address='a@b.com')])
     m.send()  # Or m.send_and_save() if you want a copy in the 'Sent' folder
`

I started comparing commits, but, thought that you might have somewhere to check this better (and faster).

**Comment by ecederstrand** [comment]
When you create a message and call `send()` on it, the message needs to know which account to save to. Just do this:

```python
m= Message(
    account=a, 
    subject=...
)
m.send()```

**Comment by vladanmilosevic73** [comment]
I just managed to find the commit and where it tests for account. Sorry for raising the alarm so quickly. Trying now.

commit: https://github.com/ecederstrand/exchangelib/commit/8d403811132c1f754d905d81dd6a0e055b90a98a
 Thanks for *very* quick response!

**Comment by vladanmilosevic73** [comment]
Got another exception, but managed to move around it by removing the folder:

Exception:
  File ".\email-test.py", line 26, in <module>
    m.send()  # Or m.send_and_save() if you want a copy in the 'Sent' folder
  File "C:\Program Files\Python35\lib\site-packages\exchangelib-1.7.1-py3.5.egg\exchangelib\folders.py", line 1223, in send
    send_meeting_invitations=send_meeting_invitations)
  File "C:\Program Files\Python35\lib\site-packages\exchangelib-1.7.1-py3.5.egg\exchangelib\folders.py", line 793, in _save
    send_meeting_invitations=send_meeting_invitations)
  File "C:\Program Files\Python35\lib\site-packages\exchangelib-1.7.1-py3.5.egg\exchangelib\account.py", line 180, in bulk_create
    raise AttributeError("Folder must be None in send-ony mode")
AttributeError: Folder must be None in send-ony mode

But the correct version should be:
    m = Message(
        account=a,
        subject='Daily motivation', 
        body='All bodies are beautiful', 
        to_recipients=[Mailbox(email_address='a@b.com')])
    m.send()  # Or m.send_and_save() if you want a copy in the 'Sent' folder

Now it works fine.

**Comment by vladanmilosevic73** [comment]
Tested in 1.7.2 also - works fine.

Many thanks! You might want to update the e-mail sending example or put it on the example page.

Many thanks!

**Comment by ecederstrand** [comment]
I'd love to update the e-mail sending example. Where did you find it? FWIW, this module is in dear need of real documentation.

**Comment by vladanmilosevic73** [comment]
It is issue #18. I have used that one to send e-mails. And for tests also. I would offer to write it, if I understood it :)

**Comment by ecederstrand** [comment]
Thanks! I have updated the example and added an email sending example to the README

**Comment by vladanmilosevic73** [comment]
Excellent! Thank you for speedy update and clarification
