### ISSUE TITLE
fetching mime_content for 3 years from office 365 inbox (approx. 5000 emails)

### ISSUE THREAD

**Issue by anusheh** [ecederstrand/exchangelib#390]
Hello,

I am writing a connector in python using exchangelib that is fetching the mime_content of emails for 3 years (approx 5000 emails). I am using a Service Account, Iterator, as well as Chunkify. However after processing around 2500 emails the connector hangs and does not proceed further. It sometimes goes into Server Busy catch block and ends (as I have added a condition to loop five times when it catches the Server Busy error after adding sleep), and sometimes it gives a memory error. 

Basically we want only headers - the code was working fine without any Server Busy or memory error when we were fetching only headers. However the header does not contain fields like 'To','From','CC' and that is why we are fetching mime_content. Is there any way to (1) fetch header fields (Return-Path, Authentication-Results, Received, Received-SPF etc) and 'To','From','CC' together in one call or to (2) fetch the mime_content without the payload/body? Such that we get the required header fields without hitting the rate limiting policies of the server. 

Code snippet below - 

```python
item = my_account.inbox.filter(
    datetime_received__gte=tz.localize(EWSDateTime(2015, 4, 1))
).only('mime_content').iterator(page_size=500)
p = Parser()
logging.basicConfig()

exceptionCount = 0;
while (exceptionCount < 5):
    try:
        for chunk in chunkify(item, 500):
            for msg in chunk:
                try:
                    myMimeContent = msg.mime_content
                    if myMimeContent is None:
                        continue;
                    myParsedMime = p.parsestr(myMimeContent)
                    myHeaderList = myParsedMime.items()
                    if myHeaderList is None:
                        continue;
                except ParseError:
                    continue;
                for header in myHeaderList:
            # Process the required headers
            time.sleep(120)

    except ErrorServerBusy as e:
        print 'Server busy. Waiting..'
        time.sleep(120)
        exceptionCount = exceptionCount + 1;
```

It would be great if you could help.

Thank you.

**Comment by ecederstrand** [comment]
I believe most message headers are available in the `headers` attribute. `Message` items also have other attributes that could be of use, e.g. `author`, `sender`, `to_recipients` etc. See `Message.FIELDS`. If you need more specific attributes than that, you'll have to look into extended properties, but I have no idea if the fields you want are available that way.

It's not possible to fetch `mime_content` without the body, as far as I know. It's delivered as a singe binary, base64-encoded blob.

Please note that more graceful handling of `ErrorServerBusy` was added in https://github.com/ecederstrand/exchangelib/commit/7aa76d212b0b84929f35a293c9cfd59e5713d110 so try out v. 1.11 if you haven't done so already.

**Comment by anusheh** [comment]
Ok no problem and thanks for the information.
