### ISSUE TITLE
Subscribe to Exchange notifications (webhook)

### ISSUE THREAD

**Issue by RemiDesgrange** [ecederstrand/exchangelib#394]
Hi,

It seems that exchange is capable of doing webhook (sort of) https://msdn.microsoft.com/en-us/library/office/dn458791(v=exchg.150).aspx

I cannot find any information regarding this feature in exchangelib. In case this feature exist in exchangelib, can you point me the source ?

Thanks !

**Comment by ecederstrand** [comment]
This is a duplicate of #145 and #209. There is a WIP merge request available in #355.
