### ISSUE TITLE
compare 2 mailbox

### ISSUE THREAD

**Issue by dastious** [ecederstrand/exchangelib#395]
I migrate source_mailbox to target_mailbox with account.export and account_target.upload, everything is working, but I'm looking to make new migration that migrate only the new mail, or modified mail.

I tried comparing ItemId and Changekey, but they are not the same on account_target. Any idea how can I do it ?

**Comment by ecederstrand** [comment]
You are correct that export+upload does not produce a 1:1 copy of all field values.

You will probably have to make a custom comparison function. There are some pointers on which fields to ignore in the export/upload test at https://github.com/ecederstrand/exchangelib/blob/44a0b17c53a455da0b6afb6c047d9d81804909b4/tests/__init__.py#L4554
