### ISSUE TITLE
Sending invitation by delegate

### ISSUE THREAD

**Issue by shaktikshri** [ecederstrand/exchangelib#399]
Hi, I have delegate access to a mailbox. However when I create a calendar item using the following script,

```python
credentials = Credentials('myemail@sample.com', 'password')
account = Account(primary_smtp_address='email_i_want_to_update@sample.com', credentials=credentials, autodiscover=True, access_type=DELEGATE)
attendees = ['abc@sample.com']
item = CalendarItem(
    account=account,
    folder=account.calendar,
    start=tz.localize(EWSDateTime(2018, 5, 10, 3, 0)),
    end=tz.localize(EWSDateTime(2018, 5, 10, 3, 30)),
    subject="Some meeting invitation",
    body="Please come to my meeting",
    required_attendees=attendees
)
item.save(send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY)
```

and send it, it gets reflected as me as the organiser and not the primary email for which I have delegate access. Any way I can get this done?

**Comment by ecederstrand** [comment]
You should be able to set the organizer explicitly with `organizer = 'anne@example.com'`. See also #340

**Comment by ShaktiKShrivastava** [comment]
I have access as an editor to the primary email's calendar. However it is not getting reflected as him as the organiser even though I set it explicitly

**Comment by ShaktiKShrivastava** [comment]
Let me check with all the rights on the primary's account, not just calendar. But its weird since I am able to do the same thing from within outlook, but not from the python library :/

**Comment by ShaktiKShrivastava** [comment]
No luck :(

**Comment by ecederstrand** [comment]
I think we'll need a working example in e.g. C# or a trace of the XML requests and responses of a working interaction with Exchange to work out what we're doing differently.

**Comment by ShaktiKShrivastava** [comment]
I suspect the `item.save(send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY)` is saving it to the user's calendar and not the actual primary's email address. This is mentioned in the C# request for the EWS.

https://msdn.microsoft.com/en-us/library/office/dn641956(v=exchg.150).aspx#bk_createewsma

**Comment by ShaktiKShrivastava** [comment]
I tried out sending the invitation with delegate permission using XML template, and it works perfectly fine. For other users who may find this issue, please use the below XML schema,

`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
         xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
         xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <m:CreateItem SendMeetingInvitations="SendToAllAndSaveCopy">
      <m:SavedItemFolderId>
        <t:DistinguishedFolderId Id="calendar">
          <t:Mailbox>
            <t:EmailAddress>primaryemail@sample.com</t:EmailAddress>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:SavedItemFolderId>
      <m:Items>
        <t:CalendarItem>
          <t:Subject>Team building exercise</t:Subject>
          <t:Body BodyType="HTML">Lets learn to really work as</t:Body>
          <t:ReminderMinutesBeforeStart>60</t:ReminderMinutesBeforeStart>
          <t:Start>2018-05-10T23:00:33.756+05:30</t:Start>
          <t:End>2018-05-10T23:30:33.756+05:30</t:End>
          <t:Location>Conference Room 12</t:Location>
          <t:RequiredAttendees>
            <t:Attendee>
              <t:Mailbox>
                <t:EmailAddress>youremail@sample.com</t:EmailAddress>
              </t:Mailbox>
            </t:Attendee>
          </t:RequiredAttendees>
        </t:CalendarItem>
      </m:Items>
    </m:CreateItem>
  </soap:Body>
</soap:Envelope>
`

**Comment by ecederstrand** [comment]
What are `primaryemail@sample.com` and `youremail@sample.com` in the XML, compared to `myemail@sample.com` and `email_i_want_to_update@sample.com` from your previous example?

**Comment by ShaktiKShrivastava** [comment]
Sorry I put it in a wrong way, it should be,
`
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
         xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
         xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <m:CreateItem SendMeetingInvitations="SendToAllAndSaveCopy">
      <m:SavedItemFolderId>
        <t:DistinguishedFolderId Id="calendar">
          <t:Mailbox>
            <t:EmailAddress>email_i_want_to_update@sample.com</t:EmailAddress>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:SavedItemFolderId>
      <m:Items>
        <t:CalendarItem>
          <t:Subject>Team building exercise</t:Subject>
          <t:Body BodyType="HTML">Lets learn to really work as</t:Body>
          <t:ReminderMinutesBeforeStart>60</t:ReminderMinutesBeforeStart>
          <t:Start>2018-05-10T23:00:33.756+05:30</t:Start>
          <t:End>2018-05-10T23:30:33.756+05:30</t:End>
          <t:Location>Conference Room 12</t:Location>
          <t:RequiredAttendees>
            <t:Attendee>
              <t:Mailbox>
                <t:EmailAddress>any_attendees@sample.com</t:EmailAddress>
              </t:Mailbox>
            </t:Attendee>
          </t:RequiredAttendees>
        </t:CalendarItem>
      </m:Items>
    </m:CreateItem>
  </soap:Body>
</soap:Envelope>
`
and this XML should be POST using the credentials of myemail@sample.com for connecting to the exchange services.

I feel the definition of item.save is the one we need to update in exchangelib, since C# documentation mentions,
`meeting.Save(new FolderId(WellKnownFolderName.Calendar, 
        "primary@contoso.com"), 
        SendInvitationsMode.SendToAllAndSaveCopy);
`
> Note that when you save the item, the Save method call must identify the mailbox owner's Calendar folder. If the mailbox owner's Calendar folder is not specified, the meeting request gets saved to the delegate's calendar and not the mailbox owner's Calendar folder. You can include the mailbox owner's Calendar folder in the Save method call in two ways. We recommend that you instantiate a new instance of the FolderId object by using the WellKnownFolderName and the SMTP address of the mailbox owner.

`meeting.Save(new FolderId(WellKnownFolderName.Calendar,
    "primary@contoso.com"), SendInvitationsMode.SendToAllAndSaveCopy);`

OR

`// Identify the mailbox owner's SMTP address
    // and bind to their Calendar folder.
    Mailbox primary = new Mailbox("primary@contoso.com"); 
    Folder primaryCalendar = Folder.Bind(service, 
        new FolderId(WellKnownFolderName.Calendar, primary)); 
…
    // Save the meeting to the Calendar folder for the mailbox owner and send the meeting request.
    meeting.Save(primaryCalendar.Id, 
        SendInvitationsMode.SendToAllAndSaveCopy);`

Source is here, 
[https://msdn.microsoft.com/en-us/library/office/dn641956(v=exchg.150).aspx](url)

**Comment by ShaktiKShrivastava** [comment]
I certainly agree with you that we should be comparing the XML generated from the exchangelib code and this XML to see what is going wrong. Will update you on it once I check :)

**Comment by ecederstrand** [comment]
Thanks for the updates! I'm reopening the ticket to make sure it doesn't get lost.

**Comment by ecederstrand** [comment]
Hi @ShaktiKShrivastava 

Can you capture the XML that exchangelib produces in the latest version (1.11.4)? I suspect this may have been fixed, but I'd like to be sure, and I don't have a test server with multiple accounts ATM.

**Comment by ecederstrand** [comment]
Clopsing this issue as outdated. Setting a parent folder as a `DistinguishedFolderId` with a specific mailbox has been supported for quite a while.
