### ISSUE TITLE
Instantiate a Contact

### ISSUE THREAD

**Issue by michaelmontagne** [ecederstrand/exchangelib#400]
Hi.  I am attempting to do some editing on a contact.  The Persona object does not have all the fields I need.  i think the contact object does but I am unsure how a Persona can be converted to a Contact.  I get an error that tells me `__init__() takes exactly one argument (2 given)`.  I'm sure this is simple and I don't understand basic Python technique but I'm struggling.

This is how I am trying:

```python
for f in account.root.walk():
    if "foldername" in f.name:
        print (f)
        break
a = f.people()[0]
c = items.Contact([a])
```

**Comment by ecederstrand** [comment]
There's no automatic translation between a `Contact` and a `Persona`. You'll have to do the translation manually. A `Contact` is instantiated using keyword arguments, e.g. `Contact(display_name='john', initials='JM', ...)`. You can see the available fields with `print([f.name for f in Contact.FIELDS])`

I honestly don't know what the relation between a Contact and a Persona is in EWS. I just implemented it :-)

**Comment by michaelmontagne** [comment]
Excellent reply.  Thank you.  As it turns out it is the ".people()" function that returns a persona object.  If you simply iterate the folder, you get contacts!  Hopefully this helps someone else someday.  There is one more thing though.  I store a unique identifier in the "Account" field.  It's a previous app that I'm migrating.  It seems to be the one field that doesn't read from the object.  It returns the exchange account instead.  I tried editing the Contact object to add it to the fields but only succeeded in throwing a bunch of errors that led me to believe that is more complicated than that. Do you think it is possible to get the "Account" field from a Contact?

**Comment by michaelmontagne** [comment]
Success!  There is an Outlook plugin called "Outlook spy" that is a big help.
