### ISSUE TITLE
Can you use exchangelib to migrate email from Exchange 2010 to O365?

### ISSUE THREAD

**Issue by JPerryJr** [ecederstrand/exchangelib#401]
None of the tools I've tried work so, I'm looking into writing my own.
I believe all I need to move is email and calendar items. (maybe contacts).
I've seen the O365 REST API but I didn't anything that allowed you to create an email and not send it.
I guess what I'm looking for is more of a Mail Sync from EXCH2010 to O365.

Any ideas?

**Comment by ecederstrand** [comment]
Assuming this is just a single account, and you're not looking to migrate an entire site to O365, I belive the correct way to do this is to use export + upload. See https://github.com/ecederstrand/exchangelib#export-and-upload

**Comment by JPerryJr** [comment]
With so few accounts (4), I can simply run it  a few times and I'm good.
I'll give it a shot.

Thanks!
