### ISSUE TITLE
Get bcc receipients from Email

### ISSUE THREAD

**Issue by karthikrajender** [ecederstrand/exchangelib#402]
Hi everyone

How can i access bcc receipients from the email using exchnagelib

item.bcc_recipients -> gives value None for bcc mails, how can i get bcc is there any to get it.

**Comment by ecederstrand** [comment]
Is this an email you recieved? If so, then the list will be empty. That's the intended feature of BCC.

If it's an email you sent, then `bcc_recipients` should contain the recipients. If not, there's a bug in EWS or in exchangelib.

**Comment by karthikrajender** [comment]
hi ecederstrand

i had tested a email, which is send by some person to my mail id along with bcc recipients, when i tried to read that email from my mailbox  i didn't got bcc recipients

**Comment by ecederstrand** [comment]
As recipient of an email, you can't see other BCC recipients of that email. It's a feature of emails, not a bug. See https://en.wikipedia.org/wiki/Blind_carbon_copy
