### ISSUE TITLE
Can't upgrade Exchangelib

### ISSUE THREAD

**Issue by kfjelsted** [ecederstrand/exchangelib#404]
Although I was able to install Exchangelib on a Google cloud instance a month ago, I am not able to upgrade. The following is the output:

```
Linux python-dev-3cx 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) x86_64

kfjelsted@python-dev-3cx:~$ sudo pip install --upgrade exchangelib
Collecting exchangelib
  Using cached https://files.pythonhosted.org/packages/f5/6d/a8bc916c35a70a688645708cce2afea7ab8e658c634b7ddfc4cbfb1aff79/exchangelib-1.11.3-py2.py3-none-any.whl
Requirement not upgraded as not directly required: requests-ntlm>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from exchangelib) (1.1.0)
Requirement not upgraded as not directly required: isodate in /usr/local/lib/python2.7/dist-packages (from exchangelib) (0.6.0)
Requirement not upgraded as not directly required: future in /usr/local/lib/python2.7/dist-packages (from exchangelib) (0.16.0)
Requirement not upgraded as not directly required: python-dateutil in /usr/local/lib/python2.7/dist-packages (from exchangelib) (2.7.2)
Requirement not upgraded as not directly required: dnspython>=1.14.0 in /usr/local/lib/python2.7/dist-packages (from exchangelib) (1.15.0)
Requirement not upgraded as not directly required: cached-property in /usr/local/lib/python2.7/dist-packages (from exchangelib) (1.4.0)
Requirement not upgraded as not directly required: pytz in /usr/local/lib/python2.7/dist-packages (from exchangelib) (2018.3)
Collecting requests-kerberos (from exchangelib)
  Using cached https://files.pythonhosted.org/packages/ee/a2/866f2b9a60f75055137b9ad127033e397963b2c4769d4b5fab1c3c7e8be3/requests_kerberos-0.12.0-py2.py3-none-any.whl
Collecting defusedxml (from exchangelib)
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Requirement not upgraded as not directly required: six in /usr/lib/python2.7/dist-packages (from exchangelib) (1.10.0)
Requirement not upgraded as not directly required: requests>=2.7 in /usr/lib/python2.7/dist-packages (from exchangelib) (2.12.4)
Requirement not upgraded as not directly required: tzlocal in /usr/local/lib/python2.7/dist-packages (from exchangelib) (1.5.1)
Requirement not upgraded as not directly required: lxml>3.0 in /usr/local/lib/python2.7/dist-packages (from exchangelib) (4.2.1)
Requirement not upgraded as not directly required: pygments in /usr/local/lib/python2.7/dist-packages (from exchangelib) (2.2.0)
Requirement not upgraded as not directly required: ntlm-auth>=1.0.2 in /usr/local/lib/python2.7/dist-packages (from requests-ntlm>=0.2.0->exchangelib) (1.1.0)
Requirement not upgraded as not directly required: cryptography>=1.3 in /usr/local/lib/python2.7/dist-packages (from requests-ntlm>=0.2.0->exchangelib) (2.2.1)
Collecting pykerberos<2.0.0,>=1.1.8; sys_platform != "win32" (from requests-kerberos->exchangelib)
  Using cached https://files.pythonhosted.org/packages/9a/b8/1ec56b6fa8a2e2a81420bd3d90e70b59fc83f6b857fb2c2c37accddc8be3/pykerberos-1.2.1.tar.gz
Requirement not upgraded as not directly required: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3->requests-ntlm>=0.2.0->exchangelib) (1.11.5)
Requirement not upgraded as not directly required: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3->requests-ntlm>=0.2.0->exchangelib) (1.1.6)
Requirement not upgraded as not directly required: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3->requests-ntlm>=0.2.0->exchangelib) (2.6)
Requirement not upgraded as not directly required: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3->requests-ntlm>=0.2.0->exchangelib) (0.24.0)
Requirement not upgraded as not directly required: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.3->requests-ntlm>=0.2.0->exchangelib) (1.0.19)
Requirement not upgraded as not directly required: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3->requests-ntlm>=0.2.0->exchangelib) (2.18)
Building wheels for collected packages: pykerberos
  Running setup.py bdist_wheel for pykerberos ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hNVjpY/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-H81I1x --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  
  ----------------------------------------
  Failed building wheel for pykerberos
  Running setup.py clean for pykerberos
Failed to build pykerberos
Installing collected packages: pykerberos, requests-kerberos, defusedxml, exchangelib
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hNVjpY/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-z3y8tf/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-hNVjpY/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-z3y8tf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-hNVjpY/pykerberos/
kfjelsted@python-dev-3cx:~$ 
```

**Comment by kfjelsted** [comment]
This is a Google Cloud standard Debian 4.9.82-1+deb9u2 x86_64 installation. 
I can find no reference for installing libkrb5-dev
When attempting to install 
 sudo pip install pykerberos
The following occurs. 
Collecting pykerberos
  Using cached https://files.pythonhosted.org/packages/9a/b8/1ec56b6fa8a2e2a81420bd3d90e70b59fc83f6b857fb2c2c37accddc8be3/pykerberos-1.2.1.tar.gz
Building wheels for collected packages: pykerberos
  Running setup.py bdist_wheel for pykerberos ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-EQXAS2/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ArNcr_ --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pykerberos
  Running setup.py clean for pykerberos
Failed to build pykerberos
Installing collected packages: pykerberos
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-EQXAS2/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rZTWzM/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-EQXAS2/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-rZTWzM/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-EQXAS2/pykerberos/
kfjelsted@python-dev-3cx:~$ sudo pip install pykerberos

Up until now Exchangelib has worked out of the box with the standard Python install approach.
THis is blowing us out ofthe water for any continued use.
Can yu provide more information on the dependency and how this issue can be resolved?
 
-Kevin

**Comment by ecederstrand** [comment]
You are correct that `pykerberos` is failing to install on your system. I don't know how to do that on a Google Cloud instance, but try with `apt-get install  libkrb5-dev`, or `sudo apt-get install  libkrb5-dev` if you are not root already. Then try ``pip install pykerberos` again.

**Comment by kfjelsted** [comment]
Interesting!
The error seems to be the line <<< unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed>>>


I ran the following.
kfjelsted@python-dev-3cx:~$ sudo apt-get install libkrb5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libkrb5-dev is already the newest version (1.15-1+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
kfjelsted@python-dev-3cx:~$ sudo pip install pykerberos
Collecting pykerberos
  Using cached https://files.pythonhosted.org/packages/9a/b8/1ec56b6fa8a2e2a81420bd3d90e70b59fc83f6b857fb2c2c37accddc8be3/pykerberos-1.2.1.tar.gz
Building wheels for collected packages: pykerberos
  Running setup.py bdist_wheel for pykerberos ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4N4vbx/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-MBSnph --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o -isystem /usr/include/mit-krb5 -DGSSAPI_EXT
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pykerberos
  Running setup.py clean for pykerberos
Failed to build pykerberos
Installing collected packages: pykerberos
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4N4vbx/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_BsAhY/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o -isystem /usr/include/mit-krb5 -DGSSAPI_EXT
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4N4vbx/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_BsAhY/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4N4vbx/pykerberos/
kfjelsted@python-dev-3cx:~$

**Comment by kfjelsted** [comment]
The upgrade was resolved by first installing
sudo apt-get install build-essential libssl-dev libffi-dev python-dev

**Comment by ecederstrand** [comment]
Of wow, that's a lot of system packages for just one Python package! I'll make sure to document this, to make upgrading easier for other users.
