### ISSUE TITLE
redact or desensitize email in log to comply with GDPR

### ISSUE THREAD

**Issue by wei-hai** [ecederstrand/exchangelib#405]
read from environment variable as an option to redact or desensitize email address in log to comply with GDPR, for example, the email address is john.smith@example.com, after desensitization it will be j****h@example.com

**Comment by ecederstrand** [comment]
Thanks for looking into this!

Looking at #406, it only touches debug log statements. Usually, production servers will not be logging at this level, and if they do, it's to debug issues where the actual email is likely to be important to debugging.

If we truly need to remove any personally identifiable information at debug level, then there's a lot more work that needs to be done. For example, we log the raw XML request and response which may contain the full body of the emails requested, date and place for calendar appointments, etc. We would also need to look at exception messages.

I have started on an [anonymizing log handler](https://github.com/ecederstrand/exchangelib/blob/ce6df480b6cd8ca71dfb20129c1bea34e50f51b4/exchangelib/util.py#L336) that I intended to point people to when requesting raw log output in GitHub issues. Maybe we can build on that to strip sensitive information? It's also conceptually a better place to add log statement filtering than at the source of the message.

**Comment by wei-hai-pai** [comment]
we use managed service to store log information and we need to comply with GDPR, which means we cannot have any sensitive information in production server's log. We have other workaround to recognize which email address is causing problem so redacting email in debug level is okay for us.

**Comment by ecederstrand** [comment]
I'm just saying that if you're logging at debug level, then you will also be logging the full XML requests and responses, which contain not just email addresses but a lot of other sensitive data which would also violate GDPR.
