### ISSUE TITLE
Unexpected next offset: 0 -> 1000

### ISSUE THREAD

**Issue by KarelCoudijzer** [ecederstrand/exchangelib#41]
When looping over all items in a folder containing more then 1000 items.
I always get the warning "Unexpected next offset: 0 -> 1000" and don't retrieve all items within the folder.
I'm using Exchange2016 on outlook.office365.com
```python
folder = account.inbox
for item in folder.all():
    # Unexpected next offset: 0 -> 1000
```

**Comment by ecederstrand** [comment]
Fixed by https://github.com/ecederstrand/exchangelib/pull/42
