### ISSUE TITLE
Can you sponsor better hosting for the test suite?

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#412]
Currently, the test suite only has access to a single Exchange account on a very limited plan. This means it's not possible to test and debug certain features, such as:

* Meeting invitations
* Public and shared folders
* Cc and Bcc fields
* Impersonation and delegate access to 
* Global address list
* Access restrictions
* Appointment organizer field
* Private items

The issue tracker is already showing signs of this because we don't have proper test coverage of these areas.

If you are using exchangelib commercially in your product, or just really like this project, please consider hosting or sponsoring a more complete test environment for the test suite. Thanks!

**Comment by msta** [comment]
Hi there!
We are using your library in your project, and I'm _really_ happy using it - just the thought of having to personally program anything against the MS API's just makes me shudder.
I want to bring my $$$-guys a draft of a hosting environment that you ask for here. I have no idea of what you might need, so can you give me an idea?
Thanks again.

**Comment by ecederstrand** [comment]
Hi @msta and thanks for your interest!

I'm actually not familiar at all with Exchange administration, so I don't know exactly what is needed to allow access to all these features. I would like a better hosting environment to properly test existing features, but also to allow others to contribute new features that are actually testable. The current test server is a dirt cheap 1-seat plan that doesn't allow this.

Googling around, I think the [Business Essentials](https://products.office.com/da-dk/business/office-365-business-essentials) plan is a good bet. It's possible [Enterprise E1](https://products.office.com/da-dk/business/office-365-enterprise-e1-business-software) or greater would provide more features, but it's not clear to me what that would be. If you're reading this and have experience with Office 365 administration, please chip in!

We'll need 2 seats to test meeting requests, access restrictions, GAL and and private items, 1 to test public folders, 1 to test resources (I think) and 1 to test delegate/impersonation access. In total, we're looking at expenses of 2-300 DKK per month.

**Comment by ecederstrand** [comment]
I'm currently working in Copenhagen, BTW. I can drop by the Archii office some day and work out the details, if you are still interested.

**Comment by msta** [comment]
Thanks for the response. I think that would be great. I haven't floated the idea yet (we're launching a new product soon so it'd be immediately after), but a visit would be awesome.

**Comment by msta** [comment]
Hi again!
So I managed to convince our CEO that 2-300 DKK is a worthy investment to support your awesome library. How about stopping by next week for a coffee and a chat about how to set it up?
Do notice that we also have a bit of contact with Microsoft through a startup-service, so we might be able to secure some accounts through there..?

**Comment by ecederstrand** [comment]
No longer relevant. Closing.
