### ISSUE TITLE
Change Charset 

### ISSUE THREAD

**Issue by jscurtu** [ecederstrand/exchangelib#413]
Is there a way to change the charset used when sending an email? 

![grafik](https://user-images.githubusercontent.com/590307/40105808-59f1ef24-58f4-11e8-8464-9fba4569173c.png)

thx.

Jason

**Comment by ecederstrand** [comment]
I'm curious where you got this from? exchangelib doesn't do any MIME message handling. It just passes whatever raw or HTML body you add to your message on to EWS, so this is not something generated explicitly by exchangelib.

If you want to create MIME messages, you need to build the body by hand using e.g. https://docs.python.org/3.6/library/email.html You'll possibly have to set some extra email headers, too.

**Comment by ecederstrand** [comment]
Did you also send these emails using exchangelib? If not, you may have the same issue if you look at these emails using Outlook or another Exchange client.

Also, how are you reading the files you write to disk? If you read them using a normal text editor, then beware that `mime_content` is binary data so a normal text editor does not know which encoding to display the file as. You need a real email client that knows about MIME messages to do that.

**Comment by jscurtu** [comment]
No, i send the mails regulary using Message() and yes, i have the issue with looking at mails in any mail client, especially with text/plain view.

After I write the mime_content to disc, I have no issues opening them with a text editor at all..
I do parse them using the python email.parser (BytesParser) in a different process. 

What I did notice now is that, if I encode the email text to unicode before loading it in to HTMLBody() the charset changes to iso-8859-1 .. 

![grafik](https://user-images.githubusercontent.com/590307/40226649-84d72738-5a8c-11e8-8e4c-9f448276596a.png)

which means something is detecting (trying) it automaticlly when sending over EWS. 

Just seen this here so it is EWS related.. 
https://stackoverflow.com/questions/36156628/control-the-message-encoding-when-sending-email-using-ews-api

this is also wrong:

![grafik](https://user-images.githubusercontent.com/590307/40226873-36445374-5a8d-11e8-9487-6067bc73c2f1.png)

**Comment by ecederstrand** [comment]
Ok. How are you building the `Message` item and sending it? I think that to send MIME email with exchangelib, you have to build up the `mime_content` manually and send that instead of the `body` content, as suggested in the answer to the SO question.

**Comment by jscurtu** [comment]
This is how the message is built.. 

![grafik](https://user-images.githubusercontent.com/590307/40228145-c09b1294-5a90-11e8-9366-cd3c43531d58.png)

are there any examples how I would do that using the mime_content manually? 

Thanks..

**Comment by ecederstrand** [comment]
Ah. It definitely looks like you need to use `mime_content` rather than `body`. This is outside the scope of exchangelib, but you can start with the Python [email](https://docs.python.org/3.6/library/email.html) package.

**Comment by jscurtu** [comment]
But can I still use exchange to send it? If I build the mime content.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional issues with the `mime_content` field :-)
