### ISSUE TITLE
Moving/copying an item to a different mailbox wrongfully raises an exception

### ISSUE THREAD

**Issue by BenJoParadise** [ecederstrand/exchangelib#414]
According to [this exchange doc](https://msdn.microsoft.com/en-us/library/office/dn600291(v=exchg.150).aspx):

> If you're moving or copying an email message between two folders in the same mailbox, the new item is returned in the response, which gives you access to the new item ID. **However, if you're moving or copying an email message between two mailboxes or between a mailbox and a public folder, the new item is not returned in the response.**

However, exchangelib treats this as an incorrect behaviour, and raises an exception: https://github.com/ecederstrand/exchangelib/blob/c742030163b8d1b1993eee0d57bea25ca2e3e907/exchangelib/items.py#L360-L362

**Comment by ecederstrand** [comment]
Thanks for the report! Feel free to reopen if https://github.com/ecederstrand/exchangelib/commit/0def79f59897bfae41b3330d1fec2e6674b4ee95 doesn't fix this for you.
