### ISSUE TITLE
Editing/Creating a contact

### ISSUE THREAD

**Issue by michaelmontagne** [ecederstrand/exchangelib#415]
When I read an existing contact I get a field value that looks something like this for phone_number, addresses, email_addresses.

```python
[
    PhoneNumber(label='BusinessFax', phone_number='f:412-766-8100'),
    PhoneNumber(label='BusinessPhone', phone_number='(412) 777-8000'),
    PhoneNumber(label='BusinessPhone2', phone_number=None), 
    PhoneNumber(label='HomePhone', phone_number=None), 
    PhoneNumber(label='MobilePhone', phone_number=None)
]
```

It looks like a list of objects.  

I imagine I would need to recreate that to make a new Contact but I'm not sure how.  Same would go if I am changing an existing contact.  Hopefully this is an easy answer that is just basic Python that I don't understand quite yet.

**Comment by ecederstrand** [comment]
The `PhoneNumber`class is located in `exchangelib.indexed_properties`. A range of other contact field classes are located there, too. So to create a contact with a list of phone numbers, you would do:

```python
from exchangelib.indexed_properties import EmailAddress, PhysicalAddress, PhoneNumber
contact = Contact(
    display_name='John Doe',
    phone_numbers=[PhoneNumber(label='HomePhone', phone_number='123-456-7890')],    
    ...,
)
contact.save()
```

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional questions :-)
