### ISSUE TITLE
CategoryList or Color for CalendarItem

### ISSUE THREAD

**Issue by freenetwork** [ecederstrand/exchangelib#416]
How to use?
https://msdn.microsoft.com/en-us/library/ee203806(v=exchg.80).aspx

**Comment by ecederstrand** [comment]
That doesn't look like a protocol available via EWS, so I don't think that would be possible via exchangelib.

**Comment by ecederstrand** [comment]
You can add categories to calendar items using exchangelib, and then in your client, e.g. Outlook, you can assign colors to the categories you have created, if that's what you wanted to achieve.
