### ISSUE TITLE
Unable to access folder structure of a shared mailbox

### ISSUE THREAD

**Issue by bobusfindus** [ecederstrand/exchangelib#425]
Hi Eric... 

I have downloaded the latest source from GitHub, but am still having trouble accessing a shared mailbox using ExchangeLib. I have configured the credentials as follows:

```python
config = Configuration(server='my.mailserver.net', credentials=Credentials(
'WINDOMAIN\lan_user', config.LAN_PASS), auth_type=NTLM, service_endpoint='https://EWS-Server.asmx',)
sam_account = Account(
primary_smtp_address='other@shared-mailbox.com', config=config, access_type=DELEGATE)
```

However when I print the folder tree, exchangelib will only return folders in _my_ mailbox, not the other shared mailbox I'm trying to access:

```python
processed_folder = sam_account.root.tree()
print(processed_folder)
```

I read that the bug had been fixed on Github, but it still seems to be happening to me - have you got any ideas what's wrong? I'm pulling my hair out here!

Cheers, Bob

**Comment by ecederstrand** [comment]
@bobusfindus How did you install from GitHub? You may still be running an old version. `pip install -U git+https://github.com/ecederstrand/exchangelib.git`should do the trick.

@Dave-a-richards `get_folder_by_name()` was deprecated in version 1.10.2 and removed in 1.11.0, so that will not work for @bobusfindus.

**Comment by bobusfindus** [comment]
Hi Erik,

Yes I'd downloaded the zip from GitHub and installed via pip instead of
using pip to manage the download. I was running 1.11.3. A pip install
upgrade did the trick! Sorry for the bother - it's all working so shape now
:)

Bob

Sent from Astro <https://www.helloastro.com> for Android

On 10/06/2018 at 14:12, Erik wrote:

@bobusfindus <https://github.com/bobusfindus> How did you install from
GitHub? You may still be running an old version. pip install -U git+
https://github.com/ecederstrand/exchangelib.gitshould do the trick.

@Dave-a-richards <https://github.com/Dave-a-richards> get_folder_by_name()
was deprecated in version 1.10.2 and removed in 1.11.0, so that will not
work for @bobusfindus <https://github.com/bobusfindus>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ecederstrand/exchangelib/issues/425#issuecomment-396048201>,
or mute the thread
