### ISSUE TITLE
Issue saving attachment to email

### ISSUE THREAD

**Issue by Dave-a-richards** [ecederstrand/exchangelib#426]
I am able to save an attachment to an email most of the time, but on occasion it "hangs".  If I let it keep running, over time I will see on the exchange server side the the same file is being attached to the email multiple times.  The way I am adding the attachment and saving is:

```python
def attatchfile(email,filename,path,logger):
    logger.info("Begin attatching %s", filename)
    filename_and_path = path + filename
    logger.info("File full path is %s", filename_and_path)
    logger.info("Open file for reading as binary")
    with open(filename_and_path, mode='rb') as file:  # b is important -> binary
        logger.info("Read file into memory")
        binary_file_content = file.read()
    logger.info("Create file object to use as attatchment")
    my_file = FileAttachment(name=filename, content=binary_file_content)
    logger.info("Save file onto email object")
    email.attach(my_file)
    logger.info("Save email object back to exchange")
    email.save()
    logger.info("Done saving email object back to exchange")
    return "Successful"
```

The email.save() is never returning and that is where duplicate attachments are getting put onto the. email.

Possible Solution:  If this is due to some type of issue with the communication with the exchange server, then should I handle this with threading?  I can spin off a thread that calls this attachment function and kill it if it doesn't return in a set time.  However, if I do that, I would want to revert the email back to it's original state before I attached anything.  Is there a way to have a second, untouched email object open that I can re-save at this point to undo any changes that I may have already pushed to the server or would I need to keep track of the changes and undo them?

**Comment by ecederstrand** [comment]
You can do `email.refresh()` to have all fields on the `email` object reset with values from the server. If you want to be absolutely sure, you can even do `fresh_email = account.inbox.get(item_id=email.item_id, changekey=email.changekey)` to keep `email` untouched andget a fresh item from the server.

**Comment by Dave-a-richards** [comment]
Do you have any idea why the initial save() may be looping and saving the attachment to the email multiple times?  It doesn't throw an error, it just keeps attaching the same attachment.

**Comment by ecederstrand** [comment]
I don't have any firm conclusions, but it could be that the initial request succeeds but the Exchange server never sends a positive response, and we try again because we thought the request failed. You could [enable debug logging](https://github.com/ecederstrand/exchangelib#troubleshooting) to get a better understanding of what's going on.

**Comment by Dave-a-richards** [comment]
This is what the debug output is showing...

A LOT OF BINARY TEXT </t:Content></t:FileAttachment></m:Attachments></m:CreateAttachment></s:Body></s:Envelope>'
Response data: b''

INFO:exchangelib.util:Session 25158 thread 2164: Connection error on URL https://mail.url.com/EWS/Exchange.asmx (code 503). Cool down 10 secs
DEBUG:exchangelib.protocol:Server mail.url.com: Renewing session 25158
DEBUG:exchangelib.protocol:Server mail.url.com: Created session 17103
DEBUG:exchangelib.util:Session 17103 thread 2164: retry 1 timeout 120 POST'ing to https://mail.url.com/EWS/Exchange.asmx after 20s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mail.url.com
DEBUG:urllib3.connectionpool:https://mail.url.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:urllib3.connectionpool:https://mail.url.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0


****It just hung at this point here (although looking at the email it has the file attached) and then came back with the same as seen below****

A LOT OF BINARY TEXT </t:Content></t:FileAttachment></m:Attachments></m:CreateAttachment></s:Body></s:Envelope>'
Response data: b''

INFO:exchangelib.util:Session 17103 thread 2164: Connection error on URL https://mail.url.com/EWS/Exchange.asmx (code 503). Cool down 20 secs
DEBUG:exchangelib.protocol:Server mail.url.com: Renewing session 17103
DEBUG:exchangelib.protocol:Server mail.url.com: Created session 27896
DEBUG:exchangelib.util:Session 27896 thread 2164: retry 2 timeout 120 POST'ing to https://mail.url.com/EWS/Exchange.asmx after 40s wait
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mail.url.com
DEBUG:urllib3.connectionpool:https://mail.url.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0


****When it came back here it now had the file attached twice***

**Comment by ecederstrand** [comment]
This confirms my suspicion. The server returned an HTTP 503 status code on the first attachment request, but added the attachment anyway. We interpreted the HTTP 503 as a request to try again later, which is why the attachment is added multiple times.

I'm not sure what the best solution is here. The server provided zero context with the HTTP 503, so we can't distinguish it from at real error where we want to retry. You could try to change from using a `ServiceAccount` instance to a `Credentials` instance. You can then catch this error manually and only retry after fetching a fresh item and determining if the attachment was indeed added.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's something we can improve in exchangelib :-)
