### ISSUE TITLE
Saving Outlook Items

### ISSUE THREAD

**Issue by nstr10** [ecederstrand/exchangelib#43]
I'm trying to figure out how to save Outlook Items that are attached to emails (emails attached to emails). For normal file attachments, I simply do something like:
```
for att in item.attachments:
    with open(filename, "wb") as temp:
        temp.write(att.content)
```
However, Outlook Items have no attribute "content" and I therefore have no idea what attribute needs to be written to disk. I'm fairly certain I'm just overlooking something - there is an overwhelming amount of information returned if I print out the attributes of the attachment.

Is there a way to get a binary version of the attachment to save?

**Comment by ecederstrand** [comment]
`item.attachments` is a mixed list of `FileAttachment` And `ItemAttachment` objects. The latter has an `item` attribute which is a `Message` object if your attachment is an e-mail, a `CalendarItem` if you attached an appointment, etc. Does that help?

**Comment by nstr10** [comment]
It definitely puts me closer to my goal! In .NET the `ItemAttachment` equivalent to `FileAttachment.content` would be `ItemAttachment.Item.MimeContent` but it doesn't look like the `MimeContent` attribute is exposed in the `Message` object in exchangelib.

I think I might be able to accomplish what I need by detaching the `ItemAttachment`, moving it to the inbox, and iterating through again. I'll experiment with this over the weekend.

**Comment by ecederstrand** [comment]
We don't yet support the `MimeContent` attribute on `Message`. Does it contain data that you can't access otherwise, e.g. via the `body` field?

**Comment by ecederstrand** [comment]
`Item.mime_content` is available as of https://github.com/ecederstrand/exchangelib/commit/5c19edd99c577e1a7b91a6818cc6d8721abd9062 so you can get  the attachment MIME content via `some_item.attachments[0].item.mime_content`, assuming `attachments[0]` is an `ItemAttachment`. Let me know if this fixes the issue for you.

**Comment by nstr10** [comment]
I've uninstalled and re-installed exchangelib, but getting `AttributeError: 'Message' object has no attribute 'mime_content'`
Trying `attachments[0].mime_content` returns the same, but about `ItemAttachment`
Dumping all the properties of `attachments[0].item` and searching for `mime` gives no results.

Should I be manually cloning the repo rather than using pip?

The reason the MIME content is important to me is because it's the only way to get the headers from an attached email. I'm using this library to help monitor an inbox where people forward malware, spam, and phishing emails, typically as item attachments.

**Comment by ecederstrand** [comment]
Oh, that's a cool use case!

I haven't released a new version, so you need to clone from GitHub and run `python3 setup.py build install`. Or put this in a `requirements.txt` file in your project and install using `pip install -U -r requirements.txt`

```
git+https://github.com/ecederstrand/exchangelib.git
```

I also opened https://github.com/ecederstrand/exchangelib/issues/44 today. That might be useful to you.

**Comment by nstr10** [comment]
With a fresh clone, I am seeing the `mime_content` attribute but it is set to `None` in all of the test emails I've processed. I'll keep experimenting, but I suspect #44 will mean I don't really need to parse through the MIME contents.

**Comment by ecederstrand** [comment]
That's strange. This snippet prints MIME on my machine:

```
for message in a.inbox.all():
    print(message.mime_content)
```

Do you perhaps have a `.only(...)` clause in your query?

**Comment by nstr10** [comment]
The inbox I'm working with is too large to run `.all()` on, but running this doesn't work:
```
for message in account.inbox.find_items(datetime_received__range=(start_date, end_date)):
    print(message.mime_content)
```
Perhaps this is an issue with my exchange instance. I see you've pushed code for headers, so I'll try that out. It works on normal email, I just need to test it with some item attachments.

**Comment by nstr10** [comment]
Item attachments do not appear to have `.header` properties yet.

**Comment by ecederstrand** [comment]
Yes, they do :-) I think you have an issue with your local exchangelib installation. Please uninstall and reinstall from GitHub - the latest changes aren't on PyPI yet. This works for me:

```python
for message in a.inbox.all():
    if message.attachments:
        for a in message.attachments:
            if isinstance(a, ItemAttachment):
                print(a.item.headers)
```
This shouldn't be affected by the version of Exchange, but to be sure, you can enable DEBUG logging and see the XML response to check if it has an `InternetMessageHeader` attribute:

```python
import logging
loglevel = logging.DEBUG
logging.basicConfig(level=loglevel)

# Your code here

```

**Comment by nstr10** [comment]
Not sure what I did wrong yesterday - I had uninstalled and re-cloned, but after repeating those steps I'm able to get the headers on item attachments. I feel like I owe you a case of beer now.

**Comment by ecederstrand** [comment]
No problem :-) Can we close this issue?
