### ISSUE TITLE
ErrorInternalServerError accessing Account.contacts

### ISSUE THREAD

**Issue by alirezaimi** [ecederstrand/exchangelib#431]
I want to search in contact list of some account and get that contacts details back, but none of folders that told [here](https://github.com/ecederstrand/exchangelib#folders) not work because of `KeyError` exception .
Somehow i can't access to any of exchange account folders.

Is it permission or ... ?

Code :

	from exchangelib import Credentials, Account, Configuration
	from exchangelib.protocol import NoVerifyHTTPAdapter, BaseProtocol

	BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

	credentials = Credentials("YYY@XXX.com", 'PASSWORD')

	account = Account(
		primary_smtp_address="Account@XXX.com",
		autodiscover=True, 
		credentials=credentials
	)

	print(account)  # work properly with printing my account
	print(account.contacts)  # not work with KeyError Exception

Error : 

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	Traceback (most recent call last):
	  File "C:\Python\lib\site-packages\cached_property.py", line 69, in __get__
		return obj_dict[name]
	KeyError: 'contacts'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "C:\Users\dvp7\Desktop\ex.py", line 20, in <module>
		print(account.contacts)
	  File "C:\Python\lib\site-packages\cached_property.py", line 73, in __get__
		return obj_dict.setdefault(name, self.func(obj))
	  File "C:\Python\lib\site-packages\exchangelib\account.py", line 169, in contacts
		return self.root.get_default_folder(Contacts)
	  File "C:\Python\lib\site-packages\exchangelib\folders.py", line 965, in get_default_folder
		for f in self._folders_map.values():
	  File "C:\Python\lib\site-packages\exchangelib\folders.py", line 928, in _folders_map
		for f in FolderCollection(account=self.account, folders=distinguished_folders).get_folders():
	  File "C:\Python\lib\site-packages\exchangelib\services.py", line 1053, in call
		shape=shape,
	  File "C:\Python\lib\site-packages\exchangelib\services.py", line 88, in _get_elements
		response = self._get_response_xml(payload=payload)
	  File "C:\Python\lib\site-packages\exchangelib\services.py", line 189, in _get_response_xml
		raise rme
	  File "C:\Python\lib\site-packages\exchangelib\services.py", line 171, in _get_response_xml
		res = self._get_soap_payload(soap_response=soap_response_payload)
	  File "C:\Python\lib\site-packages\exchangelib\services.py", line 227, in _get_soap_payload
		cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
	  File "C:\Python\lib\site-packages\exchangelib\services.py", line 261, in _raise_soap_errors
		raise vars(errors)[code](msg)
	exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.

Build version :

    Build=15.0.847.31, API=Exchange2013_SP1, Fullname=Microsoft Exchange Server 2013 SP1

This method is work :

    account.root.walk() # output : <exchangelib.folders.FolderCollection object at 0x03ADCA90>

But when i append `filter` to it above error occurred.

    KeyError: 'folders'

only `root` folder is works fine and there is nothing in it !

    print(account.root.all())  # QuerySet(q=Q(), folders=[Root (root)])

**Comment by ecederstrand** [comment]
The `KeyError` is misleading and unrelated to the issue. The real problem here is the `ErrorInternalServerError` which is an error message from the server. For some reason, EWS does not like the request.

To debug this further, I would suggest [enabling debug logging](https://github.com/ecederstrand/exchangelib#troubleshooting) and posting the request and response that causes this exception. Maybe that will give additional hints.

**Comment by alirezaimi** [comment]
This is debugging log :
https://pastebin.com/Lf7WtYAW

**Comment by alirezaimi** [comment]
I wrote a webservice in c# and work fine with ews! 
but using python lib that you provide it, this error happened !

**Comment by alirezaimi** [comment]
any ideas ?

**Comment by alirezaimi** [comment]
any ideas whats wrong !?????

**Comment by alirezaimi** [comment]
any ideas whats wrong !?????

**Comment by ecederstrand** [comment]
Sorry, I have no idea what's wrong. The debug info reveals that the `ErrorInternalServerError` is thrown on a request for all distinguished folders. It may be that your server does not like one of these distinguished folders. To find out which one, you could try running this:

```python
from exchangelib import Credentials, Account
from exchangelib.folders import WELLKNOWN_FOLDERS, AdminAuditLogs
from exchangelib.errors import ErrorFolderNotFound, ErrorInvalidOperation, ErrorItemNotFound, ErrorNoPublicFolderReplicaAvailable

c = Credentials( 'john@example.com', 'changeme')
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)
for cls in WELLKNOWN_FOLDERS:
    if cls == AdminAuditLogs or not cls.supports_version(a.version):
        continue
    print(cls.__name__, end=': ')
    try:
        cls.get_distinguished(account=a)
        print('exists')
    except (ErrorFolderNotFound, ErrorInvalidOperation, ErrorItemNotFound, ErrorNoPublicFolderReplicaAvailable):
        print('not found')
```

If it throws an error, the last folder it prints is the culprit.

Finally, `account.root.walk()` and `account.root.all()` return a generator which do not generate any requests to the server until you consume then. `list(account.root.walk())` and `list(account.root.all())` would probably throw the same error that you got with `account.contacts`.

**Comment by ecederstrand** [comment]
But which folder was printed before you got the stack trace? That was the purpose of the `print(cls.__name__, end=': ')` in the code I posted.

**Comment by alirezaimi** [comment]
@ecederstrand 
edit it .
I think ArchiveInbox is that folder !
what can i do now ?

**Comment by ecederstrand** [comment]
According to https://github.com/OfficeDev/ews-managed-api/blob/master/Enumerations/WellKnownFolderName.cs#L182, `ArchiveInbox` is supposed to be available on Exchange2013 SP1. You could check with your Exchange admins if this is indeed an Exchange 2013 SP1 installation, or if we somehow detected the version incorrectly.

The simplest workaround for now is probably to mark the folder as unsupported on your Exchange version. It will then be ignored. Add this at the top of your code:

```python
from exchangelib.folders import ArchiveInbox
from exchangelib.version import EXCHANGE_2016

ArchiveInbox.supported_from = EXCHANGE_2016
```

and re-run the test. Repeat with other any folders exhibiting the same behavior.

**Comment by alirezaimi** [comment]
@ecederstrand 
The version is correct, i check it again .
This is new output : 

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	ArchiveDeletedItems: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	ArchiveMsgFolderRoot: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	ArchiveRecoverableItemsDeletions: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	ArchiveRecoverableItemsPurges: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	ArchiveRecoverableItemsRoot: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	ArchiveRecoverableItemsVersions: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	ArchiveRoot: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	Calendar: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Conflicts: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	Contacts: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	ConversationHistory: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	DeletedItems: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Directory: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	Drafts: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Favorites: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	IMContactList: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Inbox: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Journal: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	JunkEmail: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	LocalFailures: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	MsgFolderRoot: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	MyContacts: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Notes: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Outbox: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	PeopleConnect: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	PublicFoldersRoot: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	QuickContacts: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	RecipientCache: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	RecoverableItemsDeletions: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	RecoverableItemsPurges: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	RecoverableItemsRoot: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	RecoverableItemsVersions: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	Root: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	SearchFolders: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	SentItems: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	ServerFailures: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	SyncIssues: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found
	Tasks: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	ToDoSearch: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	exists
	VoiceMail: 
	Warning (from warnings module):
	  File "C:\Python\lib\site-packages\urllib3\connectionpool.py", line 857
		InsecureRequestWarning)
	InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
	not found

**Comment by ecederstrand** [comment]
Who did you check the version with? You can't just print `account.protocol.version` because we may have an error in the code that detects whether this is Exchang 2013 or Exchange 2013 SP1.

Anyway, the workaround should let you run your original code now:

```python
from exchangelib import Credentials, Account, Configuration
from exchangelib.protocol import NoVerifyHTTPAdapter, BaseProtocol
from exchangelib.folders import ArchiveInbox
from exchangelib.version import EXCHANGE_2016

ArchiveInbox.supported_from = EXCHANGE_2016
BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
credentials = Credentials("YYY@XXX.com", 'PASSWORD')
account = Account(
	primary_smtp_address="Account@XXX.com",
	autodiscover=True, 
	credentials=credentials
)

print(account)
print(account.contacts)
print(account.contacts.all().count())
```

**Comment by alirezaimi** [comment]
@ecederstrand 
Thanks for your support, i work with this workaround for now .

this is output of exchange version : 

	[PS] C:\Windows\system32>Get-ExchangeServer | Format-List Name, Edition, AdminDisplayVersion
	Name                : EXCHANGE-1
	Edition             : Enterprise
	AdminDisplayVersion : Version 15.0 (Build 847.32)

**Comment by ecederstrand** [comment]
Ok, thanks for the extra information! I'm not sure I can commit any changes to this library to fix this for you because, according to the link I posted previously, `ArchiveInbox` is supposed to work on this version of Exchange.

Unless you have any other suggestions, just keep using the workaround, at least for this specific server.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's something we can improve in exchangelib :-)
