### ISSUE TITLE
Message item_id after save_and_send & sent status

### ISSUE THREAD

**Issue by elv1z** [ecederstrand/exchangelib#434]
Is it possible to get item_id or message_id after save and send? 
Message object attributes returns None. 

```
	m = exchangelib.Message(
		account=account,
		folder=account.sent,
		subject=subject,
		body=body,
		to_recipients=recipients,
	)
	m.send_and_save()
	
	print ('Message id ' , m.message_id) # returns None
	print ('Item id ' , m.item_id) # returns None
```

And how to get message state? Maybe there is an attributes to show information about message sent to recipient without error. 

Thanks in advance.

**Comment by ecederstrand** [comment]
In send_and_save mode,EWS doesn't return the ID and changekey of the item it saves, unfortunately. You'll have to query the folder for something that is unique to the message you sent.

Regarding the state of a sent message, I don't think EWS supports that.
