### ISSUE TITLE
Find if an email is the first email of a conversation

### ISSUE THREAD

**Issue by Nihhaar** [ecederstrand/exchangelib#435]
Hi, I am using exhcangelib to fetch emails, I am able to extract conversation_id from emails and group them. I want to find if an email is the start of a conversation or not. Obviously I can order by datetime, but the emails I have are not complete (some emails are only part of a conversation). So I want to do either on of the following:

1) Get "complete" conversations from my mailbox.
2) Somehow figureout that a mail is start of a conversation. From the [docs](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/ff406135%28v%3dexchg.140%29), 
```
Conversations are based on the first message’s Message-ID header. All replies and related messages will relate to the original message’s Message-ID header by their References and In-Reply-To headers.
```
But I dont know how to check any of these. Any help is greatly appreciated, thanks.

**Comment by ecederstrand** [comment]
I think the `headers` attribute of a message contains the headers you need. A message also has the `message_id`, `references` and `in_reply_to` fields that you may find useful.

**Comment by Nihhaar** [comment]
Thank you.
`item.in_reply_to == None` seems to work for detecting first email of a conversation. Will re-open if I have any issue.
