### ISSUE TITLE
Attachments in original format

### ISSUE THREAD

**Issue by pyro57** [ecederstrand/exchangelib#441]
I'm using this to parse through a mailbox folder full of potential phishing emails.  I can see where it says I can get the attachments in Binary format, but is it possible to get them in the original format?  Specifically what I want to do is grab the attachment and feed it to my sandbox (cuckoo sandbox) to run and analyze for me.  

I apologize if this is already asked/stated in the documentation I did some light searching but couldn't find anything on it.

Thank you!

**Comment by ecederstrand** [comment]
I apologize if I misunderstand your question, but binary format *is* the original format. When an email client attaches a file to an email, it is attached to the email content as a chunk of binary data.

If you need access to the raw MIME content of the email, there's the `mime_content` attribute for that.

**Comment by ecederstrand** [comment]
Feel free to reopen if this did not answer your question.
