### ISSUE TITLE
public folder access

### ISSUE THREAD

**Issue by illyax** [ecederstrand/exchangelib#444]
Hey, is it possible to get contacts from public folder through exchangelib? 
I am able to get personal contacts but nothing from public folder.

**Comment by ecederstrand** [comment]
I'm not very familiar with how contacts work in Exchange. You can access the GAL if you have see it in your `account.root.tree()` listing, if that's what you meant.

**Comment by ecederstrand** [comment]
Closing as duplicate of #396
