### ISSUE TITLE
Display_to max length exceeded 

### ISSUE THREAD

**Issue by harounasow** [ecederstrand/exchangelib#445]
Hello,
I am having an issue when attaching mail with len(subject_to) > 255, can you please take a look. Thanks.

```python
~/anaconda3/lib/python3.6/site-packages/exchangelib/fields.py in clean(self, value, version)
    645             else:
    646                 if len(value) > self.max_length:
--> 647                     raise ValueError("'%s' value '%s' exceeds length %s" % (self.name, value, self.max_length))
    648         return value
    649 
```

I would also like to contribute to your beautiful work, how can i help?

**Comment by harounasow** [comment]
Sorry i meant 'display_to'. Ok i'll try to handle it with a try/ except in my code.
Thanks!

**Comment by ecederstrand** [comment]
You could also just test the length of your input first (`if len(my_display_to_value) > 255`) and either truncate the value (`my_display_to_value  = my_display_to_value[:255]`) or abort, depending on what you want.
