### ISSUE TITLE
Accessing a shared contacts folder

### ISSUE THREAD

**Issue by theplaceboeffect** [ecederstrand/exchangelib#446]
Hi,

I have access to a shared contacts folder on exchange but I am unable to access it. account.root.glob() isn't returning it either. Is there a way to access these shared of folders contacts or otherwise?

Thanks.

--mwt

**Comment by ecederstrand** [comment]
I believe the correct solution is to create an `Account` using the email address of the shared account containing the contacts folder and access the folder from that account object.

You may also find additional hints in similar issues in the issue tracker.

**Comment by ecederstrand** [comment]
Hi @theplaceboeffect Does ny suggestion work for you? If so, I'll see if I can improve the documentation.

**Comment by theplaceboeffect** [comment]
Hi,

Yes, that is what I ended up doing but I really didn't want to do that to
keep my accounts/security separate. Nevertheless, thanks for developing the
library - it's really fantastic. I'm writing a two-way sync now so
hopefully your write API works well!

--mwt

**Comment by ecederstrand** [comment]
Thanks for the kind words! I developed the library exactly for syncing purposes, so that part is very well tested over the years in production, as long as you don't need to use the push/pull services that are only partly implemented in https://github.com/ecederstrand/exchangelib/pull/355
