### ISSUE TITLE
Meeting Room Calendar accepts same timing

### ISSUE THREAD

**Issue by r7rajkumar** [ecederstrand/exchangelib#447]
Hi ,

If i run this code multiple times with same timing (11am to 12pm)every time its create new item i am not getting decline message. but when i do the normal booking via outlook calendar if the meeting room is not available then i am getting decline message from outlook calendar. 
 

    config = Configuration(server='Servername', credentials=creds)

    account = Account(primary_smtp_address="Room1-CCO-XXXX.Com",config = config,autodiscover=False,access_type=DELEGATE)
  

    tz = EWSTimeZone.timezone('Asia/Singapore')
 
    tz = EWSTimeZone.localzone()
   
    calendar_item = CalendarItem(
       account=account,
        folder=account.calendar,
        organizer='r7rajkumar@xxxx.com',
        start=tz.localize(EWSDateTime(2018, 7, 28, 11, 0)),
        end=tz.localize(EWSDateTime(2018, 7, 28, 12, 0)),
        subject="Meeting Python Request",

        location="valby",
        body=" meeting ",
        required_attendees=['r7rajkumar@xxxx.com', 'dts@xxxxx.com']
    )
    calendar_item.save(send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY)
![sample](https://user-images.githubusercontent.com/27937636/43057564-a86bba20-8e75-11e8-8654-6c1b5a5b487a.PNG)

**Comment by ecederstrand** [comment]
That's correct. Nothing in EWS prevents you from double-booking a room.

If you want to get a warning about overlapping meetings, you will have to implement it yourself.

**Comment by r7rajkumar** [comment]
OK .Thanks lot for your suggestion.
