### ISSUE TITLE
Searching for a meeting with specific UID

### ISSUE THREAD

**Issue by earlchew** [ecederstrand/exchangelib#453]
I'm looking for advice as to how to implement this query using exchangelib:

http://www.infinitec.de/post/2009/04/13/Searching-a-meeting-with-a-specific-UID-using-Exchange-Web-Services-2007.aspx

**Comment by ecederstrand** [comment]
Wow, great work!

I'm reopening because I think this could be added as a utility method somewhere in exchangelib, if you grant me permission to do so.

**Comment by earlchew** [comment]
@ecederstrand I grant you permission to use any part of the above fragment.

You will probably want to add a similar one for `OutlookId` as described in https://msdn.microsoft.com/en-us/library/hh338153(v=exchg.80).aspx

And while I have your attention, my thanks for supporting such a well crafted package.

**Comment by ecederstrand** [comment]
I needed some adaptions to make this work on Python3. Just to make sure I got it right, can you please post the correct result of `Uid('261cbc18-1f65-5a0a-bd11-23b1e224cc2f')`? I got:

```python
print(Uid('261cbc18-1f65-5a0a-bd11-23b1e224cc2f'))
'BAAAAIIA4AB0xbcQGoLgCAAAAAAAAAAAAAAAAAAAAAAAAAAAMQAAAHZDYWwtVWlkAQAAADI2MWNiYzE4LTFmNjUtNWEwYS1iZDExLTIzYjFlMjI0Y2MyZgA='
```

**Comment by ecederstrand** [comment]
Never mind, I tested your original code on Python2.

I committed your code, slightly altered for python3 and changed to a `bytes` subclass. Here's a full example:

```python
from exchangelib import CalendarItem, ExtendedProperty, UID
class GOI(ExtendedProperty):
    property_set_id = '6ED8DA90-450B-101B-98DA-00AA003F1305'
    property_name = 'PidLidGlobalObjectId'
    property_type = 'Binary'

CalendarItem.register('PidLidGlobalObjectId', GOI)
account.calendar.filter(global_object_id=GOI(UID('261cbc18-1f65-5a0a-bd11-23b1e224cc2f')))
```

Wrapping in `GOI` takes care of base64-encoding the value in the filter, so I removed that from the `UID` implementation.

Can you test if this works for you?

**Comment by earlchew** [comment]
@ecederstrand I tested the following, and it works as I expect, so I conclude that `exchangelib.properties.UID` is correct:

```
class GlobalObjectId(exchangelib.ExtendedProperty):
    # https://github.com/ecederstrand/exchangelib/issues/78
    distinguished_property_set_id = 'Meeting'
    property_id = 3
    property_type = 'Binary'

for item in folder.filter(
        exchangelib.Q(global_object_id=GlobalObjectId(exchangelib.properties.UID(
            'd84b539e-38ec-54d0-b1e7-de306f1cbfd2')))):
    print item
```

If I substitute the following, the filter finds nothing:

```
class GlobalObjectId(ExtendedProperty):
    property_set_id = '6ED8DA90-450B-101B-98DA-00AA003F1305'
    property_name = 'PidLidGlobalObjectId'
    property_type = 'Binary'
```

A search for both turns up https://social.msdn.microsoft.com/Forums/office/en-US/b71344ff-1581-4fc8-adda-681afe070255/getting-named-properties-via-ews?forum=exchangesvrdevelopment

> If you see it okay the one reason your Query may fail is that you are specifying the PropertySetId instead of using the DistinguishedPropertySetId eg you should be using
>
> <t:ExtendedFieldURI DistinguishedPropertySetId="Meeting" PropertyId=
"3" PropertyType="Binary" />

**Comment by ecederstrand** [comment]
Thanks for the update! I fixed the documentation for UID with your working example.

**Comment by DS4711** [comment]
The example documented in the class UID did for filtering via global_object_id did not work for me without providing a bytes() conversion.
    """Helper class to encode Calendar UIDs. See issue #453. Example:
    class GlobalObjectId(ExtendedProperty):
        distinguished_property_set_id = 'Meeting'
        property_id = 3
        property_type = 'Binary'
    CalendarItem.register('global_object_id', GlobalObjectId)
    account.calendar.filter(global_object_id= **bytes(** UID('261cbc18-1f65-5a0a-bd11-23b1e224cc2f')) **)**
    """

It took me some time to figure this out since, so I thought I leave a comment here.
