### ISSUE TITLE
Check for conflicting calendar items?

### ISSUE THREAD

**Issue by clemenskroell** [ecederstrand/exchangelib#454]
I didn't found, how I can check if there are conflicting calendar items, when adding a new event. Any advice how I can achieve this before saving the event to the calendar?

Thanks!

**Comment by ecederstrand** [comment]
The easiest way is probably the [calendar.view()](https://github.com/ecederstrand/exchangelib#searching) method:

```python
# Check for events today between 8:00 and 10:00
has_conflicts = a.calendar.view(
    start=a.default_timezone.localize(EWSDateTime(2018, 8, 7, 8)),
    end=a.default_timezone.localize(EWSDateTime(2018, 8, 7, 10)),
    max_items=1
).exists()
```

**Comment by clemenskroell** [comment]
Very cool! Thank you…
