### ISSUE TITLE
exchangelib 0365 authentication issue - Synapse

### ISSUE THREAD

**Issue by cameronkinsel** [ecederstrand/exchangelib#456]
Hello! Hope all is well. 

I'm attempting to utilize software (called Synapse, part of TheHive Project), which uses exchangelib to authenticate into EWS.  Synapse can authenticate to a mailbox, and interface with TheHive based on the contents of the emails.

I've worked with the Synapse\TheHive dev to do some basic troubleshooting, and he suggested I reach out to this team to look into the exchangelib library for further troubleshooting.

-----------------------------------------

I'll start with the Synapse.conf file, which sets variables that are used with exchangelib:

```
server:outlook.office365.com

#According to exchangelib doc:

#"username is usually in WINDOMAIN\username format

#some servers also accept usernames in PrimarySMTPAddress

#('myusername@example.com') format (Office365 requires it)

username:Account@company.com

password:[redacted]

smtp_address:Account@company.com

folder_name:TheHive
```

Note the "username:" section, and how it matches the 0365 format per the comment

Next, I trigger Synapse, and ultimately exchangelib, to attempt to log into the mailbox specified in Synapse.conf

Looking at the logs, I get the following output:

>  2018-08-03 12:03:35,788 :: INFO :: workflows.common.common.getConf starts
> 		2018-08-03 12:03:38,234 :: INFO :: workflows.Ews2Case.connectEws starts
> 		2018-08-03 12:03:38,234 :: INFO :: common.common.getConf starts
> 		2018-08-03 12:03:38,234 :: INFO :: objects.EwsConnector. getAccount starts
> 		2018-08-03 12:03:38,969 :: ERROR :: Failed to get account
> 		Traceback (most recent call last):
> 		  File "/home/flast/Synapse/workflows/objects/EwsConnector.py", line 28, in getAccount
> 			auth_type=NTLM)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
> 			version=version
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
> 			protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 230, in __init__
> 			self.version = Version.guess(self)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 206, in guess
> 			return cls._guess_version_from_service(protocol=protocol, hint=api_version)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 239, in _guess_version_from_service
> 			list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 1557, in call
> 			contact_data_shape=contact_data_shape,
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 88, in _get_elements
> 			response = self._get_response_xml(payload=payload)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 164, in _get_response_xml
> 			allow_redirects=False)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 547, in post_ratelimited
> 			_raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 601, in _raise_response_errors
> 			raise UnauthorizedError('Wrong username or password for %s' % r.url)
> 		exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx
> 		2018-08-03 12:03:38,971 :: ERROR :: Failed to create case from email
> 		Traceback (most recent call last):
> 		  File "/home/flast/Synapse/workflows/Ews2Case.py", line 25, in connectEws
> 			ewsConnector = EwsConnector(cfg)
> 		  File "/home/flast/Synapse/workflows/objects/EwsConnector.py", line 13, in __init__
> 			self.account = self.getAccount()
> 		  File "/home/flast/Synapse/workflows/objects/EwsConnector.py", line 28, in getAccount
> 			auth_type=NTLM)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
> 			version=version
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
> 			protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 230, in __init__
> 			self.version = Version.guess(self)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 206, in guess
> 			return cls._guess_version_from_service(protocol=protocol, hint=api_version)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 239, in _guess_version_from_service
> 			list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 1557, in call
> 			contact_data_shape=contact_data_shape,
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 88, in _get_elements
> 			response = self._get_response_xml(payload=payload)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 164, in _get_response_xml
> 			allow_redirects=False)
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 547, in post_ratelimited
> 			_raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
> 		  File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 601, in _raise_response_errors
> 			raise UnauthorizedError('Wrong username or password for %s' % r.url)
> 		exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx

I can see, that it is complaining about the credentials being passed to EWS.  I have confirmed that they are indeed keyed in correctly in synapse.conf.  
Additionally, if I manually browse to the URL provided in the logs. It prompts me for, and accepts the credentials for my outlook account, and denies access if I key it incorrectly.

This suggests to me that the credentials provided to Synapse aren't even being tested against EWS, or my company's environment.
More evidence to this point, is that attempting this connection 10 times in less than 15 seconds, does NOT result in the account being disabled.
Additionally, I checked internal network traffic, and verified that communication wasn't being blocked.  I saw a seemingly complete TCP conversation between my machine and exchange servers, and the only traffic that was blocked were ping attempts I initiated against the exchange servers.

Looking at exchangelib, I see the following snippet is what is used to authenticate:

```python
def getAccount(self):
        self.logger.info('%s. getAccount starts', __name__)

        try:
            username = self.cfg.get('EWS', 'username')
            password = self.cfg.get('EWS', 'password')
            credentials = Credentials(username=username, password=password)
            
            ews_server = self.cfg.get('EWS', 'server')
            smtp_address = self.cfg.get('EWS', 'smtp_address')
            
            config = Configuration(server=ews_server,
                credentials=credentials,
                auth_type=NTLM)


            account = Account(primary_smtp_address=smtp_address,
                config=config, autodiscover=False, access_type=DELEGATE)

            return account
        except Exception as e:
            self.logger.error('Failed to get account', exc_info=True)
            raise
```

I can see that Synapse connections are being caught in the exception block.  Looking at the code, I see no obvious reason why the credentials are failing to be tested.

Looking at Synapse, or more specifically Ews2Case.py, here is a snippet of code related to calling exchangelib (below).  I'm fairly new to Python, but believe I've chosen the first portion of code which calls exchangelib, let me know if you want a different section of code.  

```python
from common.common import getConf
from objects.EwsConnector import EwsConnector
from objects.TheHiveConnector import TheHiveConnector
from objects.TempAttachment import TempAttachment

def connectEws():
    logger = logging.getLogger(__name__)
    logger.info('%s.connectEws starts', __name__)

    report = dict()
    report['success'] = bool()

    try:
        cfg = getConf()

        ewsConnector = EwsConnector(cfg)
        folder_name = cfg.get('EWS', 'folder_name')
        unread = ewsConnector.scan(folder_name)

        theHiveConnector = TheHiveConnector(cfg)

        for msg in unread:
            #type(msg)
            #<class 'exchangelib.folders.Message'>
            conversationId = msg.conversation_id.id

            #searching if case has already been created from the email
            #conversation
            esCaseId = theHiveConnector.searchCaseByDescription(conversationId)

```

Please let me know if there is something that I'm doing wrong, or if you've identified an issue that I do not see.  Is the implementation of exchangelib shown above being implemented correctly? 
Any insight about exchangelib here would be greatly appreciated.

**Comment by ecederstrand** [comment]
I see that the connection code in `getAccount()` hardcodes NTLM auth, but it's possible the server uses another authentication method.

You could try to connect to your server using plain exchangelib, as described in the README, without hardcoding the authentication method. If that succeeds, than the problem is in Synapse instead.

**Comment by cameronkinsel** [comment]
Thank you for the fast reply Erik!  I will follow the instructions in the Readme and test the connection directly.  I'll report back when I have more information.

**Comment by cameronkinsel** [comment]
Alright, I've referenced the Readme.md, and have tried the following (with values obfuscated):

```
from exchangelib import Credentials, Account

credentials = Credentials('first.last@company.com', 'password')
account = Account('first.last@company.com', credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)
```
Which gave the following:

> Traceback (most recent call last):
>   File "test.py", line 15, in <module>
>     account = Account('first.last@company.com', credentials=credentials, autodiscover=True)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/account.py", line 82, in __init__
>     credentials=credentials)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/autodiscover.py", line 209, in discover
>     return _try_autodiscover(hostname=domain, credentials=credentials, email=email)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/autodiscover.py", line 257, in _try_autodiscover
>     return _try_autodiscover(e.server, credentials, email)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/autodiscover.py", line 275, in _try_autodiscover
>     raise_from(AutoDiscoverFailed('All steps in the autodiscover protocol failed'), None)
>   File "/home/flast/.local/lib/python2.7/site-packages/future/utils/__init__.py", line 454, in raise_from
>     raise e
> exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

Weirdly though, using testconnectivity.microsoft.com to test, O365 autodiscover succeeded. 
Anyway, I wanted to try connecting by specifying the server instead, since that is what Synapse requires.
I tried the following:

```
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, GSSAPI, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version, FolderCollection

credentials = Credentials('first.last@company.com', 'password')
config = Configuration(server='outlook.office365.com', credentials=credentials)
account = Account(primary_smtp_address='first.last@company.com', config=config, autodiscover=False)


for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)
```
Gave the following:
> Traceback (most recent call last):
>   File "test.py", line 6, in <module>
>     account = Account(primary_smtp_address='first.last@company.com', config=config, autodiscover=False)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/account.py", line 100, in __init__
>     self.root = Root.get_distinguished(account=self)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/folders.py", line 811, in get_distinguished
>     account=account, folders=[cls(account=account, name=cls.DISTINGUISHED_FOLDER_ID)]).get_folders()
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/services.py", line 1053, in call
>     shape=shape,
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/services.py", line 88, in _get_elements
>     response = self._get_response_xml(payload=payload)
>   File "/home/flast/.local/lib/python2.7/site-packages/exchangelib/services.py", line 189, in _get_response_xml
>     raise rme
> exchangelib.errors.ErrorImpersonateUserDenied: The account does not have permission to impersonate the requested user.
> 

So, this result confuses me.  I'm not very familiar with O365, and don't have access to make any changes to our implementation within my company, but I don't understand why it is trying to impersonate any account?

Erik, can you see if my python above is correct? Or did I forget to specify something in the config?

**Comment by ecederstrand** [comment]
Yes, setting `access_type` to `DELEGATE` explicitly is needed when you use the `config` argument. It's a bit inconsistent, because it's the default if you don't, which is probably why it's not set explicitly in the Synapse code. Delegate is the proper access type if you're accessing your own account.

Disabling autodiscover (or disabling TLS verification) is needed for O365 due to a bug in our autodiscover implementation that's not yet solved, but tracked in #337.

**Comment by cameronkinsel** [comment]
Alright, I'll work with the Synapse Dev to add the ability to set `access_type`, and also be able to specify `auth_type`

When I do not specify `auth_type`, do you know what it is defaulting to use?  I assume it is something the Synapse dev will need to know if Synapse users need to specify it in their configs.

**Comment by cameronkinsel** [comment]
I've opened [Issue 1](https://github.com/TheHive-Project/Synapse/issues/1) with the Synapse Dev.  Thanks for your fast support Erik!

The issue seems to be in the Synapse code side, as writing a basic connect script utilizing exchangelib revealed a few required settings that Synapse needs to specify for o365 accounts.

**Comment by Nirmalnk05** [comment]
### Connect to mailbox 
try:
    my_account = Account(
                primary_smtp_address='msbehsva@xxx.com', 
                credentials=credentials,
                autodiscover=True, access_type=DELEGATE
                )
    if(my_account):
        print(my_account)
except:
    print("not connected")
    pass

Getting below error : 
We have already tried this URL: https://autodiscover.micron.com/Autodiscover/Autodiscover.xml

Tried all possibilities, nothing works out.
