### ISSUE TITLE
RateLimitError does not contain status code

### ISSUE THREAD

**Issue by BenJoParadise** [ecederstrand/exchangelib#460]
https://github.com/ecederstrand/exchangelib/blob/d9e7e12b6bf4aab72f36587a90eb06ea5eaea322/exchangelib/util.py#L580

We wish to implement our own logic for dealing with the status codes that cause RateLimitErrors.
However, we wish to have different logic for each status code.

Currently, when a RateLimitError is thrown, there is no way to know which status code triggered it.
Can you please add the status code to the exception?

**Comment by ecederstrand** [comment]
That seems like a useful addition. Thanks for the suggestion!
