### ISSUE TITLE
requests timeout hardcoded?

### ISSUE THREAD

**Issue by cristianocca** [ecederstrand/exchangelib#461]
Looking at https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/protocol.py#L49 it seems that the requests timeout is hardcoded.

Is it possible to use a different value? This is helpful when fetching/querying a large amount of emails and the server is slow, so far it seems impossible to query more than 10-20 emails without a timeout error.

**Comment by ecederstrand** [comment]
You can just change the value in your own code:

```python
from exchangelib.protocol import BaseProtocol
BasePtotocol.TIMEOUT = 999
```

However, if you can't get more than 10 emails within 120 minutes, I would suggest getting fewer emails at a time, or only get the fields you need on each email (the email body and attachments can be huge):

```python
# Setting page size
qs = account.inbox.filter(subject='mumble')
qs.page_size = 2
for email in qs:
    print(email)

# Limiting number of fields
for email in account.inbox.filter(subject='mumble').only('subject', 'datetime_received'):
    print(email)
```

**Comment by ecederstrand** [comment]
It’s not documented because it should be a last-resort solution. I think it’s better to limit the requested workload than to put a server in a situation where it can’t send a single byte over the wire for 120 seconds :-)

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional issues  :-)
