### ISSUE TITLE
Copying and Sending Drafts

### ISSUE THREAD

**Issue by dem0ndxxvii** [ecederstrand/exchangelib#463]
Hello, I am attempting to send an item in my drafts to multiple people. However, each email has to be slightly different. My idea to accomplish this was to create a draft of the email in the Outlook client, then create a new message using exchangelib, edit the body, send, and repeat in a loop for each sender. This is the code I am currently using:

```python
def send_draft(draft,address,link,authAccount): 

    newb = re.sub('REPLACETHISLINK', link, draft.body)

    m = Message(
    account=authAccount,
    subject=draft.subject,
    body=HTMLBody(newb),
    to_recipients=[
        Mailbox(email_address=address),
    ]

    m.send()
    print("Email send to address.")`
```

The problem that I am having, is that my draft includes inline images and they are breaking. The images are not being displayed, and the error says "The linked image cannot be displayed. The file may have been moved, renamed, or deleted. Verify that the link points to the correct file and location."

The second thing that I tried is to place a piece of code to replace, in place of the images "<REPLACETHIS>. The code was successfully replaced with: 

`<img width="654" height="205" src="cid:logo.png">`

and attached the image as an attachment:

```python
with open(logo, 'rb') as fp:
        logoImage = FileAttachment(
            name="logo.png",
            content=fp.read(),
            is_inline=True,
            content_type='GIF/Image',
            content_id="logo.png"
        )
m.attach(logoImage)
```

 Unfortunately, this yielded the same results. At this point, I am all out of ideas and was hoping that somebody here may have a better solution or could point out something that I am doing incorrectly. Any assistance would be greatly appreciated.

**Comment by ecederstrand** [comment]
It seems you haven't actually attached the file to the message. See https://github.com/ecederstrand/exchangelib#attachments for an example that has been verified to work in previous issues on the topic.

**Comment by dem0ndxxvii** [comment]
I appreciate your quick response, wasn't sure how long it was going to take to hear from anybody. I'm assuming the following is what you are referring to:

`logo_filename = 'logo.png'
 with open(logo_filename, 'rb') as f:
    my_logo = FileAttachment(
         name=logo_filename, 
         content=f.read(), 
         is_inline=True, 
         content_id=logo_filename)
    message.attach(my_logo)

message.body = HTMLBody('<html><body>Hello logo: <img src="cid:%s"></body></html>' % logo_filename)`

This is actually what I based my code on. Call me crazy, but I cannot for the life of me find the difference.
The second block of my code was added right before `m.send()`, my apologies for the confusion.

**Comment by ecederstrand** [comment]
Hmm. My next suggestion would be to create a draft email with working inline attachments using an official client, e.g. Outlook or OWA, and inspect that using exchangelib to determine how the working draft is constructed.

**Comment by ecederstrand** [comment]
Hi @dem0ndxxvii Did you get this to work? If so, I would like to know if there is anything we can do to improve the documentation.

**Comment by dem0ndxxvii** [comment]
Unfortunately I have been unable to get this working, and have curbed this angle for now. I have backed up to using regular mail relay to accomplish this task. I appreciate the assistance that you have provided.

**Comment by ecederstrand** [comment]
Ok. Thanks for getting back. I’m closing the issue, but feel free to reopen if you have additional information.
