### ISSUE TITLE
Changing calendar item organized by other entity fails

### ISSUE THREAD

**Issue by frennkie** [ecederstrand/exchangelib#464]
I guess my changes in #369 did not consider this.

I want to turn off the reminders on all meetings that are in the calendar of a special mailbox.
If the meeting was created by this mailbox the following is working fine:

``` 
    calendar_items = account.calendar.all().order_by('-datetime_received')[:15]

    for item in calendar_items:
        if item.reminder_is_set:
            click.secho("DEBUG: %s - Reminder is on!" % item.subject)
            item.reminder_is_set = False
            item.save()
```

But if the organizer of the meeting is another account I get errors. The first error was that `calendar:IsResponseRequested` could not be set.. so I tried to narrow it down by setting `is_read_only` to True.. then the same with  `calendar:RequiredAttendees` ,`calendar:OptionalAttendees` , `calendar:Resources` and `calendar:Recurrence`. Finally it complained about `calendar:StartTimeZone` which I can not set to read only.

Any ideas how to properly do/fix this?

**Comment by ecederstrand** [comment]
Some fields are apparently read-only when you are not the organiser. `save()`has an optional `update_fields` argument that you can use to specify which fields to update. Does this work for you?

```python
if item.reminder_is_set:
    item.reminder_is_set = False
    item.save(update_fields=['reminder_is_set'])
```

**Comment by frennkie** [comment]
Didn't think of this.. Work great.. Thanks. 
--
