### ISSUE TITLE
Add email as attachment in memory

### ISSUE THREAD

**Issue by hernanfila** [ecederstrand/exchangelib#466]
Hi, first of all thank you for the space, you are very helpful with your answers.
I am trying to follow #attachment section to attach an email that I get from a folder: 
Then I want to attach the first item, that it is an email, to a new email:

```python
for item in my_folder.all():
    # Create a new email with the email item as an attachment`
    newEmailItem= Message(...)`
    newEmailItem.attach(item?)  # How can I attach the email item (msg) without saving it as a file?
```

Or can it be done easily by saving it as I file?`  
Could you advise me if I should save it as a file and then attach it?
Thank you

**Comment by ecederstrand** [comment]
To do this, you must wrap the message in an `ItemAccount` instance before attaching. See https://github.com/ecederstrand/exchangelib#attachments

**Comment by hernanfila** [comment]
Yes, finally it was `ItemAttachment`. Thank you

Another issue I have is that if the account has a lot of folder and subfolders ( and emails), the error I get is: Unexpected next offset: 9500 -> 9502. It doesn't happen if we use an account with not so many emails on it. So I guess the issue is the load of the account. 

Is there any recommendation you have to parse a large set of emails?

Thank you.
