### ISSUE TITLE
CalendarItem Field is_response_requested not working?

### ISSUE THREAD

**Issue by theKraid** [ecederstrand/exchangelib#467]
I'm trying to send out a calendar item that does not require responses

```python
termin = CalendarItem(
  account=account,
  folder=account.calendar,
  start=tz.localize(EWSDateTime(2018, 9, 1, 1, 1),
  end=tz.localize(EWSDateTime(2018, 9, 2, 1, 1),
  subject='test meeting',
  body='test meeting',
  required_attendees=calendar_recipients,
  legacy_free_busy_status='Free',
  is_response_requested=False,
)
```
Despite the parameter is_response_requested set to False, the event requires the recipients to select a response. Is this feature not working (yet) ?

**Comment by ecederstrand** [comment]
There are tests covering that we can set and change the field, but I'm not sure what that field actually does in EWS.

You may want to use `termin.send(send_meeting_invitations=SEND_TO_NONE)` instead?

**Comment by ecederstrand** [comment]
@theKraid Did the suggested solution work for you?

**Comment by theKraid** [comment]
Sorry, I did not get to try it yet, I will get back to you about this asap! Thank you so much for the help!

**Comment by theKraid** [comment]
My bad, it actually DID work the way I initially tried. Sorry. Thanks for helping out!
