### ISSUE TITLE
i can not update meeting Item。

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [ecederstrand/exchangelib#470]
i want to update meeting item .
i have item_id.
how can i do this?
![image](https://user-images.githubusercontent.com/24671601/45141995-f6bedd00-b1e9-11e8-953b-86a5c7de3d2c.png)
![image](https://user-images.githubusercontent.com/24671601/45142068-2241c780-b1ea-11e8-9e34-d842ee05d988.png)
https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-update-appointments-and-meetings-by-using-ews-in-exchange

**Comment by ecederstrand** [comment]
There are multiple ways to do this. The easiest way is probably to fetch the full item first, make changes and then call save():

full_item = account.inbox.get(item_id=item_id)
full_item.subject = 'New subject'
full_item.save()

**Comment by SamGenTLEManKaka** [comment]
thanks for your answer !
i copy your code 
but i get an error
It means that the ID is not in the correct format.
![image](https://user-images.githubusercontent.com/24671601/45142580-80bb7580-b1eb-11e8-8e21-00db44a39022.png)

**Comment by gkowalski** [comment]
This really needs to be add to the doc , could not find a way to get and re-instantiate a specific calendar event.

**Comment by gkowalski** [comment]
`calendar_item = CalendarItem(
    account=account,
    folder=account.calendar,
    start=  tz.localize(EWSDateTime.now()),
    end=  tz.localize(EWSDateTime.now()),
    subject="Bring your A Game ",
    body=htmlBody,
    required_attendees=['me@mcw.edu' ]

)
# This works , created !
calvalue = calendar_item.save(send_meeting_invitations=SEND_ONLY_TO_ALL)
print ( calvalue)
item_id = calvalue.item_id

# This does seemingly nothing in the same script 
full_item = account.calendar.get(item_id=item_id)
full_item.subject ="Updated !"
full_item.save()


`
