### ISSUE TITLE
message read receipt

### ISSUE THREAD

**Issue by RezaFFM** [ecederstrand/exchangelib#473]
Good Morning! I used to work with win32 python to read messages from mailbox. There you could check whether a message is a report or email (class 46 or 43). 

Is it possible to do the same with your package? I want to find out, whether a message is a read receipt or not. Thank you!

**Comment by ecederstrand** [comment]
I have no idea whether that information is available via EWS. I haven't seen any numeric email class fields in the documentation, but it's possible it's available as extended properties. Please update this issue if you find out, so we can update the documentation. Thanks!

**Comment by ecederstrand** [comment]
According to https://stackoverflow.com/questions/28352518/how-to-get-email-type-using-ews, it's possible you can distinguish message types using the `item_class` field. Reports supposedly have a value of `Report.[something]`. See https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/mapi-report-messages

**Comment by RezaFFM** [comment]
Hi, I tried your suggestions, but it always returns None. Might be related to out Server version (2013, S1).

**Comment by ecederstrand** [comment]
I don't know if this is server-specific. I just tried my own inbox which is hosted on Exchange Server 2013 SP1:

```python
c = Credentials('username', 'password')
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)

for m in a.inbox.all().only('item_class'):
    print(m.item_class)
```

which prints a combination of:

```
REPORT.IPM.Note.IPNRN
IPM.Note
REPORT.IPM.Note.IPNNRN
```

**Comment by RezaFFM** [comment]
Hm I am sorry I dont know. The only practical solution is to Check if the subject starts with „Read“ and then tag accordingly.

**Comment by ecederstrand** [comment]
That's of course an option, if your server does not return any `item_class` values. It's a bit strange, though, because your server version is the exact same as mine.

Just as a last suggestion, check that you are using the latest version of exchangelib (1.11.4 at the time of writing).

**Comment by ecederstrand** [comment]
I'm not sure there's more we can do here. `item_class` is the documented way to do this, and it works on my test account. I have no suggestions how to convince your server to also return the `item_class` values.

Feel free to reopen if you think there's something we can improve in exchangelib.
