### ISSUE TITLE
exchangelib Status code 400

### ISSUE THREAD

**Issue by liushuhuai** [ecederstrand/exchangelib#474]
when i try to login the exchange mailbox with exchangelib(the latest version), the following errors occurred, do you know what causes this error and how to resolve it? thanks very `much.`

```
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 10
Timeout: 120
Session: 7823
Thread: 12344
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x039C2390>
URL: https://ex.exmail.qq.com/EWS/Exchange.asmx
HTTP adapter: <__main__.DESAdapter object at 0x039C2430>
Allow redirects: False
Response time: 0.25
Status code: 400
Request headers: {'Content-Type': 'text/xml; charset=utf-8', 'Accept': '*/*', 'A
ccept-Encoding': 'compress, gzip', 'Content-Length': '1124', 'User-Agent': 'pyth
on-requests/2.18.4', 'Connection': 'Keep-Alive'}
Response headers: {'Content-Type': 'text/html; charset=UTF-8', 'Cache-Control':
'private, max-age=0', 'Connection': 'keep-alive', 'Alternate-Protocol': '443:qui
c', 'Content-Length': '149', 'Server': 'nginx/1.0.5', 'WWW-Authenticate': 'Basic
 realm="qq.com"', 'Date': 'Thu, 13 Sep 2018 01:03:11 GMT', 'Expires': 'Thu, 13 S
ep 2018 01:03:11 GMT'}
Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http:
//schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas
.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/serv
ices/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016" /><t:T
imeZoneContext><t:TimeZoneDefinition Id="China Standard Time" /></t:TimeZoneCont
ext></s:Header><s:Body><m:GetFolder><m:FolderShape><t:BaseShape>IdOnly</t:BaseSh
ape><t:AdditionalProperties><t:FieldURI FieldURI="folder:ChildFolderCount" /><t:
FieldURI FieldURI="folder:EffectiveRights" /><t:FieldURI FieldURI="folder:Folder
Class" /><t:FieldURI FieldURI="folder:DisplayName" /><t:FieldURI FieldURI="folde
r:ParentFolderId" /><t:FieldURI FieldURI="folder:TotalCount" /><t:FieldURI Field
URI="folder:UnreadCount" /></t:AdditionalProperties></m:FolderShape><m:FolderIds
><t:DistinguishedFolderId Id="root"><t:Mailbox><t:EmailAddress>account@domain</t
:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>Mailbox</t:Mailb
oxType></t:Mailbox></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></s:Bod
y></s:Envelope>'
Response data: b'<HTML>\r\n\t<HEAD>\r\n\t<TITLE>400 Bad Request</TITLE>\r\n\t</H
EAD>\r\n\t<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\r\n\t\t<H1>400 Bad Request</H1
>\r\n\t</BODY>\r\n</HTML>\r\n'
```

**Comment by ecederstrand** [comment]
It looks like you're forcing NTLM authentication but your server does not support it. Can you post some minimal code that causes this error?

**Comment by liushuhuai** [comment]
> It looks like you're forcing NTLM authentication but your server does not support it. Can you post some minimal code that causes this error?

my code is something like this. now the code cracks in function Account(), i've tried calling Configuration without a hardcode auth_type, then it will crack in function Configuration() with this error: exchangelib.errors.TransportError: Failed to get auth type from service

i've almost tried every combination of params, seems like only adjusting the params passed to the api has no help to solve it.

CIPHERS = (
    'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:'
    'DH+HIGH:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+HIGH:RSA+3DES:!aNULL:'
    '!eNULL:!MD5'
)

class DESAdapter(HTTPAdapter):
    """
    A TransportAdapter that re-enables 3DES support in Requests.
    """

    def init_poolmanager(self, *args, **kwargs):
        context = create_urllib3_context(ciphers=CIPHERS)
        kwargs['ssl_context'] = context
        return super(DESAdapter, self).init_poolmanager(*args, **kwargs)

    def proxy_manager_for(self, *args, **kwargs):
        context = create_urllib3_context(ciphers=CIPHERS)
        kwargs['ssl_context'] = context
        return super(DESAdapter, self).proxy_manager_for(*args, **kwargs)
        
BaseProtocol.HTTP_ADAPTER_CLS = DESAdapter
#BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter

creds = Credentials(username='account@domain', password='pwd')
print('Credentials ok')

#version = Version(build=Build(15,1,1415,2))
version = Version(build=Build(8,3,517,0))

config = Configuration(         
    server='ex.exmail.qq.com',
    has_ssl=True,
    credentials=creds,
    auth_type = NTLM,
    version = version
)

print('Configuration ok')
account = Account(primary_smtp_address='account@domain', autodiscover=False, access_type=DELEGATE
                  ,config=config
                  )

print('Account ok')

for i, f in enumerate(Folder.FIELDS):
    if f.name == 'unread_count':
        Folder.FIELDS.pop(i)

for i, f in enumerate(CalendarItem.FIELDS):
    if f.name == '_meeting_timezone':
        CalendarItem.FIELDS.pop(i)  
        
for item in account.inbox.all().only('subject', 'body', 'sender', 'datetime_received', 'attachments').order_by('-datetime_received'):
    print(item.subject, item.sender, item.datetime_received)

**Comment by liushuhuai** [comment]
> It looks like you're forcing NTLM authentication but your server does not support it. Can you post some minimal code that causes this error?

whats'more, this is the traceback infor when running the code above, thanks for your comments.

Traceback (most recent call last):
  File "Script\ExchangeMail.py", line 65, in <module>
    ,config=config
  File "PyEnv\lib
\site-packages\exchangelib\account.py", line 100, in __init__
    self.root = Root.get_distinguished(account=self)
  File "PyEnv\lib
\site-packages\exchangelib\folders.py", line 840, in get_distinguished
    folders=[cls(account=account, name=cls.DISTINGUISHED_FOLDER_ID, is_distingui
shed=True)]
  File "PyEnv\lib
\site-packages\exchangelib\services.py", line 1058, in call
    shape=shape,
  File "PyEnv\lib
\site-packages\exchangelib\services.py", line 85, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "PyEnv\lib
\site-packages\exchangelib\services.py", line 154, in _get_response_xml
    allow_redirects=False)
  File "PyEnv\lib
\site-packages\exchangelib\util.py", line 550, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an e
xception
  File "PyEnv\lib
\site-packages\exchangelib\util.py", line 621, in _raise_response_errors
    raise TransportError(str('Unknown failure\n') + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 10
Timeout: 120
Session: 25259
Thread: 9288
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x03BC7DF0>
URL: https://ex.exmail.qq.com/EWS/Exchange.asmx
HTTP adapter: <__main__.DESAdapter object at 0x03BC7E70>
Allow redirects: False
Response time: 0.2180000000007567
Status code: 400

**Comment by ecederstrand** [comment]
The response header `'WWW-Authenticate': 'Basic realm="qq.com"'` from the server means it wants to use Basic auth. So try to use `auth_type=BASIC` instead.

If you are still unable to connect, you will need to debug further. Maybe you have the wrong credentials? You can try accessing https://ex.exmail.qq.com/EWS/Exchange.asmx in a browser, or you can test your connection at https://testconnectivity.microsoft.com/ to see if that gives you any hints. about the problem. 

It's also possible `requests` is unable to talk to the server due to missing local certificates or SSL incompatibilities. A simple `import requests; requests.get('https://ex.exmail.qq.com/EWS/Exchange.asmx ')` may give you additional hints.

**Comment by liushuhuai** [comment]
i tried accessing  https://ex.exmail.qq.com/EWS/Exchange.asmx in a browser and it reports: 503 : HTTP Error 503, 
when using https://testconnectivity.microsoft.com/ to test connection, it reports the same thing as my python code, does it means the url of the mail server is not typical?

**Comment by ecederstrand** [comment]
If the MS connectivity test fails, then it's either wrong server URL or credentials, or an improperly configured server. Have you tried to autodiscover the email address? You can do that from https://testconnectivity.microsoft.com/ It's possible you have the wrong URL to the server.

**Comment by liushuhuai** [comment]
autodiscover failed too, it reports:The Autodiscover service couldn't be contacted successfully by any method.
i guess the server is not improperly configured like you said or it uses some different protocol to access maybe.
thank you for offering your thoughts anyway.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think this is an exchangelib issue after all.
