### ISSUE TITLE
Export email items

### ISSUE THREAD

**Issue by dpajkovic** [ecederstrand/exchangelib#475]
Is it possible to export mail items as individual eml or msg files? I’m sure it’s there somewhere but I just can’t put my hand on it. 

Thanks in advance!

**Comment by ecederstrand** [comment]
I'm not sure there's a global standard for .eml files, but at least some email clients dump the raw MIME content, which is available in exchangelib as `Item.mime_content`.

**Comment by dpajkovic** [comment]
Thank you!

in fact

`file.write(item.mime_content.decode("utf-8"))`

works perfect and produces valid eml file.

**Comment by msheltongit** [comment]
Another way is to create a .eml file.

```
            data = a.export([item])[0]
            with open (outPath2 + '/m' + 
                       str(item.datetime_created)[:10] + '_' +
                       ''.join(e for e in item.subject[:25] if e.isalnum()) +
                       '.eml', 'w') as f:
                f.write(data)
                f.close()
```
