### ISSUE TITLE
Is there any way create a forward and modify it's fields as a message before sending?

### ISSUE THREAD

**Issue by kbrowder** [ecederstrand/exchangelib#476]
In the EWS managed API this is done by using "CreateForward" (https://stackoverflow.com/questions/7732911/forward-email-using-ews-managed-api-keeping-the-headers) to create a message that represents a forward; haven't seen a way to do this without creating a message from scratch.  Specifically i'm looking at adding a reply-to and/or an attachment.

**Comment by ecederstrand** [comment]
The `Message.forward()` implementation is an example of how to create a forward message: https://github.com/ecederstrand/exchangelib/blob/23b71346f4575dcbf9924f0097d20f7f566d363b/exchangelib/items.py#L768

You can't add attachments or reply-to information directly to a `ForwardItem` (see https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/forwarditem), but you can reference the original item which may have attachments and a reply-to field.

**Comment by kbrowder** [comment]
> but you can reference the original item which may have attachments and a reply-to field

Unfortunately forwarding drops the reply-to portion.  Was hoping that the CreateForward mechanism existed (I'm not sure if this is something that's actually in the API or if it's done on the client?)

> And you can add the content of the old message to the content of the new message, as described in the SO question you linked to.

Ya so I guess i could create a new message with the same content and attachements as the old but I was hoping to add a small snippet of text in the same way forwarditem or replyitem does.  I guess I could parse the original items HTML body and add the separation bar and original email metadata myself, but I was hoping to be lazy and let exchange do that for me.

**Comment by ecederstrand** [comment]
Here's a description of how to create forwards in the managed API and in EWS: https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-respond-to-email-messages-by-using-ews-in-exchange

I'm not sure about the reply-to part, but I don't see anything there that exchangelib can't do.

**Comment by kbrowder** [comment]
Wow thanks, so createreply/createforward in C# is actually just a wrapper around createitem.
Basically should do the same thing that BaseReplyItem.send with a ForwardItem does except with a message_disposition of SAVE_ONLY with a folder of account.drafts and then take the res and do an account.fetch on it to get the message.  I've tried this and it works.

Maybe BaseReplyItem should have a save (or maybe better a create since it returns a result?) that more-or-less does this and returns the fetched message?  I may be able to make a PR if it's helpful.

**Comment by ecederstrand** [comment]
That sounds reasonable. PR's are most welcome :-)

**Comment by kbrowder** [comment]
OK I think I implemented this reasonably :)
