### ISSUE TITLE
Serializing Item objects

### ISSUE THREAD

**Issue by hakim-khan** [ecederstrand/exchangelib#477]
Hi, we are iterating over emails with following functionality: 

`for msg in account.inbox:
       ... `

And we figured out each msg can be saved via msg.mime_content. 

Now, we want to write unit tests for our code, and preferrably do those unit tests on "msgs" that were saved to local folder from the exchange server. For example by pickling the msg object. That way we are not relying on an internet connection to run unit tests, we can use local files as a mockup for msgs. 

However, we found no way to restore a msg item from its mime_content such that our unit tests can do regular operations on that msg item. 

Is there a way to do this? account.export() and .upload() don't seem to be for this purpose either. And pickling the msg objects directly gives TypeError: can't pickle _thread.lock objects

**Comment by ecederstrand** [comment]
`export()` and `upload()` are only meant for server-side dump and restore, e.g. when archiving or migrating mailboxes.

`mime_content` is only part of the message content. In short, it's what is sent to a recipient over the SMTP protocol when sending an email. Exchange message items contain more information than that.

If you want to serialize a `Message` object using pickle, then you already found out you got in trouble with the locking primitives.  Luckily, they are only present on the Account object - each Message has a reference back to the account it belongs to. So you could probably do something like this:

```python
# Dumping
for m in a.inbox.all():
    m.account = None
    with open(m.item_id, 'wb'):
        f.write(pickle.dumps(m))

# Restoring
for f in os.listdir():
    with open(f, 'rb'):
        m = pickle.loads(f.read())
    m.account = a
```

And then recreate the Account object by other means.
