### ISSUE TITLE
High memory usage iterating over a large Mailbox

### ISSUE THREAD

**Issue by KarelCoudijzer** [ecederstrand/exchangelib#48]
When iterating over a large mailbox (>5000 mails). Python is starting to get in memory problems. It starts using more than 600 Mb and finally raises a out of memory exception.

```python
    account = exchangelib.Account(...)
    for item in account.inbox.all():
        ...
        
        for attachment in item.attachments:
            ...
```

```
Traceback (most recent call last):
  File "...\exchangelib\exchangelib\util.py", line 157, in to_xml
  File "...\lib\xml\etree\ElementTree.py", line 1335, in XML
xml.etree.ElementTree.ParseError: out of memory: line 1, column 0
```

**Comment by ecederstrand** [comment]
Does Python crash at 600MB usage? How much raw data is the 5000 messages in total? If you have large attachments, 600MB may not be unreasonable.

**Comment by ecederstrand** [comment]
`.all()` is greedy and fetches all items in one go. Attachments load their content when accessing `attachment.content` or `attachment.item`, which will increase your memory usage while iterating.

If you have attributes that you don't care about, you can optimize your memory usage by fetching only the attributes you need:

```
for m in account.inbox.all().only('item_id', 'changekey', 'attachments'):
    ...
```

**Comment by ecederstrand** [comment]
https://github.com/ecederstrand/exchangelib/commit/638995b4aad5e54cf16d2d9a52e9cb8b21a28245 clears some elements after XML parsing, which should ease the memory pressure a bit. Can you try if that helps?

A more optimal solution would be to changing from a greedy XML parser to an iterating parser, but that would be quite painful.

**Comment by ecederstrand** [comment]
Hi @KarelCoudijzer Did you get to the bottom of this? If you are still having problems, I think #52 would make it possible to create a generator that makes `.all()` non-greedy.

**Comment by ecederstrand** [comment]
Closed this with a recommendation to use this optimisation and the latest 1.7.5 release:

```python
for m in account.inbox.all().only('item_id', 'changekey', 'attachments').iterator():
    ...
    for attachment in item.attachments:
        ...
```

If this doesn't help, please provide measurements or other insight into the problem.
