### ISSUE TITLE
Read properties from ArchiveMailbox

### ISSUE THREAD

**Issue by shireen91** [ecederstrand/exchangelib#480]
Hi,

I have few folders in archive mailbox. I want unable to read properties of all messages in the folders. can you please help me here. 
I am using following. Please let me know if I am wrong here
archive = account.archive_msg_folder_root.walk()

**Comment by shireen91** [comment]
![image](https://user-images.githubusercontent.com/28636338/45712200-b05a6e00-bb59-11e8-80f8-d92470d96790.png)

**Comment by shireen91** [comment]
From the above the image as you can children list is empty. can you please let me know how to read messages from folders of archive mailbox.

**Comment by ecederstrand** [comment]
This is a duplicate of #396

**Comment by shireen91** [comment]
Are you working on the fix for this?

**Comment by ecederstrand** [comment]
Yes
