### ISSUE TITLE
Plan to drop support for Python 2.7

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#483]
This is a heads-up that I plan to remove Python 2 support after January 1, 2020. This is in line with the [Python 2.7 EOL schedule](https://devguide.python.org/#status-of-python-branches).

Feel free to pitch in with comments.

Actions:
* [x] Remove `# coding=utf-8` headers
* [x] Remove all uses of packages `future`, `__future__` and `six`
* [x] Replace `class SomeClass(object):` with `class SomeClass:`
* [x] Replace `super(SomeCls, self)` with `super()`
* [x] Replace `u'something'` with just `'something'`
* [x] Remove Python2 from `python_requires` in `setup.py`
* [x] Remove Python2 from `.travis.yml`

**Comment by ecederstrand** [comment]
The more we debat it the less likely you are to migrate your code at all :-)

**Comment by iasniv** [comment]
I actually was not expecting a response! Thanks for the awesome exchangelib and taking the time to respond :) 

What you say is, unfortunately, true, given that we are already using a bunch of Python2-only third party libs. Given that we still have an year to go, let us see how it goes. Thanks again.

**Comment by iasniv** [comment]
Complete agree with you. 
>>You still have the possibility of sticking to the latest version with Python2 support after Jan. 1, 2020.
Actually that was what I was looking for.  I actually misunderstood the topic as "no Python2 version available at all". Thank you.
