### ISSUE TITLE
Implement ConvertId service

### ISSUE THREAD

**Issue by gkowalski** [ecederstrand/exchangelib#484]
Our Company is migrating from our own MS Mail server to Office365 . I have a database full of old item_id's for calendar evemts and after they've converted them to office365 I try to update those Calendar events and get the message : 

ResponseMessageError The EWS Id is in EwsLegacyId format which is not supported by the Exchange version specified by your request. Please use the ConvertId method to convert from EwsLegacyId to EwsId format.

Exception in running update of Events Not Archived :
The EWS Id is in EwsLegacyId format which is not supported by the Exchange version specified by your request. Please use the ConvertId method to convert from EwsLegacyId to EwsId format.

Is there a way to convert my leagcy ID's to the newer ones or am I SOL... 

Thanks

G

**Comment by ecederstrand** [comment]
I don't know if Exchange keeps the item ID when migrating mailboxes. A good guess is that they don't. At least for the export and upload functionality, item IDs are not restored.

Apparently, EWS has a `[ConvertID service](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/convertid-operation)`. It's not supported by exchangelib, but you could try it out and see if it helps in your case.

**Comment by ecederstrand** [comment]
Hi @gkowalski Did you get anywhere with this?
