### ISSUE TITLE
Very slow when fetch 'mime_content' with order_by.

### ISSUE THREAD

**Issue by qholi** [ecederstrand/exchangelib#486]
I have tried fetching emails and write to the .eml files with 'order_by' method. But discovered the CPU and RAM overloading, and very slow. Finally, I query the 'message_id' first and join them to a list, then query 'mime_content' with parameter 'message_id__in' to do the stuff.

Original code:
```
queryset = account.inbox.filter().order_by('datetime_received').values_list('message_id', flat=True).iterator()

for msg in queryset:
    <do stuff here>
```

New code:
```
message_ids = [i for i in account.inbox.filter().order_by('datetime_received').values_list('message_id', flat=True).iterator()]

page_size = 30
qs_start = 0
qs_end = qs_start + page_size
qs_total = len(message_ids)
qs_times, last_qs_end = divmod(qs_total - qs_start, page_size)
_times = qs_times + 1

for i in range(_times):
    m = message_ids[qs_start:qs_end]
    queryset = account.inbox.filter(message_id__in=m).only('mime_content', 'subject', 'message_id', 'datetime_received', 'datetime_sent')
    queryset.page_size = page_size

    for msg in queryset:
        <do stuff here>

    qs_start += page_size
    qs_end += page_size if i != _times else last_qs_end

```

Thanks,

Qho

**Comment by ecederstrand** [comment]
I'm not sure what your question is?

```python
qs = account.inbox.all().only('mime_content').iterator()
for msg in qs:
    with open('%s.eml' % msg.item_id, 'wb') as f:
        f.write(msg.mime_content)
```

should be reasonably fast, but if you have many emails with large attachments, you may want to lower the page size of the request from the default of 100, to reduce memory usage and response times from the server:

```python
qs = account.inbox.all().only('mime_content').iterator()
qs.page_size = 10
for msg in qs:
    with open('%s.eml' % msg.item_id, 'wb') as f:
        f.write(msg.mime_content)
```

If you have huge emails, you may want to set the page size even lower.

**Comment by qholi** [comment]
If fetch the emails without 'order_by' that does not have any problems. But it will use many resources if added 'order_by' even set the page_size to '1'.
Besides, cannot set the page_size for the iterator(), it prompts "AttributeError: 'generator' object has no attribute 'page_size'". I tried to set the page_size for normal qs.

**Comment by ecederstrand** [comment]
That's very strange. `order_by` is a value we pass on to the server, and sorting is done server-side. There is no client-side processing unless you are sorting the result of `calendar.view()` (assuming you have a recent version of exchangelib). So there should be no extra client-side work, whether you request sorting or not.

You are right that `page_size` cannot be set on the result of `.iterator()` . I've updated my example now.

**Comment by qholi** [comment]
Thanks @ecederstrand .
Finally, I may have found the cause of slow. It will run the requests with multi threads. I limited single request in the new code mentioned above, so it seems lower loading.
But I have a question that can I stop the multithread feature for the query?

**Comment by ecederstrand** [comment]
You can change the `BaseProtocol.SESSION_POOLSIZE` setting from a default of 4 if you need less parallelism when making requests.

**Comment by ecederstrand** [comment]
Seems we can close this issue?
