### ISSUE TITLE
Create a new calendar

### ISSUE THREAD

**Issue by cacciatc** [ecederstrand/exchangelib#489]
Hello,

Is there a way to create calendars with exchangelib? I have successfully created folders under ```account.calendar```, but not an actual calendar.

**Comment by cacciatc** [comment]
Hmmm, after reading more of the Microsoft docs I am not seeing a way to create a calendar via EWS API. Apologies.

**Comment by ecederstrand** [comment]
Hi @cacciatc 

Creating a secondary calendar should be as easy as creating a new calendar folder as a child folder of the default calendar folder:

```python
from exchangelib.folders import Calendar

Calendar(parent=account.calendar, name='My New Calendar').save()
```

**Comment by cacciatc** [comment]
Thanks for the reply @ecederstrand. I tried your snippet and it creates a folder under the calendar folder (folder view from outlook below):
![folder_view](https://user-images.githubusercontent.com/149836/46364134-c5d79980-c629-11e8-9cd1-956288db174f.png)

However, it doesn't appear under my calendar tab in Outlook (or any of the other calendar groups):
![cal_view](https://user-images.githubusercontent.com/149836/46364219-0b946200-c62a-11e8-9a17-84cdc150ab89.png)

Is there some secret sauce to make the calendar appear in the calendar view as well? Thanks

**Comment by ecederstrand** [comment]
Should be fixed now. You have to delete the folder and create it again because the folder class cannot be changed on existing folders. Thanks for testing!
