### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by bmullen-steelcase** [ecederstrand/exchangelib#50]
I'm trying to filter a huge email folder by date.  I'm working from the filtering example on the main page, but getting an error.  Is there a different process for filtering emails? Here's my code:
```
def processCompleted(processAttachments=False):
    folder = account.root.get_folder_by_name('COMPLETED EMAILS')
    for idx, message in enumerate(folder.filter(start__range=(EWSDateTime(2016, 12, 1), EWSDateTime(2017, 1, 1)))):
        soup = BeautifulSoup(message.body, 'html.parser')
        bodyText = re.sub("<!.*-->",'',soup.get_text(), flags=re.S).strip()
```

Here's the error:

> Traceback (most recent call last):
>   File "C:\Users\XXXX\Desktop\Code\Email\emailTest.py", line 220, in <module>
>     processCompleted()
>   File "C:\Users\XXXX\Desktop\Code\Email\emailTest.py", line 142, in processCompleted
>     for idx, message in enumerate(folder.filter(start__range=(EWSDateTime(2016, 12, 1), EWSDateTime(2017, 1, 1)))):
>   File "C:\Python35\lib\site-packages\exchangelib\folders.py", line 1951, in filter
>     return QuerySet(self).filter(*args, **kwargs)
>   File "C:\Python35\lib\site-packages\exchangelib\queryset.py", line 237, in filter
>     q = Q.from_filter_args(self.folder.__class__, *args, **kwargs) or Q()
>   File "C:\Python35\lib\site-packages\exchangelib\restriction.py", line 163, in from_filter_args
>     kwargs_q &= Q(**{key: value})
>   File "C:\Python35\lib\site-packages\exchangelib\restriction.py", line 82, in __init__
>     self.children.append(self.__class__(**{'%s__gte' % field: value[0]}))
>   File "C:\Python35\lib\site-packages\exchangelib\restriction.py", line 102, in __init__
>     self.value = value.astimezone(UTC)
>   File "C:\Python35\lib\site-packages\exchangelib\ewsdatetime.py", line 52, in astimezone
>     t = super().astimezone(tz=tz)
> ValueError: astimezone() cannot be applied to a naive datetime

**Comment by ecederstrand** [comment]
The error message is not very helpful. The problem is that your timestamps in the range filter must be timezone-aware. Otherwise the filtering is ambiguous.

The README describes how to create timezone-aware EWS timestamps.

**Comment by bmullen-steelcase** [comment]
My filter string is from the README.  Here is the line in the README.  Could you tell me where I'm wrong?

`# items_for_2017 = my_calendar.filter(start__range=(EWSDateTime(2016, 1, 1), EWSDateTime(2017, 1, 1)))`

**Comment by ecederstrand** [comment]
Ah, I see the code in the comment is wrong. Fixed now.

What you should do is:
```python
tz = EWSTimeZone.timezone('Some/Region')
items_for_2017 = my_calendar.filter(start__range=(
    tz.localize(EWSDateTime(2017, 1, 1)),
    tz.localize(EWSDateTime(2018, 1, 1))
))
```

**Comment by bmullen-steelcase** [comment]
That fixed the problem.  For anyone else, to get emails after a certain date, I used this.

```
def processCompleted(processAttachments=False):
    folder = account.root.get_folder_by_name('COMPLETED EMAILS')
    print(folder.allowed_field_names())  # Show available fields to filter on
    tz = EWSTimeZone.timezone('US/Eastern')
    
    for idx, message in enumerate(folder.filter(datetime_received__lt=tz.localize(EWSDateTime(2016, 12, 1)))):
        soup = BeautifulSoup(message.body, 'html.parser')
        bodyText = re.sub("<!.*-->",'',soup.get_text(), flags=re.S).strip()
```
