### ISSUE TITLE
HTML bodies in calendar items

### ISSUE THREAD

**Issue by rjwiii** [ecederstrand/exchangelib#500]
For the life of me, I can't seem to draw a table in a calendar item with borders of any kind. Tried header styles & inline styles ... neither worked.

Here's the rub: the borders render fine on Outlook on a Mac ...

Tried reverse engineering it ... Mocked up a a meeting, then tried to dump the body out via exchangelib ... produced HTML with no style tags anywhere ...

I'm thinking that with the convoluted way Outlook (on M$ at least) renders the body of a meeting invite internally to some byte encoded RTF, that formatting outside of Outlook itself may not be possible.

Any ideas?

rjwiii

**Comment by rjwiii** [comment]
Tried the reverse engineering thing ... made a calendar item with 3pt boarders ... examined with exchangelib ... boarders where stripped from the HTML ... I'll keep testing.

**Comment by nstr10** [comment]
@rjwiii I found this, which might be relevant:
https://stackoverflow.com/questions/20712500/ews-managed-api-breaks-appointment-html-message-body-on-update

It seems this is an issue with a conversion from HTML to RTF somewhere within Exchange (therefore not likely an exchangelib issue). You might try using a library like PyRTF3 to troubleshoot.

Based on what I've read, you are likely to see differing behavior between Outlook clients, OWA, and EWS.

**Comment by ecederstrand** [comment]
Thanks for the link, @nstr10 

I'm closing this issue since I don't think we can do anything in exchangelib to improve the situation. Feel free to reopen if you think otherwise.
