### ISSUE TITLE
outlook.office365.com/EWS/Exchange.asmx says user / pass is wrong..

### ISSUE THREAD

**Issue by nitrocode** [ecederstrand/exchangelib#502]
I'm trying to use the main exchange server `outlook.office365.com` and I cannot seem to authenticate. Our system uses Active Directory and requires an authenticator. I can login using my user / pass on outlook.office.com but cannot through this code. Also auto discover doesn't work.

My `os.environ['ADUSER']` is `firstinitiallastname@company.com`

```
from datetime import datetime, timedelta
import pytz
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, GSSAPI, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version, FolderCollection
import os
import pdb


credentials = Credentials(username=os.environ['ADUSER'], password=os.environ['ADPASS'])
URL = "https://outlook.office365.com/EWS/Exchange.asmx"

config = Configuration(server='outlook.office365.com', credentials=credentials)
```

My error message

```
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    config = Configuration(server='outlook.office365.com', credentials=credentials)
...
raise UnauthorizedError('Wrong username or password for %s' % response.url)
exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx
```

The username and password definitely seem correct... What could be the issue?

**Comment by shehreyarahmedkohati** [comment]
I have the same issue with outlook.office.com Email.

**Comment by ecederstrand** [comment]
This could be because the this is the wrong server to connect to. Does autodiscover work? You have to disable SSL for now due to https://github.com/ecederstrand/exchangelib/issues/337

**Comment by nitrocode** [comment]
@ecederstrand thanks for linking that issue. I tried the workaround https://github.com/ecederstrand/exchangelib/issues/337#issuecomment-389450692 with my username, domain, and password and it returned the following error

> exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

Is there additional details I can provide that would show where the error is coming from?

**Comment by ecederstrand** [comment]
I think your best bet is to compare the steps exchangelib is taking in the autodiscover process with the steps taken in the canonical autodiscover test at https://testconnectivity.microsoft.com. Assuming autodiscovery work there, we're taking a wrong turn somewhere.

**Comment by ecederstrand** [comment]
I'm closing this one. Let's solve autodiscovery problems in #337
