### ISSUE TITLE
Unable to reply/reply_all "ValueError: Message must have an ID"

### ISSUE THREAD

**Issue by leesandao** [ecederstrand/exchangelib#506]
Hi 

I try to use exchangelib to create daily reply_to_all job to a specific mail, I have successfully send mail but unable to reply/reply_all , could someone give me guide on this?

```
import urllib3
from exchangelib import DELEGATE, Account, Credentials, Configuration, NTLM, Message, Mailbox, HTMLBody
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter

BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


cred = Credentials(r'domain\username', 'password')

config = Configuration(server='mail.example.com', credentials=cred, auth_type=NTLM)
a = Account(
    primary_smtp_address='username@examplecom', config=config, autodiscover=False, access_type=DELEGATE
)


m = Message(
    account=a,
    #folder=a.sent,
    subject='Daily motivation',
    body='All bodies are beautiful',
    to_recipients=[Mailbox(email_address='username@example.com')]
)
m.send()

m.reply_all(
    subject='Re: foo',
    body='I agree',
)
```

when executing, error below

> C:\Users\raynorwin10\Desktop>python ex3_replymail.py
Traceback (most recent call last):
  File "ex3_replymail.py", line 31, in <module>
    body='I agree',
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\items.py", line 778, in reply_all
    self.create_reply_all(subject, body).send()
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python37\lib\site-packages\exchangelib\items.py", line 766, in create_reply_all
    raise ValueError('%s must have an ID' % self.__class__.__name__)
ValueError: Message must have an ID

**Comment by ecederstrand** [comment]
You can only `.reply_all()` to a message that exists in the Exchange database. `.send()` only sends the message, but does not store it in the database.

I'm not sure why you would want to reply to a message you sent yourself, but you can do it by calling `.send_and_save()` instead of just `.send()`.

If you really want to call `.send()` for some reason, and are sending the message to yourself, then you can wait for the message to arrive in your inbox and reply to that:

```python
import time
from exchangelib.queryset import DoesNotExist

m = Message(...)
m.send()
for _ in range(10):
    try:
        incoming = a.inbox.get(subject='Daily motivation'))
    except DoesNotExist:
        time.sleep(10)
else:
    assert False, 'Gave up waiting for incoming message'
incoming.reply_all(...)
```

**Comment by leesandao** [comment]
Hi ecederstrand,

Thanks for your description.

I have a job that need to report status at same timestamp everyday in one mail thread, so I think exchangelib may help me a lot.

My previous code is just sample, what I was confusing is how does "reply_all" work. Does the "subject" need to be the same string both in Message() and reply_all()?

In your example, it seems following below process:
1.define a message that I need to reply_all with "Message" function
2.use m.reply_all to reply it
3.send and save() for next day reply_all

I will try your sample first, thanks!

**Comment by leesandao** [comment]
Hi ecederstrand,

Thanks for your description.

I have a job that need to report status at same timestamp everyday in one mail thread, so I think exchangelib may help me a lot.

My previous code is just sample, what I was confusing is how does "reply_all" work. Does the "subject" need to be the same string both in Message() and reply_all()?

In your example, it seems following below process:
1.define a message that I need to reply_all with "Message" function
2.use m.reply_all to reply it
3.send and save() for next day reply_all

I will try your sample first, thanks!

**Comment by leesandao** [comment]
I think I got to know how to use reply_all function right now.

```
from exchangelib import Credentials, Account

credentials = Credentials('john@example.com', 'passwd')
account = Account('john@example.com', credentials=credentials, autodiscover=True)

#print(account.root.tree())

CIO_Status_mail = account.sent.get(subject='RE:Daily motivation')  //define where is the target mail thread
CIO_Status_mail.reply_all(subject="RE:Daily motivation",   //reply_all to this mail thread
					body="This test is from sent items")
```

Thanks a lot for your reply, ecederstrand!  I think it maybe better to write in sample of reply/reply_all functions, that will be easier for newbee like me...

**Comment by ecederstrand** [comment]
I changed the fordingg a bit in the README now.

`reply()`, `reply_all()` and `forward()` will work on anything that has an Exchange item ID, i.e. any message that you either retrieved from a folder or called `save()` or `send_and_save()` on. The subject can be anything you choose, just like in most email clients.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still need help.
