### ISSUE TITLE
How to reply_all with embedded images

### ISSUE THREAD

**Issue by leesandao** [ecederstrand/exchangelib#508]
I can send new mail with embedded image through #250 

I can reply_all with specific mail

But when I want to reply_all with embedded mail, it always shows "X" in outlook client
```
from exchangelib import Credentials, Account, HTMLBody, FileAttachment

credentials = Credentials('xxx@yyy.com', 'zzz')
account = Account('xxx@yyy.com', credentials=credentials, autodiscover=True)

CIO_Status_Screenshot = 'E:\screenshots\screenshot.jpg'

with open(CIO_Status_Screenshot,'rb') as fp:
	Screenshot_Img = FileAttachment(name=CIO_Status_Screenshot, content=fp.read())
	
CIO_Status_mail = account.sent.filter(subject='RE:Daily motivation')  
for item in CIO_Status_mail.order_by('-datetime_received')[:1]:
	#item.attach(Screenshot_Img)
	item.reply_all(subject = "RE:Daily motivation",body = HTMLBody('<html><body><p>Hi Team<br /><img src="cid:screenshot.jpg"><br />B.R.<br />Raynor</p></body></html>'))
	item.attach(Screenshot_Img)
```

**Comment by ecederstrand** [comment]
Your code is is adding the attachment to the original item, not the reply you are trying to send.

But `.reply_all()` will send the reply at once. There's no return value. If you want to modify the reply before sending, use `.create_reply_all()` and then call `.send()` on the return value.

However, `ReplyAllToItem` items in EWS do not support attachments, so if you want to add attachments to a reply, you will need to create a normal `Message` item, add your attachments, and send that item instead. Have a look at the `references` and `in_reply_to` fields if you want to retain the conversation IDs.

**Comment by leesandao** [comment]
Hi , I cannot find ```references``` and ```in_reply_to``` in README session,  could you guide me detailed information.... thanks a lot

**Comment by ecederstrand** [comment]
Enumerating all fields on all item types in the README would be too much, I think. You can get the list of supported fields like this:

```python
 >>> from exchangelib import Message
>>> for f in Message.FIELDS:
...     print(f)
... 
[...]
TextField(name='in_reply_to', value_cls=<class 'str'>, is_list=False, is_complex=True, default=None)
[...]
TextField(name='references', value_cls=<class 'str'>, is_list=False, is_complex=True, default=None)
[...]
```

If you want additional documentation, there's a link to MSDN in the docstring of almost all classes:

```python
>>> print(Message.__doc__)

    MSDN: https://msdn.microsoft.com/en-us/library/office/aa494306(v=exchg.150).aspx
```

**Comment by leesandao** [comment]
Thanks! Let me study on this.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you need additional help.
