### ISSUE TITLE
Debug Stuck at Releasing Session

### ISSUE THREAD

**Issue by cyberion1985** [ecederstrand/exchangelib#510]
My code runs but without errors or anything. I've tried an older version of exchangelib and a new one. If I run the debug, it sits at this line :

> DEBUG:exchangelib.protocol:Server SERVERNAME: Releasing session 12355

**Comment by ecederstrand** [comment]
There's way too little context here to provide any help. Please post the code that causes this, your exchangelib version and the debug output that least up to this.

**Comment by cyberion1985** [comment]
I think I can close issue. This is probably tied to the Timeout issue I have
