### ISSUE TITLE
How do export email addresses list by using exchangelib

### ISSUE THREAD

**Issue by jacara** [ecederstrand/exchangelib#511]
Hello
I want to export email addresses list from my Exchange Server. How do I export email addresses by using exchangelib.

Thank you.

**Comment by ecederstrand** [comment]
You can't do that with EWS, as far as I know. You can pull out members of distribution lists, and you can query searchable mailboxes if you have sufficient privileges: https://github.com/ecederstrand/exchangelib#non-account-methods
