### ISSUE TITLE
Mismatch between inbox in Outlook and in EWS

### ISSUE THREAD

**Issue by mr-bjerre** [ecederstrand/exchangelib#513]
I have an inbox that contains 8 elements in my Outlook client. But when I use exchangelib then I get additional 2 emails that I can't locate in my Outlook client. Any suggestions to what the issue might be?

**Comment by ecederstrand** [comment]
Please post some example code. If you print the subjects of each item, you will probably get an idea of what is going on.

**Comment by mr-bjerre** [comment]
Problem is that it is sensitive data so I can't really post an example. I did print each subject and that's how I realized it. The following code shows the 8 subjects as expected but also prints two additional subjects in the end.

    for item in a.inbox.all():
        if isinstance(item, Message):
            print(item.subject)

**Comment by ecederstrand** [comment]
Your Outlook client is probably out of sync, then. exchangelib fetches data directly from the server, which has the master database.

**Comment by mr-bjerre** [comment]
Just looked into the received time. The two emails are two years older. There might be some filter on the Outlook Client i suppose.

Btw. are there some way of copying emails between accounts? (or a sample script that exports and imports?)
