### ISSUE TITLE
Ntlm warnings

### ISSUE THREAD

**Issue by Alan564** [ecederstrand/exchangelib#515]
When using the exchangelib, warnings from the Ntlm library are displayed.
`/ntlm_auth/ntlm.py:149: DeprecationWarning: Using Ntlm() is deprecated and will be removed in a future version. Use NtlmContext() instead`
![2018-11-22 15-55-58](https://user-images.githubusercontent.com/35463265/48904346-24253980-ee6f-11e8-9949-b0e5ff8c68c9.png)

https://github.com/jborean93/ntlm-auth/commit/25c6a00a1e95967e7fbc989bf0391dd83e9e1de6

**Comment by Alan564** [comment]
https://github.com/jborean93/ntlm-auth/commit/25c6a00a1e95967e7fbc989bf0391dd83e9e1de6

**Comment by ecederstrand** [comment]
exchangelib doesn't use `ntlm-auth` directly. We use `requests_ntlm` which in turn calls `ntlm-auth`. See https://github.com/requests/requests-ntlm/blob/master/requests_ntlm/requests_ntlm.py#L74

Please redirect the ticket to `requests_ntlm`.

**Comment by Alan564** [comment]
Thanks a lot!
