### ISSUE TITLE
Listening for new emails

### ISSUE THREAD

**Issue by mr-bjerre** [ecederstrand/exchangelib#516]
Is there a listener feature in the package?

I want to automatically distribute any incoming emails to folders when they are received. I know I can just iterate over the inbox every x seconds but maybe there is a better way to do it?

**Comment by ecederstrand** [comment]
That's supported by EWS but still unimplemented in exchangelib. Tracked in #145 and #209 and partially implemented in #355

**Comment by ecederstrand** [comment]
There's also inbox filtering rules, of course. exchangelib cannot create them yet (see https://github.com/ecederstrand/exchangelib/issues/233) but you can create them using e.g. Outlook or OWA.
