### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by chenzhaoyangATgithub** [ecederstrand/exchangelib#517]
when I use a test env ,which means I have no certificate for my own v machine. Why not give a param like "force" to send request such as :
requests.post(url,send_data,verify=False) ??

**Comment by ecederstrand** [comment]
We use HTTP adapters as a more general way of solving this. In your case, you can use `NoVerifyHTTPAdapter`. See https://github.com/ecederstrand/exchangelib#proxies-and-custom-tls-validation

**Comment by chenzhaoyangATgithub** [comment]
Thank you very much.
BTW, I have a problem in my new app.
Suppose that I were an administrator for Email in a group. My job is to check everybody's email to ensure nobody is illegal. How can I download all the emails in the exchange server with python script instead of existing apps?
Could you help me please?
Thanks

**Comment by ecederstrand** [comment]
Something like this will search for all message type items in all subfolders of the Top of Information Store folder, where personal folders are normally stored. This assumes you have a list of account emails:

```python
admin_credentials = Credentials(...)
for email in all_emails:
    a = Account(primary_smtp_address=email, credentials= admin_credentials,
                     autodiscover=True, access_type=IMPERSONATION)
    all_messages = list(a.root.tois.glob('*').filter(item_class='IPM.Note'))
```

**Comment by chenzhaoyangATgithub** [comment]
In my case , I can get any permission before the script run ,even if do something at the server instance. But I'm not sure how to connect with Power Shell in system of CentOS or any other linux

**Comment by ecederstrand** [comment]
PowerShell commands can only be run on the Windows server running Exchange. You'll have to look up the exact commands to list all accounts in the Exchange manual.

Hopefully your list of accounts doesn't change very often. You could use a static list of accounts in a text file that you or your Exchange admin refreshes regularly.

**Comment by ecederstrand** [comment]
If you can get someone to assign your account the proper privileges, you may have luck listing all accounts using the `get_searchable_mailboxes()` method. See https://github.com/ecederstrand/exchangelib#non-account-methods

**Comment by chenzhaoyangATgithub** [comment]
emmm……in my case , I can get any proper privileges, because I 'm the supper admin. and can do anything on the exchange server even if "rm -rf /" : )

**Comment by ecederstrand** [comment]
Well in that case, give `account.protocol.get_searchable_mailboxes()` a try.

**Comment by chenzhaoyangATgithub** [comment]
Well, what proper privileges I need to give the admin account ?

**Comment by chenzhaoyangATgithub** [comment]
GetSearchableMailboxes is only supported for Exchange 2013 servers and later?

**Comment by ecederstrand** [comment]
The method is only available to users who have been assigned the Discovery Management RBAC role.

According to https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getsearchablemailboxes-operation, it was in fact added in Exchange Server 2013.

**Comment by chenzhaoyangATgithub** [comment]
you mean my server exchange 2010 can't use this method ?

**Comment by ecederstrand** [comment]
No. Exchange 2010 doesn't support that method.

**Comment by chenzhaoyangATgithub** [comment]
But exchange 2010 has discover management role , can I use this role to do something to get mail boxes?

**Comment by chenzhaoyangATgithub** [comment]
Awesome! my product manager give me a good news, that user list will be provided by other system!

**Comment by chenzhaoyangATgithub** [comment]
Thank you very much ,gentleman.  It 's very kind of you!
