### ISSUE TITLE
Using MD4 hashing is considered a security flaw

### ISSUE THREAD

**Issue by bergerod** [ecederstrand/exchangelib#518]
First, thanks you writing this package.  It has been a great help to our team.  We are using this package in our code deploy and are hitting an issue.  Our openssl doesn't have MD4 and MD5 hash as they are considered a flaw.  Is there another auth_type in the configuration to use, or thoughts about upgrading this?

**Comment by bergerod** [comment]
I am sorry, this is within the NTLM -> requests_ntlm -> ntlm_auth.     both the compute_response.py and compute_hash.py have md4 and md5 hard coded.   Here is a copy of the stack that we are getting.  If this is not the correct place to open this ticket please let me know.

File "/usr/local/ECP/virtualenvs/capacityserver/lib/python3.4/site-packages/ntlm_auth/messages.py", line 347, in __init__
    compute_response.get_lm_challenge_response()
  File "/usr/local/ECP/virtualenvs/capacityserver/lib/python3.4/site-packages/ntlm_auth/compute_response.py", line 95, in get_lm_challenge_response
    self._client_challenge)
  File "/usr/local/ECP/virtualenvs/capacityserver/lib/python3.4/site-packages/ntlm_auth/compute_response.py", line 274, in _get_LMv2_response
    nt_hash = comphash._ntowfv2(user_name, password, domain_name)
  File "/usr/local/ECP/virtualenvs/capacityserver/lib/python3.4/site-packages/ntlm_auth/compute_hash.py", line 87, in _ntowfv2
    digest = _ntowfv1(password)
  File "/usr/local/ECP/virtualenvs/capacityserver/lib/python3.4/site-packages/ntlm_auth/compute_hash.py", line 66, in _ntowfv1
    digest = hashlib.new('md4', password.encode('utf-16-le')).digest()
  File "/usr/local/ECP/virtualenvs/capacityserver/lib64/python3.4/hashlib.py", line 159, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/local/ECP/virtualenvs/capacityserver/lib64/python3.4/hashlib.py", line 118, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md4

**Comment by ecederstrand** [comment]
The NTLM protocol is known to be weak, but it's what most Exchange servers offer apart from Basic auth, which is even less secure. Changing the NTLM protocol is not an option.

Office365 apparently supports OAuth (see https://github.com/ecederstrand/exchangelib/issues/90) but on-prem don't have that choice, AFAIK. Some servers may offer Kerberos, but it's rare in my experience. Someone in a different issue even complained that Kerberos is insecure ¯\_(ツ)_/¯

So I do't think there's much we can do here.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's anything we can do on our side to improve the situation.

**Comment by ankushagarwal87** [comment]
Can you share how you resolve the issue.
I am using Exchange on premise & my application is running fine in windows but failing in linux server with ValueError: unsupported hash type md4

**Comment by ecederstrand** [comment]
You either need to re-add support for MD4 in your OpenSSL installation or switch your server to a different authentication mechanism than NTLM.

**Comment by eusoubrasileiro** [comment]
Solution is this https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1971580/comments/3

Add this to your `/usr/lib/openssl.cnf` to 're-enable' md4 to hashlib

```
[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```

**Comment by c84c** [comment]
First of all, thanks for the great work to all `exchangelib` contributors, expecially to @ecederstrand !

> You either need to re-add support for MD4 in your OpenSSL installation or switch your server to a different authentication mechanism than NTLM.

Like exposed, on-prem Exchange server users cannot use a different authentication method  than NTLM. So the only solution is to re-add support for MD4 in OpenSSL.

Instead of manage OpenSSL distribution configuration file like `/usr/lib/openssl.cnf`, a portable python solution implies to use [oscrypto](https://github.com/wbond/oscrypto) package (thanks to  @wbond ).

I successful test below solution with OpenSSL version 3.0.2 and 3.0.8 on Ubuntu 22.04 and Fedora 37 respectively.

The solution:
1. install `oscrypto` master branch instead of PyPi released version:
    * with **pip** run `pip install git+https://github.com/wbond/oscrypto.git@master`
    * with **poetry** run `poetry add git+https://github.com/wbond/oscrypto.git#master`
1. before any import to `exchangelib`, e.g. in a `__init__.py` file, insert an import to a function from `oscrypto` like following snippet. Pay attention on function used: the function must be an alias of underlying used crypto library. `rand_bytes` works like a charm!
   ```python
    # import a oscrypto wrapper function to load underlying crypto library
    # and enable legacy providers for OpenSSL
    from oscrypto.util import rand_bytes
    
    # block auto formatting from remove import
    _ = rand_bytes(1)
   ```

I hope this python solution can be useful.
