### ISSUE TITLE
event timezones getting simplified incorrectly

### ISSUE THREAD

**Issue by mcv21** [ecederstrand/exchangelib#519]
Hi,

I might be driving it wrong, but exchangelib is over-simplifying event timezones in a way that is causing breakage.

XML from server includes:
```XML
<t:StartTimeZone Name="(UTC+00:00) Dublin, Edinburgh, Lisbon, London" Id="GMT Standard Time">
```
but that appears in the python object as GMT:
```python
>>> debugtest._start_timezone
<StaticTzInfo 'GMT'>
```
Whereas I actually need something like "Europe/London". This is important because a recurring event that crosses a DST boundary is different if it's "08:00 GMT" or "08:00 Europe/London".

This is with python3 and exchangelib HEAD from October this year (ac4d84c20dcded85194e9a58d57552a76d745a9a)

**Comment by ecederstrand** [comment]
I don't think there's enough information in the returned data to do what you want:

  * There's no DST information in the XML
  * Microsoft insists on inventing their own timezone definitions that nobody else uses, so you can't just look up "(UTC+00:00) Dublin, Edinburgh, Lisbon, London" in the Olson database
  * The name mapping we have in https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/winzone.py#L24 currently contains 9 different `pytz` region/country translations for `GMT Standard Time`. If we somehow convert this to `Europe/London` then tomorrow someone will complain that they wanted `Europe/Lisbon` instead
  * Assuming your problem is that your start date is in the DST timeframe, then the server is returning bogus data because it should return a `(UTC+01:00) ...` timezone. Otherwise, you don't really have a problem unless you're doing datetime math on the start date.

Are you sure the server doesn't return a `(UTC+01:00) ...` timezone for dates within the DST timeframe?

**Comment by mcv21** [comment]
Thanks for your response.
As it happens any of those 9 would be better than GMT, as they all switch to UTC+1 in the summer :)

This is a recurring event, starting on 30 April, 08:00 - 08:30 each day, until 6 May (i.e. it crosses the DST transition - starting in GMT, moving to BST). I'm trying to import it into a different calendar system (google). At which point we hit the problem that 08:00 GMT (and then daily for a few days) is not the same as 08:00 Europe/London (and then daily for a few days).

**Comment by mcv21** [comment]
Looking at the MS list https://support.microsoft.com/en-gb/help/973627/microsoft-time-zone-index-values and the list exchangelib uses http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml

I observe that there are options for "UTC not varying" which, as I've noted here, is different to Europe/Lisbon, and causes breakage with recurring events crossing a DST change. I think it would be better to pick one of the Olson names in the unicode.org list (the `territory="001"` one would be an obvious default), perhaps with an optional override. 
But for people in a GMT/BST timezone, any of those options would be better than "GMT", which is incorrect.

**Comment by ecederstrand** [comment]
Ok, so the returned timezone from EWS is bogus. It should return `(UTC+01:00)` and an ID of `British Summer Time` or something like that. Ugh. At least we read the `start` value correctly.

I'm not keen on selecting a semi-random region/country value here. What you can do in your case is to replace the `_start_timezone` value manually for each item you fetch. Or you can ignore it and do `item.start.astimezone(pytz.timezone('Europe/London'))` on the values that are returned with a bogus timezone. Also, https://github.com/ecederstrand/exchangelib#non-account-methods describes how to get the default timezone of a user, so you can use that to convert your start date instead of relying on the `_start_timezone` value.

**Comment by mcv21** [comment]
No, I think it's correct. The "(UTC+00:00) Dublin, Edinburgh, Lisbon, London" is a UI label if you like - if you look at the MS list at https://support.microsoft.com/en-gb/help/973627/microsoft-time-zone-index-values you'll see that there are no "summer" timezones there. 

That is, I think, the nub of this bug - MS's "GMT Standard Time" or "Dublin, Edinburgh, Lisbon, London" is in reality a timezone like "Europe/London", not "UTC" - that's why there's a separate entry for "Greenwich Standard Time"/"(GMT) Monrovia, Reykjavik", as those are places which are GMT all year round (i.e. no summer time adjustment). So exchangelib is wrong to be picking "GMT" as timezone, it needs to be picking a timezone with summer time.

**Comment by ecederstrand** [comment]
Thanks for being insistent! I'm finally convinced :-)

I wish I didn't have to waste so much brain space on timezones. I found some more fun facts about GMT Standard Time and the DST/no-DST debacle: https://stackoverflow.com/questions/2292334/difference-between-utc-and-gmt-standard-time-in-net

I think we can fix the problem by removing this line: https://github.com/ecederstrand/exchangelib/blob/ec8bfebba94233f6c946a072dc5ab1b95c0c3f84/exchangelib/winzone.py#L493

That will cause https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/fields.py#L609 to return a random region/country timezone matching GMT Standard Time, which is the best we can do, I believe.

According to the commit log, the GMT Standard Time -> GMT translation was once part of the CLDR database. It no longer is.

**Comment by mcv21** [comment]
I think we can do better :-) We really want the "001" territory value, I think, so `MS_TIMEZONE_TO_PYTZ_MAP` should contain those rather than the rather random value you currently get by reversing `PYTZ_TO_MS_TIMEZONE_MAP`. That can be done fairly easily thus:

```python
import import xml.etree.ElementTree as ET
#re-use result of download in winzone.py or download fresh CLDR_WINZONE_URL
root=ET.fromstring(r.content)
revmap={}
for m in root.findall("./windowsZones/mapTimezones/*[@territory='001']"):
    revmap[m.get('other')] = m.get('type')
```

Would you take an MR that did something similar in winzone.py ? [with a cached copy like you already have for CLDR_TO_MS_TIMEZONE_MAP]

**Comment by mcv21** [comment]
...for reference, that gives you a map like this:
```python
MS_TIMEZONE_TO_PYTZ_MAP = {
    'Dateline Standard Time': 'Etc/GMT+12',
    'UTC-11': 'Etc/GMT+11',
    'Aleutian Standard Time': 'America/Adak',
    'Hawaiian Standard Time': 'Pacific/Honolulu',
    'Marquesas Standard Time': 'Pacific/Marquesas',
    'Alaskan Standard Time': 'America/Anchorage',
    'UTC-09': 'Etc/GMT+9',
    'Pacific Standard Time (Mexico)': 'America/Tijuana',
    'UTC-08': 'Etc/GMT+8',
    'Pacific Standard Time': 'America/Los_Angeles',
    'US Mountain Standard Time': 'America/Phoenix',
    'Mountain Standard Time (Mexico)': 'America/Chihuahua',
    'Mountain Standard Time': 'America/Denver',
    'Central America Standard Time': 'America/Guatemala',
    'Central Standard Time': 'America/Chicago',
    'Easter Island Standard Time': 'Pacific/Easter',
    'Central Standard Time (Mexico)': 'America/Mexico_City',
    'Canada Central Standard Time': 'America/Regina',
    'SA Pacific Standard Time': 'America/Bogota',
    'Eastern Standard Time (Mexico)': 'America/Cancun',
    'Eastern Standard Time': 'America/New_York',
    'Haiti Standard Time': 'America/Port-au-Prince',
    'Cuba Standard Time': 'America/Havana',
    'US Eastern Standard Time': 'America/Indianapolis',
    'Paraguay Standard Time': 'America/Asuncion',
    'Atlantic Standard Time': 'America/Halifax',
    'Venezuela Standard Time': 'America/Caracas',
    'Central Brazilian Standard Time': 'America/Cuiaba',
    'SA Western Standard Time': 'America/La_Paz',
    'Pacific SA Standard Time': 'America/Santiago',
    'Turks And Caicos Standard Time': 'America/Grand_Turk',
    'Newfoundland Standard Time': 'America/St_Johns',
    'Tocantins Standard Time': 'America/Araguaina',
    'E. South America Standard Time': 'America/Sao_Paulo',
    'SA Eastern Standard Time': 'America/Cayenne',
    'Argentina Standard Time': 'America/Buenos_Aires',
    'Greenland Standard Time': 'America/Godthab',
    'Montevideo Standard Time': 'America/Montevideo',
    'Magallanes Standard Time': 'America/Punta_Arenas',
    'Saint Pierre Standard Time': 'America/Miquelon',
    'Bahia Standard Time': 'America/Bahia',
    'UTC-02': 'Etc/GMT+2',
    'Azores Standard Time': 'Atlantic/Azores',
    'Cape Verde Standard Time': 'Atlantic/Cape_Verde',
    'UTC': 'Etc/GMT',
    'GMT Standard Time': 'Europe/London',
    'Greenwich Standard Time': 'Atlantic/Reykjavik',
    'W. Europe Standard Time': 'Europe/Berlin',
    'Central Europe Standard Time': 'Europe/Budapest',
    'Romance Standard Time': 'Europe/Paris',
    'Morocco Standard Time': 'Africa/Casablanca',
    'Sao Tome Standard Time': 'Africa/Sao_Tome',
    'Central European Standard Time': 'Europe/Warsaw',
    'W. Central Africa Standard Time': 'Africa/Lagos',
    'Jordan Standard Time': 'Asia/Amman',
    'GTB Standard Time': 'Europe/Bucharest',
    'Middle East Standard Time': 'Asia/Beirut',
    'Egypt Standard Time': 'Africa/Cairo',
    'E. Europe Standard Time': 'Europe/Chisinau',
    'Syria Standard Time': 'Asia/Damascus',
    'West Bank Standard Time': 'Asia/Hebron',
    'South Africa Standard Time': 'Africa/Johannesburg',
    'FLE Standard Time': 'Europe/Kiev',
    'Israel Standard Time': 'Asia/Jerusalem',
    'Kaliningrad Standard Time': 'Europe/Kaliningrad',
    'Sudan Standard Time': 'Africa/Khartoum',
    'Libya Standard Time': 'Africa/Tripoli',
    'Namibia Standard Time': 'Africa/Windhoek',
    'Arabic Standard Time': 'Asia/Baghdad',
    'Turkey Standard Time': 'Europe/Istanbul',
    'Arab Standard Time': 'Asia/Riyadh',
    'Belarus Standard Time': 'Europe/Minsk',
    'Russian Standard Time': 'Europe/Moscow',
    'E. Africa Standard Time': 'Africa/Nairobi',
    'Iran Standard Time': 'Asia/Tehran',
    'Arabian Standard Time': 'Asia/Dubai',
    'Astrakhan Standard Time': 'Europe/Astrakhan',
    'Azerbaijan Standard Time': 'Asia/Baku',
    'Russia Time Zone 3': 'Europe/Samara',
    'Mauritius Standard Time': 'Indian/Mauritius',
    'Saratov Standard Time': 'Europe/Saratov',
    'Georgian Standard Time': 'Asia/Tbilisi',
    'Caucasus Standard Time': 'Asia/Yerevan',
    'Afghanistan Standard Time': 'Asia/Kabul',
    'West Asia Standard Time': 'Asia/Tashkent',
    'Ekaterinburg Standard Time': 'Asia/Yekaterinburg',
    'Pakistan Standard Time': 'Asia/Karachi',
    'India Standard Time': 'Asia/Calcutta',
    'Sri Lanka Standard Time': 'Asia/Colombo',
    'Nepal Standard Time': 'Asia/Katmandu',
    'Central Asia Standard Time': 'Asia/Almaty',
    'Bangladesh Standard Time': 'Asia/Dhaka',
    'Omsk Standard Time': 'Asia/Omsk',
    'Myanmar Standard Time': 'Asia/Rangoon',
    'SE Asia Standard Time': 'Asia/Bangkok',
    'Altai Standard Time': 'Asia/Barnaul',
    'W. Mongolia Standard Time': 'Asia/Hovd',
    'North Asia Standard Time': 'Asia/Krasnoyarsk',
    'N. Central Asia Standard Time': 'Asia/Novosibirsk',
    'Tomsk Standard Time': 'Asia/Tomsk',
    'China Standard Time': 'Asia/Shanghai',
    'North Asia East Standard Time': 'Asia/Irkutsk',
    'Singapore Standard Time': 'Asia/Singapore',
    'W. Australia Standard Time': 'Australia/Perth',
    'Taipei Standard Time': 'Asia/Taipei',
    'Ulaanbaatar Standard Time': 'Asia/Ulaanbaatar',
    'Aus Central W. Standard Time': 'Australia/Eucla',
    'Transbaikal Standard Time': 'Asia/Chita',
    'Tokyo Standard Time': 'Asia/Tokyo',
    'North Korea Standard Time': 'Asia/Pyongyang',
    'Korea Standard Time': 'Asia/Seoul',
    'Yakutsk Standard Time': 'Asia/Yakutsk',
    'Cen. Australia Standard Time': 'Australia/Adelaide',
    'AUS Central Standard Time': 'Australia/Darwin',
    'E. Australia Standard Time': 'Australia/Brisbane',
    'AUS Eastern Standard Time': 'Australia/Sydney',
    'West Pacific Standard Time': 'Pacific/Port_Moresby',
    'Tasmania Standard Time': 'Australia/Hobart',
    'Vladivostok Standard Time': 'Asia/Vladivostok',
    'Lord Howe Standard Time': 'Australia/Lord_Howe',
    'Bougainville Standard Time': 'Pacific/Bougainville',
    'Russia Time Zone 10': 'Asia/Srednekolymsk',
    'Magadan Standard Time': 'Asia/Magadan',
    'Norfolk Standard Time': 'Pacific/Norfolk',
    'Sakhalin Standard Time': 'Asia/Sakhalin',
    'Central Pacific Standard Time': 'Pacific/Guadalcanal',
    'Russia Time Zone 11': 'Asia/Kamchatka',
    'New Zealand Standard Time': 'Pacific/Auckland',
    'UTC+12': 'Etc/GMT-12',
    'Fiji Standard Time': 'Pacific/Fiji',
    'Chatham Islands Standard Time': 'Pacific/Chatham',
    'UTC+13': 'Etc/GMT-13',
    'Tonga Standard Time': 'Pacific/Tongatapu',
    'Samoa Standard Time': 'Pacific/Apia',
    'Line Islands Standard Time': 'Pacific/Kiritimati',
}
```

**Comment by ecederstrand** [comment]
You are right. Territory `001` is the territory to use if you don't have explicit territory information.

I would prefer to add territory information to `CLDR_TO_MS_TIMEZONE_MAP ` along with the MS timezone name (e.g. expand the values to a `{ms_id="Hawaiian Standard Time", territory="001"}` format) and continue to generate `MS_TIMEZONE_TO_PYTZ_MAP` from that list. That way we carry less redundant code around.

**Comment by mcv21** [comment]
[obv. if you like that approach, the test would need adjusting and so on, but I thought it was worth agreeing on the approach before I start thinking about a proper PR :) ]

**Comment by ecederstrand** [comment]
I would prefer to let `generate_map()` generate one mapping structure that contains all timezones and maps from CLDR to MS ID + territory information, and hardcore that one structure in winzones.py. We can then generate the direct and reverse mappings from that one structure.

If we had two hardcoded mapping structures, then we risk that they become out of sync.

**Comment by ecederstrand** [comment]
Thanks for the high quality PR!

+1 would merge again :-)
