### ISSUE TITLE
create_reply_all      bug??

### ISSUE THREAD

**Issue by kongxiaocong** [ecederstrand/exchangelib#522]
```python
    def create_reply_all(self, subject, body,add_cc_recipients=None):
        if not self.account:
            raise ValueError('%s must have an account' % self.__class__.__name__)
        if not self.id:
            raise ValueError('%s must have an ID' % self.__class__.__name__)
        if add_cc_recipients==None:
            cc_recipients = self.cc_recipients
        else:
            try:
                cc_recipients = self.cc_recipients + add_cc_recipients
            except:
                cc_recipients = add_cc_recipients
        return ReplyAllToItem(
            account=self.account,
            reference_item_id=ReferenceItemId(id=self.id, changekey=self.changekey),
            subject=subject,
            new_body=body,
            to_recipients=self.to_recipients or [self.author],    
            cc_recipients=cc_recipients,
            bcc_recipients=self.bcc_recipients,
        )
```

to_recipients=self.to_recipients or [self.author],     → to_recipients=self.to_recipients+  [self.author] or [self.author],

**Comment by kongxiaocong** [comment]
to_recipients=self.to_recipients or [self.author]
to_recipients can not find  self.author

**Comment by kongxiaocong** [comment]
My English is not very good, I don’t know if you don’t understand.

**Comment by ecederstrand** [comment]
I don't really like adding more kwargs to `create_reply_all()`. It's supposed to be just a helper. If you need more control over the `ReplyAllToItem`, you can just create one yourself or edit the returned item.

I've changed a small bug in `reply()` for when you explicitly set `to_recipients=[]`, and I agree that `reply_all()` should default to sending to both `self.to_recipients` *and* `self.author`.

**Comment by kongxiaocong** [comment]
that's definitely right.thanks!!
