### ISSUE TITLE
Archived calendar

### ISSUE THREAD

**Issue by vadimkara** [ecederstrand/exchangelib#523]
How can i acсess archived calendar stored at my network archive in exchange 2013.

**Comment by ecederstrand** [comment]
Archived folders are available from `account.archive_root`. You can list the entire folder structure with `print(archive_root.tree())`. There are more examples at https://github.com/ecederstrand/exchangelib#folders

**Comment by vadimkara** [comment]
I tried this command but there is only inbox folder and no calendar
archiveroot
├── Recoverable Items
│   ├── Deletions
│   ├── Purges
│   └── Versions
├── Входящие
└── Корневой уровень хранилища
    └── Удаленные

**Comment by ecederstrand** [comment]
Then I don't know where you can access it. You could check `print(root.tree())` to see if it's attached there.

**Comment by ecederstrand** [comment]
Did you find a solution to this? Is the archived calendar accessible to other clients, e.g. Outlook?

**Comment by vadimkara** [comment]
no
├── AllItems
├── Common Views
├── Deferred Action
├── ExchangeSyncData
│   ├── AirSync-Android-android1387101599817
│   │   ├── 10
│   │   ├── 15
│   │   ├── 2
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-android1387465180868
│   │   ├── 10
│   │   ├── 2
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-android1399060624167
│   │   └── Policy
│   ├── AirSync-Android-android1495277969113
│   │   └── Policy
│   ├── AirSync-Android-android22245612962
│   │   ├── 16
│   │   ├── 3
│   │   ├── 4
│   │   ├── 8
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-android35344182367
│   │   ├── 11
│   │   ├── 12
│   │   ├── 14
│   │   ├── 19
│   │   ├── 3
│   │   ├── 8
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-android38023335782
│   │   ├── 14
│   │   ├── 3
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc1096416516
│   │   ├── 11
│   │   ├── 12
│   │   ├── 14
│   │   ├── 19
│   │   ├── 3
│   │   ├── 8
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc1202191266
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 22
│   │   ├── 3
│   │   ├── 4
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc1328071387
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 3
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc1820676864
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 3
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc1872395104
│   │   ├── 11
│   │   ├── 12
│   │   ├── 16
│   │   ├── 22
│   │   ├── 3
│   │   ├── 4
│   │   ├── 5
│   │   ├── 6
│   │   ├── 8
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc1926426880
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 3
│   │   ├── 4
│   │   ├── 6
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc2068375748
│   │   ├── 3
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc237144251
│   │   ├── 10
│   │   ├── 11
│   │   ├── 15
│   │   ├── 21
│   │   ├── 3
│   │   ├── 4
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc346082724
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 3
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc349198904
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 3
│   │   ├── 4
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc445883820
│   │   ├── 10
│   │   ├── 11
│   │   ├── 15
│   │   ├── 21
│   │   ├── 22
│   │   ├── 23
│   │   ├── 3
│   │   ├── 4
│   │   ├── 5
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc517411977
│   │   ├── 10
│   │   ├── 13
│   │   ├── 14
│   │   ├── 16
│   │   ├── 21
│   │   ├── 3
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Android-androidc55649664
│   │   ├── 11
│   │   ├── 12
│   │   ├── 14
│   │   ├── 19
│   │   ├── 20
│   │   ├── 3
│   │   ├── 4
│   │   ├── 8
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Outlook-484031C692FBD574
│   │   ├── 10
│   │   ├── 11
│   │   ├── 15
│   │   ├── 21
│   │   ├── 3
│   │   ├── 4
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   ├── AirSync-Outlook-5896EABB67F19045
│   │   └── Policy
│   ├── AirSync-Outlook-D7951906DEE798B8
│   │   ├── 10
│   │   ├── 11
│   │   ├── 13
│   │   ├── 14
│   │   ├── 23
│   │   ├── 3
│   │   ├── 4
│   │   ├── 5
│   │   ├── Autd
│   │   ├── FolderIdMapping
│   │   ├── Policy
│   │   ├── Root
│   │   └── SyncStatus
│   └── AirSync-WindowsMail-D4DCF75B0E3B9CCC818F1A0F03EEA59C
│       ├── 11
│       ├── 12
│       ├── 16
│       ├── 3
│       ├── 8
│       ├── FolderIdMapping
│       ├── Policy
│       ├── Root
│       └── SyncStatus
├── Finder
│   ├── MS-OLK-AllMailItems
│   └── NoArchiveTagSearchFolder8534F96D-4183-41fb-8A05-9B7112AE2100
├── Freebusy Data
├── Location
├── MailboxAssociations
├── MailboxMoveHistory
├── MyContactsExtended
├── ParkedMessages
├── PeopleConnect
├── Recoverable Items
│   ├── Calendar Logging
│   ├── Deletions
│   ├── Purges
│   └── Versions
├── Schedule
├── Sharing
├── Shortcuts
├── Spooler Queue
├── Subscriptions
├── System
├── TemporarySaves
├── Top of Information Store
│   ├── Infected Items
│   ├── RSS-каналы
│   │   └── Группа компаний "Сигма"
│   ├── Working Set
│   ├── Входящие
│   │   ├── ИТ Отдел
│   │   ├── Копи Сервис
│   │   ├── Левчук
│   │   ├── На удаление
│   │   ├── Супервайзеры
│   │   └── Счета
│   ├── Дневник
│   ├── Задачи
│   ├── Заметки
│   ├── Исходящие
│   ├── Календарь
│   ├── Контакты
│   │   ├── GAL Contacts
│   │   ├── Recipient Cache
│   │   ├── {06967759-274D-40B2-A3EB-D7F9E73727D7}
│   │   └── {A9E2BC46-B3A0-4243-B315-60D991004455}
│   ├── Напоминания
│   ├── Настройка быстрых действий
│   ├── Настройка действий беседы
│   ├── Нежелательная почта
│   ├── Отправленные
│   ├── Ошибки синхронизации
│   │   ├── Конфликты
│   │   ├── Локальные ошибки
│   │   └── Ошибки сервера
│   ├── Пакет новостей
│   ├── Предлагаемые контакты
│   ├── Удаленные
│   └── Черновики
├── Views
├── Избранное
├── Мои контакты
├── Обработка отслеживаемой почты
├── Оповещения
└── Поиск дел

print(root.tree()) didnt help me either. Its an network archive stored on exchange server.

**Comment by vadimkara** [comment]
When a look at properties of actual and archived calendar, locations are "\\Network archive — user@domain" and "\\user@domain"

**Comment by vadimkara** [comment]
When i move calendar to mailbox root i can see it when but wheni move it back cant see it in archive root

**Comment by ecederstrand** [comment]
That's weird. You could try to enable debug logging and see if you can find any hints there. See https://github.com/ecederstrand/exchangelib#troubleshooting

**Comment by ecederstrand** [comment]
Hi @vadimkara Did you find a solution to this problem?

**Comment by ecederstrand** [comment]
According to https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/archiving-in-ews-in-exchange, archives are stored in a different mailbox tan the primary mailbox. So you would have to find the primary SMTP address of that account and connect to that instead to access your archive.
