### ISSUE TITLE
I encountered some problems when using time as a filter

### ISSUE THREAD

**Issue by SPuerBRead** [ecederstrand/exchangelib#529]
Hello 
When I use all(), I can get all the data,but when I use time to filter, no data available.
Use the following code

```
tz = EWSTimeZone.localzone()

print(len(account.inbox.all()))

a = account.inbox.filter(end__gt=account.default_timezone.localize(EWSDateTime(2017, 11, 1, 8, 30)),start__lt=account.default_timezone.localize((EWSDateTime.now())))
print(len(a))

b = account.inbox.filter(end__gt=tz.localize(EWSDateTime(2017, 11, 1, 8, 30)),start__lt=tz.localize((EWSDateTime.now())))
print(len(b))
```
The output results are 200  0  0 , but there is data in this period of time, I don't know why I can't get it

**Comment by SPuerBRead** [comment]
@ecederstrand sorry,I didn't see this. I thought I could get mail in time directly through this. :joy:Thank you.

**Comment by ecederstrand** [comment]
If you want to filter messages by date, you can use one of the timestamp fields on Message items: https://github.com/ecederstrand/exchangelib#message-timestamp-fields
