### ISSUE TITLE
Extract Message from FileAttachment?

### ISSUE THREAD

**Issue by bmullen-steelcase** [ecederstrand/exchangelib#53]
I'm noticing when I pull emails from the server, not all of the conversation is always available in the message body.  However, when there is content missing, it's typically available in the attachments as a message.  How can I access the message functions when it's in a FileAttachment?

Looking at the FileAttachment content looks something like this:
`FileAttachment(Message(is_response_requested=False, is_read_receipt_requested=False, is_delivery_receipt_requested=False, is_read=True, sender=...`

**Comment by ecederstrand** [comment]
That's strange. Are you sure the attachment is not an `ItemAttachment`? `FileAttachment` has its binary content in the `content` attribute while `ItemAttachment` has the item in the `item` attribute.

**Comment by bmullen-steelcase** [comment]
Here's the code.  Emails are on a transitional MS Exchange / Office 365 environment.  Since I can't seem to penetrate the attachments to get the text, I'm simply printing the attachment object itself.  The emails I'm pulling have been moved to a folder called "COMPLETED EMAILS".  What can I do to help troubleshoot?

```
def processCompleted():
    folder = account.root.get_folder_by_name('COMPLETED EMAILS')
    tz = EWSTimeZone.timezone('US/Eastern')
    
    for idx, message in enumerate(folder.filter(datetime_received__gt=tz.localize(EWSDateTime(2016, 12, 12)))):
        if len(message.attachments) == 0:
            continue
        for attachment in message.attachments:
            print(attachment)
            break

        break
```

**Comment by ecederstrand** [comment]
Try this:

```python
from exchangelib.folders import ItemAttachment, FileAttachment

def processCompleted():
    folder = account.root.get_folder_by_name('COMPLETED EMAILS')
    tz = EWSTimeZone.timezone('US/Eastern')
    items = folder.filter(datetime_received__gt=tz.localize(EWSDateTime(2016, 12, 12)))
    for idx, message in enumerate(items):
        for attachment in message.attachments:
            if isinstance(attachment, ItemAttachment):
                # Print the attached EWS item, which can be a CalendarItem, a Message, etc
                print(idx, attachment.item)
                continue
            if isinstance(attachment, FileAttachment):
                # Print the contents of the attached file
                print(idx, attachment.content)
                continue
            raise ValueError('Unknown attachment type: %s' % attachment)
```

**Comment by bmullen-steelcase** [comment]
It seems like the FileAttachment contains a Message with image attachments.  Your code seems to pull the images from the nested attachments, but doesn't get the text.  I'm attaching a chunk of text from running print(attachment) to hopefully show what I'm saying.  I've gone through and replaced some of the sensitive information with 'XXXXX'
[attachment.txt](https://github.com/ecederstrand/exchangelib/files/661471/attachment.txt)

**Comment by ecederstrand** [comment]
I think you're just getting confused by the very verbose `__str__` output. What you're seeing as the first part of your output is the `parent_item` attribute which is a reference to the `Message` holding the attachment. Try the code I posted and you should get the contents of the `FileAttachment` when you access `attachment.content`.

**Comment by bmullen-steelcase** [comment]
I understand what you're saying.  Here's a better example.  When I view message.body on the attached message, I get the text from two emails.  If you read the raw data from the __str__ output on the message, you see there are actually three emails in the conversation.  The first email in the conversation doesn't come through in the message.body.

[attachment2.txt](https://github.com/ecederstrand/exchangelib/files/661711/attachment2.txt)
