### ISSUE TITLE
MeetingRequest is not exported

### ISSUE THREAD

**Issue by viking** [ecederstrand/exchangelib#531]
The MeetingRequest class is not exported in the exchangelib module. Is this intentional? The README refers to it, and I'm seeing MeetingRequest objects when I iterate over mailbox items. I tried to use `isinstance(item, MeetingRequest)` but discovered that the class is not exported.

**Comment by ecederstrand** [comment]
I'm not sure what you mean by "exported". The class can be imported as `from exchangelib.items import MeetingRequest`.

**Comment by viking** [comment]
Ah, I thought all objects were meant to be imported from exchangelib proper. The `Message` class is on the top level module, so I assumed that `MeetingRequest` would be as well.

**Comment by ecederstrand** [comment]
The most common classes have shortcuts directly under `exchangelib.*`. There's no hard rule about when shortcuts get added there, but I'll make sure to update the docs.

**Comment by viking** [comment]
Great, thanks for clarifying.
