### ISSUE TITLE
EWSDateTime.fromtimestamp returns datetime object

### ISSUE THREAD

**Issue by noonedeadpunk** [ecederstrand/exchangelib#532]
Hi,

For some reason, EWSDateTime.fromtimestamp() returns bare datetime object, if tz is passed as an argument. For this reason, when I want to get data from timestamp, I have to build pretty weired construction (the last one):
```
>>> from exchangelib import EWSTimeZone, EWSDateTime
>>> timezone = EWSTimeZone.timezone("UTC")
>>> timezone.localize(EWSDateTime.fromtimestamp(1547258400))
EWSDateTime(2019, 1, 12, 4, 0, tzinfo=<UTC>)
>>> EWSDateTime.fromtimestamp(1547258400, tz=timezone)
datetime.datetime(2019, 1, 12, 2, 0, tzinfo=<UTC>)
>>> EWSDateTime.from_datetime(EWSDateTime.fromtimestamp(1547258400, tz=timezone))
EWSDateTime(2019, 1, 12, 2, 0, tzinfo=<UTC>)
>>>	
```
So it would be pretty nice, if EWSDateTime always return EWSDateTime object.
Using exchangelib 1.12.1 with Python 3.6.7

**Comment by ecederstrand** [comment]
Thanks for the report! This must be done on a per-method basis. I have fixed `fromtimestamp`, `utcfromtimestamp` and `utcnow` for now.
