### ISSUE TITLE
Handling Proxy with Authentication

### ISSUE THREAD

**Issue by guptasakshi01** [ecederstrand/exchangelib#534]
Module exchangelib==1.10.5

Proxy is configured in our environment with username and password.
while connecting to server using exchangelib module we need to use proxy with authentication.

What steps needs to be followed to handle proxy with username and password.

Please help.

**Comment by ecederstrand** [comment]
We purposely do not add any special proxy handling in exchangelib. You should use HTTP transport adapters from the `requests` package to solve your needs, and any username and pawwrods handling will need to be solved using the methods provided by that package. See https://github.com/ecederstrand/exchangelib#proxies-and-custom-tls-validation

**Comment by guptasakshi01** [comment]
@ecederstrand  Thanks for help

We are able to do it as below:
`
class ProxyAdapter(requests.adapters.HTTPAdapter):
    def send(self, *args, **kwargs):
        kwargs['proxies'] = {
            'http': 'http://username:password@10.0.0.1:1243',
            'https': 'https://username:password@10.0.0.1:4321',
        }
        return super(ProxyAdapter, self).send(*args, **kwargs)

BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter
`
