### ISSUE TITLE
Unable to retrieve attachments

### ISSUE THREAD

**Issue by hari6963** [ecederstrand/exchangelib#536]
Hi,

I am trying to retrieving attachments using the .attachments and not able to. I am able to get the email without any issues. Any ideas?

Here is the relevant code snippet - 

```python
for msg in account.inbox.filter(datetime_received__gt=emails_since, is_read=False) \
                   .only('datetime_received', 'subject', 'text_body') \
                   .order_by('datetime_received')[:10]:
    # Extract attachments
    for attachment in msg.attachments:
        print(attachment.name)
```

Thanks
Hari

**Comment by hari6963** [comment]
Hi Erik,

I am not getting any errors. Email has 2 zip file as attachments. Upon scanning the inbox based on the subject, its able to recognize the email. Do I need to open the email perhaps, similar to a file open? Here is the code - 

for msg in account.inbox.filter(datetime_received__gt=emails_since, is_read=False).only('datetime_received', 'subject', 'text_body').order_by('datetime_received')[:10]:

	if msg.subject == 'custom subject':
		print(msg.attachments) # This line prints an empty array []

Thanks
Hari

**Comment by ecederstrand** [comment]
Maybe the attachments are provided inline in the MIME body content, and not as an Exchange attachment? You could look for attachments in `item.mime_content`.

I haven't checked, but it's possible that attachments are only available in `item.attachments` if the email was sent using an Exchange client.

**Comment by hari6963** [comment]
Hi Erik,

I was able to resolve this issue by removing the .only call which was restricting the fields being retrieved.

Thanks
Hari

**Comment by ecederstrand** [comment]
Ah yes, of course. I hadn't noticed that. If can also add `attachments` to `.only()` if you still want to restrict the number of fields to fetch.
