### ISSUE TITLE
Setting Proxy Dynamically

### ISSUE THREAD

**Issue by guptasakshi01** [ecederstrand/exchangelib#537]
Hi I want to call that ProxyAdapter class sending proxy dynamically to function.
How Can I achieve it ?

Example:
```python
class ProxyAdapter(requests.adapters.HTTPAdapter):
    '''
    Setting Proxy
    '''
    def send(self, *args, **kwargs):
        kwargs['proxies'] = urllib.getproxies()
        return super(ProxyAdapter, self).send(*args, **kwargs)
```
Say:
`BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter(Proxy)`

Can you please help how can i achieve this ?

**Comment by ecederstrand** [comment]
This isn't really related to exchangelib, but I'll try to answer anyway.

`BaseProtocol.HTTP_ADAPTER_CLS` expects a class, not a class instance, so you can't do `ProxyAdapter('Proxy')`. Calling a class invokes `__new__` which returns a class instance. You could do something fancy with Python metaclasses, but that's probably overkill for this purpose.

If you only need to configure one proxy globally, you can set a class instance dynamically (note that `BaseProtocol.HTTP_ADAPTER_CLS` is also a global setting):

```python
class ProxyAdapter(requests.adapters.HTTPAdapter):
    PROXIES = None
    def send(self, *args, **kwargs):
        kwargs['proxies'] = self.PROXIES
        return super(ProxyAdapter, self).send(*args, **kwargs)

ProxyAdapter.PROXIES = ['http://example.com']
BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter
```

If you need to chose the proxy on a per-server basis, I would add some logic in `send()` to pick the right proxy depending on the server:

```python
class ProxyAdapter(requests.adapters.HTTPAdapter):
    def send(self, request, *args, **kwargs):
        if request.url == 'http://example.com':
            kwargs['proxies'] = 'http://proxy.example.com'
        else:
            ...
        return super(ProxyAdapter, self).send(*args, **kwargs)

BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter
```

**Comment by guptasakshi01** [comment]
Thanks @ecederstrand 

Is there any other way we can handle proxy for exchangelib apart from HTTP_ADAPTER_CLS ?

**Comment by ecederstrand** [comment]
No. The `BaseProtocol.HTTP_ADAPTER_CLS = MyCustomAdapter` solution is supposed to be sufficient to handle all the custom HTTP protocol handling you need.

**Comment by guptasakshi01** [comment]
Thanks @ecederstrand 

```
ProxyAdapter.PROXIES = {'http':'http://example.com'}
BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter
```
This helped

**Comment by ecederstrand** [comment]
Thanks. I've updated the example.
