### ISSUE TITLE
Error : Item type on RecoverableItemsPurges (Purges)

### ISSUE THREAD

**Issue by nakasix** [ecederstrand/exchangelib#538]
Hello,

I'm trying to retrieve items in the purge's folder with a script, but I get the following error with the "all()" function : 

> Error : Item type {http://schemas.microsoft.com/exchange/services/2006/types}Item was unexpected in a Folder folder

In this document, the type exist : https://msdn.microsoft.com/en-us/library/hh354700(v=exchg.80).aspx, so is it possible to get all items of "RecoverableItemsPurges (Purges)" to move to another folder ?

Thank you,
Regards,

**Comment by ecederstrand** [comment]
Can you try to add the `Item` class to this list?: https://github.com/ecederstrand/exchangelib/blob/e6f11df8fd000cd84452ce2414695037f2c6e401/exchangelib/items.py#L1344

**Comment by nakasix** [comment]
It Works !

Thank you,

**Comment by ecederstrand** [comment]
Reopening to get this fixed in the source code
