### ISSUE TITLE
Do Not Forward Permission

### ISSUE THREAD

**Issue by GeethaThangavel** [ecederstrand/exchangelib#540]
How to set Do Not Forward permission while sending an email using exchangelib?

**Comment by ecederstrand** [comment]
I haven't heard about that feature before. Do you have any documentation on it?

**Comment by GeethaThangavel** [comment]
We require to send some sensitive information in the email message for which need to set permission level as "Do not forward" which is available as IRM (Information Rights Management) integration in exchange server. Please suggest if there is any option available for this,

**Comment by ecederstrand** [comment]
According to https://stackoverflow.com/questions/37131242/is-it-possible-to-access-and-set-an-emails-information-rights-management-using-e it seems you can set the flag via EWS as an extended property (https://stackoverflow.com/questions/36067768/how-to-set-access-outlook-donotforward-property-in-microsoft-exchange-service has information about the magic variables), but you must do the client-side encryption yourself.

See https://github.com/ecederstrand/exchangelib#extended-properties on how to work with extended properties in exchangelib.

**Comment by GeethaThangavel** [comment]
Thanks for the details, We have gone through the link https://github.com/ecederstrand/exchangelib#extended-properties .
and understood the procedure to set extended properties.

Tried to set as below

class ForwardAllowed(ExtendedProperty):
    property_tag = 0x6673
    property_type = 'Boolean'

Using the property_tag value, additional attributes are set.
But couldn't find exact property tag/uuid for "ForwardAllowed" attribute in the link (https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/forwardallowed).

It will very helpful if you share the details.

**Comment by ecederstrand** [comment]
I'm not sure I can help you more. https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/rightsmanagementlicensedata mentions that it is a child element of the Message element, but https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/message-ex15websvcsotherref doesn't mention it at all. So it seems the EWS docs are inconsistent. exchangelib doesn't support the field on items.

https://stackoverflow.com/a/36075827/219640 and the links contained there suggests that you have to construct a magic verb using some arcane, binary MS format as the payload for the extended property. There are some hints how to do that at https://github.com/ecederstrand/exchangelib/issues/198#issuecomment-327087222 but it's too time consuming for me to provide you with a full example.

By looking at line 153 in the script in https://gsexdev.blogspot.com/2014/09/sending-noreply-noreplyall-noforward.html it seems a definition for the extended property used there would be:

```python
class PidLidVerbStream(ExtendedProperty):
    distinguished_property_set_id = 'Common'
    property_id = 0x8520
    property_type = 'Binary'
```

**Comment by ecederstrand** [comment]
I'm closing because I think all the building blocks are available in exchangelib, and because I don't see us adding helpers to create arcane binary payloads for custom functionality.

I did a quick test to support the `item:RightsManagementLicenseData` but my test servers do not return anything when I request this field, not even an empty XML element, so I assume it's not actually implemented in EWS.

Feel free to reopen if you want to improve support in this area.

**Comment by guptasakshi01** [comment]
@GeethaThangavel 

were you be able to achieve Do Not Forward using exchangelib ?
