### ISSUE TITLE
Retrieving Fields/Properties of an Outlook Custom Form

### ISSUE THREAD

**Issue by Centanium** [ecederstrand/exchangelib#542]
Hello,

Currently I am trying to use my Python script in order to retrieve fields from my custom task object and both write to a log file as well as insert into a database using pyodbc. But when I look for the fields I have created in outlook for my custom form, I cant seem to find where it is. And i've looked into extended properties, but I either don't understand it well enough or it isn't exactly what im looking for.

Is there something im missing for this or is it just something that isn't really possible yet?

[Final Python Script.txt](https://github.com/ecederstrand/exchangelib/files/2742071/Final.Python.Script.txt)

**Comment by ecederstrand** [comment]
It's very likely that your custom form is implemented using an extended property.

Extended properties are an absolute pain to work with, but there is some guidance at https://github.com/ecederstrand/exchangelib#extended-properties. Unfortunately, you have to know beforehand which extended properties you are looking for.

**Comment by Centanium** [comment]
Actually, although i've been dealing with this script for 2 days now, I just figured it out not even 10 minutes ago, but thank you very much for your quick response and you are definitely right, they are a pain to deal with! :) Thank you.

**Comment by Centanium** [comment]
So this is just for anyone has a similar problem and wants some specific direction:

For example if I had a custom form field with the name 'WO Number' that I wanted to access to:

`
#I would create the class
class WONumber(ExtendedProperty):
    distinguished_property_set_id = 'PublicStrings' #set this as the ID
    property_name = 'WO Number'                        #this is field within outlook already created
    property_type = 'String'                                     #this is its datatype

#I would then register it as 'WONumber' being the name I now use to call item.WONumber 
#and I would use WONumber as the name of the class I just created earlier
Task.register('WONumber', WONumber)
`
I can now go on to use item.WONumber and it will pull from the outlook form.

It was a pain to figure that out, but now its going to make my life a lot simpler.
