### ISSUE TITLE
How to customize the sender

### ISSUE THREAD

**Issue by hari6963** [ecederstrand/exchangelib#544]
Hi

How do I customize the sender information when sending the email? I would like to specify a custom name instead of the account. 

Thanks
Hari

**Comment by hari6963** [comment]
Thanks Erik. Any idea how to set a custom name along with the email id? I was able to do this using smtplib by setting the sender as "Custom Name <abc@xyz.com>".

**Comment by hari6963** [comment]
I tried using the below but it seems to ignore the name value being passed and sends the email using the name of the email account. In other words, email comes with the name as "First Last" as opposed to "Custom Name". This works with smtplib. 

m = Message(account=account, subject=emailSubject, body=msgBody, to_recipients=emailTo, author=Mailbox(name='Custom Name', email_address='first.last@emailhost.com'))

**Comment by ecederstrand** [comment]
I'm not sure that is possible with EWS. Either EWS changes the custom name back to the default, or EWS email clients display the default name no matter what. I have found these SO questions with no answer:

https://stackoverflow.com/questions/10584708/using-custom-display-name-when-sending-email-through-ews and 
https://stackoverflow.com/questions/19784954/mailmessage-setting-the-sender-name-ews

**Comment by ecederstrand** [comment]
Closing since my searching suggests it's not possible with EWS. Feel free to reopen if you find a solution.

**Comment by ecederstrand** [comment]
No. I still don’t think it’s supported by EWS.

**Comment by sumoncuet** [comment]
@ecederstrand , did you get any solution for custom sender? I also want to customize the display name but failed. 
![image](https://user-images.githubusercontent.com/1089392/118436063-ea60e100-b701-11eb-8d5f-6c5906246a01.png)

**Comment by ecederstrand** [comment]
No. I still don’t think it’s supported by EWS.

**Comment by sumoncuet** [comment]
Can you try with the following url

https://ezcloudinfo.com/2014/07/30/modifying-system-generated-mailbox-in-exchange-2013/

**Comment by ecederstrand** [comment]
That article describes some PowerShell commands. I don’t see anything related to EWS which is the API that exchangelib uses.
