### ISSUE TITLE
is_online_meeting

### ISSUE THREAD

**Issue by davidedironza** [ecederstrand/exchangelib#546]
Hi all

I'm trying to use the "is_online_meeting" item. But what exactly is this item doing?
Is it adding the Skype Online Meeting informations to the calendar to join the meeting via skype?

If I set it to True i can't see what happens in the invitation. No Skype Meeting visible.

My Code:

```python
calendaritem = CalendarItem(
        ...
        is_online_meeting = True,
        ...
   )
```
Our Exchange Version:
`Version(Build(14, 3, 361, 1), 'Exchange2010_SP2')`

**Comment by ecederstrand** [comment]
The documentation for all fields are available in EWS. Each class has a link to the docs in their docstring:

```python
>>> from exchangelib import CalendarItem
>>> print(CalendarItem.__doc__)

    MSDN: https://msdn.microsoft.com/en-us/library/office/aa564765(v=exchg.150).aspx
```

From there, you can click through to the documentation for the `IsOnlineMeeting` field.

In exchangelib, the field is marked as read-only (see https://github.com/ecederstrand/exchangelib/blob/794ccdc36777cc1fe3101885eadf49ed9ffb8a90/exchangelib/items.py#L569) which means you can't set or update the value. It's supposedly possible to set or update it in some circumstances, but I never got it to work in my tests when implementing the field.

**Comment by davidedironza** [comment]
Thanks.
I read the documentation but for me it was not really clear what the output should be. So whether it refers to a Skype Meeting or something else.
I'm expecting that it adds the Skype Link, but it doesn't.
So you mean that the read-only doesn't show any output on the invitation and if we can update it to is_read_only=False something should be shown?

**Comment by ecederstrand** [comment]
Hi @davidedironza 

Did you find a solution to this problem?

**Comment by ecederstrand** [comment]
Closing, as I think this question should be directed at the EWS developers, not this project. Feel free to reopen if you think otherwise.
