### ISSUE TITLE
Unable to Access account.sent, account.msg_folder_root.tree as Delegate

### ISSUE THREAD

**Issue by nstr10** [ecederstrand/exchangelib#548]
I am attempting to add automated replies to my project using exchangelib 1.12.0 but am receiving the following error:

```[EWS] Processing new mail [REDACTED]  <-- this means it's reading the inbox fine
[EWS] Failed to send response to client [REDACTED]!  <-- and parsing the message
The specified object was not found in the store.  <-- just not finding the sent folder
[EWS] Error processing mail [REDACTED]
Traceback (most recent call last):
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/cached_property.py", line 50, in __get__
    return obj_dict[name]
KeyError: 'sent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/EWS.py", line 233, in process_new_mail
    reply.send()
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/items.py", line 1254, in send
    res = self.account.bulk_create(items=[self], folder=copy_to_folder, message_disposition=message_disposition)
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/account.py", line 387, in bulk_create
    folder = self.sent  # 'Sent' is default EWS behaviour
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/account.py", line 258, in sent
    return self.root.get_default_folder(SentItems)
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/folders.py", line 1632, in get_default_folder
    return super(Root, self).get_default_folder(folder_cls)
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/folders.py", line 1500, in get_default_folder
    return folder_cls.get_distinguished(root=self)
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/folders.py", line 845, in get_distinguished
    raise folder
  File "/path/to/python/3.4.7/lib/python3.4/site-packages/exchangelib/services.py", line 287, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorItemNotFound: The specified object was not found in the store.
```

I get the same traceback trying to run `account.msg_folder_root.tree()` or access `account.sent` directly, and `account.root.tree()` output is just `root` for some reason. I'm kind of stabbing at straws in the dark.

The `reply` object being sent was generated using the `create_reply()` method of a message from the inbox.

I tested that I am able to reply to the same message as the delegate user from OWA so I don't think it's a permissions issue.

Sorry in advance if I've again done something silly!

**Comment by ecederstrand** [comment]
You are correct that the direct problem is that we cannot look up the `sent` folder.

`account.root.tree()` returning only the `root` folder is an indication that you do not have proper permissions to the mailbox you are connecting to. If you turn on debug logging, you will probably see a lot of `ErrorItemNotFound` or `ErrorAccessDenied` elements in the response XML.

You didn't post the code that produced this error, but you could try setting a different `auth_type`, or check permissions with your Exchange admin if you are connecting to a different account than your own.

**Comment by nstr10** [comment]
I double checked and the service user is set up with delegated full access rights on the mailbox. I'll see if my Exchange admin will set up a couple of different accounts for me to test whether this issue is isolated to delegate access, or is perhaps something wrong with the account in question.

I am using `NTLM` auth as I have done for years with this library - would the auth protocol potentially affect this if the issue is not auth failure?

The code is not much different from #504 but I've included it below for reference.

```python3
from exchangelib import Configuration, Account, Credentials, DELEGATE, ... NTLM, services
from config import mailbox, server, domain, username, password

self.account = Account(
  primary_smtp_address = mailbox,
  config = Configuration(
    server = server,
    credentials = Credentials(
      username = "{0}\{1}".format(domain, username),
      password = password
    ),
    auth_type = NTLM
  ),
  access_type=DELEGATE
)
start_date, end_date = # boring code removed
items = account.inbox.filter(datetime_received__range=(start_date, end_date)).values('id').iterator()
for item in items:
  full_email = account.inbox.get(id=item["id"])
  reply = full_email.create_reply("Test Reply", "This is some text.")
  reply.send()
```

**Comment by ecederstrand** [comment]
I don't mind the issue being open for now. Just remember to update with your findings so others can benefit, and feel free to close the issue if it's not a problem with exchangelib.

**Comment by nstr10** [comment]
Created a second account with same permissions and had no problem.

Switched back to the original account and had no problem.

Not sure what the cause was exactly, but it seems like this was in fact a permissions issue.
