### ISSUE TITLE
the calendar item didn't show up in attendee's calendar

### ISSUE THREAD

**Issue by ramwin** [ecederstrand/exchangelib#55]
Dear, author, now I'm using the exchangelib to create a multi-user event.  
After creating the calendar item, the item shows up in the sender's calendar. But the calendar item doesn't show up in the receivers's calendar.  
The receiver's mailbox is in the sender's calendar with no response . But the receiver didn't receive any calendar or email.
Here is my code:
```
required_attendees = account.calendar.all()[0].required_attendees
attendee = required_attendees[0]
print(require_attendees) # [Attendee(Mailbox('username', 'username@example.com', 'Mailbox', None), 'Unknown', None)]
organizer = account.calendar.all()[0].organizer
print(organizer) # Mailbox('sender', 'sender@example.com', 'Mailbox', 'None)
calendaritem = CalendarItem(
        start=tz.localize(EWSDateTime(year, month, day, hour, 30)),
        end=tz.localize(EWSDateTime(year, month, day, hour + 1, 15)),
        subject='Test item',
        body='Hello from Python',
        location='devnull',
        # categories=['foo', 'bar'],
        account = account,
        folder = account.calendar,
        organizer = organizer,
        # required_attendees = required_attendees
        required_attendees = [attendee],
    )
calendaritem.save()
```
I also tried to change the response_type to other values of `attendee.RESPONSE_TYPES` and save the item again. But none of them show up in the receiver's calendar.  
I know that you are inconvenient to test the Meeting invitations and required/optional attendees. I'm glab to assistance you as far as possible. I'm looking forward to your reply.

**Comment by ecederstrand** [comment]
Can you enable `DEBUG` logging and check if the `required_attendees` data is present in the `CreateItem` XML? That would be a first sanity check.

I'm not sure how Exchange works with meeting invitations. Is it possible that `username@example.com` needs to acknowledge a meeting request before he/she appears on the calendar item? `.save()` has an optional `send_meeting_invitations` attribute that can be any one of `SEND_TO_NONE, SEND_ONLY_TO_ALL, SEND_TO_ALL_AND_SAVE_COPY`. Default is `SEND_TO_NONE`

**Comment by ramwin** [comment]
Sorry for ask this question. I only followed the code from `README.rst`, and found it didn't work. Your answer reminds me to view your source code and then ask any question.

**Comment by ecederstrand** [comment]
No problem. Did you find a solution? I'm happy to update the `README` if it is incorrect.

**Comment by ramwin** [comment]
Yes, it worked. And I'm trying to enrich the reference. [ Here is my rough code.](https://github.com/ramwin/python_tutorial/blob/master/exchangelib.md)
