### ISSUE TITLE
Request More Info: Folder Usage

### ISSUE THREAD

**Issue by jerodg** [ecederstrand/exchangelib#550]
The documentation for wellknown folders is fairly straightforward, however, accessing named folders isn't very clear.

e.g. some_folder.root How is this accessed? Is it under account?
You have a lot of examples for what you can do with the folder but there isn't a declaration for 'some_folder'. Not sure how to instantiate the folder object for an existing custom folder.

```
root
├── inbox
├── Top of Information Store
│   ├── My Custom Folder
```

How do I retrieve items from 'My Custom Folder'?

**Comment by ecederstrand** [comment]
Folder navigation uses the syntax of the built-in `pathlib` module from Python. It's documented here: https://github.com/ecederstrand/exchangelib#folders

In your example, it would be:

```python
my_custom_folder = account.root / 'Top of Information Store' / 'My Custom Folder'
for i in my_custom_folder.all():
    print(i)
```

Feel free to contribute improvements to the documentation if you think this could be described more clearly :-)

**Comment by jerodg** [comment]
Perfect; thanks.

The my_custom_folder = account.root / 'Top of Information Store' / 'My Custom Folder'
part threw me off, haven't seen that syntax before.
