### ISSUE TITLE
send_and_save() does not save email

### ISSUE THREAD

**Issue by fpeterson194** [ecederstrand/exchangelib#558]
Hi everyone!

I was successfully able to send emails with several attachments. Now, I just want to have a copy of the email I sent. I tried different ways to do it:

- m.send_and_save()
- m.send(save_copy=True, copy_to_folder=a.sent)
- defining "folder" or comment it in the Message (see below)
- try to use m.copy(a.sent) but I get an error saying "Message must have an ID"
- Use save() and then send() separately. The issue of doing this is that I split emails that has more than 100 attachments. So let´s say I have 150 emails to send as attachments to a particular sender, then I make 2 emails, one with 100 and other with 50. The first one is sent and save properly, however, the second one write the same email with 150, instead of 2 separate emails (this is documented in the README as follows: "item.save()  # When the items has an item_id, this will update the item")

I defined m as follows:
m = Message(
	account=a,
	folder=a.sent,
	author='sender@mydomain.com',
	subject='Subject Here',
	body=notification_body,
	to_recipients=  # User mail
)

Any ideas how to sort this issue? My goal: Have a copy of the email in a folder I want.
Thanks in advance!!

**Comment by ecederstrand** [comment]
I just tried this:

```python
from exchangelib import Credentials, Account, Message
username, password = 'john@example.com', 'SECRET'
c = Credentials(username, password)
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)
Message(
    folder=a.sent,
    subject='send_and_save() test',
    to_recipients=[username]
).send_and_save()
```

And I immediately get an email in my inbox and a copy in my sent folder.

If you are on Exchange 2007, we have to fake the send_and_save() implementation because it doesn't work there: https://github.com/ecederstrand/exchangelib/blob/478f47128462245391e5c2825fc53205f0dcb5c5/exchangelib/items.py#L720

Regarding your last point, if you want an entirely new email, you have to create a new `Message` instance for each batch of attachments you send.

**Comment by fpeterson194** [comment]
@ecederstrand thanks for your prompt response! I´m using Exchange 2010/2013. I tried to do the same simple test you made and I can´t get a copy in my Sent folder (Inbox works).
I enable debug and this is the output:

```
DEBUG:exchangelib.util:Session 12906 thread 7288: Useful response from XXX
DEBUG:exchangelib.protocol:Server XXX: Releasing session 12906
DEBUG:exchangelib.account:Adding items for sender1@mydomain.com (folder SentItems (Sent Items), message_disposition: SendAndSaveCopy, send_meeting_invitations: SendToNone)
DEBUG:exchangelib.services:Processing items in chunks of 100
DEBUG:exchangelib.services:Starting CreateItem._get_elements worker 1 for 1 items
DEBUG:exchangelib.services:Waiting for CreateItem._get_elements result 1 of 1
DEBUG:exchangelib.services:Adding item Message(subject='test-send-and-save', attachments=[], to_recipients=['recipient@mydomain.com'], author='someone@mydomain.com')
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account sender1@mydomain.com
DEBUG:exchangelib.protocol:Server XXX: Waiting for session
DEBUG:exchangelib.protocol:Server XXX: Got session 12906
DEBUG:exchangelib.util:Session 12906 thread 11228: retry 0 timeout 120 POST'ing to XXX after 10s wait
DEBUG:urllib3.connectionpool:XXX "POST /EWS/Exchange.asmx HTTP/1.1" 200 None
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 12906
Thread: 11228
```

**Comment by ecederstrand** [comment]
That seems like a bug in your version of the EWS service. If you enable XML pretty-printing (see https://github.com/ecederstrand/exchangelib#troubleshooting), you should be able to see the request XML of the `CreateItem` service call containing a message disposition element containing `SendAndSaveCopy` and a `SavedItemFolderId` element pointing to your sent folder.

**Comment by fpeterson194** [comment]
I enabled debug. The response does not show an error as far as I see. Let me share it with you. Is this a bug then?

**Request**
```
<s:Body>
<m:CreateItem MessageDisposition="SendAndSaveCopy" SendMeetingInvitations="SendToNone">
	<m:SavedItemFolderId>
		<t:DistinguishedFolderId Id="sentitems">
			<t:Mailbox>
				<t:EmailAddress>sender@mydomain.com</t:EmailAddress>
				<t:RoutingType>SMTP</t:RoutingType>
				<t:MailboxType>Mailbox</t:MailboxType>
			</t:Mailbox>
		</t:DistinguishedFolderId>
	</m:SavedItemFolderId>
	<m:Items>
		<t:Message>
		<t:Subject>test-send-and-save</t:Subject>
		<t:Sensitivity>Normal</t:Sensitivity>
		<t:Importance>Normal</t:Importance>
		<t:ReminderIsSet>0</t:ReminderIsSet>
		<t:ReminderMinutesBeforeStart>0</t:ReminderMinutesBeforeStart>
		<t:ToRecipients>
			<t:Mailbox>
				<t:EmailAddress>recipient@mydomain.com</t:EmailAddress>
				<t:RoutingType>SMTP</t:RoutingType>
				<t:MailboxType>Mailbox</t:MailboxType>
			</t:Mailbox>
			</t:ToRecipients>
			<t:IsReadReceiptRequested>0</t:IsReadReceiptRequested>
			<t:IsDeliveryReceiptRequested>0</t:IsDeliveryReceiptRequested>
			<t:From>
				<t:Mailbox>
					<t:EmailAddress>sender@mydomain.com</t:EmailAddress>
					<t:RoutingType>SMTP</t:RoutingType>
					<t:MailboxType>Mailbox</t:MailboxType>
				</t:Mailbox>
			</t:From>
			<t:IsRead>0</t:IsRead>
			<t:IsResponseRequested>0</t:IsResponseRequested>
		</t:Message>
	</m:Items>
</m:CreateItem>
</s:Body>
```
**Response**
```
<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<m:CreateItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
	<m:ResponseMessages>
		<m:CreateItemResponseMessage ResponseClass="Success">
			<m:ResponseCode>NoError</m:ResponseCode>
			<m:Items/>
		</m:CreateItemResponseMessage>
	</m:ResponseMessages>
</m:CreateItemResponse>
</s:Body>
```

**Comment by ecederstrand** [comment]
Yes, I think this is a bug in your EWS version. The request clearly states to save a copy in the `sentitems` folder, but instead, the item is saved to your inbox.

As a workaround, I would first `save()` each message to the `account.sent` folder, and then `send()` it.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you are stuck and need more help.

**Comment by fpeterson194** [comment]
@ecederstrand sorry for the delay in response. I tried to make save() + send() and it works. However, when I put a limit in the amount of emails attached (100 in my case) it fails with this error:

> Exception has occurred: exceptions.AttributeError
> Folder must be supplied when in save-only mode
>   File "<myScriptPathHere>", line 195, in <module>

Based on your documentation, save() return an item_id that send doesn´t return. In addition, I tried to supply a folder within save () but it doesn´t work neither.

Let´s put an example: Let´s say I have to distribute 250 emails to a sender. In this case, I will make 3 emails: 1 with 100, another with 100 and the last one with 50. If I use save() and then send(), first email will work like a charm (I need to put a timer between them due to race conditions, but it works), then second email will give me this error that cannot save the email. Finally, I user received one email with 100 attachments and I have a copy of it in the Sent. The rest of the 2 emails are not sent and save in Sent folder.

My code with the save, is the following:

```
# Build email notification
m = Message(
	account=a,
	folder=a.sent,
	author='sender@mydomain.com',
	subject='Email Subject',
	body=notification_body, # HTML Template
	to_recipients= # User mail
)

# Attach emails
		
# Maximun number of attachments
maximumAttachEmails = 100
# Amount of emails to be sent
amountOfSplits = int(len(emails)/maximumAttachEmails) + (len(emails) % maximumAttachEmails >0)
# Current email part sent
currentEmailPart = 1
# Total number of emails processed
numberOfAttachEmails = 0
for email in emails:
	numberOfAttachEmails += 1
	email.message_id = None
	m.attach(ItemAttachment(name=email.subject, item=email))
	if (len(m.attachments) == maximumAttachEmails or numberOfAttachEmails == len(emails)): 
		loggerStdOut.info(u'\t Sending mail...')
		# Save and Send email
		m.subject = "Email Subject - Part " + str(currentEmailPart) + "/" + str(amountOfSplits)
		m.save()
		time.sleep(0.1) # Due to race conditions between save() and send()
		m.send()
		loggerToFile.info(u'\t Sent to: '+ str(user) + ' part '+ str(currentEmailPart)+"/" + str(amountOfSplits))
		# Move emails to proper folder
		#for attachment in m.attachments:
		#	moveEmailToFolder(attachment.item, processedEmailsFolder)
		m.attachments = [] # Clear attachments
		currentEmailPart += 1
```
```
def moveEmailToFolder(email, folder):
	try:
		email.move(folder)
		loggerToFile.info(u'\t email: '+ email.subject + ' was moved')
	except: 
		loggerToFile.info(u'\t Could not move: ' + email.subject )
```
Last question here: If I enable the "moveEmailToFolder" as it is in the for loop, I get a "item_id" issue with the save. Maybe is better to move emails after all the parts were already sent, right? The reason why I wanted to do it there is because then I do "m.attachments = []" so I lost them to move after the for loop finishes.

Thanks in advance!

**Comment by ecederstrand** [comment]
You are causing yourself a lot of trouble by making only one `Message` object. Instead, you should create one message object for each email you send within the for loop.

Every time you reach `maximumAttachEmails`, you call `m.save()`, `m.send()` and then reset the message with `m = Message(...)`. Just remember to send and save one last time if needed after you exit the for loop.

**Comment by fpeterson194** [comment]
@ecederstrand thanks for the response. Testing now...

**Comment by fpeterson194** [comment]
@ecederstrand works like a charm! Thanks very much for your support!! : D
