### ISSUE TITLE
Establishing a connection...

### ISSUE THREAD

**Issue by pwatts002** [ecederstrand/exchangelib#56]
Hi,

I've been trying to connect to an inbox for a few days but can't diagnose the problem. I appreciate this may not be an issue with your library but I thought I'd ask the question as I think it's an easy one to answer + it might help others.

Can this library connect to an account if it has no available POP / IMAP / SMTP settings prepared? 

(I account can be accessed via OWA as normal.)

I have also wondered if I'm using the correct username 'MYWINDOMAIN\\myusername'. If the username is 'davesmith' and email 'davesmith@company.com' what should be used here?

Any help is much appreciated!
Phil

**Comment by ecederstrand** [comment]
The library can connect to an account if the connecting credentials has access via EWS and is granted access to the user it is trying to connect to (we support delegate and impersonation access to other accounts). It does not touch SMTP, IMAP or POP.

Usually, OWA access implies EWS access, but I'm sure it's possible to disable EWS explicitly.

Whether you log in with a `username@domain.tld` or `WINDOMAIN\username` formatted username is up to the Exchange admin. I assume it will be the same format as your OWA credentials.

If you want to know exactly what is going on, turn on `DEBUG` logging. This will print everything that goes over the wire. If you need more help, please post any specific error messages.

**Comment by pwatts002** [comment]
Hi,

I eventually realised I was getting a 401 connection error so went back to check the WINDOMAIN.

Turns out I'd been told the wrong one! Got it all fixed after that.

Thanks,
Phil
