### ISSUE TITLE
"True" Attachments In Mails

### ISSUE THREAD

**Issue by dispatchai** [ecederstrand/exchangelib#562]
Hi,

This issue of mine is probably not directly related with the exchangelib library itself but maybe someone can help me. I download and save the attachments of mails into varios folders using exchangelib and my problem is that not only the files that are attached to mails but also the embedded images are retrieved in the form of attachments. When I query the same mail on Outlook, such embedded images are not seen as attachments (there is to attach picture  displayed for them), yet the images are retrieved anyway through the library. Is there a way to only look for the "real" file attachments?

**Comment by ecederstrand** [comment]
I'm not sure how to do that. If you look at `Attachment.FIELDS`: https://github.com/ecederstrand/exchangelib/blob/fd1452ca06d5c64a816f2eadcffc9053e30de996/exchangelib/attachments.py#L36 there are a number of extra fields that may help you determine which attachments are interesting for you.

Another possibility is to go through the HTML body of the messages and find references to the attachments that are supposed to be shown in-line, and ignore those.

**Comment by dispatchai** [comment]
Thanks, fields list will be of help for this, I believe.

**Comment by nstr10** [comment]
I believe what you're referring to are inline attachments. Here's how I deal with that using the `is_inline` field:
```python
if hasattr(email_item, "attachments"):
  for attachment in item.attachments:
    if hasattr(attachment, "item"):
      # Do things with attached Exchange items like .eml attachments
    if attachment.is_inline:
      continue # or do something else
```
I believe any attachment that makes it past those checks should be a regular attached file. Hope this helps!

**Comment by ecederstrand** [comment]
Yes, `is_inline` seems like the best solution.

**Comment by adeolaibigbemi** [comment]
Thanks, nstr10. This helped me too.
