### ISSUE TITLE
can't pickle _thread.lock objects 

### ISSUE THREAD

**Issue by SolomonGebreyohannes** [ecederstrand/exchangelib#563]
Am trying to process emails (exchangelib messages) parallely using Python multiprocessing but got "can't pickle _thread.lock objects" error. How to release this lock?

**Comment by SolomonGebreyohannes** [comment]
Installing exchangelib 1.12.2 fix the problem. Now, I get new error: "AttributeError: 'FileAttachment' object has no attribute '__dict__'.

**Comment by ecederstrand** [comment]
Please post some example code that causes this error.

**Comment by SolomonGebreyohannes** [comment]
Sample code ... 
Aim: to process emails parallely 
   def func(emails): 
         do sth  
   # emails = {emailId:email} 
    # emailId: 1 ... 100 for hundred emails 
    # emails: exchangelib message 
    jobs = []
    nthreads = 4      
    jobEach = len(emails)//nthreads 
    firstEmailId = list(emails.keys())[0] 
    lastEmailId  = list(emails.keys())[-1]  
    
    for i in range(nthreads): 
        if i == nthreads - 1: 
            emailIds = [(jobEach*i)+firstEmailId,lastEmailId] 
            emailsProcessor = {emailId:emails[emailId] for emailId in emailIds} 
        else: 
            emailIds = [(jobEach*i)+firstEmailId,(jobEach*(i+1))+firstEmailId]  
            emailsProcessor = {emailId:emails[emailId] for emailId in emailIds}  
            
        p = multiprocessing.Process(target=func, args=(emailsProcessor)) 
        jobs.append(p)
        # print(emailIds)
    for p in jobs:
        p.start()
        
    for p in jobs:
        p.join() 

Error message (not full) : 
   ...
  File "C:\Users\~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\~\AppData\Local\Continuum\anaconda3\lib\site-packages\exchangelib\attachments.py", line 188, in __getstate__
    state = self.__dict__.copy()

AttributeError: 'FileAttachment' object has no attribute '__dict__'

**Comment by ecederstrand** [comment]
The issue happens when the `Message` items are being serialized and de-serialized when they are passed to the processes.

In general with multiprocessing, it's much better to pass around simple strings and integers instead of full objects, and then load the full objects within the process run method. One reason is to avoid trying to pickle something that cannot be pickled. Another reason is to avoid passing potentially huge amounts of data around in IPC channels. For example, attachments can be very large.

In your case, you should query message IDs in your main thread and then fetch the full items in the run method. So, do something like:

```python
from multiprocessing import Pool
pool = Pool(processes=10)
ids = account.inbox.all().values('id', 'changekey')

def worker(item_ids):
    items = account.fetch(item_ids)
    # Do something with the items

pool.map(worker, ids, chunksize=100)
```

That said, it is a bug that attachments cannot be pickled. I have now pushed a fix and added a test for this bug.

**Comment by SolomonGebreyohannes** [comment]
Thanks. Since I don't want all inbox to be fetched, I did this: 

account = ... 
def worker(item_ids):     
    items = account.fetch(item_ids)
    for item in items: 
        print(item.subject) 

if __name__ == '__main__': 
    
    SomeFolder = ...     

    dateToCheck1 = EWSDateTime(2018, 5, 10, 10, 00, 00,0, pytz.UTC) 
    dateToCheck2 = EWSDateTime(2018, 5, 10, 20, 15, 00,0, pytz.UTC)  
    
    pool = Pool(processes=4)
    ids = SomeFolder.filter(datetime_received__range=(dateToCheck1,dateToCheck2)).values('id', 'changekey')[:5] 
         
    pool.map(worker, ids, chunksize=5) 

but throws this error (runs fine with out the multiprocessing): 

... 
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "~\AppData\Local\Continuum\anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

TypeError: unhashable type: 'slice'

**Comment by ecederstrand** [comment]
You may need to materialize the list of IDs:

```python
pool.map(worker, list(ids), chunksize=10)
```

**Comment by SolomonGebreyohannes** [comment]
Thanks. List didn't work for me but user defined iterator slice using tuple works.
