### ISSUE TITLE
Recurrent meetings returning incorrectly

### ISSUE THREAD

**Issue by javierlm** [ecederstrand/exchangelib#565]
I'm trying to get all calendar meetings for today, and it returns me all, except the ones that are recurrent. If I use `account.calendar.view(start=start, end=end)`, it returns repeated meetings (same meeting twice or more), and sometimes they aren't recurrent.

What is the correct syntax to do it?

**Comment by ecederstrand** [comment]
`account.calendar.filter(start__range(start, end))` returns stand-alone appointments and the master item of recurring items. `account.calendar.view(start=start, end=end)` returns stand-alone items and the expanded items of recurring items.

I have never experienced duplicate items returned from `.view()`. Is it possible that you simply have overlapping appointments? Anyway, please post the output you see, including the EWS ID (`item.id`) of each of the returned items.

**Comment by javierlm** [comment]
> `account.calendar.filter(start__range(start, end))` returns stand-alone appointments and the master item of recurring items. `account.calendar.view(start=start, end=end)` returns stand-alone items and the expanded items of recurring items.
> 
> I have never experienced duplicate items returned from `.view()`. Is it possible that you simply have overlapping appointments? Anyway, please post the output you see, including the EWS ID (`item.id`) of each of the returned items.

`item.id` is the same when I use `account.calendar.view(start=start, end=end)`. I've already checked that.

Today there are 3 appointments. 2 are stand-alone, and the other repeats every friday. With
`account.calendar.filter(start__range(start, end))` is returning only 2 of them, except the recurrent one
When I call `account.calendar.view(start=start, end=end)` it returns 3 items, but it's the same item repeated 3 times. In this case, it isn't the recurrent one. It's one of the items returned previously using the `filter` method.

**Comment by ecederstrand** [comment]
Can you pleas post some kind of output of your two queries and the start/end values you used for both? A simple `for item in some_query: print(item)` should print all non-empty attributes on each item, allowing to get a better idea of what is happening. You can anonymize any sensitive data before posting. EWS IDs are not sensitive.

**Comment by ecederstrand** [comment]
Hi @javierlm 

Can you please post the requested output?

**Comment by javierlm** [comment]
Hi @ecederstrand , I've solved the problem. It's not a exchangelib bug. Elements in iterator are returning correctly. Was the `list(iterator_of_appointments)` that I've included in the code, the problematic line. I don't know why, but it duplicates elements in the iterator all the time :/
