### ISSUE TITLE
newbie question - how to read the calendar events

### ISSUE THREAD

**Issue by jfabiani** [ecederstrand/exchangelib#566]
I'm sorry I don't just see what I'm doing wrong (most likely plenty).  All I am attempting to do is read the events of a public calendar. I tried to follow the discussions on using public folders but it was a little confusing for a newbie.   Using python 2.7.x on OpenSuse 15.0

```python
from exchangelib.folders import Calendar
from exchangelib import Credentials, Account, CalendarItem, UTC_NOW
import datetime
account = Account(...)
account.public_folders_root.refresh()
start = UTC_NOW() - datetime.timedelta(days=7)
print account.public_folders_root.tree()  #this works
x = account.public_folders_root
specificFolder = [item for item in x.walk().get_folders() if item.name == "OC Appointment Calendar"]
leg_folder = Calendar(folder_id = specificFolder[0].id, changekey = specificFolder[0].changekey)
for i in leg_folder.view(start=start, end=start + datetime.timedelta(days=14)):
    print i
```

```
testexchange.py", line 15, in <module>
  for i in leg_folder.view(start=start, end=start + datetime.timedelta(days=14)):
File "/usr/lib/python2.7/site-packages/exchangelib/folders.py", line 957, in view
  return FolderCollection(account=self.root.account, folders=[self]).view(*args, **kwargs)

AttributeError: 'NoneType' object has no attribute 'account'
```

**Comment by ecederstrand** [comment]
You have to tell leg_folder which account or root folder hierarchy it is connected to. You can do that by adding the `root` kwarg: `Calendar(folder_id=specificFolder[0].id, changekey=specificFolder[0].changekey, root=x)`

To get a folder with a specific name at arbitrary depth, you can use globbing:

```python
specificFolder = list(account.public_folders_root.glob('**/OC Appointment Calendar'))[0]
```

You shouldn't need to explicitly create a `Calendar` instance. Normally, you can just call `specificFolder.view()` directly. But maybe `specificFolder` isn't correctly identified as a calendar instance?

**Comment by jfabiani** [comment]
That worked - thanks.  Now all I have to do is parse the data.
