### ISSUE TITLE
ErrorInvalidOperation: Shared folder search cannot be performed on multiple folders.

### ISSUE THREAD

**Issue by karthikhebbar** [ecederstrand/exchangelib#567]
I am unable to filter mails by subject in inbox (including subfolders). This leads to below traceback.

```python
items = account.inbox.walk().filter('subject:test')
print items

for item in items:
    print item.subject
```

Leads to this traceback:

```
QuerySet(q=subject:test, folders=[Messages (Inner1), Messages (Inner2), Messages (inner3)])

File "/Users/xxx/ews/ewsservice.py", line 122, in test_something
    for item in items:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/queryset.py", line 298, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/queryset.py", line 375, in _item_yielder
    for i in iterable:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/account.py", line 580, in fetch
    shape=ID_ONLY,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/account.py", line 302, in _consume_item_service
    is_empty, items = peek(items)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/util.py", line 118, in peek
    first = next(iterable)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/folders.py", line 250, in find_items
    for i in items:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/services.py", line 432, in _paged_call
    parsed_pages = [self._get_page(message) for message in response]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/services.py", line 481, in _get_page
    rootfolder = self._get_element_container(message=message, name='{%s}RootFolder' % MNS)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/exchangelib/services.py", line 345, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidOperation: Shared folder search cannot be performed on multiple folders.
```

**Comment by ecederstrand** [comment]
This is the Exchange server telling you that what you are trying to do is forbidden. There’s nothing exchangelib can do here. For shared folders, you will have to change your code to do one search per folder.

**Comment by karthikhebbar** [comment]
Thanks !!
https://github.com/ecederstrand/exchangelib/blob/master/README.md#searching

# The filtering syntax also works on collections of folders, so you can search multiple folders in  a single request.
a.inbox.walk().filter(subject='foo')
This led me assumption that it can be done.


Nice work :-) 👍

**Comment by ecederstrand** [comment]
It does normally work, but for some reason your inbox contains shared folders, and EWS doesn’t allow querying those more than one at a time.

**Comment by ecederstrand** [comment]
No, sorry, no idea. I didn’t think it wad even possible to create folders as shared folders manually.

**Comment by thefedoration** [comment]
I'm getting the same exception with using QueryStrings filters across multiple folders using a `FolderCollection`

The folder collection method successfully searches across multiple folders when the filter is like `filter(subject__icontains='test')`, but not when it's a QueryString filter `filter('subject:test')`

@ecederstrand  are you sure that it's a limitation on EWS given that the first filter format seems to work? Unfortunately using that filter format doesn't work for me in all scenarios, so I'm pretty reliant on using the QueryStrings filters across sent + inbox simultaneously.

<img width="992" alt="Screen Shot 2021-06-04 at 10 39 08 AM" src="https://user-images.githubusercontent.com/6766645/120842134-2dec8500-c521-11eb-91f0-f7e783b9e4a0.png">

**Comment by ecederstrand** [comment]
The exception and error message comes from the server, so yes, it’s a limitation of EWS.

**Comment by thefedoration** [comment]
Ah gotcha, thanks @ecederstrand 

I guess I'll make requests to both inbox + sent independently and stitch them together. Not excited to handle 2 pagination cursors, but it is what it is.

If you have any ideas on better ways to do this - let me know!

**Comment by ozbrk** [comment]
A workaround for this issue. 

walk() returns an iterable collection of folders. You can iterate trough them and perform the search on them individualy. This is inconvinient but here is a little pseduocode (probably won't work just telling you the main idea here)

	main_folder = account.inbox #my own inbox
	searchon = main_folder.walk() #all of my subfolders		
        for i in searchon:
		main_q = i.filter(f"From:{domain}")  #perform the search on each and every folder that found on the collection. search will be performed one by one so you never try to search on "multiple" folders.
