### ISSUE TITLE
ExchangeService UseDefaultCredentials Property

### ISSUE THREAD

**Issue by techspence** [ecederstrand/exchangelib#568]
Within the Microsoft Exchange Web Services API v2.2 there is a Property within the `Microsoft.Exchange.WebServices.Data.ExchangeService` class called `UseDefaultCredentials`. The purpose of this is to get or set a value that indicates whether the credentials of the user who is currently logged on to Windows should be used to authenticate with Exchange Web Services (EWS).

Reading through the documentation, I don't see that this feature is available. Am I missing something or is there another way to achieve the above result?

**Comment by ecederstrand** [comment]
A quick googling suggests that this feature is only available in the .Net-based EWS Managed API, not the XML-based SOAP API?

**Comment by techspence** [comment]
Hmm..that's too bad. I did a bit of a dive into the XML elements and i'm not seeing much of anything to achieve this. There's probably a valid reason that I just don't understand why it's not available.

Thanks for responding!

**Comment by ecederstrand** [comment]
At least if you use Kerberos auth, you should be able to achieve single sign-on. See #96
