### ISSUE TITLE
Save Function Not Working

### ISSUE THREAD

**Issue by glide1178** [ecederstrand/exchangelib#570]
Hello, I am hoping you can help me with an issue calling the save() function on a Message item.  Every time I call the function it times out on me.  Everything else in the library seems to work great except this.  Here is a code snippet, and the error I receive.  

This code below is using a service account, but I get the same behavior when I use my personal account.

Thanks for any help!

```python
from exchangelib.configuration import Configuration
from exchangelib import Message, DELEGATE, IMPERSONATION, Account, Credentials, EWSDateTime, EWSTimeZone, Configuration, NTLM, CalendarItem, Q, ServiceAccount, Folder, FolderCollection
from exchangelib.folders import Folder
import logging,os.path
import json

from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
		
credentials = ServiceAccount(username='xxxx\\xxxxxxx', password='xxxxxxxxxx')

config = Configuration(
    server='xxxxxxxxxxxxxx.net',
    credentials = credentials
)

account = Account(
    primary_smtp_address='xxxxxxxx@xxxxx.com',
    autodiscover=False, 
    config=config,
    access_type=DELEGATE
)

f = account.public_folders_root / 'f1' / 'f2' / 'f3'
for item in f.all():
    item.is_read = False
    item.save()
```

```
DEBUG:exchangelib.protocol:Server autodiscover.firstam.net: Releasing session 24088
DEBUG:exchangelib.services:GetItem._get_elements result 1 of 1 is ready
DEBUG:exchangelib.account:Updating items for xxxxxxxxxxxx@xxxxxxxxxx.com (conflict_resolution AutoResolve, message_disposition: SaveOnly, send_meeting_invitations: SendToNone)
DEBUG:exchangelib.services:Processing items in chunks of 100
DEBUG:exchangelib.services:Starting UpdateItem._get_elements worker 1 for 1 items
DEBUG:exchangelib.services:Waiting for UpdateItem._get_elements result 1 of 1
DEBUG:exchangelib.services:Updating item AAIARgAAAAAAGkRzkKpmEc2byACqAC/EWgkAsf0XL8gNR02a7yQU4NEC6AAABJzoigAAFXqdykD7vUucwDynwBleJgABktbOCQAALgAAAAAAGkRzkKpmEc2byACqAC/EWgMAsf0XL8gNR02a7yQU4NEC6AAABJzoigAA values ['subject', 'sensitivity', 'body', 'categories', 'importance', 'in_reply_to', 'reminder_is_set', 'reminder_minutes_before_start', 'extern_id', 'culture', 'is_read', 'is_response_requested', 'references']
DEBUG:exchangelib.services:Trying API version Exchange2010_SP2 for account xxxxxxxxxxxxx@xxxxxxxxxxxx.com
DEBUG:exchangelib.protocol:Server xxxxxxxxxxxxxx.net: Waiting for session
DEBUG:exchangelib.protocol:Server xxxxxxxxxxxxxxxx.net: Got session 24088
DEBUG:exchangelib.util:Session 24088 thread 9312: retry 0 timeout 120 POST'ing to https://xxxxxxxxxxxxxxxxx.net/EWS/Exchange.asmx after 10s wait
```

**Comment by glide1178** [comment]
As a follow-up to this.  The save function works when running in a Linux environment, but not in Windows.

**Comment by ecederstrand** [comment]
If you are editing a lot of items, you may simply be rate-limited. If you wait long enough, you will probably get through. I don't think this is a Linux-vs-Windows problem.

A first thing you could try if you only want to update the `is_read` field is to tell exchangelib to only fetch that field, and also only update that field:

```python
for item in f.all().only('is_read'):
    item.is_read = True
    item.save(update_fields=['is_read'])
```

To put even less load on the server, try batch updating your items:

```python
update_tuples = []
for item in f.all().only('is_read'):
    item.is_read = True
    # bulk_update() expects a list of (Item, fieldnames) tuples
    items_to_update.append((item, ['is_read']))

account.bulk_update(update_tuples)
```

**Comment by glide1178** [comment]
It works when I add the only() function.  If I leave that off then it times out.  I let this code sit there for 10 minutes in the debugger before cancelling it.  Thanks for the reply.

Works:
for item in account.inbox.all().only('categories')[:1]:
        item.categories = ['TEST']
        item.save(update_fields=['categories'])

Doesn't work:
for item in account.inbox.all()[:1]:
        item.categories = ['TEST']
        item.save(update_fields=['categories'])

**Comment by ecederstrand** [comment]
An busy exchange server, or a server with strict policies, can easily rate-limit you for 10 minutes at a time, and only allow 1 request at a time before rate-limiting you again, so you'll have to leave the inefficient code running for an hour or more. Debug output will tell you what is going on. Probably there will be some progress if you let if wait long enough, but the inefficient version may take hours to complete if you have many emails to update.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have evidence that save() is failing and not just slow.
