### ISSUE TITLE
Inline images showing up inside attachments

### ISSUE THREAD

**Issue by lucasczpnk** [ecederstrand/exchangelib#573]
Similar question as to issue #250...

I've used the example posted there by @eric-hua and I was able to make it attach as it should.
But even setting `inline=True`, the images still appear inside the attachments.
I'm wondering if this is the expected behavior for exchangelib or if there is a certain way to make it so that the images appear only on the email body.

Could somebody help me clarify this?
Thanks in advance!

Below are additional information (screenshot + bits of code) for better understanding..

![example](https://i.imgur.com/a8SJrDA.png)

Here's the file handling / attachment

``` python
# attach signature images
for img in signature_img:
    with open(img, 'rb') as f:
        content = f.read()
    name = str(re.search(r'[a-z]{3}\.png', str(img)).group())
    sig_logo = FileAttachment(
        name=name,
        content=content,
        is_inline=True,
        content_type='GIF/Image',
        content_id=name,
        )
m.attach(sig_logo)
```

and here are the mapped bits in the message html 

``` python
@staticmethod
    def build_message_body(signature_img):
        img_arr = [str(signature_img[0]), str(signature_img[1])]
        img0 = re.search(r'[a-z]{3}\.png', str(img_arr[0])).group()
        img1 = re.search(r'[a-z]{3}\.png', str(img_arr[1])).group()
        html_body = HTMLBody('
```
...
``` html
<img width="124" height="64" id="cvc" src="cid:{0}" style="max-width: 100vw; max-height: 51.6129vw;">
...
<img width="373" height="137" id="ass" src="cid:{1}" style="max-width: 100vw; max-height: 36.7292vw;">
```
...
``` python
format(img1, img0))
```

**Comment by ecederstrand** [comment]
You could send an email using a client that is known to produce a correctly looking email, and then use exchangelib to inspect the exact fields and attachment properties that were used to create that email. This would give you a hint how to do the same in exchangelib.

**Comment by ecederstrand** [comment]
Hi @lucasczpnk Did you find a solution to this?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you get time to debug this as suggested above :-)

**Comment by lucasczpnk** [comment]
Hey Erik!

So sorry, haven't gotten the notifications for the updates, for some reason.

Yeah, I ended up having to add the images as attachments and reference them in the mail body.
Not the cleanest solution, but at least it works just fine.

When I have some spare time, I'll definitely try to inspect the mail sent from another client!
And if I manage to find it I'll be sure to contribute it here! :smile: 
Thanks for the tip!
