### ISSUE TITLE
Support folder:PermissionSet field

### ISSUE THREAD

**Issue by cranbar** [ecederstrand/exchangelib#574]
The library doesn't seem to support folder permissions (ACL's):

https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.folder.permissions?view=exchange-ews-api#Microsoft_Exchange_WebServices_Data_Folder_Permissions

**Comment by ecederstrand** [comment]
That link points to the Managed API which is different than the EWS XML-bases API that exchangelib uses.

I think the equivalent for XML is PermissionSet: https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-set-folder-permissions-for-another-user-by-using-ews-in-exchange#adding-folder-permissions-by-using-ews

We do support it (in the Folder.effective_rights field), but we don’t support modifying the value yet.

**Comment by cranbar** [comment]
Sorry, @ecederstrand-- this is the right documentation:

https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/permissionset-permissionsettype

(linked from the "Permissions" item on https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/folder)

Effective rights are the current user's rights with respect to the folder.  The permissions include _other_ users' permissions for the folder, including users with whom the owner has delegated access to the folder.  This information corresponds to the PR_ACL_TABLE in MAPI.

I'm still figuring out if I'm going to require the permissions.  If I do, I'll implement it and provide a pull request.

**Comment by ecederstrand** [comment]
Ah, yes, I see that now. In https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/folder there's a wrong indent so it looks like EffectiveRights is a sub-element of PermissionSet, but they are in fact two different fields.

It should be relatively easy to add support for this field.

**Comment by cranbar** [comment]
I opened a PR with my implementation.  It looks like there could be a number of different ways to slice the XML using your objects, but I made the best guesses I could.  Calendars have subtly different permissions, but I couldn't find a great way to represent those, so I ended up just making the permission set contain both possible lists of permissions.
