### ISSUE TITLE
Filter complains about categories not being string property

### ISSUE THREAD

**Issue by mzenzie** [ecederstrand/exchangelib#575]
When I run 
`account.inbox.filter(categories__icontains='test')`

 similar to the example in the documentation: 
`filtered_items = a.inbox.filter(subject__contains='foo').exclude(categories__icontains='bar')`

I get `exchangelib.errors.ErrorContainsFilterWrongType: The Contains filter can only be used for string properties.`

I also tried `account.inbox.exclude(categories_icontains='test')` which gave me the same result.

Is the documentation one wrong, or am I missing something?

**Comment by ecederstrand** [comment]
Hmm, that's strange. It's tested to work and I've used that query for years against various Exchange versions.

Can you enable debug logging (see https://github.com/ecederstrand/exchangelib#troubleshooting) and post the request and response XML here?

I just tried `account.inbox.exclude(categories_icontains='test')` against my O365 test account (Exchange 2016) and got a successful response. Here's my request XML:

```xml
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2016"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="Romance Standard Time"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
      </m:ItemShape>
      <m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="100" Offset="0"/>
      <m:Restriction>
        <t:Contains ContainmentComparison="IgnoreCase" ContainmentMode="Substring">
          <t:FieldURI FieldURI="item:Categories"/>
          <t:Constant Value="test"/>
        </t:Contains>
      </m:Restriction>
      <m:ParentFolderIds>
        <t:DistinguishedFolderId Id="inbox">
          <t:Mailbox>
            <t:EmailAddress>john@example.com</t:EmailAddress>
            <t:RoutingType>SMTP</t:RoutingType>
            <t:MailboxType>Mailbox</t:MailboxType>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:ParentFolderIds>
    </m:FindItem>
  </s:Body>
</s:Envelope>
```

**Comment by mzenzie** [comment]
We're using 2010 SP2. Here's the request XML, sorry for the formatting:

Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2"/><t:TimeZoneContext><t:TimeZoneDefinition Id="UTC"/></t:TimeZoneContext></s:Header><s:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>IdOnly</t:BaseShape></m:ItemShape><m:IndexedPageItemView BasePoint="Beginning" MaxEntriesReturned="2" Offset="0"/><m:Restriction><t:Contains ContainmentComparison="IgnoreCase" ContainmentMode="Substring"><t:FieldURI FieldURI="item:Categories"/><t:Constant Value="test"/></t:Contains></m:Restriction><m:ParentFolderIds><t:DistinguishedFolderId Id="inbox"><t:Mailbox><t:EmailAddress>x@x.x</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>Mailbox</t:MailboxType></t:Mailbox></t:DistinguishedFolderId></m:ParentFolderIds></m:FindItem></s:Body></s:Envelope>
Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="399" MinorBuildNumber="0" Version="Exchange2010_SP2" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:FindItemResponseMessage ResponseClass="Error"><m:MessageText>The Contains filter can only be used for string properties.</m:MessageText><m:ResponseCode>ErrorContainsFilterWrongType</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey></m:FindItemResponseMessage></m:ResponseMessages></m:FindItemResponse></s:Body></s:Envelope>

**Comment by ecederstrand** [comment]
That's strange. It's exactly the same request. It's possible that your server simply doesn't support this query. `account.inbox.exclude(categories='test')` may work for you, but in general filtering on array-type fields is a bit wonky in EWS.

I've found sometimes that the only way to apply a filter on categories (e.g. "at least these two categories must exist") is to fetch everything that has a category (`account.inbox.filter(categories__exists=True)`) and then do a final filter client-side.

**Comment by mzenzie** [comment]
Thanks for taking a look! Unfortunately I get the same error with __contains. I'll just do the filtering on the python end.

**Comment by ecederstrand** [comment]
Ok. I'm closing this issue as I think it's a quirk or bug in your specific version of Exchange. Feel free to reopen if you disagree :-)
