### ISSUE TITLE
Check that folder is exist

### ISSUE THREAD

**Issue by MishkaBulkin** [ecederstrand/exchangelib#579]
Hi, how to check that folder is already exist?

**Comment by MishkaBulkin** [comment]
Also i want to know How i can find needed folder and remove it

**Comment by ecederstrand** [comment]
You can navigate to your folder using the options described in https://github.com/ecederstrand/exchangelib/blob/master/README.md#folders

If you reference a non-existent folder, we’ll throw `ErrorFolderNotFound`.

If you want to remove a folder, just call `.delete()` on the folder instance.

```python
try:
    f = account.root / 'some' / 'folder' / 'path'
except ErrorFolderNotFound:
    pass
else:
    f.delete()
```

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have further questions.
