### ISSUE TITLE
PyPi bump after Exchange 2019 support

### ISSUE THREAD

**Issue by vesche** [ecederstrand/exchangelib#580]
#577 was a great add, any chance to see a bump soon for these changes to be live on PyPi?

**Comment by ecederstrand** [comment]
No problem. I'll have a new version up at the end of the week.

**Comment by ecederstrand** [comment]
Sorry, got side-tracked. I'll have a version up later this week.

**Comment by vesche** [comment]
Thanks! I asked because I have software that uses packages from PyPi and wish to add 2019 support without statically including the entire lib.

**Comment by ecederstrand** [comment]
FWIW, you can always point directly to GitHub in a requirements file if the code you rely on has not yet been released. Just add this:

```
git+https://github.com/ecederstrand/exchangelib.git@736347b337c239fcd6d592db5b29e819f753c1ba
```

**Comment by ecederstrand** [comment]
v1.12.3 is out now.

**Comment by vesche** [comment]
Thank you!!
