### ISSUE TITLE
is there some sort of 'queryset' caching mechanism and if so, is there a way to force a refresh?

### ISSUE THREAD

**Issue by serbant** [ecederstrand/exchangelib#581]
the following code doesn't make sense to me:

```python
ipdb> account.inbox.filter(body__iexact=str(message.message_uuid)).count()
0
ipdb> account.inbox.filter(body__exact=str(message.message_uuid)).count()
1
ipdb> account.inbox.filter(body__iexact=str(message.message_uuid)).count()
0
ipdb> account.inbox.filter(body__exact=str(message.message_uuid)).count()
1
ipdb> account.inbox.filter(body__icontains=str(message.message_uuid)).count()
1
ipdb> str(message.message_uuid)
'17c457db-f8c9-4d2f-9abc-a5e099ad0836'
ipdb> account.inbox.filter(body__icontains=str(message.message_uuid)).get().body
'17c457db-f8c9-4d2f-9abc-a5e099ad0836'
ipdb>
```
# iexact should return a match as well unless i am mistaken

this is the code where the problem occurs:

```python
while _wait_receive < max_wait_receive:
                    found_message = account.inbox.filter(body__iexact=str(message.message_uuid))
                    if found_message.exists():
                        # this is supposed to kick in because the outlook client does show the
                        # message but it only kicks in if the first time filter function is called
                        # happens at least 30 to 45 seconds after the message was sent
                        print('breaking')
                        found_message = found_message.get()
                        break

                    time.sleep(step_wait_receive)
                    _wait_receive = _wait_receive + step_wait_receive
                    found_message = None

```

**Comment by ecederstrand** [comment]
To answer the question in the title: Yes, there is queryset caching. You can prevent caching by using the `.iterator()` method, as described in the README. There is no public method to invalidate the cache, but in your example code, you are creating a new queryset object on each line, so the queries do not share any cached values.

I have had issues with filtering on the `body` element before. If you enable debug logging (see https://github.com/ecederstrand/exchangelib#troubleshooting) you will see that the filter clause is created correctly, but somehow EWS does not always match that correctly with the existing items. I'm inclined to believe this is an error in EWS.

**Comment by serbant** [comment]
I don't think the .iterator() method fits the pattern in my sample. Right now my workaround is very crude: instead of using this while not timeout pattern, i just wait a relatively long time (like a minute) before issuing the first query.
I don't know if it's only iexact that's broken, I've encountered the same problem with exact, contains, and icontains.
Your answer suggests that the while pattern will work if the search is on subject instead of body. Is that correct?

**Comment by ecederstrand** [comment]
Fro complex fields such as `body`, EWS certainly has a different backend search implementation than for simple fields such as `subject`. I think you are correct that it can take quite some time before searching the `body` field works as expected. I don't know whether EWS caches the search result, but it's likely they do that for performance resons.

**Comment by ecederstrand** [comment]
I tested with the following example code:

```python
import logging
import random
import string
import time

from exchangelib import Credentials, Account, Message
from exchangelib.util import PrettyXmlHandler

# logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
username, password = 'john@demo.affect-it.dk', 'kPD8RE6fw7'
c = Credentials(username, password)
a = Account(primary_smtp_address=c.username, credentials=c, autodiscover=True)

def rand_str(length):
    return ''.join(map(lambda i: random.choice(string.ascii_letters + string.digits + ':.-_'), range(length)))

subject = rand_str(8).lower()
body = rand_str(32).lower()
item = Message(folder=a.inbox, subject=subject, body=body).save()

print('Searching for item with body %r' % body)
print(a.inbox.filter(body=body).count())
print(a.inbox.filter(body__exact=body).count())
print(a.inbox.filter(body__iexact=body).count())
print(a.inbox.filter(body__contains=body).count())
print(a.inbox.filter(body__icontains=body).count())

print('Sleeping 3 minutes')
time.sleep(600)

print(a.inbox.filter(body=body).count())
print(a.inbox.filter(body__exact=body).count())
print(a.inbox.filter(body__iexact=body).count())
print(a.inbox.filter(body__contains=body).count())
print(a.inbox.filter(body__icontains=body).count())

item.delete()
```

I am consistently getting the following results, no matter how long I wait and how large the body is:

```
Searching for item with body 'qms-82wvmparso57uabgl5fobmy6zivb'
1
0
0
0
0
Sleeping 10 minutes
1
0
0
0
0
```

It seems that an exact match on the body works, but substring comparison using the `Contains` element on the body field is simply broken in EWS, no matter how long I wait (you can add the logging line to see the exact XML request we generate). I'm surprised you get a hit with `exact` and `contains` because I don't.

**Comment by ecederstrand** [comment]
It seems someone found out that the `body` field cannot be part of a restriction: https://stackoverflow.com/a/37996517/219640 There's no authoritative source of this information, though.

There's an example using substring search with the EWS Managed API, but it may simply be a bug in the documentation: https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/dd633693(v%3Dexchg.80)

**Comment by serbant** [comment]
Ouch.... That takes away a lot of applications. Is there a way to warn poor
souls trying to use it: a readme entry, some sort of 'beware of alligators'
sign?

In my case it is not that relevant anymore, matching on subject with
icontains seems a better solution to begin with.

Thank you for the help.

**Comment by ecederstrand** [comment]
I've added a warning in the README now.
