### ISSUE TITLE
Timeout in base protocol not applicable for filters?

### ISSUE THREAD

**Issue by karthikhebbar** [ecederstrand/exchangelib#582]
I am trying to do filter query on folder to get mails matching certain criteria. I want to simulate timeout error for such cases. `BaseProtocol.TIMEOUT` I set it to like .3 seconds, still i am not hitting timeout error ? Is `BaseProtocol.TIMEOUT` applicable for filter query as well or what should I use?

**Comment by ecederstrand** [comment]
`BaseProtocol.TIMEOUT` is used directly in all `post()` requests. See https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/util.py#L630

It's possible your requests succeed within 300 ms. You could try setting it even lower, but I don't know if `requests` measures time reliably at such low timeout levels.

If you want to simulate a server timeout, I would suggest mocking the service endpoint or the `requests.post()` call instead. You can do the latter with the `requests_mock` package.

**Comment by karthikhebbar** [comment]
You can close this. I was able to stimulate by using lesser timeout values like .05. Thanks
