### ISSUE TITLE
Occasionally show this error （on field 'mime_content' to type <class 'bytes'>）

### ISSUE THREAD

**Issue by hkenter** [ecederstrand/exchangelib#584]
..............................BdS9GeFlmbE44LzdRMDk3WjRhYVc2bi9MQmE1bzBYM0REcDRRdHlhUVFueXFOUHhYSm5nTjkvU3BBDQo3MWZnNzhNTmY1Mk9rZ28wSG5OUzlLWlRvempDKzdMalVUcUZsZms3ZEN6TG1qcXRXR1g3cGFtYkRIOFIxdVdETmw4bE9yYXVjVlVpDQpPU0ZNcGtaSGFlNkg2Y05qRnEwRkowOWYzUnN2eTAvdkVONFZBNXJscCtmZ' on field 'mime_content' to type <class 'bytes'>

for the same email(has attachment),sometimes ok,sometimes failed,I have no idea.

What's wrong with this error? Thx~

**Comment by ecederstrand** [comment]
Can you please post the full stack trace?

**Comment by ecederstrand** [comment]
BTW, this is a warning, not an error. It is most likely raised here: https://github.com/ecederstrand/exchangelib/blob/e2cb2ad5533cbaca32cc916b06268bb72e7d2876/exchangelib/fields.py#L537

because the value of the `mime_content` field in the XML response cannot be Base64 decoded by the `base64.b64decode()` call just above. It's possible that the `mime_content` value is simply broken on this item.

**Comment by hkenter** [comment]
```
items = account.inbox.filter(datetime_received__gt=account.default_timezone.localize(today)).order_by('-datetime_received')
logger.info('Get mail box,analysing...')
hasAttach = 0
for msg in items:
    if msg.subject is not None:
```

Here's the code.
Whenever this waring occurs,there's a very long encryption like this.
`...............BdS9GeFlmbE44LzdRMDk3WjRhYVc2bi9MQmE1bzBYM0REcD`

like you said,may be the server transports cause the problem that cannot be decode.
I guess so.
anyway,thank u.

**Comment by ecederstrand** [comment]
To be able to find out if the string is valid or broken, we need the entire string causing trouble. It's best if you can post the full response XML here, but only do so if there is no confidential information in the email. https://github.com/ecederstrand/exchangelib#troubleshooting describes how to capture the response XML.

If you just want to get around the problem, you can avoid fetching `mime_content` field by specifying the exact fields you need for your script to work. For example, if you only need the `subject` and `datetime_received` fields:

```python
items = account.inbox.filter(...).order_by('-datetime_received').only('subject', 'datetime_received')
```

This will also save you some bandwidth and memory usage.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you think this is a bug in exchangelib :-)

**Comment by hkenter** [comment]
I use "only(...)" a few days, and it works well.
thanks a lot.

**Comment by mdoar** [comment]
I'm getting this with 1.12.5, but did not get it with 1.11.4
If I choose not to retrieve the mime_content, will that affect retrieving the text_body attribute?

**Comment by ecederstrand** [comment]
No. `mime_content` and `text_body` are distinct attributes.
