### ISSUE TITLE
Can't access sub folders under inbox

### ISSUE THREAD

**Issue by jacobceles** [ecederstrand/exchangelib#586]
When I try to access a subfolder inside my inbox, I get the error `exchangelib.errors.ErrorFolderNotFound: No subfolder with name 'AUG-DEC 2018'`

My folder name is AUG-DEC 2018 and I can see it in my outlook account. 
At the same time, when I try to print the inbox children count using `outlook_account.inbox.child_folder_count`, I get 5, which is the correct count, since I have 5 such sub folders.

Also, `outlook_account.root.tree()` doesn't show the subfolders under inbox now.
Everything was working fine 2 weeks ago when I tested the same code. I was able to fetch the emails from the subfolders under inbox.

My code fails at:
`folder = outlook_account.inbox/name` where name is a string with the value as AUG-DEC 2018

**Comment by jacobceles** [comment]
@ecederstrand I see that you have committed folders.py file recently. DO you think something was changed? Because the same code was working fine a few weeks back.

**Comment by ecederstrand** [comment]
Hmm. I can reproduce this. I wonder why it's not caught by the tests...

**Comment by jacobceles** [comment]
Can you rollback to a point where it was working?

**Comment by ecederstrand** [comment]
I found the error. We are receiving an `ErrorAccessDenied` but then ignoring the following `ErrorBatchProcessingStopped` which would have caught this bug. It's a try/catch that is too greedy. I'm working on a fix now.

**Comment by jacobceles** [comment]
It's fixed now! Works perfectly!
