### ISSUE TITLE
Voting option not working

### ISSUE THREAD

**Issue by kumaramit228** [ecederstrand/exchangelib#587]
I tried to send emails with voting options using extendedProperty but everytime I'm getting this error:

```
exchangelib.errors.ErrorInvalidExtendedProperty: The extended property attribute combination is invalid. (field: <t:ExtendedFieldURI xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" DistinguishedPropertySetId="Common" PropertyId="34080" PropertyType="IntegerArray"/>)
```

Here is my code for the same:
```python
class VoteRequest(ExtendedProperty):
    distinguished_property_set_id = 'Common'
    property_id = 0x00008520
    property_type = 'IntegerArray'

Message.register('vote___request',VoteRequest)
email = Message(
    account=mailBoxConnection.Ews,
    folder=mailBoxConnection.Ews.sent,
    subject='Demo script',
    vote___request=votingOptions,
    # author=Mailbox(email_address='xyz@fdsaj.com'),
    body='glad to spam you!',
    to_recipients=[Mailbox(email_address='amit.kuma@bc.com')],
    reply_to='alpha@beta.com',
)

email.send_and_save()
```

Thank you!

**Comment by ecederstrand** [comment]
Where did you find this example? I can't find it in the documentation, and the example in https://github.com/ecederstrand/exchangelib/issues/198#issuecomment-326973617 does not match your code.

**Comment by kumaramit228** [comment]
You're referring to this ? 
How can we get those voting option values if I've to set multiple voting option say 10 in an email, the link you provided deals with only Binary.

![image](https://user-images.githubusercontent.com/30652411/57456422-1e8ba680-728b-11e9-9637-57b2b8da30a5.png)

**Comment by ecederstrand** [comment]
You can't just change the type of the `VoteRequest` property to `IntegerArray`. It won't work. Outlook expects a very complicated binary blob containing the specification of the poll options, as described in the follow-up comment from me: https://github.com/ecederstrand/exchangelib/issues/198#issuecomment-327087222 That comment even contains a full implementation telling you how to build the binary blob for your vote options.

Getting the vote responses is described in https://github.com/ecederstrand/exchangelib/blob/master/README.md#extended-properties

**Comment by kumaramit228** [comment]
Hey mate, thanks for the code. That code works for the options that you've coded for. I need to add more options to the vote apart from what you've listed over there. Can you please put a documentation with what different codes mean the example, so that we can customize it as per our use case? I went through [Msdn doc](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxomsg/87488eff-3eec-4502-bc94-2368c04e3109) but couldn't make sense out of it.
Thank you!

**Comment by ecederstrand** [comment]
The code I posted reverse-engineered the voting option binary blob using some examples. I have no idea what the codes mean and how to use them for other purposes. You'll have to contact Microsoft for that.

It took a *long* time just to reverse-engineer the two examples. If you want modifications, you'll have to do the work yourself (or hire me to do it :-)).

If you just want to have the binary blob generated for your exact purpose, I suggest using an Exchange client that supports creating voting options, e.g. Outlook, send off a message with those options, and then inspect the generated extended property value using exchangelib.

**Comment by kumaramit228** [comment]
Thank you! I did reverse engineering using outlook client to get the desired voting options. For other's reference:
1. Send a mail to yourself using voting options from outlook with desired voting buttons.
2. Parse the email using exchangelib and parse voting request using VoteResponse.
3. You'll get a string which will be similar to [this comment](https://github.com/ecederstrand/exchangelib/issues/198#issuecomment-327087222)
4. That string is your voting options.
Here is a code example for doing the same:
`#register VoteRequest Property
class VoteRequest(ExtendedProperty):
    distinguished_property_set_id = 'Common'
    property_id = 0x00008520
    property_type = 'Binary'
Message.register('vote_request', VoteRequest)

#read the email with voting options and in that voting option string will be something like this
z=msg.vote_request

#when create your new mail just use this string (z here)
email=Message(
                account=mailBoxConnection.Ews,
                folder=mailBoxConnection.Ews.sent,
                vote_request=z,
                to_recipients=[Mailbox(email_address=emailAddress)],
            )
`
Also, by trying some reverse engineering I got a bit of understanding about [this doc](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxomsg/87488eff-3eec-4502-bc94-2368c04e3109).
Find the first occurence of your voting option display field (what you see in your outlook inbox) in the voting options string (z in above example). That's your DisplayName (variable) as per the doc. Post that all the variables are in the same order as they have been documented in the [doc](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxomsg/87488eff-3eec-4502-bc94-2368c04e3109) (each of them separated by a back slash '\' in the string) e.g. You can change the sendBehaviour i.e where to prompt the user for response or not.
