### ISSUE TITLE
Converting Message objects to standard library EmailMessage objects

### ISSUE THREAD

**Issue by kskyten** [ecederstrand/exchangelib#588]
Thanks for the library. It looks really solid.

I'm interested in using exchangelib to handle emails with [Notmuch](https://notmuchmail.org/) and to sync calendar events to a CalDAV server such as [Xandikos](https://xandikos.org/). To do this I need to download the emails into a [Maildir](https://en.wikipedia.org/wiki/Maildir) and to convert calendar events to icalendar files and back.

It would be really nice if the `Message` objects could be converted to [`email.message.EmailMessage`](https://docs.python.org/3/library/email.message.html#email.message.EmailMessage) objects from the standard library.

I'm not sure if it is in the scope of the project, but converting calendar events to and from icalendar objects from [this](https://github.com/collective/icalendar) library, for example, would also be really nice.

**Comment by ecederstrand** [comment]
Hmmm. I'm inclined to say it's out of scope. Since there will be lots of potential data loss in the conversion, I'm pretty sure that there will be as many requirements for the conversion as there are users of the feature.

**Comment by kskyten** [comment]
Just to be clear. You are talking about the icalendar conversion, right? What about the emails?

**Comment by ecederstrand** [comment]
I’m talking about both. EWS objects can have lots of extra fields that you have to decide if and how to encode in a .eml or .ics format.

**Comment by kskyten** [comment]
I see. Well, I can make a PR when I have something useful and separate the functionality into a different library if need be.

**Comment by ecederstrand** [comment]
Closing. Let's reopen if we get something more concrete on the table :-)
