### ISSUE TITLE
Is it possible to search in mail and related replies?

### ISSUE THREAD

**Issue by yassipo** [ecederstrand/exchangelib#592]
Hi,

I'm using this awesome library. I want to know that is it possible to get replies for below query?

filtered_item= account.inbox.filter(subject__contains='1100 - a sample rule for search')

Best
Yassipo

**Comment by ecederstrand** [comment]
Do you mean your own replies or other people's replies? Your own replies are usually in the Sent folder, and other people's replies will usually have a subject of `Re:`. There are also suggestions for other fields to use for filtering conversations in https://github.com/ecederstrand/exchangelib/issues/435 and https://github.com/ecederstrand/exchangelib/issues/261

**Comment by yassipo** [comment]
Thanks for you reply. I mean all replies. Because I have to list a mail and all replies (like mail box)

**Comment by ecederstrand** [comment]
In that case you can probably do that by:

1) split your search in two, the first one looking for messages with `in_reply_to=None`, and then do a search per `conversation_id`, or
2) fetch all items at once, and group them by `conversation_id` afterwards

You may need to look in both inbox and sent folders, assuming that's where your incoming and outgoing mails are located there.

**Comment by yassipo** [comment]
Thank you.
