### ISSUE TITLE
Inbox email filter based off of issue #485

### ISSUE THREAD

**Issue by gismcieri** [ecederstrand/exchangelib#593]
Hi,

Thanks so much for this library it is going to be awesome once i can get all the concepts down.  I am having problems seaching for emails no matter what i try nothing gets returned.  What i want to do is search by date (preferably time also and i tried your response in issue  #485 but i am not getting anything.

```python
i=0
tz = EWSTimeZone.timezone('America/New_York')
start = tz.localize(EWSDateTime(2019,5,20))
end = tz.localize(EWSDateTime(2019,5,23))
print (start)
print (end)
for item in account.inbox.filter(start__range=(start, end)):
    i+=1
    print(item.subject, item.sender, item.datetime_received)


print ("Retrieved " + str(i) + " messages")
```

I would also like to filter by subject.  

Any assistance would be greatly appreciated.

Thanks,
Matt

**Comment by gismcieri** [comment]
I also tried not using a range and just to get all the emails for a day.
```

tz = EWSTimeZone.timezone('America/New_York')
day = tz.localize(EWSDateTime(2019,5,23))
filtered_items = account.inbox.filter(datetime_received=day) 

i=1
for item in filtered_items:
    print(str(i))
    print(item.subject, item.sender, item.datetime_received)
    i+=1 
```

Thanks,
Matt

**Comment by ecederstrand** [comment]
`.filter(start__range=(start, end))` will filter on the `start` field, but only calendar items have start and end fields. You inbox probably has mostly messages, so you should filter on `datetime_received`.

In your second query, you are filtering on an exact value of `datetime_received` (`2019-05-23 00:00:00`), which is likely not going to match any messages. Instead, try filtering on a range: `filter(datetime_received__range=(start, end))`

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have additional questions :-)

**Comment by gismcieri** [comment]
Thanks so much for the assistance my problem was i wasn't using the time portion of DataTime correctly. In other words i wasn't using it.  I figured that if you were using a range that just the date would find everything for a day. I was trying to use the same date for both start and end and it wouldn't return anything.  Once i added in the time i was getting the returns i expected.
