### ISSUE TITLE
Unable to access account folders using impersonation account and autodiscover=False

### ISSUE THREAD

**Issue by aheficent** [ecederstrand/exchangelib#596]
Cannot access any folder when connecting using impersotation account and autodiscover=False

This code: 

```python
credentials = ServiceAccount(username='myusername@example.com', password='topsecret')
config = Configuration(server='mail.example.com', credentials=credentials)
account = Account(primary_smtp_address='john@example.com', config=config,
                  autodiscover=False, access_type=IMPERSONATION)
account.calendar
```

returns  `exchangelib.errors.ErrorNonPrimarySmtpAddress: The primary SMTP address must be specified when referencing a mailbox.`

however, if I type `account.primary_smtp_address` I get  _john@example.com_

With autodiscover=True the code above works fine.

**Comment by ecederstrand** [comment]
When you use autodiscover, what's the service endpoint that ends up being used? `print(account.protocol.service_endpoint)`. Maybe autodiscover sends you to a different server?

**Comment by aheficent** [comment]
Thanks for you answer. This is what I get:
`https://mail.example.com/ews/exchange.asmx`

With no autodiscover I get something similar but not the same:
`https://mail.example.com/EWS/Exchange.asmx`

Could it be that?

**Comment by ecederstrand** [comment]
That’s highly unlikely. I think your next step would be to compare the exact XML requests and responses to see what the difference is between the two. See https://github.com/ecederstrand/exchangelib/blob/master/README.md#troubleshooting on how to log and pretty-print the XML

**Comment by aheficent** [comment]
All right, thanks for your help. I am closing this for now.

**Comment by aheficent** [comment]
The requests are very similar, he only significant difference is the following:
-no_autodiscover:
` <t:DistinguishedFolderId Id="root">`

-autodiscover:
`<t:DistinguishedFolderId Id="calendar">`

I am sure if this is relevant.

**Comment by ecederstrand** [comment]
Just to be sure, what is the value of `account.primary_smtp_address` in the two cases, before you call `account.calendar`?

**Comment by aheficent** [comment]
> Just to be sure, what a the values of `account.primary_smtp_address` in the two cases, before you call `account.calendar`?

it was actually different! :sweat_smile: 
john.doe@example.com vs jdoe@example.com

I change that and now it works. Thanks a lo for the help.
