### ISSUE TITLE
Unable to update "Title" on  the contact model

### ISSUE THREAD

**Issue by hafedh305** [ecederstrand/exchangelib#597]
Hello
I'm trying to synchronize the title field to exchange, but I have this bug.
ValueError: Field name(s) 'title' are not valid for a 'Contact' item
Do you have an idea?

![title](https://user-images.githubusercontent.com/16020039/59119731-6dd8fb80-894b-11e9-822a-e4ae8cd15f99.png)

**Comment by ecederstrand** [comment]
The `Contact` class doesn’t have a `title` field. How did you come to expect that field?

**Comment by hafedh305** [comment]
@ecederstrand 
Thank you for your reply
We look in the exchange documentation I you that there is a contact field
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/contacts-rest-operations
Also we have this field.
![title 2](https://user-images.githubusercontent.com/16020039/59124689-450b3300-8958-11e9-811f-140de393412b.png)

**Comment by ecederstrand** [comment]
The docs you are linking to are for the REST API, but this library uses the SOAP API. In a Python prompt, you can see both all the supported fields on a model and a link to the EWS documentation for that element:

```python
>>> from exchangelib import Contact
>>> Contact.__doc__
'\n    MSDN: https://msdn.microsoft.com/en-us/library/office/aa581315(v=exchg.150).aspx\n    '>>> for f in Contact.FIELDS:
...     print(f.name)
mime_content
id
changekey
parent_folder_id
[...]
```

**Comment by hafedh305** [comment]
Thank you for answering it's clear.
