### ISSUE TITLE
is there anyway to create a draft mail using exchangelib

### ISSUE THREAD

**Issue by LevoWu** [ecederstrand/exchangelib#598]
i want to write a loop to write some draft mail to the mailbox ,and manual confirm and send these mail in my mailbox..but not find any function that can write a draft mail ,any suggestion for this?many thanks

**Comment by ecederstrand** [comment]
The easiest way is probably to save the message to th drafts folder without sending it:

```python
Message(folder=account.drafts, subject='blah').save()
```

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this does not solve your issue.
