### ISSUE TITLE
Issue deleting emails from trash

### ISSUE THREAD

**Issue by clubaccessdev** [ecederstrand/exchangelib#599]
Hello,
I've been struggling with this for a couple days now. I'm trying to write a script to _hard delete_ emails that have already been moved to the trash.

Originally, I wanted to delete the oldest 10 emails found in the trash folder using account.trash.all()[:-10]

Since I couldn't get that to work, I am now trying to delete based on a filter of subject__contains="CAS Test Lab"

Code I'm using to loop the process:

```python
import datetime
import time
from time import sleep
from exchangelib import DELEGATE, Account, Credentials, Configuration, Folder, Message, CalendarItem

while True:

    credentials = Credentials('user@mail.com', 'some-password1')
    config = Configuration(server='outlook.office365.com', credentials=credentials)
    account = Account(primary_smtp_address='user@mail.com', config=config, autodiscover=False, access_type=DELEGATE)

    print("Searching for emails in trash...")
    print(account.trash.filter(subject__contains='CAS Test Lab').count())

    input("Press enter to delete the emails listed above.....")

    account.trash.filter(subject__contains='CAS Test Lab').delete()

    sleep(10)
```

**Comment by ecederstrand** [comment]
How is it not working? What are the error messages you get?

**Comment by clubaccessdev** [comment]
This is the error it gives me.

Searching for emails in trash...
32
Press enter to delete the emails listed above.....
Traceback (most recent call last):
  File "deletescript.py", line 24, in <module>
    account.trash.filter(subject__contains='CAS Test Lab').delete()
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\queryset.py", line 606, in delete
    chunk_size=page_size,
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\account.py", line 497, in bulk_delete
    suppress_read_receipts=suppress_read_receipts,
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\account.py", line 308, in _consume_item_service
    for i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 678, in _pool_requests
    for elem in elems:
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 370, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Users\joshu\AppData\Local\Programs\Python\Python36\lib\site-packages\exchangelib\services.py", line 345, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.

**Comment by ecederstrand** [comment]
That's strange. I use a combination of filter() and delete() all the time. Can you please post the XML request triggering the error message and XML response containing the error message? See https://github.com/ecederstrand/exchangelib#troubleshooting on how to capture the XML.

**Comment by clubaccessdev** [comment]
[debug_xml.txt](https://github.com/ecederstrand/exchangelib/files/3278448/debug_xml.txt)

**Comment by clubaccessdev** [comment]
It looks like its not allowing me to _hard delete_ because the destination folder is full. I thought a hard delete skipped the recoverable items folder and just purged the item? Am i doing something wrong?

Is there a way to work on deleting the recoverable items directory before deleting items out of the trash?

Thank you for your help. I really appreciate it.
-Joshua

**Comment by ecederstrand** [comment]
That's also my understanding of hard deletes, but EWS sometimes has its own ways. What happens if you empty the recoverable items folder first? `account.recoverable_items_deletions.all().delete()` or maybe better `account.recoverable_items_deletions.empty()` if the folder has a huge number of items.

**Comment by ecederstrand** [comment]
I just pushed a commit to allow you to at least see the `ErrorQuotaExceededOnDelete: Cannot delete message because the destination folder is out of quota.` message instead of the more generic `ErrorInternalServerError`.

**Comment by ecederstrand** [comment]
Closing. Feel free to te-open if emptying the `recoverable_items_deletions` folder does not help.
