### ISSUE TITLE
Method to Extract the ItemIDs or MessageIDs of emails

### ISSUE THREAD

**Issue by abhaykaggarwal** [ecederstrand/exchangelib#600]
Is there a method to actually extract the ItemID or MessageIDs from the emails in a given inbox using exchangelib? I wanted to be able to get these IDs in a bulk manner and then use them to get the exact full items. Thanks!

**Comment by ecederstrand** [comment]
The ItemId and Changekey are available as the `id` and `changekey` fields. You can fetch the IDs only by using `.only()`:

```python
account.inbox.all().only('id', 'changekey')
```
