### ISSUE TITLE
Manage message moderation

### ISSUE THREAD

**Issue by klem4** [ecederstrand/exchangelib#604]
Manage message moderation

Hello, I studied your library, but did not find a way to approve or reject messages awaiting moderation. Tell me please, is it possible to implement this?
Thank!

**Comment by ecederstrand** [comment]
I don’t know what that is. Can you post some documentation on the feature?

**Comment by klem4** [comment]
Of course! I mean this email moderation mechanism: https://docs.microsoft.com/en-gb/exchange/security-and-compliance/mail-flow-rules/manage-message-approval#how-to-decide- which-approval-approach-to-use

My goal is to monitor incoming moderator email, filter emails that are a request for moderation and confirm or reject them, that is, something like this:

```python
APPROVED_CLASS = "IPM.Note.Microsoft.Approval.Reply.Approve"
REQUESTED_CLASS = "IPM.Note.Microsoft.Approval.Request"

for item in a.inbox.all().order_by('-datetime_received')[:100]:
    if item.item_class == REQUESTED_CLASS:
        # item.approve() or item.reject() or something like this ...
        item.item_class = APPROVED_CLASS
        item.save()
```


Here is a description of the actions that need to be performed in order to send the necessary message to the exchange server:
https://stackoverflow.com/questions/43359295/approve-email-message-via-exchange-ews-api?rq=1
https://gsexdev.blogspot.com/2012/07/ews-managed-api-and-powershell-how-to.html

**Comment by ecederstrand** [comment]
This would be a nice enhancement, but I'm pretty hesitant in adding official support for things that require using extended properties. It does seem like everything in https://gsexdev.blogspot.com/2012/07/ews-managed-api-and-powershell-how-to.html is doable with exchangelib, but it also has a big disclaimer: 

> Approving or Rejecting Emails
> 
> ***********Disclaimer this bit is unsupported ************

I think that documenting this as a recipe somewhere for others to use would be a good start.

The blog post mentions a `GetMailTips` service that I do think would be useful to implement in exchangelib: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getmailtips-operation

**Comment by klem4** [comment]
I think I found a solution, it implements the same actions that are written in powershell, but using your library, as soon as I check everything, put the code here, maybe it will be useful to someone, i will do it today

**Comment by ecederstrand** [comment]
@klem4 Did you ever find a solution to this?

**Comment by ecederstrand** [comment]
Closing due to OP timeout. Feel free to reopen if you have something to share.

**Comment by cooleasyhan** [comment]
Great projects~~~

It works for me!

```python
from exchangelib import Account  # Definition,
from exchangelib import (
    DELEGATE,
    IMPERSONATION,
    Configuration,
    Credentials,
    ExtendedProperty,
    Mailbox,
    Message,
)


def login(username, password):
    credentials = Credentials(username, password)
    c = Configuration(server="xxx.net", credentials=credentials)
    return Account(username + "@xxx.cn", config=c, access_type=DELEGATE)


class ReportTag(ExtendedProperty):
    property_tag = 0x0031
    property_type = "Binary"


class VerbResponse(ExtendedProperty):
    distinguished_property_set_id = "Common"
    property_id = 0x8524
    property_type = "String"


def reject(account, message, reject_body):
    m = Message(
        account=account,
        folder=account.sent,
        subject="Reject: " + message.subject,
        to_recipients=[message.sender],
        item_class="IPM.Note.Microsoft.Approval.Reply.Reject",
        verb_response="Reject",
        report_tag=message.report_tag,
        body=reject_body,
    )
    m.send_and_save()


def approve(account, message):
    m = Message(
        account=account,
        folder=account.sent,
        subject="Approve: " + message.subject,
        to_recipients=[message.sender],
        item_class="IPM.Note.Microsoft.Approval.Reply.Approve",
        verb_response="Approve",
        report_tag=message.report_tag,
    )
    m.send_and_save()


account = login(username="approve-ews", password="xxxxx")
Message.register("verb_response", VerbResponse)
Message.register("report_tag", ReportTag)

all_items = account.inbox.all()
for message in all_items:
    print(message.subject, message.sender.email_address)
    reject(account, message, "Sorry, you cannot send a phinsh mail")
    # approve(account, message)

```
