### ISSUE TITLE
Filtered Inbox ID list is returning a QuerySet

### ISSUE THREAD

**Issue by abhaykaggarwal** [ecederstrand/exchangelib#606]
When I run the below query (with the author filled in)
`filtered_inbox = a.inbox.filter(author="*****", subject__startswith="JSP licenses Report for", 
                 datetime_sent__range = (UTC.localize(EWSDateTime.now()), nec_datetime))
print(filtered_inbox.all().values_list('id'))`

instead of getting the result I usually would which is a list of IDs, I instead get the query itself in the form of 
`QuerySet(q=author == '*****' AND datetime_sent >= EWSDateTime(2019, 6, 24, 14, 6, 45, 568643, tzinfo=<UTC>) AND datetime_sent <= EWSDateTime(2019, 6, 24, 21, 0, 16, tzinfo=<UTC>) AND subject startswith 'JSP licenses Report for', folders=[Inbox (Inbox)])`

I wanted to know if there was a solution to this issue, or if I am using filter incorrectly

**Comment by ecederstrand** [comment]
All the methods that support chaining, like `.filter()`, `.all(()` and `.values()`, return a new `QuerySet` object. To get the actual result of the query, you need to iterate the QuerySet, for example by wrapping it in a `list()` or consuming it in a for-loop.

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if the above did not solve your issue.
