### ISSUE TITLE
Access to Teams shared calenders

### ISSUE THREAD

**Issue by NICWELLER98** [ecederstrand/exchangelib#607]
I am wondering if It is possible to access calender's which were shared with me through exchangelib? To my knowledge, it doesn't appear that way because when I use account.root.tree(). It just shows calendar as a branch but nothing stemming from it. If I try to iterate through the items in my calendar it only shows my items. Is there some trick I am missing which would allow me to access other peoples calendars which were shared with me, and iterate though them using exchangelib? Thanks!

**Comment by ecederstrand** [comment]
There are multiple suggestions in closed issues about accessing shared calendars, but the correct solution seems to be to create an Account using the email address of the shared account containing the calendar folder you want to access.

**Comment by NICWELLER98** [comment]
How do you create an account without knowing the other persons password. They have shared their calendar with me, but I don't have their password.

**Comment by ecederstrand** [comment]
An Account does not have to point to the same account as the Credentials user. That’s dokumented in https://github.com/ecederstrand/exchangelib/blob/master/README.md#setup-and-connecting and the examples in the other issues.

**Comment by NICWELLER98** [comment]
Thank you!
