### ISSUE TITLE
ValueError: unsupported hash type md4

### ISSUE THREAD

**Issue by ankushagarwal87** [ecederstrand/exchangelib#608]
I am using Exchange on premise & my application is running fine in windows but failing in linux server with ValueError: unsupported hash type md4

**Comment by ecederstrand** [comment]
This is a duplicere of #518

**Comment by eusoubrasileiro** [comment]
Solution is this https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1971580/comments/3

Add this to your `/usr/lib/openssl.cnf` to 're-enable' md4 to hashlib

```
[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```

**Comment by dogwynn** [comment]
Some further discussion and [solutions here](https://gitlab.com/kalilinux/packages/kali-tweaks/-/issues/27)

**Comment by monperrus** [comment]
I confirm that tweaking `/etc/ssl/openssl.cnf` per https://github.com/cannatag/ldap3/issues/1038 is a solution.

**Comment by spaceone** [comment]
Another workaround without adjusting the SSL config:
```
import ctypes
 
ctypes.CDLL("libssl.so").OSSL_PROVIDER_load(None, b"legacy")
ctypes.CDLL("libssl.so").OSSL_PROVIDER_load(None, b"default")

import hashlib
…
```
