### ISSUE TITLE
Authentication to the Exchange server

### ISSUE THREAD

**Issue by goratt12** [ecederstrand/exchangelib#609]
Hello,
After I read the README and didn't find an answer:
Is it possible to authenticate to the Exchange Server using the credentials the service\process is running with?
I need this in order to avoid entering my password every time OR saving it locally.
thank you!

**Comment by ecederstrand** [comment]
That would require some kind of SSO mechanism. Kerberos is somewhat supported, and someone mentioned [getting SSPI to work](https://github.com/ecederstrand/exchangelib/issues/96#issuecomment-510471790).

**Comment by goratt12** [comment]
If I understood correctly, I need to change my auth_type to GSSAPI.
But when i run it with the new setting I get the error:
Unsupported auth type gssapi.

**Comment by ecederstrand** [comment]
You also need to install the optinonal Kerberos packages. See https://github.com/ecederstrand/exchangelib#installation

**Comment by alberto-dev** [comment]
I've performed a little test on my pc and the kerberos method seems not to work with single sign on (passwordless) access to our Exchange server, but sspi library does.
Here are my two test scripts: https://gist.github.com/alberto-dev/ce66ff523d6130d4c5a631888cd546b9

**Comment by ecederstrand** [comment]
Ok. SSPI is being discussed in #96
