### ISSUE TITLE
Cannot connect to EWS 2013 with "The SMTP address has no mailbox associated with it"

### ISSUE THREAD

**Issue by serbant** [ecederstrand/exchangelib#611]
This the debug return from exchangelib code running with Python 3.6.8 on a Windows 7 Enterprise host:

Session: 25135
Thread: 15104
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x00000000054D1DD8>
URL: https://autodiscover.phsa.ca/Autodiscover/Autodiscover.xml
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x00000000054D1CC0>
Allow redirects: True
Streaming: False
Response time: 0.7960000000311993
Status code: 200
Request headers: {'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connecti
on': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '361', 'Authorization': 'NTLM TlRMTVNTUA
ADAAAAGAAYAGwAAAD4APgAhAAAAAYABgBYAAAADgAOAF4AAAAAAAAAbAAAABAAEAB8AQAANoKJ4gYBsR0AAAAPOQ3wmv4reUhRzcry/lHutlBIU0FCQ3N2Y1
9TT0NtYWlsYm94AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPxVoT3T8cVQiKnevvKwYwAEBAAAAAAAAwcMso95A1QGeLu18DL7jjQAAAAACAAwAUABIAFMAQQ
BCAEMAAQAUAFMAUgBWAEUAWABDAEEAUwAwADIABAAgAHAAaABzAGEAYgBjAC4AZQBoAGMAbgBlAHQALgBjAGEAAwA2AFMAUgBWAEUAWABDAEEAUwAwADIALg
BwAGgAcwBhAGIAYwAuAGUAaABjAG4AZQB0AC4AYwBhAAUAEgBlAGgAYwBuAGUAdAAuAGMAYQAHAAgAwcMso95A1QEGAAQAAgAAAAoAEAA++BJ0s1dGfNWmba
aIOkTaAAAAAAAAAAArWw62Wyf0dKZOCWd1ExPn'}
Response headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '363', 'Content-Type': 'text/htm
l; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/7.0', 'X-AspNet-Version': '2.0.50727', 'X-Powered-By': 'ASP
.NET', 'Date': 'Mon, 22 Jul 2019 22:41:44 GMT'}
Request data: ←[36m<?xml version='1.0' encoding='utf-8'?>←[39;49;00m
←[34;01m<Autodiscover←[39;49;00m ←[36mxmlns=←[39;49;00m←[33m"http://schemas.microsoft.com/exchange/autodiscover/outlook/
requestschema/2006"←[39;49;00m←[34;01m>←[39;49;00m
  ←[34;01m<Request←[39;49;00m←[34;01m>←[39;49;00m
    ←[34;01m<EMailAddress←[39;49;00m←[34;01m>←[39;49;00mz-spexcm001-db01001@phsa.ca←[34;01m</EMailAddress>←[39;49;00m
    ←[34;01m<AcceptableResponseSchema←[39;49;00m←[34;01m>←[39;49;00mhttp://schemas.microsoft.com/exchange/autodiscover/o
utlook/responseschema/2006a←[34;01m</AcceptableResponseSchema>←[39;49;00m
  ←[34;01m</Request>←[39;49;00m
←[34;01m</Autodiscover>←[39;49;00m

Response data: ←[36m<?xml version='1.0' encoding='utf-8'?>←[39;49;00m
←[34;01m<Autodiscover←[39;49;00m ←[36mxmlns=←[39;49;00m←[33m"http://schemas.microsoft.com/exchange/autodiscover/response
schema/2006"←[39;49;00m←[34;01m>←[39;49;00m
  ←[34;01m<Response←[39;49;00m←[34;01m>←[39;49;00m
    ←[34;01m<Error←[39;49;00m ←[36mTime=←[39;49;00m←[33m"15:41:44.2146949"←[39;49;00m ←[36mId=←[39;49;00m←[33m"219876722
5"←[39;49;00m←[34;01m>←[39;49;00m
      ←[34;01m<ErrorCode←[39;49;00m←[34;01m>←[39;49;00m500←[34;01m</ErrorCode>←[39;49;00m
      ←[34;01m<Message←[39;49;00m←[34;01m>←[39;49;00mThe e-mail address cannot be found.←[34;01m</Message>←[39;49;00m
      ←[34;01m<DebugData←[39;49;00m←[34;01m/>←[39;49;00m
    ←[34;01m</Error>←[39;49;00m
  ←[34;01m</Response>←[39;49;00m
←[34;01m</Autodiscover>←[39;49;00m

DEBUG:exchangelib.util:Session 25135 thread 15104: Useful response from https://autodiscover.phsa.ca/Autodiscover/Autodi
scover.xml
DEBUG:exchangelib.protocol:Server autodiscover.phsa.ca: Releasing session 25135
DEBUG:exchangelib.autodiscover:Response headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Length': '
363', 'Content-Type': 'text/html; charset=utf-8', 'Expires': '-1', 'Server': 'Microsoft-IIS/7.0', 'X-AspNet-Version': '2
.0.50727', 'X-Powered-By': 'ASP.NET', 'Date': 'Mon, 22 Jul 2019 22:41:44 GMT'}

I know the account is supposed to work because:
- the same code runs happily from a Win 10 Pro host
- the EWSEditor (https://github.com/dseph/EwsEditor/releases) used with the same credentials and with autodiscovery enabled also works

The first difference between the logs above and the logs from the working host happen in the Request Headers where the cookie entry is missing. The Response Headers are completely different already.

**Comment by serbant** [comment]
Not related to the OS version at all.
The failure is related to having the autodiscover server resolved to an address that points to an out of date Exchange environment. Thank you Microsoft for not playing by the rules (https://blogs.msdn.microsoft.com/douggowans/2007/06/28/serviceconnectionpoints/) again.

In my case, the solution was to have a hosts file entry pointing the autodiscover server to the correct IP address.

Feel free to close this issue. It contains valid information but I have no idea where it belongs.

**Comment by ecederstrand** [comment]
Ok. I'm closing because we have other issues tracking autodiscover issues, and our autodiscover code needs an overhaul.
