### ISSUE TITLE
Time is always 1 hour off

### ISSUE THREAD

**Issue by warddebecker** [ecederstrand/exchangelib#62]
Hello,

When creating or checking existing appointments in the calendar, the time is always 1 hour off (it shows 1 hour earlier) .
I have set the correct timezone for me (UTC+1 , Romance Standard Time, Brussels).
Do you have any idea what the problem might be?
The only thing I could think of is daylight saving time, but this should not be an issue.
It might be usefull to implement NTP support if this is possible.

Best regards,
Ward

**Comment by ecederstrand** [comment]
Hi, probably the server is returning datetimes in UTC. You can check by printing `tzinfo` on the datetimes. If so, just localize the datetimes by creating a timezone and running `tz.localize(dt)`

**Comment by warddebecker** [comment]
Thanks for the fast response!
The server does indeed return UTC datetimes, but I can't localize the received time since it is already a localized datetime

This is a snippet of what I am attemting to do: 
`items = account.calendar.filter(
    start__lt=tz.localize(EWSDateTime(year, month, day+1)),
    end__gt=tz.localize(EWSDateTime(year, month, day)),
)

for item in items:
    tz.localize(item.start)
    tz.localize(item.end)`
    print(item.start.tzinfo,item.start, item.end, item.subject, item.body, item.location, item.required_attendees,item.optional_attendees,item.extern_id)

And this is the error I receive:
ValueError: Not naive datetime (tzinfo is already set)

So how do I convert the item.start and item.end, which are already UTC localized, to a UTC+1 datetime?

Thanks in advance

**Comment by ecederstrand** [comment]
Ah, of course. Sorry for misleading you. Changing timezone for a localised datetime goes like this: `item.start.astimezone(tz)`.

**Comment by warddebecker** [comment]
Thanks! that solved it
