### ISSUE TITLE
Add Headers to Maintain Affinity

### ISSUE THREAD

**Issue by spmsh** [ecederstrand/exchangelib#622]
Hi There, I was messing a bit with your great lib, and also reading more EWS documentation provided by Microsoft and referring to this [one](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-maintain-affinity-between-group-of-subscriptions-and-mailbox-server), it says to maintain affinity it needs to add the two following headers:

- X-PreferServerAffinity, set to True
- X-BackEndOverrideCookie, set with the value returned by EWS at first subscription

I've seen that in transport.py you are only adding X-AnchorMailbox, so I've added the two above additional headers as well.

```python
    def extra_headers(account):
        """
        Generate extra headers for impersonation requests. See
        https://blogs.msdn.microsoft.com/webdav_101/2015/05/11/best-practices-ews-authentication-and-access-issues/
        """
        if account and account.access_type == IMPERSONATION:
            extra_headers = {
                'X-AnchorMailbox': account.primary_smtp_address,
                'X-PreferServerAffinity': str(True)
            }
            if _get_backend_override_cookie() is not None:
                extra_headers['X-BackEndOverrideCookie'] = _get_backend_override_cookie()
            return extra_headers
        return None
```

I have also created this function `def _get_backend_override_cookie()` added in common.py inaisw `_get_soap_payload` to get the returned cookie from Microsoft and extract the X-BackEndOverrideCookie value from it and store it (e.g., in session, in db, etc...).

In common.py:

```python
    def _get_soap_payload(cls, response, **parse_opts):
        root = to_xml(response.iter_content())
        cookie = response.headers['Set-Cookie']
        _set_backend_override_cookie(cookie)
        [...] # rest of your code below
```

Is it worthwhile for you to add this to the master branch ? 
Feel free to add it if you believe it is better with it than without.

~spmsh

**Comment by ecederstrand** [comment]
Hi @spmsh 

I've just done a cursory read, and I agree that this would be a good addition.

It seems that this is only necessary for subscriptions which aren't implemented yet in exchangelib. Do you know if there are any implications of setting the headers in non-subscription mode?

**Comment by ecederstrand** [comment]
Related to #145
