### ISSUE TITLE
Error when trying to update calendar item

### ISSUE THREAD

**Issue by ggravlingen** [ecederstrand/exchangelib#623]
Hi,

Is there a specific way of updating a calendar item? To do the update, I'm running the sequence below:

```
calendar_item.body = HTMLBody(body)
ncr_calendar_item.save(
    send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY,
    update_fields=['body'],
)
```

But when doind so, I get the error below:
```
The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item., Item could not be saved because conflicts were detected when saving. ItemId:[longidnumber]SaveStatus: IrresolvableConflict
```

Oddly, the calendar item is silenty updated, but I get no email with the new calendar item, where the content has changed. Am I supposed to use the API in a different way?

If I change the start time of the calendar item, I seem to get an update to my email inbox.

Thanks,
Patrik

**Comment by spmsh** [comment]
If I'm not mistaking, you are getting this error because the item change key has changed between the item when you got your calendar_item and the time you are saving it. 

I can see two ways to work around the issue:

1. Retrieve the latest change key before saving the item, or
2. Use python```conflict_resolution=ALWAYS_OVERWRITE``` to force the update as below:

```python
calendar_item.body = HTMLBody(body)
ncr_calendar_item.save(
    send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY,
    update_fields=['body'],
    conflict_resolution=ALWAYS_OVERWRITE
)
````

PS: the change key of a calendar item can have many reasons to change, for instance if someone accept/decline the event, it will update its change key that could be different from the one you have in your app at the time you retrieve the calendar item

**Comment by ggravlingen** [comment]
Thanks! I recall trying the ALWAYS_OVERWRITE-attribute to no avail earlier today, but I’ll give it another go. Retrieving the latest key sounds more promising though. Is that the refresh-method in the same class?

Thanks,
Patrik

**Comment by ecederstrand** [comment]
Yes, `ncr_calendar_item.refresh()` method will get the new changekey so you can call `.save()`.

**Comment by ggravlingen** [comment]
I'm still not able to get it to work even after running a refresh with the same error. Am I understanding this wrong? This is the a snippet code of my custom class.

```
class CalendarAPI:

    def update_invitation(self,
                          calendar_item_id,
                          body=None, ):
        """Update calendar invitation."""

        calendar_item = self.get_calendar_item(calendar_item_id)

        # Create an empty list of fields to be updated
        update_fields = list()

        if body:
            update_fields.append('body')
            calendar_item.body = HTMLBody(body)

        calendar_item.refresh()
        calendar_item.save(
            update_fields=update_fields,
            #conflict_resolution=ALWAYS_OVERWRITE,
            send_meeting_invitations=SEND_TO_ALL_AND_SAVE_COPY,
        )

    def get_calendar_item(self, calendar_item_id):
        """Get a calendar item object."""

        try:
            return self.account.calendar.get(
                calendar_item_id=calendar_item_id,
            )
        except querysetDoesNotExist:
            return None
```

And `calendar_item_id` is an `ExtendedProperty`.

I pasted the full error here:
https://hastebin.com/esijitafos.sql
