### ISSUE TITLE
Pulling emails from the last 15 minutes

### ISSUE THREAD

**Issue by NICWELLER98** [ecederstrand/exchangelib#631]
I am trying to figure out how to pull emails out of my inbox from the last 15 minutes.

this is the error I am getting
 ```
if time >  item.datetime_received():
    TypeError: 'EWSDateTime' object is not callable
```

```python
def get_emails(account, time = datetime.now() - timedelta(minutes = 15)):
    inbox = account.inbox.all().filter('-datetime_received')
    temp_inbox = []
    for item in inbox:
        if time >  item.datetime_received():
            temp_inbox.append(item)
    return temp_inbox
```

Any insight on how this could be accomplished would be much appreciated! Thanks

**Comment by ecederstrand** [comment]
There are a couple of things wrong here. First of all, `item.datetime_received` is an attribute, not a method, so you shouldn't call it with parens. That's the reason for the error you posted.

Second of all, you are using the filter syntax wrong. you wrote `filter('-datetime_received')` but probably meant to order the items instead, i.e. `order_by('-datetime_received')`.

Finally, if all you want to do is get the last 15 minutes of emails, I would suggest you filter on the `datetime_received` value. To filter, you need to convert plain Python datetime objects to `EWSDateTime` instances, and you need to specify your timezone explicitly:

```python
from exchangelib import EWSDateTime, EWSTimeZone
tz = EWSTimeZone.localzone()
now = tz.localize(EWSDateTime.now())
fifteen_minutes_ago = now - timedelta(minutes=15)
last_emails = account.inbox.filter(datetime_received__gt=fifteen_minutes_ago).order_by('-datetime_received')
```

**Comment by NICWELLER98** [comment]
Thank you! That makes a lot more sense now.

**Comment by NICWELLER98** [comment]
So I tried writing what's below and it doesn't seem to print anything. I extended the time to ensure that there should be emails within the timeframe, but still nothing. Is this suppose to be happening?
for item in last_emails:
      print(item.subject, item.sender, item.datetime_received)


Thanks for the time and help!

**Comment by ecederstrand** [comment]
I just tested this, and it works fine for me. Maybe try a timedelta of 24 hours just to be sure. Also, try printing `fifteen_minutes_ago` and check that it looks as expected, including timezone info.

**Comment by NICWELLER98** [comment]
Thanks! It seems to be working now and I didn't change anything. So kind of strange. Take care.

**Comment by NICWELLER98** [comment]
I am stuck on the syntax for moving a email item to a different folder.
let say I have a folder name processed. 

would the syntax be item.move("processed") or item.move(a.inbox.processed).

I tried using item.move(a.inbox.processed) and it didn't end up working.

I ended up getting this error.
AttributeError: 'Inbox' object has no attribute 'processed'

**Comment by ecederstrand** [comment]
Navigating to subfolders is described in https://github.com/ecederstrand/exchangelib#folders

`.move()` takes a `Folder` instance. See https://github.com/ecederstrand/exchangelib#creating-updating-deleting-sending-and-moving

So, basically, you want ` item.move(a.inbox / 'processed')`

**Comment by NICWELLER98** [comment]
Thank you for the documentation below, but I am getting this error now. I am confused as to what would cause this. Any insights would be much appreciated thanks!


 item.move(account.inbox / 'processed' )
  File "/anaconda3/lib/python3.7/site-packages/exchangelib/items.py", line 377, in move
    raise ValueError('%s must have an ID' % self.__class__.__name__)
ValueError: Message must have an ID

**Comment by ecederstrand** [comment]
I’ll need a complete example to be sure, but somehow your item does not have an ID yet. You can only move items that already exist on the server. If you just created the item, set the `folder` attribute before saving, instead of moving the item to the folder you want.

**Comment by NICWELLER98** [comment]
The email is fairly new so that is most likely the cause. What do you mean by set the folder attribute before saving?

**Comment by ecederstrand** [comment]
The email either has an ID or it doesn't. It doesn't get one after a while.

If you got the email from the server, then it has an ID (unless you removed the `item.id` attribute, called `.send()` or `.delete()` or otherwise modified the item). If you created it yourself, then it doesn't have an ID until you call the `.save()` method.

```python
item = Message(folder=account.inbox, subject='Test')
item.move(account.trash)  # doesn't work because the item doesn't exist on the server yet.
item.save()  # Now the item has an ID
item.move(account.trash)  # Now this works. 
item.delete()  # Now the item doesn't have an ID anymore
```

**Comment by NICWELLER98** [comment]
It's strange because I am not calling .send() or .delete(). So basically what my program is doing is it is taking all of the emails in an inbox and checking their subject against a specific condition. If it meets the condition it sends it to one folder which isn't working. However, if it doesn't meet the condition it sends it to another folder which works. Which confuses me and originally made me think that it must be something to do with me not move to an existent folder but I have checked the spelling multiple times and it seems right.

**Comment by NICWELLER98** [comment]
Is there a way to get the items ID so that I can print it out and track when it disappears? thanks!

**Comment by ecederstrand** [comment]
The ID is available in the `.id` and `.changekey` attributes: `print(some_item.id, some_item.changekey)`.

**Comment by NICWELLER98** [comment]
I think I may have found a glitch or something. When I try useing EWSTimeZone on my Mac it works but it refuses to work on my windows computer. Is this suppose to happen. It just says NameError EWSTimeZone is not defined.

**Comment by ecederstrand** [comment]
You’re probably missing an import of `EWSTimeZone` at the top on your Windows version of the code. Otherwise, please post the entire stacktrace.
