### ISSUE TITLE
How to add CompleteDate to extendedproperty?

### ISSUE THREAD

**Issue by Xiejiaming-95** [ecederstrand/exchangelib#632]
Hi,
To monitor the kpi in our group, I need to collect the complete date for the emails attributed to different persons. Not only I need the flag status for which I have already find the solutions in issue #85, but also I need the CompleteDate which played a crucial role in our process. I have find this in EWS XML Elements but I don't know how to find the property_tag or property_Id? Please see the reference. https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/completedate#text-value 

Thank you for your help.

**Comment by Xiejiaming-95** [comment]
Oh, I have find the solution. According to 'https://pypi.org/project/exchangelib/' and the reference in it, I check the PDF in "https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148" and get the property_tag: 0x1091. At last, the code is as bellow:
class FlagComplete(ExtendedProperty):
    property_tag = 0x1091
    property_type = "SystemTime"

Message.register('flagcomplete', FlagComplete)

However, I still need collect the data for when the flag is set up. The issue #324 provide the proterty "flag_start" but it has only the date information without the exact hour and minute. It would be the best if I can find the exact data. Thank you very much.

**Comment by ecederstrand** [comment]
I don't know it that information is available on the server. Do users press a button or tick a box when they start on a task?

In general, we provide the methods to work with extended properties, but extended properties are very complex and giving advice on specific properties or reverse-engineering Outlook-specific functionality becomes very time-consuming.

**Comment by Xiejiaming-95** [comment]
Thank you for your information. There is indeed an button for users to click, which means this email has been followed up. If this is time-consuming, just let me continue finding ways to solve it.  Again, thanks for your reply.

**Comment by ecederstrand** [comment]
I may be wrong, but the button will probably only mark the email with a certain status, not record the time when the button was pressed. At least that's how I read e.g. https://social.msdn.microsoft.com/Forums/exchange/en-US/bce82c8c-a534-4713-a38d-169620c0cffd/ews-set-followup-on-an-email?forum=exchangesvrdevelopment

You may need to tell your users to do something different when they start and stop tasks if you need to track their start and stop timestamps.

**Comment by ecederstrand** [comment]
Closing as I think the remaining questions are outside the scope of exchangelib. Feel free to reopen if you disagree :-)

**Comment by Xiejiaming-95** [comment]
Thank you very much. I will continue to figure out the solution. Once I find it, I will respond to this issue.
