### ISSUE TITLE
Speed up the filter process while searching in more than 50000 emails.

### ISSUE THREAD

**Issue by Xiejiaming-95** [ecederstrand/exchangelib#634]
Since there are too many, more than 50000, emails in the inbox of our shared account, it takes quite a long time to use .filter to search some specific emails. For example, I want to find all the emails with subject containing "Hello world" which only came up after 2019.08.01. So I naturally use the code presented below where my start is 2019.07.29 and end is 2019.09.10:

```python
items = folder.filter(datetime_received__range=(start, end)).filter(subject__contains='Hello world')
```
and wish it is faster than 
```python
items = folder.filter(datetime_received__range=(start, end), subject__contains='Hello world')
```
and
```python
items = folder.filter(subject__contains='Hello world')
```
However, through my observation. These three codes take nearly the same time to work out the result. So if there is any method that can speed up this process. For my example, maybe narrowing the scope with received time before filtering on the subject should make it faster. But it does't work. Thank you very much for your help. I like this module very much. ^ ^
Best wish.

**Comment by ecederstrand** [comment]
It would help if you can post some actual measurements to back up your observations.

`folder.filter(foo=True, bar=False)` and `folder.filter(foo=True).filter(bar=False)` and `folder.filter(bar=False).filter(foo=True)`

are equivalent - they all produce the same query to send to the server. So the order should not make a difference.

The time to return the query results depends on the server. That's where the server executes. But if your query returns a large amount of items, it will take time to retrieve all of them, especially if you are retrieving complex fields lime `body` or `mime_content`. In this case, limiting the query to the actual fields you need will help - use the `.only('foo', 'bar')` method to do that.

Finally, you may see that using `.order_by()` slows down your query, if the ordering happens on a field that is not indexed by Exchange.

**Comment by ecederstrand** [comment]
Closing. Using `.only()` should speed up your queries.

Feel free to reopen if you still think response times are slower than they should be and you get time to collect some measurements.
