### ISSUE TITLE
ErrorNoRespondingCASInDestinationSite exception

### ISSUE THREAD

**Issue by PawelGajo** [ecederstrand/exchangelib#635]
I'm trying to connect to Exchange to pull emails from this mailbox
```python
credentials = Credentials(username='mailbox_username', password='mailbox_password')
version = Version(build=Build(15, 0, 12, 34)) 
config = Configuration(
        server='server_address', credentials=credentials, version=version
)
account = Account('mailbox_name', config=config, autodiscover=False, access_type=DELEGATE)

inbox_items = account.inbox.all().order_by('-datetime_received')
```
and im getting below error :
`exception: ErrorNoRespondingCASInDestinationSite('Exchange Web Services are not currently available for this request because none of the Client Access Servers in the destination site could process the request.',)`
I figured out I need to add X-AnchorMailbox header to my request.
There is a function extra_headers in transport.py
```python
def extra_headers(account):
    """
    Generate extra headers for impersonation requests. See
    https://blogs.msdn.microsoft.com/webdav_101/2015/05/11/best-practices-ews-authentication-and-access-issues/
    """
    if account and account.access_type == IMPERSONATION:
        return {'X-AnchorMailbox': account.primary_smtp_address}
    return None
```
but header X-AnchorMailbox is added only if access type is IMPERSONATION.

When I remove 
```python
 and account.access_type == IMPERSONATION
```
 from the condition, everything is ok.

Is this condition needed? If is, what could be wrong with my code, that this header is also required for DELEGATE access type?

Thanks.

**Comment by ecederstrand** [comment]
The first time I read the article in the comment, it seemed that setting the header was only necessary in impersonation mode. Upon reading it again, I think you are right that we should just set it always.

**Comment by dseph** [comment]
X-AnchorMailbox should always be set when using EWS against 365 - especially if Impersonation or Delegate access is used.  Calls which use it may work for now but fail at anytime in the future.   client-request-id, return-client-request-id and user-agent should also be set when using EWS against 365 as well as being able to log traffic - these help MS troubleshoot issues and check server-side logs.   X-AnchorMailbox  resolves so many issues its almost like a magic fix button - just set it and worry less.

**Comment by ecederstrand** [comment]
We do set it unconditionally for all services that depend on a specific mailbox: https://github.com/ecederstrand/exchangelib/blob/802366a1cd0495db05ca9e95ae2438c22616e781/exchangelib/services/common.py#L792
