### ISSUE TITLE
Implement GetDelegates service

### ISSUE THREAD

**Issue by mjsanmarco** [ecederstrand/exchangelib#638]
I'm trying to pull a list of delegates from a given users mailbox/calendar. I see there is a GetDelegates method in the EWS API documents (https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/dd633672(v%3Dexchg.80))

Is there way to do this in exchangelib now, or would this be a feature enhancement?

**Comment by ecederstrand** [comment]
exchangelib doesn’t support the `GetDelegates` service yet, so that would need to be implemented.

**Comment by ecederstrand** [comment]
I implemented this now as `Account.delegates`, returning a list of DelegateUser objects. I don't have access to an account with delegates, so please test if this works for you.
