### ISSUE TITLE
Option to return autodiscover LegacyDN

### ISSUE THREAD

**Issue by rodrigues8** [ecederstrand/exchangelib#639]
Hello, first I would like to thank you for lib which is a great job. I would like to provide a recommendation, I work at an email provider and am developing something to look for legacydn accounts to update at another provider. But the autodiscover option does not have a feature today that returns this information. Looking a lot in lib I identified that there is a private function in autodiscover.py called _get_response inside the content of the variable r that is returned can already find the legacy.

thanks for everything

**Comment by ecederstrand** [comment]
Thanks for the suggestion! I'm rewriting the autodiscover logic currently, but progress is slow. I'll take the `LegacyDN` value into account.

In general, I think it's time that we handle all autodiscover attributes that are returned. https://github.com/ecederstrand/exchangelib/issues/636 also requires some autodiscover values that we don't currently support.

**Comment by ecederstrand** [comment]
This should be possible now. The full autodiscover response message is now available on the `Account` object as `account.ad_response`, and `discover()` will now return an `ad_response` object. The `LegacyDN` field is available as `ad_response.user.legacy_dn`.
