### ISSUE TITLE
Implement CalendarEventDetails 

### ISSUE THREAD

**Issue by TheCodingLand** [ecederstrand/exchangelib#640]
I was trying to reach the subject and location of a CalendarEvent, through the fields in  CalendarEventDetails.

I think the implementation is missing for this field and it's not in the list of missing fields in issue https://github.com/ecederstrand/exchangelib/issues/203.

Is There a way to get the XML response from the freedata from a calendar event for me as a fix so I can access the properties as a temporary fix ?

              ?[94m<CalendarEvent?[39;49;00m?[94m>?[39;49;00m
                ?[94m<StartTime?[39;49;00m?[94m>?[39;49;00m2019-09-12T14:00:00?[94m</StartTime>?[39;49;00m
                ?[94m<EndTime?[39;49;00m?[94m>?[39;49;00m2019-09-12T15:00:00?[94m</EndTime>?[39;49;00m
                ?[94m<BusyType?[39;49;00m?[94m>?[39;49;00mBusy?[94m</BusyType>?[39;49;00m
                ?[94m<CalendarEventDetails?[39;49;00m?[94m>?[39;49;00m
                  ?[94m<ID?[39;49;00m?[94m>?[39;49;00m00000000428B9FA5C2693E4F9407D7EF7F84354507004B9EDC37B1D1BE4CA67F2B2E757537F200000000010D00004B9EDC37B1D1BE4CA67F2B2E757537F20002212299F00000?[94m</ID>?[39;49;00m
                  ?[94m<Subject?[39;49;00m?[94m>?[39;49;00mJLR?[94m</Subject>?[39;49;00m
                  ?[94m<Location?[39;49;00m?[94m>?[39;49;00mLuxembourg Training Room?[94m</Location>?[39;49;00m
                  ?[94m<IsMeeting?[39;49;00m?[94m>?[39;49;00mtrue?[94m</IsMeeting>?[39;49;00m
                  ?[94m<IsRecurring?[39;49;00m?[94m>?[39;49;00mfalse?[94m</IsRecurring>?[39;49;00m
                  ?[94m<IsException?[39;49;00m?[94m>?[39;49;00mfalse?[94m</IsException>?[39;49;00m
                  ?[94m<IsReminderSet?[39;49;00m?[94m>?[39;49;00mfalse?[94m</IsReminderSet>?[39;49;00m
                  ?[94m<IsPrivate?[39;49;00m?[94m>?[39;49;00mfalse?[94m</IsPrivate>?[39;49;00m
                ?[94m</CalendarEventDetails>?[39;49;00m
              ?[94m</CalendarEvent>?[39;49;00

**Comment by ecederstrand** [comment]
#203 only tracks missing fields on Item types (the kind returned by `FindItem`/`GetItem` services) while this element is part of the response returned by the `GetUserAvailability` service. Anyway, thanks for reporting! The referenced patch should allow you to get what you want via the new `details` attibute:

```python
for view_info in account.protocol.get_free_busy_info(accounts=[(account, 'Required', False),], start=start, end=end):
    for e in view_info.calendar_events:
        print(e.details)
```
