### ISSUE TITLE
Accessing shared mailbox - The SMTP address has no mailbox associated with it.

### ISSUE THREAD

**Issue by lululukas** [ecederstrand/exchangelib#641]
I'm having trouble accessing a shared mailbox again. I am getting the error `exchangelib.errors.ErrorNonExistentMailbox: The SMTP address has no mailbox associated with it` whenever I try to access any property of the shared mailbox account, apart from `public_folders_root`. I am still able to connect to my own email address without problems.

Log for `account.root.tree()`:

Request data:

```xml
<?xml version=\'1.0\' encoding=\'utf-8\'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
    <s:Header>
        <t:RequestServerVersion Version="Exchange2010_SP2"/>
        <t:TimeZoneContext>
            <t:TimeZoneDefinition Id="W. Europe Standard Time"/>
        </t:TimeZoneContext>
    </s:Header>
    <s:Body>
        <m:GetFolder>
            <m:FolderShape>
                <t:BaseShape>IdOnly</t:BaseShape>
                <t:AdditionalProperties>
                    <t:FieldURI FieldURI="folder:ChildFolderCount"/>
                    <t:FieldURI FieldURI="folder:EffectiveRights"/>
                    <t:FieldURI FieldURI="folder:FolderClass"/>
                    <t:FieldURI FieldURI="folder:DisplayName"/>
                    <t:FieldURI FieldURI="folder:ParentFolderId"/>
                    <t:FieldURI FieldURI="folder:PermissionSet"/>
                    <t:FieldURI FieldURI="folder:TotalCount"/>
                    <t:FieldURI FieldURI="folder:UnreadCount"/>
                </t:AdditionalProperties>
            </m:FolderShape>
            <m:FolderIds>
                <t:DistinguishedFolderId Id="root">
                    <t:Mailbox>
                        <t:EmailAddress>my@email.com</t:EmailAddress>
                        <t:RoutingType>SMTP</t:RoutingType>
                        <t:MailboxType>Mailbox</t:MailboxType>
                    </t:Mailbox>
                </t:DistinguishedFolderId>
            </m:FolderIds>
        </m:GetFolder>
    </s:Body>
</s:Envelope>
```

Response data:
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo MajorVersion="14" MinorVersion="3" MajorBuildNumber="442" MinorBuildNumber="0" Version="Exchange2010_SP2"
            xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
            xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"/>
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <m:GetFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:GetFolderResponseMessage ResponseClass="Error">
                    <m:MessageText>The SMTP address has no mailbox associated with it.</m:MessageText>
                    <m:ResponseCode>ErrorNonExistentMailbox</m:ResponseCode>
                    <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
                    <m:MessageXml><t:Value Name="SmtpAddress">my@email.com</t:Value></m:MessageXml>
                    <m:Folders/>
                </m:GetFolderResponseMessage>
            </m:ResponseMessages>
        </m:GetFolderResponse>
    </s:Body>
</s:Envelope>
```

**EDIT**:

Using my personal account, I can confirm that the shared mailbox is properly resolved:

```python
acc.protocol.resolve_names(['my@email.com'])

Out[13]: [Mailbox(name='My Mailbox Name', email_address='my@email.com', routing_type='SMTP', mailbox_type='Mailbox', item_id=None)]
```

**Comment by ecederstrand** [comment]
Is it possible that the shared account only has public folders?

**Comment by lululukas** [comment]
Nope, it has many folders that are all not public.

I was able to connect to that same mailbox before and access all of its subfolders. It stopped working after this weekend. I was using the latest release, I have now updated to the latest github version, but still the same issue.

**Comment by ecederstrand** [comment]
Does it still work with the same version that worked for you previously? If so, please compare the XML requests to see where we differ.

**Comment by lululukas** [comment]
No that version also does not work any longer, I updated after I encountered the problem. I am aware this might mean that it's not an issue with the library, but nothing about the Exchange configuration has changed..

**Comment by ecederstrand** [comment]
It could be related to #636

**Comment by lululukas** [comment]
Looks possible. After skimming over it quickly, it seems that it's mostly related to public folders though? It seems strange to me that I can even access the `public_folder_root`, although supposedly there is no mailbox at all at that smtp address?

**Comment by lululukas** [comment]
OK, so the problem was indeed on our side, the shared mailbox was moved to a new "cloud" environment which changed the endpoint I have to use for the configuration. Thanks for the help troubleshooting.

**Comment by axk7812** [comment]
> OK, so the problem was indeed on our side, the shared mailbox was moved to a new "cloud" environment which changed the endpoint I have to use for the configuration. Thanks for the help troubleshooting.

Can you share the new endpoint? I'd like to try to see if this is the same issue I'm having but not sure what endpoint

**Comment by ecederstrand** [comment]
You may be able to use autodiscover to fetch the correct endpoint for your account.

**Comment by lululukas** [comment]
@axk7812 this is my configuration since we moved to Office365:

```python
ews_config = Configuration(
        server="outlook.office365.com",
        credentials=credentials,
        version=Version(build=Build(14, 3, 442, 0)),
)
```

**Comment by ecederstrand** [comment]
As a side note, the version number in that config is probably wrong (O365 is running some version of Exchange 2016), but we can recover from a wrong version number.
