### ISSUE TITLE
Log level for "Found naive datetime" message

### ISSUE THREAD

**Issue by lululukas** [ecederstrand/exchangelib#643]
Whenever I retrieve mails from the exchange server, I get a huge amount of log messages like "exchangelib.fields:INFO:Found naive datetime 2019-09-18 17:23:24 on field last_modified_time. Assuming timezone Europe/Berlin". I'm checking with our exchange team why that field has no tz info, but in the meantime, would it be possible to set the log level of that message to debug instead of info? It is definitely useful information, but since the automatic conversion usually works fine and does what you want it to do, I think a debug message would be sufficient?

**Comment by ecederstrand** [comment]
You can lower the log level on this specific logger in your logging setup to silence the warning:

```python
import logging

logging.getLogger('exchangelib.fields').setLevel(logging.WARNING)
```

**Comment by lululukas** [comment]
That's an easier solution.. thanks!
