### ISSUE TITLE
Exception when using folder.only(properties), as folder might contain different types of emails 

### ISSUE THREAD

**Issue by ra2630** [ecederstrand/exchangelib#646]
I am trying to read emails in a folder, and using a list of properties passed into .only() method. However, a folder may contain different kinds of messages(For example, Sent Items folder may have Email messages and Meeting messages). There are certain fields (like conversation_topic/conversation_id in this case) which may be present in one type, but not in other. Due to this, my query on entire folder fails with following error:

The message doesn't contain some of the attributes for the given list of requested properties.

I would like to skip the Messages which don't have these properties, or set the particular property element to None, rather than raising an "AttributeErrorException" and failing the entire query for the folder.

Is there a workaround for this?
Any suggestions on how to resolve this will be really helpful and highly appreciated.

**Comment by ecederstrand** [comment]
Please post some example code that produces the error you are getting. That will help guide you to a solution.

**Comment by ecederstrand** [comment]
I'll have to guess what your code looks like, but if you want to access different properties of an item depending on the item type, use `is instance()`:

```python
from exchangelib.items import Message, MeetingRequest

for item in account.inbox.all():
    if isinstance(item, MeetingRequest):
        print(item.meeting_request_type)
    elif isinstance(item, Message):
        print(item.message_id)
    else:
        print(item.subject)
```

Feel free to reopen if this did not solve your issue.
