### ISSUE TITLE
exchangelib.errors.ErrorServerBusy to export large calendars

### ISSUE THREAD

**Issue by rodrigues8** [ecederstrand/exchangelib#647]
997/5000
Hello!

I would like someone to help me on one issue, I am using lib to do a calendar export from one account to another, in accounts with small calendars works very well, but in larger calendars I have problems with the error:

exchangelib.errors.ErrorServerBusy

I have checked a few topics about this error here, but my question is whether it would be possible a way to split this information to reduce the number of requests, making a export by parts. If anyone can help me with this I would appreciate it, I am currently using the following code:

        acc = exchangelib.Account (primary_smtp_address = c, credentials = cred, autodiscover = True, access_type = exchangelib.DELEGATE)
        acc2 = exchangelib.Account (primary_smtp_address = c, autodiscover = False, config = config, access_type = exchangelib.DELEGATE)

        item = acc.calendar
        items = item.all ()
        data = acc.export (items) -> Error Line
        acc2.upload ((acc2.calendar, d) for d in data)

**Comment by ecederstrand** [comment]
You can either try to lower the pressure on the server by setting a lower chunksize, or enable fault tolerance so exchangelib does a backoff/retry on the request when the server returns `ErrorServerBusy`.

The former is done like this. Note that the `ExportItems` service just need items IDs, not full items. So you can speed up your query considerably by fetching IDs only instead of the full item.

```python
queryset = account.calendar.all().only('id', 'changekey')
queryset.page_size = 200  # How many items to fetch per request
data = account.export (queryset, chunk_size=5)  # How many items to export per request
```

The latter is done by enabling the `FaultTolerance` policy. See https://github.com/ecederstrand/exchangelib#setup-and-connecting

**Comment by rodrigues8** [comment]
Many thanks my friend, helped me a lot !!! It worked perfectly and I still learned a few more things about lib. You are the best!

**Comment by ecederstrand** [comment]
Thanks. I'm glad you find the find the library useful :-)

Closing. Feel free to reopen if you have additional questions.

**Comment by deepaksinghtopwal** [comment]
i am facing a similar issue while saving attachments from emails.
So i have approx. 500 emails in my inbox and i am trying to save attachments from them (approx. 5000)

given below is the code i am trying (this is just a sample one , i am also saving attachments from it)

accnt =  account.inbox.all().order_by('-datetime_received')
accnt.page_size = 25
acnt_itr = accnt.iterator()

for item in acnt_itr :
    print(item.subject)

**Comment by deepaksinghtopwal** [comment]
I am also facing similar issue where i receive the following error while i am trying to save attachments (approx. 1000) from approx.(450 emails in inbox) :
Any suggestion how i can fix it in Exchangelib ?

equests.exceptions.ConnectionError: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

**Comment by ecederstrand** [comment]
As noted above, you can have this library handle connection errors for you by defining a retry policy. See the README for examples.

**Comment by deepaksinghtopwal** [comment]
Thanks Erik..
just increased the Timeout time and it worked for me. :)

but sometimes it works fine and sometimes it gives error ..
So any specific reason for that ??

**Comment by ecederstrand** [comment]
It’s because your serveres under varying load. Sometimes it will work, sometimes it won’t.

As I mentioned, adding a retry policy will hide most of that from you.

**Comment by deepaksinghtopwal** [comment]
Ok.. So is there any other configuration , setting apart from FaultTolerance you can suggest, which can help it making more efficient with no errors. ?

**Comment by ecederstrand** [comment]
That, or create your own subclass with your own custom logic.

**Comment by deepaksinghtopwal** [comment]
Yeah , i was able to  handle that with adding some more logic to my code .
But really appreciate your quick response and help on the issue :)
Thankss..
