### ISSUE TITLE
Add possibility of forwarding MeetingRequests

### ISSUE THREAD

**Issue by Ozzyz** [ecederstrand/exchangelib#648]
As I understand it, forwarding in exchangelib is only available to Messages, not MeetingRequests. However, MeetingRequests can also be forwarded in outlook. Is there any workaround for this, or does this functionality not exist to date?
Ideally, I think it should work the same way as for messages, e.g `m.forward(subject=..., to_recipients)` for both Messages and Meetingrequests.

**Comment by ecederstrand** [comment]
That sounds reasonable. The [ForwardItem](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/forwarditem) element just takes a `ReferenceItemId` which can be any item type, AFAICT.

Can you test if this works for you? It should be as simple as copying the `forward()` and `create_forward()` methods to the `Item` class.

If that works, then I can commit the fix. The same should probably be done for the `reply()` and `reply_all()` methods.

**Comment by Ozzyz** [comment]
I'll check it out, thanks :)

**Comment by Ozzyz** [comment]
@ecederstrand Forwarding works as a charm :) However, `reply()` and `reply_all()` uses the author field, which is not available in the Item class.

**Comment by ecederstrand** [comment]
Cool, thanks for testing!
