### ISSUE TITLE
multiple rooms

### ISSUE THREAD

**Issue by warddebecker** [ecederstrand/exchangelib#65]
Hi,

I am working on a system to display available meeting rooms on a screen using a raspberry pi.
I was testing with this library and I like it alot so far.
Now I would like to know if it is possible to have 1 room admin account with impersonation and rights over the rooms(or roomlist) and dynamically switch between the rooms to pull their calendars from EWS.
I would prefer to use a roomlist since it can automatically adapt when rooms are added or removed, but if this is harder to implement, I would just read a config file or something with the list of room e-mails.

Thanks in advance

**Comment by ecederstrand** [comment]
My own test server doesn't have rooms or room lists, but there are the `services.GetRoomLists` and `services.GetRooms` services that you could try out. They are untested AFAIK, but your code would look something like this:

```python
svc_account = Account(credentials=...)
rooms = GetRooms(protocol=svc_account.protocol).call(roomlist='MyRoomList')
for room in rooms:
     room_account = Account(
         primary_smtp_address=room.email_address, 
         credentials=..., 
         access_type=IMPERSONATION
     )
     for item in room_account.calendar.all().order_by('start'):
          print(item)
```

Granting impersonation access for `svc_account` to the relevant room accounts is something you need to handle on the Exchange server itself.

**Comment by warddebecker** [comment]
I just got around to testing this, but it doesn't appear to work. 
It doesn't return any rooms
I know you said it was untested, but is there any chance you could take a look at it? I know this might be hard without roomlists but it would help me alot.

Just FYI, im using exchange 365, I don't know if this changes anything.

Oh and the account also needed the smtp & autodiscover.
```python
svc_account = Account(primary_smtp_address='admin@domain', autodiscover=True , credentials=creds)
```

**Comment by ecederstrand** [comment]
I would love to test this in more depth, but the issue is that it's already tested as far as I can go, which is checking that the server returns an empty response. See: https://github.com/ecederstrand/exchangelib/blob/master/tests/__init__.py#L458

You could try calling `GetRoomLists(svc_account.protocol).call()` and see if that returns anything. If not, then `GetRooms` is not likely to return anything, either.

**Comment by warddebecker** [comment]
The ```GetRoomLists(svc_account.protocol).call()``` also doesn't return anything.
I double checked with powershell to exchange and the roomlist does exist and there are 2 testrooms in it.

I don't know if you have the time for it, but it is possible to create an office 365 development enviorment for free( I think its 30day trial).
You only get 1 account license, but you can make a bunch of rescource (room) accounts so it would be possible to create a roomlist. 
I am currently using the same kind of development enviorment for my testing.
This might take a little time to setup, but its very handy to have.

**Comment by ecederstrand** [comment]
Ok, thanks for the info.

As a last test, you could enable debug logging and check the raw responses from the server. Maybe the server is sending the right response but we're not picking up the contents.

**Comment by warddebecker** [comment]
Yes, I would like to check the raw responses, how could I go about doing that? Maybe a stupid question but i've never needed to do that before.

**Comment by ecederstrand** [comment]
```python
import logging
logging.basicConfig(level=logging.DEBUG)

# Your code here
```

:-)

**Comment by warddebecker** [comment]
Good news (I think), the raw response does contain the roomlist so it is a matter of fishing the correct data out of the response.

This is the response:

```XML
<?xml version="1.0" ?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Header>
		<h:ServerVersionInfo MajorBuildNumber="845" MajorVersion="15" MinorBuildNumber="22" MinorVersion="1" Version="V2016_10_10" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/>
	</s:Header>
	<s:Body>
		<m:GetRoomListsResponse ResponseClass="Success" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			<m:ResponseCode>NoError</m:ResponseCode>
			<m:RoomLists>
				<t:Address>
					<t:Name>Roomlist</t:Name>
					<t:EmailAddress>Roomlist@domain</t:EmailAddress>
					<t:RoutingType>SMTP</t:RoutingType>
					<t:MailboxType>PublicDL</t:MailboxType>
				</t:Address>
			</m:RoomLists>
		</m:GetRoomListsResponse>
	</s:Body>
</s:Envelope>
```

Exactly like expected, so something is going wrong in the processing of the XML.

**Comment by ecederstrand** [comment]
Cool! That should be enough to fix the problem.

Can you also capture the response from your `GetRooms` call?

**Comment by warddebecker** [comment]
Was already working on it, see edit on previous post ;)

**Comment by ecederstrand** [comment]
This should be fixed now, and `GetRooms` can be accessed via a helper method:

```python
for room in svc_account.protocol.get_rooms('my.roomlist@example.com'):
     room_account = Account(
         primary_smtp_address=room.email_address, 
         credentials=creds, 
         access_type=IMPERSONATION
     )
     for item in room_account.calendar.all().order_by('start'):
          print(item)
```

**Comment by warddebecker** [comment]
Everything seems to be working, thanks for the fast solution!

**Comment by sivakrkumar** [comment]
Hi ,

I need your help on above code. which mail id (my.roomlist@example.com) have to pass in get_rooms method to get rooms.
I am receiveing the below error message when using the original code ,

error message : 
Traceback (most recent call last):
  File "C:/Sivakumar/Python/MeetingRoomsBot/test.py", line 30, in <module>
    roomlist=RoomList(email_address='RES-CCCO-2EVE2J5Z@daimler.com')
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 408, in call
    return [Room.from_xml(elem=elem, account=None) for elem in elements]
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 264, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 237, in _get_element_container
    return self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
  File "C:\Python27\lib\site-packages\exchangelib\services.py", line 254, in _raise_errors
    raise vars(errors)[code](text)
exchangelib.errors.ErrorNameResolutionNoResults: No results were found.

Thanks.

**Comment by ecederstrand** [comment]
I'm not able to help you with that. `ErrorNameResolutionNoResults` means that Exchange could not resolve the name `RES-CCCO-2EVE2J5Z@daimler.com`
