### ISSUE TITLE
MeetingResponse object missing 'is_read' field

### ISSUE THREAD

**Issue by kgutwin** [ecederstrand/exchangelib#650]
I received the following exception:

    ValueError: Field name(s) 'is_read' are not valid for a 'MeetingResponse' item

However, IsRead appears to be a valid field in the MeetingResponse object: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/meetingresponse

**Comment by ecederstrand** [comment]
Thanks for the heads-up! It does indeed look like a bug.
