### ISSUE TITLE
Sending mails as member of a distribution group

### ISSUE THREAD

**Issue by riwish** [ecederstrand/exchangelib#653]
I need some help with replying (or sending) mails as a user from a mail distribution group.

Some background information...

I try to receive mails from a mail address distribution group I have access to. Please note that I do refer to a mail address other than my primary one. When I try send a message back (either by replying or regular send operation) I noticed a few pecularities.

- Normally when one member of a distribution mail group sends a mail, the receiver should see "ACCOUNT NAME on behalf of DISTRIBUTION GROUP NAME". Instead, the sender name is limited to the account name only. How can I get achieve the former mentioned structure.

- After a mail is sent, it changes to a concept message and it doesn't move to the "Sent items" folder which I cannot seem to understand. This doesn't occur when I change the primary smtp address from a distribution group to my actual primary address.

- When sending (or replying to) a mail from the Microsoft Exchange Server and as a member of a mail group distribution , I noticed that each message I sent, ends up getting saved in the "Sent items" folder of my PRIMARY mail address. I expected the same behaviour when using the library exchangelib but unfortunately.

```
# You can now create the Account without autodiscovering, using the cached values:
config = Configuration(service_endpoint=ews_url, credentials=credentials, auth_type=ews_auth_type)
account = Account(
    primary_smtp_address=primary_smtp_address, 
    config=config, autodiscover=False, 
    access_type=DELEGATE,
)
```

and the code for replying to a mail

```
# 'm' is the message instance we want to reply to 
m.reply(
    subject='Re: Daily motivation',
    body='I agree',
    to_recipients=['carl@example.com', 'denice@example.com']
)
```

So my question is how to solve the pecularities I mentioned earlier.

Thanks in advance

**Comment by ecederstrand** [comment]
If you want to save the message to your own `Sent items` folder, you need to specify that folder explicitly:

```python
dist_group = Account('distribution_group@example.com', ...)
me = Account('me@example.com', ...)
Message(account=dist_group, ...).send(copy_to_folder=me.sent)
```

Regarding what is shown as the sender, you probably need to fill out both the `sender` and `author` (`message:Sender` and `message:From` EWS fields, respectively). I think you should do like this:

```python
Message(
    account=dist_group, 
    sender=me.primary_smtp_address,
    from=dist_group.primary_smtp_address,
    ...
).send(copy_to_folder=me.sent)
```

I don't have a test account with distribution groups, so I can't test myself.

**Comment by ecederstrand** [comment]
@riwish Do the suggestions work for you?

**Comment by ecederstrand** [comment]
Closing, assuming the suggestions work for you. Feel free to reopen i you still have issues.

**Comment by riwish** [comment]
Hi Erik,

Sorry for responding so late. The code you provided works well, thank you! I do have another issue which prevents me saving the actual reply message (the reply message was initialized by a new Message instance). Apparently, the ```copy_to_folder=me.sent``` does not copy anything at all unless I specify ```message.move(to folder) # where message is an item```. In addition, the original mail is copied and not the reply that was sent back to its original sender. How can I proceed if I want to save the message with its reply, just as the ```message.reply()``` method works? 

Thank you in advance

**Comment by ecederstrand** [comment]
It's a bit hard for me to follow what you're trying to do. Can you please post an example so I can recreate the situation?
