### ISSUE TITLE
Processing emails and moving them results in premature loop termination

### ISSUE THREAD

**Issue by georgi-huklev** [ecederstrand/exchangelib#655]
I am writing a python script that iterates over items in the inbox. Once each individual message has been processed I move it to a different folder.
```python
folder: exchangelib.Folder = account.inbox.parent / 'Processed'
query: exchangelib.queryset.QuerySet = account.inbox.all().only(
        'subject',
        'datetime_received',
        'attachments'
)
for item in query.iterator():
    process_attachments(item)
    item.move(folder)
```
Unfortunately halfway through the emails the processing stops.

I am not sure if I am doing something wrong or this is a bug.

python 3.7.4, echangelib 2.0.1

**Comment by ecederstrand** [comment]
Try enabling debug logging so you can see what exchangelib is trying to do when it stops. See https://github.com/ecederstrand/exchangelib#troubleshooting

**Comment by ecederstrand** [comment]
Also, I don't quite understand if the loop exits, or the loop never exits?

**Comment by georgi-huklev** [comment]
Hi Eric,

Thanks for your ideas. I will collect some debug info today.
Yes the loop exits without errors(process exit code is 0).

Cheers,
Georgi

On 15 Oct 2019 07:23, Erik Cederstrand <notifications@github.com> wrote:

Also, I don't quite understand if the loop exits, or the loop never exits?

**Comment by georgi-huklev** [comment]
I think somehow the folder iterator breaks if you move item out of it. The problem does not occur if no items are moved.

**Comment by ecederstrand** [comment]
Ah. We are consuming a query from the server, so it's possible that the server does not like messages being removed from the query while we are consuming it. If you enable debug logging you should be able to see the paging info that the server responds with in the response XML. It could be that the server sends a response that the paging has ended, or maybe it sends paging info that we incorrectly interpret as if paging has stopped.

**Comment by ecederstrand** [comment]
@georgi-huklev Did you get time to debug this issue?

**Comment by georgi-huklev** [comment]
Thanks for the feedback, Erik.
I didn't have time to debug yet. Perhaps this afternoon I'll be able to squeeze in some test runs.

**Comment by georgi-huklev** [comment]
Ok, here we go.

**Test setup**: I have two folders:
 * 'Test' - about 250 e-mails
 * 'Test2' - Empty

**Test code**:

```python
import logging

import exchangelib
from exchangelib.util import PrettyXmlHandler

# Enable exchangelib debugging
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])

credentials = exchangelib.Credentials('...', '...')
config = exchangelib.Configuration(
    credentials=credentials,
    server='...'
)
account = exchangelib.Account(
    '...',
    config=config,
    access_type='delegate'
)


def move(source, destination):
    src: exchangelib.Folder = account.inbox.parent / source
    dst: exchangelib.Folder = account.inbox.parent / destination
    for item in src.all().only('subject').iterator():
        item.move(dst)


if __name__ == '__main__':
    move('Test', 'Test2')

```

**Result**:  Only half of the mails have been moved.

**The debug log**: https://paste.ee/p/Zjv43

**Comment by ecederstrand** [comment]
This looks like a bug in EWS. We are requesting 100 items. 100 items are returned. You move some (or all) of them. We then ask for 100 more, and get a response with IndexedPagingOffset="125" TotalItemsInView="125". Many programming languages don't like the iterator to change when iterating. It's possible C3 (or whatever EWS is implemented in) is one of those.

I think your best bet is to fetch *all* the items you want to move, before moving them. So wrap your queryset in a list: `list(src.all().only('subject').iterator())`.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's anything we can do in exchangelib to fix this problem.
