### ISSUE TITLE
UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx

### ISSUE THREAD

**Issue by suryareddy005** [ecederstrand/exchangelib#659]
Hi, I use the following code every day to access my account. But from the last 3 days, it's giving an error:
I tried a couple of things that haven't worked. Could someone help me in that 

```python
creds = Credentials(user_smtp, user_password) 
account = Account(
    primary_smtp_address=user_smtp,
    autodiscover=False,
    config=Configuration(server='outlook.office365.com', credentials=creds),
    access_type=DELEGATE
)
```

**Comment by ecederstrand** [comment]
Can you please post the stack trace? Also, you can try setting an explicit auth type in yout configuration object..

**Comment by suryareddy005** [comment]
Thanks for quick response, here you go

---------------------------------------------------------------------------
UnauthorizedError                         Traceback (most recent call last)
<ipython-input-5-339c1e6d99ec> in <module>()
      1 account = xlib.Account(
      2         primary_smtp_address = config.user_smtp,
----> 3         autodiscover = False, config = xlib.Configuration(server = 'outlook.office365.com', credentials = creds),
      4         access_type = xlib.DELEGATE)

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/configuration.py in __init__(self, credentials, server, has_ssl, service_endpoint, auth_type, version)
     44             auth_type=auth_type,
     45             credentials=credentials,
---> 46             version=version
     47         )
     48 

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/protocol.py in __call__(cls, *args, **kwargs)
    209             log.debug("Protocol __call__ cache miss. Adding key '%s'", str(_protocol_cache_key))
    210             try:
--> 211                 protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
    212             except TransportError as e:
    213                 # This can happen if, for example, autodiscover supplies us with a bogus EWS endpoint

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/protocol.py in __init__(self, *args, **kwargs)
    264             except TransportError:
    265                 pass
--> 266             self.version = Version.guess(self)
    267 
    268     def _create_session_pool(self):

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/version.py in guess(cls, protocol)
    210             shortname = None
    211         api_version = VERSIONS[shortname][0] if shortname else None
--> 212         return cls._guess_version_from_service(protocol=protocol, hint=api_version)
    213 
    214     @staticmethod

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/version.py in _guess_version_from_service(cls, protocol, hint)
    242         protocol.version = Version(build=None, api_version=hint or API_VERSIONS[-1])
    243         try:
--> 244             list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
    245         except (ErrorInvalidSchemaVersionForMailboxVersion, ErrorInvalidServerVersion):
    246             raise TransportError('Unable to guess version')

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/services.py in call(self, unresolved_entries, parent_folders, return_full_contact_data, search_scope, contact_data_shape)
   1647             return_full_contact_data=return_full_contact_data,
   1648             search_scope=search_scope,
-> 1649             contact_data_shape=contact_data_shape,
   1650         ))
   1651         for elem in elements:

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/services.py in _get_elements(self, payload)
     87             try:
     88                 # Send the request, get the response and do basic sanity checking on the SOAP XML
---> 89                 response = self._get_response_xml(payload=payload)
     90                 # Read the XML and throw any general EWS error messages. Return a generator over the result elements
     91                 return self._get_elements_in_response(response=response)

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/services.py in _get_response_xml(self, payload, **parse_opts)
    160                 data=wrap(content=payload, version=api_version, account=account),
    161                 allow_redirects=False,
--> 162                 stream=self.streaming,
    163             )
    164             if self.streaming:

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/util.py in post_ratelimited(protocol, session, url, headers, data, allow_redirects, stream)
    675         protocol.retire_session(session)
    676         try:
--> 677             _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
    678         finally:
    679             if stream:

/hdfs/app/GCS_ANA/shared_envs/envs/dsx3/lib/python3.6/site-packages/exchangelib/util.py in _raise_response_errors(response, protocol, log_msg, log_vals)
    745     if response.status_code == 401 and protocol.credentials.fail_fast:
    746         # This is a login failure
--> 747         raise UnauthorizedError('Wrong username or password for %s' % response.url)
    748     if 'TimeoutException' in response.headers:
    749         raise response.headers['TimeoutException']

UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx

**Comment by ecederstrand** [comment]
Hmm. That does look like an authentication issue. Can you use the exact same email address and password to log into https://outlook.office365.com via a browser? Does your organization use 2-factor auth or some other non-standard auth mechanism?

**Comment by suryareddy005** [comment]
I'm able to login to my account using the above URL.  Yes, my organization uses 2-factor auth.

**Comment by ecederstrand** [comment]
We don't support 2-factor auth yet - see #196. It's possible that your Exchange admins recently changed the auth setup for the EWS endpoint to OAuth, Kerberos or something else. You need to ask them which auth method you should use for EWS.

**Comment by suryareddy005** [comment]
Sure... I'm gonna check with them. Thanks for your support!

**Comment by ecederstrand** [comment]
Hi @suryareddy005 Did you find a solution to your problem?

**Comment by suryareddy005** [comment]
You are right exchange admins recently changed the auth setup. I haven't find the optimal way to access the outlook365 account. But for the time being, To access the account the Infosec IT team added some permissions to bypass 2-factor auth.

**Comment by ecederstrand** [comment]
Ok. Closing the issue, then. Feel free to re-open or add comments to #196 if you have additional insights.

**Comment by pallavjha25** [comment]
Hi @ecederstrand, I am writing a new program for doing some automation on my email. Have used the program in past, but not used for some time. now when I am trying to run, it gives me below error:-

Program pgm.py contains below code
```
import exchangelib
from exchangelib import DELEGATE, Account, Credentials,   Configuration, Message, Mailbox, HTMLBody, CalendarItem, \
    EWSDateTime, EWSTimeZone


class emailServer:
    __credentials = None
    __config = None
    __account = None

    def __init__(self):
        self.__credentials = Credentials( username='DOMAINName\corpid', password ='topsecret') # Single backward slash in username

        self.__config = Configuration(server='outlook.office365.com/EWS/Exchange.asmx',
                                      credentials=self.__credentials)
        self.__account = Account(
            primary_smtp_address="corpid@company.com", config=self.__config, autodiscover=False, access_type=DELEGATE)

if __name__ == "__main__":
    ex = emailServer()
```

Running python3.8 pgm.py gives below error  

```
Traceback (most recent call last):
  File "mailbox.py", line 24, in <module>
    ex = ExchangeServer()
  File "mailbox.py", line 18, in __init__
    self.__account = Account(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/account.py", line 132, in __init__
    self.version = self.protocol.version
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/protocol.py", line 437, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/version.py", line 230, in guess
    list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/services/resolve_names.py", line 32, in call
    for elem in elements:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/services/common.py", line 173, in _get_response_xml
    r, session = post_ratelimited(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/util.py", line 814, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/exchangelib/util.py", line 891, in _raise_response_errors
    raise UnauthorizedError('Invalid credentials for %s' % response.url)
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx/EWS/Exchange.asmx
```

I have read on this ticket and in #196. My organization has Ping ID enabled (2 Factor Authentication) but I am runnign this program being on corp network.

**Comment by ecederstrand** [comment]
Since you are on O365, you probably need to supply your username as an email address, not `DOMAIN\account`.

Apart from that, authentication errors are almost impossible for others to debug on a public list.

**Comment by cburkeinga** [comment]
Did your 0365 password expire?

**Comment by pallavjha25** [comment]
I think no, because this is my main work account that I use to login the same computer.

**Comment by Nirmalnk05** [comment]
> Did your 0365 password expire?

Yes, My  account password expires. After, updating it, I'm started facing this error.

**Comment by gitthegk** [comment]
exchangelib.errors.UnauthorizedError: Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx/EWS/Exchange.asmx

Getting this error
but this user doesn't have 2MFA and this has EWS also.
Please help me to resolve this issue

**Comment by ecederstrand** [comment]
I believe Office365 have finally shut down Basic authentication. You'll have to switch to OAuth instead.

**Comment by ecederstrand** [comment]
It's in the docs: https://ecederstrand.github.io/exchangelib/#oauth-on-office-365
