### ISSUE TITLE
How Specify Certificate for ESG

### ISSUE THREAD

**Issue by gprinz** [ecederstrand/exchangelib#664]
I would like to use exchangelib in a project, but in order to connect to the Exchange Server, a certificate must be specified because I have to use an enterprise service gateway. In normal post request, I'm doing the following:

answer = requests.post(url=ENDPOINT, data=request, verify=False, auth=auth, **cert=cert**)

How can I specify the path to the certificate similar as I can do it in a simple post request? And how can I turn off the verification?

**Comment by ecederstrand** [comment]
To do this, you should use a custom HTTP Adapter. See https://github.com/ecederstrand/exchangelib/blob/master/README.md#proxies-and-custom-tls-validation

**Comment by gprinz** [comment]
Using a custom HTTP adapter solves the problem.
