### ISSUE TITLE
after generated .exe using pyinstaller it give me error (no module named exchangelib)

### ISSUE THREAD

**Issue by Hesham-XQ** [ecederstrand/exchangelib#665]
I am writing python code to fetch inbox mails using credentials and I am using exchangelib and importing some modules but when I generate .exe file using pyinstaller it give me this error after run the .exe file (ModuleNotFoundError : No module named 'exchangelib')

I tried to solve it by change hidden imports in .spec file but it failed .

here is my impot libraries

```
from exchangelib import Account , Credentials , Configuration
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
```
any help please ??

**Comment by ecederstrand** [comment]
I think you will get better help if you post this question in a pyinstaller forum. I don’t think it’s an issue with exchangelib.

**Comment by Hesham-XQ** [comment]
sorry for that but I am still new here ..
could I ask another question please ?
I used this code 
```
for mailbox, contact in a.protocol.resolve_names(['anne', 'bart'], 
return_full_contact_data=True):
    print(mailbox.email_address, contact.display_name)
```
as equivalent to this one (item.sender.getExchangerUser().Alias) in win32com ..
is this right ? or I am missing something ??

**Comment by ecederstrand** [comment]
I'm sorry, but I don't have experience with the win32com interface, so I can't answer that.

**Comment by ecederstrand** [comment]
Solution to original question in https://stackoverflow.com/questions/58718826/after-generated-exe-using-pyinstaller-it-give-me-error-no-module-named-exchang
