### ISSUE TITLE
Supported fields in query sets

### ISSUE THREAD

**Issue by gprinz** [ecederstrand/exchangelib#667]
As stated in the documentation, a QuerySet can be used for searching items. For example, the statement 

qs.filter(subject__exact='foo')

returns all items with the subject 'foo'. Unfortunately, there is no list of supported fields. Which fields besides of the subject are supported? IS there a way to search for the sender or the recipient?

**Comment by ecederstrand** [comment]
Here's how to print the list of fields that are supported for e.g. Message items:

```python
from exchangelib import Message

print([f.name for f in Message.FIELDS])
```

A few of the fields do no support searching in EWS, so here's the list of fields that do support searching:

```python
from exchangelib import Message

print([f.name for f in Message.FIELDS if f.is_searchable])
```

**Comment by gprinz** [comment]
Hi Erik, thank you so much for you assistance. This is exactly what I was looking for!
