### ISSUE TITLE
Item.detach() only detaches half of the attachments

### ISSUE THREAD

**Issue by Zelwak** [ecederstrand/exchangelib#669]
Hello,

First, sorry for my bad English level.

I'm working on Odoo.
I synch interventions with an Exchange calendar with a queue job system: there are informations like start/end dates, location, description and also documents (PDF/XML).
On Odoo, when user update informations, there where an IrresolvableConflict error. I solved it with `item.save(conflict_resolution=ALWAYS_OVERWRITE)`. It works good.

My problem is for documents. On Odoo I keep items IDs but not for documents.
When user make a new version of a document, I detach all attachments of Exchange item and I attach all documents from Odoo.
Except that somtimes, on `item.detach()` method, I have this error:
`exchangelib.errors.ErrorIrresolvableConflict: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item., Cannot save changes made to an item to store.SaveStatus: IrresolvableConflict
`.
Error is not raised everytime. Sometime it works, sometime not.
How can I force detach of all attachments without "conflict_resolution=ALWAYS_OVERWRITE" parameter.

Here my code:
```python
if vals.get('documents'):
    if item.attachments:
        len_atta = len(item.attachments)
        for j in range(len_atta):
            item.detach(item.attachments[0]) # Error here

    if item.attachments:
        _logger.error("Tous les documents présents sur le RV n'ont pas dû être supprimés (id: {})".format(id))

    for doc in vals.get('documents'):
        if doc.file:
            file = FileAttachment(name=doc.name, content=base64.b64decode(doc.file), content_id=doc.name)
            item.attach(file)
    item.save(conflict_resolution=ALWAYS_OVERWRITE)
```
Note that I've made a loop to detach attachments because when I do `item.detach(item.attachments)`, all attachments are often not deleted (eg, 7 of 13).

Ask me if you want the full error traceback or more informations.

**Comment by ecederstrand** [comment]
You are trying to repeatedly detach the same attachment. You should do `item.detach(item.attachments[j])`, not `item.detach(item.attachments[0])`

**Comment by Zelwak** [comment]
No because when I call "item.attachments", it's updated

For example, if there are 6 docs:
```python
len_atta = len(item.attachments)
print('len_atta', len_atta)
for j in range(len_atta):
    print('Remaining attachments (before detach): {}'.format(len(item.attachments)))
    item.detach(item.attachments[0])
    print('Remaining attachments (after detach): {}\n'.format(len(item.attachments)))
```
=>
```
len_atta 6
Remaining attachments (before detach): 6
Remaining attachments (after detach): 5

Remaining attachments (before detach): 5
Remaining attachments (after detach): 4

Remaining attachments (before detach): 4
Remaining attachments (after detach): 3

Remaining attachments (before detach): 3
Remaining attachments (after detach): 2

Remaining attachments (before detach): 2
Remaining attachments (after detach): 1

Remaining attachments (before detach): 1
Remaining attachments (after detach): 0
```

And when it's done with "[j]":
```python
len_atta = len(item.attachments)
print('len_atta', len_atta)
for j in range(len_atta):
    print('j', j)
    print('Remaining attachments (before detach): {}'.format(len(item.attachments)))
    item.detach(item.attachments[j])
    print('Remaining attachments (after detach): {}\n'.format(len(item.attachments)))
```
=>
```
len_atta 6
j 0
Remaining attachments (before detach): 6
Remaining attachments (after detach): 5

j 1
Remaining attachments (before detach): 5
Remaining attachments (after detach): 4

j 2
Remaining attachments (before detach): 4
Remaining attachments (after detach): 3

j 3
    [...]
    item.detach(item.attachments[j])
    IndexError: list index out of range
```

**Comment by ecederstrand** [comment]
Ok, well you can just pass the entire list to detach. It takes both a single attachment and a list:

`item.detach(item.attachments)`

If it still doesn't work, please post the stack trace.

**Comment by Zelwak** [comment]
Thanks for your answer, but it didn't works.
When I do:
```python
if item.attachments:
    print('Before detach', len(item.attachments))
    item.detach(item.attachments)
    print('After detach', len(item.attachments))
```
I get with 13 attachments:
```
Before detach 13
After detach 6
```
With 19 attachments:
```
Before detach 19
After detach 9
```
With 22 attachments:
```
Before detach 22
After detach 11
```
I note that it delete always half of the attachments but without error.
This is the same case that I told you yesterday:
```python
len_atta = len(item.attachments)
print('len_atta', len_atta)
for j in range(len_atta):
    print('j', j)
    print('Remaining attachments (before detach): {}'.format(len(item.attachments)))
    item.detach(item.attachments[j])
    print('Remaining attachments (after detach): {}\n'.format(len(item.attachments)))
```

**Comment by ecederstrand** [comment]
Hmm, I'll try to see if I can reproduce this locally.

**Comment by Zelwak** [comment]
Ok thanks a lot!
I found a backup solution. With the job queue system of Odoo, I retry a job when it failed until it works. Often it works after 2 or 3 tries.
If you need, I can give you an extract of the full code which is used.

**Comment by ecederstrand** [comment]
Turns out this is really easy to reproduce:

```python
from exchangelib import Credentials, Account, Message, FileAttachment, DELEGATE

username, password = 'john@example.com', '********'
c = Credentials(username, password)
a = Account(primary_smtp_address=c.username, autodiscover=True, credentials=c, access_type=DELEGATE)

item = Message(folder=a.inbox, subject='test').save()
try:
    for i in range(20):
        item.attach(FileAttachment(name='my_file.txt', content=f'hello world {i}'.encode('utf-8')))

    print('Before detach', len(item.attachments))
    item.detach(item.attachments)
    print('After detach', len(item.attachments))
finally:
    item.delete()
```
Output:
```
Before detach 20
After detach 10
```
