### ISSUE TITLE
Unable to filter items by complex type properties

### ISSUE THREAD

**Issue by DavidPavlicek** [ecederstrand/exchangelib#67]
I’m using this code to get attachments from filtered items:
 
```
q = (Q(datetime_received__gt=tz.localize(EWSDateTime(2017, 1, 1))) & Q(subject__iexact='foo'))
for i in account.inbox.filter(q):
    for a in i.attachments:
        with open(a.name, 'wb') as file:
            file.write(a.content)
```
 
This code works as expected, but when I change `subject__iexast='foo' `to `sender__iexact='foo@example.com'` I got this error:
 
  File "C:\venv\exchangelib\lib\site-packages\exchangelib\restriction.py", line 292, in translate_fields
    raise ValueError("Complex field '%s' does not support filtering" % self.field)
ValueError: Complex field 'sender' does not support filtering
 
I think it’s because sender is instance of Mailbox class, not simple type…

It would be nice to have oportunity to filter items by complex type properties... At least for some subset of them (sender, from, etc..).

Reference: [https://msdn.microsoft.com/en-us/library/office/dn579422(v=exchg.150).aspx ]

**Comment by ecederstrand** [comment]
This should work now. Filtering on `to_recipients`, `reply_to` and other fields that hold multiple email addresses still doesn't work. I'm not sure EWS supports filtering on these fields at all.
