### ISSUE TITLE
Saving entire email with attachments as .msg file

### ISSUE THREAD

**Issue by bakarep** [ecederstrand/exchangelib#671]
I wanted to know if there is functionality to save email as .msg file to local filesystem. Could not find anything in api or on web. Please guide to the page if functionality already exists.

**Comment by ecederstrand** [comment]
Duplicate of https://github.com/ecederstrand/exchangelib/issues/475

**Comment by MarcAllain** [comment]
Hi everybody,
I do not agree with the "duplicate" action on this issue.
The [#475](https://github.com/ecederstrand/exchangelib/issues/475) deals with generating "*.eml" file, the question was about generatin "*.msg" files ... ?

**Comment by ecederstrand** [comment]
There's no standard for neither .msg nor .eml files. Tools can dump whatever they like in a file and give it either suffix. But usually it will be the MIME content in both cases. Hence the duplicate.
