### ISSUE TITLE
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed

### ISSUE THREAD

**Issue by ytzk507** [ecederstrand/exchangelib#673]
I try the example code as follows:

```python
from exchangelib import Credentials, Account

credentials = Credentials('john@example.com', 'topsecret')
account = Account('john@example.com', credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)`
```

And then got above error.
python3.7,exchangelib 2.1.9
Thanks

**Comment by ecederstrand** [comment]
The autodiscover protocol is fragile, and our implementation of it is not entirely standards-compliant (and there is no standard to adhere to, either).

There are multiple other issues tracking this (#337, #502, #228), so I'm closing this one. I would suggest comparing the autodiscover steps in the log output of exchangelib with the output from an autodiscover test at https://testconnectivity.microsoft.com to see where we differ.

A workaround is to not use autodiscover and point directly to the EWS server instead.

**Comment by ytzk507** [comment]
Thanks very much. I will have a try to pint directly to the EWS server.
