### ISSUE TITLE
error info "unable to get local issuer certificate'

### ISSUE THREAD

**Issue by ytzk507** [ecederstrand/exchangelib#674]
Error occured when I try go connect to exchange with following code:
``credentials = Credentials(
    username=ews_username, password=ews_password)
config = Configuration(service_endpoint=ews_url, credentials=credentials)
account = Account(primary_smtp_address=ews_email, config=config)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)``

Error info as follows:
Failed to create cached protocol with key ('https://mail.sh****.com/EWS/Exchange.asmx', Credentials('sh**.com\\07*****58', '********')): HTTPSConnectionPool(host='mail.sh******.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'protocol'

During handling of the above exception, another exception occurred:
----------------------

Any info can help me? Cant' find similar issue like this. Thanks & best regards.

**Comment by ecederstrand** [comment]
There is a certificate error trying to access `mail.sh****.com`. This is not an exchange-specific issue. You will most likely get the same error if you do:

```python
import requests
requests.get(`https://mail.sh****.com/EWS/Exchange.asmx`)
```

The fix might be to add the root certificate to the certificate store of you OS, or inject the certificate using a custom HTTP adapter: https://github.com/ecederstrand/exchangelib#proxies-and-custom-tls-validation

**Comment by ytzk507** [comment]
Thanks very much. I will have a try.
