### ISSUE TITLE
Access denied for shared calendar

### ISSUE THREAD

**Issue by Slyfoxy** [ecederstrand/exchangelib#676]
Hi! I found a problem while I was using `account.root`.

When I'm trying to get someone else's calendar via a request, `exchangelib` raises the following error: `exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again., Underlying MAPI stream threw exception`

Version: 2.0.1

Code example:
```python

version = Version(build=Build(15, 2, 397, 5))

username = "DOMAIN\\testuser02"  # my user
config = Configuration(
    service_endpoint=server,
    credentials=Credentials(username=username, password=password),
    version=version,
    auth_type=NTLM,
)
a = Account(
    primary_smtp_address="testuser01@domain.com",  # shared calendar account 
    config=config,
    autodiscover=False,
    access_type=DELEGATE,
)

a.root  # error Access denied

```
I compared my request with the [Ews Editor](https://github.com/dseph/EwsEditor) request and found the problematic field. It is:

```xml
<t:FieldURI FieldURI="folder:PermissionSet"/>
```

I found myself a temporary solution, and I wonder if there's a better way to fix this issue

```python
# exchangelib.util.py

def set_xml_value(elem, value, version, index=None):
    from .ewsdatetime import EWSDateTime, EWSDate
    from .fields import FieldPath, FieldOrder
    from .properties import EWSElement
    from .version import Version
    
    if "AdditionalProperties" in str(elem):
        from exchangelib.fields import PermissionSetField
        if isinstance(value[5].field, PermissionSetField):
            p = value.pop(5)
	# ...

**Comment by ecederstrand** [comment]
Try upgrading to version 2.1.0. There is an issue with `PermissionSet` where it's not supported on Exchange 2016. See https://github.com/ecederstrand/exchangelib/issues/610.

While is seems you're not on Exchange 2016, it may be that the shared mailbox is.

Feel free to re-open If version 2.1.0 does not fix your issue. There may be other Exchange versions that also do not support this field.
