### ISSUE TITLE
Error at copy an event to a calendar of another account

### ISSUE THREAD

**Issue by DirkJo** [ecederstrand/exchangelib#678]
Hello,
at first: Thank you for exchangelib, it is very helpful and as far as I can say a great work :+1: 
I got the following error, when I copy an event to a calendar of another account. A copy in another calendar of the same account works fine. The response data of the logging give NoError.
Best regards Dirk

**File testcopy.py:**
`
from exchangelib import Credentials, Account, EWSDateTime
from datetime import timedelta

credentials = Credentials('login', 'password')
meiner = Account('account', credentials=credentials, autodiscover=True)
kalender = Account('account2', credentials=credentials, autodiscover=True)

for item in meiner.calendar.all().order_by('-datetime_sent')[:1]:
    print(item.subject,item.start)
    print(item.id,item.changekey)

mytest=meiner.calendar / 'test'
ev=meiner.calendar.get(id=item.id,changekey=item.changekey)
ev.copy(to_folder=mytest)

logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
ev.copy(to_folder=kalender.calendar )`

**python3 testcopy.py**
Dirk geht früher 2019-11-20 15:00:00+00:00
AAMkAGRlNDc0MGY4LTk5YWQtNGY0Mi04YjVkLWRkOGZmNmI3YTA5OQBGAAAAAABZB/RTRf6dSL1KaFwz2yrVBwBuPP5NpyF+QYhj40YU6bIJAAAAAAENAABuPP5NpyF+QYhj40YU6bIJAAHERhagAAA= DwAAABYAAABuPP5NpyF+QYhj40YU6bIJAAHDxk6M
Traceback (most recent call last):
  File "testcopy.py", line 17, in <module>
    ev.copy(to_folder=kalender.calendar)
  File "/home/nuclos/.local/lib/python3.6/site-packages/exchangelib/items.py", line 375, in copy
    raise ValueError('Expected result length 1, but got %s' % res)
ValueError: Expected result length 1, but got []

**Comment by ecederstrand** [comment]
Does the copy actually work - i.e. do you see the copied event in the destination calendar afterwards?

**Comment by DirkJo** [comment]
That's strange: Yes, I see the event now after a full browser refresh of Web-Outlook. My calendar test is on my account and show immediately the event, the calendar of the other account did not update without refresh.
I am sorry, but happy - it works.
The only question: why the error message?
For me it's closed.

**Comment by ecederstrand** [comment]
The error message happens because we were expecting EWS to return an ID and a changekey for the copied item, but that only happens when you copy to a folder within the same mailbox. So the check we have on the return value is too strict.
