### ISSUE TITLE
Rertrieving Values from QuerySets

### ISSUE THREAD

**Issue by gprinz** [ecederstrand/exchangelib#679]
As described in the inbox, it is possible to query the items of a mailbox with the following statement:
```
 q = (Q(subject__icontains='ch mim | inc'))
 items = inbox.filter(q)
```
items are of type QuerySet, but how can we extract information out of them (for example the item id or change key?)

**Comment by ecederstrand** [comment]
`items` is a QuerySet, but the items within the QuerySet are e.g. `Message` instances:

```python
for item in inbox.filter(q):
    print(item.__class__.__name__, item.id)
```

**Comment by gprinz** [comment]
This works perfectly fine, but there seems to be a problem when iterating over the QuerySets. Let me illustrate this:

We have 

` q = (Q(subject__icontains='some filter'))
 items = inbox.filter(q)`

and lets say the QuerySet contains 50 Message instances.

If I iterate over the entire QuerySet 

`example_list = [queries.move_template.format(id=item.id, key=item.changekey) for item in items]`

, it takes a very long time or ends in an error. But if I do

`move_elements = [queries.move_template.format(id=item.id, key=item.changekey) for item in items[0:len(items)-1]
`
, everything works much faster. Do you have any idea what the reason might be?

**Comment by ecederstrand** [comment]
If you are only interested in the ID and changekey, then you can optimize your query by using `.only()` to limit the number of fields you are fetching.

By default QuerySets cache their result internally, so what is most likely happening in the 2nd line is that the result has already been cached so you are not hitting the server.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this did not answer your questions
