### ISSUE TITLE
[Q] possible to work against local ics files?

### ISSUE THREAD

**Issue by laur89** [ecederstrand/exchangelib#681]
exchangelib is doing amazing work at interacting with the DAV servers.

a) Would it still be possible to use the library against local .ics files that are being kept in-sync by other means (eg by [vdirsyncer](https://github.com/pimutils/vdirsyncer/))?
b) if not, does exchangelib offer similar support for synchronization?

**Comment by ecederstrand** [comment]
By .ics files I assume you mean calendar files? exchangelib can't read or write from those files, but there are Python libraries that can, and you could use exchangelib as part of a program that synced to or from that file.

exchangelib is used by many to sync calendars. Currently only in a polling fashion since the build-int sync services of EWS are not supported.

**Comment by laur89** [comment]
> By .ics files I assume you mean calendar files?
correct.

> exchangelib is used by many to sync calendars. Currently only in a polling fashion since the build-int sync services of EWS are not supported.
my use-case is similar, in that a script polls at regular interval next X days' worth of calendar data, unpacks it (ie expands the recurring events), and then operates on said data. But this isn't really syncing, in that it always pulls all the data down, not only delta.
Did you mean same by "sync", or am i not aware of a delta resolution?

**Comment by ecederstrand** [comment]
There are various ways og dealing with this depending on the sync features you need to support. The simplest is probably to maintain a lokal list of ID/changekey pairs and find your delta by fetching  a new list of ID’s from the server every time you sync. Fetching ID’s is cheap with EWS.

**Comment by laur89** [comment]
Cool. This should handle nicely event creation & deletion. Would it cover event changes as well?

**Comment by ecederstrand** [comment]
Event changes is what the `changekey` tracks.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional questions.
