### ISSUE TITLE
sender email_address unproperly parsed

### ISSUE THREAD

**Issue by immez** [ecederstrand/exchangelib#684]
I am not sure if this is a situation that conflicts with RFC or any protocols.
But if there was a comma in the sender name, exchangelib may parse it as multi-senders?
E,g: a mail whose mime_content contains "From: immez, Co. Ltd <immez@xxx.yyy>"
the mail.sender.email_address will be immez, and the chars after the comma will be ignored?

**Comment by ecederstrand** [comment]
The sender and mime_content fields are sent as separate values by EWS, so there is no connection between the two fields as far as exchangelib is concerned. If you look at the response XML, you will probably see that this is just how EWS sends the values. I don't think this is an issue with exchangelib.

**Comment by immez** [comment]
Sorry, I can not find the example just now, maybe this is an unproper issue that should be closed.
