### ISSUE TITLE
How to use FindPeople?

### ISSUE THREAD

**Issue by marekk1717** [ecederstrand/exchangelib#685]
I'm trying to find manager assigned to user. First I need to find contact/user. "GAL Contacts" is empty. I think it should be possible with FindPeople. Do you have any idea how it can be used?

**Comment by marekk1717** [comment]
I've already found answer to this question. We can use pyad module to get user's manager.

**Comment by ecederstrand** [comment]
In general, you use the `FindPeople` service by adding `.people()` to the queryset.
