### ISSUE TITLE
Access to large file attachments (In version 2.1.0)

### ISSUE THREAD

**Issue by joanrodriguezr** [ecederstrand/exchangelib#686]
Hi Erik,

I need to retrieve large attachments recursively in on an attached message which has inside it the PDF file attached which I want to access.

I have been looking at the different Issues another users have opened in your project, and tried to apply some of the changes you have proposed them but I can't see a proper solution to the need I have.

If I filter items with this:

account.inbox.all().only('subject','datetime_received','sender','body','attachments','headers','mime_content')

I get the ERROR:  " 'NoneType' object has no attribute 'name' "

But if I filter with this:
account.inbox.all().only('subject','datetime_received','sender','body','attachments','headers')

And I try to access with mailItem.attachment I get 1 attachment for the very first Message (which has instance of ItemAttachment) but it does not have the second level attachment:

Message(sensitivity='Normal', attachments=[], importance='Normal', reminder_is_set=False, reminder_minutes_before_start=0, is_read_receipt_requested=False, is_delivery_receipt_requested=False, is_read=False, is_response_requested=False)

Can you shed some light on this please?

Thank you very much!

**Comment by joanrodriguezr** [comment]
I have tried the following change in the fields.py code (in class Base64Field(FieldURIField) ):

    def from_xml(self, elem, account):
        val = self._get_val_from_elem(elem)
        if val is not None:
            try:
                padding = len(val)%4
                if padding > 0:
                    log.warning("Current Padding for val is %d", (len(val)%4))
                    val += '='* (4 - padding)

                log.warning("New padding for modified val is %d", (len(val)%4))
                return base64.b64decode(val)
            except (TypeError, binascii.Error) as e:
                print(e)
                log.warning("Elem %s val len is = %d Cannot convert value on field '%s' to type %s", elem,len(val),self.name, self.value_cls)
                return None
        return self.default

But it is still failign and generates the following logs:

Current Padding for val is 1

New padding for modified val is 0

Invalid base64-encoded string: number of data characters (9999085) cannot be 1 more than a multiple of 4

Elem <Element {http://schemas.microsoft.com/exchange/services/2006/types}Message at 0x5e481b3b88> val len is = 9999088 Cannot convert value on field 'mime_content' to type <class 'str'>

**Comment by joanrodriguezr** [comment]
And this is what I get from the DEBUG traces activated (within exchange server):

lDQWdJQzlUYVhwbElEWU5DaUFnSUNBdlVtOXZkQ0F4SURBZ1VnMEtQajROQ25OMFlYSjBlSEpsWmcwS056TTBPRGN4RFFvbEpVVlANClJnMEsNCg0KLS1fMDI0X0NBR1Z5TVRTVkVlTWVMVHRlQ2NhYVFxT2p5OUxnOTJEd3NCc3NWTVU1dTZldWt4SHdtYWlsZ21fLS0NCg0KLS1fMDA0XzJGMDRGMTJCMEU1
RERCNDU5N0U5NDBFNkZDMDA1MjVEM0Q2RTM4M0NWTUVTQ0wxMDBYQ01QMDVfLS0NCg==</t:MimeContent>
              <t:ItemId Id="AAMkADhmY2UwY2U3LWE0NGQtNDBjMy05ZDk5LTE3OTVjNzY1MGVjZABGAAAAAAB8DfEro8KET4jLDh99mxhGBwBuFvQUYW+fTJPq2cUqNLL/AAAAxZIXAADN+kPEJKKSQ5LcrCyfCR6vAZACZZ4oAAA="←[39;49;0
0m ChangeKey="CQAAABYAAABuFvQUYW+fTJPq2cUqNLL/AAAAxh8p"/>
              <t:ParentFolderId Id="AAMkADhmY2UwY2U3LWE0NGQtNDBjMy05ZDk5LTE3OTVjNzY1MGVjZAAuAAAAAAB8DfEro8KET4jLDh99mxhGAQBuFvQUYW+fTJPq2cUqNLL/AAAAxZIXAAA=" ChangeKey="AQAAAA=="/>
              <t:ItemClass>IPM.Note</t:ItemClass>
              <t:Subject>RV: Subject of the first level email</t:Subject>
              <t:Sensitivity>Normal</t:Sensitivity>
              <t:Body BodyType="HTML">....</t:Body>
              <t:Attachments>
                <t:ItemAttachment>
                  <t:AttachmentId Id="AAMkADhmY2UwY2U3LWE0NGQtNDBjMy05ZDk5LTE3OTVjNzY1MGVjZABGAAAAAAB8DfEro8KET4jLDh99mxhGBwBuFvQUYW+fTJPq2cUqNLL/AAAAxZIXAADN+kPEJKKSQ5LcrCyfCR6vAZACZZ4oAAABBgAEAAAAAAA="/>
                  <t:Name>Second level message subject</t:Name>
                  <t:ContentId/>
                  <t:Size>19256273</t:Size>
                  <t:LastModifiedTime>2019-11-26T16:42:45</t:LastModifiedTime>
                  <t:IsInline>false</t:IsInline>
                </t:ItemAttachment>
              </t:Attachments>
              <t:DateTimeReceived>2019-12-03T10:42:43+01:00</t:DateTimeReceived>
              <t:Size>19296848</t:Size>
              <t:Importance>Normal</t:Importance>
              <t:InReplyTo>sensitivedata</t:InReplyTo>
              <t:IsSubmitted>false</t:IsSubmitted>
              <t:IsDraft>false</t:IsDraft>
              <t:IsFromMe>false</t:IsFromMe>
              <t:IsResend>false</t:IsResend>
              <t:IsUnmodified>true</t:IsUnmodified>
              <t:InternetMessageHeaders>
                <t:InternetMessageHeader HeaderName="Received">from internal server</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Content-Type">application/ms-tnef</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Content-Transfer-Encoding">binary</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Subject">RV: Subject of the first level email</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Thread-Topic">Subject of the first level email</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Thread-Index">AdWkb73++rAEnEtORY6CXj+Zv5JkFAFTiqUg</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Date">Tue, 3 Dec 2019 10:42:34 +0100</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Message-ID">sensitivedata</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="References">sensitivedata</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="In-Reply-To">sensitivedata</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Accept-Language">es-ES, en-US</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="Content-Language">es-ES</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-MS-Has-Attach">yes</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-MS-Exchange-Organization-SCL">-1</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-MS-TNEF-Correlator">sensitivedata</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="MIME-Version">1.0</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-MS-Exchange-Organization-AuthSource">sensitivedata</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-MS-Exchange-Organization-AuthAs">Internal</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-MS-Exchange-Organization-AuthMechanism">04</t:InternetMessageHeader>
                <t:InternetMessageHeader HeaderName="X-Originating-IP">sensitivedata</t:InternetMessageHeader>
              </t:InternetMessageHeaders>
              <t:DateTimeSent>2019-12-03T10:42:34+01:00</t:DateTimeSent>
              <t:DateTimeCreated>2019-12-03T10:42:40+01:00</t:DateTimeCreated>
              <t:ReminderIsSet>false</t:ReminderIsSet>
              <t:ReminderMinutesBeforeStart>0</t:ReminderMinutesBeforeStart>
              <t:DisplayCc/>
              <t:DisplayTo>sensitivedata</t:DisplayTo>
              <t:HasAttachments>true</t:HasAttachments>
              <t:Culture>es-ES</t:Culture>
              <t:EffectiveRights>
                <t:CreateAssociated>false</t:CreateAssociated>
                <t:CreateContents>false</t:CreateContents>
                <t:CreateHierarchy>false</t:CreateHierarchy>
                <t:Delete>true</t:Delete>
                <t:Modify>true</t:Modify>
                <t:Read>true</t:Read>
                <t:ViewPrivateItems>true</t:ViewPrivateItems>
              </t:EffectiveRights>
              <t:LastModifiedName>sensitivedata</t:LastModifiedName>
              <t:LastModifiedTime>2019-12-04T17:32:35+01:00</t:LastModifiedTime>
              <t:IsAssociated>false</t:IsAssociated>
              <t:WebClientReadFormQueryString>sensitivedata@sensitivedata.com/?ae=Item&amp;a=Open&amp;t=IPM.Note&amp;id=RgAAAAB8DfEro8KET4jLDh99mxhGBwBuFvQUYW%2bfTJPq2cUqNLL%2fAAAAxZIXA
ADN%2bkPEJKKSQ5LcrCyfCR6vAZACZZ4oAAAJ&amp;exvsurl=1</t:WebClientReadFormQueryString>
              <t:ConversationId Id="AAQkADhmY2UwY2U3LWE0NGQtNDBjMy05ZDk5LTE3OTVjNzY1MGVjZAAQAPqwBJxLTkWOgl4/mb+SZBQ="/>
              <t:UniqueBody BodyType="HTML">....</t:UniqueBody>
              <t:Sender>
                <t:Mailbox>
                  <t:Name>sensitivedata</t:Name>
                  <t:EmailAddress>sensitivedata@sensitivedata.com</t:EmailAddress>
                  <t:RoutingType>SMTP</t:RoutingType>
                  <t:MailboxType>Mailbox</t:MailboxType>
                </t:Mailbox>
              </t:Sender>
              <t:ToRecipients>
                <t:Mailbox>
                  <t:Name>sensitivedata</t:Name>
                  <t:EmailAddress>sensitivedata@sensitivedata.com</t:EmailAddress>
                  <t:RoutingType>SMTP</t:RoutingType>
                  <t:MailboxType>Mailbox</t:MailboxType>
                </t:Mailbox>
              </t:ToRecipients>
              <t:IsReadReceiptRequested>false</t:IsReadReceiptRequested>
              <t:IsDeliveryReceiptRequested>false</t:IsDeliveryReceiptRequested>
              <t:ConversationIndex>AdWkb73++rAEnEtORY6CXj+Zv5JkFAFTiqUg</t:ConversationIndex>
              <t:ConversationTopic>Subject of the first level email</t:ConversationTopic>
              <t:From>
                <t:Mailbox>
                  <t:Name>sensitivedata</t:Name>
                  <t:EmailAddress>sensitivedata@sensitivedata.com</t:EmailAddress>
                  <t:RoutingType>SMTP</t:RoutingType>
                  <t:MailboxType>Mailbox</t:MailboxType>
                </t:Mailbox>
              </t:From>
              <t:InternetMessageId>sensitivedata</t:InternetMessageId>
              <t:IsRead>true</t:IsRead>
              <t:IsResponseRequested>false</t:IsResponseRequested>
              <t:References>sensitivedata</t:References>
              <t:ReceivedBy>
                <t:Mailbox>
                  <t:Name>sensitivedata</t:Name>
                  <t:EmailAddress>sensitivedata@sensitivedata.com</t:EmailAddress>
                  <t:RoutingType>SMTP</t:RoutingType>
                  <t:MailboxType>Mailbox</t:MailboxType>
                </t:Mailbox>
              </t:ReceivedBy>
              <t:ReceivedRepresenting>
                <t:Mailbox>
                  <t:Name>sensitivedata</t:Name>
                  <t:EmailAddress>sensitivedata@sensitivedata.com</t:EmailAddress>
                  <t:RoutingType>SMTP</t:RoutingType>
                  <t:MailboxType>Mailbox</t:MailboxType>
                </t:Mailbox>
              </t:ReceivedRepresenting>
            </t:Message>
          </m:Items>
        </m:GetItemResponseMessage>
      </m:ResponseMessages>
    </m:GetItemResponse>
  </s:Body>
</s:Envelope>

**Comment by johnvonneumann36** [comment]
Hi Joan,

I meet the same problem. Before that, i have raised an issue #670. Accroding to the solution, i updated my Exchangelib to 2.1.1, but the problem is still there. The padding is correct, but str object can not be decoded.

**Comment by ecederstrand** [comment]
Hi @joanrodriguezr Can you please test with version 2.1.1, if you aren't doeing so already? Also if you still get the `NoneType' object has no attribute 'name'` error, please post the full stack trace here.

**Comment by nburlett** [comment]
I've run into what seems to be a similar problem. I have an email with a 50MB attachment, which makes the `mimecontent` tag HUGE. 

My current theory (still debugging) is that [lxml has a 10MB limit on text nodes](https://stackoverflow.com/a/33831595) . This makes the `mimecontent` node return only 10MB of text. The mimecontent node is the first node handled, and it seems that all subsequent nodes end up with None or some default value.

**Comment by nburlett** [comment]
I was able to work around the maximum size by telling the `exchangelib.util.ForgivingParser` to set the `huge_tree` option:

```diff
 class ForgivingParser(GlobalParserTLS):
     parser_config = {
         'resolve_entities': False,
         'recover': True,  # This setting is non-default
+         'huge_tree': True,
     }
```

According to the [lxml documentation](https://lxml.de/api/lxml.etree.XMLParser-class.html), this option: 

> `huge_tree `- disable security restrictions and support very deep trees
>  * and very long text content (only affects libxml2 2.7+)

I believe the security concern is denial-of-service due to large memory usage, but it's hard to find documentation on that. 

I suggest exchangelib have an option to enable huge_tree in the parser, but perhaps it should be off by default.

**Comment by ecederstrand** [comment]
Good find, @nburlett ! I just committed that option. I think it's fine to have it on always. Rogue Exchange servers is not a threat scenario I'm really worried about, and the consequences are not catastrophic. And I think we should be able to parse even huge attachments by default.
