### ISSUE TITLE
Client Access server version

### ISSUE THREAD

**Issue by Ads5740** [ecederstrand/exchangelib#692]
Hi,

I'm probably doing something wrong.
I'm getting the following error:

"The Client Access server version doesn't match the Mailbox server version of the resource that was being accessed. To determine the correct URL to use to access the resource, use Autodiscover with the address of the resource."

The server version is returned correctly:

"""Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="0" MajorBuildNumber="1497" MinorBuildNumber="0" Version="V2_23" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body><m:FindItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:FindItemResponseMessage ResponseClass="Error"><m:MessageText>The Client Access server version doesn't match the Mailbox server version of the resource that was being accessed. To determine the correct URL to use to access the resource, use Autodiscover with the address of the resource.</m:MessageText><m:ResponseCode>ErrorWrongServerVersion</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:MessageXml><t:Value """

In the python code I have set the following:

```Python
version = Version(build=Build(15, 0, 1497, 0))
config = Configuration(server=server, credentials=credentials, version=version, auth_type=NTLM)
account = Account(primary_smtp_address=address, config=config, autodiscover=False, access_type=DELEGATE)
```
In order to match, but I can't get it to work, any help would be appreciated

**Comment by ecederstrand** [comment]
It could be that the server version of the server hosting the Mailbox is different than the server responding to your request. What happens if you don't specify the version explicitly?

**Comment by ecederstrand** [comment]
@Ads5740 Did you get anywhere with this issue?

**Comment by Ads5740** [comment]
Negative, I didn't, so we reverted the mailbox back onto 2013.

**Comment by ecederstrand** [comment]
Ok, closing as we will not be able to reproduce
