### ISSUE TITLE
Set Parameter for Meeting

### ISSUE THREAD

**Issue by pradipanand** [ecederstrand/exchangelib#694]
I am not able to set AlldayEvent and Free(Appointment) in meeting, could you please help.

**Comment by ecederstrand** [comment]
What did you try?

**Comment by pradipanand** [comment]
item = CalendarItem(
    account=account,
    folder=account.calendar,
    start=account.default_timezone.localize(EWSDateTime(2019, 12, 19, 00, 00)),
    end=account.default_timezone.localize(EWSDateTime(2019, 12, 19, 00, 00)),
    item.AllDayEvent = True,
    subject="Subject of Meeting",
    body="Please come to my meeting",
    required_attendees=['pradip.anand@xyzcom']
)

How to add here all day event and Free. I tried like that..

**Comment by pradipanand** [comment]
and different way, what i can see in search.

**Comment by pradipanand** [comment]
I am able to to do by below 
is_all_day = True,

**Comment by pradipanand** [comment]
I found my self but thanks for creating this api.
