### ISSUE TITLE
Support OAuth authorization code grant

### ISSUE THREAD

**Issue by dmcgee** [ecederstrand/exchangelib#698]
The work for #90 (#630) added support for the client credentials OAuth grant type, which is suitable for an application used internally by an organization to access its own accounts. However, (for example) a hosted service with multiple accounts using exchangelib to access different Microsoft tenants needs to be able to restrict actions taken on behalf of users to only the accounts they've authorized. The client credentials grant cannot make that guarantee since it only conveys the Microsoft tenant ID in the authorization redirect (which is subject to tampering by the authorizing user), and then it relies on the application to provide the tenant ID it wants to operate on with no verification.

A solution for that problem would be to support the authorization code OAuth 2.0 grant type. This flow returns a signed code during authorization, which the application exchanges for an access token. Microsoft ensures that the token only provides access to the originally authorized tenant, so as long as the application is secure there's no opportunity for users to gain access to Microsoft tenants they don't own.

One challenge is access token handling and refreshing: unlike with the client credentials grant, the application doesn't have a static set of credentials that can yield a new access token at any time, and instead it relies on a refresh token returned with the access token. Since the refresh token changes with each refresh, the application must cache tokens to avoid requiring users to re-authorize each time the application restarts, and it needs to refresh tokens as they expire.

I've prepared an implementation and I'll open a pull request shortly.

**Comment by ecederstrand** [comment]
Hi @dmcgee Thanks for raising the issue, and thanks for the contribution! I'll have time for a review within the next couple of days.
