### ISSUE TITLE
Get mailbox properties failure

### ISSUE THREAD

**Issue by sumansouravsingh** [ecederstrand/exchangelib#701]
Hi @ecederstrand ,
While trying to get properties for a particular mailbox i get the following error:

> **'Access is denied. Check credentials and try again., Non-system logon cannot access Audits folder.'**

at the following line in file services.py in method `_get_element_container` while its trying to access the folder - Recoverable items.

Also, when the mailbox does not have any item in it, it works fine (all the folders and its structure is displayed properly)

Here is the stack trace:

> File "C:\Commvault\Automation\Application\Exchange\ExchangeMailbox\exchangelib_helper.py", line 258, in get_mailbox_properties
>     folder, processed_folder_list, count)
>   File "C:\Commvault\Automation\Application\Exchange\ExchangeMailbox\exchangelib_helper.py", line 327, in get_message_properties_helper
>     if folder.all().exists():
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\queryset.py", line 474, in exists
>     return self.count() > 0
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\queryset.py", line 470, in count
>     return len(list(new_qs.__iter__()))
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\queryset.py", line 197, in __iter__
>     for val in result_formatter(self._query()):
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\queryset.py", line 272, in _as_items
>     for i in iterable:
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\folders.py", line 435, in find_items
>     for i in items:
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 319, in _paged_call
>     rootfolder, next_offset = self._get_page(response)
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 339, in _get_page
>     rootfolder = self._get_element_container(message=response[0], name='{%s}RootFolder' % MNS)
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 256, in _get_element_container
>     self._raise_errors(code=response_code, text=msg_text, msg_xml=msg_xml)
>   File "C:\Program Files\Python36\lib\site-packages\exchangelib\services.py", line 273, in _raise_errors
>     raise vars(errors)[code](text)

Can you tell me what the error might be. The service account i am using to access the mailbox has global admin rights

**Comment by ecederstrand** [comment]
It seems you are attempting to access a folder that Exchange does not allow you to access. It's an error from the server so not something we can really fix in exchangelib. If you have admin rights, it could be either a bug in Exchange or a policy on that folder denying your access.

**Comment by ecederstrand** [comment]
Hi @sumansouravsingh Did you get anywhere with this?

If not, I think your best bet is to do a try/catch on this exception type around the `folder.all().exists()` call in your `get_message_properties_helper()` method.

**Comment by sumansouravsingh** [comment]
Hi @ecederstrand . No luck as of yet. I might have to skip getting the properties for this case. I might raise a ticket with Microsoft maybe since this works for on prem exchange servers but fails for exchange online. Thank you for the help. Marking the topic as closed since nothing can be fixed from your side
