### ISSUE TITLE
No permission to see folder:PermissionSet

### ISSUE THREAD

**Issue by nburlett** [ecederstrand/exchangelib#702]
When attempting to access an account for which I have delegated access, I see `ErrorAccessDenied: Access is denied. Check credentials and try again.` due to the request for `permission_set` on the root of the hierarchy. 

This is different from #610  in that the server I'm working with is `EXCHANGE_2013_SP1`, and the field does exist in that version. The problem is just that the credentialed user doesn't have permission to see the `permission_set` of the delegated account. It's also different in that it's the `folders.roots.RootOfHierarchy` that's the problem and not the `folders.Folder` fields.

Removing this field from `folders.roots.RootOfHierarchy` allows me to access the subfolders of the account to which my user has delegated access:

```diff
     LOCAL_FIELDS = [
-        PermissionSetField('permission_set', field_uri='folder:PermissionSet', supported_from=EXCHANGE_2007_SP1,
-                            deprecated_from=EXCHANGE_2016),
         EffectiveRightsField('effective_rights', field_uri='folder:EffectiveRights', is_read_only=True,
                              supported_from=EXCHANGE_2007_SP1),
     ]
```
alternatively, this monkey-patch:

```python
from exchangelib.folders.roots import RootOfHierarchy
original_fields = RootOfHierarchy.FIELDS
RootOfHierarchy.FIELDS = [f for f in RootOfHierarchy.FIELDS if f.name != 'permission_set']
```

Perhaps permission_set shouldn't be requested by default for the root folder?

**Comment by ecederstrand** [comment]
I opted to remove the field entirely on folder roots. I've seen a lot of reports of failures in the wild, and I believe the advantage of keeping the field is minimal.
