### ISSUE TITLE
Unable to reply to mail while keeping the same conversation id.

### ISSUE THREAD

**Issue by angyangcheng** [ecederstrand/exchangelib#703]
I replied to an email thread using the following code below:
```
	def replymail(self, replyid, message):
		self.login()
		self.replyitem = self.a.inbox.get(id=replyid)
		self.reply = self.replyitem.create_reply("Re: "+self.replyitem.subject, message)
		self.msg = self.reply.save(self.a.drafts)
		self.msg.send()
```
However, by doing so, the email I sent has a different conversation_id as the rest of the emails in this thread. Anyone has any idea how I can retain the conversation_id in my sent mail as I am trying to display the conversation thread based on the conversation_id in my UI. Any help is appreciated. Thank you.

**Comment by ecederstrand** [comment]
It's unclear if EWS allows to write conversation IDs when creating objects. This is tracked in https://github.com/ecederstrand/exchangelib/issues/642 but nobody is working actively on it, AFAIK.

**Comment by angyangcheng** [comment]
Thanks for the reply. Also, is there any way I can change the content of a reply mail that I have created and saved into drafts before I send it out?

**Comment by ecederstrand** [comment]
`create_reply()` regturns a `ReplyItem` instance. If defines these fields that you can change before sending:

https://github.com/ecederstrand/exchangelib/blob/04b6ea1f5cd55c0d7fc80f93a6be5edb0ac61aa1/exchangelib/items/base.py#L101

**Comment by ecederstrand** [comment]
Closing as we're tracking the conversation ID issue in #642
