### ISSUE TITLE
Hashing fails for credentials objects containing an access token

### ISSUE THREAD

**Issue by dmcgee** [ecederstrand/exchangelib#704]
A recent change to the hashing logic in `exchangelib.credentials` switched from each subclass defining its own hashing behavior to a uniform implementation in `BaseCredentials`. However, `OAuth2Credentials` and its subclass(es) need special handling for `access_token`, which is a `dict` and not hashable:

```
  File ".../.pyenv/versions/3.8.0/lib/python3.8/site-packages/exchangelib-2.1.1-py3.8.egg/exchangelib/credentials.py", line 67, in __hash__
    return hash(tuple(getattr(self, k) for k in self.__dict__.keys() if k != '_lock'))
TypeError: unhashable type: 'dict'
```

`OAuth2Credentials` should use the `access_token` string field from its `access_token` attribute in the hash instead of the full dictionary.

**Comment by ecederstrand** [comment]
Thanks, and sorry for the breakage!

**Comment by dmcgee** [comment]
No problem, thanks for the merge!
