### ISSUE TITLE
mime content appears to be invalid base64 and cannot be decoded

### ISSUE THREAD

**Issue by Austin-Schmidli** [ecederstrand/exchangelib#707]
When trying to retrieve a large email (>2MB of text) I get the following error.

`Cannot convert value [very long base64 string] on field 'mime_content' to type <class 'str'>`

This looks quite similar to some others have previously had:
https://github.com/ecederstrand/exchangelib/issues/584 
https://github.com/ecederstrand/exchangelib/issues/683

I enabled logging and looked at the actual '\<MimeContent CharacterSet="UTF-8">' field and it appears that Exchange is actually sending an impossible base64 encoding. The string is padded with '==' but 15310599 characters in total (including that padding). It is my understanding that the total number of characters must always be divisible by 4, and that it should be impossible for a base64 encoding to require more than two padding characters.

Passing the string directly into Python's base64.b64decode() function gives the following error:

`binascii.Error: Invalid base64-encoded string: number of data characters (15310597) cannot be 1 more than a multiple of 4`

Because of this, regardless of how many '=' padding characters appended to the end of the string, it will never successfully decode.

As far as I can tell, this must be a bug on Microsoft's end? If it helps, the server information (as determined by exchangelib) is: `server version Build=14.3.415.0, API=Exchange2010_SP2, Fullname=Microsoft Exchange Server 2010 SP2`

**Comment by ecederstrand** [comment]
This was solved in https://github.com/ecederstrand/exchangelib/issues/683. Another related bug was solved in https://github.com/ecederstrand/exchangelib/issues/686

**Comment by Austin-Schmidli** [comment]
I referenced #683 in the issue, its a very similar issue that was fixed but I believe that this one is different. The mime_content I'm receiving already has two padding characters, the fix from #683 will append a third '=' padding character, and then the decoding will proceed to fail regardless. 

The issue is that for some reason the Exchange server seems to be providing a mime_content field that is not a valid base64 encoding of any string _regardless of padding_. Any string properly encoded in base64 will require at most two padding characters to become divisible by 4. https://stackoverflow.com/questions/42052364/can-base64-encoded-string-end-with-3-equal-signs

**Comment by ecederstrand** [comment]
Oh, sorry for not properly reading your issue. That indeed sounds like a bug in Exchange.

If you can come up with a piece of Python code that can parse the encoded data anyway, I'm fine with adding it to our base64 decoder.

**Comment by ecederstrand** [comment]
@Austin-Schmidli Can you upload the failing string somewhere (assuming it doesn't contain confidential information)? Otherwise, you're welcome to DM me. If none of those work for you, I'm afraid you'll have to come up with a patch yourself.

**Comment by Austin-Schmidli** [comment]
Unfortunately I can't share the string as it contains business info. I was going to try and sanitize it, or generate a mock one that could reproduce the issue, but somehow the issue has since mysteriously vanished. I can identify two things appear to have changed since I was originally having the issue, the second of which I have no explanation for.

For all of my tests I used exchangelib to read the same email that was causing the original problem. (Not a copy, the very same email that's still sitting in Exchange)

Firstly, in all versions of exchangelib after 2.1.1, the ```Cannot convert value [...]  on field 'mime_content' to type <class 'str'>``` error no longer occurs. I can only assume that this due to 8077c51d821d6a97960c7599ee20321d756b903c.

Secondly, for some reason the Mime Content field provided by Exchange appears to have changed since last week even though its coming from the exact same email. I tested with 2.1.0, 2.1.1, 2.2.0, 3.1.0, and 3.1.1. The Mime Content field output in each of these versions is identical, and most importantly it *is correct base64*. But it does not match the (malformed base64) Mime Content that I got from the same email last week (I had a saved copy of it). I ran a diff and the Mime Contents are identical except the original malformed one has 11 extra characters ```E3Sm01aWMzQ``` about 1100 characters from the end of the string. I have no explanation for why these characters were showing up originally, and why they aren't now. 

I should mention that even though the Mime Content field Exchange is providing is now correct, versions 2.1.0 and 2.1.1 of exchangelib still give ```Cannot convert value [...]  on field 'mime_content' to type <class 'str'>```. At this point my only guess is that two separate issues, one of which being a random fluke from Exchange's end, just happened to be happening at the same time. 

Regardless, everything seems to have resolved itself and so far I haven't been able to reproduce it recently. So I suppose the issue can be closed?

**Comment by ecederstrand** [comment]
A bug in EWS that has sinde been fixed seems like a reasonable explanation. I’ve seen that before.

With no way to reproduce, I’ll glose the issue. If you see this again, please store the encoded string somewhere so it’s possible to reproduce and hopefully find a workaround that can parate the string anyway.
