### ISSUE TITLE
update the date and time for a meeting

### ISSUE THREAD

**Issue by lcgosi** [ecederstrand/exchangelib#714]
First of all, lib is sensational, thanks for sharing.
I am trying to update the date and time of a previously scheduled meeting, but I cannot.
I can only update the meeting subject for example and even then it is only updated for the user who created and updated the meeting.

Can you help me, please?!

```python
item.subject = 'new! Subject of Meeting '
item.send_and_save(update_fields=['subject'])
```

**Comment by ecederstrand** [comment]
Thanks for the kind words.

`send_and_save()` is only available on `Message` objects, i.e. emails. A scheduled meeting is a `CalendarItem` object.

To send updates to a meeting to participants, use the `send_meeting_invitations` argument. `SEND_MEETING_INVITATIONS_AND_CANCELLATIONS_CHOICES` contains the possible values on update:

```python
from exchangelib.items import SEND_MEETING_INVITATIONS_AND_CANCELLATIONS_CHOICES, SEND_ONLY_TO_ALL
item = account.calendar.get(subject='Subject of Meeting')
item.subject = 'New subject'
item.save(update_fields=['subject'], send_meeting_invitations=SEND_ONLY_TO_ALL)
```

**Comment by lcgosi** [comment]
Erik, Thanks a lot for your attention, quick response and for teaching me.
it's working perfectly now. =)

Thanks!
Good week to you!
