### ISSUE TITLE
Error when using fetch and only_fields

### ISSUE THREAD

**Issue by torhhu** [ecederstrand/exchangelib#715]
I'm downloading emails from an account using
```python
full_items_iter = account.fetch(ids=items_list)
for item in full_items_iter:
 do_something(item)
```

This works, but if I try to use
```python
full_items_iter = account.fetch(ids=items_list, only_fields=only_fields)
```

where only_fields is a list of strings with the fields I would like to fetch, the program crashes when starting the `for item in full_item_iter` loop (it doesn't start on do_something(item). This happens even if I have only_fields = ['id']

Error message:
```
File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\account.py", line 597, in fetch
    shape=ID_ONLY,
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\account.py", line 307, in _consume_item_service
    for i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\services\common.py", line 541, in _pool_requests
    elems = r.get()
  File "C:\Anaconda\Python\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Anaconda\Python\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\services\common.py", line 520, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\services\common.py", line 66, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\services\common.py", line 151, in _get_response_xml
    res = self._get_soap_messages(body=body, **parse_opts)
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\services\common.py", line 258, in _get_soap_messages
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "C:\Anaconda\Python\venvs\epost\lib\site-packages\exchangelib\services\common.py", line 294, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.
```

**Comment by ecederstrand** [comment]
Well, that's a really unhelpful error message from the server. `ErrorInternalServerError` could be anything.

It this consistent? What happens if you lower the `chunk_size` value?

**Comment by torhhu** [comment]
Lowering the chunk_size does not change anything.
`full_items_iter = account.fetch(ids=items_list, only_fields=['id'], chunk_size=1)`
give the same "helpful" error.
The ids I send in is found using:
`items_found = folder.filter(datetime_created__range=(start, end)).exclude(subject__icontains='Filter this subject').only('id', 'item_class').iterator()`

So the .only works in the filter at least.

**Comment by ecederstrand** [comment]
I think I found the problem. `only_fields` should not contain `id` or `changekey` because they are not normal fields and are fetched unconditionally. So the request ends up being malformed. `account.fetch(ids=items_list, only_fields=tuple())` should do what you want.

It's a bug that we don't have proper error handling for this case, so I'm keeping the issue open to have that done.

**Comment by torhhu** [comment]
Thanks, it makes sense and I'll try it soon. A (not really) related question: is it possible to get a count of the number of attachments without actually downloading the attachments? At the moment I'm downloading everything for each item and then taking the length of the attachments list (len(item.attachments)) as the number of attachments. But I was hoping it was possible to do this without actually downloading the attachments.

**Comment by ecederstrand** [comment]
`Item.attachments` only contains the attachment metadata, not the attachment content. Content is only fetched when you access `ItemAttachment.item` or `FileAttachment.content`.

There may be some extended property that contains the attachment count, but I'm not sure.

**Comment by torhhu** [comment]
Just tested this (excluding the ID from the only_fields) now, and it works as you explained. Thank you. Also thanks for pointing out that the item.attachments only contain the metadata, then the overhead of fetching this is negligible for my application.
