### ISSUE TITLE
Saved Messages are flagged as "Draft" - how to avoid/remove that

### ISSUE THREAD

**Issue by coldcoff** [ecederstrand/exchangelib#716]
Hi!

Thanks for exchangelib. I had much fun in the last days with that library and converted a bunch of imaplib scripts to work with exchangelib now instead.

When saving some message in an exchange folder via exchangelib (either by saving a completely new message -- created in exchangelib --,  or by updating an existing message, with `save(update_fields = ['mime_content'])` and some modifications in the mail text -- as proposed in #331 -- I always get these messages displayed in the Outlook Web Access as "Drafts", not as regular messages. I found no hint how to avoid that.

Also it seems I cannot remove the `message.is_draft` from exchangelib with an additional, separate update lateron. The field is readonly (at least in exchangelib?).

How to create messages that are not considered drafts? How to remove the draft flag from existing messages?

Thanks

Tino

**Comment by coldcoff** [comment]
Googling and digging the MS documentation for it I found:

https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/exporting-and-importing-items-by-using-ews-in-exchange

especially:
![image](https://user-images.githubusercontent.com/14311781/73486603-c90da180-43a5-11ea-8982-464e130d224f.png)

and;
https://docs.microsoft.com/en-US/office/client-developer/outlook/mapi/pidtagmessageflags-canonical-property?redirectedfrom=MSDN

![image](https://user-images.githubusercontent.com/14311781/73486766-0d993d00-43a6-11ea-9d8e-efffb5051d5d.png)

--> How to set this flag when doing `message.save()` ?

**Comment by coldcoff** [comment]
Got it!

```python
    from exchangelib import Credentials, Configuration, Account, DELEGATE, Message, ExtendedProperty

    # https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/cc839733(v=office.12)?redirectedfrom=MSDN
    class PrMessageFlags(ExtendedProperty):
        property_tag = 0x0e07
        property_type = 'Integer'

    # http://blog.abadev.com/2011/03/22/mapi-message-flags/
    # https://github.com/zarafagroupware/python-zarafa/issues/28
    # https://doc.zarafa.com/trunk/WebApp_JavaScript_API/source/MessageFlags.html
    MSGFLAG_READ = 0x0001
    MSGFLAG_UNMODIFIED = 0x0002
    MSGFLAG_SUBMIT = 0x0004,
    MSGFLAG_UNSENT = 0x0008
    MSGFLAG_HASATTACH = 0x0010
    MSGFLAG_FROMME = 0x0020
    MSGFLAG_ASSOCIATED = 0x0040
    MSGFLAG_RESEND = 0x0080
    MSGFLAG_RN_PENDING = 0x0100
    MSGFLAG_NRN_PENDING = 0x0200

    Message.register('pr_msg_flags', PrMessageFlags)
```
later

```python
    message.id = None
    message.changekey = None
    message.folder = <set folder here>
    message.mime_content = <set complete mime str here>
    #https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/master/docs/exchange-web-services/how-to-import-items-by-using-ews-in-exchange.md#use-the-ews-managed-api-to-import-an-email-from-an-eml-file-by-using-the-mime-stream
    message.pr_msg_flags = MSGFLAG_READ
    message.save()
```

works!

(I do not understand why `1` is the right flag, but I'm following the MSDN receipt ... and it works)

**Comment by ecederstrand** [comment]
Nice. And thanks for sharing your code!
