### ISSUE TITLE
EWSDateTime and EWSTimeZone do not support dateutil.tz timezone

### ISSUE THREAD

**Issue by qinfeng** [ecederstrand/exchangelib#717]
Since python 3.6, python standard documentation recommends using [dateutil](https://docs.python.org/3/library/datetime.html) to deal with timezone info. However, EWSDateTime and EWSTimeZone right now only support pytz timezone, not dateutil.tz timezone.

It will be great if exchangelib could support dateutil.tz

Thanks.

**Comment by ecederstrand** [comment]
`EWSTimeZone` uses pytz internally to represent the timezone, but it's supposed to be an implementation detail.

Is there something you are not able to do with the current implementation, that switching to dateutil would enable?

Converting a dateutil timezone to an `EWSTimezone` is a bit hacky, but apparently possible:

```python
from dateutil.tz import gettz
from exchangelib import EWSTimeZone

dateutil_tz = gettz('America/Chicago')
tz_name = '/'.join(dateutil_tz._filename.split('/')[-2:])
ews_tz = EWSTimeZone.timezone(tz_name)
```

**Comment by qinfeng** [comment]
@ecederstrand Thanks so much for your comment and the hack. `pytz` can solve most of the problem. The reason i like to request `dateutil` support is that i've slowly migrated from `pytz` to `dateutil` in my projects. But still need to mix `dateutil` and `pytz` when using exchangelib.

There are already many articles online comparing `pytz` and `dateutil`, so i would not do it here. To me, it's just a personal choice.

However, since Python officially recommends to use `dateutil`, more users would have this dilemma using exchangelib. So I guess it might be good for `exchangelib` to support `dateutil`.
