### ISSUE TITLE
Acceptable kwargs for inbox.filter()

### ISSUE THREAD

**Issue by connorferster** [ecederstrand/exchangelib#720]
I am looking for the complete list of acceptable kwargs that can be used with `.filter()`. I have read on the documentation, under **Searching**, that the kwarg can be used in conjunction with `__` in addition to various modifiers such as `exact`, `iexact`, and `contains`, etc. However, I am wondering what the list of "base" fields are (like, `sender` and `subject`) that can be used.

For example, in the documentation, there is a reference to the kwargs `subject` and `sender`, such as:  `.filter(subject = "My subject")` and `.filter(sender = "sender@sending.com")`. However, when I tried using a kwarg like `recipient`, `recipients`, or `to` I get an `InvalidField` error.

I read the Microsoft reference you posted (https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/querystring-querystringtype) and will just resort to using query strings if I have to but I am wondering if it is possible to get a list of the full set of "base" fields that are acceptable in `.filter()`. I have tried looking in `restrictions.py` and `fields.py` and `query_set.py` but I have not been able to find those references to the kwargs that I know will work: `sender` and `subject`. Could it be that these are the only two?

If you are able to point me to the list, I would be happy to update the documentation to include them. 

Many thanks! Exchangelib is an excellent library. I have enjoyed using it at my work: it's a real time saver.

**Comment by ecederstrand** [comment]
Hi @connorferster 

For `.filter()`, you can use almost all fields supported by the type of item you are searching for. Some fields are not supported by the server when filtering, and for a few others filtering the field is accepted but the filter does not work. These fields are marked with the `is_searchable` attribute:

```python
from exchangelib import Message

for f in Message.FIELDS:
    if f.is_searchable:
        print(f.name)
```

**Comment by connorferster** [comment]
Confirmed. Thanks!
