### ISSUE TITLE
FileAttachment is not working

### ISSUE THREAD

**Issue by klem4** [ecederstrand/exchangelib#721]
Hi!
I'm trying to send an email with an attachment, but the letter is sent without it, I don’t get any errors.
I would be grateful for your help.

exchangelib==3.1.1
exchange version 15, 0, 12, 34

```python
att_file = open(att_path, 'rb')
att_content = att_file.read()
att = FileAttachment(name=att_name, content=att_content)
m.attach(att)
m.send_and_save()
```

**Comment by klem4** [comment]
At the same time, in the **sent** folder the letter with the attachment!

**Comment by klem4** [comment]
the problem was not in the library

**Comment by mike-egg123** [comment]
Hi, I had the exact opposite problem. I attached the files in an email and send it. In the reciever, I could find the attachment, but in the primary email, I even couldn't find this email!
