### ISSUE TITLE
routing_type: should 'EX' be an additional choice?

### ISSUE THREAD

**Issue by fleminra** [ecederstrand/exchangelib#722]
Most of the messages I've seen from my Exchange server have routing_type of 'SMTP' but several have 'EX'. Should that be a valid choice in `exchangelib/properties.py`? I noticed that it [was added](https://github.com/nylas/exchangelib/commit/dcd77b406fa26242de6094c4fd2e1784e66e7a3c#diff-73bb057caf6c86a1ee220a3fdb95eb72) in [this fork](https://github.com/nylas/exchangelib).

**Comment by ecederstrand** [comment]
Yes, it probably should. I'm currently in the process of merging back changes from that fork to this repo. I'll make sure that change also gets in.

**Comment by ecederstrand** [comment]
I filed https://github.com/MicrosoftDocs/office-developer-exchange-docs/pull/77 to have the official docs updated.
