### ISSUE TITLE
Unable to use OAuth2AuthorizationCodeCredentials

### ISSUE THREAD

**Issue by ppremkumar** [ecederstrand/exchangelib#723]
Hi:

Below is my code to access a work Microsoft exchange account that has 2-factor authentication. To overcome this 2-factor authorization, I decided to use OAuth2AuthorizationCodeCredentials.

Now, I generate an access token before I create an instance of OAuth2AuthorizationCodeCredentials.

For that, I am using **AuthenticationContext** from **adal**.
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code **XXXXXXXX** to authenticate.

Here, I use my **domain.com** account and I give the native app the necessary authorization. I get the below response, as well.

> EWSNativeApp
> You have signed in to the EWSNativeApp application on your device. You may now close this window.

After the access token is successfully generated, I pass the necessary client_id, client_secret, and access_token to OAuth2AuthorizationCodeCredentials.

Everything works fine until I reach **account = Account(primary_smtp_address=token_response['userId'], config=config, autodiscover=False, access_type=DELEGATE)**.

```
import config
from adal import AuthenticationContext
from exchangelib import Account, Configuration, OAUTH2, OAuth2AuthorizationCodeCredentials, DELEGATE, OAuth2Credentials
ctx = AuthenticationContext(config.AUTHORITY_URL, api_version=None)
device_code = ctx.acquire_user_code(config.RESOURCE, config.CLIENT_ID)
print(device_code['message'])
token_response = ctx.acquire_token_with_device_code(config.RESOURCE, device_code, config.CLIENT_ID)
credentials = OAuth2AuthorizationCodeCredentials(client_id=config.CLIENT_ID, client_secret=config.CLIENT_SECRET, access_token=token_response['accessToken'])
config = Configuration(credentials=credentials, auth_type=OAUTH2)
account = Account(primary_smtp_address=token_response['userId'], config=config, autodiscover=False, access_type=DELEGATE)
for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)
```

I keep getting the below errors.

```
Traceback (most recent call last):
  File "exchange_web_services/ews.py", line 10, in <module>
    account = Account(primary_smtp_address='john.doe@domain.com', config=config, autodiscover=False, access_type=DELEGATE)
  File "exchange_web_services\venv\lib\site-packages\exchangelib\account.py", line 94, in __init__
    self.protocol = Protocol(config=config)
  File "exchange_web_services\venv\lib\site-packages\exchangelib\protocol.py", line 357, in __call__
    protocol = cls._protocol_cache.get(_protocol_cache_key)
  File "exchange_web_services\venv\lib\site-packages\exchangelib\credentials.py", line 60, in __hash__
    return hash(tuple(self._get_hash_values()))
  File "exchange_web_services\venv\lib\site-packages\exchangelib\credentials.py", line 158, in <genexpr>
    return (getattr(self, k) if k != 'access_token' else self.access_token['access_token'] for k in self.__dict__.keys() if k != '_lock')
TypeError: string indices must be integers
```

I am really stuck here and not sure what mistake I have made. Any inputs will be helpful.

**Comment by spencer-hanson** [comment]
You passed in a string for `value` in the `OAuth2AuthorizationCodeCredentials(access_token=value)` It is expecting a dictionary (`self.access_token['access_token']`)
Try:
`OAuth2AuthorizationCodeCredentials(access_token={"access_token": value})`

**Comment by ppremkumar** [comment]
Thank you. I am able to proceed now.
