### ISSUE TITLE
Equivalent to SearchDirectory(MS EWS c# method)

### ISSUE THREAD

**Issue by srinathgnath** [ecederstrand/exchangelib#724]
Hello,

Is there an equivalent method "SearchDirectory" in exchangelib? I want to filter out conference room using search.

C#:
SearchDirectory("(&(objectClass=*)(msExchRecipientDisplayType=7))")

Thanks,
Srinath

**Comment by ecederstrand** [comment]
Si the search string a QueryString? If so, QueryStrings are supported in exchangelib. See the README for more.

To locate the folder you want to do the search on, just list your entire folder structure with `account.root.tree()` and find your search folder location.

**Comment by srinathgnath** [comment]
Querystring and folder search works against specific mailbox. What I was looking for is search against the exchange and get the list of rooms( here the rooms are of type RecipientDisplayType=7).

Note: get_roomlists() and get_rooms() doesn't work as its not defined at exchange.
