### ISSUE TITLE
GetUserAvailability sample code

### ISSUE THREAD

**Issue by srinathgnath** [ecederstrand/exchangelib#725]
Hello,

Could you please share sample code to fetch availability of a user.

Thanks,
Srinath

**Comment by ecederstrand** [comment]
It's a bit hidden, but you probably want the `.get_free_busy_info()` method explained in https://github.com/ecederstrand/exchangelib#non-account-methods

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you need additional help.

**Comment by ecederstrand** [comment]
X

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you need additional help.
