### ISSUE TITLE
Custom Key/Value pairs in Calendar Invite

### ISSUE THREAD

**Issue by ccwong-github** [ecederstrand/exchangelib#727]
I would like to add a few custom Key/Value pairs to calendar invite (i.e. in the invite.ics attachment) to automate sending online meetings. Following are a few sample custom key/values:

```
X-MICROSOFT-ONLINEMEETINGEXTERNALLINK:https://xxxx/yyy/zzz/123456
X-MICROSOFT-ONLINEMEETINGCONFLINK:conf:sip:aaa@example.com\;gruu\;opaque
 =app:conf:focus:id:ssss?conversation-id=xxx
X-MICROSOFT-CONFERENCETELURI:tel:+122121234567
X-MICROSOFT-ONLINEMEETINGINFORMATION:{"OnlineMeetingProvider":1}
```

Can u please advise how I can add these fields? Or I need to make changes to your library?

Thx
CC

**Comment by ecederstrand** [comment]
AFAIK, Exchange does not automatically create a invite.ics attachment when you create a CalendarItem with attendees and specify to send meeting invitations.

How was the invite created? If you are creating the .ics yourself, then you can just edit the file you are attaching. That is not specific to exchangelib. `CalendarItem` also has the `conference_type`, `is_online_meeting`, `net_show_url` an `meeting_workspace_url` that might be of help to you.

**Comment by ecederstrand** [comment]
@ccwong-github  Did you get anywhere with your problem?

**Comment by ccwong-github** [comment]
HI Erik,
Thank a lot for your support! Initially, I was planning to explore if I can add any custom header in the invite to generate an online meeting using CalendarItem class directly.  As per your advice, I am now creating and attaching an .ics attachment to include the custom headers to achieve the same goal :)

Cheers
CC

**Comment by ecederstrand** [comment]
Seems like we can close this issue, then.
