### ISSUE TITLE
Move/Copy functions issues with version 2.2.0

### ISSUE THREAD

**Issue by morro91** [ecederstrand/exchangelib#728]
Having some issues after upgrading from 1.12.0 to 2.2.0 (needed to use the expand_dl feature).

In 1.12.0, the moving or copying of email items works perfectly fine. No issues.

After upgrade to 2.2.0, the moving/copying items no longer works, it waits a while, then goes "ErrorServerBusy" exception. Also does this just before "No handlers could be found for logger "exchangelib.protocol".

The strange thing is, when I put the PrettyXmlHandler debug logging lines in, it then takes an age, but it does work.  It looks to use a fallback method.

I can't really post debug messages due to sensitive system, but I have two systems, one with 1.12.0 which still works fine, the other with 2.2.0 which does not, so I don't believe it to be a permissions error.

Does this sound familiar/something that can be assisted with?

Not sure if python 2 is still supported at this stage.

**Comment by morro91** [comment]
basic code is:
```
items = mailbox.inbox.filter(subject__startswith='Daily deals')
for i in items:
    i.move(to_folder=mailbox.inbox / 'Archive')
```

**Comment by morro91** [comment]
workaround of downgrading to 1.12.2 seems to work, both copy/move work now and hasthe expand_dl feature i wanted. 1.12.3-5 have access denied issue reported in #610

**Comment by ecederstrand** [comment]
Exchange servers can be very slow to respond at times. It's not given that this has to do with using `PrettyXmlHandler` or the exchangelib version.

The best way to debug this is to compare the verbose output of a working and a non-working situation to see what the two versions are doing differently. But you will have better changes of getting things fixed if you test on the latest version. Quite a lot has happened since 2.2.0.

**Comment by ecederstrand** [comment]
@morro91 Did you get anywhere with this problem?

**Comment by morro91** [comment]
I did a test with python3 version 3.1.1. 

Both expand_dl and move work, tho the move operations does take a while, but it works.

So thanks :)

Now to migrate my scripts to python3, I spose. (which I should do anyway)
