### ISSUE TITLE
Ambitions to ActiveSync?

### ISSUE THREAD

**Issue by alfonsrv** [ecederstrand/exchangelib#731]
Are there any ambitions to implement [Active Sync](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-ashttp/4cbf28dc-2876-41c6-9d87-ba9db86cd40d?redirectedfrom=MSDN) to provide an alternative way to interact with servers that are not only Exchange or, alternatively Exchange servers that don't have EWS enabled?

**Comment by ecederstrand** [comment]
I have no plans to do so. Contributions are welcome, but it may be a better fit for an entirely different package.
