### ISSUE TITLE
Create Message object from .msg file

### ISSUE THREAD

**Issue by joanrodriguezr** [ecederstrand/exchangelib#732]
Hi Eric,

First of all thanks for your support, it's always appreciated. 

I have an email with a .zip attachment which is a .msg file. That .msg file is the one I have to analyze with my scripts in a recursive way as if it was a Message within the inbox.

I guess if I can create a Message() or something similar from the .msg file

Thanks in advance!

**Comment by ecederstrand** [comment]
A .msg file usually contains the MIME content of an email. It's not directly readable by exchangelib since it does not translate directly to a `Message` item. [email.parser](https://docs.python.org/3/library/email.parser.html) can supposedly parse MIME content.

**Comment by joanrodriguezr** [comment]
Thanks for your quick response I will take a look at that library and will let you know if I have any progress from my side.

**Comment by ecederstrand** [comment]
Closing. Feel free to post progress here :-)

**Comment by joanrodriguezr** [comment]
Hi Erik,

I have gone over this again after a few months. I've tried another workaround:

- Step 1: Decompress the .zip file and get the .msg file which is within the .zip file.
---> Here I can double click on the .msg file and Outlook can open it and read as if it was a regular email (that .msg has 2 attachtments on it)
- Step 2: I create a FileAttachment object adding the binary contents of the .msg file (msgPath is the local file location), and I add it to a new Message item which I store in a temporary folder within the Mailbox:

	binary_file_content = None
	with open(msgPath, 'rb') as f:
		binary_file_content = f.read()
		f.close()

	from exchangelib import FileAttachment
	my_file = FileAttachment(name='{}.msg'.format(nombreAttachment[:-4]), content=binary_file_content)
	item.attach(my_file)
	item.save()

-Step 3: One I have the fake Message saved in the temporay folder within the Mailbox I can add to the loop and I'm able to read the .msg attachment perfectly but when I go deeper to get the 2 files within the .msg I'm getting this error:

    'FileAttachment' object has no attribute 'attachments'

Is there anything I'm missing or another way to do it?

Any help would be appreciated

**Comment by joanrodriguezr** [comment]
May I use ItemAttachment insteadof FileAttachment?

**Comment by ecederstrand** [comment]
You must use ItemAttachment if you are attaching an item. FileAttachment is for files.

**Comment by joanrodriguezr** [comment]
But is .msg file considered a FileAttachment or an ItemAttachment when speaking in terms of exchangelib ? 

I say that because I have made a 2 separate tests:

- Test 1: Email containing the .zip file as the only attachment (inside the .zip there is a .msg file that I store in local disk and then try to add as an attachment to a Message() object.
- Test 2: Email containing a .msg file as the only attachment.

When I print the object for the root Item with both Tests what I see is the following:

- Test 1: The fake Message() that I recover gives me the fake .msg Attachment as a FileAttachment (It is what I added previously) but I can browse deeper on its attachments.
- Test 2: The .msg attachment is a ItemAttachment with content_type='message/rfc822'

Does it provide any clue to you that can shed some light on me?

Thanks again!

**Comment by ecederstrand** [comment]
A `.msg` isn't considered anything in exchangelib, because there isn't any special handling of `.msg` files.

You have two options:

1. Try to convert the file to a `Message` item, for example with the help of the `email.parser` module, and attach the message  using an `ItemAttachment`
1. Attach the file without any special processing, using a `FileAttachment`, and hope that the client reading this at the other end knows what this means. Setting `content_type='message/rfc822'` may help clients to know which type of file this is, but you'll have to test yourself to see if it works for you.

**Comment by joanrodriguezr** [comment]
Hi Erik,

I tested both options without getting any positive results. But... lucky me! I found this library for my purposes:
https://github.com/mattgwwalker/msg-extractor/tree/master/extract_msg

And this is an snippet of the code I used (If any one has the same problem as me in the near future):

       tmpAttDir = 'The path where you want to store the attachments extracted from the .msg file'

       # If the tmpAttDir does not exist then create it
	try:
		os.stat(tmpAttDir)
	except:
		os.mkdir(tmpAttDir)	
	
        # Get the msg Object from .msg file path
	import extract_msg
	msg = extract_msg.openMsg(msgFilePath)

        # Extract attachments to the temp folder
	attachments = msg.attachments
	for attachment in attachments:
		attachment.save(customPath=tmpAttDir)

        # Iterate over attachment files and add the to the exchangelib in a fake Message Item	
	lista_arq = ls(tmpAttDir)
	for arch in lista_arq:
		saved_path = tmpAttDir + '\\{}'.format(arch) 
		with open(saved_path, 'rb') as f:
			binary_file_content = f.read()
			from exchangelib import FileAttachment
			my_file = FileAttachment(name=arch, content=binary_file_content)
			exchangelibMessage.attach(my_file)
			exchangelibMessage.save()	
		f.close()
		os.remove('{}\\{}'.format(tmpAttDir,arch))

Thanks for your help and support!
