### ISSUE TITLE
How can i filter emails with a date range

### ISSUE THREAD

**Issue by niernier007** [ecederstrand/exchangelib#733]
I want to filter emails received before 2020-3-13 and after 2020-3-11. Is it right using the below code?
But i can not get anything in the for loop. 
Who can help me? Thanks.

```python
start = account.default_timezone.localize(EWSDateTime(2020, 3, 11))
end = account.default_timezone.localize(EWSDateTime(2020, 3, 13))
qs = account.calendar.all()
items = qs.filter(start__range=(start, end))  # Returns items within range
for item in items:
      print(item.start, item.end, item.subject, item.body, item.location)
```

**Comment by ecederstrand** [comment]
`Message` items don't have a `start` field. Only `CalendarItem` has this, so your filter doesn't really make sense.

Use one of the other datetime fields on the `Message` class. You can list all available fields and their type with this:

```python
from exchangelib import Message

for f in Message.FIELDS:
    print(f.name, f.__class__)
```

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if this did not solve your issue.
