### ISSUE TITLE
Create new contact in public folder

### ISSUE THREAD

**Issue by vertex-live** [ecederstrand/exchangelib#734]
I am not sure if I miss it in the documentation, but I can't find anything on creating a contact in a public folde.r

I can find my folders and extract contacts just fine, but I can't find a flow to create items.

Thank you!

**Comment by ecederstrand** [comment]
The general approach to create items in a folder is:

```python
from exchangelib import Contact, Account

a = Account(...)
some_folder = a.root / 'Some' / 'Folder'
Contact(folder=some_folder, display_name='Mr. Foo', email_addresses=['foo@example.com']).save()
```

**Comment by vertex-live** [comment]
Thank you for the quick answer! I got the following error:

TypeError: Field 'email_addresses' value 'foo@example.com' must be of type <class 'exchangelib.indexed_properties.EmailAddress'>

**Comment by vertex-live** [comment]
I tried this in addition to the code above:

from exchangelib.indexed_properties import EmailAddress

Contact(
    folder=some_folder,
    display_name = 'Mr. Foo Bar',
    email_addresses = [EmailAddress(email = 'foo@example.com')]
).save()

and it worked! let me know if this is a good solution or I just got lucky.

**Comment by ecederstrand** [comment]
Sorry for the broken example. Simple strings as input was an optimization we didn't actually have yet. I've fixed that in the referenced commit.

**Comment by wangdi244** [comment]
I want to know how to delete. Please give me an example. Thank you

**Comment by ecederstrand** [comment]
Is anything unclear in the README?
