### ISSUE TITLE
BaseFolder.glob() case-sensitivity depends on operating system

### ISSUE THREAD

**Issue by dmcgee** [ecederstrand/exchangelib#736]
`BaseFolder.glob()` may or may not perform a case-sensitive match depending on the operating system on which it runs: on Windows, matches are case-insensitive; everywhere else they're case-sensitive.

`glob()` (via `_glob()`) uses `fnmatch.fnmatch()` to check candidate folders against the pattern, and `fnmatch()` normalizes its parameters using `os.path.normcase()`. However, `normcase()` is written with local filesystem operations in mind, and whether or not it's case-sensitive depends on the operating system.

Since Exchange folder names are case-insensitive, the desired (or at least default) behavior is probably always searching case-insensitively. If it's useful to allow case-sensitive searching, `glob()` should take an option to enable that, and `fnmatch()` should not be allowed to affect the chosen behavior.

**Comment by ecederstrand** [comment]
This sounds reasonable.

I would like to link to documentation, but I can't find any documentation stating that Exchange folder names are case-insensitive. Is this from docs, or just experience?

**Comment by dmcgee** [comment]
That was my thought, too. Unfortunately it's only my experience that Exchange folders are case-insensitive. It was oddly hard to search for, though I suppose since it's Microsoft's convention for themselves, they didn't feel a particular need to document it.

I'm happy to open a PR if that fix sounds good to you.

**Comment by ecederstrand** [comment]
Feel free to open a PR. I’m fine with trusting your experience. I just prefer hard evidence if such exists :-)
