### ISSUE TITLE
Tracking moved messages

### ISSUE THREAD

**Issue by fdroessler** [ecederstrand/exchangelib#737]
Hello,

I am new to this library so I hope you'll excuse if this is answered somewhere but I could not find anything so far.
I have noticed that when a message is moved to another folder the message id changes. Is there any unique identifier that would allow to find where a message was moved? I know that potentially I could find an email by using search by subject etc. but there are sometimes duplicates and a unique identifier would make things easier to keep track.

Many thanks for any pointers in that matter.

Cheers,
Florian

**Comment by ecederstrand** [comment]
When an item is moved within the same Exchange account, the item ID is preserved. I.e. the `Message.message_id` field may change, but the `Message.id` field should not.

So you can look up the item by ID: `account.root.get(id='some_id')`. The `Item.parent_folder_id` field will tell you which folder the item was moved to.

**Comment by fdroessler** [comment]
Ok that is what I was hoping for too but there seems to be something not working. This would be my minimal example in which `a` is an Exchange Account:

```
m = Message(account=a, folder=a.inbox, subject='some header', body='some text')
m.save()
message_id = m.id
f1 = a.inbox // 'folder_01'
m.move(f1)
a.inbox.refresh()
f1.refresh()
a.root.get(id=message_id)
```

The last line results in the following error:
`exchangelib.errors.ErrorItemNotFound('The specified object was not found in the store., The process failed to get the correct properties.')`

Based on your comment above that would suggest that I am moving the message to a different account?

**Comment by ecederstrand** [comment]
It turns out I was wrong. Moving an item does indeed change the ID. Here's how you can track the item:

```python
m = Message(folder=a.inbox, subject='some header', body='some text')
m.save()
print(m.id)
m.move(a.trash)
print(m.id)
m = a.root.get(id=m.id)
print(m.id)
```

Prints:
```
[...]8YFhLlR4EvlUWaA+3wAAKd96kDAAA=
[...]8YFhLlR4EvlUWaA+3wAAKd+EIyAAA=
[...]8YFhLlR4EvlUWaA+3wAAKd+EIyAAA=
```

**Comment by fdroessler** [comment]
I see thanks for the confirmation! So as long as things are moved through the API it's traceable but I guess it becomes more tricky as things are moved manually or otherwise. Thanks for answering, from my perspective this issue can be closed unless there are more ways of tracking E-Mail movement through the postbox :)

**Comment by ecederstrand** [comment]
If you want to track your own items when they move around inside an account, you can mark them with an extended property. I have used this extended property to mark item with a unique ID: 
https://github.com/ecederstrand/exchangelib/blob/21c006421d886315740ebda667d07be1ca453fa2/exchangelib/extended_properties.py#L307

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this does not solve your problem.
