### ISSUE TITLE
Get Folder by ID

### ISSUE THREAD

**Issue by xkobal** [ecederstrand/exchangelib#742]
Hi, 

I would like to know if it is possible to get a folder by its Exchange ID (Folder.id) instead of its name ?

I have test a lot of different methods without success.

Thanks for your help and your great work.

**Comment by ecederstrand** [comment]
Good question. I think the easiest is to just create a folder instance:

```python
f = Folder(root=account.root, id='AAAAx==')
f.refresh()  # Test that the folder can be found, and get additional attributes.
```

If you don't mind fetching the entire folder structure, you can also traverse your folder hierarchy:

```python
for f in account.root.walk():
    if f.id == 'AAAAx==':
        break
else:
    raise Exception('No folder with this ID')
```

exchangelib also has a concept of querysets for folders (see https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/folders/queryset.py) but the public API hasn't evolved to the point yet where you can easily query your folder structure by folder ID.

**Comment by ecederstrand** [comment]
Hi @xkobal Did this solve your issue?

**Comment by xkobal** [comment]
Hi @ecederstrand, I didn't seen the previous Github notification. I will test this afternoon.

Thanks for the answer & the reminder !

**Comment by xkobal** [comment]
Here is the exception that is raised when I try your first method: 

`Expected folder Inbox(Root(<exchangelib.account.Account object at 0x7f4efed1c790>, '[self]', 'root', 8, 0, 56, None, 'AAMkADUwOTcxZmMwLTMzMDgtNDZiYy05ODkyLTkyOTdiNjdhMmFkZAAuAAAAAABybeYYOG9iSq6EYYk3QSo9AQBxyAu/l0vbSa3iURdnBSYeAAAAAAEBAAA=', 'AQAAABYAAABxyAu/l0vbSa3iURdnBSYeAASJGelI'), 'Inbox', 0, 0, 0, 'IPF.Note', 'AAMkADUwOTcxZmMwLTMzMDgtNDZiYy05ODkyLTkyOTdiNjdhMmFkZAAuAAAAAABybeYYOG9iSq6EYYk3QSo9AQBxyAu/l0vbSa3iURdnBSYeAAAAAAEMAAA=', 'AQAAABYAAABxyAu/l0vbSa3iURdnBSYeAASJGelH') to be a <class 'exchangelib.folders.base.Folder'> instance`

Am I doing something wrong ?

The second is working and is the actual method I am using. But it's a little expansive.

**Comment by ecederstrand** [comment]
Ah, this is probably an overly strict assertion. I'll have a look at it. For now, when your ID points to an inbox-type folder, you can do this:

```python
from exchangelib.folders import Inbox
f = Inbox(root=account.root, id='AAAAx==')
f.refresh()
```

**Comment by xkobal** [comment]
Ok, understand, I have the same problem with every distinguished folders:

`Expected folder SentItems(Root(<exchangelib.account.Account object at 0x7ff4ab7d2400>, '[self]', 'root', 8, 0, 56, None, 'AAMkADUwOTcxZmMwLTMzMDgtNDZiYy05ODkyLTkyOTdiNjdhMmFkZAAuAAAAAABybeYYOG9iSq6EYYk3QSo9AQBxyAu/l0vbSa3iURdnBSYeAAAAAAEBAAA=', 'AQAAABYAAABxyAu/l0vbSa3iURdnBSYeAASJGelI'), 'Sent Items', 0, 0, 0, 'IPF.Note', 'AAMkADUwOTcxZmMwLTMzMDgtNDZiYy05ODkyLTkyOTdiNjdhMmFkZAAuAAAAAABybeYYOG9iSq6EYYk3QSo9AQBxyAu/l0vbSa3iURdnBSYeAAAAAAEJAAA=', 'AQAAABYAAABxyAu/l0vbSa3iURdnBSYeAAAAAAAz') to be a <class 'exchangelib.folders.base.Folder'> instance`

or for a normal folder:

`Expected folder Messages(Root(<exchangelib.account.Account object at 0x7fb11d17a760>, '[self]', 'root', 8, 0, 56, None, 'AAMkADUwOTcxZmMwLTMzMDgtNDZiYy05ODkyLTkyOTdiNjdhMmFkZAAuAAAAAABybeYYOG9iSq6EYYk3QSo9AQBxyAu/l0vbSa3iURdnBSYeAAAAAAEBAAA=', 'AQAAABYAAABxyAu/l0vbSa3iURdnBSYeAASJGelI'), 'Calendar Version Store', 16, 0, 0, 'IPF.Note', 'AAMkADUwOTcxZmMwLTMzMDgtNDZiYy05ODkyLTkyOTdiNjdhMmFkZAAuAAAAAABybeYYOG9iSq6EYYk3QSo9AQBxyAu/l0vbSa3iURdnBSYeAARna2ODAAA=', 'BwAAABYAAABxyAu/l0vbSa3iURdnBSYeAARpbuPI') to be a <class 'exchangelib.folders.base.Folder'> instance`

If you fix the assertion on Folder instance, I think it will be the good way to get a folder by Id.

**Comment by ecederstrand** [comment]
(just updated the previous comment to provide a solution to the above)

**Comment by ecederstrand** [comment]
For distinguished folders specifically, `account.some_distinguished_folder` will get the folder without traversing the entire folder structure of your account.

For other folders where you do know the path to the folder, `account.root // 'Parent folder' // 'Child folder'` will only fetch the folders that are part of the path.

**Comment by xkobal** [comment]
Thanks for your help, the second solution works like a charm !

**Comment by ecederstrand** [comment]
Great. Ca we close this issue, then? I think exposing a better API should go in a separate issue.

**Comment by xkobal** [comment]
Yes we can, have a good day.
