### ISSUE TITLE
Consider using SmtpAddress for an impersonation

### ISSUE THREAD

**Issue by s-limo** [ecederstrand/exchangelib#743]
Consider using SmtpAddress isntead of PrimarySmtpAddress for impersonation. While PrimarySmtpAddress looks correct value according to documentation (https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/connectingsid) it causes some problems.

**Issue**
I tried to subscribe to push notifications using code from #355 as base. I was able to subscribe (received subscription ID), however later did not receive any change events. I was able to fix by changing impersonation part of message  to use SmtpAddress isntead of PrimarySmtpAddress

transport.py line 71:
`            #  add_xml_child(connectingsid, 't:PrimarySmtpAddress', account.primary_smtp_address)
            add_xml_child(connectingsid, 't:SmtpAddress', account.primary_smtp_address)`

**Additional details**
To debug issue I tried to reproduce similar behavior using Microsoft.Exchange.WebServices managed API with .NET. Here are results:
- API allows to select what kind of impersonation to use:
![image](https://user-images.githubusercontent.com/1849760/78967482-44f53a00-7b0b-11ea-867a-00890a3c0d0e.png) (and for some reason there is no "PrimarySmtpAddress "
- when using SmtpAddress (not suprise) it produces XML which uses SmtpAddress  as Connection ID:
```<Trace Tag="EwsRequest" Tid="1" Time="2020-04-09 06:59:58Z" Version="14.02.0051.000">
  <?xml version="1.0" encoding="utf-8"?>
  <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Header>
      <t:RequestServerVersion Version="Exchange2010_SP1" />
      <t:ExchangeImpersonation>
        <t:ConnectingSID>
          <t:SmtpAddress>kitchen@tenant.onmicrosoft.com</t:SmtpAddress>
        </t:ConnectingSID>
      </t:ExchangeImpersonation>
    </soap:Header>
    <soap:Body>
      <m:GetFolder>
        <m:FolderShape>
          <t:BaseShape>IdOnly</t:BaseShape>
        </m:FolderShape>
        <m:FolderIds>
          <t:DistinguishedFolderId Id="calendar" />
        </m:FolderIds>
      </m:GetFolder>
    </soap:Body>
  </soap:Envelope>
</Trace>
```

Of course the best solution would be to allow choose which connection type to use, but as simple (and nonbraking?) fix would be to use SmtpAddress instead of PrimarySmtpAddress

**Comment by ecederstrand** [comment]
That's really weird. As you say, there's nothing indicating that `PrimarySmtpAddress` is wrong, and my understanding of the two is that there will only be a difference if you are passing an alias to the primary account. It could be that there is a difference if your account is registered in O365 with some internal `*.onmicrosoft.com` email address.

Anyway, I'm not opposed to the change, but the documentation also suggests sending the SID or UPN instead. Let's see if EWS can give us that information, and send SID/UPN on impersonation requests instead.

**Comment by ecederstrand** [comment]
Re-reading this, are you sure your email address *is* in fact the primary SMTP address? Tid you do an autodiscover lookup on the address to confirm?

**Comment by s-limo** [comment]
Actually I am not sure if this is an issue at all - there was error at some other pace. Still working at that place will let you now after dobule-checking

**Comment by ecederstrand** [comment]
I just committed a change so you can do:

```python
account.smtp_address = 'kitchen@tenant.onmicrosoft.com'
```

and have that value be used in impersonation headers instead.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues.
