### ISSUE TITLE
how to get the item id for a message

### ISSUE THREAD

**Issue by Liwenhui02** [ecederstrand/exchangelib#745]
I have a system which can scan exchange emal body and attachment. The result will be json data of a email if it matches some rules.

I want to move user's email  to a public account's inbox,according as the returned json data.

I list all the returned json data of a email.
```json
  "fileCreatedTime":"2020-03-13 16:15:36",
  "fileChecksum":"f556b9d212c0b151e302f184039268b9",
   "fileModifiedTime":"2020-03-13 16:15:00",
   "filePath":"smith@test.com/inbox/test mail",
     "folderPath":"smith@test.com/inbox",
      "filename":"test mail",
```

I found that if I only use "subject" Eg."test mail" of message was insufficient to get item id. 

I don't know whether I can obtain a item id with these json data ?

**Comment by ecederstrand** [comment]
All items have an `id` attribute containing the UUID of that message. Likewise, attachments have an `attachment_id.id` attribute  containing the UUID of the attachment.

**Comment by ecederstrand** [comment]
You can't move a message that you haven't created yet. So either call `.move()` on an item that already has an `id` attribute, or call `.save()` first, and then `.move()` (but then you might as well just save the item to the correct folder in the first place).

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues with this.

**Comment by Liwenhui02** [comment]
Erik,
Today I comfirmed that it works. When I move a message from account A to account B's inbox. Exchange will take the exact action. Account B can find that he has a new received message in inbox.
Thank you for your support and thank you for your great project.
