### ISSUE TITLE
Read Exchange Online emails via tenant_id

### ISSUE THREAD

**Issue by piskvorky** [ecederstrand/exchangelib#747]
This looks like an awesome lib, but I got lost in the authentication options.

I want to read emails of a specific user `user@company.onmicrosoft.com` within Exchange Online. I have the `tenant_id`, `client_id` and `client_secret` for the whole org, set up to access whatever mailbox I want.

Here's what I tried, based on your README:

```python
>>> credentials = OAuth2Credentials(client_id='<my_client_id>', client_secret='<my_client_secret>', tenant_id='<my_tenant_id>')
>>> config = Configuration(credentials=credentials, auth_type=OAUTH2)
>>> a = Account('user@company.onmicrosoft.com', config=config)
AttributeError: 'config.service_endpoint' must be set

>>> a = Account('user@company.onmicrosoft.com', config=config, autodiscover=True)
ValueError: Auth type must be 'OAuth 2.0' for credentials type OAuth2Credentials
```

What's the correct way?

I'm just starting to wrap my head around the whole Office API ecosystem, sorry if I'm way off.

**Comment by ecederstrand** [comment]
Thanks!

The OAuth2 stuff is contrib code and hasn't been tested with autodiscover. Also, I don't have access to an OAuth2-enabled server myself to do proper testing.

I would suggest to have a look at https://github.com/ecederstrand/exchangelib/issues/735. There are various examples (and patches still on the master branch) that should let you log into O365 using OAuth2 with autodiscovery disabled.

I'll see if I can track down the ValueError. If you are patient enough, I can send you some patches in a week or so :-)

**Comment by piskvorky** [comment]
Absolutely. Happy to work through this together & contribute back.

Context: I'm used to generating / refreshing the Bearer tokens myself, via GET/POST requests in the O365 Graph API. I'm looking into `exchangelib` because I want to move beyond O365 and read emails from on-site Exchange installations too, in a more unified way. That's my motivation and scope of my interest.

**Comment by piskvorky** [comment]
Following #735, I tried this from the `master` branch:

```python
from exchangelib import (
    DELEGATE, IMPERSONATION, Account, Credentials, OAuth2Credentials, 
    OAuth2AuthorizationCodeCredentials, FaultTolerance, Configuration, NTLM, GSSAPI, SSPI,
    OAUTH2, Build, Version, Identity,
)
from exchangelib.autodiscover import AutodiscoverProtocol
from exchangelib.version import Version, EXCHANGE_O365

credentials = OAuth2Credentials(
    client_id='<my_client_id>',
    client_secret='<my_client_secret>',
    tenant_id='<my_tenant_id>',
    identity=Identity(primary_smtp_address='user@company.onmicrosoft.com')),
)
config = Configuration(
    credentials=credentials,
    auth_type=OAUTH2,
    service_endpoint="https://outlook.office365.com/EWS/Exchange.asmx",
)
account = Account(
    'user@company.onmicrosoft.com',
    config=config,
    autodiscover=False,
    access_type=IMPERSONATION,
)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-206430e20968> in <module>
----> 1 account = Account('user@company.onmicrosoft.com', config=config, autodiscover=False, access_type=IMPERSONATION)

/Volumes/work/workspace/exchangelib/exchangelib/account.py in __init__(self, primary_smtp_address, fullname, access_type, autodiscover, credentials, config, locale, default_timezone)
    104             primary_smtp_address = primary_smtp_address
    105             self.ad_response = None
--> 106             self.protocol = Protocol(config=config)
    107
    108         # Other ways of identifying the account can be added later

/Volumes/work/workspace/exchangelib/exchangelib/protocol.py in __call__(cls, *args, **kwargs)
    354         _protocol_cache_key = kwargs['config'].service_endpoint, kwargs['config'].credentials
    355
--> 356         protocol = cls._protocol_cache.get(_protocol_cache_key)
    357         if isinstance(protocol, Exception):
    358             # The input data leads to a TransportError. Re-throw

/Volumes/work/workspace/exchangelib/exchangelib/credentials.py in __hash__(self)
     58
     59     def __hash__(self):
---> 60         return hash(tuple(self._get_hash_values()))
     61
     62     def __getstate__(self):

/Volumes/work/workspace/exchangelib/exchangelib/credentials.py in <genexpr>(.0)
    162         return (
    163             getattr(self, k) if k != 'access_token' else self.access_token['access_token']
--> 164             for k in self.__dict__.keys() if k != '_lock'
    165         )
    166

TypeError: 'NoneType' object is not subscriptable
```

**Comment by ecederstrand** [comment]
Thanks. The referenced commit should fix the latest stack trace.

**Comment by ecederstrand** [comment]
I've looked into fixing the "Auth type must be 'OAuth 2.0' for credentials type OAuth2Credentials". It boils down to us not being able to autodetect that the autodiscover endpoint supports OAuth. 

I'm not sure it's worthwhile trying to fix because apparently you're not supposed to attempt autodiscover for accounts that you know are on O365 - the EWS endpoint is always https://outlook.office365.com/EWS/Exchange.asmx (see https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/get-started-with-ews-client-applications)

**Comment by piskvorky** [comment]
Thanks. I tried with `master` and now I get:

```
UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx
```

Not sure what username and password this is talking about – I'm using the `client_id`, `client_secret` and `tenant_id` of my registered application.

Where am I going wrong?

**Comment by ecederstrand** [comment]
Is that using autodiscover, or with autodiscover disabled? Can you post the entire stack trace?

**Comment by piskvorky** [comment]
Same code as above:

```python
from exchangelib import (
    DELEGATE, IMPERSONATION, Account, Credentials, OAuth2Credentials, 
    OAuth2AuthorizationCodeCredentials, FaultTolerance, Configuration, NTLM, GSSAPI, SSPI,
    OAUTH2, Build, Version, Identity,
)
from exchangelib.autodiscover import AutodiscoverProtocol
from exchangelib.version import Version, EXCHANGE_O365

credentials = OAuth2Credentials(
    client_id='<my_client_id>',
    client_secret='<my_client_secret>',
    tenant_id='<my_tenant_id>',
    identity=Identity(primary_smtp_address='user@company.onmicrosoft.com')),
)
config = Configuration(
    credentials=credentials,
    auth_type=OAUTH2,
    service_endpoint="https://outlook.office365.com/EWS/Exchange.asmx",
)
account = Account(
    'user@company.onmicrosoft.com',
    config=config,
    autodiscover=False,
    access_type=IMPERSONATION,
)

/Volumes/work/workspace/exchangelib/exchangelib/account.py in __init__(self, primary_smtp_address, fullname, access_type, autodiscover, credentials, config, locale, default_timezone)
    123         # We may need to override the default server version on a per-account basis because Microsoft may report one
    124         # server version up-front but delegate account requests to an older backend server.
--> 125         self.version = self.protocol.version
    126         log.debug('Added account: %s', self)
    127

/Volumes/work/workspace/exchangelib/exchangelib/protocol.py in version(self)
    416                 if not self.config.version or not self.config.version.build:
    417                     # Version.guess() needs auth objects and a working session pool
--> 418                     self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
    419         return self.config.version
    420

/Volumes/work/workspace/exchangelib/exchangelib/version.py in guess(cls, protocol, api_version_hint)
    224         name = str(protocol.credentials) if protocol.credentials and str(protocol.credentials) else 'DUMMY'
    225         try:
--> 226             list(ResolveNames(protocol=protocol).call(unresolved_entries=[name]))
    227         except (ErrorInvalidSchemaVersionForMailboxVersion, ErrorInvalidServerVersion, ErrorIncorrectSchemaVersion):
    228             raise TransportError('Unable to guess version')

/Volumes/work/workspace/exchangelib/exchangelib/services/resolve_names.py in call(self, unresolved_entries, parent_folders, return_full_contact_data, search_scope, contact_data_shape)
     30             return_full_contact_data=return_full_contact_data,
     31             search_scope=search_scope,
---> 32             contact_data_shape=contact_data_shape,
     33         ))
     34         for elem in elements:

/Volumes/work/workspace/exchangelib/exchangelib/services/common.py in _get_elements(self, payload)
     82             try:
     83                 # Send the request, get the response and do basic sanity checking on the SOAP XML
---> 84                 response = self._get_response_xml(payload=payload)
     85                 # Read the XML and throw any general EWS error messages. Return a generator over the result elements
     86                 return self._get_elements_in_response(response=response)

/Volumes/work/workspace/exchangelib/exchangelib/services/common.py in _get_response_xml(self, payload, **parse_opts)
    160                 ),
    161                 allow_redirects=False,
--> 162                 stream=self.streaming,
    163             )
    164             if self.streaming:

/Volumes/work/workspace/exchangelib/exchangelib/util.py in post_ratelimited(protocol, session, url, headers, data, allow_redirects, stream)
    764         protocol.retire_session(session)
    765         try:
--> 766             _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
    767         finally:
    768             if stream:

/Volumes/work/workspace/exchangelib/exchangelib/util.py in _raise_response_errors(response, protocol, log_msg, log_vals)
    844     if response.status_code == 401 and protocol.retry_policy.fail_fast:
    845         # This is a login failure
--> 846         raise UnauthorizedError('Wrong username or password for %s' % response.url)
    847     if 'TimeoutException' in response.headers:
    848         raise response.headers['TimeoutException']

UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx

```

The credentials are correct though (work fine in existing workflow, without `exchangelib`). Do you want them for testing? (privately, temporarily, for testing only)

**Comment by ecederstrand** [comment]
Yes, that would be cool! You can send them to the email in my bio.

**Comment by piskvorky** [comment]
Sent.

**Comment by ecederstrand** [comment]
I finally got the time to test. I'm getting a HTTP 401 from the server, with these HTTP headers in the response (abbreviated):

```python
{
    'x-ms-diagnostics': '2000008;reason="The token contains no permissions, or permissions can not be understood.";error_category="invalid_grant"',
    'WWW-Authenticate': 'Bearer client_id="[REDACTED]", trusted_issuers="v@*", token_types="app_asserted_user_v1 service_asserted_app_v1", authorization_uri="https://login.windows.net/common/oauth2/authorize", error="invalid_token",Basic Realm=""',
}
```

I don't know if `The token contains no permissions, or permissions can not be understood` rings a bell with you. I'm not familiar with OAuth myself. It's possible that either @cranbar or @dmcgee are willing to chip in here.

**Comment by piskvorky** [comment]
How did you generate the token? Did you respect the `expires_in` response value?

To be clear, the current workflow that works = what I'm looking to replace by exchangelib, generates and refreshes the token via:

```python
url = f"https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token"
response = requests.post(
    url,
    data={
        "client_id": client_id,
        "client_secret": client_secret,
        "scope": "https://graph.microsoft.com/.default",
        "grant_type": "client_credentials",
    },
)
```

**Comment by ecederstrand** [comment]
Ok, so it's probably a bug in the way we refresh the access token. I'll have a look at it today or tomorrow.

**Comment by ecederstrand** [comment]
It seems we're fetching the access token correctly. The only difference I see is in the scope; you're fetching tokens with a scope of `'https://graph.office365.com/.default'`, but we're fetching tokens with a scope of `'https://outlook.office365.com/.default'`. 

Is it possible that your credentials have been given access to the Graph API, but not the EWS API?

**Comment by piskvorky** [comment]
> Is it possible that your credentials have been given access to the Graph API, but not the EWS API?

Absolutely possible. Let me see if I can find where to set that.

**Comment by piskvorky** [comment]
OK, I added the `Mail.Read` and `User.Read.All` permissions for Exchange under `Supported legacy APIs`:

<img width="898" alt="Screen Shot 2020-05-12 at 10 56 15" src="https://user-images.githubusercontent.com/610412/81663871-52218380-943f-11ea-818a-5384e1adcc08.png">

**Comment by ecederstrand** [comment]
There are no concrete plans to remove the EWS API, but it is in legacy mode. All new development will go into the Graph API.

If previous Microsoft definitions of legacy is any guideline, EWS is likely to stay for the next 5-10 years.

**Comment by piskvorky** [comment]
OK, thanks. BTW the Graph API suffers from throttling: Microsoft limits the number of API requests, and there's no way to increase this limit from the user side. Do you know whether the EWS API has something similar?

Let me know if you need any other API permissions.

**Comment by ecederstrand** [comment]
Still getting the `The token contains no permissions, or permissions can not be understood` error message. Since I can access the Graph API using the same tokens, I think this is permission-related. Are there additional permissions you can grant? E.g. accessing folders or something like that. You can also run your own example from above and experiment a bit.

**Comment by ecederstrand** [comment]
And yes, EWS does throttling as well. For on-premise installs it’s possible to change throttling values for the connecting user. I don’t know about O365 but I have done some heavy work with thousands of accounts on O365 and exchangelib is pretty good at handling server-side rate-limiting.

**Comment by piskvorky** [comment]
Hmm, I now granted "full access as app". This should be the highest permission level:

<img width="835" alt="Screen Shot 2020-05-12 at 12 51 34" src="https://user-images.githubusercontent.com/610412/81675647-6ec5b780-944f-11ea-8dd3-93019715b200.png">

That's not great though, I'll have to keep the perms read-only. So this is just temporary.

> You can also run your own example from above and experiment a bit.

Which example do you mean? How do *you* test this?

**Comment by ecederstrand** [comment]
There. Now everything works!

Here's the example code I used. It should work on the latest version 3.2.0:

```python
from exchangelib import IMPERSONATION, Account, Credentials, OAuth2Credentials, \
    Configuration, OAUTH2, Identity

client_id='xxx'
client_secret='yyy'
tenant_id='zzz'
user='john@example.onmicrosoft.com'

credentials = OAuth2Credentials(
    client_id=client_id,
    client_secret=client_secret,
    tenant_id=tenant_id,
    identity=Identity(primary_smtp_address=user),
)
config = Configuration(
    credentials=credentials,
    auth_type=OAUTH2,
    service_endpoint="https://outlook.office365.com/EWS/Exchange.asmx",
)
account = Account(
    user,
    config=config,
    autodiscover=False,
    access_type=IMPERSONATION,
)
print(account.root.all().count())
```

You can try removing permissions one by one yourself. I'm deleting the credentials you sent me now.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues with this.

**Comment by piskvorky** [comment]
I confirm the above works. Even after removing the `full_access_as_app` permission.

**Comment by vprem** [comment]
@piskvorky , as you said full_access_as_app is the top level permission that our IT team cannot give to us. All they can provide is user level permission. We also need that only. From our app we are trying to read a particular user email. 
You said, for you it is working without full_access_as_app. Can you give us more details how it is accessing a particular user account?

**Comment by AvitalL** [comment]
@piskvorky @ecederstrand Hi :) I'm joining @vprem 's question regarding the permissions. Seems from your comments that you manages to run make the code above work without full_access_as_app permission. Could you please share the permission setup you had? I tried removing it and it stopped working immediately. 

Thanks!

**Comment by vprem** [comment]
After removing the full_access_as_app it did not work for me, I tried a lot but all in vain. Hence I have migrated  my application to O365.

**Comment by robco** [comment]
> Hmm, I now granted "full access as app". This should be the highest permission level:
> 
> <img alt="Screen Shot 2020-05-12 at 12 51 34" width="835" src="https://user-images.githubusercontent.com/610412/81675647-6ec5b780-944f-11ea-8dd3-93019715b200.png">
> 
> That's not great though, I'll have to keep the perms read-only. So this is just temporary.
> 
> > You can also run your own example from above and experiment a bit.
> 
> Sure. Which example do you mean? How do _you_ test this?

If I can join you discussion...

It seems to me that when I set "EWS API" permissions to the ones on the printscreen I have access to *ALL* exchange mailboxes in the organizacion when I just change email in the identity. 

Any hint how to set the permisisons so the assess will be *ONLY* to one mailbox which I specify?

**Comment by ethansutcliffe** [comment]
> If I can join you discussion...
> 
> It seems to me that when I set "EWS API" permissions to the ones on the printscreen I have access to _ALL_ exchange mailboxes in the organizacion when I just change email in the identity.
> 
> Any hint how to set the permisisons so the assess will be _ONLY_ to one mailbox which I specify?

You can limit access to specific mailboxes by adding an ApplicationAccessPolicy. 
https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access

**Comment by robco** [comment]
> > If I can join you discussion...
> > It seems to me that when I set "EWS API" permissions to the ones on the printscreen I have access to _ALL_ exchange mailboxes in the organizacion when I just change email in the identity.
> > Any hint how to set the permisisons so the assess will be _ONLY_ to one mailbox which I specify?
> 
> You can limit access to specific mailboxes by adding an ApplicationAccessPolicy.
> https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access

Hi. Thank you for reply. 

I've actually realized that the key was to set permissions with type of _Delegated_ and not _Application_.

**Comment by cmin764** [comment]
So what's the minimum set of permissions you have to enable on such app in order to be able to authorize and just send an e-mail to yourself using a non-Admin simple user in the tenant?

For now I got it working only with the _Delegated_ `EWS.AccessAsUser.All` permission. (as described [here](https://github.com/robocorp/example-oauth-email#microsoft-exchange-outlook)) But this implied the need of setting an impersonation role from PowerShell to the test account using a tenant Admin.

And if I'm going to set _Application_ permissions, the non-Admin user cannot initialize and complete the flow, because during the permissions consent screen you can't accept those (as they require Admin consent), even when they were accepted in advance by the Admin from the AD UI. And even with an Admin user, without the `EWS.AccessAsUser.All` one I don't have enough "scope" to auth and send mails no matter how many other permissions I add and accept.

Is there another way to auth and send mails as a non-Admin user to yourself with `exchangelib` without the need for the `ApplicationImpersonation` role? (like some sort of configuration I missed which will skip the need for this)

**Comment by ecederstrand** [comment]
I don't have a lot of insight into the different flows or into Exchange permissions in general, but https://github.com/ecederstrand/exchangelib/pull/1121 is supposed to allow delegate access in combination with OAuth.

**Comment by cmin764** [comment]
Nice! Anyway, I can DO delegate auth and mail sending, but can I do impersonation without being an Admin? (as a simple user) Do you have any code example still working which doesn't depend on the `EWS.AccessAsUser.All` permission so I can test it myself with an app **not** using such _Delegate_ permission?
