### ISSUE TITLE
Attaching image from form to new e-mail

### ISSUE THREAD

**Issue by gregchamblin** [ecederstrand/exchangelib#750]
I have created a form in flask the goal of which is to process the exif information of the uploaded image and email the image and the reverse geocoded address. 

If I do not try to attach the image, the email sends fine.  Below is the line I am using to attach the image and the error I receive. I have not been doing this long, so let me know if I need to give you more information.

> my_file = FileAttachment(
>         name=f"{wonum}.jpg", content=image
>     )

> TypeError: Field '_content' value <exif._image.Image object at 0x0000014EAFA22940> must be of type <class 'bytes'>

**Comment by ecederstrand** [comment]
exchangelib doesn't handle exif Image objects - only `bytes`. You have to convert your file content to `bytes` first.

Assuming your image was created with the https://pypi.org/project/exif/ package, it seems there's an `image.get_file()` method that does this for you.

**Comment by gregchamblin** [comment]
That solved the issue for a file stored locally, I am now having issues with exif and flask.  Thank you very much I will continue working on this.
