### ISSUE TITLE
Feature Request: Certificate Based Authentication (CBA)

### ISSUE THREAD

**Issue by neutronscott** [ecederstrand/exchangelib#751]
I'd like to use CBA. I had it working by setting session.cert in protocol.py's raw_session. Then I took request's sample code to add cert_file in the pool without hacks to lib code.

This is what I've got

```python
import requests.adapters
from urllib3.poolmanager import PoolManager
from exchangelib.protocol import BaseProtocol
from exchangelib import Account, Credentials

class TLSClientAuth(requests.adapters.HTTPAdapter):
    def cert_verify(self, conn, url, verify, cert):
        super(TLSClientAuth, self).cert_verify(conn=conn, url=url, verify=False, cert=cert)
    def init_poolmanager(self, num_pools, maxsize, block=False):
        self.poolmanager = PoolManager(num_pools=num_pools, maxsize=maxsize, block=block,
                cert_file='user.pem')

# Tell exchangelib to use this adapter class instead of the default
BaseProtocol.HTTP_ADAPTER_CLS = TLSClientAuth

credentials = Credentials('user@domain', 'dontmatter')
account = Account(
        'user@domain', credentials=credentials, autodiscover=True)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
        print(item.subject, item.sender, item.datetime_received)
```

Seems to work but maybe can be better. Maybe can be an auth_type so that I don't even need to use Credentials (it's all in the cert).

**Comment by ecederstrand** [comment]
This is cool!

We can definitely add a `TLSClientAuth` class. I assume the only configurable thing thee is the cert file, so the class could be defined as:

```python
class TLSClientAuth(requests.adapters.HTTPAdapter):
    cert_file = 'user.pem'
    ....

# And then
TLSClientAuth.cert_file = '/path/to/cert.pem'
BaseProtocol.HTTP_ADAPTER_CLS = TLSClientAuth
```

I agree that it's stupid to require credentials in this case.

**Comment by ecederstrand** [comment]
I committed the above implementation of `TLSClientAuth`. Can you please test that?

I also attempted to remove the requirement for a `Credentials` object, but it's not possible for me to do an end-to-end test. Can you please test that part also?

**Comment by ecederstrand** [comment]
I'm uncertain if autodiscovery will work with CBA. You may need to disable that, or do your own debugging to find out if it can be made to work.

**Comment by neutronscott** [comment]
My second thought was that perhaps Credentials could be used to give path to cert.

The cert auth wasn't meant to stay. Was only my quick way to test. I removed it after setting requests to use my systems cert file that included the Enterprise CA.

autodiscover did work with my adapter and Credentials, but without Credentials was a failure on a credentials.lock() missing which your commit seems to address (just briefly reviewing on my mobile).

I like just calling super().init_poolmanager, less code the better.

I will try to test the changes at work tomorrow. Thanks for the quick implementation.

**Comment by neutronscott** [comment]
Well, shoot. I was using pip --user install of 2.2.0 on a rhel7 machine with python2.7. I can test master on python3 it will just take some more time.

**Comment by neutronscott** [comment]
It's working with the following:

```
#!/usr/bin/python3
import requests.adapters
import os
from exchangelib.protocol import BaseProtocol
from exchangelib import Account, Configuration, Credentials, DELEGATE, \
    Version, Build, CBA, TLSClientAuth

os.environ["REQUESTS_CA_BUNDLE"]="/etc/pki/tls/cert.pem"
EMAIL='xxx'
USER_PEM='/home/me/something.pem'

TLSClientAuth.cert_file = USER_PEM
BaseProtocol.HTTP_ADAPTER_CLS = TLSClientAuth

config = Configuration(auth_type=CBA)
account = Account(
        primary_smtp_address=EMAIL,
        config=config, autodiscover=True,
                access_type=DELEGATE)
```
