### ISSUE TITLE
query on sent mailbox

### ISSUE THREAD

**Issue by ludicludo** [ecederstrand/exchangelib#752]
Hi,
First of all, thank you for this nice piece of work. I already send my first message thanks to your api in python. Great for sending messages to my students :-)
I would like to insure that I sent all the expected messages by checking my sent folder.

Is it possible to query from messages you have sent the same way you do it on messages you received ?
Actually, I tried but searchable fields are different between inbox and sent folders. 

``list(my_account.sent.filter(subject_contains='some filter of my own'))`` 
raises an exception:
``InvalidField: Unknown field path 'subject_contains' on folders 
[SentItems(Root(<exchangelib.account.Account object at 0x00000230DD8CE828>, '[self]', 'root', 11, 0, 63, None, 'AAMkAGUzYTVmNDg2LTU3N2EtNDYyNi04M2I3LWI0ZGQzODY0Mjk0YwAuAAAAAACCSp8B1S7TEZ76AFAECzCJAQARUoiwEirTEZ74AFAECzCJAAAAAEIcAAA=', 'AQAAABYAAAB7AopfpewqSZ/y15b5atFAAAHwEZZF'), 'Eléments envoyés', 3333, 0, 0, 'IPF.Note', 'AAMkAGUzYTVmNDg2LTU3N2EtNDYyNi04M2I3LWI0ZGQzODY0Mjk0YwAuAAAAAACCSp8B1S7TEZ76AFAECzCJAQARUoiwEirTEZ74AFAECzCJAAAAAEIiAAA=', 'AQAAABYAAAB7AopfpewqSZ/y15b5atFAAAH8XXtO')]``
Thank you
Best regards

**Comment by ecederstrand** [comment]
You need double underscores between the field name and the modifier: `subject__contains`
