### ISSUE TITLE
How to authenticate users in an application ?

### ISSUE THREAD

**Issue by yeyeric** [ecederstrand/exchangelib#756]
Hello,

I’m creating a portal where my users would be able to send emails. The idea is that I generate template of emails Which they can eventually amend, making their life easier with.

The question I have is how I managed the login to their exchange account ? I have perfectly managed to login using login/password, working as a charm.

Therefore I could store their login/password in my database and uses this Information every time needed but that would not be secure and when changing not sync when changing password for instance.

I would have only 5-10 users so that’s not a pain for me to proceed like this but how should I do to manage properly the security ?

My thinking would be that I store an encrypted token generated once by my user, or renewed every time they change their password, which I can then store and use every time they need to access their exchange account but I’m not sure if that’s how it should be done and if so, how exactly. Tried to read about it but I’m afraid I don’t get it.

I’m using office 365 business premium

My application is running in an aws lambda function if that changes anything.

Thanks for the help

**Comment by ecederstrand** [comment]
Would you be able to create a system account that has access to the accounts of all your users? If so, that would be a better solution than storing credentials for each user.

When you are on O365, you can also look at authentication using OAuth2. It may be a better solution in your situation.

I'd rather not comment on how you should store your secrets. That would depend on your threat model.

**Comment by yeyeric** [comment]
I was thinking about it but I don't know how I should do so. I've my account which is set up as an admin but when I try to I get an error.
`a =  Account(primary_smtp_address='my_other_user@company.com', autodiscover=True, credentials=my_admin_credentials, access_type=DELEGATE) #same with IMPERSONATION`
If I try to access a.sent, I have this error message: `exchangelib.errors.ErrorItemNotFound: The specified object was not found in the store., The process failed to get the correct properties.
`

I believe it's a matter of rights but don't know what that should be ?

**Comment by yeyeric** [comment]
OK I've followed this now I don't have the error anymore, however, I'm not able to send on behalf of my other user despite this setting:
https://messageops.com/how-to-grant-full-access-to-an-office-365-mailbox/

**Comment by yeyeric** [comment]
Found my way, the idea to use a master login was the good one, very easy, and just requires 2 lines of powersheell

Connect-ExchangeOnline -UserPrincipalName admin@company.com -ShowProgress $true
Get-Mailbox | Add-RecipientPermission -Trustee admin@company.com -AccessRights SendAs
