### ISSUE TITLE
OAuth2AuthorizationCodeCredentials requires SOAP impersonation headers unconditionally

### ISSUE THREAD

**Issue by DeanArbel** [ecederstrand/exchangelib#757]
Trying to use a service that's accessible via `account.protocol` with an OAuth2 access token (via `OAuth2AuthorizationCodeCredentials`) will return the following error:

```
ExchangeImpersonation SOAP header must be present for this type of OAuth token.
```

This seems related to https://github.com/ecederstrand/exchangelib/issues/735, which was fixed by adding an identity argument to `OAuth2Credentials`. This addition is missing from `OAuth2AuthorizationCodeCredentials`.

**Comment by ecederstrand** [comment]
It's actually already supported, but not in keyword args. The referenced commit should fix that. If you can't install that, the following workaround should work.

```python
c = OAuth2AuthorizationCodeCredentials(...)
c.identity = Identity(upn='foo@example.com')
```

**Comment by DeanArbel** [comment]
The workaround worked, thank you very much!
