### ISSUE TITLE
exchangelib.errors.ErrorNonExistentMailbox: No mailbox with such guid.

### ISSUE THREAD

**Issue by mattxs** [ecederstrand/exchangelib#763]
Hi!

I have an issue with cloud EWS mailboxes. We migrate our mailboxes from "on the ground" EWS server to Cloud O365. Cloud mailboxes are not "UserMailbox" , but "RemoteUserMailbox" , which means that cloud mailboxes don't looks like mailboxes in terms of exchange on-premise.

So if I try to get Calendar or Root in RemoteUserMailbox I get `exchangelib.errors.ErrorNonExistentMailbox: No mailbox with such guid. ` and cashed_property `KeyError: 'root'` - it is the _class Account_ property.

All remote mailboxes are licensed and have the same folder's structure like "ground" boxes.
I tried to change server from EXCHANGE 2016 to 19 and to O365, tried to change access_type from IMPERSONATION to DELEGATE, but it didn't help. The error is the same everywhere.

The library works great with "ground" boxes, but could you tell me please, why do I get "No mailbox with such guid" and can't have an access to Root folder?

**Comment by ecederstrand** [comment]
I'm not very familiar with this setup, and I don't have any Exchange admin experience. is it possible that your on-prem `foo@example.com` accounts have a primary SMTP address in O365 that is something like `foo@example.com.onmicrosoft.com`? If you do an autodiscover lookup on `foo@example.com`, what is the returnes EWS endpoint and primary SMTP address?

**Comment by mattxs** [comment]
Yes, our accounts have a primary SMTP address in O365. For example, I try to work with real cloud user `testontd@ontd.ru`. _testontd_ has a primary SMTP address like `testontd@licenseramblerco.mail.onmicrosoft.com` and `testontd@licenseramblerco.onmicrosoft.com`

We do an autodiscover lookup on `testontd@ontd.ru` and it looks into the cloud, so
`autodiscover.ontd.ru    canonical name = autodiscover.outlook.com` and in returns EWS endpoint `https://outlook.microsoft.com/ews/exchange.asmx`

**Comment by ecederstrand** [comment]
I would suggest to log the XML request and response (see https://github.com/ecederstrand/exchangelib#troubleshooting). It may provide you a hint about why the error happens. It's possible that the wrong primary SMTP address is mentioned somewhere.

**Comment by mattxs** [comment]
Well, we tested a several cases of this issue and received the same error. I suppose it happens due to the hybrid condition of our user's account (trying to get cloud mailbox from the ground). At the same time, we plan to migrate all our accounts to the cloud O365, and I hope we won't be deal with this Issue. I think I'll leave this ticket open to keep you informed.

**Comment by mattxs** [comment]
Hi!

So, we found the problem. The problem was due-to library doesn't work in hybrid modification: cloud and ground.
I was trying to get cloud calendar from the cloud mailbox in O365 and it was working perfect! But if you try to get calendar (on the cloud) from the ground you get an Error like describe above.

We will migrate all our mailboxes to the cloud and will use your library.

Thank you for the help!
