### ISSUE TITLE
Soap Services EWS 

### ISSUE THREAD

**Issue by manish59** [ecederstrand/exchangelib#765]
Hi, 

Im actually trying to understand the your code and compare with the EWS soap services documentation. I have couple of questions and I would really appreciate if you can answer them
1. Every request is a post method and are your using requests.post library?
2. Is the payload str or xml or a json?
3. Do I need to put any headers when requesting the for resources ?
4. If exchange server versions change then the soap body changes ? do they have seperate documentation for server versions?

I really appreciate if you take some time to give me a reply

Thanks.

**Comment by ecederstrand** [comment]
1. Yes. Almost all requests go through `post_ratelimited()`: https://github.com/ecederstrand/exchangelib/blob/aa2b161305731eebb787d1269115df0ca9eb24a2/exchangelib/util.py#L635
1. It's XML (which is a string). The final payload is created in `wraps()`: https://github.com/ecederstrand/exchangelib/blob/aa2b161305731eebb787d1269115df0ca9eb24a2/exchangelib/transport.py#L62
1. Default headers are added when creating the session: https://github.com/ecederstrand/exchangelib/blob/aa2b161305731eebb787d1269115df0ca9eb24a2/exchangelib/protocol.py#L327. Depending on the service requested, we may add some extra headers in `extra_headers()`: https://github.com/ecederstrand/exchangelib/blob/aa2b161305731eebb787d1269115df0ca9eb24a2/exchangelib/transport.py#L52
1. Yes, it might. You used to be able to select the version on MSDN, but I can't find that function anymore. Instead, new features will usually state the version they are supported from.
