### ISSUE TITLE
Cannot read the msg attachment

### ISSUE THREAD

**Issue by WindyZheng** [ecederstrand/exchangelib#77]
I tried the example code to read my email attachment, but if the attachment is an email, it cannot be read. The printed attachments property is:
[ItemAttachment(attachment_id=AttachmentId('AQMkADY0ZTRhNjk3LTE1ODMtNGExMy05NGQwLWVjMjE2ZTdlMGUyOABGAAADmqHNeknGM0KXcj85ihwuxgcArX/iHiVc20OqOzq5BvzgKwABk2UAugAAAB968bUtHaxDl2XM1/eVKtQAAABs2v8XAAAAAQYABAAAAw==', None, None), name=None, content_type=None, content_id=None, content_location=None, size=21966, last_modified_time=EWSDateTime(2017, 2, 6, 5, 44, 29, tzinfo=<UTC>), is_inline=False)]
When I try to iterate through the attachment items, the content of the attachment doesn't exist. Will we have an enhancement to support reading attached email?

**Comment by ecederstrand** [comment]
This should already be supported. `ItemAttachment` attachments have an `item` attribute that contains the actual item:

```python
for m in messages:
    for a in m.attachments:
        if isinstance(a, ItemAttachment):
            print(a.item.subject, a.item.body)
```

**Comment by WindyZheng** [comment]
Cool, that's exactly what I want. Thank you very much!
