### ISSUE TITLE
Unexpected result of __in filter with an empty iterable

### ISSUE THREAD

**Issue by wanaryytel** [ecederstrand/exchangelib#770]
Whenever querying emails from an inbox, the `__in` filter only seems to be working when the iterable is not empty. Here's an example:

```python
account.inbox.filter(message_id__in=[]).count()
>>> 4
account.inbox.filter(message_id__in=['']).count()
>>> 0
```

I think both of those should return 0, but the first one fails to do that.

Thanks for the nice work on the library!

**Comment by ecederstrand** [comment]
What were you expecting to happen in the first case? What are the expected semantics?

For me, the query doesn't really make sense. But if I interpret it as "don't filter message_id on any values", then I  think the result is correct.

**Comment by wanaryytel** [comment]
As an example, let's say we have emails in our inbox with IDs `1`, `2` and `3`.
If I query "give me all emails where the email ID is in list [`2`, `3`]", I expect to get back `2` and `3`. Narrowing that down, a query "give me all emails where the email ID is in list [`2`]", I expect to get back only email with ID `2`.
Further narrowing, a query "give me all emails where the email ID is in list[]", I expect to get back nothing, because there are no email ID's n the list. 

If you think that this is bonkers, then this is exactly what I'm doing in order to sync all emails from an inbox to my system. Pseudo-code as follows:

```python
local_ids = get_all_synced_email_ids()
remote_ids = get_all_inbox_email_ids()

unsynced_emails = set(remote_ids) - set(local_ids)

sync_emails(inbox.filter(message_id__in=unsynced_emails))
```

Semantically it makes perfect sense in my opinion, that if `unsynced_emails` is an empty iterable, then the query will not return any emails in this case.

But moreover - the queryset style seems heavily inspired by Django ORM. That's also where I got the idea to query emails in this manner - because that's how Django ORM handles it. :)

```python
# Django
In [4]: User.objects.filter(id__in=[1, 2]).count()                                                                                          
Out[4]: 2

In [5]: User.objects.filter(id__in=[]).count()                                                                                              
Out[5]: 0
```

**Comment by ecederstrand** [comment]
Thanks for the thorough explanation! Makes much more sense now.

I agree that this is useful, and having the same behavior as Django is itself an agrument.

I'm pretty sure EWS doesn't support this type of query, so we'll have to do some kind of client-side shortcut to return an empty query. It may take some time for me to find a clean way of doing this.

**Comment by ecederstrand** [comment]
I just stumbled on a related query:

```python
account.inbox.filter(attachments__in=[]).count()
account.inbox.filter(attachments__contains=[]).count()
```

For list-type fields, what do we expect the result of this to be?

**Comment by ecederstrand** [comment]
Postgres ARRAY-type fields in Django support [__contains](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/fields/#contains) and other lookup types. The documentation does not define what the result should be when querying with an empty list of values.

I don't think it's possible or worthwhile to pursue the corner cases for list-type fields in exchangelib, and it's probably not possible to implement the other lookup types server-side, so any implementation would have to be client-side, which means we would need to fetch all items first, and then filter. This is going to be very slow when the hit rate is low.

Closing since the original issue is solved.

**Comment by wanaryytel** [comment]
@ecederstrand 
Thanks for working on this! Personally I don't need the support for such edge cases, but I think it would be good practice to throw a warning or an exception if the user tries to do something that is not supported? Otherwise the user might expect an actual result and think that this is a bug.
