### ISSUE TITLE
Language in mail forwarding

### ISSUE THREAD

**Issue by SchupsCH** [ecederstrand/exchangelib#771]
Good day, and congrats for this amazing library!

I wrote a script that does conditional forwarding of emails.

When I forward an email, the date is "rendered" to German (probably Exchange default, out of my control), rather than English (my users desire).

**This is how I create my Account object**
```
config = Configuration(server='mail.domain.com', credentials=credentials)

account = Account('sdtest@domain.com', 
config=config, 
autodiscover=False, 
access_type=DELEGATE, 
locale='en_US.UTF-8')
```

***This is how the forwarded email gets "rendered":***
```
This email was originally received from 'schups@domain.com'
________________________________________
From: Stefano
Sent: Freitag, 19. Juni 2020 11:52:30
To: final-email@domain.com
Subject: Another locale test`

This is a test
```

`Freitag, 19. Juni 2020 11:52:30` was expected to be `19 June 2020 11:52 AM`, like it is the case when I manually forward emails from the web interface (OWA).

Through OWA I confirm my language to be set to English.

What am I doing wrong/what am I missing? 

Thank you for any hint!!

**Comment by SchupsCH** [comment]
By the way, a good alternative would be to forward the email as an attachment. But is it possible?

**Comment by ecederstrand** [comment]
How do you render the email - using exchangelib or in a different client? And how do you forward the emails - using exchangelib or a different client?

**Comment by SchupsCH** [comment]
The email is forwarded via exchangelib using create_forward() and then send()

I am able to forward the email as attachment, which solves my need. I will close this issue.

```
attachment = ItemAttachment(name='Received email', item=email_to_be_forwarded)

new_email = Message(account=account,
   subject='Fwd: ' + email_to_be_forwarded.subject,
   body="Text to be defined...",
   to_recipients=['target-email@domain.com']
)

new_email.attach(attachment)
new_email.send()
```
