### ISSUE TITLE
How to send mail to stored contact group 

### ISSUE THREAD

**Issue by sebastianwindeck** [ecederstrand/exchangelib#772]
I was checking the README and stackoverflow but could find a clue, I am still testing and trying. Maybe somebody could give me a hint.

**Comment by ecederstrand** [comment]
Can you explain what you mean by a "stored contact group"?

**Comment by sebastianwindeck** [comment]
![image](https://user-images.githubusercontent.com/28544726/85851537-279d4700-b7af-11ea-83c5-07ef48c52ccf.png)

How to address some mail to such a contact group.?

**Comment by ecederstrand** [comment]
I think a contact group is also called a distribution list.

I don't know if there are better ways, but you can use `Protocol.expand_dl()` to get the members of a distribution list, and then send an email with all the members as recipients.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if this did not solve your problem.
