### ISSUE TITLE
WorkingElsewhere not shown in merged FreeBusyView result

### ISSUE THREAD

**Issue by hatl** [ecederstrand/exchangelib#777]
Hi

I've added a calendar entry from 09:00 to 16:00 with the busy type "Working Elsewhere".
When querying by using

`account.protocol.get_free_busy_info(accounts=accounts, start=start, end=end, requested_view='DetailedMerged')`

I get the following result:

```
FreeBusyView(
view_type='DetailedMerged',
merged='000000000000000000000000000000000000000000000000',
calendar_events=[CalendarEvent(start=EWSDateTime(2020, 7, 5, 7, 0), end=EWSDateTime(2020, 7, 5, 14, 0), busy_type='WorkingElsewhere', details=CalendarEventDetails(id='...', subject='tw', location=None, is_meeting=False, is_recurring=False, is_exception=False, is_reminder_set=True, is_private=False))], working_hours=[WorkingPeriod(weekdays=[1, 2, 3, 4, 5], start=datetime.time(8, 0), end=datetime.time(17, 0))], working_hours_timezone=TimeZone(bias=-60, standard_time=StandardTime(bias=0, time=datetime.time(3, 0), occurrence=5, iso_month=10, weekday='Sunday'), daylight_time=DaylightTime(bias=-60, time=datetime.time(2, 0), occurrence=5, iso_month=3, weekday='Sunday')))
```

**Expected**: the "merged" field should show "5555..."  for the time period of the "Working Elsewhere" entry

**Comment by ecederstrand** [comment]
Can you enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) and check if the posted `merged` value is also the string that the server responds with?

**Comment by hatl** [comment]
Unfortunately, the server returns it in the same way. See attached log.
Seems like "WorkingElsewhere" is not supported by:
https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/mergedfreebusy

But the Outlook REST API would support it:
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar
[exchangelib.txt](https://github.com/ecederstrand/exchangelib/files/4851554/exchangelib.txt)

**Comment by ecederstrand** [comment]
Ok. I'm not sure there's anything we can do here. I'm not keen on fiddling with the value that EWS returns.
