### ISSUE TITLE
.filter('from:"Example"'): gives wrong results

### ISSUE THREAD

**Issue by iconberg** [ecederstrand/exchangelib#778]
Hello,

i have following code:

```
    orders_test = account.inbox / 'Orders_test'
    for item in orders_test.filter('from:"Orders test"'):
    #for item in orders_test.all():
        print(item.sender,
              item.subject,
              item.datetime_sent,
              )
```
There are 3 mails in the folder, all sent from the same device with the same account at different times.
With .filter i got 2 mail back, with .all i got 3 mails back.

.filter result:
```
Mailbox(name='Orders test', email_address='orderstest@xyz.com', routing_type='SMTP', mailbox_type='OneOff') Bestellung: ghjh 2020-06-25 09:04:00+00:00
Mailbox(name='Orders test', email_address='orderstest@xyz.com', routing_type='SMTP', mailbox_type='OneOff') Bestellung: test 2020-06-24 09:34:11+00:00
```

.all result:
```
Mailbox(name='Orders test', email_address='orderstest@xyz.com', routing_type='SMTP', mailbox_type='OneOff') Bestellung: gshfg 2020-06-29 09:32:10+00:00
Mailbox(name='Orders test', email_address='orderstest@xyz.com', routing_type='SMTP', mailbox_type='OneOff') Bestellung: ghjh 2020-06-25 09:04:00+00:00
Mailbox(name='Orders test', email_address='orderstest@xyz.com', routing_type='SMTP', mailbox_type='OneOff') Bestellung: test 2020-06-24 09:34:11+00:00
```

Is this a bug, or doing i something wrong?

Versions:
```
Name                : EX2016
Edition             : Standard
AdminDisplayVersion : Version 15.1 (Build 1913.5)
```

`exchangelib 3.2.0, python 3.7`

**Comment by ecederstrand** [comment]
That's weird. This should just work. This is a QueryString filter; we just ship that off to the server and wait for the result.

I see that the missing email is the newest one. I know that Exchange does some sort of full-text indexing on the database, and that this index can be slow to update. But it should find stuff from yesterday.

**Comment by iconberg** [comment]
I checked the exchange,ContextIndexState gives an "Healthy" status. But i am not sure how good this info is.

I deleted the specifc mail an resend a new one, the problem vanished. But if the index could be a source of trouble i go with .all(), we will the mails process hourly so there are only some dozenz that are moved afterwards.

Thanks for your help.

**Comment by ecederstrand** [comment]
You could try avoiding the QueryString filter and do a normal filter on the `from` field (called `author` in exchangelib because `from` is a reserved word in Python): `orders_test.filter(author='orderstest@xyz.com')`.
