### ISSUE TITLE
PidLidGlobalObjectId?

### ISSUE THREAD

**Issue by CodersAreImaginative** [ecederstrand/exchangelib#78]
Thanks for your great work on this immensely useful library, which I have personally put to good work.

For some analysis I wanted to be able to extract an extended property of the CalendarItem, which identifies the same meeting across multiple calendars.

Unfortunately, item_id will not fulfil this role as it is unique to the instance of the particular CalendarItem and the ID that I would be interested in is one that remains identical for the same meeting appointment across several users' records in the Exchange database.

I understand there is such a property and that it is called PidLidGlobalObjectId according to this source:
http://interoperability.blob.core.windows.net/files/MS-OXPROPS/[MS-OXPROPS].pdf (page 86, bottom)

I tried extending the basic CalendarItem following your directions in the dialogue with amille44420 and your fix #25:
```
class GOI(ExtendedProperty):
    property_id = '6ED8DA90-450B-101B-98DA-00AA003F1305'
    property_name = 'PidLidGlobalObjectId'
    property_type = 'Binary'

CalendarItem.register('PidLidGlobalObjectId', GOI)

items = account.calendar.filter( [...] ).only( [...] 'PidLidGlobalObjectId', 'subject')
```
However, when I inspect the resultant object it just tells me the value of the field PidLidGlobalObjectId is "None", which is a bit of a surprise to me.

Here is a link to an example from where people are advised to use the sibling field "PidLidCleanGlobalObjectId' as a way to map the same calendar item across multiple users' folders:

http://stackoverflow.com/questions/38271407/ews-given-an-appointment-get-the-owners-copy-of-the-appointment

I'd much appreciate it if you could potentially shed some light upon this issue, which probably has a lot to do with me being a relative newcomer to Python and (the innards of) Exchange.

**Comment by ecederstrand** [comment]
Hmm, I'll have to look into it in more detail later. ExtendedProperties are known to work, at least for some subset of ExtendedProperty functionality. As a first test, you could try to enable debug logging and check if the property is returned in the XML response, and we're just not picking it up:

```python
import logging
logging.basicConfig(level=logging.DEBUG)

# Your code here
```

**Comment by CodersAreImaginative** [comment]
Thanks for your quick reply. I enabled debug logging as you suggested. It took me a little while to get working as apparently Pyzo doesn't implement it that well. However, PyCharm CE displays beautifully thorough debug logs. I have copied the XML for the request and pasted in the below. It seems to be well formed:
```
Request headers: {'User-Agent': 'python-requests/2.13.0', 'Accept-Encoding': 'compress, gzip', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Cookie': 'exchangecookie=BLABLABLABLABLABLABLA', 'Content-Length': '10079', 'Authorization': 'Basic BLABLABLABLBLABLABLABLABLA'}
Response headers: {'Cache-Control': 'private', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Server': 'Microsoft-IIS/8.5', 'request-id': 'be60d5fe-193e-4949-a289-5a296e5f641e', 'X-CalculatedBETarget': 'HE1PR0302MB2636.eurprd03.prod.outlook.com', 'X-BackEndHttpStatus': '200', 'Set-Cookie': 'exchangecookie=BLABLABLABLABLABLABLABLABLA; path=/', 'X-AspNet-Version': '4.0.30319', 'X-DiagInfo': 'HE1PR0302MB2636', 'X-BEServer': 'HE1PR0302MB2636', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'VI1PR10CA0067', 'Date': 'Tue, 07 Feb 2017 10:15:03 GMT'}
DEBUG:exchangelib.util:Request data: b'<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2016" /></s:Header><s:Body><m:GetItem><m:ItemShape><t:BaseShape>IdOnly</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="calendar:Location" /><t:FieldURI FieldURI="calendar:OptionalAttendees" /><t:FieldURI FieldURI="calendar:Start" /><t:ExtendedFieldURI PropertyName="PidLidGlobalObjectId" PropertySetId="6ED8DA90-450B-101B-98DA-00AA003F1305" PropertyType="Binary" /><t:FieldURI FieldURI="item:Subject" /><t:FieldURI FieldURI="calendar:Organizer" /><t:FieldURI FieldURI="calendar:End" /><t:FieldURI FieldURI="calendar:RequiredAttendees" /></t:AdditionalProperties></m:ItemShape>
```
Since the property type gets passed on to the Exchange server it could be that I should use the notation specified in the documentation. I.e. "ptBinary" and not "Binary". I thought this was something for Python to digest, but when it gets passed in the XML it's clearly meant for Exchange.

By the way there is not a single mention of PidLidGlobalObjectId anywhere in the server response. I have included a heavily redacted version of one calendar item in the below:
`DEBUG:exchangelib.util:Response data: <?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="1" MajorBuildNumber="888" MinorBuildNumber="25" Version="V2017_01_07" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body><m:GetItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetItemResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode><m:Items><t:CalendarItem><t:ItemId Id="AAMkADQ5MTM1MmZjLWIzZjYtNDEzOC1iOTY3LTFhMmRmOGFiODMyYwBGAAAAAADQsRbVskYrR424s+ei8zzQBwDl4tVSSbz7SI7Xqrr38fy/AAAAAAENAADl4tVSSbz7SI7Xqrr38fy/AAACDdzsAAA=" ChangeKey="DwAAABYAAADl4tVSSbz7SI7Xqrr38fy/AAACEEwm"/><t:Subject>Interview with X / Y, Z</t:Subject><t:Start>2016-01-14T09:00:00Z</t:Start><t:End>2016-01-14T10:00:00Z</t:End><t:Location>Room 188</t:Location><t:Organizer><t:Mailbox><t:Name>Board of Directors</t:Name><t:EmailAddress>boardofdirectors@acme.com</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>OneOff</t:MailboxType></t:Mailbox></t:Organizer><t:RequiredAttendees><t:Attendee><t:Mailbox><t:Name>The Man/Acme</t:Name><t:EmailAddress>theman@acme.com</t:EmailAddress><t:RoutingType>SMTP</t:RoutingType><t:MailboxType>OneOff</t:MailboxType></t:Mailbox>`

**Comment by CodersAreImaginative** [comment]
```
Hmm.. when I change the datatype it stops and throws the following error:
Traceback (most recent call last):
  File "/Users/TheOtherGuy/PycharmProjects/Sugekop/sugekop.py", line 86, in <module>
    MeetingOrganizer = items[x].organizer.email_address
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/queryset.py", line 176, in __getitem__
    list(self.__iter__())  # Make sure cache is full by iterating the full query result
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/queryset.py", line 163, in __iter__
    for val in result_formatter(self._query()):
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/account.py", line 381, in fetch
    for i in GetItem(account=self).call(items=ids, folder=validation_folder, additional_fields=only_fields):
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/services.py", line 410, in _pool_requests
    for elem in r.get():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/services.py", line 399, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/services.py", line 460, in _get_payload
    additional_property_elems = folder.additional_property_elems(additional_fields)
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/folders.py", line 2027, in additional_property_elems
    for elem in item_model.additional_property_elems(fieldname=f):
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/folders.py", line 1236, in additional_property_elems
    elems.append(field_uri.field_uri_xml())
  File "/Users/TheOtherGuy/Library/Python/3.6/lib/python/site-packages/exchangelib/folders.py", line 765, in field_uri_xml
    assert cls.property_type in cls.PROPERTY_TYPES
AssertionError

Process finished with exit code 1
```
Based on the following code:
```
class GOI(ExtendedProperty):
    property_id = '6ED8DA90-450B-101B-98DA-00AA003F1305'
    property_name = 'PidLidGlobalObjectId'
    property_type = 'PtypBinary'

CalendarItem.register('PidLidGlobalObjectId', GOI)

credentials = Credentials(BLABLABLABLA)

        account = Account(primary_smtp_address=usr, credentials=credentials,
                          autodiscover=True, access_type=DELEGATE)

        items = account.calendar.filter("start >= 'BLABLABLA' and end < 'BLABLABLABLA'").only('organizer', 'start', 'end', 'location', 'required_attendees', 'optional_attendees', 'PidLidGlobalObjectId', 'subject')
```

**Comment by ecederstrand** [comment]
Hmm, `PtypBinary` is not a valid `PropertyType` according to https://msdn.microsoft.com/en-us/library/office/aa564843(v=exchg.150).aspx. Can you also paste the `GetItem` request that happened before the response you pasted above?

The StackOverflow post you linked to mentions ` PidLidCleanGlobalObjectId` and `Binary`. Have you tried that combination?

**Comment by ecederstrand** [comment]
Good news. I got this working by expanding the `ExtendedProperty` implementation. According to https://social.technet.microsoft.com/Forums/projectserver/en-US/b71344ff-1581-4fc8-adda-681afe070255/getting-named-properties-via-ews?forum=exchangesvrdevelopment you can access the GlobalObjectId property by sending this `AdditionalProperties` XML element:

```xml
<t:ExtendedFieldURI DistinguishedPropertySetId="Meeting" PropertyId=
"3" PropertyType="Binary" />
```

which can now be generated with this code:

```python
a = Account(email, credentials=Credentials(email, password), autodiscover=True)

class GlobalObjectId(ExtendedProperty):
    distinguished_property_set_id = 'Meeting'
    property_id = 3
    property_type = 'Binary'

CalendarItem.register('global_obj_id', GlobalObjectId)
for c in a.calendar.all().only('global_obj_id'):
     print(c. global_obj_id)
```
