### ISSUE TITLE
Problems moving emails from one mailbox to another (and to different (sub)folders within)

### ISSUE THREAD

**Issue by wanaryytel** [ecederstrand/exchangelib#780]
I've been wondering for a while whether exchangelib supports moving emails from one mailbox to another, so something like this: 

```python3
account1 = Account('test1@test.com', ...)
account2 = Account('test2@test.com', ...)

account1.inbox.all()[0].move(account2.inbox)
```

From this issue https://github.com/ecederstrand/exchangelib/issues/414 I kind of get the feeling that this is supported but I can't find anything in the docs. Is it supported or not?  

Anyways, assuming for a moment that it is [supposed to be] supported, I'm running into all kinds of trouble when attempting this. Couple of things I've tried in semi-pseudocode:

```python3
account1 = Account('test1@test.com', ...)
account2 = Account('test2@test.com', ...)

account1.inbox.all()[0].move(account2.inbox)

>>> ErrorItemNotFound: The specified object was not found in the store., The process failed to get the correct properties.

# From this issue this seems to be a permissions issue https://github.com/ecederstrand/exchangelib/issues/548
# What about a random subfolder?

account2.inbox // 'Subfolder'
>>> Folder(...)  
# It exists, cool

account2.inbox // 'Non-existent subfolder'
>>> ErrorFolderNotFound: No subfolder with name 'Non-existent subfolder'
# Makes sense

account1.inbox.all()[0].move(account2.inbox // 'Subfolder')
>>> ErrorToFolderNotFound: The specified target folder could not be found.
# :(

# So, what if we try to move to a folder that really doesn't exist?
account1.inbox.all()[0].move(account2.inbox // 'Non-existent subfolder')
>>> ErrorFolderNotFound: No subfolder with name 'Non-existent subfolder'
# Hmm, so in fact exchangelib does tell some kind of a difference between a real and a non-existing folder,
# but tells me that neither exist. What's the deal?
```

I tried to poke around a bit more but with no success and the results shown here seemed weird enough to come asking for help. Am I missing something? Maybe all of this is related to not having enough permissions? Is there a way I could test it?

**Comment by wanaryytel** [comment]
It seems that this was a permissions issue all along. For anyone stuck with this: in order to move/copy emails between mailboxes, it's not enough if you have access to both of the accounts. The Account should be a shared mailbox (as far as I know about EWS which is not a lot).

**Comment by Gokulhirani** [comment]
i am still unable to move mails from one mailbox to another mailbox ,I gave the permission and also it is shared mailbox then give me error like this The specified object was not found in the store
