### ISSUE TITLE
Reopening - UnauthorizedError when using OAuth to connect to outlook.office365.com #773

### ISSUE THREAD

**Issue by vprem** [ecederstrand/exchangelib#781]
full_access_as_app is opening up the full access to all mailboxes. IT team is not giving this permission for us.
is there a way to access a mail box alone?
Our application only needed this. 

IT team is will to give full_access permission to one or few mail boxes alone but not to all mail boxes.

**Comment by ecederstrand** [comment]
I don’t know anything about the permission system I Exchange, unfortunately. You’ll have to work with your admins to get the permissions you need for your task.

**Comment by vprem** [comment]
is it possible for you to get the information ?

"Delegated permissions are used by apps that have a signed-in user present. For these apps, either the user or an administrator consents to the permissions that the app requests and the app can act as the signed-in user when making API calls."

From the above Microsoft document, it seems user level permission is OK to access mail box. 
But in our case it is asking for full_access_as_app permission.

**Comment by ecederstrand** [comment]
exchangelib doesn’t ask for specific permissions. It calls various services that your authenticated user may or may not have permissions to call on behalf of other accounts.

You can enable debug logging and see which service is called when you get permission errors. Then ask your admins to grant you that acces, or find a way to not call that service if you don’t need it.

**Comment by vprem** [comment]
```
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Authorization': 'Bearer XXXX'} and data b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/><t:ExchangeImpersonation><t:ConnectingSID><t:PrimarySmtpAddress>ABX@XYZ.com</t:PrimarySmtpAddress></t:ConnectingSID></t:ExchangeImpersonation></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>client ID</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>'
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'stream': False, 'allow_redirects': False, 'json': None, 'timeout': 120}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): outlook.office365.com:443
DEBUG:urllib3.connectionpool:https://outlook.office365.com:443 "POST /EWS/Exchange.asmx HTTP/1.1" 401 0
DEBUG:exchangelib.util:Retry: 0
Waited: 10
Timeout: 120
Session: 28707
Thread: 140631909172992
Auth type: <requests_oauthlib.oauth2_auth.OAuth2 object at 0x7fe767614860>
URL: https://outlook.office365.com/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7fe7676144e0>
Allow redirects: False
Streaming: False
Response time: 1.0735664519888815
Status code: 401
```

On enabling debug logs and pasting above.

Can you please tell us which service it is trying to access and so failing with status 401

**Comment by vprem** [comment]
Debugged further and able to conclude that exchange lib is not have the support of user level authentication.
It is having app level authentication. App level authentication means that full_access_as_app permission is needed in the azure port during the app registration. 

Can you please support us with user level authentication?  I mean on running the client application, it can request for username and password for authentication. Once the user is authorized, app can proceed further

**Comment by vprem** [comment]
OAuth2AuthorizationCodeCredentials() can be used. Can be help us with the format of the access_token?

**Comment by ecederstrand** [comment]
The `access_token` argument to `OAuth2AuthorizationCodeCredentials` should be an `oauthlib.oauth2.OAuth2Token` instance, or just a dict of the form `{'access_token': 'MY_TOKEN'}`

**Comment by vprem** [comment]
Still it is giving same error.  
In the case,  https://github.com/ecederstrand/exchangelib/issues/747
piskvorky mentioned that he too faced this issue and full_access_as_app solved this issue.
And after that, he commented that without full_access_as_app also working.  As show below
 ```
piskvorky commented on May 13 • 
I confirm the above works from 3.2.0. Even after removing the full_access_as_app permission.
```
For us we were not able to succeed without full_access_as_app. Is it possible for you to help us in this regards?

**Comment by ecederstrand** [comment]
@piskvorky do you know how you got your code to work without `full_access_as_app`?

**Comment by piskvorky** [comment]
My comments included concrete screenshots and code – not sure what else you need.

My use-case was for *application access* though (app acts as its own entity), not delegating to individual users (app works on behalf of concrete users).

**Comment by vprem** [comment]
Thank you All for the support. I will close this case.
