### ISSUE TITLE
Find mailbox database for user account

### ISSUE THREAD

**Issue by levensailor** [ecederstrand/exchangelib#783]
I'm able to connect to an account, and the closest thing i've seen to do this is:

account.ad_response

but the mdb_dn appears to be the legacy dn and does not include the CN of the mailbox database that I need. 

any ideas to what methods I can use in this library to find the distinguished mailbox dn that has a CN=XXX that I need?

**Comment by ecederstrand** [comment]
Sorry, I have no idea. I don't even know if EWS or autodiscover responses contain that information.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you find any hints that this info is available via EWS.
