### ISSUE TITLE
Credentials get authentication error 

### ISSUE THREAD

**Issue by Abhi-1504** [ecederstrand/exchangelib#786]
I am using exchangelib to extract emails from a mailbox hosted on my organisation EWS managed server. It has been working fine till last week but now it throws Authentication error of wrong username or password when executed. 

This error is not consistent as for some runs it's still works and I get the desired output. I am using Configuration object and auth_type to NLTM. Kindly help, let me know if any further information is needed.

**Comment by Abhi-1504** [comment]
Hi @ecederstrand 

Kindly help on this issue.

**Comment by ecederstrand** [comment]
If it works sometimes, than this is probably not an issue with exchangelib.

It's possible that you are being rate-limited by the server. Either talk to your Exchange server admins about raising the connection limits for your account, or use the rate-limiting policy feature to hide the fact that you are being rate-limited.

**Comment by Abhi-1504** [comment]
Hi @ecederstrand 

Thanks for the response. Can you please refer me to the resource that explains the usage rate-limiting policy feature.

**Comment by ecederstrand** [comment]
https://ecederstrand.github.io/exchangelib/#fault-tolerance

**Comment by Abhi-1504** [comment]
Thanks for your help. Closing this issue.
