### ISSUE TITLE
Autodiscover fails on ChunkedEncodingError instead of continuing to the next server

### ISSUE THREAD

**Issue by SamCB** [ecederstrand/exchangelib#79]
Hi there, wondering if you'd know anything about some issues we've been having.

Yesterday, with no particular changes on our end, we started getting errors:

```
DEBUG:exchangelib.autodiscover:Attempting autodiscover on email ***@*****.com
DEBUG:exchangelib.autodiscover:Waiting for _autodiscover_cache_lock
DEBUG:exchangelib.autodiscover:_autodiscover_cache_lock acquired
DEBUG:exchangelib.autodiscover:Cache miss for domain example.com credentials ***@*****.com
DEBUG:exchangelib.autodiscover:Cache contents:
{}
DEBUG:exchangelib.autodiscover:Trying autodiscover on https://*****.com/Autodiscover/Autodiscover.xml
DEBUG:exchangelib.transport:Getting autodiscover auth type for https://*****.com/Autodiscover/Autodiscover.xml 10
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): *****.com
DEBUG:requests.packages.urllib3.connectionpool:https://*****.com:443 "HEAD /Autodiscover/Autodiscover.xml HTTP/1.1" 400 0
DEBUG:requests.packages.urllib3.connectionpool:Resetting dropped connection: *****.com
DEBUG:requests.packages.urllib3.connectionpool:https://*****.com:443 "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 400 None
DEBUG:exchangelib.autodiscover:Releasing_autodiscover_cache_lock

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 535, in _update_chunk_length
      self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b’'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
      yield
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 590, in read_chunked
      self._update_chunk_length()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 539, in _update_chunk_length
      raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 719, in generate
      for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 428, in stream
      for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 618, in read_chunked
      self._original_response.close()
  File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
      self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
      raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.5/site-packages/exchangelib/account.py", line 43, in __init__
      credentials=credentials, verify_ssl=verify_ssl)
  File "/usr/local/lib/python3.5/site-packages/exchangelib/autodiscover.py", line 179, in discover
      email=email, verify=verify_ssl)
  File "/usr/local/lib/python3.5/site-packages/exchangelib/autodiscover.py", line 200, in _try_autodiscover
      verify=verify)
  File "/usr/local/lib/python3.5/site-packages/exchangelib/autodiscover.py", line 238, in _autodiscover_hostname
      auth_type = _get_autodiscover_auth_type(url=url, verify=verify, email=email)
  File "/usr/local/lib/python3.5/site-packages/exchangelib/autodiscover.py", line 307, in _get_autodiscover_auth_type
      verify=verify)
  File "/usr/local/lib/python3.5/site-packages/exchangelib/transport.py", line 166, in get_autodiscover_authtype
      verify=verify)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 535, in post
      return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
      resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
      r.content
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 797, in content
      self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 722, in generate
      raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

We have no clue what caused it, we tried both updating Exchangelib and rolling it back to a previous version that worked, all of them gave the same error. We've tried rolling back versions of our own codebase, still exact same failures. We've tried two different accounts.

We can connect to both the accounts via the Microsoft Remote Connectivity Analyzer and Microsoft Outlook.

Wondering if you (or anyone else using this library) has come across this issue?

Thanks!

**Comment by ecederstrand** [comment]
I haven't come across this myself, but the root of the cause is this:

```
DEBUG:requests.packages.urllib3.connectionpool:https://*****.com:443 "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 400 None
```

We try to POST an autodiscover request (an XML document describing the information we want to retrieve) for ***@***.com to `https://*****.com/Autodiscover/Autodiscover.xml`. Let's assume this is where you expected autodiscover requests to land (otherwise there's a bug in our autodiscover algorithm). This server is returning HTTP 400 (Bad Request). Additionally, it's sending a bogus response body which the the `requests` module doesn't like, so `requests` throws `ChunkedEncodingError`, but that's actually a bit irrelevant here because the interesting part is the HTTP 400.

I have no idea why your server would throw HTTP 400 on this request. Maybe it's misconfigured, maybe it's not the right server to handle this request, maybe we're not trying hard enough to look like a Microsoft client.

**Comment by ecederstrand** [comment]
If you are panicking, you could work around this for now by hard-coding the EWS server in a `Configuration` object and pass that to your `Account` objects along with `autodiscover=False` to disable autodiscover entirely.

This assumes that it's predictable which accounts are located on which EWS servers.

**Comment by SamCB** [comment]
I had a closer look at the output of https://testconnectivity.microsoft.com for what's going wrong with autodiscover. It tests for autodiscover in the following steps:

1. Look for Autodiscover URL `https://*****.com:443/Autodiscover/Autodiscover.xml`; then if that fails
2. Look for Autodiscover URL `https://autodiscover.*****.com:443/Autodiscover/Autodiscover.xml`; then if that fails
3. Use the HTTP redirect method, calling `autodiscover.*****.com`, retrieving an `HTTP 301/302` request and using that as the autodiscover URL.

(There may be more steps, but it always succeeded at 3).

I had a play around in the codebase and from what I understand, we're failing fatally at step 1 instead of progressing onto steps two and three as testconnectivity performs it. I'm not sure why it suddenly started failing this week, but by hardcoding in step 3, I've been able to progress.

If I was to take a look at how we currently implement the autodiscover steps and submitted a PR that would fix cases like this, would you be interested in merging it? Do you have any other thoughts?

**Comment by ecederstrand** [comment]
Thanks for investigating! I think an immediate fix would be to catch `ChunkedEncodingError` and handle HTTP 400, and mark both as a failed autodiscover step so autodiscover can continue to the correct endpoint.

The Microsoft autodiscover is a pretty convoluted algorithm and it's not always clear what conditions in the wild must be met for an endpoint to be considered valid.

I'd be happy to review any fixes you come up with. Just beware that the autodiscover code is not the most well-organized code I have ever produced :-)

**Comment by ecederstrand** [comment]
I hope I fixed this earlier today by catching the `ChunkedEncodingError`. Please re-open if it's still an issue. I can't test myself since `*****.com` is not a valid hostname :-)

**Comment by SamCB** [comment]
Sorry, now getting a syntax error on the latest commit in master.

```
  File "<string>", line 1
    raise AutoDiscoverFailed("Error guessing auth type: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))",) from ChunkedEncodingError(ProtocolError('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read)),)
                                                                                                                                                                                                                                                             ^
SyntaxError: invalid syntax
```

**Comment by ecederstrand** [comment]
I think this is `raise_from()` from the `futures` package that is having a fit. It does all sorts of magic to emulate `raise foo from bar` in Python3.

Can you try removing `raise_from` at https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/autodiscover.py#L354 with a simple `raise AutoDiscoverFailed(...)`?

**Comment by SamCB** [comment]
Did it, worked, rolled back, still worked. Could not reproduce the syntax error.

No clue why that ended up happening. Looks like your changes fixed it, will leave it be for now.

Are your changes available on pip or should I install manually for now?

**Comment by SamCB** [comment]
Sorry, was wrong, did not seem to work. I'll give the solution I've been working on a try and hopefully make a PR early next week.

**Comment by ecederstrand** [comment]
Ok. Forcefully raising `ChunkedEncodingError` within `get_autodiscover_authtype()` should make this reproducible. I'll see if I can write a test case that does exactly that.

**Comment by ecederstrand** [comment]
If you want, you can send the hostname in question to erik@cederstrand.dk so I can test the URL negotiation. That should be possible without having the correct username/password.

**Comment by SamCB** [comment]
Ah, well. I think we've found what's actually gone wrong here. Seems a library we were using for logging, [watchtower](https://github.com/kislyuk/watchtower), was causing some kind of conflicts. Removing watchtower stopped the problems.

I have NO clue why watchtower was having an impact on the requests made to an exchange server and why it suddenly Monday last week, but it appears to be working fine.

We have no qualms removing watchtower and doing something else for logging (it was responsible for a whole host of other issues), but wondering if you have any idea as to why the watchtower library would be causing our exchange server to return HTTP 400 errors to exchangelib?

Thank you so much for your help in this issue.

**Comment by ecederstrand** [comment]
I sorry, I have no idea either why `watchtower` would do that to you. We're not doing anything fancy when we're logging, just the plain vanilla

```python
log = logging.getLogger(__name__)
log.info('foo')
```
