### ISSUE TITLE
group members

### ISSUE THREAD

**Issue by Idriel** [ecederstrand/exchangelib#790]
Hi,
How to get 
is smtp group or single member and then get recursively all mail address if it's a group.  

Thank you.

**Comment by Idriel** [comment]
Hi, i found - account.protocol.expand_dl
is there some property how I can check. if smtp_address is DL or not, rather then catching exception?

**Comment by ecederstrand** [comment]
When you get contacts in a contact folder, the returned items are either `Contact` or `DistributionList` instances. That should enable you to only call `expand_dl()` on the distribution lists.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still have issues with this.
