### ISSUE TITLE
how to get the attributes of rooms?

### ISSUE THREAD

**Issue by YunusovSamat** [ecederstrand/exchangelib#792]
Your library is super, thanks.

I set the attribute for the room.
PowerShell: set-Mailbox "meeting-room-1" -ResourceCustom ("VKS")
To get the attribute via PowShell: https://docs.microsoft.com/ru-ru/powershell/module/exchange/get-resourceconfig?view=exchange-ps&viewFallbackFrom=exchserver-2016
can i get a given attribute via exchangelib?

**Comment by ecederstrand** [comment]
Is this value possible to get via EWS? I can't find any documentation with a quick google search.

**Comment by YunusovSamat** [comment]
through EWS did not find, thought you knew

**Comment by ecederstrand** [comment]
After some more searching, I don't think this information can be accessed via EWS. See e.g. https://social.technet.microsoft.com/Forums/office/en-US/9eef45a5-dd1d-4912-9beb-bded7b40cb9e/ews-managed-api-using-c?forum=exchangesvrdevelopment

Feel free to reopen if you find some way to do this anyway with EWS.
