### ISSUE TITLE
Internal Server Error while marking mail as read

### ISSUE THREAD

**Issue by Abhi-1504** [ecederstrand/exchangelib#793]
I am getting the below error stack while trying to read and download attachments from the mailbox for specified sender's mail id. The error occurs on saving the marked mail as read also while sending email, it's able to make connection and get the account object created for the mail box. The code was working fine till yesterday and I am not sure what caused the problem today. I have pasted my functions dealing with the operations on emails below. Kindly help.

**Error:**

> Traceback (most recent call last):
>   File "/home/appuser/sandbox/mail_module.py", line 129, in get_mails
>     paths = Download( item, download_path, invoice_check=True)
>   File "/home/appuser/sandbox/mail_module.py", line 25, in Download
>     mails.save()
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/item.py", line 134, in save
>     send_meeting_invitations=send_meeting_invitations
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/item.py", line 217, in _update
>     send_meeting_invitations_or_cancellations=send_meeting_invitations)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 450, in bulk_update
>     suppress_read_receipts=suppress_read_receipts,
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 445, in <genexpr>
>     i if isinstance(i, Exception) else Item.id_from_xml(i)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 307, in _consume_item_service
>     for i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 541, in _pool_requests
>     elems = r.get()
>   File "/home/appuser/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
>     raise self._value
>   File "/home/appuser/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 520, in <lambda>
>     lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 66, in _get_elements
>     response = self._get_response_xml(payload=payload)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 151, in _get_response_xml
>     res = self._get_soap_messages(body=body, **parse_opts)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 258, in _get_soap_messages
>     cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 294, in _raise_soap_errors
>     raise vars(errors)[code](msg)
> exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Controller.py", line 75, in <module>
>     account, unread_mails, emails_ids_and_pdf_list = m.get_mails(username = username,password = password, from_email_ids = from_email_ids, limit = limit, download_path = download_path, subdirectory = subdirectory)
>   File "/home/appuser/sandbox/mail_module.py", line 139, in get_mails
>     item.move(to_folder)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/item.py", line 269, in move
>     res = self.account.bulk_move(ids=[self], to_folder=to_folder)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 552, in bulk_move
>     to_folder=to_folder,
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 550, in <genexpr>
>     i if isinstance(i, Exception) else Item.id_from_xml(i)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 307, in _consume_item_service
>     for i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/move_item.py", line 15, in call
>     to_folder=to_folder,
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 66, in _get_elements
>     response = self._get_response_xml(payload=payload)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 151, in _get_response_xml
>     res = self._get_soap_messages(body=body, **parse_opts)
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 258, in _get_soap_messages
>     cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
>   File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 294, in _raise_soap_errors
>     raise vars(errors)[code](msg)
> exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.

**Functions:**

```
import os
import re
from exchangelib import Credentials, Account, FileAttachment, Mailbox, Message, NTLM, Configuration, DELEGATE
from log import logger
from ControllerErrors import ControllerError
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
import warnings
from zipfile import ZipFile
from shutil import copy2
warnings.filterwarnings("ignore")

def Download(mails,download_path,invoice_check=False):
    """
    Download the attachments from mails
    Parameters:
        mails (items): mail item object
        download_path (str): path where invoices needs to be downloaded
        invoice_check (bool): variable to check if the downloaded attachment needs unique identifier in file name.
    Return:
        local_paths (list): list of invoices downloaded (multiple in case of zipped files)
    """
    # MArking mails as read
    mails.is_read = True
    mails.save()

    # list to populate the path of downloaded invoices
    local_paths = list()
    mail_attachments = mails.attachments
    #Download the attachments

    # Checking if mail has atleast on attachment
    if len(mail_attachments) > 0:
        #path for downloading attachments
        attachment_folder_path = download_path

    #downloading the attachments
    for attachment in mail_attachments:
        if isinstance(attachment, FileAttachment):
            local_path = os.path.join(attachment_folder_path,attachment.name.replace(" ", ""))
            if invoice_check:
                index = local_path.rfind('.')
                local_path = local_path[:index] + str(mails.message_id) + local_path[index:]
            with open(local_path, 'wb') as f:
                f.write(attachment.content)

        # Extracting the invoices from the attachment if it's a compressed file (.zip extension)
        if local_path != None and '.zip' in local_path:
            tmp = os.path.join(download_path,'unzip')
            if not os.path.exists(tmp):
                os.mkdir(tmp)
            with ZipFile(local_path, 'r') as zipfile:
                zipfile.extractall(tmp)
            os.remove(local_path)
            filelist=os.listdir(tmp)
            for files in filelist:
                filename = os.path.join(tmp,files)
                index = filename.rfind('.')
                file = filename[filename.rfind(os.sep)+1:index] + str(mails.message_id) + filename[index:]
                local_path = os.path.join(download_path,file)
                local_paths.append(local_path)
                copy2(filename,local_path)
                os.remove(filename)
            os.rmdir(tmp)
    # Returrng the path for the downloaded and extracted invoices
    if len(local_paths) > 0:
        return local_paths
    else:
        local_paths = [local_path]
        return local_paths


def get_mails(username, password, download_path,from_email_ids, subdirectory,limit = 5):
    """
    Read emails from a given outlook mailbox and save attachments generating a list of email to process
    Parameters:
        username (str): Username for the master mailbox
        password (str): Password for the master mailbox
        download_path (str): download path for the invoices
        from_email_ids (list): list of the senders' email address for which the mails need to processed
        subdirectory (list): list of subdirectories from which mails need to be fetched from
        limit (int): number of mails tio be fetched and processed (currently obsolute, used for batch processing)
    Return:
        len(Emails) (int): Number of filtered unread emails
        email_id_list (list): List of tuples containg message id, path of downloaded invoice and mailbox directory of mail from which it was downloaded from
    """

    # Configuration setup for master mailbox and fetching emails from EWS API
    try:
        BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
        credentials = Credentials(username,password)
        config = Configuration(server='xxx.xxx.xxx', credentials=credentials, auth_type=NTLM)
        account = Account(primary_smtp_address=username, config=config, credentials=credentials, autodiscover=False, access_type=DELEGATE)
    except Exception as e:
        logger.error(str(e))
        exit(0)
        raise ControllerError(sys_err_msg=str(e), custom_err_msg="Connection Error with mailbox")

    logger.info("Reading emails from master mailbox...")

    # Creating list of mailbox directory objects from which mails needs to be fetched from
    email_id_list = list()
    if len(subdirectory) > 0:
        if 'Inbox' in subdirectory:
            sub_directories = [account.inbox]
            subdirectory.remove('Inbox')
        else:
            sub_directories = []
        for folder in subdirectory:
            sub_directories.append(account.inbox / folder)
    else:
        sub_directories = [account.inbox]

    #print(sub_directories)

    subd_and_emails = list()
    Emails = list()

    # Fetching all the unread mails filtered based on senders' email addresses from the mentioned directories
    for sub in sub_directories:
        subd_and_emails.append((sub,[item for mail in from_email_ids for item in sub.all().filter(sender=mail).exclude(is_read=True)]))
        #print(subd_and_emails[0][1])

    for sub ,emails in subd_and_emails:
        Emails.extend(emails)
        # Travesing through the list of emails and calling download function to download the attachments
        for item in emails:
            try:
                if item.sender.email_address in [xxxx]:
                    paths = Download( item, download_path, invoice_check=True)
                else:
                    paths = Download(item, download_path)
                for path in paths:
                    email_id_list.append((item.message_id,path,sub))

            except Exception as e:
                logger.error(e)
                #Moving mails to Unprocessed folders
                to_folder = account.root/'Top of Information Store'/'UnprocessedMails'
                item.move(to_folder)

    return account, len(Emails), email_id_list

def send_mails(account, message, excel_file, to_emails, unprocessed_invoices=None):
    """
    Send generated excel report in an email to the recipents
    Parameters:
        account (object): Account object of master mailbox
        excel_file (str): path to the generated excel file report
        to_emails (list): list of recipents' email
    """

    # Creating list of Mailbox objects from the list of recipents' email and sending email from master mailbox
    try:
        to_recipients =[Mailbox(email_address=mail) for mail in to_emails]
        #Create message
        create_message = Message(account=account,
                             folder = account.sent,
                             subject="Report",
                             body=message,
                             to_recipients=to_recipients)
        attachments = []
        if excel_file != None:
            with open(excel_file, 'rb') as f:
                content = f.read()
            index = excel_file.rfind('/')
            filename = excel_file[index+1:]
            attachments.append((filename,content))

            #attach files
            for attachment_name, attachment_content in attachments or []:
                file = FileAttachment(name=attachment_name, content=attachment_content)
                create_message.attach(file)
        create_message.send_and_save()

    except Exception as e:
        logger.error(str(e))

def move_mails(account, ids, subdirectory):
    """
    Move unprocessed emails to unprocessed directory of master mailbox
    Parameters:
        account (object): Account object of master mailbox
        ids (list): list of tuple containing directory object and message ids of unprocessed emails
        subdirectory (list): list of subdirectories from which mails were fetched
    """
    # Creating a dictionary with keys as directory objects and values as the list of unprocessed message ids of mails from that directory
    move_dict = dict()

    for id,sub in ids:
        if sub not in move_dict:
           move_dict[sub] = []
        move_dict[sub].append(id)
    # Moving the unprocessed mails from their respective directories to unprocessed mails in bulk
    to_folder = account.root/'Top of Information Store'/'Unprocessed'
    for target_folder, msg_ids in move_dict.items():
        item_ids = target_folder.filter(message_id__in=msg_ids)
        bulk_items = account.fetch(item_ids)
        account.bulk_move(bulk_items, to_folder)

```

**Comment by Abhi-1504** [comment]
Hi @ecederstrand ,

Kindly help me on this issue. I am.not exactly sure what bos causing this error.

**Comment by ecederstrand** [comment]
`ErrorInternalServerError` is a generic erro and could be caused by a lot of things. Was your server upgraded recently?

Apart from that, it's hard for me to follow your example. You should be able to reduce it to the 10-15 lines of code that are necessary to trigger the error. When you have that, you can enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) and see which exact XML request is triggering this error.

**Comment by Abhi-1504** [comment]
mails.save() in the download() function is the first one to trigger the error and if commented out send_mail() function triggers the error. Since the code was working fine day before yesterday, could it be a possibility that something changed on the EWS server side ?

**Comment by ecederstrand** [comment]
If you didn't change any code, then the only possibility I can see is that that the server changed somehow. You could ask your Exchange administrators about this. Regarding workarounds, downgrading the server (assuming it was upgraded) is one option. Another is to actually debug the issue and find out why the request triggers this error on the server. If you don't ahve access to server logs or assistance from Exchange admins, it's going to involve some trial-and-error and slowly working from something that does work, to something that doesn't.

**Comment by Abhi-1504** [comment]
Hi Erik, 

I tried to access few sample mail and then mark as read using item.is_read=True and then item.save() and the below error was thrown when I tried to use the save() function. Is there any other alternative to perform the operation,,eanwhile I am trying to get hold of the exchange admin.

```Traceback (most recent call last):
  File "Test_Mail.py", line 73, in <module>
    email.save()
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/item.py", line 134, in save
    send_meeting_invitations=send_meeting_invitations
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/item.py", line 217, in _update
    send_meeting_invitations_or_cancellations=send_meeting_invitations)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 450, in bulk_update
    suppress_read_receipts=suppress_read_receipts,
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 445, in <genexpr>
    i if isinstance(i, Exception) else Item.id_from_xml(i)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 307, in _consume_item_service
    for i in service_cls(account=self, chunk_size=chunk_size).call(**kwargs):
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 541, in _pool_requests
    elems = r.get()
  File "/home/appuser/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/appuser/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 520, in <lambda>
    lambda c: self._get_elements(payload=payload_func(c, **kwargs)),
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 66, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 151, in _get_response_xml
    res = self._get_soap_messages(body=body, **parse_opts)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 258, in _get_soap_messages
    cls._raise_soap_errors(fault=fault)  # Will throw SOAPError or custom EWS error
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 294, in _raise_soap_errors
    raise vars(errors)[code](msg)
exchangelib.errors.ErrorInternalServerError: An internal server error occurred. The operation failed.
```

**Comment by ecederstrand** [comment]
You could use some other client to perform the save, if you cvan find one that works.

Otherwise, I'll have to reiterate my suggestions in https://github.com/ecederstrand/exchangelib/issues/793#issuecomment-669731770

**Comment by Abhi-1504** [comment]
@ecederstrand can you please let me know or refer me to resource where I can find out what api request is being sent to when item.save() gets called to save the changes in the mail on Exchange server. Will provide this info to my exchange admin to pinpoint the cause of the error.

**Comment by ecederstrand** [comment]
If you follow https://ecederstrand.github.io/exchangelib/#troubleshooting, you can see the exact request and response XML that is sent between the client and the server.

Regarding `ErrorItemNotFound`, I have no idea myself. Google suggests this explanation: https://stackoverflow.com/questions/59415638/the-specified-object-was-not-found-in-the-store-the-process-failed-to-get-the

**Comment by Abhi-1504** [comment]
Hi @ecederstrand ,

Marking email as read issue got resolved by passing update_fields=['is_read'] in the item.save() function as  item.save(update_fields=['is_read'])  . Now I am facing issue with sending emails and most probably would face the same in moving emails. Seems like the request and payload acceptance of the exchange server has changes somehow. I am getting the Exchange server details currently from exchange admin. Meanwhile checking what other parameters might resolve the issue with other functionality.

**Comment by ecederstrand** [comment]
If limiting save() to certain fields works, then there must be at least one other field that the server is not accepting, throwing an internal server error instead.

You should be able to find the problematic field by calling save() with an update_field containing *all* field names, and then do a binary search to pinpoint the field.

**Comment by Abhi-1504** [comment]
I tried just *send()* function to send mail and I got the below error.

```
Traceback (most recent call last):
  File "Test_Mail.py", line 114, in <module>
    send_mails(account=account, message='Just a Test', excel_file=None, to_emails=['xxxx'], unprocessed_invoices=None)
  File "Test_Mail.py", line 70, in send_mails
    create_message.send()#copy_to_folder=None)#send_meeting_invitations='SendToAllAndSaveCopy')
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/message.py", line 79, in send
    res = self._create(message_disposition=SEND_ONLY, send_meeting_invitations=send_meeting_invitations)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/items/item.py", line 167, in _create
    send_meeting_invitations=send_meeting_invitations)
  File "/home/appuser/anaconda3/lib/python3.7/site-packages/exchangelib/account.py", line 377, in bulk_create
    raise AttributeError("Folder must be None in send-ony mode")
AttributeError: Folder must be None in send-ony mode
```

**Comment by Abhi-1504** [comment]
The root cause of the issue was that the mailbox I was accessing via exchangelib was moved from one city server to another within my organisation, which sounds odd for it to start throwing error for save(), move() and send() functions but moving it back to its original server resolved the issue.

Closing this issue and thank you for all the help @ecederstrand

**Comment by ecederstrand** [comment]
Thanks for the update! This *may* be related to https://github.com/ecederstrand/exchangelib/issues/622
