### ISSUE TITLE
Working with Archived email attachments

### ISSUE THREAD

**Issue by NotInControl** [ecederstrand/exchangelib#794]
Hello, I have been using this library with great success so thank you.

However, I have ran into an issue when trying to download attachments from archived emails where an attachment is never returned instead a blank file with name 'EAS' is returned. Outlook will download the message first, so I am trying to figure out how to do the equivalent using the library.

It appears there is an attachmentID in one of the properties of the EAS file, Is there a method which allows me to get an attachment directly from an attachment ID, or is there a recommended way to get attachments from archived emails?

If more info is needed, i'd be happy to share

**Comment by ecederstrand** [comment]
I don't know what EWS does with attachments on archived messages, but you can call the `GetAttachment` service directly in exchangelib with an attachment ID using something like:

```python
from exchangelib.services import GetAttachment

account = ...
for attachment in GetAttachment(account=account).call(
    items=['my_attachment_id'], include_mime_content=True)
):
    print(attachment)
```

See some usage examples in https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/attachments.py

If you come up with something that works, we could add a helper method to (automatically?) fetch attachments on archived items using information in this "EAS" file. Depending on how you fetch your messages, items will know that they are archived via `some_message.folder.root` that should be an `ArchiveRoot` instance.

**Comment by ecederstrand** [comment]
Hi @NotInControl Did you get anywhere with this issue?

**Comment by NotInControl** [comment]
Hi @ecederstrand , unfortunately not. While your code did work to pull the attachment based on ID, in my particular case EAS file attachment signifies that the email was archived, but EWS itself doesn't store the attachment. In order to retrieve the attachment we will have to use Exchange Active Sync to query our archive servers and retrieve the archived email details along with the attachment. Our internal outlook uses a 3rd party plugin to detect archived emails, download from the active sync server and then returns the email body and attachments. If we wanted to solve this case, we would need to do something similar. For now we have parked that requirement. Which I also believe is out of scope of this repo due to using acvtivesync protocol. 

Appreciate the help, but we can mark this issue closed.

**Comment by ecederstrand** [comment]
Thanks for the detailed description! I hope it can be useful for someone else stumbling into the same issue.
