### ISSUE TITLE
TLS Configuration

### ISSUE THREAD

**Issue by Arka01** [ecederstrand/exchangelib#798]
Hello,

I have explained the error in a StackOverflow post, posting here for further reach.
[Here is the link](https://stackoverflow.com/questions/63520476/exchangelib-tls-configuration)
Would be great if someone could reply in either of the platforms.

**Comment by ecederstrand** [comment]
I just answered there. I think `getaddrinfo failed` is a DNS issue, not a TLS verification issue.

**Comment by Arka01** [comment]
Hi Eric,
Thanks for the reply in StackOverflow, I'll just continue here, for now.

This is the code that I'm running:

```
logging.basicConfig(level=logging.DEBUG)
from exchangelib import Credentials, Account, DELEGATE, Configuration,NTLM, IMPERSONATION, FaultTolerance,EWSDateTime,EWSTimeZone,Message,Q
import logging
import getpass
import datetime 
 
user_name = 'Test.Helpdesk'
new_password = getpass.getpass(prompt='Password: ', stream=None)

try:
    credentials = Credentials(username = user_name, password = new_password)
    config = Configuration(server ='keccas.ad.*******.com', credentials = credentials)
    account = Account(primary_smtp_address = "Test.Helpdesk@*******.com", credentials = credentials, config = config, autodiscover = False)
    print("Success")

except Exception as e:
    print(e)
```

And this is the output:

`DEBUG:exchangelib.protocol:Waiting for _protocol_cache_lock
DEBUG:exchangelib.protocol:Protocol __call__ cache miss. Adding key '('https://keccas.ad.*******.com/EWS/Exchange.asmx', Credentials('Test.Helpdesk', '********'))'
DEBUG:exchangelib.transport:Requesting b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2019"/></s:Header><s:Body><m:ResolveNames ReturnFullContactData="false"><m:UnresolvedEntry>Test.Helpdesk</m:UnresolvedEntry></m:ResolveNames></s:Body></s:Envelope>' from https://keccas.ad.*******.com/EWS/Exchange.asmx
DEBUG:exchangelib.transport:Trying to get service auth type for https://keccas.ad.*******.com/EWS/Exchange.asmx
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): keccas.ad.*******.com:443
DEBUG:exchangelib.util:No retry: no fail-fast policy
WARNING:exchangelib.protocol:Failed to create cached protocol with key ('https://keccas.ad.*******.com/EWS/Exchange.asmx', Credentials('Test.Helpdesk', '********')): HTTPSConnectionPool(host='keccas.ad.*******.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`

`
HTTPSConnectionPool(host='keccas.ad.*******.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
`

I'm honestly clueless on what the problem is, would be great if you could explain what exactly is throwing this error.

**Comment by ecederstrand** [comment]
In that case, a simple POST request to the endpoint would probably also show this error:

```python
import requests
requests.post('https://keccas.ad.*******.com/EWS/Exchange.asmx')
```

You have a TLS handshake error. There can be numerous reasons for that - the most likely being that 1) your Python version does not support the TLS version of the server, 2) you don't have the proper root certificate on your cmachine, or haven't configured python to use it, and 3) the certificate is invalid for the hostname (for example if the URL points to an internal hostname but the certificate is issued for the public hostname).

In any case, this isn't really an issue with exchangelib itself.

**Comment by Arka01** [comment]
Hi Eric,

I will check into all the points that U made in your reply one by one.

Assuming, if Point 1 (Python version) is not the issue, for Point 2, does the code below from the exchangelib doc, help in any way to configure the certificate.

```
from urllib.parse import urlparse
import requests.adapters
from exchangelib.protocol import BaseProtocol

class RootCAAdapter(requests.adapters.HTTPAdapter):
    """An HTTP adapter that uses a custom root CA certificate at a hard coded location"""
    def cert_verify(self, conn, url, verify, cert):
        cert_file = {
            'example.com': '/path/to/example.com.crt',
            'mail.internal': '/path/to/mail.internal.crt',
        }[urlparse(url).hostname]
        super().cert_verify(conn=conn, url=url, verify=cert_file, cert=cert)

# Tell exchangelib to use this adapter class instead of the default
BaseProtocol.HTTP_ADAPTER_CLS = RootCAAdapter
```

If so, can U briefly explain how it works and what exactly should be put in-place of **example.com** and **mail.internal** in the above code.

**Comment by Arka01** [comment]
Also, let me share a few code snippets that I have been running.
I do not have networking knowledge, hence these code snippets are mostly based on Google Searches.

Running this script ;

```
import requests
print(requests.get('https://www.howsmyssl.com/a/check', verify=True).json()['tls_version'])
import sys
sys.version
```

Gave me this output:

```
TLS 1.3
'3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]'
```

Running this:

```
import ssl
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.poolmanager import PoolManager

class SSLAdapter(HTTPAdapter):
    '''An HTTPS Transport Adapter that uses an arbitrary SSL version.'''
    def __init__(self, ssl_version=None, **kwargs):
        self.ssl_version = ssl_version

        super(SSLAdapter, self).__init__(**kwargs)

    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = PoolManager(num_pools=connections,
                                       maxsize=maxsize,
                                       block=block,
                                       ssl_version=self.ssl_version)

ssl_versions = {
    #ssl.PROTOCOL_SSLv2: 'SSLv2', # Removed in 3.6
    #ssl.PROTOCOL_SSLv3: 'SSLv3',
    ssl.PROTOCOL_SSLv23: 'SSLv23',
    ssl.PROTOCOL_TLSv1: 'TLSv1',
    ssl.PROTOCOL_TLSv1_1: 'TLSv1_1',
    ssl.PROTOCOL_TLSv1_2: 'TLSv1_2',
    #ssl.PROTOCOL_TLS, # New in 3.6,
    None: 'None'
}

urls = [
    'https://webmail.leedsworld.com/',
    'https://www.google.com',
    'https://www.outlook.com'
]

for url in urls:
    print(url)
    for k,v in ssl_versions.items():
        s = requests.Session()
        s.mount('https://', SSLAdapter(ssl_version=k))
        try:
            s.get(url)
            print ('\t{}\tSuccess'.format(v))
        except:
            print ('\t{}\tFail'.format(v))
```

Gave this:

```
https://webmail.leedsworld.com/
	SSLv23	Fail
	TLSv1	Fail
	TLSv1_1	Fail
	TLSv1_2	Fail
	None	Fail
https://www.google.com
	SSLv23	Success
	TLSv1	Success
	TLSv1_1	Success
	TLSv1_2	Success
	None	Success
https://www.outlook.com
	SSLv23	Success
	TLSv1	Success
	TLSv1_1	Success
	TLSv1_2	Success
	None	Success
```

I have a fixed requirement that I need to use TLS 1.2
But as U can see above, it seems both 1.2 & 1.3 is working in my Python version.

**Comment by ecederstrand** [comment]
The `RootCAAdapter` example code looks at the URL of the request, extracts the hostname of the URL, and injects the path to a local certificate store if the hostname matches one of the hostnames in the dict. In your case, that would be `keccas.ad.*******.com`.

If the server only supports TLS 1.2, and your client supports both 1.2 and 1.3, then the TLS protocol should take care of auto-negotiating a protocol version that both sides support. If not, you can write an adapter that forces the TLS version. See https://requests.readthedocs.io/en/master/user/advanced/#example-specific-ssl-version

**Comment by Arka01** [comment]
Hi Eric,

Will check up all of this and get back to U.

**Comment by Arka01** [comment]
Hi Eric,

It finally worked using the RootCAAdapter Class.
Just placed the host as U suggested and it ran without errors.

Thanks a lot !!!

[This issue](https://github.com/ecederstrand/exchangelib/issues/795) can be closed too, since they were related.
