### ISSUE TITLE
What's the best way to get the CalendarItem object of the organizer?

### ISSUE THREAD

**Issue by andrkhr** [ecederstrand/exchangelib#799]
Hello! 

We are using a library to batch process meetings. 
We receive all the meetings (CalendarItems) of a particular negotiation room and in a cycle, for each CalendarItem, we receive the organizer's CalendarItem, since it contains more complete information that may not be present in the negotiation meeting. This works, it feels like it is not very optimal to make a separate request for each meeting. 
Perhaps there is a better way to get organizers meetings (CalendarItems), in addition to negotiation meetings? Something like select_related in django orm.

Thank you!

**Comment by ecederstrand** [comment]
EWS doesn't allow for SQL joins, unfortunately, so something like `select_related()` would not work.

If you collect the item IDs for the meetings you need to fetch, then you can fetch these items in bulk using `Account.fetch()`. In theory, it should be possible to do this for multiple accounts in one go, but if you are using impersonation to access the organiser account, then you will probably have to do one bulk-fetch per account.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional issues with this.
