### ISSUE TITLE
How do i get all meeting rooms of an organization?

### ISSUE THREAD

**Issue by wizravi** [ecederstrand/exchangelib#8]
small piece of code would help.

**Comment by ecederstrand** [comment]
That would require support for the [GetRooms](https://msdn.microsoft.com/en-us/library/office/dd899415(v=exchg.150).aspx) or [GetRoomLists](https://msdn.microsoft.com/en-us/library/office/dd899416(v=exchg.150).aspx#sectionSection1) services and the [Room](https://msdn.microsoft.com/en-us/library/office/dd899479(v=exchg.150).aspx) element, if I understand you correctly. There is no such support yet, but patches are welcome :-)

**Comment by wizravi** [comment]
yes, looked at the existing code, but GetRooms doesn't fit into the current model of retrieving a particular user's information. Informations like GetRooms, Groups are global information to an organization, Any ideas on how we can approach this.

**Comment by ecederstrand** [comment]
`services.GetServerTimeZones` is an example of a service that is not account-centric. You could use that as a starting point.

**Comment by ecederstrand** [comment]
Can you try 1823fa1222b1aae33d7816d18e9c6608d2fe5826 ? I implemented the two services but don't have access to create rooms or room lists on my test server so I can only test empty responses.

**Comment by ecederstrand** [comment]
Ping?

**Comment by wizravi** [comment]
Hi Eric, 
I tried with your patch, it did work. However GetRoomList and GetRooms are not serving my purpose. 
GetRoomList basically means Distribution Group consisting of set of Room email IDs which need to be created by user. and GetRooms basically returns list of rooms in a given GetRoomList.
But What I need to set of Rooms(Name,location,capacity etc.) in a given organization either through EWS means or through REST APIs.
Please let me know how to accomplish this.
Thanks
Ravi

**Comment by ecederstrand** [comment]
Ok. I have no idea if that is possible through EWS. If not, it's probably out of scope of this package.

If you do find documentation or examples to accomplish this using EWS, then please open a new issue with the specifics.

**Comment by wizravi** [comment]
So, what I have noticed is it is possible to get these information form Active Directory using LDAP. Do you have any idea if Active Directory can be accessed using EWS?

**Comment by ecederstrand** [comment]
Exchange and ActiveDirectory are entirely different Microsoft products. EWS is an Exchange-only webservice.

I see there are a number of packages related to ActiveDirectory on PyPI. You may have better luck with those.
