### ISSUE TITLE
reply message with mime_content

### ISSUE THREAD

**Issue by aschrempf** [ecederstrand/exchangelib#800]
Dear Erik,

I'm using your lib for an email client written for macOS (swift - PyObjC - python) and I highly appreciate your work. Actually I have implemented signing and decrypting/encrypting emails. This requires to directly provide the ``mime_content`` for the message which works well. However, when I want to create a reply message, which should be signed and/or encrypted the only way is to create a new message. Hence this new message does not show up in the conversation thread. I tried to set the ``conversation_index`` in the new message, but this is not working.

```python
conversationID = refMessage.conversation_index
...
msg = Message(
   account=self.account,
   subject=subject,
   mime_content=mimeContent,
   to_recipients=recList,
   cc_recipients=recListCC,
   conversation_index=conversationID
)
```

Is there another way to create a reply which accepts the ``mime_content`` field and is thread-aware?

Thanks in advance!

**Comment by ecederstrand** [comment]
I'm glad you found exchangelib useful!

The `conversation_index` field is read-only in exchangelib. This is tracked in https://github.com/ecederstrand/exchangelib/issues/642

I believe it's possible to make it read-write but I haven't done any testing yet.

**Comment by aschrempf** [comment]
Thanks for the fast reply!

It would be nice, if you will consider to make ``conversation_index`` read-write. Additionally the same for ``conversation_id``would be beneficial.

Actually I found out, that appending the ``message_id``to the ``references`` string allows Outlook to identify the message as a part of the corresponding thread:

```python
messageReferences = refMessage.references " " + refMessage.message_id
....
msg = Message(
   account=self.account,
   subject=subject,
   mime_content=mimeContent,
   to_recipients=recList,
   cc_recipients=recListCC,
   references=messageReferences
)
```

Thank you!

**Comment by ecederstrand** [comment]
Great. Closing this issue since the conversation fields are coveres by the mentioned issue.
