### ISSUE TITLE
Sending or Retrieving mail fails

### ISSUE THREAD

**Issue by qblone** [ecederstrand/exchangelib#802]
I have tried several options with configs and read through open and closed issues but could not find answer. Ill be grateful if someone can guide me. 
I have also turned on debugging. 

```

credentials = Credentials(username='DASTUD\MYID', password='MY_PASSWORD') 
config = Configuration(server='webmail.myuni.nl', credentials=credentials)

 a = Account(primary_smtp_address='myaccount@myuni.nl', credentials=credentials,config=config,
                     autodiscover=True,access_type=DELEGATE)


 for item in a.inbox.all().order_by('-datetime_received')[:100]:
            print(item.subject, item.body, item.attachments)

```

The code does not throw any error unless I am trying the retrieve messages or send email. I get following output. 

`Request data: <?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
  <s:Header>
    <t:RequestServerVersion Version="Exchange2016"/>
    <t:TimeZoneContext>
      <t:TimeZoneDefinition Id="UTC"/>
    </t:TimeZoneContext>
  </s:Header>
  <s:Body>
    <m:GetFolder>
      <m:FolderShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="folder:FolderId"/>
          <t:FieldURI FieldURI="folder:ChildFolderCount"/>
          <t:FieldURI FieldURI="folder:EffectiveRights"/>
          <t:FieldURI FieldURI="folder:FolderClass"/>
          <t:FieldURI FieldURI="folder:DisplayName"/>
          <t:FieldURI FieldURI="folder:ParentFolderId"/>
          <t:FieldURI FieldURI="folder:TotalCount"/>
          <t:FieldURI FieldURI="folder:UnreadCount"/>
        </t:AdditionalProperties>
      </m:FolderShape>
      <m:FolderIds>
        <t:DistinguishedFolderId Id="root">
          <t:Mailbox>
            <t:EmailAddress>'myaccount@myuni.nl</t:EmailAddress>
            <t:RoutingType>SMTP</t:RoutingType>
            <t:MailboxType>Mailbox</t:MailboxType>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:FolderIds>
    </m:GetFolder>
  </s:Body>
</s:Envelope>

Response data: b''

DEBUG:exchangelib.util:No retry: wrong status code 403
DEBUG:exchangelib.protocol:Server webmail.myuni.nl: Retiring session 26476
DEBUG:exchangelib.protocol:Server webmail.myuni.nl: Created session 26774
DEBUG:exchangelib.protocol:Server webmail.myuni.nl: Releasing session 26774
WARNING:exchangelib.services.common:EWS https://webmail.myuni.nl/ews/exchange.asmx, account 'myaccount@myuni.nl: Exception in _get_elements: Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'inbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 118, in _get_elements
    for i in self._response_generator(payload=payload):
  File "/opt/miniconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 109, in _response_generator
    response = self._get_response_xml(payload=payload)
  File "/opt/miniconda3/lib/python3.7/site-packages/exchangelib/services/common.py", line 185, in _get_response_xml
    stream=self.streaming,
  File "/opt/miniconda3/lib/python3.7/site-packages/exchangelib/util.py", line 814, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "/opt/miniconda3/lib/python3.7/site-packages/exchangelib/util.py", line 895, in _raise_response_errors
    raise TransportError(str('Unknown failure\n') + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 10
Timeout: 120
Session: 26476
Thread: 140116309710656
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f6f589b4650>
URL: https://webmail.myuni.nl/ews/exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f6f589b4f90>
Allow redirects: False
Streaming: False
Response time: 0.10520533286035061
Status code: 403`

The same error is thrown if I try ```print(a.root.walk())```

Thank you in advance for any pointers or help.

**Comment by ecederstrand** [comment]
[HTTP 403](https://en.wikipedia.org/wiki/HTTP_403) means that the request is forbidden. Are you sure that there is in fact an EWS service located at https://webmail.myuni.nl/ews/exchange.asmx?

**Comment by qblone** [comment]
Hi Erik 
Thank you so much for a quick reply. If I try to access ( https://webmail.myuni.nl/ews/exchange.asmx), I am prompted for username and password. After authentication it shows following output 

To test this service, you will need to create a client and use it to call the service. You can do this using the svcutil.exe tool from the command line with the following syntax:
C#

class Test
{
    static void Main()
    {
        HelloClient client = new HelloClient();

        // Use the 'client' variable to call operations on the service.

        // Always close the client.
        client.Close();
    }
}



svcutil.exe https://srv221.myuni.net:444/EWS/Services.wsdl
This will generate a configuration file and a code file that contains the client class. Add the two files to your client application and use the generated client class to call the Service. For example:

C#

**Comment by qblone** [comment]
In the logs after authentication, I do find my Active Directory OU object. It also shows various types of protocols: 

<Protocol>
        <Type>WEB</Type>
        <Internal>
          <OWAUrl AuthenticationMethod="Basic, Fba">https://webmail.myuni.nl/owa/</OWAUrl>
          <Protocol>
            <Type>EXCH</Type>
            <ASUrl>https://webmail.myuni.nl/ews/exchange.asmx</ASUrl>
          </Protocol>
        </Internal>
        <External>
          <OWAUrl AuthenticationMethod="Fba">https://webmail.myuni.nl/owa/</OWAUrl>
          <Protocol>
            <Type>EXPR</Type>
            <ASUrl>https://webmail.myuni.nl/ews/exchange.asmx</ASUrl>
          </Protocol>
        </External>
      </Protocol>

Can system administrators restrict email objects for read or write ?

**Comment by ecederstrand** [comment]
Oh, I didn't see that you were using autodiscovery. When you do that, you can skip the `server` argument to `Configuration()` (and the `config` argument to `Account`).

It seems the autodiscover is missing an `EwsUrl` element in the `Protocol` element. That's what we use to find the EWS endpoint. See more at https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/protocol-pox

**Comment by qblone** [comment]
Thanks Erik for your kind reply. I think then misconfiguration is at my university exchange server. The exchange server is also a bit unstable since yesterday, so they might be patching/updating. 

Ill try latter and will report back if anything changes. 

Thank you again for developing such a great tool and providing support. I am really grateful.

**Comment by qblone** [comment]
Hi Erik, I think it was our exchange server issue. It now finds root but still throws error if i try to access account.inbox or account.sent object with 

```
  File "/opt/miniconda3/lib/python3.7/site-packages/cached_property.py", line 69, in __get__
    return obj_dict[name]
KeyError: 'inbox'
```

account.root.walk() function returns <exchangelib.folders.collections.FolderCollection object at 0x7f5f897e1790>

and 

account.root.tree() returns root 


Is there anyway to know the folder structure for Inbox and Sent, since I need to send automated emails using this account.

**Comment by ecederstrand** [comment]
The `KeyError` is misleading - it's part of how `cached_property` works. There must be something else later on in the stack trace that tells you what the actual error is.

`account.root.walk()` is a generator. You can't print it directly, but you can iterator over it and print its elements.

**Comment by qblone** [comment]
Hi Eric, 
I just retried and it worked. I am now certain it was our email exchange issue rather than the library. I would like to thank you for building such an amazing library and being so helpful. Thank you so much for your prompt replies. I am really grateful.
