### ISSUE TITLE
Question: Logging the output into a file

### ISSUE THREAD

**Issue by blueteamzone** [ecederstrand/exchangelib#804]
Hey I'm trying to create a log file.

```
import logging
from exchangelib.util import PrettyXmlHandler
logging.basicConfig(level=logging.DEBUG, handlers=[PrettyXmlHandler()])
```

However when I try to add a filename to logging.basicConfig it throughs the following error:
`logging.basicConfig(filename='exchange.log',level=logging.DEBUG, handlers=[PrettyXmlHandler()])`

### 'stream' or 'filename' should not be specified together with 'handlers'

How can I fix this issue? Is this something to fix from your side? 

Thanks

**Comment by mralecthomas** [comment]
If you are wanting to output logging info to a file, then you will need to remove the handler param:

`logging.basicConfig(filename='exchange.log',level=logging.DEBUG)`

**Comment by ecederstrand** [comment]
`PrettyXmlHandler` is a subclass of `StreamHandler`. It doesn't handle logging to files.

If you need that prettifying functionality of `PrettyXmlHandler`, you can either create your own `FileHandler` class that inherits functionality from `PrettyXmlHandler`, or redirect stdout to a file using functionality in your shell/terminal.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional issues with this.
