### ISSUE TITLE
Package not compatible with next version of tzlocal

### ISSUE THREAD

**Issue by pganssle** [ecederstrand/exchangelib#805]
The next version of `tzlocal` will [switch from using `pytz` zones to `zoneinfo`](https://github.com/regebro/tzlocal/pull/92) (which is generally a good idea), which will break this package, since `zoneinfo` zones don't have the same interface as `pytz` zones.

You should probably pin the version of `tzlocal` ASAP, and/or add in some logic to detect `zoneinfo` zones and convert them to whatever you want.

In the longer term, you should probably also migrate away from `pytz` and on to `zoneinfo`. I have a [`pytz-deprecation-shim`](https://pytz-deprecation-shim.readthedocs.io/en/latest/) module that should help ease the pain (though it is not 100% backwards compatible - in the [migration guide](https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html) you'll find that the [semantics of datetime addition are slightly different](https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html#handling-datetime-arithmetic-normalizing-datetimes)).

**Comment by ecederstrand** [comment]
Thanks for the heads-up!

This issue is related to #717. I think we should just migrate from `pytz` to `zoneinfo`.
