### ISSUE TITLE
Sort error on querying calendar items

### ISSUE THREAD

**Issue by gtdavidv** [ecederstrand/exchangelib#808]
I've got a new error cropping up when querying calendar items.

Error:
```
Error: Error on line 59 Traceback (most recent call last):
  File "./<file>", line 59, in <function>
    <function>()
  File "<file>", line 703, in <function>
    for eachMeeting in calendarList:
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/queryset.py", line 287, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
  File "/usr/local/lib/python3.6/dist-packages/exchangelib/queryset.py", line 256, in _query
    items = sorted(items, key=lambda i: _get_value_or_default(i, f), reverse=f.reverse)
TypeError: can't compare EWSDateTime to EWSDate
```

Query:
```
calendarList = account.calendar.view(start=startDateTime, end=endDateTime).order_by('-start')[:25]
for eachMeeting in calendarList:
    ...
```

startDateTime and endDateTime are valid EWSDateTime objects

Using exchangelib v3.2.1

The Exchange user is on Outlook365

Happy to provide more info if it can be helpful

**Comment by ecederstrand** [comment]
Thanks for reporting!

I think this happens when the view contains items that are a mix of normal and all-day events. For all-day events we change the start and end dates to `EWSDate` values instead of `EWSDateTime`, but that breaks sorting when sorting is done client-side because these values can't be compared.

**Comment by gtdavidv** [comment]
Strange, this is the same code we've been running for dozens of users for months. I'd be pretty surprised if we hadn't run into time events + full day events in the same window before.

Anyway, I messed around a bit and put together something that looks to be working. PR here: https://github.com/ecederstrand/exchangelib/pull/809

You're welcome to decline/edit if I messed anything up.

**Comment by ecederstrand** [comment]
Let's start by finding a way to reproduce, so we can add a test case that exercises this code path.

**Comment by ecederstrand** [comment]
I can reproduce this when client-side sorting by date on calendar items where the first item encountered is a normal item and one of the following is an all-day item:

```python
now = UTC_NOW()
start, end = now, now + timedelta(hours=1)
normal_item = CalendarItem(folder=a.calendar, subject='Normal item', start=start-timedelta(days=1), end=end-timedelta(days=1)).save()
all_day_item = CalendarItem(folder=a.calendar, subject='All-day item', start=start.date(), end=end.date(), is_all_day=True).save()

for item in a.calendar.view(start=start-timedelta(days=1), end=end + timedelta(days=1)).order_by('-start'):
    print(item.subject, item.start, item.end)
```

**Comment by ecederstrand** [comment]
Thanks for the PR, by the way!

I have created a test case for this and will be fixing it slightly different than your PR. We should use the actual timezone of the start or end field to do the translation from date to datetime, to avoid a large skew for timezones that are far away from Greenwich. Also, we want to push the start date back to the midnight before, and end dates to the midnight after.
