### ISSUE TITLE
Timeout when login doesn't work

### ISSUE THREAD

**Issue by warddebecker** [ecederstrand/exchangelib#81]
Hello again,

I was wondering if it is possible to set some sort of timeout on the login.
Since currently when credentials are incorrect, this code gets stuck on the svc_account line, and seemingly  stays stuck there forever. 
I want it to throw an error if it wasn't able to connect in N seconds, is this possible?

```python
creds = Credentials(username='account@domain', password='supersecret')

print('Connecting to EWS')
svc_account = Account(primary_smtp_address='account@domain',credentials=creds, autodiscover=True)
print('Connected!')
```

Thanks in advance

**Comment by ecederstrand** [comment]
There's an optional `is_service_account` parameter for `Credentials` for this purpose. That should let authentication fail immediately if connection failed.

**Comment by warddebecker** [comment]
sorry for the late response, I haven't had alot of time.
I only briefly tested to add the parameter, and set it both true & false, and it seemed to stay stuck at the login if I use invalid credentials.
Do you have a small example how to use it?

**Comment by ecederstrand** [comment]
I just tested this. If I do this:

```python
c = Credentials(username, 'thisiswrong', is_service_account=True)
a = Account(primary_smtp_address=c.username, credentials=c, access_type=DELEGATE, autodiscover=True)
```

then it sits and retries the login for at least an hour, which is expected. If I do this, then it fails after around 30 seconds when all autodiscover attempts have failed:

```python
c = Credentials(username, 'thisiswrong', is_service_account=False)
a = Account(primary_smtp_address=c.username, credentials=c, access_type=DELEGATE, autodiscover=True)
```

**Comment by warddebecker** [comment]
Oh yes, I didn't wait long enough it seems, but it just throws a bunch of errors when it fails, is there a way to make it execute some code when it fails instead of throwing all those errors and then exiting?

**Comment by ecederstrand** [comment]
Just catch `exchangelib.errors.AutoDiscoverFailed` in your code, if you're using autodiscover, and do whatever you want in the `except` clause.

**Comment by warddebecker** [comment]
Thanks, got it working :)
thanks for helping me with what are probably some newbie questions.

**Comment by ecederstrand** [comment]
No problem. Glad you got it working!
