### ISSUE TITLE
Canceled meetings

### ISSUE THREAD

**Issue by pkonnov** [ecederstrand/exchangelib#816]
How from the letter with the type of meeting cancellation you can understand that all the following appointments or appointments from the current series have been canceled?
![Screenshot (46)](https://user-images.githubusercontent.com/16544499/95365451-32559500-08e3-11eb-98e6-b6cded79604d.png)

**Comment by ecederstrand** [comment]
When you have a recurring master calendar item, the `deleted_occurrences` field contains the occurrences in the recurrence that have been deleted.

**Comment by pkonnov** [comment]
I created a recurring meeting. Then he deleted (All events in the series). But in the calendar item I get a `deleted_occurrences` field equal to `None`
![Screenshot from 2020-10-08 15-39-56](https://user-images.githubusercontent.com/16544499/95453967-d3445e80-097c-11eb-90ab-a0d5183fe90f.png)

**Comment by ecederstrand** [comment]
Then you are probably not holding the master calendar item. You need to look in your calendar - I don't think it's available via `associated_calendar_item_id`. Master items have `calendar_item.is_recurring = True`. When you have an item that is part of a recurrence, you can get to the master via `calendar_item.recurring_master().refresh()`.

**Comment by pkonnov** [comment]
`exchangelib.errors.ErrorCalendarCannotUseIdForOccurrenceId: The Id specified does not represent an occurrence`
`calendar_item ` is element with `is_recurring=True`
![Screenshot from 2020-10-08 16-50-37](https://user-images.githubusercontent.com/16544499/95462093-1952ef80-0988-11eb-8df8-eff80d83b76c.png)

**Comment by ecederstrand** [comment]
Ok, so it's already a master item. You can't get the master item of a master item.

I don't get why you are fetching the master item out of an email, though. It should be available in your calendar folder.

It's possible that they are in the `modified_occurrences` instead. It's also possible that the recurrence itself is changed if you cancel all occurrences, so there are no longer any occurrences on the master item. You can check the value of the fields `first_occurrence`, `last_occurrence` and `recurrence`.

**Comment by pkonnov** [comment]
So, you can understand that the meeting was canceled from the type field. If `type = Exсeption` then canceled one day from the meeting series. If `type = RecurringMaster` then all subsequent appointments are canceled. The cancellation start date can be taken from the calendar item. Something like this

**Comment by ecederstrand** [comment]
I'm not sure if there was a question hidden there. Did you get your issue sorted out?

**Comment by pkonnov** [comment]
I solved my issue with different way

**Comment by ecederstrand** [comment]
Great to hear! Closing this issue, then.
