### ISSUE TITLE
bounced emails

### ISSUE THREAD

**Issue by qblone** [ecederstrand/exchangelib#818]
I have browsed the documentation but couldnt find any function which could classify why the email bounced like email box full, or mail box non existent. 

I will be grateful if someone has any thoughts or ideas on it. Thank you so much in advance.

**Comment by qblone** [comment]
Hi Erik, 

Thank you so much for your kind reply. I was asking about the external email addresses. I have received the reports with some explanation in the body of the email. I was wondering if there is something to classify them. 

If it is outside the scope of the library, i fully understand and can just parse the body of the received report to classify them manually.

**Comment by ecederstrand** [comment]
Yeah, parsing the content of emails is outside the scope of exchangelib. There is a large number of different email servers that all send different reports, and are not guaranteed to send any at all.

**Comment by ecederstrand** [comment]
Closing, but feel free to reopen if you have additional questions related to this.
