### ISSUE TITLE
Read Master Category List?

### ISSUE THREAD

**Issue by mpwoodward** [ecederstrand/exchangelib#819]
First and foremost, THANK YOU for this library. It's a huge time-saver.

Apologies if I'm missing how to do this, but is there a way to access the Master Category List? I've come across examples of how to get at this from C# and PHP but I'm not seeing how to do it with this library. Thanks.

**Comment by ecederstrand** [comment]
I had no idea what a Master Category List is, so I had to google. It seems this functionality is implemented by the *UserConfiguration services, e.g. https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getuserconfiguration-operation Thos are not yet implemented in exchangelib, but it looks fairly easy to do so.

**Comment by mpwoodward** [comment]
Thanks -- that would be super helpful for a project I'm working on right now. I'll poke around and do a PR if I come up with something, but you may beat me to it. :-) I appreciate the response and additional info.

**Comment by mpwoodward** [comment]
Thanks so much for implementing this! I'll kick the tires on it as soon as I get a chance. Really appreciate it!

**Comment by ecederstrand** [comment]
You're welcome :-) I pushed a series to commits ending in https://github.com/ecederstrand/exchangelib/commit/2bd108da7a649d544090fe24bf6a78d73bb41870, to complete support for all key-value types that EWS supports.
