### ISSUE TITLE
[oauth help] usage instructions with company-managed SSO portal

### ISSUE THREAD

**Issue by charger89** [ecederstrand/exchangelib#826]
Hi, long time user & fan!
Recently my company switched over to company's own SSO login portal, so 365 now is authenticated with company's group AD accounts. Is there any guidance out there how to approach this?

I take it should be something in the lines of

    from exchangelib import Configuration, OAuth2Credentials, OAuth2AuthorizationCodeCredentials, \
        Identity, OAUTH2
    from oauthlib.oauth2 import OAuth2Token

    MAIL='my.mail@example.com'
    CREDENTIALS = OAuth2Credentials(client_id='client-id', client_secret='TODO_MISSING', \
                        tenant_id='tenant-id', identity=Identity(primary_smtp_address=MAIL))
    CC = Configuration(server='outlook.office365.com', credentials=CREDENTIALS, auth_type=OAUTH2)

    ACCOUNT = Account(primary_smtp_address=MAIL, config=CC, autodiscover=False, access_type=DELEGATE)

Note I've extracted the `clientId` & `tenantId` from the headers of browser client, but no idea how to access the secret. I'm guessing the AD password is not it.

**Comment by ecederstrand** [comment]
I don't have any experience with OAuth myself. I think you need to obtain the OAuth secret with your Exchange admins.

**Comment by ecederstrand** [comment]
@charger89 Did you get anywhere with this?

**Comment by ecederstrand** [comment]
Closing. Feel free to re-open if you need more help.
