### ISSUE TITLE
Configuring resolver params 

### ISSUE THREAD

**Issue by xx113355** [ecederstrand/exchangelib#827]
I have a problem using exchangelib on Android (via vivy). Problem in dnspython package, there is no file '/etc/resolv.conf' on Android system. I open issue https://github.com/rthalley/dnspython/issues/603, one of solution - configure resolver manually (like this  dns.resolver.Resolver(configure=False)). You create resolver in discovery.py in function def resolver(self). Maybe you can add some option to configuring?

**Comment by ecederstrand** [comment]
Would the suggestion to [install an extra package](https://github.com/termux/termux-packages/issues/5800) to get `/etc/resolv.conf` on Android work for you?

**Comment by ecederstrand** [comment]
Nevermind, I committed a patch that should allow you to configure kwargs for Resolver.
