### ISSUE TITLE
Help with no_proxy support

### ISSUE THREAD

**Issue by dadokkio** [ecederstrand/exchangelib#828]
I was able to add proxy support following documentation but I'm not able to add no_proxy variable.
At the moment my code is:

```python
class ProxyAdapter(requests.adapters.HTTPAdapter):
    PROXIES = None

    def send(self, *args, **kwargs):
        kwargs["proxies"] = self.PROXIES
        return super(ProxyAdapter, self).send(*args, **kwargs)


proxies = {
    "https": "https:/xx",
    "http": "http:/xx",
    "no_proxy": "xx.xx.xx.xx",
}

BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
ProxyAdapter.PROXIES = proxies
BaseProtocol.HTTP_ADAPTER_CLS = ProxyAdapter
```
I've seen that there is an [issue opened in requests](https://github.com/psf/requests/issues/4600), not sure if related.
Has been someone able to set no_proxy in some way?

**Comment by ecederstrand** [comment]
Without knowing how this works in requests, can’t you just have the `send()` method look at the address and there decide whether to pass on the `proxies` kwarg or not?

**Comment by ecederstrand** [comment]
Anyway, I think the discussion on this should be done in the `requests` issue tracker, since this is not an exchangelib issue.

**Comment by dadokkio** [comment]
Sorry, my intention was just to ask if someone using exchangelib had the same issue and found a workaround. 
Your idea is a good starting point but is very difficult to make it "general purpose" for all the possibility way you can write the no_proxy value (ip, domain, subnets .. mixed and wildcarded)
In any case the code proposed in the linked issue seems to be working. 
I'm now able to connect and I'm testing if everything else works as expected.
