### ISSUE TITLE
Processing 2500+ emails through exchangelib

### ISSUE THREAD

**Issue by Bibhu280** [ecederstrand/exchangelib#829]
Hi I want to process almost 2500+ emails through exchangelib and download some attachments. I am executing  emails batch wise(50,100) also, but every time I am getting error 

**ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host**

I am not understanding is this error from exchangelib side ya the server side where my mail id is hosting.
Please help if you have any solution how to process 2500+ emails and download attachments at a time.

**Comment by Bibhu280** [comment]
ConnectionResetError                      Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\response.py in _error_catcher(self)
    424             try:
--> 425                 yield
    426 
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\response.py in read_chunked(self, amt, decode_content)
    751             while True:
--> 752                 self._update_chunk_length()
    753                 if self.chunk_left == 0:
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\response.py in _update_chunk_length(self)
    681             return
--> 682         line = self._fp.fp.readline()
    683         line = line.split(b";", 1)[0]
C:\ProgramData\Anaconda3\lib\socket.py in readinto(self, b)
    588             try:
--> 589                 return self._sock.recv_into(b)
    590             except timeout:
C:\ProgramData\Anaconda3\lib\ssl.py in recv_into(self, buffer, nbytes, flags)
   1070                   self.__class__)
-> 1071             return self.read(nbytes, buffer)
   1072         else:
C:\ProgramData\Anaconda3\lib\ssl.py in read(self, len, buffer)
    928             if buffer is not None:
--> 929                 return self._sslobj.read(len, buffer)
    930             else:
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
During handling of the above exception, another exception occurred:
ProtocolError                             Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in generate()
    750                 try:
--> 751                     for chunk in self.raw.stream(chunk_size, decode_content=True):
    752                         yield chunk
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\response.py in stream(self, amt, decode_content)
    559         if self.chunked and self.supports_chunked_reads():
--> 560             for line in self.read_chunked(amt, decode_content=decode_content):
    561                 yield line
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\response.py in read_chunked(self, amt, decode_content)
    780             if self._original_response:
--> 781                 self._original_response.close()
    782 
C:\ProgramData\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\response.py in _error_catcher(self)
    442                 # This includes IncompleteRead.
--> 443                 raise ProtocolError("Connection broken: %r" % e, e)
    444 
ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
During handling of the above exception, another exception occurred:
ChunkedEncodingError                      Traceback (most recent call last)
<ipython-input-30-c039d745ab2b> in <module>
      3     print("Processing batch:: " , _i)
      4     counter = 0
----> 5     for item in mails[_i:_i+50]:
      6         counter += 1
      7         print(counter)

**Comment by ecederstrand** [comment]
First of all, if you are getting connection errors, you can configure [fault tolerance](https://ecederstrand.github.io/exchangelib/#fault-tolerance) to let your script continue even though the server throws errors.

You didn't post the code that shows the error, but the batch processing in `for item in mails[_i:_i+50]` is redundant. You may as well do `for item in mails:` because exchangelib already fetches items in batch ("pages"). You can [change the paging settings](https://ecederstrand.github.io/exchangelib/#paging) if you want.

Finally, you might be able to optimize your query a bit if you fetch only the fields you need with the `.only('attachments', ...)` method. Since you are fetching attachments you might not gain a lot, but it's worth a try.

**Comment by Bibhu280** [comment]
Hi
I need to read every month some 2500+ mail and download attachments from that based on, if that attachment name is available in some excel file. Due to large no of unread mail I am getting ConnectionResetError  server error .Any solution to downloads all attachments easily with less time.

I am only passing one time connection need to pass more no of times inside scripts?

local_path=" c:\\user\\file"
for item in account.inbox.all().order_by('-datetime_received').exclude(is_read=True):
    for attachment in item.attachments:
        match=re.findall(r'DS\d+', attachment.name)
        if refer['Names'].isin(match).any():
            #print(df['Reference'].isin(match).any())
            if isinstance(attachment, FileAttachment):
                local_path = os.path.join(attachment.name)
                with open(local_path, 'wb') as f:
                    f.write(attachment.content)
                print('Saved attachment to', local_path)

Please help, thanks for response

**Comment by ecederstrand** [comment]
Hi @Bibhu280 Did you try configuring fault tolerance as I suggested? Also, your example code doesn't contain the `only()` QuerySet method that I suggested.

**Comment by Bibhu280** [comment]
Yes I tried  fault tolerance, still server issue is their, but can you please tell how to use only() method to download all attachments from unread email.

**Comment by ecederstrand** [comment]
Can you post the full stack trace you get when fault tolerance is enabled?

The `.only()` method is used like this:

```python
for item in account.inbox.all().order_by('-datetime_received').exclude(is_read=True).only('attachments'):
   ...
```

**Comment by Bibhu280** [comment]
Hi Now I am running with vpn so no server error, but when I am downloading it is not downloading all files some are lefting.
.only('attachments') method I am not using because all emails contain attachments.




try:
    ## credential details 
    BaseProtocol.HTTP_ADAPTER_CLS = NoVerifyHTTPAdapter
    cred = Credentials(username=username,password=pwd)
    conf = 
     Configuration(server='webmail.wipro.com',retry_policy=FaultTolerance(max_wait=3600),credentials=cred,auth_type=NTLM)
    account = Account(username, credentials=cred,config=conf,autodiscover=False,access_type=DELEGATE)
except Exception as e:
    print(str(e))
    print('Unknown failure')
    print("Transport Error:Network connectivity issue Please check internet or mail server")



local_path="..........."
for item in account.inbox.all().order_by('-datetime_received').exclude(is_read=True):
    account = Account('G117498@wipro.com', credentials=cred,config=conf,access_type=DELEGATE)
    for attachment in item.attachments:
        match=re.findall(r'DS\d+', attachment.name)
        if itc['Reference'].isin(match).any():
            item.is_read=True
            item.save()
            if isinstance(attachment, FileAttachment):
                local_path = os.path.join(attachment.name)
                with open(local_path, 'wb') as f:
                    f.write(attachment.content)
                print('Saved attachment to', local_path)

**Comment by ecederstrand** [comment]
`.only('attachments')` doesn't fetch all emails emails with attachments. It still fetches all emails, but only the `attachments` field, not the `body` or `mime_content` or other fields on an email that may be very large. This will save you bandwidth.

Next, you shouldn't run `item.save()` on every attachment. You should do it only once per item. Also, you only want to change the `is_read` field, so it's safer and faster do `item.save(update_fields=['is_read'])`.

Finally, if your script doesn't download all attachments, then it could be a problem with the filtering you are doing. Try to print out the `attachment.name` for all attachments that your logic is skipping. You'll probably find your missing files there.

**Comment by Bibhu280** [comment]
Hi now in less time I am able to download attachments. But it is skipping some attachments in 1st run but when did 2nd run it is downloading(same code).Skipping always random attachments.
total-1k, 1st run-800 downloading,2ndrun-200


for item in account.inbox.all().order_by('-datetime_received').exclude(is_read=True).only('attachments'):
 for attachment in item.attachments:
        match=re.findall(r'DS\d+', attachment.name)
        if itc['Reference'].isin(match).any():
            item.is_read=True
            item.save(update_fields=['is_read'])
            if isinstance(attachment, FileAttachment):
                local_path = os.path.join(attachment.name)
                with open(local_path, 'wb') as f:
                    f.write(attachment.content)
                print('Saved attachment to', local_path)

**Comment by ecederstrand** [comment]
You are still setting the `is_read` attribute once per attachment instead of once per item. Apart from that, it's really difficult for me to find out what is wrong. I think you'll have to do some more debugging yourself. For example, what is special about the attachments that are not getting processed in the first run? Does `item.attachments` contain all attachments in the first run, if you print the attachment names out before matching and filtering?

**Comment by Bibhu280** [comment]
Requirement is if attachment available in reference file then download it mark that email as read. But when marking read it is skipping some email, but if do not mark  as read it is downloading everything.

path = "D:\\data"
for item in account.inbox.filter(is_read=False).order_by('-datetime_received').only('attachments'):
        for attachment in item.attachments:
            if itc['Reference'].isin([attachment.name.split(".")[0]]).any():
                if isinstance(attachment, FileAttachment):
                    local_path = os.path.join(path,attachment.name)
                     item.is_read=True
                     item.save(update_fields=['is_read'])
                    with open(local_path, 'wb') as f:
                        f.write(attachment.content)
                        print('Saved attachment to', local_path)


(item.is_read=True)  statement passing below attachment because I want download attachment from email and mark as read only that particular email where download happen. If (item.is_read=True) passing after for loop it is marking everything read.

**Comment by Bibhu280** [comment]
Hi mailbox configuration can cause this type of issue & my mailbox size is 1GB.Need to do any configuration changes in mailbox.
please response

**Comment by ecederstrand** [comment]
It's possible that calling `item.save()` during iteration of the items messes up the iteration of attachments. One thing you could try is to instead collect the items in a list, and update the `is_read` attribute afterwards:

```python
mark_as_read = []
for item in account.inbox.filter(is_read=False).order_by('-datetime_received').only('attachments'):
   # Do stuff here. If the item was processed, add it to the list (but only once!)
   mark_as_read.append(item)

for item in mark_as_read:
      item.is_read=True
      item.save(update_fields=['is_read'])
```

**Comment by Bibhu280** [comment]
Thanks, it is working.
