### ISSUE TITLE
Listing events in Shared Calendar

### ISSUE THREAD

**Issue by RossK1** [ecederstrand/exchangelib#830]
Hello,

We're trying to implement a cross-platform sync of calendar events and so need to export a list of all events from a shared calendar. Users share their calendar in read-only mode with a generic account, we log into that account using exchangelib (great package, btw!) and pass the shared accounts email address as the smtp address.

The problem is that whilst we can access the calendar without issues and even query the number of items in it, as soon as we try to view those items we get the error shown below. I found the post relating to trying to access details from private events, so used the code from that topic to narrow the query, but still no luck.

I found a post on the Microsoft support site (https://support.microsoft.com/en-us/help/3196521/operation-failed-cannot-query-rows-in-a-table-error-during-finditems-o) dealing with a similar error. Is that what is happening here?

Any thoughts or suggestions?

As a side query, is this the only way to check a shared calendar? As we will be processing upwards of 500 calendars, logging in every time is quite a slow process. Is there a way to log in once and then switch between addresses to quickly access all the calendars?

Thanks :)

> exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again., Cannot query rows in a table.
```python
account = connect_to_mailbox("user@domain.com")
print(account.calendar.total_count) # This works fine and prints the number of calendar events (matches with what i see in outlook)
items = account.calendar.all().only('start', 'end', 'sensitivity') # no errors here either
print(items) # This prints "QuerySet(q=Q(), folders=[Calendar (Calendar)])", so no issue there
for item in items: # This line errors out with exchangelib.errors.ErrorAccessDenied: Access is denied. Check credentials and try again., Cannot query rows in a table.
    print(item.start)
```

**Comment by ecederstrand** [comment]
First, a comment about the example code. The actual query to EWS only happens when you consume the `items` queryset, i.e. when you iterate over it. That's why you don't get errors before the for loop.

I don't have a lot of experience with shared calendars. There have been numerous issues opened here about then, and it's not obvious to me when it works and when it doesn't.

If you want to do large-scale syncing of calendars (I've done that myself for 5-10 years with exchangelib) then a better approach is to acquire a service user on the Exchange server and the get impersonation (preferably) or delegate access to the calendars in the mailboxes you want to sync. That's best done by the Exchange admins, but users should also be able to grant delegate access to the service user.

exchangelib distinguishes between the connecting user (the Credentials) and the mailbox to connect to (the Account) so you would set up a Credentials for your service user and then an Account for each of the mailboxes you want to access the calendar for.

**Comment by RossK1** [comment]
Thanks for the prompt reply! 

Apologies, I forgot to include the code for the connect_to_mailbox function. It's below. The server allows me to connect to the SMTP account as a delegate (if I try to switch to impersonate it throws an an access denied error when trying to connect), but the test user hasn't actually granted the account delegate access, just shared the calendar with read/write access. Would that be enough to access it? So I'm wondering if EWS is allowing the delegate connection, but then denying access when I try to actually do something like read the list of events. It may also be that the test user we chose is a large shared calendar that has 2GB worth of items in it ... so that error may well be an exchange error rather than an actual access denied error.

In the exchangelib code, if the server returns an error like the aforementioned "cannot query rows in a table", would it throw that back as an accessdiened error?

So the best way to check multiple shared calendars is to loop through the smtp addresses and create a separate Account object for each, then use those account objects to query the calendars?

A little off topic here, but once authenticated on the first smtp, is there a way to speed up the creation of subsequent Account objects?

Thanks again :)

```python
def connect_to_mailbox(email_address):
    # Define some of the autodiscover values to speed up the connection
    ews_url = r'https://outlook.office365.com/EWS/Exchange.asmx'
    ews_auth_type = 'basic'
    # Build credentials
    retrieved_credentials = retrieve_credentials() # This function retrieves username and password
    credentials = Credentials(retrieved_credentials[0], retrieved_credentials[1])
    # Build the config
    config = Configuration(service_endpoint = ews_url,
                           credentials=credentials,
                           auth_type = ews_auth_type)
    # Connect to the account
    account = Account(primary_smtp_address = email_address,
                      config=config,
                      autodiscover=False,
                      access_type=DELEGATE) # DELEGATE or IMPERSONATION
    return account
```

**Comment by ecederstrand** [comment]
exchangelib tries to relay the server exception as honestly as possible, so you'll get the exception type and wording that we get from EWS.

I don't know a lot about the internals of Exchange WRT the permission system and performance of the backing store, but it's my understanding that a shared calendar with 500 participants is not the way to go. So I'd rather not spend a lot of time trying to get it to work, and instead suggest you the better option that I know works - a system account and impersonation/delegate access to the accounts.

Creation of additional Account objects should be fast in general when the initial authentication has happened. autodiscovery will slow down the creation, but we're caching the information that's possible to cache after the first successful autodiscover query. Are you seeing a different pattern?

**Comment by ecederstrand** [comment]
@RossK1 Did you get any further with this?

**Comment by RossK1** [comment]
Hey @ecederstrand. Yes, thanks for checking! The calendar simply being shared with the automation account was not enough, we kept getting the access denied errors described. When the account was explicitly granted delegate access, all the problems went away and the calendar items can be queried with no issues :)
Thank you!
