### ISSUE TITLE
Folder save() failed after calling refresh()

### ISSUE THREAD

**Issue by Eden-Liu** [ecederstrand/exchangelib#832]
Hello,

Found this issue in version 3.3.0. Using Exchange 2016 CU18

```python
folderTest = Folder(parent=ewsc.user.inbox, name='Folder Test')
folderTest.save()  # The step successful
folderTest.refresh()  #after refresh(), permission_set isn't empty, call save() will failed.
folderTest.name = 'Folder Name Modify'
folderTest.save()
```
![image](https://user-images.githubusercontent.com/14228648/100713012-a3e72680-33ee-11eb-9d44-47dcdb2ca5de.png)

Found it is PermissionSetField issue. If remove PermissionSetField from class Folder, no the exception.

**Comment by ecederstrand** [comment]
Some people report they can set the `PermissionSetField` field, others not. I haven't found a pattern or explanation yet The workaround I've suggested previously is:

```python
folderTest.name = 'Folder Name Modify'
folderTest.save(update_fields=['name'])
```

It's good practice anyway to only write back the field(s) you are changing.

**Comment by Eden-Liu** [comment]
Thank you @ecederstrand
Actually, I want to modify PermissionSetField, but it is always failed. So, found the issue. Do you have anyway to do that?

**Comment by ecederstrand** [comment]
I don't know why it fails for you, unfortunately, and an InternalServerError is not a helpful error message from the server at all. Maybe your Exchange admins are able to help you find out why it's failing.

**Comment by ecederstrand** [comment]
@Eden-Liu Did you find a solution to this problem?

**Comment by Eden-Liu** [comment]
@ecederstrand No, I didn't. Close this issue?
