### ISSUE TITLE
Can not Connect

### ISSUE THREAD

**Issue by mark-des** [ecederstrand/exchangelib#834]
Hello, 

I hope somone can help me im geting this error when trying to connect

Failed to create cached protocol with key ('https://outlook.office.com/EWS/Exchange.asmx', None): HTTPSConnectionPool(host='outlook.office.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002926CC09D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

This is the code im using

from exchangelib import DELEGATE, Account, Configuration, Credentials, NTLM, Build, Version

credentials = Credentials('User@user.com', 'password')
config = Configuration(server='outlook.office.com')
account = Account('User@user.com', credentials=credentials, config=config , autodiscover=False)

**Comment by ecederstrand** [comment]
For some reason, your system cannot resolve the hostname to an IP address. See https://stackoverflow.com/questions/7334199/getaddrinfo-failed-what-does-that-mean

**Comment by anshibanov** [comment]
Thank you for helping! Hostname successful resolvnig:

`print(socket.getaddrinfo('mail.rostechn.ru', 8080))`
[(<AddressFamily.AF_INET: 2>, 0, 0, '', ('188.128.56.27', 443))]

Any other ideas?

**Comment by ecederstrand** [comment]
But that's not the hostname or port that's failing. The error message says host='outlook.office.com', port=443.

**Comment by mark-des** [comment]
Thank you ecedestand for you comment that gave me the hint where to look for the problem that i need to add a proxy server for this to work. and now it does

**Comment by RossK1** [comment]
As a heads up, this error may appear occasionally if the server you are connecting to is down (e.g. for maintenance). If you are certain that the connection should work and have tested it before, you can add some sort of retry to your script :)
