### ISSUE TITLE
Adding a member to a distribution (mailing) list

### ISSUE THREAD

**Issue by maximbetin** [ecederstrand/exchangelib#835]
Is it possible to add a user to a mailing list? I've been searching the docs for hours now to no avail. If so, could you share an example?

**Comment by ecederstrand** [comment]
I think the way to do this is to access the distribution list item via your contacts folder, append to the `DistributionList.members` field and then save the item.

**Comment by ecederstrand** [comment]
@maximbetin Did you get anywhere with this issue?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional issue.

**Comment by maximbetin** [comment]
Hello Erik, sorry for the long delay, I had to postpone this issue for a while. 

What exactly do you mean by accessing a DL from the Contacts folder? That DL would have to be previously added to the Contacts folder then I suppose? I went ahead and added one of my distribution lists as a Contact and successfully referenced it by its display name, however, the 2nd line from your snippet returns the following error output:

`AttributeError: 'Contact' object has no attribute 'members'`

Currently, the distribution groups my user is part of in Outlook Cloud is accessed through Settings > General > Distribution groups, so I'm kind of confused by the use of the Contacts folder, could you clarify that? Thanks a lot.

**Comment by ecederstrand** [comment]
I don't have a lot of experience with contacts and distribution lists. I just know that a contacts folder can contain both `Contact` and `DistributionList` items, but I don't know how to create `DistributionList` items manually in the folder. Only `DistributionList` items have the `members` attribute that would contain the members.

**Comment by maximbetin** [comment]
Hello Erik,

Thanks for the answer. I don't really require to create a Distribution List, it is already created in Exchange. I would just like to access it somehow and add another member to it using the library, hence my confusion in regards to the use of the Contacts folder. To my awareness, Distribution Lists or Mail-Enabled Security groups in Exchange Online appear at the Groups section, is there any other way I can access one of these?

![image](https://user-images.githubusercontent.com/12023089/104123731-2992b600-534d-11eb-914a-eaaabcbeea0c.png)

**Comment by ecederstrand** [comment]
Doing a bit of googling, it seems that EWS does not support editing distribution lists. See e.g. https://stackoverflow.com/questions/16540795/changing-the-members-of-a-static-exchange-distribution-list-programmatically and https://stackoverflow.com/questions/42979693/create-group-distribution-group-and-add-members-ews o you'll hae to find some other way of handling your DLs, e.g. via Exchange management commands.
