### ISSUE TITLE
Can We use exchangelib for processing  mails in outlook(cloud shared mailbox).

### ISSUE THREAD

**Issue by Bibhu280** [ecederstrand/exchangelib#836]
Previously I am using Exchangelib library for accessing  mail through webmail in my organization. But due to space size issue in webmail we want  move mails to cloud shared mailbox(Delegate access).
Is exchangelib will support in cloud shared mailbox ya need to do some changes?

**Comment by ecederstrand** [comment]
I don't know how shared mailboxes work, but it seems that you'll get a special email address for the mailbox in the cloud? See https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes

In that case, just create an `Account` object with that email address.

**Comment by ecederstrand** [comment]
@Bibhu280 Did you get anywhere with this issue?

**Comment by Bibhu280** [comment]
Hi still mail not migrate, once mail migrate to cloud shared mail box then only I can check exchangelib library is working or not.

**Comment by ecederstrand** [comment]
Ok. Feel free to re-open this issue if you still have issues related to exchangelib when the migration is done.
