### ISSUE TITLE
Reverse delegate look-up

### ISSUE THREAD

**Issue by RossK1** [ecederstrand/exchangelib#838]
Hello,

When connected as to account, I am able to query a list of delegates of that account using a.delegates. Is there currently a functionality or workaround to query which accounts the current account is a delagate of, i.e. looking up the tree rather than down?

Thanks!

**Comment by ecederstrand** [comment]
I don't think EWS supports this. A quick googling only gives me this: https://stackoverflow.com/questions/7922408/ews-api-delegate-list

The only workaround I can think of is to get a list of all accounts and do a delegates query on each, and then build up the tree yourself. It only scales to a certain level, of course.

**Comment by RossK1** [comment]
I was able to get access to expand one of the distribution lists which gives me most of the active emails. I can loop through that and establish connections to each of those accounts but when I query account.delegates on them, they all return an empty list [].
Even when checking an account which I know my test account is a delegate of of, it returns []. If I assign a delegate to the test account and query itself, it shows the delegate information as expected so I'm guessing this is a permission issue? Maybe a delegate cannot query an account for other delegates? Seems weird.

Another workaround I thought of would be to connect to each account and try to query the calendar. If it can do this, then it has access. If it errors out, then it does not have access. The problem is that this is extremely slow and a bit of an ugly brute force approach.

Is there any way to quickly query permissions when connected to an account to see if the test account is a delegate of that account? EWS will happily allow me to connect with access_type = DELEGATE even if the test account has no access at all :P Is there some flag to check to see if it actually allowed any access or permissions?

Thanks :)

**Comment by ecederstrand** [comment]
It's possible that the missing delegate information is a permission issue. I don't know a lot about that part, and probably an Exchange server list would be a better place to ask.

To tests access, `account.calendar.all().exists()` should be quite fast. It requests the ID of one single item from the calendar. You can make if faster by disabling autodiscover, if you haven't done that already.

**Comment by RossK1** [comment]
That would definitely work and I have already disabled autodiscover to speed up the process :) The issue is that if the test account has no access to the account it is querying, it cannot even navigate to account.calendar to see if any items exist, it gives the error below. Is there a way to query the account object to see what folders are in it without actually trying to access one of them?

Thanks :)

> exchangelib.errors.ErrorItemNotFound: The specified object was not found in the store., The process failed to get the correct properties.

**Comment by ecederstrand** [comment]
If you get an exception, then just catch it and continue. It’s an indication that you don’t have any access to the account.

**Comment by RossK1** [comment]
That's what I currently have, try to access account.calendar, if it fails, the test account doesn't have access. It just takes about ~1.5s for the error to come back vs < 0.5s if it actually has access so was hoping there was a way to query if it had access without actually trying and having it error out. Also not sure if the server is going to appreciate all these access requests :P

**Comment by ecederstrand** [comment]
I don't know of any better options, unfortunately, but EWS is a pretty extensive API. Feel free to post here if you find anything.

The server is probably not going to care, but it's possible that some server policy will eventually block your account. Make sure to agree with your Exchange admins that what you're doing is OK.

**Comment by RossK1** [comment]
I poked around a bit but couldn't find any way to query up. I think I'll probably get a DL from the admins, expand that and loop through each address, trying to access the calendar. If the server throws an access denied error, move on. If it allows the access, query the account for delegates to check the permissions.

If anyone else finds a way to do this, let us know!

Thanks again :)
