### ISSUE TITLE
BodyType: Text vs HTML

### ISSUE THREAD

**Issue by AltruisConsulting** [ecederstrand/exchangelib#84]
I have spent quite a bit of time ploughing through the code to figure this one out....but have failed to do so. 

When reading accessing the body of an email the default format, when an email is sent in HTML, is in HTML. Is there a way to access the text BodyType of an email?

Thanks!

**Comment by ecederstrand** [comment]
The `Message.body` attribute contains either the text or HTML representation, not both. If the body is HTML and you need the text, you could probably use the `mime_content` attribute.

Out of curiosity, why would you want the text if the e-mail is sent as HTML?

**Comment by AltruisConsulting** [comment]
Ok, I will try that out. 

We use exchangelib to parse emails. The text body of the email is more predictable when reading. I realize we could using something like beautifulsoup or some other package to clean up the html...but why waste lines of code if it already exists!

Again, I'm always open to alternative solutions.

Thanks!

**Comment by ecederstrand** [comment]
Ok, I'll see if I can support this in a non-awkward manner. https://github.com/ecederstrand/exchangelib/blob/master/notifier.py uses `beautifulsoup` to convert HTML to text.

**Comment by ecederstrand** [comment]
This should probably be implemented using the `TextBody` element: https://msdn.microsoft.com/en-us/library/office/jj191321(v=exchg.150).aspx and exposed as an attribute called e.g. `text_body`.

See further discussion in http://stackoverflow.com/questions/20982851/how-to-get-the-email-body-in-html-and-text-from-exchange-using-ews-in-c

Unfortunately, the `TextBody` element is only supported on Exchange 2013 and up, and `exchangelib` has no concept of versioned attributes yet. This needs to be solved first.
