### ISSUE TITLE
Accessing Office 365 Groups and mail inside groupmailbox

### ISSUE THREAD

**Issue by arijit-s** [ecederstrand/exchangelib#840]
How to access O365 Groups and the mails in the groupmailbox? To be clear I am talking about this group.

https://support.microsoft.com/en-us/office/learn-about-microsoft-365-groups-b565caa1-5c40-40ef-9915-60fdb2d97fa2

I do not see the groups getting listed in the root tree of the account.

**Comment by ecederstrand** [comment]
I don’t think those groups are exposed via EWS. Do you have any indication that they are?

**Comment by arijit-s** [comment]
I could not find anything official, but maybe can these help?

quiet old post..
https://gsexdev.blogspot.com/2015/05/using-office-365-groups-within-ews.html

Here please check the reply from Seven Zhou MSFT, he have mentioned using exchange accessing Office Groups.
https://answers.microsoft.com/en-us/outlook_com/forum/all/how-to-access-microsoft-365-outlook-groups-with/ea36dd9b-44a0-4ded-b6d8-aaa7dee9cf33

**Comment by ecederstrand** [comment]
The answer from Seven is about IMAP, confirming that it's not supported via that protocol.

The blog post mentions an `GetUserUnifiedGroups` EWS service that is undocumented. It's still not documented at https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/ews-operations-in-exchange so I'm unsure if it's available at all.

**Comment by ecederstrand** [comment]
Closing. I'm not keen on implementing undocumented services in exchangelib.
