### ISSUE TITLE
Help with Blocking an email address or sender's domain 

### ISSUE THREAD

**Issue by MatanHaSiemplify** [ecederstrand/exchangelib#841]
Hello!

I need some guidance and help here, will really appreciate it if someone can direct me to the right solution.

We are using exchangelib v3.2.1.
We have a use case in which we **would like to block a sender or a domain from sending mails into the organization's mailboxes.**
We would like to use the lib to perform a block operation in exchange: add it to blocked senders/domain list, etc..
For example, like mentioned [here](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-add-and-remove-email-addresses-from-blocked-senders-list-by-using-ews)

I wanted to ask if there's a way to achieve this goal using the library - the actual operation is not the main concern, but having the mailbox protected is the main one. 

Thank you!

**Comment by ecederstrand** [comment]
That requires the [MarkAsJunk ](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/markasjunk) service which is not supported by exchangelib yet. It's a very simple service so it should not be difficult to implement.

**Comment by MatanHaSiemplify** [comment]
Great @ecederstrand thank you for your quick response! 
Does that mean you are going to implement it soon? or we should try to do it ourselves and send it to you?

Thanks again!

**Comment by ecederstrand** [comment]
I'm pretty busy ATM and don't have plans to implement it myself. I'd be happy to review a PR for this :-)
