### ISSUE TITLE
Reading category list and adding categories

### ISSUE THREAD

**Issue by RossK1** [ecederstrand/exchangelib#842]
Hi :)

Is there currently a way in exchangelib to access the category list of an account and to add categories to it? I've seen some C# and VB code online dealing with this (e.g. [here](https://www.independentsoft.de/exchangewebservices/tutorial/addcategory.html) but not sure if it is implemented in exchangelib yet. #819  deals with the master category list, so this may be related to that.

Thank you!

**Comment by ecederstrand** [comment]
The tutorial mentions a `GetCategoryList` service, but I don't see it available at https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/ews-operations-in-exchange It's possible that it's only available in the managed API, not vi EWS.

**Comment by ecederstrand** [comment]
Closing. I'm not keen on implementing undocumented services in exchangelib.
