### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by gtdavidv** [ecederstrand/exchangelib#845]
We just upgraded to the most recent version of exchangelib on pip and are getting a new error.

```
File "/usr/local/lib/python3.6/dist-packages/exchangelib/queryset.py", line 287, in __iter__
    for val in self._format_items(items=self._query(), return_format=self.return_format):
File "/usr/local/lib/python3.6/dist-packages/exchangelib/queryset.py", line 256, in _query
    items = sorted(items, key=lambda i: _get_value_or_default(i, f), reverse=f.reverse)
TypeError: can't compare offset-naive and offset-aware datetimes
```

The query that produces this error is when I try to access:

`calendarList = account.calendar.view(start=startDateTime, end=endDateTime).order_by('-start')[:25]`

I believe this may be related to a previous issue I raised back in September: https://github.com/ecederstrand/exchangelib/issues/808

This seems to be a rare issue affecting a small percentage of calendar items for a single user (so far).

For now I'm just going to try to fall back on unsorted results using:
```
try:
    calendarList = account.calendar.view(start=startDateTime, end=endDateTime).order_by('-start')[:25]
except TypeError:
    calendarList = account.calendar.view(start=startDateTime, end=endDateTime)[:25]
```

**Comment by ecederstrand** [comment]
Thanks for reporting! After #808, I can't see how that could happen. 

Can you enable debug logging, or break out a debugger, and check what the `start` values look like? There's obviously something slipping through as dates or naive datetimes.

**Comment by gtdavidv** [comment]
It would be pretty tough to manually home in on the exact items causing this issue. The fix I mentioned is working well enough for my purposes, but let me know if it's valuable to you for me to spend time getting more diagnostics and I can dig in.

**Comment by ecederstrand** [comment]
I was thinking to do the query without sorting, and then calculate all the sort values to find the misbehaving value. Something like:

```python
from exchangelib.queryset import _get_value_or_default

qs = account.calendar.view(start=startDateTime, end=endDateTime)
f = qs._get_field_order('-start')
prev_sort_value = None
for i in qs:
    sort_value = _get_value_or_default(i, f)
    if prev_sort_value is not None:
        try:
            prev_sort_value < sort_value
        except TypeError:
            print(prev_sort_value , sort_value, i)
            raise
    prev_sort_value = sort_value
```

**Comment by ecederstrand** [comment]
@gtdavidv Did you get to the bottom of this?

**Comment by gtdavidv** [comment]
No update from my end unfortunately. The error was only happening for 1 of our users and even then only on a very small subset of their data out of a full-history merge so recreating is a bit tricky. From my perspective feel free to close the issue.

If it is really important to you to track down the issue I can set aside some time to go find the culprit data again.

**Comment by ecederstrand** [comment]
I’ve never seen it reported elsewhere and I can’t find a way to reproduce. Let’s close this issue and then you can reopen if this causes problems for you again.
