### ISSUE TITLE
filter mail in all folders 

### ISSUE THREAD

**Issue by BrianWang1990** [ecederstrand/exchangelib#848]
As an administrator, I want to delete the mails sent by mistake by IMPERSONATION, but I am not sure whether the recipients have receiving rules, and automatically put the received mails in a custom folder. Is there any good? The method traverses all folders of the recipient to find the only mail(not including calendar, contacts, etc.)

**Comment by ecederstrand** [comment]
A normal `.filter()` works on just the folder you call it on. EWS does not support searching items within all folders, but only the folders explicitly mentioned in the `FindItems` service call.

In exchangelib, the way to call `FindItems` on multiple folders in one go is to use a `FolderCollection`:

```python
from exchangelib import FolderCollection
FolderCollection(account=account, folders=[...]).filter(some_field='foo')
```

The `folders` argument can be any iterable of folders, e.g. `[account.inbox, account.sent]`, `account.root.walk()` or `(f for f in account.root.walk() if f.CONTAINER_CLASS == 'IPF.Note')`

**Comment by BrianWang1990** [comment]
@ecederstrand  thanks for the comment. It did solve my problem, I will close the issue.

**Comment by ecederstrand** [comment]
I just remembered that you can also call ``.filter()` on various subfolder access methods like `.glob()`, `.walk()`, and `.children` :

```python
account.root.glob('**/*').filter(some_field='foo')
account.inbox.walk().filter(some_field='foo')
(account.inbox // 'some_subfolder').children.filter(some_field='foo')
```
