### ISSUE TITLE
Flag and mark complete

### ISSUE THREAD

**Issue by ninSmith** [ecederstrand/exchangelib#85]
Hey there again,

I'm looking for a way to flag emails and when processed mark them as complete however I can't find the right field in the email class.

Could you please indicate me which one to use ?

Thanks

**Comment by ecederstrand** [comment]
If you can use the `is_read` flag then I would suggest to use that. Otherwise, you can create an extended property that stores your `is_processed` information. Have a look at the README and `exchangelib.folders.ExternId` for examples.

**Comment by ninSmith** [comment]
Thanks, just to be sure, there are no functions to put a flag or check mark on an email like in outlook (https://support.office.com/en-us/article/Flag-an-item-for-follow-up-7b0f0c0e-21a6-41f0-96de-2cbda41e7eb1 https://support.office.com/en-us/article/Remove-a-flag-or-mark-flag-complete-eae87efc-2b10-4239-88bb-1b20674721cd) ?

Moreover, for the ExternId solutions, which value do I have to put for ```property_set_id``` ? Is it a random value ?

Thanks very much for your help.

**Comment by ecederstrand** [comment]
Ah, *that* flag. You can see the available fields in EWS for a Message item here: https://msdn.microsoft.com/en-us/library/office/aa494306(v=exchg.150).aspx I'm not sure if one of those maps to the flag on Outlook.

**Comment by ecederstrand** [comment]
It seems the flag and related properties is actually an extended property. See the answer to http://stackoverflow.com/questions/26017121/facing-issue-in-setting-follow-up-for-email

You should be able to create and register an extended property that implements this. Please follow up here if you get this to work. I imagine other users will run into the same issue.

**Comment by ninSmith** [comment]
Thanks for your help.   

I'll keep you updated.

**Comment by ecederstrand** [comment]
This worked for me:

```python
class Flag(ExtendedProperty):
    property_tag = 0x1090
    property_type = 'Integer'

Message.register('flag', Flag)

for m in account.inbox.all():
    print(m.flag)
```

This prints either `None` for non-flagged messages and or `2` for flagged ones.

I think this should be added as a standard attribute on `Message`, possibly implemented as a boolean `flagged` that can be `True` or `False`.

**Comment by ninSmith** [comment]
Hey,    

First, sorry for the late reply.

It works :+1: !    

I managed to write value into it and the email is flagged in outlook.   

For now this is perfect for me, I don't need the others functionality connected to flags.

Thank you very much for your fantastic work !

**Comment by ecederstrand** [comment]
@Pratibha-Singh Filtering emails by flag value is a different problem. Please open a new issue with your code and the full stack traces you get.

**Comment by vidyasagarhj** [comment]
The best way is to set FlagStatus=1 (tick mark against the email) and save it. Use the below code to flag the email **Mark complete**.

    message.FlagStatus = 1
    message.save()
