### ISSUE TITLE
Exchangelib hitting issues with number of concurrent connections

### ISSUE THREAD

**Issue by cjsanjay** [ecederstrand/exchangelib#855]
I am using exchangelib for subscribing to push notifications from the exchange 2016. After receiving the push notification I am fetching the email and running some processing.
I am using service account credentials for impersonating the mailbox user and there are total ~10k users. I am running the exchange lib wrapped in a python service in a docker container. This exchangelib service reads from the push notifications queue and fetches message(No threading only one instance of exchangelib in the python service).
I am encountering the following error multiple times.

```python
exchangelib.errors.ErrorExceededConnectionCount: You have exceeded the available concurrent connections for your account.  Try again once your other requests have completed.
```

I have only 24 instance of this service running and the EwsMaxConcurrency throttling policy is set to 50. Not sure why it would exceed the concurrent connections limit. 
rough code snippet that I am using

```python
credentials = Credentials(username=svc_account_user_name, password=svc_password)
config = Configuration(server=host, credentials=credentials, retry_policy=None)
for message_id in push_notification_queue:
  account = Account(mailbox_email, credentials=credentials, config=config, access_type=IMPERSONATION,
                                default_timezone=UTC)
   msg_items = account.fetch(ids=[{"id": message_id, "changekey": change_key}])
   process message(msg_items)
```

Is there some connection caching that happens underneath for each mailbox that will keep the mailbox connections open?
Do I need to explicitly close the connection from the mailbox after fetching the message for each push notifications?

**Comment by cjsanjay** [comment]
@ecederstrand any pointers will be really helpful. Thanks in advance.

**Comment by ecederstrand** [comment]
Which version of exchangelib is this? Since 3.2.0 exchangelib is supposed to only open one TCP connection per server in the default configuration. The connection is not tied to the Account but rather to a Protocol instance that is shared per server. Connections are closed when the Protocol instance is garbage collected.

**Comment by cjsanjay** [comment]
@ecederstrand we are using exchangelib version 3.2.0. 
So if the protocol object is shared then in my code snippet above when I overwrite the account instance object it will just reuse the underlying protocol object and when I am done processing all the messages in the push notification queue protocol object will be garbage collected.

**Comment by ecederstrand** [comment]
That's the theory, yes. There may be bugs, of course :-) I guess you could verify this with netstat or something like that.

**Comment by ecederstrand** [comment]
@cjsanjay Did you get anywhere with this?

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional info.
