### ISSUE TITLE
Using Microsoft Graph API with exchangelib

### ISSUE THREAD

**Issue by Gugla** [ecederstrand/exchangelib#856]
We are using 'exchangelib' with an application mailbox using EWS protocol and basic authentication to read and send emails. As Microsoft is going to retire basic authentication for all application mailboxes, we are in the process of transitioning the application mailbox to modern authentication (OAuth 2.0) for more security. our IT team has registered the mailbox on Azure AD and provided the permissions to access the mailbox through Graph API. 

As the mailbox is set with Graph API permissions, I am getting an error **'Invalid credentials for https://outlook.office365.com/EWS/Exchange.asmx**'. We have reached out to our IT team to provide access to EWS API too in order to connect with the mailbox. 

Our IT team is not ready to provide access to EWS API as EWS is an older language and they are asking us to connect through Graph API.

My question is _'does exchangelib supports Graph API?' If yes, then what config I can use to connect to the mailbox using client_id, client_secret, tenant_id. If No, then is there any other workaround to resolve this issue?_

Thanks in advance

**Comment by ecederstrand** [comment]
No. exchangelib does not support Graph API. There are other packages that do support the Graph API, but I haven't used any of them so I would rather not give any advice. Here's a starting point, though: https://developer.microsoft.com/en-us/graph/get-started/python
