### ISSUE TITLE
How to get a plain text message?

### ISSUE THREAD

**Issue by sanindd** [ecederstrand/exchangelib#861]
Hello, tell me how can I get the body of an email in plain text without html formatting?
I know what I can use `mime_content` but I don’t know how(
And also tell me can I receive the last letter without using 'for'?

```
root_folder = account.root /'my_path'
for item in root_folder.all().order_by('-datetime_received')[:1]:
    print(item.subject,item_body)
```
Thanks for your work!

**Comment by ecederstrand** [comment]
If the message was sent as HTML, and the HTML-formatted message is contained in the `item.body` field, then you can use the `item. text_body` field which contains the attempt by the Exchange server to convert the HTML message to plain text.

**Comment by sanindd** [comment]
It worked!
Thank you very much!
