### ISSUE TITLE
Get requests for System1 folder cause batch processing to stop

### ISSUE THREAD

**Issue by lmverity** [ecederstrand/exchangelib#862]
Hello!
When crawling the top level root in a mailbox, we're noticing that occasionally mailboxes have a folder called System1 that causes EWS to respond to a get folder request with ErrorAccessDenied. All subsequent items in the query set are returned as ErrorBatchProcessingStopped. After opening a case with Microsoft, we learned that there isn't a property that we can use to identify this sort of proprietary folder. It appears to be another folder similar to System or Audit, which doesn't allow get folder requests, but permits find folder.
I've added a System1 folder class to the list of known folders, which rectifies the issue. I can open a PR if this is a change you'd like to have in the repository.
Thanks!

**Comment by ecederstrand** [comment]
A PR would be most welcome. Thanks!
