### ISSUE TITLE
Autodiscover error

### ISSUE THREAD

**Issue by RodrigoBorges93** [ecederstrand/exchangelib#863]
Hi @ecederstrand how are you doing?

I'm sorry if it is not the properly place to ask for help, but I'm using exchangelib for 5 months with a shared mailbox and suddenly it stopped working:

The error:

TransportError: Redirect not allowed but we were redirected (https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml -> https://autodiscover-s.outlook.com:443/Autodiscover/sharedMailboxName/Autodiscover.xml)
Retry: 0
Waited: 10
Timeout: 10
Session: 26550
Thread: 9300
Auth type: <requests.auth.HTTPBasicAuth object at 0x000001ECB43226A0>
URL: https://autodiscover-s.outlook.com/Autodiscover/Autodiscover.xml
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x000001ECB4322C70>
Allow redirects: False
Streaming: False
Response time: 0.14099999982863665
Status code: 302
Request headers: {'User-Agent': 'exchangelib/3.3.2 (python-requests/2.24.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '/', 'Connection': 'keep-alive', 'Content-Type': 'text/xml; charset=utf-8', 'Content-Length': '366', 'Authorization': 'Basic ZXh0cmF0b3JORkVAdHJhbnNwZXRyby5jb20uYnI6ZXM3QCN3b3JrJTIxVFB0'}
Response headers: {'Cache-Control': 'private', 'Content-Type': 'text/xml; charset=utf-8', 'Location': 'https://autodiscover-s.outlook.com:443/Autodiscover/<sharedMailbox/Autodiscover.xml', 'Server': 'Microsoft-IIS/10.0', 'request-id': 'e969c5b6-2426-4ac0-b8e4-2be2b399037e', 'X-CalculatedBETarget': 'CP4P284MB1348.BRAP284.PROD.OUTLOOK.COM', 'X-BackEndHttpStatus': '302', 'X-RUM-Validated': '1', 'X-MS-Credentials-Expire': '15', 'X-MS-Credential-Service-Federated': 'false', 'X-AspNet-Version': '4.0.30319', 'X-DiagInfo': 'CP4P284MB1348', 'X-BEServer': 'CP4P284MB1348', 'X-Proxy-RoutingCorrectness': '1', 'X-Proxy-BackendServerStatus': '302', 'X-Powered-By': 'ASP.NET', 'X-FEServer': 'ROAP284CA0028', 'Date': 'Fri, 12 Feb 2021 21:45:05 GMT', 'Content-Length': '0'}
Request data: b'\nhttp://schemas.microsoft.com/exchange/autodiscover/outlook/responseschema/2006a'
Response data: b''

Traceback (most recent call last):
File "D:\Jenkins\jobs\extracao-gdf-anexos-email-compartilhado\teste.py", line 18, in 
account = Account('', credentials=credentials, autodiscover=True)
File "D:\Python\lib\site-packages\exchangelib\account.py", line 116, in init
self.ad_response, self.protocol = discover(
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 24, in discover
return Autodiscovery(
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 123, in discover
ad_response = self._step_1(hostname=domain)
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 433, in _step_1
return self._step_2(hostname=hostname)
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 451, in _step_2
return self._step_3(hostname=hostname)
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 483, in _step_3
return self._step_4(hostname=hostname)
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 514, in _step_4
return self._step_6()
File "D:\Python\lib\site-packages\exchangelib\autodiscover\discovery.py", line 572, in _step_6
raise AutoDiscoverFailed(
exchangelib.errors.AutoDiscoverFailed: All steps in the autodiscover protocol failed for email ''. If you think this is an error, consider doing an official test at https://testconnectivity.microsoft.com

In the code, I just tried to connect with my account in the shared Mailbox which I was enable to do in the browser with no problem. The https://testconnectivity.microsoft.com showed no problem at all and the code was working few minutes earlier. I am able to connect with others shared Mailboxs with no problem.

Do you know what could be happening?

Thanks in advance.

**Comment by ecederstrand** [comment]
The easiest way to find out is to compare the steps in the test report that  https://testconnectivity.microsoft.com reports, with the steps taken in exchangelib. If you enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting), the steps taken by exchangelib will be printed.

That said, if you know that your account is on Office365, you can just skip autodiscovery and connect to `outlook.office365.com` directly.

**Comment by RodrigoBorges93** [comment]
Thank you so much, worked just fine with the outlook.office365.com.
