### ISSUE TITLE
Get the first meeting from the meeting loop

### ISSUE THREAD

**Issue by pkonnov** [ecederstrand/exchangelib#865]
get a calendar item from an appointment letter
```python
def get_calendar_item(self, _id, change_key) -> CalendarItem:
    return account.calendar.get(id=_id, changekey=change_key)

mail_items = self.email_outlook().get_email_items()
for mail in mail_items:
    associated_calendar_id = mail.associated_calendar_item_id.id
    associated_calendar_ck = mail.associated_calendar_item_id.changekey
    calendar_item = self.calendar_outlook().get_calendar_item(_id=associated_calendar_id,
                                                              change_key=associated_calendar_ck)
```
if the meeting is repeated then in the future I want to get master item of the calendar or `first_occurrence` the cycle of meetings. how can I do this?

**Comment by ecederstrand** [comment]
If you have a occurrence, you can get the master item with the [recurring_master](https://ecederstrand.github.io/exchangelib/exchangelib/items/calendar_item.html#exchangelib.items.calendar_item.CalendarItem.recurring_master) method. If you have a master item, you can get occurrences via either the `first_occurrence`, `last_occurrence` or `modified_occurrences` fields, or you can get a specific occurrence using the [occurrence](https://ecederstrand.github.io/exchangelib/exchangelib/items/calendar_item.html#exchangelib.items.calendar_item.CalendarItem.occurrence) method.

**Comment by pkonnov** [comment]
I receive an email with a rescheduling of the meeting, this email contains the identifier of the calendar item from this appointment. I get this element, and call recurring_master from it and get the same element.

**Comment by ecederstrand** [comment]
Ok, then `calendar_item` may already be a recurring master? If it is, the `calendar_item.recurrence` should be non-null. Also, `calendar_item.recurring_master()` only returns a reference to the recurring master on the server. You have to call `.refresh()` on it to actually fetch the item from the server.

**Comment by pkonnov** [comment]
Maybe, but this is not the case. Calling the calendar_item.recurring_master().refresh() method returns nothing https://github.com/ecederstrand/exchangelib/blob/78f377b0a7e65e7d02fdea26350460f136f67a4b/exchangelib/items/item.py#L196
It's not entirely clear how you can get it?

**Comment by ecederstrand** [comment]
As you found out, `.refresh()` does not return anything. It just refreshes the fields on the item it is called on:

```python
master_item = calendar_item.recurring_master()
master_item.refresh()
print(master_item.recurrence)
```

**Comment by pkonnov** [comment]
Thank you!
