### ISSUE TITLE
Performance to retrieve mime_content for one email

### ISSUE THREAD

**Issue by anestors** [ecederstrand/exchangelib#869]
In the Inbox I have 1 email, body is empty, it has one attachment of type 'message/rfc822' i.e. another email.    I wish to get the mime_content for this other email.  The other email itself has 1 attachment, size 13.2Mb.  Total mime content is ~ 17.5Mb.

However it takes 3 mins 36 seconds to retrieve the email, fetch the attachment, and get the mime_content.   Is this expected performance?

```python
print(f'{datetime.datetime.now()} Start')
qs = account.inbox.all().order_by('-datetime_received')[:10] 
count = 0
for item in qs:
    count += 1
    print(f'{datetime.datetime.now()} count={count}')
    if item.has_attachments and item.attachments[0].content_type == 'message/rfc822':
        # fetch attachment (which is original email)
        orig_msg = item.attachments[0].item
        orig_msg_id = orig_msg.message_id
        print(f'{datetime.datetime.now()} retrieved orig_msg={orig_msg_id}')
        # get the mime data from original email which includes attachments
        mime_data = orig_msg.mime_content
        mime_size = len(mime_data)
        print(f'{datetime.datetime.now()} retrieved mime_data={mime_size}')
print(f'{datetime.datetime.now()} Finish')
```

Output:   
```bash
$ time python testbed.py
2021-02-19 20:13:09.900566 Connect
2021-02-19 20:13:11.992431 Start
2021-02-19 20:13:30.882724 count=1
2021-02-19 20:16:57.247902 retrieved orig_msg=<01020177bbd90646-3fc57d42-9241-4946-accd-88e56d98bdc6-000000@eu-west-1.amazonses.com>
2021-02-19 20:16:57.247940 retrieved mime_data=18069892
2021-02-19 20:16:57.248040 Finish
python testbed.py  216.72s user 0.83s system 95% cpu 3:47.94 total
```

It also uses ~ 100Mb memory while retrieving this 1 email with 13.2 Mb attachment.

I can recreate the error at will, have tried different accounts and running on different networks.

Python 3.8.7
exchangelib 3.3.2

In my real life case, it is taking longer than one day to extract mime_content for one days worth of email, which is an issue as the days mount up !

Kind regards!

**Comment by ecederstrand** [comment]
There are a couple of things you could do to improve the performance and memory usage. First, you're fetching 10 emails but possibly only using some of them. It's better to filter emails server-side so you only get the emails you need:

```python
account.inbox.filter(has_attachments=True).order_by('-datetime_received')
```

Second, you only need certain fields, so you can request only those:

```python
account.inbox.filter(has_attachments=True).only('attachments').order_by('-datetime_received')
```

The 100MB memory usage is probably due to fetching more emails than you need, and fetching more fields for each email than you need.

**Comment by anestors** [comment]
Thanks for the response and these suggestions.   I have tried them all, but I am not sure I understand the results.

In my test account I have 19 emails, each one has a single attachment with content_type = 'message/rfc822'.  This single attachment is the mime_content for a nested email, which itself may have attachments generally between 4k - 25Mb.  In the production scenario, we expect to have >1000 similar emails each day.  

However attempting to filter for only emails with attachments returns 0 rows
`qs = account.inbox.filter(has_attachments=True).order_by('datetime_received')`

Without the filter, it returns 19 rows
`qs = account.inbox.all().order_by('datetime_received')`

and then subsequently, each of these proves to have an attachment
` if item.has_attachments and item.attachments[0].content_type == 'message/rfc822'`

In terms of time taken to fetch the attachment, it seems pretty linear but taking a long time for large attachments.

![image](https://user-images.githubusercontent.com/22590017/109516406-0a3c1d80-7aa0-11eb-8d38-1d80bac18b15.png)

**Comment by ecederstrand** [comment]
Filtering on `has_attachments` should work. Anyway, if you don't want to figure out why, then at least ask for just the `attachments` field:

```python
account.inbox.all().only('attachments').order_by('-datetime_received')
```

That would still help you with memory consumption.

Regarding the slowness, it seems that you are limited by how fast the server is able to deliver the attachment content. You can see what exchangelib is doing by enabling debug logging: https://ecederstrand.github.io/exchangelib/#troubleshooting

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's anything exchangelib can do better.

**Comment by anestors** [comment]
The exchange server is AWS WorkMail.   I will open a ticket with AWS regarding poor performance to retrieve attachment data ~ 80 Kbps.

`qs = account.inbox.filter(has_attachments=True).order_by('-datetime_received')`
continues to return 0 rows.  

`qs = account.inbox.all().only('attachments').order_by('-datetime_received')`
returns all 19 items, but for every item the field item.has_attachments is False.

 I will try and diagnose using the debug logging.
