### ISSUE TITLE
ErrorCorruptData raises error in response, preventing applications from handling the error

### ISSUE THREAD

**Issue by lmverity** [ecederstrand/exchangelib#870]
Hi again!
In cases where a requested item has corrupt data, the error returned from EWS is raised in the response, and we have no chance to handle it from our application code. I solved this by adding ErrorCorruptData to the list of errors to handle in the response. The rationale was that catching the error at application level would allow the application to have the option to continue iterating through the query set and ignore the corrupted item, versus it being fatal to the query and causing the progress to abort.
Does that sound like something that you would be amenable to adding to exchangelib?
Thanks!

**Comment by ecederstrand** [comment]
Yes, that sounds entirely reasonable.
