### ISSUE TITLE
Exchange 2010 SP1: ErrorSchemaValidation - The value 'contacts:Alias' is invalid according to its datatype

### ISSUE THREAD

**Issue by aaron-blake** [ecederstrand/exchangelib#874]
Hey,

I've tried to use exchangelib with Exchange 2010 SP1 and it returned `ErrorSchemaValidation` about the field `contacts:Alias`.
I looked in [MSDN](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/fielduri), and saw that this field is supported only from Exchange 2010 SP2.

I can open a PR that will fix the issue, if you'd like.

**Comment by ecederstrand** [comment]
Thanks for reporting! I've committed a fix for `contacts:Alias`, and aligned other Contact fields that had a different Exchange version defined than the above link reports.
