### ISSUE TITLE
Porting to Go

### ISSUE THREAD

**Issue by DrGo** [ecederstrand/exchangelib#878]
Hi Eric and everyone,
I am not a python programmer, but by browsing through your repo I believe your lib is well-designed and well-documented. 
Do you know of a similar lib for c, c++ or go?
I am trying to gather the courage to create a similar lib in go. Any thoughts on possible challenges?
I see an issue about upgrading to using MSAL #749. How far are you in that process?

Many thanks for your time,

/salah

**Comment by ecederstrand** [comment]
I don't know of similar packages in other languages, but I haven't researched, either. You're free to take whatever you want from this project and translate to a Go equivalent :-) I don't have any experience with Go, but I assume that it would be entirely possible to do. There's nothing this package does that is somehow Python-specific. The only obstacle is that it's 18.00 lines of fairly optimized code that needs to be translated.

Re #749, I don't have an urgent need for it myself, and I'm not working on it.

**Comment by DrGo** [comment]
Thanks for the tips, Eric,

**Comment by geoffblack** [comment]
> If I were to start this project today, I would probably base it on the Graph API instead. EWS is a legacy API. That's nice when you have clients running old Exchange versions that don't support the Graph API, but it's not sustainable in the long run.

I'll note, if this matters to anyone, that In-Place Archive Mailboxes in Exchange Online/Microsoft 365 are currently only available via EWS and not Graph. Graph initially supported them, but the Graph team removed access in April 2020 and it hasn't returned.
