### ISSUE TITLE
Differences between account.root in 3.3.2 vs 4.1.0

### ISSUE THREAD

**Issue by RossK1** [ecederstrand/exchangelib#879]
Hi,

We have been using exchangelib==3.3.2 to move and save emails using the following code to specify the email based on its ID:
`item = account.root.get(id=email_id)`

When upgrading to exchangelib==4.1.0, however, the above code no longer works, it instead throws an error that NoneType has no attribute get. Was the nature of account.root and how items are specified changed between these two versions?

What is the correct way to specify items (emails or calendar items) in 4.1.0?

Thanks :)

**Comment by ecederstrand** [comment]
This is unexpected.

I cannot see how the `account.root` property could possibly return anything else than a folder instance, or throw an exception. It's also a very well-tested path in the test suite, and I cannot reproduce locally.

I would suggest to break out a debugger and find out what's going on. Also, you could [enable debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and compare what exchangelib is doing in 3.3.2 versus 4.1.0.

**Comment by RossK1** [comment]
@ecederstrand thanks for the prompt reply. Upgraded to 4.1.0 on other machines and they do not show the account.root.get NoneType error. I suspect it must be some sort of permission issue on that one machine.
Regardless, does not appear to be a bug, so closing the issue :)

**Comment by ecederstrand** [comment]
Glad to hear. Feel free to reopen if this pops up again.
