### ISSUE TITLE
NewMailEvent missing all metadata

### ISSUE THREAD

**Issue by InvncibiltyCloak** [ecederstrand/exchangelib#884]
**Describe the bug**
NewMailEvents are returned without `item_id`, `parent_folder_id` or `timestamp` on them making it difficult to find which item triggered the event. 

**Expected behavior**
NewMailEvents should have these metadata fields parsed and attached to the object.

**Proposed Solution**
`NewMailEvent` should inherit from `TimestampEvent` instead of `Event` so these fields are parsed.

**Additional context**
MSDN: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/newmailevent

**Comment by InvncibiltyCloak** [comment]
PR in progress

**Comment by ecederstrand** [comment]
I believe this was also fixed in https://github.com/ecederstrand/exchangelib/pull/883. Thanks!
