### ISSUE TITLE
facing issue in mail filter queryset with subject keyword

### ISSUE THREAD

**Issue by msavkar** [ecederstrand/exchangelib#885]
filter queryset result:  QuerySet(q=isRead:False AND Subject:(qateam OR act AND net OR lts AND newtest OR act OR Approval), folders=[Messages (test)])

Issue: We are not able to filter mail with Subject name as qateam.
With modernauth same queryset it is working as expected but with basic auth  we are unable to filter mails.

**Comment by ecederstrand** [comment]
Are you saying that filtering works with one authentication method, but not the other? I can't imagine how that could happen.

What do you mean by "not able to filter mail". Do you get an error message, or just an empty result?

**Comment by ecederstrand** [comment]
Closing due t inactivity. Feel free to reopen if you get back to this issue.
