### ISSUE TITLE
Occasional hanging when initializing Account

### ISSUE THREAD

**Issue by scottmsul** [ecederstrand/exchangelib#889]
We found that some of our scripts were hanging perpetually when sending notification emails, and I did some digging to figure out why. I wrote some wrapper code to print the stacktrace whenever it detected a hung job. I've copied the relevant part of the stack trace below:
```
  File "D:\batch\tasks\workitems\rt-analysis-nextera-CSWS_RSPA_RUSHSPRWNDA\job-8407\sjt\wd\ops-release-8dd4632db1a7412db1b58997940055ce\batterysimm_ops\notifications.py", line 151, in _notify
    account = Account(primary_smtp_address='no-reply@ascendanalytics.com', config=email_config, autodiscover=False, access_type=DELEGATE)
  File "C:\Program Files\Python37\lib\site-packages\exchangelib\account.py", line 97, in __init__
    self.version = self.protocol.version
  File "C:\Program Files\Python37\lib\site-packages\exchangelib\protocol.py", line 419, in version
    self.config.version = Version.guess(self, api_version_hint=self._api_version_hint)
  File "C:\Program Files\Python37\lib\site-packages\exchangelib\version.py", line 232, in guess
    if not protocol.version.build:
  File "C:\Program Files\Python37\lib\site-packages\exchangelib\protocol.py", line 416, in version
    with self._version_lock:
```
It seems stuck while calling the `Account` function.

Another interesting piece of information is that this doesn't happen often (around once per week among thousands of emails), but when it does it happens across multiple independent jobs at the same time. Maybe there's a timeout happening in an http request somewhere due to a briefly down service?

I'm using version 3.1.1, so it's possible this has already been fixed.

**Comment by ecederstrand** [comment]
This deadlock happens because we attempt to acquire `_version_lock` twice. That's a bug.

This is the part of exchangelib that tries to guess which Exchange version the server is running. Due to garbled headers or error messages form the server, we can't guess the version in some cases. There's a code path where we try again, and end up taking the lock twice.

**Comment by ecederstrand** [comment]
The referenced commit should fix the deadlock. You'll probably get an exception instead when you end up in the situation you described, but that's at least better than a deadlock.

**Comment by ecederstrand** [comment]
@scottmsul Did the patch fix your issue?

**Comment by ecederstrand** [comment]
Assuming this is fixed by the patch. Feel free to reopen if you still have issues with this.
