### ISSUE TITLE
Support answering meeting invitations

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#89]
The `exchangelib.folders.Meeting*` classes do not allow answering a meeting request. This would be a nice enhancement. A good start would be to add `accept()` and `decline()` methods to `exchangelib.folders.MeetingRequest`.

Testing requires at least two accounts on the test server because you can't invite yourself to a meeting.

**Comment by sedemmler** [comment]
Just mentioning it in the appropriate thread this time: I'll take a stab at this one.

**Comment by MartinThoma** [comment]
I'm not sure if this is the same issue: Is it possible to get a list of who accepted / declined an event?

**Comment by ecederstrand** [comment]
@MartinThoma This should be possible by looking at the ResponseType of the attendees on a `CalendarItem`. See a C# example in https://msdn.microsoft.com/en-us/library/office/dd633669(v=exchg.80).aspx

**Comment by frennkie** [comment]
I think this would be very useful!

> The exchangelib.folders.Meeting* classes do not allow answering a meeting request. This would be a nice enhancement. A good start would be to add accept() and decline() methods to exchangelib.folders.MeetingRequest.

Just to make sure: You are referring to `exchangelib.items.MeetingRequest`, right?!

**Comment by ecederstrand** [comment]
`exchangelib.items.MeetingRequest` would be the correct location.
