### ISSUE TITLE
Account initialisation took around 40 secs to raise the error when using wrong service_endpoint in Configuration

### ISSUE THREAD

**Issue by manu624** [ecederstrand/exchangelib#891]
**Describe the bug**
I have observed if i use the combination. of wrong port number and correct domain name in service_endpoint in Configuration , Account initialisation hangs on for more than 40 secs

if domain name is not correct it gives  quick response(raises ConnectionError) 

below logs may help 

```
2021-04-08 11:05:52,816, ERROR, 15404, exchangelib.util, util.post_ratelimited:827, Retry: 0
Waited: 10
Timeout: 5
Session: 24227
Thread: 13002502144
Auth type: <requests_oauthlib.oauth2_auth.OAuth2 object at 0x7f8cca479630>
URL: https://domain_name:port_value/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f8cca5ae940>
Allow redirects: False
Streaming: False
Response time: 30.211992832999385
Status code: 503
Request headers: None
Response headers: {'TimeoutException': ConnectionError(MaxRetryError("HTTPSConnectionPool(host='outlook.office365.com', port=442): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8cde7e1358>: Failed to establish a new connection: [Errno 51] Network is unreachable',))",),)}
```

**To Reproduce**
Use the correct Domain name and incorrect port number, make service_endpoint use this in Configuration and try to initialise an account

**Comment by ecederstrand** [comment]
This is expected. `exchangelib.protocol.BaseProtocol.TIMEOUT` sets the default timeout when the server does not respond. It has a default value of 120 seconds.

When the hostname either does not resolve in DNS, or is not an Exchange server and thus does not respond in a way we expect, we are able to raise exceptions earlier than the timeout. But in the case of a wrong port, the server simply does not respond, and we give up when we reach the timeout value.

You can set `BaseProtocol.TIMEOUT` to something else if you want a different timeout.

**Comment by ecederstrand** [comment]
Actually, I just noticed that it looks like you already set a timeout of 5 seconds. It's possible that this only happens when you are using OAuth2 authentication. It looks like we're not passing on the timeout setting to the `OAuth2Session.fetch_token()` method. The referenced commit should fix that.

**Comment by ecederstrand** [comment]
@manu624 Does the referenced patch make any difference for you?

**Comment by ecederstrand** [comment]
Assuming this is fixed by the patch. Feel free to reopen if you still have issues with this.
