### ISSUE TITLE
Encoding Error .save()

### ISSUE THREAD

**Issue by ipercyNC** [ecederstrand/exchangelib#892]
Getting this error when trying to mark an email as read and save it. 
`UnicodeEncodeError: 'charmap' codec can't encode character '\u30fb' in position 1237: character maps to <undefined>
Call stack:
  File "-------", line 514, in <module>
    input_destination_base_source)
  File "-------", line 257, in search_email
    email.save()`

It is interesting because I haven't seen this error. It seems to be only coming from the save() function when attempting to update items. What would be the correct fix for this? Py isn't letting me catch the UnicodeEncodeError 
exchangelib==3.3.2
Python 3.7.9

**Comment by ecederstrand** [comment]
I'll need the full stack trace and some example code to be able to reproduce this.

Also, `UnicodeEncodeError` should be perfectly valid in an except clause:

```python
>>> try:
...     '\u30fb'.encode('ascii')
... except UnicodeEncodeError:
...     print('Error')
... 
Error
```

**Comment by ipercyNC** [comment]
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python\lib\logging\__init__.py", line 1028, in emit
    stream.write(msg + self.terminator)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u30fb' in position 1236: character maps to <undefined>
Call stack:
  File "-----", line 546, in <module>
    input_destination_base_source)
  File "-----", line 264, in search_email
    email.save()
  File "C:\Python\lib\site-packages\exchangelib\items\item.py", line 101, in save
    send_meeting_invitations=send_meeting_invitations
  File "C:\Python\lib\site-packages\exchangelib\util.py", line 38, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Python\lib\site-packages\exchangelib\items\item.py", line 189, in _update
    expect_result=message_disposition != SEND_AND_SAVE_COPY,
  File "C:\Python\lib\site-packages\exchangelib\services\common.py", line 93, in get
    res = list(self.call(**kwargs))
  File "C:\Python\lib\site-packages\exchangelib\services\common.py", line 550, in _pool_requests
    for elem in self._get_elements(payload=payload_func(chunk, **kwargs)):
  File "C:\Python\lib\site-packages\exchangelib\services\update_item.py", line 178, in get_payload
    log.debug('Updating item %s fields %s', item, fieldnames)
Message: 'Updating item %s fields %s'
```
Stack for you. The email I am scanning is being forwarded, but that hasn't been an issue for me in the past. 

You'd think that it should catch the error... but it still gets thrown. Here is the shortened version of my loop, but it still outputs the UnicodeEncodeError to stderr
```	
try:
   for email in target_folders:
	if isinstance(email, Message):
			email.is_read = True
			email.save()
except UnicodeEncodeError as e:
		------
```

**Comment by ecederstrand** [comment]
Ah, ok. You can't catch the error because it's not thrown. It's printed by the Python logging module.

I'm guessing you're logging to a file and have set up your logging incorrectly. Here's an example of the same problem, and a solution: https://github.com/KBNLresearch/iromlab/issues/55

**Comment by ipercyNC** [comment]
Great I will give that a shot. Thank you!
