### ISSUE TITLE
New exchangelib release?

### ISSUE THREAD

**Issue by mautomic** [ecederstrand/exchangelib#896]
Hi @ecederstrand, 

Are there plans to cut a new release soon? Our application is utilizing the sync_items() implementation, and we're running into #882, which we noticed was merged in after the last release 4.1.0. Seems like there have been some other useful commits as well since then.

Thanks for the awesome library!

**Comment by ecederstrand** [comment]
Sure! I just had som last tings I wanted to get in, but here you go: https://github.com/ecederstrand/exchangelib/releases/tag/v4.2.0
