### ISSUE TITLE
Open other user’s mailbox?

### ISSUE THREAD

**Issue by cpach** [ecederstrand/exchangelib#899]
**Is your feature request related to a problem? Please describe.**

Sometimes, system administrators have the need to open the mailbox of another user.

**Describe the solution you'd like**

Is it possible for an Exchange Admin or Domain Admin to use exchangelib in order to see the contents of another user’s mailbox?

If so, does the admin only need to provide their own credentials via a Credentials object or do they first need to somehow delegate permission for the mailbox in question?

**Describe alternatives you've considered**

An alternative could be to use OWA.

**Additional context**

–

**Comment by ecederstrand** [comment]
If the connecting user has delegate or impersonation access to the mailbox you want to connect to, you can access that account using exchange. See the options for connecting to other accounts at https://ecederstrand.github.io/exchangelib/#setup-and-connecting

**Comment by ecederstrand** [comment]
Closing since I don't think there's anything to improve in exchangelib. Feel free to reopen if you think otherwise.
