### ISSUE TITLE
Configuration needs an option to ignore ssl certificate verification

### ISSUE THREAD

**Issue by kevin-chen-bcgdv** [ecederstrand/exchangelib#9]
As the title, it's better to have a parameter to turn off the ssl verify. Thanks

**Comment by ecederstrand** [comment]
I'm +0 on this. From a security and foot-shooting perspective, I think it's better to add the untrusted certificate to the trust store of the host. It's not a big change, though.

**Comment by xmkevinchen** [comment]
@ecederstrand I have not chance, cause some situation I'm facing. I forked and modified for my requirement, I will create a pull request later

**Comment by ecederstrand** [comment]
`autodiscover.discover()` and `configuration.Configuration` now have optional `verify_ssl` attributes. Can you please test?

**Comment by xmkevinchen** [comment]
I got pulled out for days, thanks @ecederstrand

**Comment by ecederstrand** [comment]
I merged your PR with the remaining fixes. Thanks!

**Comment by soser1488** [comment]
> `autodiscover.discover()` and `configuration.Configuration` now have optional `verify_ssl` attributes. Can you please test? I can't easily test failing SSL handshakes on my test server.

how it should look

**Comment by ecederstrand** [comment]
This flag is deprecated. Custom TLS validation is documented in https://github.com/ecederstrand/exchangelib#proxies-and-custom-tls-validation
