### ISSUE TITLE
Add OAuth support

### ISSUE THREAD

**Issue by ecederstrand** [ecederstrand/exchangelib#90]
Newer Exchange versions support OAuth authentication: https://msdn.microsoft.com/en-us/library/office/dn626019(v=exchg.150).aspx

Our low-level transport methods should support this.

**Comment by vikramarsid** [comment]
@ecederstrand will exchangelib also support kerberos authentication ?

**Comment by ecederstrand** [comment]
It's not a planned feature, and I have no way to test it ATM, but I would happily accept it as a contribution.

**Comment by AlJohri** [comment]
@ecederstrand do you know how this might work with single sign on? We use [Okta](https://www.okta.com/) to sign into Office 365. I haven't found any good documentation on how this works

**Comment by ecederstrand** [comment]
No, sorry. I have no idea how login via 3rd parties would work via EWS.

**Comment by janscas** [comment]
Hi basic auth on O365 is going to be deprecated starting on 1 November 2018. Hope Oauth implementation gets it before basic auth deprecation.

**Comment by ecederstrand** [comment]
Hi @janscas. Thanks for the heads-up!

**Comment by emorikawa** [comment]
@janscas What's your source for the basic auth deprecation for EWS on O365. We found this article (https://blogs.msdn.microsoft.com/deva/2017/12/13/office-365-devs-deprecation-of-outlook-rest-api-v1-0/) which is specifically about the defunct Outlook REST APIs as they try and transition to the Graph API. I believe the EWS infrastructure for Exchange Online as bundled in Office 365 may be different?

**Comment by janscas** [comment]
Well, basic auth is not working with microsoft graph, and as stated here, will no longer be valid with the office365 api on November first 2018:

> Version 1.0 of the Outlook REST API is being deprecated. Beginning November 1, 2018, apps will no longer be able to use Basic Authentication with the v1.0 REST endpoint (https://outlook.office.com/api/v1.0). By November 1, 2019, the v1.0 REST endpoint will be fully decommissioned, and the v1.0 documentation will be removed shortly afterwards. Start migrating your app to use Outlook REST API in v1.0 of Microsoft Graph. See more details in our announcement.

https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations

**Comment by janscas** [comment]
@emorikawa and Outlook REST API v2.0 is also not supporting basic auth

**Comment by ecederstrand** [comment]
This still only mentions the REST API. There's no mention of EWS (which is a SOAP API), as far as I can see, and I'm not sure they're related in any way.

**Comment by cranbar** [comment]
Basic authentication will be disabled in EXO on 10/13/2020:

https://redmondmag.com/articles/2018/07/10/basic-authentication-and-exchange-web-services.aspx

At that point, OAuth will be required to connect to EXO.

**Comment by spmsh** [comment]
Hi, this is me again, (I've left a comment in the PR 355). 

Are you progressing on OAuth authentication support ? 

Your lib is awesome, and I've been doing some quick (and dirty?) tweaks and managed to authenticate on Office 365 with an account using OAuth2. 

Basically, I have an OAuth mechanism on the side that gets me an access token (with all the other stuff that I save).  This is a "standard" OAuth auth with O365.

Then I've created a new class that inherits from requests.auth.AuthBase on which I simply modified the Authorization header from 'Basic xxxxxxxx' to 'Bearer access token', and that works.

Hope this helps.

**Comment by frennkie** [comment]
I would be highly interested too..! :-D

**Comment by cranbar** [comment]
I'm working on a PR for this, @ecederstrand.  Requests-OAuthlib is what I'm using:

https://requests-oauthlib.readthedocs.io/en/latest/index.html

**Comment by ecederstrand** [comment]
That's really cool, @cranbar ! I'd be happy to answer questions and review code once you get there.

**Comment by marcfro** [comment]
@spmsh do you have any example code you can share using OAuth token to connect?  I'm working on this right now using [Python Social Core](https://github.com/python-social-auth/social-core) to get the access token.  I got this working for O365 but I need a version for both )365 and for Exchange individually and its not exactly clear what the differences are (if there are any, Microsoft docs are not very clear).

It looks like you have to request the token and scope using a different RESOURCE.  Any help would be greatly appreciated!

**Comment by spmsh** [comment]
Hi Guys, sorry, I kind of missed your previous ping on this thread. 

See below how I managed to get OAuth working with Office 365. I'm simplifying the code a bit.
Note: for Exchange on-premise, I'm using the NTLM auth from ecederstrand instead.

First, I'm not detailing how you get the token from O365 but just that you would need to create a model to store the oauth token, it could be as simple as below. How to get the token is pretty standard OAuth. I'm using requests.auth lib.

```
class OAuthToken(db.Model):
    __tablename__ = "oauth_token"
    id = db.Column(db.Integer, primary_key=True)
    access_token = db.Column(db.String, nullable=False)
    refresh_token = db.Column(db.String, nullable=False)
    expires_on = db.Column(db.DateTime, nullable=False)
    user_email = db.Column(db.String, index=True, unique=True, nullable=False)
    token_type = db.Column(db.String)
    resource = db.Column(db.String)
    scope = db.Column(db.String)

    @property
    def token(self):
        if self.expires_on > datetime.utcnow():
            return self.access_token
        else:
            from app.auth.oauth import datetime_from_timestamp, refresh_oauth_token
            token = refresh_oauth_token(self.refresh_token)
            self.access_token = token['access_token']
            self.refresh_token = token['refresh_token']
            self.expires_on = datetime_from_timestamp(token['expires_on'])
            db.session.add(self)
            db.session.commit()
            return self.access_token
```

Second step, I modified transport.py AUTH_TYPE_MAP to add OAUTH as the following:
```
# Authentication method enums
NOAUTH = 'no authentication'
NTLM = 'NTLM'
BASIC = 'basic'
DIGEST = 'digest'
GSSAPI = 'gssapi'
OAUTH = 'OAuth'

AUTH_TYPE_MAP = {
    NTLM: requests_ntlm.HttpNtlmAuth,
    BASIC: requests.auth.HTTPBasicAuth,
    DIGEST: requests.auth.HTTPDigestAuth,
    OAUTH: HTTPOAuthAuth,
    NOAUTH: None,
}
```
OAuth is of HTTPOAuthAuth which is also a class that I have added for that purpose. Note the important part is to add the Bearer + token in the header of your http requests. This is where we pass the Oauth token in each request.
```
from requests.auth import AuthBase
class HTTPOAuthAuth(AuthBase):
    def __init__(self, token):
        self.token = token

    def __eq__(self, other):
        return all([self.token == getattr(other, 'token', None)])

    def __ne__(self, other):
        return not self == other

    def __call__(self, r):
        r.headers['Authorization'] = 'Bearer ' + self.token
        return r
```
Once this is done, and you got the token for your user, to use EWS with O365 using that OAuth token:
```
credentials = ServiceAccount('', '', token=token) # empty user/password is fine here
config = Configuration(server=ews_server, credentials=credentials, auth_type='OAuth') # type is OAuth here
account = Account(primary_smtp_address='user@email.net', config=config, autodiscover=False, access_type=DELEGATION)
```

Hope this helps get you a better view on this. 

Thanks and keep the good work !

**Comment by Ueland** [comment]
I'l piggyback on spmsh's comment here. Any new updates on this issue with regards to getting it into this project?

**Comment by ecederstrand** [comment]
I’m not working on it actively and I have no Way of testing. I’d be happy to review a PR collecting the advice above.

**Comment by ecederstrand** [comment]
Can I get somebody to test #630? I can't test OAuth myself, unfortunately.

Also, I would like somebody to have a loak at my question at https://github.com/ecederstrand/exchangelib/pull/601#issuecomment-523440183
