### ISSUE TITLE
How can I get some folders by folder names? 

### ISSUE THREAD

**Issue by kmsshdxf** [ecederstrand/exchangelib#900]
I want to get the wanted folders by using the folder names rather then looping in all folders.

I have used the filter method when extracting items in one folder.

So I wonder if there are some similar ways to do this? Have searched some major py files, but not found.

Thanks.

**Comment by ecederstrand** [comment]
You can navigate to folder by name using slash or double-slash notation. See https://ecederstrand.github.io/exchangelib/#folders

**Comment by ecederstrand** [comment]
Closing since I don't think there's anything to improve in exchangelib for this issue. Feel free to reopen if you think otherwise.
