### ISSUE TITLE
Can we get regional timezone of mailbox using exchangelib

### ISSUE THREAD

**Issue by hjain371** [ecederstrand/exchangelib#903]
this is needed to to generate some response time statistics ,please refer below document
https://docs.microsoft.com/en-us/powershell/module/exchange/get-mailboxregionalconfiguration?view=exchange-ps

**Comment by ecederstrand** [comment]
I can't find any documentation that this is available directly in EWS, but according to https://gsexdev.blogspot.com/2015/11/finding-timezone-being-used-in-mailbox.html the mailbox timezone *may* be available in a user configuration XML document on the calendar folder.

User configurations are supported by exchangelib so you could try that out and let us know what you find out.

**Comment by ecederstrand** [comment]
I actually do get something useful when I do:

```python
config = a.calendar.get_user_configuration('WorkHours')
print(config.xml_data.decode('utf-8'))
```

which outputs:

```xml
<Root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="WorkingHours.xsd">
	<WorkHoursVersion1>
		<TimeZone>
			<Bias>-60</Bias>
			<Standard>
				<Bias>0</Bias>
				<ChangeDate>
					<Time>03:00:00</Time>
					<Date>0000/10/05</Date>
					<DayOfWeek>0</DayOfWeek>
				</ChangeDate>
			</Standard>
			<DaylightSavings>
				<Bias>-60</Bias>
				<ChangeDate>
					<Time>02:00:00</Time>
					<Date>0000/03/05</Date>
					<DayOfWeek>0</DayOfWeek>
				</ChangeDate>
			</DaylightSavings>
		</TimeZone>
		<TimeSlot>
			<Start>08:00:00</Start>
			<End>17:00:00</End>
		</TimeSlot>
		<WorkDays>Monday Tuesday Wednesday Thursday Friday</WorkDays>
	</WorkHoursVersion1>
</Root>
```

As often with Microsoft timezones, this leaves you not much wiser, but at least I can see that this contains a CET/CEST timezone definition.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you have additional issues with this.

**Comment by hjain371** [comment]
Hi,
Thanks for sharing this but I am still getting time error fetching the details, can you please help me creating the account correctly.
I am using exchangelib 3.3.2 version, I am getting below error while fetching user configuration:

config = account.calendar.get_user_configuration('WorkHours')

----> 1 config = account.calendar.get_user_configuration('WorkHours')
AttributeError: 'Calendar' object has no attribute 'get_user_configuration'

below is the code I am using to create the account:
cred = Credentials(username=username, password=password)
config = Configuration(server=server, credentials=cred, auth_type="NTLM")
account = Account(primary_smtp_address=email_id, autodiscover=False,
                       config=config, access_type=DELEGATE)

email_id is the shared mailbox email id and server is outlook.(--my organization--).net

Should I have to change some config setting to bind calendar user config to it?
