### ISSUE TITLE
Filter  to restrict particular email domain from sender.The existing filter contains is not working to filter  

### ISSUE THREAD

**Issue by ahalyarekha** [ecederstrand/exchangelib#904]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
If this is concerns missing functionality from EWS, please provide links to this feature in MSDN.

**Comment by ecederstrand** [comment]
It seems filtering on partial sender email address does not always work on the Exchange server. See https://github.com/ecederstrand/exchangelib/issues/854

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think exchangelib can do anything to fix this issue.
