### ISSUE TITLE
How to exclude specific domain emails while reading it from exchange server via Exchangelib library 

### ISSUE THREAD

**Issue by manojkumar-seemakurthi** [ecederstrand/exchangelib#905]
How to exclude specific domain emails while reading it from exchange server via Exchangelib library 

For example , I would like to exclude emails which contain @gmail.com and @yahoo.co.in while reading email from Exchangelib 

I'm using below code snippet to exclude above 2 domain related emails , but its not working 

Please help me to find the solution  for this issue 

Thanks in advance 

```
from exchangelib import Credentials, Account , DELEGATE , Q

credentials = Credentials('test@example.com', 'topsecret')
account = Account('test@example.com', credentials=credentials, autodiscover=True, access_type  = DELEGATE)

query = Q(sender_contains = '@gmail.com') | Q(sender_contains = '@yahoo.co.in') 
recent_mails = account.inbox.filter(~query).order_by('-datetime_received')[:100] 

for item in recent_mails:
    print(item.subject, item.sender, item.datetime_received)

```

**Comment by ecederstrand** [comment]
It seems filtering on partial sender email address does not always work on the Exchange server. See https://github.com/ecederstrand/exchangelib/issues/854

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think exchangelib can do anything to fix this issue.
