### ISSUE TITLE
Running queries while in streaming mode does not work

### ISSUE THREAD

**Issue by gidnoot** [ecederstrand/exchangelib#906]
The goal is to get the email adres that couldn't be reached so I can inform the person that is responsible to fix it.

What I tried:
I received NDR (non-delivery reports) by streaming my mailbox. At that point I have the id and changekey from that item. Next thing I tried is to get the Message object by using the inbox .get() function together with the id I have but then the program just freezes and never comes with the Message object. Not even an error or time-out.

Anyone knows how to get the body text of an incoming NDR message?

**Comment by ecederstrand** [comment]
Can you please post the code you're trying to run? Preferably a minimal example that shows the problem.

**Comment by gidnoot** [comment]
```python
def stream_ndr_mails(self):
    self.p_account = login()
    while True:
        # Create a streaming subscription
        subscription_id = self.p_account.inbox.subscribe_to_streaming()

        # Stream events from the server
        for notification in self.p_account.inbox.get_streaming_events(subscription_id, connection_timeout=20):
            for event in notification.events:
                if isinstance(event, NewMailEvent):
                    item_id = event.item_id
                    self.cur_mail = self.p_account.inbox.get(id=item_id.id, changekey=item_id.changekey)
                    if self.cur_mail.subject.startswith('Onbestelbaar: LABS Alert'):
                        self.forward_rebound_mail()
        self.p_account.inbox.unsubscribe(subscription_id)
```

**Comment by ecederstrand** [comment]
Cool that you're trying out the new subscribe/notification code!

Which messages do you see in the debug log?

This could be because exchangelib is trying to reuse the same streaming connection that `get_streaming_events()` already has open to get the items. What happens if you collect the item IDs and do the `.get()` calls after `unsubscribe()`? I know it's probably not a viable solution, so it's just a test of the theory.

Another thing you could try is raising the `max_connection` value to 2 or more. See https://ecederstrand.github.io/exchangelib/#optimizing-connections That may allow the `.get()` call to use another connection than the streaming connection.

**Comment by gidnoot** [comment]
It works when I do the .get() call after unsubscribe(). Will also try the max_connection solution

**Comment by gidnoot** [comment]
max_connection doesn't work. I tried to create another account but that also doesn't work. I now have it working by creating a new process that will process the message further.

**Comment by ecederstrand** [comment]
Ok, it makes perfectly sense that a new process would also solve this. Thanks for the investigation.

I think this should either work out of the box or raise an exception. I'll see if I can reproduce this in a test case and find a solution.

**Comment by ecederstrand** [comment]
Should be fixed with the referenced commit. You still need to raise the `max_connection` value to allow more than one connection.

I also added a context manager that handles unsubscribing on exit:

```python
with self.p_account.inbox.streaming_subscription() as subscription_id:
    # Do something with the subscription
    
```
