### ISSUE TITLE
Best way to create an instance of Message for testing?

### ISSUE THREAD

**Issue by gustavwennerblom** [ecederstrand/exchangelib#91]
Hi,
(Pretty new to this library so please excuse the probably very basic question)

What is the best/recommended way of creating an instance of the Message class to use for testing? I'm getting stuck at the fact that instancing the class requires an Account, which requires Credentials etc...

Cheers,
Gustav

**Comment by ecederstrand** [comment]
A `Message` is not supposed to require an account until it's actually needed:

```python
from exchangelib import Message
m = Message(subject='foo')
```
If you're running into specific issues, please post your test code and output.

**Comment by gustavwennerblom** [comment]
Obviously when reading again.... Thanks for a great package!
