### ISSUE TITLE
Issue with MITM certs and access to O365

### ISSUE THREAD

**Issue by sdeshpande** [ecederstrand/exchangelib#912]
Hi All,

Our company does SSL Decryption of all outgoing traffic. For doing this they have installed a self signed SSL cert on all computers and servers in our environment. This SSL cert is created and served on Palo Alto firewall.
When I try to connect to Office365 using exchangelib, I am getting below error. 
`exchangelib.errors.TransportError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/Exchange.asmx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))`

Can someone please guide me on how I can workaround this issue. 

I read from previous posts, we can create custom RootCAAdapter class but I am not sure how to get the pem file for the cert. 
Can someone please assist ?

Regards,
Saurabh

**Comment by ecederstrand** [comment]
I think this question is better directed at the [requests](https://docs.python-requests.org/en/master/index.html) package since exchangelib relies on it for SSL validation and certificate support.

**Comment by RandallLasini** [comment]
@sdeshpande the main issue is that your company has deployed the SSL inspection certification into your OS/Browsers Keystore, and python like Java and many other languages does not natively support Microsofts key store.

If your company have a support area that manages the deployment of these types of languages/environments (for example via SCCM packages) then you should approach that area to develop the minor update (below) with amended Certificate store so they can deploy it to all users/environments.

The best solution I ever found was here on how to update the CA. 

https://incognitjoe.github.io/adding-certs-to-requests.html

Its important to note, that SSL inspection should be considered an environmental behavior, and not specific to exchangelib, as such the solution should be for the entire python process, not just for this package.

**Comment by sdeshpande** [comment]
Thank you. I will reach out to them today and will update back here.

**Comment by sdeshpande** [comment]
> 
> 
> @sdeshpande the main issue is that your company has deployed the SSL inspection certification into your OS/Browsers Keystore, and python like Java and many other languages does not natively support Microsofts key store.
> 
> If your company have a support area that manages the deployment of these types of languages/environments (for example via SCCM packages) then you should approach that area to develop the minor update (below) with amended Certificate store so they can deploy it to all users/environments.
> 
> The best solution I ever found was here on how to update the CA.
> 
> https://incognitjoe.github.io/adding-certs-to-requests.html
> 
> Its important to note, that SSL inspection should be considered an environmental behavior, and not specific to exchangelib, as such the solution should be for the entire python process, not just for this package.

This is it. Thank you for the assisting in this. I no longer need to ignore SSL and everything works as expected. Thank you very much !!!
