### ISSUE TITLE
SearchableMailboxes

### ISSUE THREAD

**Issue by imad777550** [ecederstrand/exchangelib#917]
Hello, can you add searchableMailboxes feature with a specific subject?

**Comment by ecederstrand** [comment]
I'm not sure exactly what you're asking for. The `GetSearchableMailboxes` service is already supported via the `Protocol.get_searchable_mailboxes()` method. See https://ecederstrand.github.io/exchangelib/#non-account-services

**Comment by imad777550** [comment]
No I'm using GetSearchableMailboxes without problems. I'm asking for searchableMailboxes in order to delete some emails based on a specific subject with these mailboxes or get forwarding rules. I know that all these features are supported in "pyews" but it is not working for me.
Thank you.

**Comment by ecederstrand** [comment]
Can you link to some documentation describing this? I can't find any EWS service called `searchableMailboxes`.

**Comment by imad777550** [comment]
I'm sorry the service is called SearchMailboxes.
here's the link https://github.com/swimlane/pyews

**Comment by ecederstrand** [comment]
Ah, that one. It's described here: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/searchmailboxes-operation but the documentation says it's deprecated and that you should use the `FindItem` service instead which exchangelib does support. Is there anything you can't do with `FindItem`?

**Comment by imad777550** [comment]
![image](https://user-images.githubusercontent.com/71044702/118728431-d4a40680-b83c-11eb-81e5-464d0d6e2c4a.png)

Can I GetInboxRules, Delete emails from searchable mailboxes? like the documentation in pyews?
Can I do this with FindItem using python?

**Comment by imad777550** [comment]
I did not find "FindItem" in exchangelib python documentation.
https://ecederstrand.github.io/exchangelib/

**Comment by ecederstrand** [comment]
`DeleteItem` is supported. `GetInboxRules` is not, and tracked in https://github.com/ecederstrand/exchangelib/issues/233. At a glance, `FindHiddenInboxRules` is a custom method in pyews that uses `FindItem` and some extended properties. `ResolveNames` is supported.

**Comment by ecederstrand** [comment]
`FindItem` is implemented here: https://github.com/ecederstrand/exchangelib/blob/master/exchangelib/services/find_item.py but wrapped more nicely in the QuerySet syntax that exchangelib supports.

**Comment by imad777550** [comment]
Thank you for your help.
I am an information security consultant and I want to implement a use case for phishing.
I want to ask some questions in order to implement this.

![image](https://user-images.githubusercontent.com/71044702/118729954-77f61b00-b83f-11eb-9635-6773cc73c19b.png)
Is this script working? and where is the "s" object?

By the way, I am using DeleteItem and ResolveName property without any problem.
My goal is to find an email with a specific subject in all mailboxes and delete it from all mailboxes. For sure I will be logging in from a high priviledge account.
![image](https://user-images.githubusercontent.com/71044702/118730325-16827c00-b840-11eb-983e-050701510ea0.png)

The problem about DeleteItem is that it will delete an email from a specific mailbox and not all searchable mailboxes

Can you provide me a small python if this can be done?

Thank you and appreciate what you've done with exchangelib.

**Comment by ecederstrand** [comment]
Inbox rules are not yet implemented, so the above script is just an example of how it *could* work in exchangelib.

You can search multiple folders using the ParentFolderIds element in FindItem: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/finditem-operation but I'm not sure if it works with folders from different mailboxes.

The equivalent in exchangelib would be to collect the folders you want to search in a `FolderCollection` object and use the QuerySet syntax on that. I don't have a multi-account test system I can test with to verify, though.

Unless you have a huge list of mailboxes, I would just process them individually.

**Comment by ecederstrand** [comment]
I'm closing this is issue because inbox rules are tracked in a different issue, and since the `SearchMailboxes` service is deprecated I'm not sure it's worthwhile to add it at this point.
