### ISSUE TITLE
How to uniquely identify whether email is forwarded or not?

### ISSUE THREAD

**Issue by ahalyarekha** [ecederstrand/exchangelib#918]
I don't see how to uniquely identify the email in mailbox is forwarded.My requirement is to identify the forwarded emails( I see subject appended with FW:) I am looking for email attribute to identify the forwarded email. Thanks

**Comment by ecederstrand** [comment]
A forwarded email is not different from any other email. It's just a convention to prepend forwarded email subjects with `FW:`, just like replies are normally prepended with `Re:`.

Some email systems may tell you anyway, in the email headers. Those are accessible via the `headers` field.

**Comment by ecederstrand** [comment]
There are some suggestions at https://stackoverflow.com/questions/32718758/ews-determine-if-an-e-mail-is-a-reply-or-has-been-forwarded

I'm closing this issue because I don't see anything in the SO answers that warrants improvements in exchangelib. Feel free to reopen if you think otherwise.
