### ISSUE TITLE
Erratic version guessing

### ISSUE THREAD

**Issue by kamilwilk** [ecederstrand/exchangelib#92]
Is it possible to filter by time? Every time I try to do something like folder.filter(start__lt=dt) I get an error:
ValueError: 'start' is not a valid field when filtering on Messages
(possibly doing something wrong)

Also any possibility of implementing something to pull say the first 10 emails from a folder? I was hoping to build a script that monitors new emails coming in.

Also authentication seems hit or miss for me. Sometimes it works, other times I get something like this:
 ```
C:\Users\xxxx>python c:/Users/xxxxx/Desktop/test.py
    Traceback (most recent call last):
  File "c:/Users/xxxx/xxxx/test.py", line 21, in <module>
    autodiscover=True, access_type=DELEGATE)
  File "C:\Python27\lib\site-packages\exchangelib\account.py", line 51, in __init__
    credentials=credentials, verify_ssl=verify_ssl)
  File "C:\Python27\lib\site-packages\exchangelib\autodiscover.py", line 186, in discover
    protocol=protocol)
  File "C:\Python27\lib\site-packages\exchangelib\autodiscover.py", line 341, in _autodiscover_quick
    verify_ssl=protocol.verify_ssl)
  File "C:\Python27\lib\site-packages\exchangelib\protocol.py", line 173, in __call__
    protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\exchangelib\protocol.py", line 207, in __init__
    self.version = Version.guess(self)
  File "C:\Python27\lib\site-packages\exchangelib\version.py", line 186, in guess
    return cls._guess_version_from_service(protocol=protocol, hint=api_version)
  File "C:\Python27\lib\site-packages\exchangelib\version.py", line 227, in _guess_version_from_service
    return cls._get_version_from_service(protocol=protocol, api_version=api_version)
  File "C:\Python27\lib\site-packages\exchangelib\version.py", line 242, in _get_version_from_service
    allow_redirects=False)
  File "C:\Python27\lib\site-packages\exchangelib\util.py", line 426, in post_ratelimited
    raise TransportError('Unknown failure\n' + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 0
Timeout: 120
Session: 22193
Thread: 7416
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x02BE1730>
URL: xxxxx
Verify: True
Allow redirects: False
Response time: 0:00:00.047000
Status code: 405
```

Thanks!

**Comment by ecederstrand** [comment]
Regarding your first question, the error you're getting is because `start` is not a valid field for `Message`:

```python
>>> from exchangelib import Message
>>> Message.fieldnames()
('message_id', 'is_delivery_receipt_requested', 'is_read', 'to_recipients', 'author', 'bcc_recipients', 'is_response_requested', 'cc_recipients', 'reply_to', 'sender', 'is_read_receipt_requested', 'attachments', 'is_draft', 'last_modified_name', 'importance', 'sensitivity', 'mime_content', 'headers', 'body', 'datetime_sent', 'reminder_is_set', 'categories', 'datetime_created', 'extern_id', 'subject', 'datetime_received', 'last_modified_time')
```

You can filter on (almost) all of these, but `datetime_received` is probably the one you want.

**Comment by ecederstrand** [comment]
Regarding your second question, QuerySets support slicing, so you can do something like this:

```python
top_ten_emails = account.inbox.all().order_by('-datetime_received')[:10]
```

To get the first ten emails in your inbox, sorted by `datetime_received` in reverse order. A statement like `first 10 emails` only really makes sense when you specify the field to sort by.

**Comment by ecederstrand** [comment]
Finally, I haven't experienced the authentication errors you reported. It's crashing in the part of the code that tries to guess the Exchange version the remote server is using. Assuming the URL you redacted is where you expected to land after autodiscover, the server is throwing HTTP 405 responses on our attempts for some reason. You could try to patch `Version._guess_version_from_service` to also catch the `TransportError` and see if that gets you further.

**Comment by ecederstrand** [comment]
I refactored the version guessing code path in https://github.com/ecederstrand/exchangelib/commit/fa5ad805e7d3556781237d4c28ed65df57b9f873 Can you give that a spin and test if it helps your `HTTP 405` errors?

**Comment by ecederstrand** [comment]
Closing due to submitter timeout. Feel free to re-open if this is still a problem.
