### ISSUE TITLE
Improve docs on in_reply_to and references

### ISSUE THREAD

**Issue by thefedoration** [ecederstrand/exchangelib#923]
**Is your feature request related to a problem? Please describe.**
I am looking to reply to emails, with attachments.
`email.create_reply` and `email.create_reply_all` do not allow for taking attachments, so I am trying to construct a new `Message`. I've found the `in_reply_to` and `references` fields, and have attempted to pass in the ID of the email I'm replying to, but it gets sent as a new message and not in reply to the conversation.

**Describe the solution you'd like**
Could you please elaborate on how to use these 2 fields to respond to emails in the same conversation? Thank you!

**Comment by ecederstrand** [comment]
If you need attachments, then you should create a reply item, save it, add attachments, and then send it. See https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-respond-to-email-messages-by-using-ews-in-exchange

It's possible that in exchangelib you have to convert the `ReplyToItem` item to a `Message` item that can have attachments, by doing something like `account.drafts.get(id=my_reply_to_item.id)`.

**Comment by thefedoration** [comment]
got it - very helpful!

that was the missing piece for me, adding attachments only after converting to a Message.
For reference, here's what worked for me:
```
# get data for the reply message
reply_data = self._get_send_message_content(to, subject, body, **kwargs)
attachments = reply_data.pop('attachments')  # will add later

# make the reply item & save to drafts
draft = email.create_reply(**reply_data)
draft = draft.save(folder=self.account.drafts)

# now fetch the draft (converts it to a Message)
message = self.account.drafts.get(id=draft.id)

# add attachments to the Message
for a in attachments:
    message.attach(a)
message.send()
```

**Comment by ecederstrand** [comment]
Thanks fo the example!

You *could* probably avoid the request/response that `self.account.drafts.get(id=draft.id)` triggers, by manually creating a `Message` object and copying over all the attributes from the `ReplyToItem ` that are valid on the `Message`. Using `.get()` was just the most simple solution I could think of.
