### ISSUE TITLE
Using incorrect Exchange login credentials when Autodiscover is enabled results in printing very verbose error information to stdout

### ISSUE THREAD

**Issue by laurachan** [ecederstrand/exchangelib#924]
**Describe the bug**
When trying to connect to Exchange with autodiscover=True, entering incorrect login credentials results in very verbose output about the request being printed to stdout before the AutoDiscoverFailed exception gets thrown, which is an annoyance when using exchangelib in a command-line application.

**To Reproduce**
In the example below, replace example.com with your domain.
```
>>> from exchangelib import Account, Credentials
>>> c = Credentials('wrongusername', 'wrongpassword')
>>> Account('wrongusername@example.com', credentials=c, autodiscover=True)

UnauthorizedError: Invalid credentials for https://autodiscover.example.com/Autodiscover/Autodiscover.xml
Retry: 0
Waited: 10
Timeout: 10
Session: 26647
Thread: 139822449653568
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x7f2af0fc0cd0>
URL: https://autodiscover.example.com/Autodiscover/Autodiscover.xml
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x7f2af0fc0970>
Allow redirects: False
Streaming: False
Response time: 0.16200923399992462
Status code: 401
[...Yet more output, including full details on request headers, omitted for brevity...]
```

**Expected behavior**
I think the default should be to not print verbose debug info to stdout about the request before throwing the AutoDiscoverFailed exception. That being said, it would be nice to have enough information in either the AutoDiscoverFailed exception object or some other appropriate return value to determine if the exception was caused by login failure so that appropriate detection and handling code can be written.

**Log output**
N/A

**Additional context**
This was reproduced in Python 3.9.2 on Linux and exchangelib 4.3.0. The verbose output does not appear when using exchangelib 2.2.0.

**Comment by ecederstrand** [comment]
While this is log output which you can chose to silence by configuring logging, I agree that this case does not need the verbose output. The referenced commit should fix that.
