### ISSUE TITLE
name 'ServiceAccount' is not defined

### ISSUE THREAD

**Issue by ahalyarekha** [ecederstrand/exchangelib#925]
I am trying to use te below code

**from datetime import datetime, timedelta
import pytz
from exchangelib import DELEGATE, IMPERSONATION, Account, Credentials, ServiceAccount, \
    EWSDateTime, EWSTimeZone, Configuration, NTLM, GSSAPI, CalendarItem, Message, \
    Mailbox, Attendee, Q, ExtendedProperty, FileAttachment, ItemAttachment, \
    HTMLBody, Build, Version, FolderCollection

credentials = ServiceAccount(username='FOO\\bar', password='topsecret')**

I get the following error
name 'ServiceAccount' is not defined.

Does this mean ServiceAccount is not exisitng in exchangelib module?

**Comment by ecederstrand** [comment]
The `ServiceAccount` class was removed in exchangelib 2.0. See https://github.com/ecederstrand/exchangelib/blob/master/CHANGELOG.md#200
