### ISSUE TITLE
Support for Address Lists ? 

### ISSUE THREAD

**Issue by ldrolez** [ecederstrand/exchangelib#926]
Hi there!

Is there support for contacts in AddressList in exchangelib? 
For example, in Powershell I used to play with Get-AddressList -Identity "CorpX" 

Thanks!

**Comment by ecederstrand** [comment]
It doesn’t look like it’s supported in EWS. Do you have any docs stating otherwise?

**Comment by ecederstrand** [comment]
Closing because I don't think the functionality is exposed in EWS. Feel free to reopen if you disagree.
