### ISSUE TITLE
Exchange2019 Version 15.2 ‎(Build 858.5)‎ return ErrorInvalidRequest

### ISSUE THREAD

**Issue by lchen016** [ecederstrand/exchangelib#927]
We updated our Exchange server from 2016 to 2019.  When our EWS client try to connect to the server with RequestServerVersion Version="Exchange2019", the server returns 500  ErrorInvalidRequest.  If we change to rise Version="Exchange2016", the same server returns 200 

EWS Request: 
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2019"></t:RequestServerVersion></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>AllProperties</t:BaseShape></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="inbox"></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></soap:Body>
</soap:Envelope>

Response from Exchange2019 server:
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorInvalidRequest</faultcode><faultstring xml:lang="en-US">The request is invalid.</faultstring><detail><e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorInvalidRequest</e:ResponseCode><e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The request is invalid.</e:Message></detail></s:Fault></s:Body></s:Envelope>

Using Exchange2016 in the request to the same Exchange2019 server
Request
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2016"></t:RequestServerVersion></soap:Header><soap:Body><m:GetFolder><m:FolderShape><t:BaseShape>AllProperties</t:BaseShape></m:FolderShape><m:FolderIds><t:DistinguishedFolderId Id="inbox"></t:DistinguishedFolderId></m:FolderIds></m:GetFolder></soap:Body></soap:Envelope>

Response:
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="2" MajorBuildNumber="858" MinorBuildNumber="2" Version="V2017_07_11" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:GetFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetFolderResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode>
<m:Folders><t:Folder><t:FolderId Id="AQMkADY2AGY4ZGY0Zi05YTNlLTRiY......"/><t:ParentFolderId Id="AQMkADY2AGY4ZGY0Zi........." ChangeKey="AQ......"/><t:FolderClass>IPF.Note</t:FolderClass><t:DisplayName>Inbox</t:DisplayName><t:TotalCount>0</t:TotalCount><t:ChildFolderCount>0</t:ChildFolderCount><t:EffectiveRights><t:CreateAssociated>true</t:CreateAssociated><t:CreateContents>true</t:CreateContents><t:CreateHierarchy>true</t:CreateHierarchy><t:Delete>true</t:Delete><t:Modify>true</t:Modify><t:Read>true</t:Read><t:ViewPrivateItems>true</t:ViewPrivateItems></t:EffectiveRights><t:UnreadCount>0</t:UnreadCount></t:Folder></m:Folders>
</m:GetFolderResponseMessage></m:ResponseMessages></m:GetFolderResponse></s:Body></s:Envelope>

**Expected behavior**
We expect when using the version Exchange2019 to connect to the Exchange2019 server, it should not return an error.
And also expect to know the reason why using version ="Exchange2016" can work with the same Exchange2019 server without error.

**Comment by ecederstrand** [comment]
While Exchange 2019 has been released, its EWS API apparently still identifies as `Exchange2016`. exchangelib will auto-negotiate the version, so it’s not a huge problem.

**Comment by lchen016** [comment]
Will this behavior being corrected in the future or is using version="Exchange2016" for Exchange2019 is expected?

**Comment by ecederstrand** [comment]
Frankly, I don’t know what Microsoft intend to do here. Does it cause problems for you in exchangelib?

**Comment by lchen016** [comment]
Things seem to work if we use version="Exchange2016" and even version="Exchange2010".

**Comment by ecederstrand** [comment]
I meant problems in terms of exceptions, stack traces etc. A single unnecessary request isn’t likely to cause real problems, as I see it.

**Comment by ecederstrand** [comment]
I’m closing this issue because I don’t see any actual problems in terms of exceptions, bugs or performance issues. Feel free to reopen if you disagree.
