### ISSUE TITLE
exchangelib.errors.TransportError: Unknown failure

### ISSUE THREAD

**Issue by OriginalDopey** [ecederstrand/exchangelib#929]
My code has been running for some time and now periodically fails with this error.  If I retry, it still fails.  This is the log data...

2021-06-03 13:46:04,562 : EWS https://csmail.xxx.xxx/EWS/Exchange.asmx, account xxx@xxx.xxx.xxx: Exception in _get_elements: Traceback (most recent call last):
  File "C:\Python Projects\venv\Mailroom_Automation_Phase1\lib\site-packages\exchangelib\services\common.py", line 66, in _get_elements
    response = self._get_response_xml(payload=payload)
  File "C:\Python Projects\venv\Mailroom_Automation_Phase1\lib\site-packages\exchangelib\services\common.py", line 131, in _get_response_xml
    stream=self.streaming,
  File "C:\Python Projects\venv\Mailroom_Automation_Phase1\lib\site-packages\exchangelib\util.py", line 742, in post_ratelimited
    _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
  File "C:\Python Projects\venv\Mailroom_Automation_Phase1\lib\site-packages\exchangelib\util.py", line 826, in _raise_response_errors
    raise TransportError(str('Unknown failure\n') + log_msg % log_vals)
exchangelib.errors.TransportError: Unknown failure
Retry: 0
Waited: 10
Timeout: 120
Session: 27030
Thread: 284
Auth type: <requests_ntlm.requests_ntlm.HttpNtlmAuth object at 0x04A127D0>
URL: https://csmail.xxx.xxx/EWS/Exchange.asmx
HTTP adapter: <requests.adapters.HTTPAdapter object at 0x04A12C10>
Allow redirects: False
Streaming: False
Response time: 0.625
Status code: 413
Request headers: {'User-Agent': 'exchangelib/3.1.1 (python-requests/2.23.0)', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'Keep-Alive', 'Content-Type': 'text/xml; charset=utf-8', 'X-AnchorMailbox': 'xxx@xxx.xxx.xxx', 'Cookie': 'exchangecookie=44f9f38399304661abd5a50ce27e29eb', 'Content-Length': '35941216'}
Response headers: {'Server': 'Microsoft-IIS/7.5', 'X-Powered-By': 'ASP.NET', 'Date': 'Thu, 03 Jun 2021 17:46:09 GMT', 'Content-Length': '0'}
Request data: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><s:Header><t:RequestServerVersion Version="Exchange2010_SP2"/><t:TimeZoneContext><t:TimeZoneDefinition Id="Eastern Standard Time"/></t:TimeZoneContext></s:Header><s:Body><m:CreateAttachment><m:ParentItemId Id="AAMkADQ0YmE2NzEwLTZiYmItNGE4NC1iNmEwLTg5MjA3ZWQxNjRhYgBGAAAAAAB2PTL79ZGmSI7YB/Ffr569BwCNCx3y+V3fRrbBxQmcQhZPAAAAGpuVAADN6pOwIHO1RKp2kNhAKJ9WAAFP+jcFAAA=" ChangeKey="CQAAABYAAADN6pOwIHO1RKp2kNhAKJ9WAAFdL8op"/><m:Attachments><t:FileAttachment><t:Name>XXXXXXXXX.pdf</t:Name><t:ContentType>application/pdf</

**Comment by ecederstrand** [comment]
You're getting an HTTP 413 response. This means that the [request payload is too large ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413). Since you're creating an attachment, I would assume that the attachment size exceeds some limit that the server admins have set on attachment sizes.

**Comment by OriginalDopey** [comment]
Thank you, I will find the sizes and code around it.  I will reopen it if this doesn't resolve it.  Thanks.
