### ISSUE TITLE
Add image attachment from template and sending does not show image

### ISSUE THREAD

**Issue by joanrodriguezr** [ecederstrand/exchangelib#930]
Hi Erik,

First of all thanks for your library and support. We are using 3.2.0 version to try to reply an user with a template that has text and embedded images.

The snippet of code is this one:

	templateFolderName = <LOADED FROM CONFIG FILE>
	templateSubject = <LOADED FROM CONFIG FILE>
	templateFolder = <GENERATED USING templateFolderName>
	templateMsg = templateFolder.filter(subject__startswith='{}'.format(templateSubject))[0]

	m = Message(account=<OUR ACCOUNT>, author='<OUR EMAIL ADDRESS>',subject=templateMsg.subject, body=templateMsg.body, to_recipients=[Mailbox(email_address=<FROM PARAMETER>),],folder=<OUR ACCOUNT>.sent).save()
		
	for Attachment in templateMsg.attachments:
		m.attach(Attachment)

        m.send()

It all works fine, sends the message with the text from the template, but shows no image within the received message generated from template.

Is there any extra thing to do with m.attach() ?

Any help would be appreciatted.

Best regards and thanks in advance

**Comment by ecederstrand** [comment]
Embedding images in HTML emails is documented in https://ecederstrand.github.io/exchangelib/#attachments

**Comment by joanrodriguezr** [comment]
Thanks for your support, it worked replacing the template image with a local file content where the script runs and setting the same filename and content-id:

	imagePath = '<IMAGE PATH>'
	with open(imagePath, 'rb') as f:
		fileAttName = FileAttachment(name=imagePath, content=f.read(), is_inline=True,content_id='<TEMPLATE IMAGE ID>')
	m.attach(fileAttName)

Thanks for your help as usual Erik you saved my day!
