### ISSUE TITLE
EML attachment with attachment in EML

### ISSUE THREAD

**Issue by gismcieri** [ecederstrand/exchangelib#932]
Hi,

We have a process that was using exchangelib to check an email box for new messages and if there was a subject of a specific type it would grab the email and download an XML attachment.  On June 3rd the emails we started receiving started coming in with an eml attachment that contained the XML we had been expecting.  Is there a way to get the XML attachment out of an eml ItemAttachment using exchangelib

I haven't been able to save the eml as file either. It doesn't save like an txt, xml or jpg file because I did find another module that will read eml files.  Do you happen to have any thoughts on this?

Thanks,
Matt

**Comment by ecederstrand** [comment]
It’s unclear to me if the new attachment is a file with the .eml file extension, or an actual ItemAttachment object.

If it’s the former, then Python has a built-in module for parsing MIME content, which is basically what a .eml file contains.

If it’s the latter, the n the ItemAttachment has an `item` field containing the attached item. This item can then have attachments.

**Comment by gismcieri** [comment]
Can you please explain option 2.

`        for attachment in item.attachments:
            if isinstance(attachment, FileAttachment):
                local_path = os.path.join('C:\Temp', attachment.name)
                with open(local_path, 'wb') as f:
                    f.write(attachment.content)
                print('Saved attachment to', local_path)
            elif isinstance(attachment, ItemAttachment):
                if isinstance(attachment.item, Message):
                    print(attachment.item.subject, attachment.item.body


`

The email gets to the elif cause i can see the subject and body but i can't seem to get .item.attachement

Thanks,
Matt

**Comment by ecederstrand** [comment]
The attached item is just a normal item, so attachments on the attached item are available in `item.attachments`, not `item.attachment`.

**Comment by gismcieri** [comment]
Hi,

Thanks so much i got it due to your response.  here is the sample code if anyone wants it.  

`
        for attachment in item.attachments:
            print (attachment.name)
            
            if isinstance(attachment, FileAttachment):
                local_path = os.path.join('C:\Temp', attachment.name)
                with open(local_path, 'wb') as f:
                    f.write(attachment.content)
                print('Saved attachment to', local_path)
            elif isinstance(attachment, ItemAttachment):
                if isinstance(attachment.item, Message):
                    print(attachment.item.subject, attachment.item.body)
                    print (attachment.item)
                    print (attachment.item.attachments)
                    for attachment in attachment.item.attachments:
                        if isinstance(attachment, FileAttachment):
                            local_path = os.path.join('C:\Temp', attachment.name)
                            with open(local_path, 'wb') as f:
                                f.write(attachment.content)
`

Matt

**Comment by dmsfabiano** [comment]
@gismcieri in my case I am trying to save the item (and it's attachment's) as an itemAttachment/.msg however I get
`exchangelib.errors.ErrorRequiredPropertyMissing: Required property is missing. (field: <t:ExceptionFieldURI xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" FieldURI="attachment:Name"/>)`
Have you seen this before?

**Comment by ecederstrand** [comment]
@dmsfabiano The `name` field of the attachment you are trying to save is empty. You need to give your attachment a name.
