### ISSUE TITLE
Sending Excel Corrupt File

### ISSUE THREAD

**Issue by rm17tink** [ecederstrand/exchangelib#935]
**Describe the bug**
I can not send an excel file along with my other PDFs. I just fails to send when I have the 4th attachment. 

**To Reproduce**
```
with open(dir_path + cover_letter_name, 'rb') as a,  \
		open(dir_path + application_name, 'rb') as b, 	\
		open(dir_path + excel_name, 'rb') as c,  \
		open(dir_path + i.AGCODE + PDF_name, 'rb') as d:	
                        cl_att = FileAttachment(name=cover_letter_name, content=a.read() )
			app_att = FileAttachment(name=application_name, content=b.read() )
			excel_att = FileAttachment(name=excel_name, content=c.read() )
			pdf_att = FileAttachment(name=i.AGCODE + PDF_name, content=d.read() )
			m.attach(cl_att)
			m.attach(app_att)
			m.attach(excel_att)
			m.attach(pdf_att)
			m.send_and_save()
```

**Expected behavior**
I would expect the email to go through as it does when I don't have the excel attached. 

**Traceback
Traceback (most recent call last):

```
  File "<ipython-input-23-ed8286f275c9>", line 46, in <module>
    excel_att = FileAttachment(name=excel_name, content=c.read() )
`UnsupportedOperation: read`

```

**Additional context**
Python 3.7 and exchangelib = 4.4.0

**Comment by ecederstrand** [comment]
Can you please post the stack trace you get?

**Comment by rm17tink** [comment]
```
Traceback (most recent call last):

  File "<ipython-input-23-ed8286f275c9>", line 46, in <module>
    excel_att = FileAttachment(name=excel_name, content=c.read() )
```

**Comment by rm17tink** [comment]
> Can you please post the stack trace you get?

added it to original. thanks

**Comment by rm17tink** [comment]
> Can you please post the stack trace you get?

Nevermind. I am sorry to waste your time. I fixed it. No issues with your code. Ill delete once you read.

**Comment by rm17tink** [comment]
> Can you please post the stack trace you get?
Any idea why it corrupts the file when sent? also corrupts the file in the source directory too.

**Comment by ecederstrand** [comment]
I don’t think this has anything to do with exchangelib. `open(dir_path + excel_name, 'rb').read()` would supposedly also fail. Either the file or filesystem is corrupt, or it’s not actually a file.

When you send file attachments, it’s good practice to Also set the `content_type` to something that matches the file type, so clients in the other end know the file type.

**Comment by rm17tink** [comment]
> I don’t think this has anything to do with exchangelib. `open(dir_path + excel_name, 'rb').read()` would supposedly also fail. Either the file or filesystem is corrupt, or it’s not actually a file.
> 
> When you send file attachments, it’s good practice to Also set the `content_type` to something that matches the file type, so clients in the other end know the file type.

How would I do that. the code works fine now but when the excel is opened in the email its corrupt.

**Comment by ecederstrand** [comment]
content_type is an attribute on FileAttachment. You set the value to something that’s relevant for Excel files.

If your file is still corrupt on arrival, then it’s probably corrupt already when you read it from disk.

**Comment by rm17tink** [comment]
@ecederstrand thanks.  Do you have an example code for adding content type?

**Comment by ecederstrand** [comment]
Here's an example from the [documentation](https://ecederstrand.github.io/exchangelib/):

```python
att = FileAttachment(
    name='ContactPicture.jpg',
    content_type='image/png',
    is_inline=False,
    is_contact_photo=True,
    content=open('john_profile_picture.png', 'rb').read(),
)
```

**Comment by rm17tink** [comment]
> Here's an example from the [documentation](https://ecederstrand.github.io/exchangelib/):
> 
> ```python
> att = FileAttachment(
>     name='ContactPicture.jpg',
>     content_type='image/png',
>     is_inline=False,
>     is_contact_photo=True,
>     content=open('john_profile_picture.png', 'rb').read(),
> )
> ```

thanks in the context of an xlsx.  would I just use content_type='xlsx',  ?

**Comment by ecederstrand** [comment]
Content type valses are not specific to exchangelib. See e.g. https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc For the correct value in your case.
