### ISSUE TITLE
timezone fetching in exchangelib

### ISSUE THREAD

**Issue by hjain371** [ecederstrand/exchangelib#937]
Hi,
Thanks for sharing this but I am still getting time error fetching the details, can you please help me creating the account correctly.
I am using exchangelib 3.3.2 version, I am getting below error while fetching user configuration:

```python
config = account.calendar.get_user_configuration('WorkHours')
```
----> 1 config = account.calendar.get_user_configuration('WorkHours')
AttributeError: 'Calendar' object has no attribute 'get_user_configuration'

below is the code I am using to create the account:

```python
cred = Credentials(username=username, password=password)
config = Configuration(server=server, credentials=cred, auth_type="NTLM")
account = Account(primary_smtp_address=email_id, autodiscover=False,
                       config=config, access_type=DELEGATE)
```

email_id is the shared mailbox email id and server is outlook.(--my organization--).net

Should I have to change some config setting to bind calendar user config to it?

_Originally posted by @hjain371 in https://github.com/ecederstrand/exchangelib/issues/903#issuecomment-860543958_

**Comment by ecederstrand** [comment]
The `GetUserConfiguration` service was added in https://github.com/ecederstrand/exchangelib/commit/09ad84061684cafbcf91a9f0d57bb2f67383571d which was released in exchangelib 4.0.0. You'll have to upgrade to get the `get_user_configuration()` method.
