### ISSUE TITLE
EAS Auth continue to work with old password

### ISSUE THREAD

**Issue by Maksym-L** [ecederstrand/exchangelib#938]
**Describe the bug**
After changing the Outlook password, the auth for EAS protocol continue to work using the old password

**To Reproduce**
```Python
import exchangelib

#1. auth directly with correct password
config = exchangelib.Configuration(
    service_endpoint=u'https://eas.outlook.com/EWS/Exchange.asmx',
    credentials=exchangelib.Credentials(username=<outlook e-mail>, password=<password>)
)

account = exchangelib.Account(
    primary_smtp_address=<outlook e-mail>,
    config=config,
    autodiscover=False,
    access_type=exchangelib.DELEGATE,
)

for item in account.inbox.all().order_by('-datetime_received')[:10]:
    print(item.subject, item.sender, item.datetime_received)
```
Steps:
- Provide correct email and password and run the script
- Change Outlook password
- Run script with old password

**Expected behavior**
The script should fail

**Actual behavior**
The script continue to work

**Comment by ecederstrand** [comment]
I don’t think this is anything exchangelib can solve. Authentication happens on the Exchange server, and auth problems should be fixed there.

**Comment by Maksym-L** [comment]
After the password change, the execution of the script using the old password would fail on a different device, but not on my current one. If it were only a server issue, the behavior would be the same on both devices. It looks like it depends on the device I'm using it.
- Is there any cache for auth tokens?
- How can I reset it?
- Is it possible to "pretend" to be a new device?

**Comment by ecederstrand** [comment]
Is that client also connecting to `eas.outlook.com`? I have a really hard time believing that EWS would accept connections with credentials that are no longer valid on the server, regardless of whatever information the client has cached locally.

Also, which authentication type is this? Authentication mechanisms are very different, depending on whether you're using Basic, Digest, NTLM, Kerberos, OAuth or some other type.

If it's NTLM auth, then an NTLM connection will be authenticated for the duration of the connection. That's how NTLM works. Basic auth, for example, requres every request to have proper authentication headers. If you keep the connection to the server open long enough, you may not have to re-auth with the new password even though you changed it on the server. I don't know how long Exchange allows NTLM-auth'ed connections to survive.

exchangelib does not persist auth tokens, passwords or anything else related to authentication when the Python process is closed. Long-running processes may reuse TCP sessions in connection pools, and those TCP connections may contain authentication tokens for a different credential than you expect, if you are switching credentials all the time within a Python process.

Finally, I believe that you are you are actually running the Nylas fork, right? Please keep in mind that your fork has diverged considerably from upstream.

**Comment by Maksym-L** [comment]
It looks like this behavior is due to how the Exchange server handles basic auth. Closing this issue, as it is no way to "fix" it anyway :(

**Comment by ecederstrand** [comment]
Just following up. This turned out to be a known issue with EAS: https://docs.microsoft.com/en-US/exchange/troubleshoot/client-connectivity/eas-devices-still-sync-with-disabled-account
