### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Kami-no** [ecederstrand/exchangelib#94]
Tried example with notifications.

CERTIFICATE_VERIFY_FAILED with:
```
# username, _, password = netrc().authenticators('office365')
c = Credentials(config.pyx_user, config.pyx_pass, is_service_account=False)
cfg = Configuration(server=config.pyx_url, credentials=c)
a = Account(primary_smtp_address=c.username, config=cfg, access_type=DELEGATE, autodiscover=False, verify_ssl=False)
```

P.S.: at Kali Linux rolling release based on Debian Sid i've
```
$ timedatectl 
      Local time: Wed 2017-03-08 14:26:34 MSK
  Universal time: Wed 2017-03-08 11:26:34 UTC
        RTC time: Wed 2017-03-08 11:26:34
       Time zone: Europe/Moscow (MSK, +0300)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
```
In means "Time zone" has space:
```
# Get the local timezone
timedatectl = sh.Command('/usr/bin/timedatectl')
for l in timedatectl():
    if 'Time zone' in l:
        tz_name = l.split()[2]
        break
else:
    raise ValueError('Timezone not found')
tz = EWSTimeZone.timezone(tz_name)
```

**Comment by ecederstrand** [comment]
Thanks for the report! `scripts/notifications.py` was a quick hack by me. You're very welcome to send a PR with your fixes.

I'm curious why you get `CERTIFICATE_VERIFY_FAILED`. Maybe it's a missing `verify_ssl=False` in `Configuration()`, but you should really create a chain of trust on your machine so you don't need to disable certificate verification.

**Comment by ecederstrand** [comment]
Committed the `timezonectl` fix in https://github.com/ecederstrand/exchangelib/commit/40ede4e64ffd0c23ba6f399d54d4a22e614e6428 Thanks!

**Comment by Kami-no** [comment]
Yes, you're right. moved `verify_ssl=False` to configuration from account and it fixed the issue. Than you also should check lines 76 and 77 in the same notifier script =)

**Comment by ecederstrand** [comment]
You mean removing `verify_ssl=False` from the script entirely? I think that's a good idea.

**Comment by Kami-no** [comment]
I mean move it from Account to Configuration. Current state caused the issue...

**Comment by ecederstrand** [comment]
Maybe you're looking at an old version? https://github.com/ecederstrand/exchangelib/blob/master/scripts/notifier.py doesn't create a `Configuration` (directly, at least).

**Comment by Kami-no** [comment]
Initially I thought 'c' stands for Configuration and wrote the first part of the comment but than remembered it's for Credentials and in my case I've added Configuration myself.
