### ISSUE TITLE
Error in accessing shared mailbox

### ISSUE THREAD

**Issue by kenwoodsi** [ecederstrand/exchangelib#945]
**Describe the bug**
can't able to access shared mailbox using either autodiscovery or config

**To Reproduce**
```python
from exchangelib import DELEGATE, Account, Credentials, Configuration
from configparser import ConfigParser
parser = ConfigParser()
parser.read('password.config')
password = parser.get('password', 'pwd')
credentials = Credentials('********@example.com', password)
config = Configuration(server='outlook.office365.com', credentials=credentials)
account = Account('********@example.com', credentials=credentials, config=config, autodiscover=False,access_type=DELEGATE)

for item in account.inbox.all().order_by('-datetime_received')[:2]:
    print(item.subject, item.sender, item.datetime_received)
```

**Expected behavior**
trying to read first 2 mails of shared mailbox

**Log output**
TransportError: Unknown failure in response. Code: 503 

**Additional context**
python version - 3.9.5
exchangelib version - 4.4.0

**Comment by ecederstrand** [comment]
You're getting an HTTP 503 Service Unavailable error response. That's usually an intermittent problem.

It's also possible that our user does not have access to the shared mailbox, and this is the response from the server.

**Comment by ecederstrand** [comment]
Closing, but feel free to reopen if you think anything can be improved in exchangelib.

**Comment by kenwoodsi** [comment]
what could be the solution for this?

**Comment by ecederstrand** [comment]
I have no idea. HTTP 503 Service Unavailable is a really generic error, and O365 is not genrally unavailable.

I would check the network connection to `outlook.office365.com` from the host. Maybe there's some proxying or redirection going on? Also, you can check with your Exchange admins whether your credentials and account are set up correctly in O365.
