### ISSUE TITLE
Exchange on-premise

### ISSUE THREAD

**Issue by rkromann** [ecederstrand/exchangelib#947]
Thank you for a great library. I have used it succesfully to communicate with Exchange online. Specifically I have extracted the body text an cleaned it using BeautifulSoup and the get_text() method, and it work like a charm.  Now I have a new task involving an on-premise Exchange server. It appears that the encoding of the body text is different in this case, and I haven't been able to figure out how to fix it. Do you have any suggestions about how to clean text from an on-premise server?

**Comment by ecederstrand** [comment]
The `body` field is supposed to be returned as a Python `str` object, i.e. as unicode and not encoded in any specific encoding.

On-prem and O365 are not supposed to be different regarding the EWS implementation. What is the exact issue you're seeing? If you see encoding issue, you may be able to get some hints if you enable debug logging (see https://ecederstrand.github.io/exchangelib/#troubleshooting) and look at the actual data transferred from the server.

**Comment by rkromann** [comment]
Thanks for your quick reply. I have figured it out now, so I am closing this issue. 

get_text() is part of BeautifulSoup. I figured it
