### ISSUE TITLE
Is it possible to use exchangelib to move mails from Recoverable Items folder to any other folder?

### ISSUE THREAD

**Issue by psmitak** [ecederstrand/exchangelib#948]
In my outlook shared mailboxes, if I move a mail from one folder to another, it is getting landed in the Recoverable items folder. The reason is unknown. So to recover the mails automatically, I want to try exchangelib. So is it possible to move the mails from Recoverable items folder (Deletions sub-folder) to any other folder?

**Comment by ecederstrand** [comment]
As far as exchangelib is concerned, all folders are handled the same. To move an item to a different folder, just do `some_item.move(destination_folder)`.

I don't see any reason why you couldn't move an item in the Recoverable items folder to any other folder in the mailbox, but whatever policies Exchange applies to restrict or allow this is out of the hands of exchangelib.

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you still need help with this.
