### ISSUE TITLE
PyExchange Crashes when requesting people from addressbook

### ISSUE THREAD

**Issue by SebastianLuebke** [ecederstrand/exchangelib#95]
`Traceback (most recent call last):
  File "test.py", line 56, in <module>
    for i in bla.iterator():
  File "/usr/lib/python3.6/site-packages/exchangelib/account.py", line 382, in fetch
    yield validation_folder.item_model_from_tag(i.tag).from_xml(elem=i, account=self, folder=folder)
  File "/usr/lib/python3.6/site-packages/exchangelib/folders.py", line 1315, in from_xml
    kwargs[fieldname] = [list_type.from_xml(e) for e in iter_elem.findall(list_type.response_tag())]
  File "/usr/lib/python3.6/site-packages/exchangelib/folders.py", line 1315, in <listcomp>
    kwargs[fieldname] = [list_type.from_xml(e) for e in iter_elem.findall(list_type.response_tag())]
  File "/usr/lib/python3.6/site-packages/exchangelib/folders.py", line 535, in from_xml
    phone_number=elem.text,
  File "/usr/lib/python3.6/site-packages/exchangelib/folders.py", line 518, in __init__
    assert isinstance(phone_number, (int, string_type)), phone_number
`

Our the telephonenumbers are saved in following format +49 (2932) 39666, shouldnt be numbers always a string instead of an integer?

**Comment by ecederstrand** [comment]
The check for `int` is stupid, yes, because phone numbers should never be passed around as ints. That's very high on the "101 things not to do in programming" list ;-) But the code is apparently failing because the `phone_number` is neither an `int` nor a `string_type`. Can you edit line 518 to print both `phone_number`, `type(phone_number)` and `string_type`?

**Comment by SebastianLuebke** [comment]
None
<class 'NoneType'>
<class 'str'>

So the number is just empty?

Von: Erik Cederstrand [mailto:notifications@github.com]
Gesendet: Mittwoch, 8. März 2017 15:18
An: ecederstrand/exchangelib <exchangelib@noreply.github.com>
Cc: Sebastian Luebke <s.luebke@sonntag-datentechnik.de>; Author <author@noreply.github.com>
Betreff: Re: [ecederstrand/exchangelib] PyExchange Crashes when requesting people from addressbook (#95)


The check for int is stupid, yes, because phone numbers should never be passed around as ints. That's very high on the "101 things not to do in programming" list ;-) But the code is apparently failing because the phone_number is neither an int nor a string_type. Can you edit line 518 to print both phone_number, type(phone_number) and string_type?

**Comment by ecederstrand** [comment]
Oh, that's weird. There shouldn't even be an XML element for that phone number, then. Can you add debug logging and capture the XML for that response?

```python
import logging
logging.basicConfig(level=logging.DEBUG)

# Your code here
```

**Comment by ecederstrand** [comment]
You can try PR #97 although I would still like to see the raw XML that triggered this.

**Comment by SebastianLuebke** [comment]
Currently very busy at work, will try it in the eve. Thank you very much for your work and help 😊

Von: Erik Cederstrand [mailto:notifications@github.com]
Gesendet: Freitag, 10. März 2017 09:53
An: ecederstrand/exchangelib <exchangelib@noreply.github.com>
Cc: Sebastian Luebke <s.luebke@sonntag-datentechnik.de>; Author <author@noreply.github.com>
Betreff: Re: [ecederstrand/exchangelib] PyExchange Crashes when requesting people from addressbook (#95)


You can try PR #97<https://github.com/ecederstrand/exchangelib/pull/97> although I would still like to see the raw XML that triggered this.

**Comment by ecederstrand** [comment]
Closing due to submitter timeout. Feel free to re-open if this is still a problem.

I'm postponing a merge of #97 until I see the actual XML, to be sure it doesn't just hide another problem.
