### ISSUE TITLE
Cannot access contacts in Global Address List

### ISSUE THREAD

**Issue by robertschulze** [ecederstrand/exchangelib#952]
**Describe the bug**
Even though I can look up contacts in Outlook in a "Global Address List", I cannot manage to do the same in exchangelib. 

**To Reproduce**
I used the example code from the exchangelib website:
```
gal = self.account.contacts / 'GAL Contacts'
gal.all().count()
```
This is the structure of the Exchange account (I replaced the GUIDs):
```
├── Top of Information Store
│   ├── Calendar
│   ├── Contacts
│   │   ├── GAL Contacts
│   │   ├── Recipient Cache
│   │   ├── {some GUID}
│   │   └── {some other GUID}
```
even trying any of the other entries, e.g.
```
folder = account.root / "Top of Information Store" / "Contacts" / "{some GUID}"
```
does not yield any results.

**Expected behavior**
I would expect to see some results, but even using `.filter()` instead does not work (cf. https://github.com/ecederstrand/exchangelib/issues/162).

**Additional context**
exchangelib version 4.4.0
Python 3.8.8
This is how the Address Book looks in Outlook:

![gal](https://user-images.githubusercontent.com/13728481/126470932-fd854161-4d98-4311-9cdc-82f28ccedd3d.png)

**Comment by ecederstrand** [comment]
I may be mistaken, but I think the "GAL Contacts" you're accessing via exchangelib is a folder containing contacts that have coped from the GAL, while the "Global Address List" in your screen dump is not a contacts folder located in your own account. It may instead be a query into Active Directory.

**Comment by ecederstrand** [comment]
I see some indication that it's possible to query contents of the GAL using either the ResolveNames or FindPeople operations. exchangelib supports both, but I don't have time to work out a possible solution right now.

**Comment by robertschulze** [comment]
Thanks, indeed using ```account.protocol.resolve_names()``` I was able to search mailboxes and contacts from Exchange. However, for anyone trying to do the same: using ```pyad``` I was able to gather the address book information in a more structured way directly from the Active Directory (i.e. e.g. without necessity to additionally authenticate against the Exchange server).

**Comment by hishamahmeddeep** [comment]
@ecederstrand  i am able to get contacts using below
aaa = a.protocol.resolve_names(, return_full_contact_data=True)
print ('////////////////',len(aaa),'///////////////////////') = 100

returns only first 100

how can a get next 100 or more records?
