### ISSUE TITLE
Access email address from to_recipients  list

### ISSUE THREAD

**Issue by VishruthBharadwaj** [ecederstrand/exchangelib#955]
Hi @ecederstrand 
I have written my code in this way

def first():

    mails = outlook.inbox.all().filter(datetime_received__range=(start,end)).order_by('--datetime_received')
    for item in mails:
        ss =item.to_recipients
   
    #print(pp)
if __name__ == '__main__':
    df = first()

if i try to add item.to_recipients.email_address it gives error as  'list' object has no attribute 'email_address'

how to get only email_address or name

**Comment by ecederstrand** [comment]
the `to_recipients` field contains a list of [Mailbox](https://ecederstrand.github.io/exchangelib/exchangelib/properties.html#exchangelib.properties.Mailbox) objects. To get the email address of each Mailbox object, do something like this:

```python
ss = [m.email_address for m in item.to_recipients]
```
