### ISSUE TITLE
Permissions on Calendar folder

### ISSUE THREAD

**Issue by tudstlennkozh** [ecederstrand/exchangelib#960]
Hi,

first of all, a big thank you for this module that saves me a lot of time everyday 👍... since I use daily, I want to do more with it ...

I just tried to display other users' access to my _calendar_ folder ... but I get none. For sure, I know there is a few people in my organization that can access my calendar.

I checked the already opened issues and it seems related to #729. I encounter the same pb : the permission_set for the calendar member of an account is empty. When I [enable logs](https://ecederstrand.github.io/exchangelib/#troubleshooting), I can see in the response from the server (Exchange2016) that I have the correct data from it (I get plenty of <CalendarPermission> with other fields like UserId, CanCreateItems, ...).

I then found the issue #702 but in the source code, the _calendar_ member of an _account_ seems to be of folder.base.Folder type and not of folders.roots.RootOfHierarchy type where the permission_set has been removed. So I do not understand why I cannot get those CalendarPermission in the account.calendar member ...

I am surely missing an obvious point but I do not know where ... 

Any help will be appreciated 😄

**Comment by ecederstrand** [comment]
I'm not sure what the `permission_set` field is actually supposed to do in EWS. The EWS docs are not very helpful: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/permissionset-permissionsettype

Have you tried the `Account.delegates()` method? It may be what you want.

**Comment by tudstlennkozh** [comment]
Thank your for your response and sorry for any misunderstandings ...

Indeed, I fisrt tried delegates but, in my case, it is empty. With Exchange, one can share its calendar with others (and only the calendar), and this does not appear to be in _delegates_.  The rights to read my own calendar seems to be stored in _permissionSet_ via a bunch of permissions. In logs I get those lines : 

           <Folders>
            <CalendarFolder>
              <FolderId Id="AAMkADNjYzk5M...AIBfvkcNAAABCj69AAA=" />
              <ParentFolderId Id="AAMkADNjYz...KlKKemAQDZygCL6+bUEYz/AIBfvkcNAAABCm4RAAA=" />
              <FolderClass>IPF.Appointment/>
              <DisplayName>Calendrier/>
              <TotalCount>2921</TotalCount>
              <ChildFolderCount>2</ChildFolderCount>
              <EffectiveRights>
                <CreateAssociated>true</CreateAssociated>
                <CreateContents>true</CreateContents>
                <CreateHierarchy>true</CreateHierarchy>
                <Delete>true</Delete>
                <Modify>true</Modify>
                <Read>true</Read>
                <ViewPrivateItems>true</ViewPrivateItems>
              </EffectiveRights>
              <PermissionSet>
                <CalendarPermissions>
                  <CalendarPermission>
                    <UserId>
                      <DistinguishedUser>Default</DistinguishedUser>
                    </UserId>
                    <CanCreateItems>false</CanCreateItems>
                    <CanCreateSubFolders>false</CanCreateSubFolders>
                    <IsFolderOwner>false</IsFolderOwner>
                    <IsFolderVisible>false</IsFolderVisible>
                    <IsFolderContact>false</IsFolderContact>
                    <EditItems>None</EditItems>
                    <DeleteItems>None</DeleteItems>
                    <ReadItems>TimeOnly</ReadItems>
                    <CalendarPermissionLevel>FreeBusyTimeOnly</CalendarPermissionLevel>
                  </CalendarPermission>
                  <CalendarPermission>
                    <UserId>
                      <SID>S-1-...</SID>
                      <PrimarySmtpAddress>....</PrimarySmtpAddress>
                      <DisplayName>.../>
                    </UserId>
                    <CanCreateItems>false</CanCreateItems>
                    <CanCreateSubFolders>false</CanCreateSubFolders>
                    <IsFolderOwner>false</IsFolderOwner>
                    <IsFolderVisible>true</IsFolderVisible>
                    <IsFolderContact>false</IsFolderContact>
                    <EditItems>None</EditItems>
                    <DeleteItems>None</DeleteItems>
                    <ReadItems>TimeAndSubjectAndLocation</ReadItems>
                    <CalendarPermissionLevel>FreeBusyTimeAndSubjectAndLocation</CalendarPermissionLevel>
                  </CalendarPermission>

Since the Folder class has declared a permission_set member 
`    permission_set = PermissionSetField(field_uri='folder:PermissionSet', supported_from=EXCHANGE_2007_SP1)`

I thought i could get those permissions this way ...

Note I was not able to see where in the code those lines could be parsed, maybe they are not ?

Best regards

**Comment by ecederstrand** [comment]
Just to be clear, are you saying that you see the above permissions in the response XML, but `account.calendar.permission_set` is empty? That would be an error.

**Comment by tudstlennkozh** [comment]
Yes, I see the above in the XML response but for the account.calendar member I get : 

```
calendar.permission_set.calendar_permissions -> [] 
calendar.permission_set.permissions -> None

```

**Comment by ecederstrand** [comment]
Ok. Can you enable [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) and post the response XML from that, including namespace information for the XML elements? That would help me to write a unit test for this.

**Comment by tudstlennkozh** [comment]
OK, is it still valuable for you if I use AnonymizingXmlHandler() instead ? (bye the way, is there any mean to remove the ESCape sequences in the log ?)

**Comment by ecederstrand** [comment]
You can try `AnonymizingXmlHandler` if you want. It's probably not complete, though, but I don't need any personally identifiable information, just the XML tags.

`PrettyXmlHandler` both prettifies and syntax highlights the XML. If you only want to prettify and not highlight, then create a subclass and override `highlight_xml()` to just return the string unmodified.

**Comment by tudstlennkozh** [comment]
Indeed, I cannot make the AnonymizingXmlHandler to handle correctly the strings to be removed, don't know why (but I'm far from a python logging module expert ...). I will just remove personal info from the log and post it. The log is actually quite big (7M), should I send it directly by mail instead ?

**Comment by ecederstrand** [comment]
Yeah, if it's huge then send it by mail instead. Then I can extract the data I need.

**Comment by tudstlennkozh** [comment]
Ok, thanks. Give me some time to anonymize it ... :-)

**Comment by tudstlennkozh** [comment]
mail sent to your mailbox

**Comment by ecederstrand** [comment]
Thanks for the test data. This should be fixed now.

**Comment by tudstlennkozh** [comment]
Thank you for this fix, I confirm it works 👍
