### ISSUE TITLE
Automatic reply consideration

### ISSUE THREAD

**Issue by sagarhj17** [ecederstrand/exchangelib#975]
Is there any direct function to identify automatic system generated replies such as out of office or leave etc. Any way to identify them as Automatic mails apart from manual replies. Subject would be same since Automatic mail will be in same loop with same conversation Id.

**Comment by ecederstrand** [comment]
EWS does not provide this functionality, AFAIK.

As far as email protocols go, there's no standard that everyone adheres to, but most well-behaved autoresponders will set one or more email headers so an autoresponder in the other end knows to not start an autorespond war. Email headers are available in the `Message.headers` field, and there are suggestions for which headers to look for in e.g. https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/ and https://serverfault.com/questions/56476/is-there-an-email-header-that-will-avoid-responses-from-most-auto-responders

**Comment by ecederstrand** [comment]
Closing. Feel free to reopen if you think there's anything we can improve in exchangelib.
