### ISSUE TITLE
account_obj.sent.get(message_id=InternetMessageId) very slow

### ISSUE THREAD

**Issue by qinshaokang** [ecederstrand/exchangelib#981]
**Describe the bug**
if my email attach a file,account_obj.sent.get(message_id=InternetMessageId) get very slow
but i don't want get the file
thx

**Comment by ecederstrand** [comment]
You can use `.only()` to limit the fields that are fetched. Something like `account_obj.sent.all().only('subject', 'sender', ...).get(message_id=InternetMessageId)`

**Comment by qinshaokang** [comment]
> You can use `.only()` to limit the fields that are fetched. Something like `account_obj.sent.all().only('subject', 'sender', ...).get(message_id=InternetMessageId)`

It works,thx
