### ISSUE TITLE
Bulk Create does not return status

### ISSUE THREAD

**Issue by MagedSaeed** [ecederstrand/exchangelib#984]
Hey, Thanks for this great library, really appreciate this awesome effort.

**Describe the bug**
The bug is quite simple I guess. When I use `bulk_create`, I do not get a list of  `BulkCreateResult` objects as mentioned in the [docs](https://ecederstrand.github.io/exchangelib/exchangelib/index.html#exchangelib.Account.bulk_create). Instead, I am getting an empty list.

**To Reproduce**
here is a sample of my code taken from a class I am using to send messages to a large number of recipients as bcc:
```python
subject = 'title'
html_content = 'html content'
exchange_account = self.get_exchange_account() # this works fine and returns the exchange account
messages = list()
for recipients_list in recipients_lists:
     message = exchangelib.Message(
     account=exchange_account,
     subject=subject,
     body=exchangelib.HTMLBody(html_content),
     to_recipients=['to_recipient@address'],
     bcc_recipients=recipients_list,
)
message.sender = 'sender@address'
messages.append(message)
sent_statuses = exchange_account.bulk_create(
     folder=exchange_account.sent,
     items=messages,
     message_disposition=SEND_AND_SAVE_COPY,
     chunk_size=10,
)
# sent_statuses is an empty list
```
**Expected behavior**
I am expecting to get a list of `BulkCreateResult` objects to make sure all recipients receive the message and save this information in my model.

If I am doing something wrong or there is a better way to achieve this goal, please let me know.

**Log output**
sent_status is an empty list.

**Additional context**
I am using `python 3.8`

I am using `exchangelib==4.5.1`

**Comment by ecederstrand** [comment]
Maybe a stupid question, but did you check that your `messages` list is non-empty just before calling `bulk_create()`?

**Comment by MagedSaeed** [comment]
Yes, yes of course. I also checked in the exchange mailbox and found all the messages in the `send` folder.

**Comment by MagedSaeed** [comment]
By the way, I am talking to an on-premise exchange server. Although I am expecting that this behaviour should be identical to both online and on-premise servers, I am just saying it to provide a complete view.

**Comment by ecederstrand** [comment]
I did a quick test against my test server, and I cannot reproduce. Here's my example:


```xml
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo
    xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="2" MajorBuildNumber="922" MinorBuildNumber="13" Version="V2017_07_11"/>
  </s:Header>
  <s:Body
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:CreateItemResponse
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items>
            <t:Message>
              <t:ItemId Id="AAIoFt9aAAA=" ChangeKey="AIoulxQ"/>
            </t:Message>
          </m:Items>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items>
            <t:Message>
              <t:ItemId Id="AAIoFt9bAAA=" ChangeKey="AIoulxW"/>
            </t:Message>
          </m:Items>
        </m:CreateItemResponseMessage>
      </m:ResponseMessages>
    </m:CreateItemResponse>
  </s:Body>
</s:Envelope>
```

**Comment by MagedSaeed** [comment]
Thanks for your prompt update and the effort you did. Regarding the response XML I am getting from the server, I sent around 8 emails in bulk mode, and here is what I am getting from the server:

```
<?xml version='1.0' encoding='utf-8'?>
<s:Envelope
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    <h:ServerVersionInfo
    xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15" MinorVersion="0" MajorBuildNumber="1473" MinorBuildNumber="3" Version="V2_23"/>
  </s:Header>
  <s:Body
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <m:CreateItemResponse
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <m:ResponseMessages>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
        <m:CreateItemResponseMessage ResponseClass="Success">
          <m:ResponseCode>NoError</m:ResponseCode>
          <m:Items/>
        </m:CreateItemResponseMessage>
      </m:ResponseMessages>
    </m:CreateItemResponse>
  </s:Body>
</s:Envelope>
```
Since I got the server version and build information, I thought that if I set the version and build manually, the problem might get resolved, but unfortunately, this adds nothing.

What is wired in this response is that the </items> element is empty. There is no `changekey` and item `id` as in your XML response, although the response class is `success`.

**Comment by MagedSaeed** [comment]
after some trials, it seems that this is a version-specific issue. We have, in our organization, two mail servers, one for testing and the other for production. Both have different versions. The production version is `V2017_08_18` where it returns the results with the created items, as expected.

I have a suggestion, for such old versions,  that if the `BulkCreateResult` did not find the `changekey` and the item `id`, it can returns `True` to indicate that the item is created successfully. What do you think?

**Comment by ecederstrand** [comment]
Thanks for the additional investigation! Returning `True` is at least better than no return value at all, when the server does not return any IDs. I'll look at adding this functionality soon.

**Comment by MagedSaeed** [comment]
if you can give me some guidance, I may try to submit a pull request on that.

**Comment by MagedSaeed** [comment]
I guess this is the function that needs to be updated:

https://github.com/ecederstrand/exchangelib/blob/85332f09ffadda2513302a7a413b814a13602cbc/exchangelib/services/create_item.py#L48

Am I right?

**Comment by ecederstrand** [comment]
That would be great! Start by adding a new test case to https://github.com/ecederstrand/exchangelib/blob/master/tests/test_items/test_bulk.py

Since this is specific to the Exchange server version, the test case needs to use a static XML response to insert into `CreateItem`. There's an example of how to do that at https://github.com/ecederstrand/exchangelib/blob/85332f09ffadda2513302a7a413b814a13602cbc/tests/test_items/test_sync.py#L224 Just replace `SendNotification` with `CreateItem`, and let the test case assert as many True's as you have entries in the static XML.

Then you can work on fixing the implementation. In addition to `_elems_to_objs()` you'll probably need to override `_get_elements_in_container()`.

**Comment by MagedSaeed** [comment]
Thanks for that, I will see what I can do and update you accordingly.
