### ISSUE TITLE
How can i create an exceptional occurrence event in recurring events sequence?

### ISSUE THREAD

**Issue by nautics889** [ecederstrand/exchangelib#985]
[According to DAV-format](https://datatracker.ietf.org/doc/html/rfc8607#section-3.3.2) `RECURRENCE-ID` property must be used to create an exceptional occurrence in recurring sequence. Essentially it behaves like a pointer to specific occurrence in original sequence.
I couldn't find any usage either `RECURRENCE-ID` or `RecurrenceId` in sources of `exchangelib`. However as i understand Microsoft Exchange supports corresponding properties and it's documented [here](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/recurrenceid), supposed to be a sub-element of calendar element as explained [here](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/calendaritem) and the item has `FieldURI` described [here](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/fielduri):
>calendar:RecurrenceId | Identifies the RecurrenceId property.

So i decided to extend `CalendarItem` class in the following way:
```
class ExtendedCalendarItem(CalendarItem):
    LOCAL_FIELDS = elib.properties.Fields(
        elib.fields.DateOrDateTimeField(
            'recurrenceid', field_uri='calendar:RecurrenceId', )
    )
    FIELDS = CalendarItem.FIELDS + LOCAL_FIELDS

    __slots__ = tuple(f.name for f in LOCAL_FIELDS)
```
However when i tried `bulk_create()` with instances of my `ExtendedCalendarItem` i got following Traceback:
```
09/28/2021 02:26:48  WARNING  [common.py:255] Account tester@******.net: Exception in _get_elements: Traceback (most recent call last):
  File "/home/ihor/workspace/calendar-sync/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 230, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/ihor/workspace/calendar-sync/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 599, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/ihor/workspace/calendar-sync/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 521, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: FieldURI(field_uri='calendar:RecurrenceId'))
Traceback (most recent call last):
  File "/home/ihor/workspace/calendar-sync/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 230, in _get_elements
    yield from self._response_generator(payload=payload)
  File "/home/ihor/workspace/calendar-sync/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 599, in _get_elements_in_response
    container_or_exc = self._get_element_container(message=msg, name=self.element_container_name)
  File "/home/ihor/workspace/calendar-sync/.venv/lib/python3.8/site-packages/exchangelib/services/common.py", line 521, in _get_element_container
    raise self._get_exception(code=response_code, text=msg_text, msg_xml=msg_xml)
exchangelib.errors.ErrorInvalidPropertySet: Set action is invalid for property. (field: FieldURI(field_uri='calendar:RecurrenceId'))
```
What am i doing wrong?

**Comment by ecederstrand** [comment]
The `ErrorInvalidPropertySet` error raised by the server means that the field is read-only in Exchange.

I agree that `calendar:RecurrenceId` is missing in exchangelib and should be implemented.

If you want to create recurring calendar items, and modify certain occurrences, have a look at the examples in https://ecederstrand.github.io/exchangelib/#recurring-calendar-items.

**Comment by nautics889** [comment]
Thanks a lot for help, the example you posted has worked correctly. I saw you already have added changes with `recurrence_id`, so i guess the issue is fully resolved.
