### ISSUE TITLE
attachment.fp is not a proper BytesIO

### ISSUE THREAD

**Issue by thrasibule** [ecederstrand/exchangelib#986]
**Describe the bug**
the fp property on an attachment is not a proper BytesIO even if it subclasses it, only the read method does something useful. This prevents using it with python functions which use a buffer.

**To Reproduce**
```python
a = Account
for item in a.inbox.all():
    for attachment in item.attachments:
        if isinstance(attachment, FileAttachment):
            with attachment.fp as buf:
                text = TextIOWrapper(buf)
                for line in text:
                      print(line) # this will be empty
```
If applicable, add the shortest possible script that reproduces the error.

**Expected behavior**
I expect to be able to write code like so:

```python

import csv
with attachment.fp as buf:
      reader = csv.reader(fp)
      headers = next(reader)
      for line in reader:
            print(line)
```

**Log output**
If applicable, add relevant output from [debug logging](https://ecederstrand.github.io/exchangelib/#troubleshooting) .

**Additional context**
For example, Python and exchangelib versions.

**Comment by ecederstrand** [comment]
Thanks for filing an issue on this, and thanks for the contribution! I added some small review comments on the PR. Looks good, overall.

**Comment by thrasibule** [comment]
Thanks for considering it! I don't see the review comments in the PR unfortunately. Maybe I'm looking in the wrong place, can you point me to the right place?

**Comment by ecederstrand** [comment]
Ah, the review was in a pending state. Do you see it now?

**Comment by thrasibule** [comment]
I do now, thanks. I've made the changes. Please let me know if I should squash the commits.

**Comment by ecederstrand** [comment]
Thanks a bunch for the contribution!
