### ISSUE TITLE
Need to find unique identifier to identify mail thread between 2 mailboxes

### ISSUE THREAD

**Issue by ahalyarekha** [ecederstrand/exchangelib#995]
Hi,

I have a scenario to identify unique identifier with in mailboxes to identify email thread.
Initially thought conversion_id would remain same across the mailboxes. With in the same conversation i.e. email thread, conversation_id with respect to one mailbox remains same. When I read the second mailbox for same mail thread the conversion_id is different. 

Please provide a proper solution to identify the mail thread across mailboxes.

**Comment by ecederstrand** [comment]
I'm not sure that's possible. I don't know the guarantees of the `conversion_id` field, but it's possible that it's only useful within a single mailbox.

You may have luck using some of the email headers available in `Message.headers`

**Comment by ecederstrand** [comment]
@ahalyarekha Did you find a solution to your issue?
