### ISSUE TITLE
Not all mails are read from shared mail box

### ISSUE THREAD

**Issue by ConMan05** [ecederstrand/exchangelib#996]
**Describe the bug**
I'm trying to read mails from a particular date but it's not reading all the mails from particular date and it dosen't throw an error
For eg: There are 315 mails from 01.10.2021 but it reads 199 mails only

**Expected behavior**
It should read all mails for the given date

**Code I Use**
```
utc = EWSTimeZone('UTC')
credentials = Credentials(conman@myorg.com, password)
config = Configuration(server='outlook.office365.com', credentials=credentials)
shared_account = Account('sharedmailbox@myorg.com', config=config, autodiscover=False, access_type=DELEGATE, default_timezone=utc)
start = datetime(start_Year,start_Month,start_Date, tzinfo=shared_account.default_timezone)
end = start + timedelta(days=1)
fetch_condition = shared_account.inbox.filter(is_read=False,datetime_received__gte=start,datetime_received__lt=end)
for msg in fetch_condition:
            msg.is_read=True
            msg.save()
            #Below this I'm using some tasks which can take upto some seconds
```

**Additional context**
Python Version - 3.8.10
Exchangelib Version - 4.5.1
OS - ubuntu 20.04.2 LTS

**Comment by ecederstrand** [comment]
You are changing the emails covered by your queryset while iterating over the queryset. Since exchangelib internally uses paging to not get all items at once, the paging may get messed up. Just like in Python where changing a list while iterating over it may lead to unexpected results.

Instead, you can get all items up front and then change them:

```python
items = list(rates_uat_account.inbox.filter(...))
for item in items:
    msg.is_read = True
    msg.save()
```
